### ISSUE TITLE
Outdated indexes notice persistence, even after running rethinkdb index-rebuild

### ISSUE THREAD

**Issue by nodesocket** [rethinkdb/rethinkdb#4682] opened 2015-08-13 02:55 UTC
Just updated to `2.1.0-1` and was prompted with:

![screen shot 2015-08-12 at 7 53 37 pm](https://cloud.githubusercontent.com/assets/523312/9241707/d540fd52-412b-11e5-973a-03dbaf3153ea.png)

So after doing `pip install rethinkdb` and running `rethinkdb index-rebuild` on one of the servers it still shows this error, even after hours.

Anything I am missing?

**Comment by danielmewes** [comment] 2015-08-13 03:04
Hi @nodesocket , thanks for the report. Can you try restarting the server?
This is probably a duplicate of https://github.com/rethinkdb/rethinkdb/issues/4664 .

**Comment by nodesocket** [comment] 2015-08-13 03:15
Upgrading to `2.1.1` and doing a restart fixed this. Wow, you must have released another version today, since I did the update to `2.1.0-1` this morning.

**Comment by danielmewes** [comment] 2015-08-13 03:20
Glad that resolved it. Closing as a duplicate.

**Closed by danielmewes** 2015-08-13 03:20 UTC
