### ISSUE TITLE
RethinkDB Stats

### ISSUE THREAD

**Issue by mariostallone** [rethinkdb/rethinkdb#5028] opened 2015-10-31 14:11 UTC
Not sure where I could ask this, hence opening an issue.

I had a look at the system stats table, and they're very detailed.
I would like to pump these statistics to statsd, so that I can visualize the cluster's performance over a period of time.

Questions.
- Do I need to look at an external system such as statsd to do this?
- Does rethinkdb keep historic data for these statistics?
- Has anyone written a plugin to push statistics to statsd from rethinkdb?

**Comment by ConnorJarvis** [comment] 2015-11-02 02:00
https://github.com/influxdb/telegraf has support for pulling stats from RethinkDB and pushing them to backends in the same manner as statsd.

**Comment by danielmewes** [comment] 2016-01-16 02:08
Going to close this since it's not a bug. I think @ConnorJarvis ' suggestion is the best option at the moment (RethinkDB itself does not keep historic statistics).

**Closed by danielmewes** 2016-01-16 02:08 UTC
