### ISSUE TITLE
Enforce order in result.changes for batch insert?

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#3853] opened 2015-02-28 03:29 UTC
So if I do
```
r.table('test').insert([
  {id: 1},
  {id: 2},
  {id: 3},
  {id: 4}
]).run()
```

In `result.changes`, I may not get the same order (I may get `4, 1, 3, 2` and not `1, 2, 3, 4`). Would it be possible to enforce the order of `changes` on the server?

**Comment by danielmewes** [comment] 2015-02-28 05:50
That sounds difficult since those inserts can be routed to different shards and part of the performance benefit of batched inserts comes from the fact that they do not have to be serialized but can be processed in any order.

Do you have a specific use case in mind for which this matters?

**Comment by neumino** [comment] 2015-02-28 06:00
So with thinky I let people do batch inserts:

```js
Model.save([doc1, doc2, doc3]).run()
// ~= r.table('data').insert(doc1, doc2, doc3, {returnChanges: true})
```

Once the query comes back, I create instances of the model using what is in `changes`. Since it doesn't come back in the same order, I may return `[doc2, doc3, doc1]` which is not super friendly.

The current field `generated_keys` enforce an order if I'm not mistaken so maybe the server could use that? While it would be nice for thinky, no one complained so far (or no complains reached me ^_^) so I guess it's not that important.

Also Slightly related to https://github.com/rethinkdb/rethinkdb/issues/3074.

**Comment by danielmewes** [comment] 2015-03-02 22:37
Oh sorry I thought you were talking about changefeeds.

Returning `changes` in the same order as the input sounds reasonable.

**Comment by mlucy** [comment] 2015-03-03 01:04
It's a little harder because we generate the keys on the parsing node but the changes are calculated on the shards, so we'll have to re-order them once we get them back.  But it should be perfectly doable since the primary key is preserved.

**Comment by danielmewes** [comment] 2015-12-03 01:31
Marking as a duplicate of https://github.com/rethinkdb/rethinkdb/issues/5041

**Closed by danielmewes** 2015-12-03 01:31 UTC
Labels: cp:reql
