### ISSUE TITLE
error in 2.3.1 testing in interface.artificial_table:polyglot/mutation/insert.py2.6

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5711] opened 2016-04-22 21:34 UTC
In the testing for `v2.3.1` I ran into this error in the `polyglot/mutation/insert.py2.6` subtest for `interface.artificial_table` on `the-shadow`. The exact same binary did not produce this error on our other MacOS X tester.
```
TEST FAILURE: line 159
    FAILURE:  unmatched keys from either side: set(['first_error'])
    SOURCE:   'tbl.insert([{\'id\':666}, {\'id\':666}], return_changes="always")'
    EXPECTED: {'changes': [{'new_val': {'id': 666}, 'old_val': None},
                           {'error': 'Duplicate primary key `id`:\n{\n\t"id":\t666\n}\n{\n\t"id":\t666\n}',
                            'new_val': {'id': 666},
                            'old_val': {'id': 666}}],
               'deleted': 0,
               'errors': 1,
               'first_error': 'Duplicate primary key `id`:\n{\n\t"id":\t666\n}\n{\n\t"id":\t666\n}',
               'inserted': 1,
               'replaced': 0,
               'skipped': 0,
               'unchanged': 0}
    RESULT:   {'changes': [{'new_val': {'id': 666}, 'old_val': None}, {'new_val': {'id': 666}, 'old_val': None}],
               'deleted': 0,
               'errors': 0,
               'inserted': 2,
               'replaced': 0,
               'skipped': 0,
               'unchanged': 0}
```

**Comment by danielmewes** [comment] 2016-04-22 21:39
This might have something to do with the _debug_scratch table, or it might be a race condition that's only exposed when using that table (and apparently only on some machines).

Pining @nighelles , since it's at least indirectly related to the new insert functionality. Though the real issue might be somewhere else...

**Comment by larkost** [comment] 2016-04-22 22:19
This also happened on my local machine, so 2 out of 3 MacOS testers.

**Comment by nighelles** [comment] 2016-04-23 01:24
Is there a particular way to reproduce this?

**Comment by larkost** [comment] 2016-04-25 17:04
Unfortunately, no. I have not been able to reproduce it during a solo run. It has only happened during bigger runs, and so far I have only seen it on those two machines. That makes it likely that this is going to be a nasty timing issue.

**Comment by nighelles** [comment] 2016-04-26 22:44
This is really odd, if it's in the artificial table, then it's just writing to memory, @danielmewes is there something in particular about the _debug_scratch table that could cause a timing issue?

**Comment by nighelles** [comment] 2016-04-27 02:07
This is fixed in next.

**Closed** 2016-04-27 02:20 UTC
Labels: tp:bug
