### ISSUE TITLE
writes during index creation completely degenerates system performance

### ISSUE THREAD

**Issue by digi604** [rethinkdb/rethinkdb#4137] opened 2015-04-28 13:35 UTC
5m rows, creating 10 indexes simultaneously gives me about 8k reads/writes /s. As soon as i start writing data to the table the whole system becomes unresponsive, read/writes drop to 200-500.

**Comment by danielmewes** [comment] 2015-04-28 19:18
Hi @digi604, sorry you're running into this problem.
Just to make sure I understand:
- you started constructing 10 indexes (all on one table? multiple tables?)
- overall throughput of the index constructions was around 8k reads + 8k writes
- then you ran some write queries other than the index construction
- reads and writes become much slower

Is this correct?

A few questions: When you talk about read/writes dropping to 200-500, do you mean the secondary index reads/writes? Or is this number from separate queries that you are running?
Are the writes you are doing also slow?

Secondary index construction generally runs at a pretty low priority, so it's expected that it's throughput decreases if there is other load on the server.

That being said write queries definitely have additional overhead while secondary index construction is proceeding, especially towards the end of the construction (we are working on fixing that, but it's a bigger project and it hasn't made it in yet, see https://github.com/rethinkdb/rethinkdb/issues/2134 )


What is the hardware you are using? Are you using rotational HDDs or SSDs?

**Comment by digi604** [comment] 2015-04-29 08:38
10 indexes on one table. OSX with SSD. The table read/writes are 8k/s before i start to write... as soon as i start to write it drops to 200-500 and the whole OS becomes very clunky and unresponsive. Chrome takes 10s of seconds to respond to mouse input etc.

**Comment by digi604** [comment] 2015-04-29 08:38
the write queries time out after 300s... etc.

**Comment by danielmewes** [comment] 2015-04-29 16:11
@digi604 Thanks for the information.
Can you check if your system is going into swap, and how much memory RethinkDB is using?
That would explain the degradation in overall system performance and the queries timing out.

What sort of write queries are you running? Do you have an example?

**Comment by digi604** [comment] 2015-04-30 09:00
no swap and uses about 10gb of ram. They are batch writes (200-10'000 a batch... played with the batch size but does not have a big impact (i think)

**Comment by danielmewes** [comment] 2015-04-30 21:04
Weird. I'm not sure what else could cause other programs on the system to become unresponsive.
Could it be that it's only going into swap while you're running the insert query?

@digi604 What do the documents look like that you're inserting? What is their average size, and do they have any nested arrays or objects?
Is there a chance you could post an example document?
A batch size of 10,000 might be a bit much, but 200 generally sounds reasonable.

My only other guess for the impact on other processes would be the i/o scheduler getting overwhelmed by the many concurrent i/o transactions that RethinkDB performs...

@digi604 You can try running RethinkDB with the `--io-threads 8` option. If i/o contention is the issue, that will likely reduce RethinkDB's impact on the rest of the system.
It wouldn't explain why RethinkDB itself gets so slow though.

**Comment by danielmewes** [comment] 2015-06-02 03:04
@digi604 Any luck with `--io-threads 8` or smaller batch sizes?

**Comment by digi604** [comment] 2015-06-02 13:32
sorry i gave up on rethinkdb for the moment...

**Comment by danielmewes** [comment] 2015-06-03 00:55
@digi604 I understand. Sorry it hasn't been working out for you. Thanks for your feedback though.

(I'm closing this because we don't currently have enough information to reproduce this, but we should re-open the issue once we see this again).

**Closed by danielmewes** 2015-06-03 00:55 UTC
Labels: tp:performance
