### ISSUE TITLE
Upgrading 2.2.3 -> 2.3.3 crash

### ISSUE THREAD

**Issue by tatsujin1** [rethinkdb/rethinkdb#5824] opened 2016-06-03 07:30 UTC
```
2016-06-03T09:23:12.607110611 54.249556s error: Error in src/arch/runtime/thread_pool.cc at line 367:
2016-06-03T09:23:12.607196722 54.249641s error: Segmentation fault from reading the address 0x8.
2016-06-03T09:23:12.607216709 54.249661s error: Backtrace:
2016-06-03T09:23:12.988233093 54.630681s error: Fri Jun  3 09:23:12 2016

1 [0xae4ea0]: backtrace_t::backtrace_t() at ??:?
2 [0xae5219]: format_backtrace(bool) at ??:?
3 [0xd9b053]: report_fatal_error(char const*, int, char const*, ...) at ??:?
4 [0x9ee474]: linux_thread_pool_t::fatal_signal_handler(int, siginfo_t*, void*) at ??:?
5 [0x7fdbe20ed8d0]: /lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0) [0x7fdbe20ed8d0] at 0x7fdbe20ed8d0 (/lib/x86_64-linux-gnu/libpthread.so.0)
6 [0xa506e0]: shared_buf_t::size() const at ??:?
7 [0x97ab4c]: ql::datum_get_array_size(shared_buf_ref_t<char> const&) at ??:?
8 [0x921930]: ql::datum_t::obj_size() const at ??:?
9 [0x921ba1]: /usr/bin/rethinkdb() [0x921ba1] at 0x921ba1 ()
10 [0x921cd0]: ql::datum_t::is_ptype() const at ??:?
11 [0x92767c]: ql::datum_t::cmp_unchecked_stack(ql::datum_t const&) const at ??:?
12 [0x927d17]: /usr/bin/rethinkdb() [0x927d17] at 0x927d17 ()
13 [0x927eb5]: ql::datum_t::operator==(ql::datum_t const&) const at ??:?
14 [0x8f64b2]: ql::changefeed::index_queue_t<std::string, ql::datum_t, ql::datum_t, ql::changefeed::limit_order_t>::insert(std::pair<std::string, std::pair<ql::datum_t, ql::datum_t> >) at ??:?
15 [0x8e1eee]: ql::changefeed::limit_manager_t::commit(rwlock_in_line_t*, boost::variant<ql::changefeed::primary_ref_t, ql::changefeed::sindex_ref_t, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) at ??:?
16 [0x7f1782]: /usr/bin/rethinkdb() [0x7f1782] at 0x7f1782 ()
17 [0x8dce2d]: ql::changefeed::server_t::foreach_limit(boost::optional<std::string> const&, store_key_t const*, std::function<void (rwlock_in_line_t*, rwlock_in_line_t*, rwlock_in_line_t*, ql::changefeed::limit_manager_t*)>, auto_drainer_t::lock_t const&) at ??:?
18 [0x7f2ec5]: rdb_update_single_sindex(store_t*, store_t::sindex_access_t const*, deletion_context_t const*, rdb_modification_report_t const*, unsigned long*, auto_drainer_t::lock_t, cond_t*, std::vector<std::pair<ql::datum_t, std::string>, std::allocator<std::pair<ql::datum_t, std::string> > >*, std::vector<std::pair<ql::datum_t, std::string>, std::allocator<std::pair<ql::datum_t, std::string> > >*) at ??:?
19 [0x7fbdb9]: callable_action_instance_t<std::_Bind<void (*(store_t*, store_t::sindex_access_t*, deletion_context_t const*, rdb_modification_report_t const*, unsigned long*, auto_drainer_t::lock_t, cond_t*, std::vector<std::pair<ql::datum_t, std::string>, std::allocator<std::pair<ql::datum_t, std::string> > >*, std::vector<std::pair<ql::datum_t, std::string>, std::allocator<std::pair<ql::datum_t, std::string> > >*))(store_t*, store_t::sindex_access_t const*, deletion_context_t const*, rdb_modification_report_t const*, unsigned long*, auto_drainer_t::lock_t, cond_t*, std::vector<std::pair<ql::datum_t, std::string>, std::allocator<std::pair<ql::datum_t, std::string> > >*, std::vector<std::pair<ql::datum_t, std::string>, std::allocator<std::pair<ql::datum_t, std::string> > >*)> >::run_action() at ??:?
20 [0x9f0e67]: coro_t::run() at ??:?

2016-06-03T09:23:12.988455579 54.630900s error: Exiting.
```

After downgrading to 2.3.2 it seems to work fine.

**Comment by OmerCora** [comment] 2016-06-03 12:22
Getting the same error after pulling the latest version this morning. 
node exits with illegal instruction

**Comment by tatsujin1** [comment] 2016-06-03 13:14
I got it almost immediately, I think it crashed on the first changefeed I sent to the server. Details available upon request :)

**Comment by danielmewes** [comment] 2016-06-03 16:53
@tatsujin1 or @OmerCora: Do you know the complete changefeed query that causes this (once a write happens)? It's probably some kind of `orderBy.limit` changefeed.

**Comment by danielmewes** [comment] 2016-06-03 16:56
@tatsujin1 Another question: Which Linux distribution / version was this on?

**Comment by tatsujin1** [comment] 2016-06-03 17:07
Sorry, at the moment I can't get to it.

However, the query was quite simple; a `.get_all` followed by a few `filter()`.

It's possible that their also was another query (it's not logged), but that is also without ordering, just a `.distinct(index=...).count()`.

On Fri, Jun 03, 2016 at 6:55 PM, Daniel Mewes <notifications@github.com<mailto:notifications@github.com>> wrote:


@tatsujin1<https://github.com/tatsujin1> or @OmerCora<https://github.com/OmerCora>: Do you know the complete changefeed query that causes this (once a write happens)? It's probably some kind of orderBy.limit changefeed.

-

**Comment by danielmewes** [comment] 2016-06-03 21:18
A likely fix for this is in commit https://github.com/rethinkdb/rethinkdb/commit/6c8960298eecb962e67eac5fd00a24eb05ff4877, and internal review 3656.

Thanks for reporting the issue and sorry you had to run into this!

**Comment by danielmewes** [comment] 2016-06-03 21:43
@tatsujin1 @OmerCora Are you using the official packages or did you compile from source?

**Comment by danielmewes** [comment] 2016-06-03 22:36
Never mind that question. I've been able to reproduce the bug now.

The reason our tests didn't catch this is that it doesn't happen if the secondary index used in an `orderBy.limit` changefeed has only numbers as key values. Most of our tests use numbers as keys because they are convenient to generate...

**Comment by danielmewes** [comment] 2016-06-03 23:03
Fixed in v2.3.x via 9ac7f62 and next via 79dbfde.

**Closed by danielmewes** 2016-06-03 23:03 UTC
Labels: pr:high, tp:bug

**Comment by danielmewes** [comment] 2016-06-04 06:31
@tatsujin1 @OmerCora New packages for RethinkDB 2.3.4 are now available in the repository. Please let us know if there's still any issue.

**Comment by tatsujin1** [comment] 2016-06-04 07:35
Swift fixing there! 😉
I won't be able to test it until end of next week, though.

**Comment by tatsujin1** [comment] 2016-06-08 15:47
Works just fine!
