### ISSUE TITLE
Building 2.1 beta on Raspberry Pi 2 fails

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/rethinkdb#4541] opened 2015-07-16 20:16 UTC
Just tried building 2.1 beta from source on a Raspberry Pi 2

```
pi@dalanmiller-pi ~/rethinkdb-2.1.0-0BETA1 $ sudo ./configure --with-system-malloc --allow-fetch
* Reading arguments from 'configure.default'
* Prepending the following arguments: --fetch re2 --fetch gtest --fetch v8
* Detecting system configuration
Bash:                           4.2.37(1)-release
Use ccache:                     no
C++ Compiler:                   GCC 4.6.3 (/usr/bin/c++)
Host System:                    arm-linux-gnueabihf
Build System:                   Linux 4.0.6-v7+ armv7l
Cross-compiling:                no
Host Operating System:          Linux
Build Architecture:             armv7l
C++11:                          ok
Precompiled web assets:         yes
Protobuf compiler:              /usr/bin/protoc
python:                         python 2.7.3
Node.js package manager:        external/node_0.12.2
coffee:                         external/coffee-script_1.7.1
Browserify:                     external/browserify_3.24.13
bluebird:                       external/bluebird_2.9.32
web UI dependencies:            external/admin-deps_2.0.3
wget:                           /usr/bin/wget
curl:                           /usr/bin/curl
Google Test:                    external/gtest_1.6.0
termcap:                        no
boost_system:                   external/boost_1.56.0
ssl:                            -lssl
protobuf:                       -lprotobuf
icui18n:                        external/icu_54.1
icuuc:                          external/icu_54.1
icudata:                        external/icu_54.1
v8 javascript engine:           external/v8_3.30.33.16
RE2:                            external/re2_20140111
z:                              -lz
crypto:                         -lcrypto
curl:                           external/curl_7.40.0
malloc:                         system
Test protobuf:                  ok
Test boost:                     ok
Installation prefix:            /usr/local
Configuration prefix:           /usr/local/etc
Runtime data prefix:            /usr/local/var
* Warning: ARM support is still experimental
* Wrote configuration to config.mk
```

```
pi@dalanmiller-pi ~/rethinkdb-2.1.0-0BETA1 $ make
    [1/405] CP build/web_assets
    [2/405] GENERATE build/release_system/web_assets/web_assets.cc
    [3/405] INSTALL-INCLUDE gtest_1.6.0
    [4/405] CC build/release_system/obj/web_assets/web_assets.o
    [5/405] PROTOC[CPP] src/rdb_protocol/ql2.proto
    [6/405] PROTOC[CPP] src/rdb_protocol/ql2_extensions.proto
    [7/405] CC build/release_system/obj/rdb_protocol/ql2.pb.o
    [8/405] CC build/release_system/obj/rdb_protocol/ql2_extensions.pb.o
    [9/405] INSTALL-INCLUDE re2_20140111
    [10/405] INSTALL-INCLUDE v8_3.30.33.16
    [11/405] FETCH curl_7.40.0
    [12/405] INSTALL-INCLUDE curl_7.40.0
    [13/405] FETCH icu_54.1
    [14/405] INSTALL-INCLUDE icu_54.1
    [15/405] CC build/release_system/obj/activity_logger.o
    [16/405] CC build/release_system/obj/perfmon/core.o
    [17/405] CC build/release_system/obj/perfmon/filter.o
    [18/405] CC build/release_system/obj/perfmon/collect.o
    [19/405] CC build/release_system/obj/perfmon/perfmon.o
    [20/405] CC build/release_system/obj/rdb_protocol/validate.o
    [21/405] CC build/release_system/obj/rdb_protocol/val.o
    [22/405] CC build/release_system/obj/rdb_protocol/datum.o
In file included from ./src/rdb_protocol/datum.hpp:24:0,
                 from src/rdb_protocol/datum.cc:2:
./src/rapidjson/writer.h: In member function ‘bool rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::WriteString(const Ch*, rapidjson::SizeType) [with OutputStream = rapidjson::GenericStringBuffer<rapidjson::UTF8<> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::Ch = char, rapidjson::SizeType = unsigned int]’:
./src/rapidjson/prettywriter.h:82:45:   instantiated from ‘bool rapidjson::PrettyWriter<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::String(const Ch*, rapidjson::SizeType, bool) [with OutputStream = rapidjson::GenericStringBuffer<rapidjson::UTF8<> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::PrettyWriter<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::Ch = char, rapidjson::SizeType = unsigned int]’
src/rdb_protocol/datum.cc:1406:17:   instantiated from ‘void ql::datum_t::write_json(json_writer_t*) const [with json_writer_t = rapidjson::PrettyWriter<rapidjson::GenericStringBuffer<rapidjson::UTF8<> > >]’
src/rdb_protocol/datum.cc:594:31:   instantiated from here
./src/rapidjson/writer.h:309:18: error: comparison is always true due to limited range of data type [-Werror=type-limits]
In file included from ./src/rapidjson/document.h:26:0,
                 from ./src/rdb_protocol/datum.hpp:22,
                 from src/rdb_protocol/datum.cc:2:
./src/rapidjson/reader.h: In member function ‘rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Token rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Tokenize(rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Ch) [with SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::MemoryPoolAllocator<>, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Ch = char]’:
./src/rapidjson/reader.h:1410:41:   instantiated from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParse(InputStream&, Handler&) [with unsigned int parseFlags = 16u, InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::MemoryPoolAllocator<>]’
./src/rapidjson/reader.h:405:58:   instantiated from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 16u, InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::MemoryPoolAllocator<>]’
./src/rapidjson/document.h:1703:9:   instantiated from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 16u, SourceEncoding = rapidjson::UTF8<>, InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >]’
./src/rapidjson/document.h:1779:57:   instantiated from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Parse(const Ch*) [with unsigned int parseFlags = 16u, SourceEncoding = rapidjson::UTF8<>, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
./src/rapidjson/document.h:1788:47:   instantiated from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Parse(const Ch*) [with unsigned int parseFlags = 16u, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
./src/rapidjson/document.h:1795:45:   instantiated from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Parse(const Ch*) [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
src/rdb_protocol/datum.cc:1677:42:   instantiated from here
./src/rapidjson/reader.h:1069:9: error: comparison is always true due to limited range of data type [-Werror=type-limits]
./src/rapidjson/reader.h: In member function ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseStringToStream(InputStream&, OutputStream&) [with unsigned int parseFlags = 16u, SEncoding = rapidjson::UTF8<>, TEncoding = rapidjson::UTF8<>, InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, OutputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::MemoryPoolAllocator<>]’:
./src/rapidjson/reader.h:654:13:   instantiated from ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseString(InputStream&, Handler&, bool) [with unsigned int parseFlags = 16u, InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::MemoryPoolAllocator<>]’
./src/rapidjson/reader.h:993:23:   instantiated from ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseValue(InputStream&, Handler&) [with unsigned int parseFlags = 16u, InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::MemoryPoolAllocator<>]’
./src/rapidjson/reader.h:418:13:   instantiated from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 16u, InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::MemoryPoolAllocator<>]’
./src/rapidjson/document.h:1703:9:   instantiated from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 16u, SourceEncoding = rapidjson::UTF8<>, InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >]’
./src/rapidjson/document.h:1779:57:   instantiated from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Parse(const Ch*) [with unsigned int parseFlags = 16u, SourceEncoding = rapidjson::UTF8<>, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
./src/rapidjson/document.h:1788:47:   instantiated from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Parse(const Ch*) [with unsigned int parseFlags = 16u, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
./src/rapidjson/document.h:1795:45:   instantiated from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Parse(const Ch*) [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
src/rdb_protocol/datum.cc:1677:42:   instantiated from here
./src/rapidjson/reader.h:697:17: error: comparison is always true due to limited range of data type [-Werror=type-limits]
./src/rapidjson/reader.h: In member function ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseStringToStream(InputStream&, OutputStream&) [with unsigned int parseFlags = 16u, SEncoding = rapidjson::UTF8<>, TEncoding = rapidjson::UTF8<>, InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, OutputStream = rapidjson::GenericReader<rapidjson::UTF8<>, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >::StackStream<char>, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::MemoryPoolAllocator<>]’:
./src/rapidjson/reader.h:663:13:   instantiated from ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseString(InputStream&, Handler&, bool) [with unsigned int parseFlags = 16u, InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::MemoryPoolAllocator<>]’
./src/rapidjson/reader.h:993:23:   instantiated from ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseValue(InputStream&, Handler&) [with unsigned int parseFlags = 16u, InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::MemoryPoolAllocator<>]’
./src/rapidjson/reader.h:418:13:   instantiated from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 16u, InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::MemoryPoolAllocator<>]’
./src/rapidjson/document.h:1703:9:   instantiated from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 16u, SourceEncoding = rapidjson::UTF8<>, InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >]’
./src/rapidjson/document.h:1779:57:   instantiated from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Parse(const Ch*) [with unsigned int parseFlags = 16u, SourceEncoding = rapidjson::UTF8<>, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
./src/rapidjson/document.h:1788:47:   instantiated from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Parse(const Ch*) [with unsigned int parseFlags = 16u, Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
./src/rapidjson/document.h:1795:45:   instantiated from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Parse(const Ch*) [with Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >, rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
src/rdb_protocol/datum.cc:1677:42:   instantiated from here
./src/rapidjson/reader.h:697:17: error: comparison is always true due to limited range of data type [-Werror=type-limits]
cc1plus: all warnings being treated as errors
src/build.mk:401: recipe for target 'build/release_system/obj/rdb_protocol/datum.o' failed
make[1]: *** [build/release_system/obj/rdb_protocol/datum.o] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
```

**Comment by danielmewes** [comment] 2015-07-16 20:31
Ah that should be pretty easy to fix.
As a work around, you can try
`make ALLOW_WARNINGS=1` again.

**Comment by dalanmiller** [comment] 2015-07-21 00:09
Works just fine using `ALLOW_WARNINGS=1`. 

There's probably some flags we should add to the documentation to speed this up on the Raspberry Pi [2]

**Comment by danielmewes** [comment] 2015-07-21 00:13
I think we should still fix this one. It looks like a hygiene issue in the code.

**Comment by danielmewes** [comment] 2015-08-01 00:21
These warnings are really stupid by the way.

They are in lines that look like this:
```
if (sizeof(Ch) == 1 || unsigned(c) < 256)
```

`Ch` is a template argument, and in this case it happens to be `char`. The comparison that the warnings talks about isn't even executed in that case, since the `sizeof(Ch)` will be `true` already.

Maybe the fact that it complains on ARM but not on AMD64 is because `char` is unsigned on ARM?

**Comment by extrabee** [comment] 2015-08-20 03:53
@danielmewes: Thanks for the tip - helped me to build on Raspbian! +1

**Comment by mogren** [comment] 2015-09-07 09:01
Yes, `ALLOW_WARNINGS=1` was needed for both `make` and `sudo make install`, but now I have rethinkdb 2.1.3 on my RPI2! Should be added to the wiki maybe? http://rethinkdb.com/docs/install/raspbian/

**Comment by danielmewes** [comment] 2015-09-08 17:59
@mogren Good idea. I opened a pull request https://github.com/rethinkdb/docs/pull/886

**Comment by dalanmiller** [comment] 2015-09-08 18:05
What's interesting is that this may only be necessary for ARM7 but not ARM6 since the first two Raspberry Pis didn't seem to have this issue.

**Comment by danielmewes** [comment] 2015-09-08 18:27
Interesting. In any case, the `ALLOW_WARNINGS=1` flag shouldn't hurt.

**Comment by mogren** [comment] 2015-09-08 18:51
I do have a raspberry pi B+ too, I can try building for that one too. Takes a while though, should time it.

**Comment by dalanmiller** [comment] 2015-09-08 19:11
@mogren Can you try with and without `ALLOW_WARNINGS=1` ?

**Comment by mogren** [comment] 2015-09-08 22:14
I'll start one now without `ALLOW_WARNINGS=1` and time it. If it fails I'll try with the flag set.

**Comment by mogren** [comment] 2015-09-08 22:24
The old pi is using an older kernel:
Linux raspberrypi 3.12.19+ #681 PREEMPT Fri May 9 16:36:10 BST 2014 armv6l GNU/Linux

The RPI2 is:
Linux ingela 4.1.6-v7+ #810 SMP PREEMPT Tue Aug 18 15:32:12 BST 2015 armv7l GNU/Linux

I'll time both so that estimated build times can be added to the wiki page.

**Comment by mogren** [comment] 2015-09-09 07:03
On the RPI2, `time make ALLOW_WARNINGS=1` took 5:35:08.54 total, but I had only done `make clean` first, so the protobuffers were already built. Guess around 6h otherwise. 

Building on the old raspberrypi B+ failed after 1.5 h:

    [87/416] CC build/release_system/obj/arch/types.o
    [88/416] CC build/release_system/obj/rdb_protocol/protocol.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
src/build.mk:401: recipe for target 'build/release_system/obj/rdb_protocol/protocol.o' failed
make[1]: *** [build/release_system/obj/rdb_protocol/protocol.o] Error 4
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
make  4100.40s user 360.35s system 75% cpu 1:38:26.91 total

Maybe I need to increase swap or something. There was no other programs running on that pi while compiling.

**Comment by dalanmiller** [comment] 2015-09-10 19:11
@mogren Before the snippet in your most recent comment, can you scroll back and find if it said "`virtual memory exhausted`"?

**Comment by mogren** [comment] 2015-09-10 19:56
@dalanmiller Checked the log, no errors before that c++ internal compiler error. All looked fine, no memory error. 

Don't think I had anything running, except that the build was done in a screen:ed zsh. I had lowered the stacksize `ulimit -s 1024` to build go 1.5.1, so I guess that caused it. (The RPI B+ still has 8192).

**Comment by danielmewes** [comment] 2015-12-02 02:35
A fix for this is in CR 3378.

The fix simply disables the particular compiler warning in the affected files. The problem is that the comparison that the compiler complains about only makes sense for particular template instantiations, and evaluates to constant `true` for others. We could change the code to account for that rather than locally disabling the warning, but I think it's not worth the trouble.

**Comment by danielmewes** [comment] 2015-12-04 19:22
Fixed in `next` 692a94387c97c77e8d3881658d6a1b29a96b14d9 and `v2.2.x` 361b7f2

**Closed by danielmewes** 2015-12-04 19:22 UTC
Labels: cp:build, tp:hygiene

**Comment by SergKhachko** [comment] 2016-04-07 10:55
For cases like `recipe for target 'build/release_system/obj/rdb_protocol/protocol.o' failed`
Successfully continued to "make" after swap enabling in Raspberry Pi 3.
`sudo apt-get install dphys-swapfile`

**Comment by 360disrupt** [comment] 2016-04-11 08:19
@SergKhachko do you need to do anything else than:
- `sudo nano /etc/dphys-swapfile`
- `CONF_SWAPFILE=1000`
- `sudo reboot`
- `free -m` => shows then the new swap size

e.g. use the `setup` command:
http://manpages.ubuntu.com/manpages/trusty/man8/dphys-swapfile.8.html
or is it fine with the above steps?

**Comment by SergKhachko** [comment] 2016-04-11 09:04
@360disrupt only dphys-swapfile installation needed, no configuring required.
For my case, there was an issue with RAM (no free ram during build process), so I've decided to enable swap in my Ubuntu Mate for RPi3.

**Comment by jbhatab** [comment] 2016-04-18 19:29
I'm running the commands here, https://rethinkdb.com/docs/install/raspbian/, which seem to be up to date with this conversation but still am having errors when running "make ALLOW_WARNINGS=1"

![screen shot 2016-04-18 at 2 27 51 pm](https://cloud.githubusercontent.com/assets/2458718/14616936/d8f7b462-0571-11e6-8aad-06c297900840.png)

@SergKhachko I ran that install but I already had it actually. Didn't seem to effect anything.

**Comment by SergKhachko** [comment] 2016-04-18 19:34
@jbhatab the same exception was throwed for me too. Just increase the swap size to avoid process killing.

**Comment by jbhatab** [comment] 2016-04-18 20:04
@SergKhachko I saw "CONF_SWAPSIZE=100", but no "CONF_SWAPFILE". Am I supposed to update the conf_swapsize or add in the conf_swapfile key?

**Comment by jbhatab** [comment] 2016-04-18 21:23
I'm getting a new bug it looks like. no space left on device.

![screen shot 2016-04-18 at 4 22 39 pm](https://cloud.githubusercontent.com/assets/2458718/14620358/d1ee7a6a-0581-11e6-925b-700279ce23ba.png)

**Comment by SergKhachko** [comment] 2016-04-19 08:02
@jbhatab seems like your SDcard is too small. Anyway, I have a deb package already built. Try to download [this](https://mega.nz/#!2lhxAK4D!u1wd35qila167d2YxCfCIfFHM044rB8RTEgUCnQL6sQ) and instal as `sudo dpkg -i rethinkdb_2.3_armhf.deb`

**Comment by 360disrupt** [comment] 2016-04-19 17:33
Maybe this helps somebody:
https://github.com/rethinkdb/rethinkdb/issues/5636
I had lots of errors when installing but managed it in the end.
