### ISSUE TITLE
Geospatial queries documentation lat,long mixed up

### ISSUE THREAD

**Issue by freak4pc** [rethinkdb/rethinkdb#4319] opened 2015-06-01 08:29 UTC
The documentation for Geospatial queries states 

`"Coordinates of points on the sphere’s surface are addressed by a pair of floating point numbers that denote longitude and latitude." `

http://rethinkdb.com/docs/geo-support/javascript/

Should be "latitude and longitude". I was sure you have the actual data mixed and only realised when calculating distances and seeing that makes no sense :) 

A small detail but could be confusing to other people as well.

**Comment by thejsj** [comment] 2015-06-01 20:56
In GeoJSON (for some weird reason), longitude goes before latitude. If you look at the [`r.point`](http://rethinkdb.com/api/javascript/#point) documentation, you can notice that longitude goes before latitude. That's why sometimes you notice in the documentation that it's addressed in different orders, but in this specific sentence it makes sense to put longitude before latitude, following the documentation for `r.point`.

**Comment by freak4pc** [comment] 2015-06-01 20:57
Thanks for the answer Jorge...

I thought so as well but in practice, the data returned by RDB is latitude
first.. So the documentation doesnr match the reality (:

**Comment by mglukhovsky** [comment] 2015-06-01 21:36
Related discussion: #3060

@chipotle, is the documentation incorrect? If so, we should open an issue on the [docs repo](https://github.com/rethinkdb/docs).

**Comment by chipotle** [comment] 2015-06-01 21:56
I'm not sure I'm following here. `r.point` takes (longitude, latitude) just as the documentation says; you can demonstrate this in the Data Explorer.

```
r.point(-122,37)
{"$reql_type$":"GEOMETRY","coordinates":[-122,37],"type":"Point"}

r.point(37,-122)
RqlRuntimeError: Latitude must be between -90 and 90.  Got -122 in: r.point(37, -122)
```

The first number is longitude and the second is latitude in both the parameters and ReQL's internal raw object representation. Is there somewhere this is not the case?

**Comment by danielmewes** [comment] 2015-06-02 02:13
@freak4pc Both conventions are common in different contexts. We ended up picking longitude, latitude for consistency with GeoJSON.

Do you have an example for an operation where RethinkDB returns the latitude first? All operations in RethinkDB should be returning longitude first followed by latitude.

**Comment by freak4pc** [comment] 2015-06-02 08:53
Sorry , seems I was just creating r.point()s with lat,long instead of long,lat ...
Very confusing , meaning I would have to somehow post-process all records or have the clients now these are flipped...

**Comment by freak4pc** [comment] 2015-06-02 09:00
Easy way to flip lat,long on all records?

**Comment by chipotle** [comment] 2015-06-02 18:25
This `forEach` function worked for me in the Data Explorer by converting the points to GeoJSON and getting the coordinate values from the returned structure.

```js
// create a test table and insert some data
r.tableCreate('geotest');

r.table('geotest').insert([
  {id: 1, location: r.point(10, 20)},
  {id: 2, location: r.point(15, 30)},
  {id: 3, location: r.point(20, 40)}
]);

// flip the point values in the "location" field
r.table('geotest').forEach(function (doc) {
  var coords = doc('location').toGeojson()('coordinates');
  return r.table('geotest').get(doc('id')).update(
    {location: r.point(coords(1), coords(0))}
  );
});
```

Back up your data first, of course. :)

**Comment by danielmewes** [comment] 2015-06-02 18:26
Going to close this since it's not a bug, but feel free to ask more questions.

**Closed by danielmewes** 2015-06-02 18:26 UTC
