### ISSUE TITLE
table.reconfigure doesn't honor dryRun option when used with emergencyRepair

### ISSUE THREAD

**Issue by kulbirsaini** [rethinkdb/rethinkdb#4807] opened 2015-09-08 14:01 UTC
This is a followup of #4806.

While trying to reconfigure one of my tables, I used the command below

```javascript
r.db('pytwitter').table('users').reconfigure({ emergencyRepair: 'unsafe_rollback', dryRun: true })
```

It went ahead and applied the configuration. For this table, I didn't have to do anything else other than manually reducing the replicas on table page in admin panel. Now, I tried this with another table but this time with `dryRun: false`. 

```javascript
r.db('pytwitter').table('tweets').reconfigure({ emergencyRepair: 'unsafe_rollback', dryRun: false })
```

Same observation. I was under the impression that with `dryRun: true`, it won't change anything and I'll have to re-run the query with `dryRun: false` again to make things work. That was not the case.

**Comment by danielmewes** [comment] 2015-09-08 18:50
Thanks for the report @kulbirsaini.
That definitely sounds like a bug. We should either honour `dry_run` with `emergency_repair`, or alternatively throw an error if both options are used together.

`dry_run` is a little bit less useful with `emergency_repair`, because there is no guarantee that a second call to `reconfigure()` will still yield the same result as the dry run. Without `emergency_repair`, one can take the generated configuration from the dry run, and apply it manually to the `table_config` table. This isn't possible for `emergency_repair`.

@VeXocide do you think it would be easy to add `dry_run` support?

**Comment by VeXocide** [comment] 2015-10-05 17:43
I initially missed this issue, sorry.

@danielmewes -- at first glance `emergency_repair` already seems to support `dry_run`, question is why it's not behaving as intended.

**Comment by VeXocide** [comment] 2015-10-05 20:20
Unfortunately I wasn't able to reproduce this problem @kulbirsaini. There is a set of tests for this which pass and when manually checking `dryRun` it behaved as expected as well. When using `dryRun` the returned object should have `"repaired": 0` instead of `"repaired": 1`, and the changes should obviously not be applied.

I'll be closing the issue since I can't reproduce it, but if you have any further information please feel free to reopen it.

**Closed by VeXocide** 2015-10-05 20:20 UTC
Labels: tp:bug
