### ISSUE TITLE
cant start up rethinkdb 2.3.5 in thread.pool

### ISSUE THREAD

**Issue by yononabike** [rethinkdb/rethinkdb#6133] opened 2016-10-04 03:56 UTC
HELP! i cant get rethinkdb to start up... tried everything... downloading and installing w/ bash, the dmg, wiping the data directory and restarting... any help would be really appreciated. terminal output is copied below. im running Mac OSX Sierra (10.12).  I had no problem running Rethink DB before....  

terminal output:
```
Recursively removing directory /Users/LOREM/Documents/superpowers/ehstuff/rethinkdb_data/tmp
Initializing directory /Users/LOREM/Documents/superpowers/ehstuff/rethinkdb_data
Running rethinkdb 2.3.5 (CLANG 7.3.0 (clang-703.0.31))...
Running on Darwin 16.0.0 x86_64
Loading data from directory /Users/LOREM/Documents/superpowers/ehstuff/rethinkdb_data
Version: rethinkdb 2.3.5 (CLANG 7.3.0 (clang-703.0.31))
error: Error in src/arch/runtime/thread_pool.cc at line 367:
error: Segmentation fault from reading the address 0x1000.
error: Backtrace:
error: Mon Oct  3 21:53:22 2016
error: Exiting.
Abort trap: 6
```

**Comment by yononabike** [comment] 2016-10-04 21:35
here is some more on the error, 
`Recursively removing directory /Users/ynuta/Documents/superpowers/ehstuff/rethinkdb_data/tmp
Initializing directory /Users/ynuta/Documents/superpowers/ehstuff/rethinkdb_data
Running rethinkdb 2.3.5 (CLANG 7.3.0 (clang-703.0.31))...
Running on Darwin 16.0.0 x86_64
Loading data from directory /Users/ynuta/Documents/superpowers/ehstuff/rethinkdb_data
Version: rethinkdb 2.3.5 (CLANG 7.3.0 (clang-703.0.31))
error: Error in ./src/containers/intrusive_list.hpp at line 13:
error: Guarantee failed: [(next_ == nullptr) == (prev_ == nullptr)]
error: Backtrace:
rethinkdb(1482,0x700001821000) malloc: *** error for object 0x7fa97dc2e200: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Version: rethinkdb 2.3.5 (CLANG 7.3.0 (clang-703.0.31))
Crashing while already crashed. Printing error message to stderr.
Bus error from accessing the address 0x7fffa422fa03.Abort trap: 6`

**Comment by danielmewes** [comment] 2016-10-07 22:19
Very odd. I hope it's not a data corruption. Does it crash like this on every startup?

Can you check the following:
* Does RethinkDB start when you pass it a new data directory, e.g. through `-d test_data`?
* That you have enough RAM available on the machine (how much does it have?)

**Comment by yononabike** [comment] 2016-10-07 22:32
Yup... it crashes the same way pretty consistently every time i start it up.   

when i start it up with a new data directory (i.e.: test_data), i get a crash as well, output below:
`Recursively removing directory /Users/ynuta/Documents/superpowers/ehstuff/test_data/tmp
Initializing directory /Users/ynuta/Documents/superpowers/ehstuff/test_data
Running rethinkdb 2.3.5 (CLANG 8.0.0 (clang-800.0.38))...
Running on Darwin 16.0.0 x86_64
Loading data from directory /Users/ynuta/Documents/superpowers/ehstuff/test_data
Version: rethinkdb 2.3.5 (CLANG 8.0.0 (clang-800.0.38))
error: Error in src/arch/runtime/thread_pool.cc at line 367:
error: Segmentation fault from reading the address 0x1000.
error: Backtrace:
error: Fri Oct  7 16:30:08 2016
error: Exiting.
Abort trap: 6`

This is a MBP with 16GB ram. I hope that should be more than enough. I dont have any memory limitations on RethinkDB. 

Let me know what other information I can provide...  Thanks
yon

**Comment by geekyme** [comment] 2016-10-10 01:40
Was this broken after you updated to Sierra?

**Comment by yononabike** [comment] 2016-10-10 02:35
Nope.  I updated to sierra hoping it might help it. Not the brightest idea in retrospect.

**Comment by danielmewes** [comment] 2016-10-10 20:41
This is very surprising. If something was corrupted in the existing data directory, that could explain such a crash. But it crashing even on a new directory is extremely weird.

You said that you were running it fine before. Was that on the same machine?

Is there anything special about your setup? Anything that changed recently?
Are you using disk encryption?

Maybe try running with `--no-update-check`, though I doubt that that's the issue.

**Comment by yononabike** [comment] 2016-10-11 15:21
I was running fine before on this machine.  Im not sure if security or permission issues were changed, but that is what i suspected and tried to route out...  id love any tips on how to reset or adjust permission to make sure everything is setup as expected.   

Anything else that I could provide to help with this diagnosis? 

I tried `--no-update-check` and again no luck, here's the output... 
`yons-macbook:ehstuff ynuta$ rethinkdb --no-update-check
Running rethinkdb 2.3.5 (CLANG 8.0.0 (clang-800.0.38))...
Running on Darwin 16.0.0 x86_64
Loading data from directory /Users/ynuta/Documents/superpowers/ehstuff/rethinkdb_data
Version: rethinkdb 2.3.5 (CLANG 8.0.0 (clang-800.0.38))
error: Inaccessible database file: "/Users/ynuta/Documents/superpowers/ehstuff/rethinkdb_data/metadata": No such file or directory
       Some possible reasons:
       - the database file couldn't be created or opened for reading and writing
       - the user which was used to start the database is not an owner of the file
Version: rethinkdb 2.3.5 (CLANG 8.0.0 (clang-800.0.38))
Crashing while already crashed. Printing error message to stderr.
Guarantee failed: [this->prev_ == this] non-empty intrusive list destroyedVersion: rethinkdb 2.3.5 (CLANG 8.0.0 (clang-800.0.38))
Crashing while already crashed. Printing error message to stderr.
Guarantee failed: [this->next_ == this] inconsistent intrusive list (end node)!Version: rethinkdb 2.3.5 (CLANG 8.0.0 (clang-800.0.38))
Crashing while already crashed. Printing error message to stderr.
Guarantee failed: [size_ == 0] empty intrusive list destroyed with non-zero sizerethinkdb(1184,0x7000004e6000) malloc: *** error for object 0x7fddf20dbc00: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6`

**Comment by yononabike** [comment] 2016-10-11 19:00
well the good news i was able to get rethinkdb running when i booted my mac into safe mode. outside of safe mode still having the same problems as above.. that points to a system issue and not a rethinkdb issue. Any ideas on what i can do to debug the system differences for OS X in and outside of safe mode?

**Comment by bselack** [comment] 2016-10-14 21:20
You may want to (if you haven't already) run Disk Utility & verify/repair disk permissions. If that doesn't help you can "Verify Disk", but if there are issues, you'll need to boot from another disk to run the "Repair Disk"

**Comment by yononabike** [comment] 2017-02-21 22:25
repair disk permissions doesn't exist in sierra :(

**Comment by srh** [comment] 2017-12-12 21:55
Closing, but feel free to reopen if there's more info or possibility of discovering the cause of this.

**Closed by srh** 2017-12-12 21:55 UTC
Labels: tp:bug
