### ISSUE TITLE
Admin UI -Data Explorer

### ISSUE THREAD

**Issue by CreativeManix** [rethinkdb/rethinkdb#6107] opened 2016-09-14 13:50 UTC
I am unable to type long query in the data explorer. Some how the curser is not placing at the end. 

r.db('test').table("CommunityMember").filter(function(m1){return r.table("CommunityMember").filter(function(m2){ return m2("userId").eq('269fd8cc-5d4b-4683-bcca-4294b7b21f82').and(m2("communityId").eq(m1("communityId")))}).count().gt(0)}).eqJoin()

The above query is incomplete  at the end i.e. the eqJoin. But If place my curser Or typing it types somewhere else, so unable to finish my query at all. Is there is anyway I can just use plain text in this ui? 

Note: I am using OSX and Chrome browser

**Comment by chrisvariety** [comment] 2016-09-14 14:37
Hey @CreativeManix just FYI this has already been reported at https://github.com/rethinkdb/rethinkdb/issues/5873

**Comment by danielmewes** [comment] 2016-09-14 18:34
Closing as duplicate of https://github.com/rethinkdb/rethinkdb/issues/5873 .

**Closed by danielmewes** 2016-09-14 18:34 UTC
