### ISSUE TITLE
Building with recc on GCC gives warning

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#1489] opened 2013-09-27 19:56 UTC
With RECC_CC=g++ set, I get the following warning at the end of the built:
```
./build/release/obj/arch/io/disk/stats.o:stats.cc:function non-virtual thunk to boost::exception_detail::error_info_injector<boost::bad_function_call>::~error_info_injector(): warning: relocation refers to discarded section
./build/release/obj/arch/io/disk/stats.o:stats.cc:function non-virtual thunk to boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_function_call> >::~clone_impl(): warning: relocation refers to discarded section
./build/release/obj/arch/io/disk/stats.o:stats.cc:function non-virtual thunk to boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_function_call> >::~clone_impl(): warning: relocation refers to discarded section
```

This might be due to the different versions of GCC installed for distcc and local compilation on newton respectively.

**Comment by AtnNn** [comment] 2015-02-25 09:32
I am unable to reproduce. Closing as outdated.

**Closed by AtnNn** 2015-02-25 09:32 UTC
Labels: cp:devops
