### ISSUE TITLE
Rethindb v2.4 for Windows link not work

### ISSUE THREAD

**Issue by AhrimanSefid** [rethinkdb/rethinkdb#6835] opened 2020-02-21 15:00 UTC
Hi
Rethindb v2.4 for Windows link not work
https://download.rethinkdb.com/windows/rethinkdb-2.4.0.zip
404 Not Found
nginx/1.14.0 (Ubuntu)

**Comment by modyamash** [comment] 2020-02-29 11:28
yes the link is not working

**Comment by srh** [comment] 2020-03-07 08:21
@AhrimanSefid Try my unofficial build at https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-win-1

**Comment by lmdc45** [comment] 2020-03-25 06:40
just wondering why 

> This release does not support the js ReQL command.

?

Thanks,

**Comment by gabor-boros** [comment] 2020-08-07 06:36
duplicate of https://github.com/rethinkdb/rethinkdb/issues/6814

**Closed by gabor-boros** 2020-08-07 06:36 UTC
