### ISSUE TITLE
rethinkdb.com iphone 6+ problem

### ISSUE THREAD

**Issue by ha1331** [rethinkdb/rethinkdb#4993] opened 2015-10-24 21:09 UTC
I haven't encountered this issue my self, relaying Williamsteins description from slack:

williamstein [7:17 PM] 
@dalanmiller: on Iphone 6+, the RethinkDb website, docs, etc., are perhaps the most horrendously broken website I've seen on mobile.  This slowed my adoption of RethinkDB for a while (e.g., a few times, I heard about it when reading something on my phone, looked at the site, it was impossible to read, so I went elsewhere).   What happens when viewing the site in iPhone 6+ is that something gets in a weird infinite loop where it changes the layout, then changes it again about 1 second later, then in response to that change, it changes it back, ad infinitum.      I imagined this problem would be quickly fixed, but I just checked and it is still broken (6 months later).    With Safari it changes the layout about once per second; with Chrome (on iOS) it changes layout back and forth about 8 times per second (so same problem, but worse).

I tested the api-docs using iphone 6, but couldn't reproduce the issue. I don't have 6+ available, so I cant test that.

**Comment by ha1331** [comment] 2015-10-24 23:08
chriscates [1:46 AM] 
What a shame @williamstein The rethinkdb docs look great on my Android (Galaxy S4).
So maybe it's something wrong with your phone.

chriscates [1:46 AM]
If I had an iPhone I'd test it and I would try to fork the code and debug it.

williamstein [2:01 AM] 
I'm not sure how to debug it.  Since it happens on both Chrome ​*and*​ Safari on my phone, I doubt it is just my phone.   Also, I just now tested on my wife's iphone 6+ and saw the same behavior.  So it's an issue with iPhone 6 plus (at least).

barkerja [2:06 AM] 
It’s an issue with the 6+’s resolution; probably a media query issue. Media queries that target ​_normal_​ iphone resolutions, will fail on the 6+.

barkerja [2:07 AM]
Maybe I’ll take a look tonight/tomorrow and provide a PR if I can figure it out (I too have a 6+ and occasionally read the docs/blog on my phone, and it is frustrating). (edited)

**Comment by chrisvariety** [comment] 2015-10-24 23:44
Gif of the problem for y'all ![bug](https://cloud.githubusercontent.com/assets/44855/10713342/5536e456-7a6e-11e5-85b3-cfb7e274a04b.gif)

**Comment by coffeemug** [comment] 2015-10-26 07:28
According to @barkerja, the following is the offending query:

```
@media screen and (max-width: 44rem) {
    html {
        font-size: 58%;
    }
}

@media screen and (min-width: 44rem) {
    html {
        font-size: 60%;
    }
}
```

Also, this is allegedly reproducible in Safari 9 responsive testing. I will bug @mglukhovsky tomorrow and we'll get it fixed.

**Comment by coffeemug** [comment] 2015-10-28 05:31
@mglukhovsky -- you mentioned you fixed this earlier today -- what's the state of this issue?

**Comment by williamstein** [comment] 2015-10-28 05:45
I can happily report that opening the official rethinkdb.com website on my iphone 6+ now works perfectly :-)

**Comment by mglukhovsky** [comment] 2015-10-28 14:52
Fantastic. Sorry for no update on this, I was busy trying to track this down and reproduce it. Some notes:

- This is a bug that _only_ appears on Webkit mobile. No other browser (including Safari 9) will reproduce this, as far as I can tell.
- This is also _not_ due to conflicting media query breakpoints, as far as I can tell. Our breakpoints are automatically generated using [Neat](http://neat.bourbon.io/).
- The unanswered question is why the site width would cause it to flicker -- the site width would have to be altered in some way for it to flip back and forth. I spent a few hours digging into it, but don't have a minimally reproducible test case yet.
- This flickering was observed by expanding the breakpoint across 5-7 pixels in either direction.

The simplest solution was to just move the breakpoint until it stopped flickering on all platforms. 

I'll close this issue for now, but if it appears on any other browser, we'll dig into this. Thanks for your help, everyone.

**Closed by mglukhovsky** 2015-10-28 14:52 UTC

**Comment by barkerja** [comment] 2015-10-28 14:55
@mglukhovsky I was able to consistently reproduce this on Safari 9 (OS X 10.11) using its responsive mode.

In doing so, I was able to see font-size jump between the two values due to the media queries listed above (the inspector pointed to those queries specifically).

Things do look good now though! :+1:

**Comment by mglukhovsky** [comment] 2015-10-28 15:02
@barkerja: could you tell me how? I'm running exactly the same setup (Safari 9.0.1 on OS X 10.11.1), and in responsive design mode (iPhone 6 Plus at 414x736) was unable to see any flickering.

The font-size jump makes sense if it's flipping across breakpoints. However, as far as I can tell, the browser should just pick one of breakpoints (the last one defined).

The only other thing I could think of was that some UI element (perhaps added via JavaScript) was forcing the browser to recalculate the site width, causing it to move back and forth across the breakpoint. Unfortunately, without the full developer tools on the desktop, it's hard to dig into it further.

**Comment by barkerja** [comment] 2015-10-28 15:05
I believe the issue could be triggered by clicking on the hamburger to slide out the side navigation. There were a couple of other cases that would cause it to happen, but I've already forgotten at this point. :frowning:

**Comment by mglukhovsky** [comment] 2015-10-28 15:08
@barkerja: yes, tried that, and still couldn't get it to reproduce. That's ok, we'll see if it pops up again. Thanks for your help in tracking this down, I really appreciate it!

**Comment by barkerja** [comment] 2015-10-28 15:09
Agh! The bugs you can never reproduce yourself are the hardest. If I see it happen again, I'll try and record more details.

**Comment by mglukhovsky** [comment] 2015-10-28 15:13
Thanks, _any_ info is helpful. I've been trying to reproduce this for ages. :smile:

**Comment by chrisvariety** [comment] 2015-10-28 15:43
I had to do a hard-refresh in the iOS simulator, but now cannot reproduce on the main site or docs. :tada:
