### ISSUE TITLE
Standardize `any`, `or`, `|` situation

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#1581] opened 2013-10-28 19:42 UTC
Even people who work here are confused by this.

I think the names `any` and `all` are confusing.  IMO we should use `and` and `or` in every language that allows it, and use something similar (like `and_` or something) in languages that don't.  We should also support the shortcuts `&` and `|` in languages that allow it.

Scheduling for backlog; let's try to avoid discussing this until we schedule it for a sprint.

**Comment by danielmewes** [comment] 2015-01-26 23:09
We should remove `any` and `all` and only keep `and`/`or`.

**Comment by marshall007** [comment] 2015-01-28 18:42
#3511 can probably be closed as a duplicate of this issue.

**Comment by danielmewes** [comment] 2015-01-28 20:10
Thanks for noting @marshall007 . Going to close the other one as suggested.

**Comment by gchpaco** [comment] 2015-02-04 04:47
> We should remove any and all and only keep and/or.

:+1:

**Comment by VeXocide** [comment] 2015-02-06 21:09
:+1:

**Comment by mlucy** [comment] 2015-02-06 23:35
Everyone seems on board with this; planning to mark it as settled on Monday.

**Comment by VeXocide** [comment] 2015-02-14 00:00
This is in CR 2610 by @Tryneus

**Comment by VeXocide** [comment] 2015-02-14 02:38
Merged into `next` via commit c4c6b0a

**Closed by VeXocide** 2015-02-14 02:38 UTC
Labels: quick_to_fix, tp:API_settled, tp:RQL_proposal
