### ISSUE TITLE
History in the data explorer is buggy

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#3620] opened 2015-01-20 10:01 UTC
I noticed a few bugs in the history feature of the data explorer -- the code probably could use a critical lookover. Here are two issues I noticed:

1. Click on the history button to open the history window
2. Press "clear history"
3. Click on the history button to close the history window
4. Run a query (I ran `r.db('rethinkdb').table('stats').changes()`)

The history window will open itself, but it should stay closed. For some reason the web ui loses/caches the state while it shouldn't.

Another bug I found is that the data explorer shows stale history while in this state:

1. Click on the history button to open the history window
2. Press "clear history"
3. Click on the history button to close the history window
4. Run a query (I ran `r.db('rethinkdb').table('stats').changes()`). The history window will open (as described above)
5. Run another query (say,  `r.db('rethinkdb').table('jobs').changes()`). At this point the second query won't show up in history while it should
6. Click on the history button. The new query will show up as it should

/cc @AtnNn

**Comment by coffeemug** [comment] 2015-01-20 10:02
Also: replicating this should be easy by following the steps above, but if you can't follow the steps (I know it's kind of a pain), grab me and I'll show how to reproduce it.

**Comment by AtnNn** [comment] 2015-01-20 18:15
I was able to reproduce. This looks like a single bug to me: the first query added to an empty history causes the history to open in a broken state.

**Comment by AtnNn** [comment] 2015-01-20 20:06
Fixed in `atnnn/3620` (e0f5fc2)

**Closed** 2015-01-23 01:44 UTC
Labels: cp:web-ui
