### ISSUE TITLE
Fetching curl fails with 'no certificate subject alternative name matches'

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#5352] opened 2016-02-03 19:20 UTC
curl doesn't complain, but wget does:

```
$ wget http://curl.haxx.se/download/curl-7.40.0.tar.bz2
ERROR: no certificate subject alternative name matches
        requested host name `curl.haxx.se'.
```

openssl seems to agree:

```
$ openssl s_client -connect curl.haxx.se:443 < /dev/null | grep subject
subject=/CN=anja.haxx.se
```

**Comment by danielmewes** [comment] 2016-02-03 19:55
That sounds like `curl.haxx.se` is configured incorrectly, doesn't it?

**Comment by danielmewes** [comment] 2016-02-03 19:59
Weirdly, if I look at the certificate for https://curl.haxx.se/ in Chrome or Firefox, the subject seems to be fine: "CN = curl.haxx.se"

**Comment by AtnNn** [comment] 2016-02-03 20:05
@vexocide pointed out to me that it seems to work with gnutls but not openssl.

```
$ gnutls-cli --print-cert curl.haxx.se | grep subject
 - subject `CN=curl.haxx.se'
```

**Comment by danielmewes** [comment] 2016-02-03 20:08
@bagder any ideas? It looks like `curl.haxx.se` is serving different certificates based on the client.

**Comment by AtnNn** [comment] 2016-02-03 20:09
Full log: https://gist.github.com/AtnNn/c06af4e9becb49a19bb8

**Comment by bagder** [comment] 2016-02-03 21:53
Lack of SNI in your tests perhaps?

**Comment by bagder** [comment] 2016-02-03 21:53
curl works fine against curl.haxx.se using either GnuTLS or OpenSSL...

**Comment by danielmewes** [comment] 2016-02-03 22:01
Thanks for chiming in @bagder. Hmm that suggests that the difference is caused by something other than the SSL library.
It reliably fails with `wget` for me, as well as with the `openssl` command line client (but works with curl as well as Firefox and Chrome, and even my phone's browser).

**Comment by AtnNn** [comment] 2016-02-03 22:01
It looks like there was an SNI related bug that was fixed in wget 1.14. I was using wget 1.13.

https://bugs.launchpad.net/ubuntu/+source/wget/+bug/338242
http://savannah.gnu.org/bugs/?func=detailitem&item_id=26786

**Comment by AtnNn** [comment] 2016-02-10 02:54
There is a possible work-around in `atnnn/curlfix` which uses curl instead of wget by default.

**Comment by danielmewes** [comment] 2016-02-10 21:36
Merged @AtnNn 's work-around into `v2.2.x` and `next` (b0d112e6f639cbd904a555e00a090e418a8cf984, 12265e9c8670562722f59f199c45c3f84ec69f3e).

**Closed by danielmewes** 2016-02-10 21:36 UTC
Labels: cp:build, pr:high

**Comment by aloukissas** [comment] 2017-02-01 18:50
Happens in the out-of-the-box centos 5.11 (which comes with an ancient version of curl/openssl):

`$ curl --version

curl 7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
Protocols: tftp ftp telnet dict ldap http file https ftps
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz
`

**Comment by AtnNn** [comment] 2017-02-02 14:25
@aloukissas You could try upgrading curl or building RethinkDB without fetching curl.

If you are building `next`, you could also download the archive into `external/.cache/`, the build system will find it, check its hash, and skip the download attempt.

**Comment by aloukissas** [comment] 2017-02-02 17:36
@AtnNn that's the most up-to-date version of curl from upstream (centos loves keeping vintage versions in their repos). The only option is building from source (or 3rd party rpm repo).

**Comment by AtnNn** [comment] 2017-02-02 17:53
I've only tested the RethinkDB build on centos 6 and 7. curl 7.15.5 is 11 years old. I don't want to spend too much time trying to support it.

If you can find an alternative URL for the curl source archive that your old version of curl can fetch, I can add it as an alternative.

Can you install `libcurl-devel` and building RethinkDB with it, instead of a fetched libcurl?
