### ISSUE TITLE
Python: import rethinkdb fails in PyPy

### ISSUE THREAD

**Issue by tptee** [rethinkdb/rethinkdb#3969] opened 2015-03-23 19:53 UTC
Hi there,

I'd been using the previous version of the Python Rethink driver (1.15) without issue on PyPy. Since upgrading the driver to 1.16.0-3, I get the following error when trying to import:

```
Python 2.7.8 (10f1b29a2bd21f837090286174a9ca030b8680b2, Feb 05 2015, 17:51:14)
[PyPy 2.5.0 with GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import rethinkdb as r
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/pypy/2.5.0/libexec/site-packages/rethinkdb/__init__.py", line 9, in <module>
    class r(__builtins__['object']): # defends against re-importing obscuring object
TypeError: 'module' object is not subscriptable
```

From https://www.bountysource.com/issues/2197808-fix-typeerror-for-pypy is an idea:

"A module object is not subscriptable in PyPy. A subscriptable module is an implementation detail for CPython. The help doc only says you can use dotted notation to get attributes out of a module, it doesn't implement __getitem__."

**Comment by mlucy** [comment] 2015-03-23 19:58
@Tryneus, any insight?

**Comment by Tryneus** [comment] 2015-03-23 20:34
@larkost recently rewrote this file, so I would defer to him

**Comment by Tryneus** [comment] 2015-03-25 22:59
I think if we just move the definition of `class r` above the import statements, that should avoid the situation the comment seems to be warning about.  Tested this, and it appears to run fine on `python2.6` - `python3.4` and `pypy`.  Up in review 2746.

**Comment by Tryneus** [comment] 2015-03-26 02:17
Ok, the fix has been approved and merged into `next` in commit 6661520, and cherry-picked into `v2.0.x` in commit 1c7dec9, and `v1.16.x` in commit 90b1e37.  Will be in release 2.0 unless we do a python driver release for this.  Thanks for reporting this, @tptee!

**Comment by danielmewes** [comment] 2015-03-26 02:33
We're going to do a 1.16.3 server point release, so we should do a driver release with it as well (@atnnn).

**Comment by tptee** [comment] 2015-03-26 02:44
Thanks for the quick fix @Tryneus!

**Comment by danielmewes** [comment] 2015-03-26 06:55
This fix seems to break the Python driver (at least) when loaded within the testing framework on gantz:

```
$ ./run
[...]
Traceback (most recent call last):
  File "/Users/daniel/rethinkdb/test/scenarios/rebalance.py", line 41, in <module>
    r = utils.import_python_driver()
  File "/Users/daniel/rethinkdb/test/common/utils.py", line 186, in import_python_driver
    driverModule = imp.load_module('rethinkdb', moduleFile, pathname, desc)
  File "/Users/daniel/rethinkdb/build/drivers/python/rethinkdb/__init__.py", line 4, in <module>
    class r(object):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
```

**Comment by Tryneus** [comment] 2015-03-26 07:19
Guess we have to do it the ugly way then, I'll have it up for review soon.

**Comment by AtnNn** [comment] 2015-03-26 07:28
Please, let's not do anything ugly.

We already have some ugly code in the `import_rethinkdb_driver` function in `test/common/util.py` which may be the cause of this error.

We could instead make the script prettier by not using `import *`.

If needed, a portable way to access the builtins might be:

```
try:
   import __builtin__ as builtins # Python 2
except ImportError:
   import builtins # Python 3

class r(builtins.object):
```

**Comment by Tryneus** [comment] 2015-03-26 07:39
Thanks for the suggestion, @atnnn, that's a little cleaner than what I was doing.  Up in review 2748.

**Comment by Tryneus** [comment] 2015-03-26 07:46
Well then, the new fix has been approved and merged to `next` in commit 59ed379, `v2.0.x` in commit 3dca9da, and `v1.16.x` in commit 345b5f8.

**Closed by Tryneus** 2015-03-26 07:46 UTC

**Comment by AtnNn** [comment] 2015-03-27 22:04
@tptee The newly released version of the rethinkdb Python driver, version 1.16.0-4, contains a fix for this issue.

**Comment by tptee** [comment] 2015-03-30 14:10
Thanks all!
