### ISSUE TITLE
I can't install RethinkDB on Ubuntu 20.04

### ISSUE THREAD

**Issue by imposs1bleuser** [rethinkdb/rethinkdb#6974] opened 2021-06-24 07:07 UTC
System: 20.04.2 LTS

Hello. I'm trying to install rethinkdb on my Ubuntu 20.04.2 LTS PC. I follow this guide https://rethinkdb.com/docs/install/ubuntu/. However, something goes wrong during installation and I get the message when I try to install: E: RethinkDB package not found.

Console Return:
[Original: in Polish]
imposs1ble@SadorPC: ~ $ source /etc/lsb-release && echo "deb https://download.rethinkdb.com/repository/ubuntu-$DISTRIB_CODENAME $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
deb https://download.rethinkdb.com/repository/ubuntu-focal focal main
imposs1ble@SadorPC: ~ $ wget -qO- https://download.rethinkdb.com/repository/raw/pubkey.gpg | sudo apt-key add -
gpg: invalid key resource URL '/tmp/apt-key-gpghome.Uf8Yj236BN/home:manuelschneid3r.asc.gpg'
gpg: zasób bloku klucza ,,(null)'': Błąd ogólny
gpg: key 1488EB46E192A257: 1 podpis nie został sprawdzony z powodu braku klucza
gpg: key 1488EB46E192A257: 1 podpis nie został sprawdzony z powodu braku klucza
gpg: key 3B4FE6ACC0B21F32: 3 podpisy nie zostały sprawdzone z powodu braku klucza
gpg: key D94AA3F0EFE21092: 3 podpisy nie zostały sprawdzone z powodu braku klucza
gpg: key 871920D1991BC93C: 1 podpis nie został sprawdzony z powodu braku klucza
gpg: Ogółem przetworzonych kluczy: 7
gpg:       pominiętych nowych kluczy: 7
imposs1ble@SadorPC: ~ $ sudo apt-get update
Stary:1 http://pl.archive.ubuntu.com/ubuntu focal InRelease
Stary:2 http://pl.archive.ubuntu.com/ubuntu focal-updates InRelease            
Stary:3 http://pl.archive.ubuntu.com/ubuntu focal-backports InRelease          
Stary:4 https://repo.steampowered.com/steam stable InRelease                   
Stary:5 http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_20.04  InRelease
Pobieranie:6 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Pobieranie:7 https://download.rethinkdb.com/repository/ubuntu-focal focal InRelease [1 546 B]
Błąd:7 https://download.rethinkdb.com/repository/ubuntu-focal focal InRelease
  Następujące podpisy nie mogły zostać zweryfikowane z powodu braku klucza publicznego: NO_PUBKEY 1D85E93F801BB43F
Czytanie list pakietów... Gotowe
W: Błąd GPG: https://download.rethinkdb.com/repository/ubuntu-focal focal InRelease: Następujące podpisy nie mogły zostać zweryfikowane z powodu braku klucza publicznego: NO_PUBKEY 1D85E93F801BB43F
E: The repository 'https://download.rethinkdb.com/repository/ubuntu-focal focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
imposs1ble@SadorPC: ~ $ sudo apt-get install rethinkdb
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności       
Odczyt informacji o stanie... Gotowe
E: Nie udało się odnaleźć pakietu rethinkdb

[translated to EN]
imposs1ble @ SadorPC: ~ $ source / etc / lsb-release && echo "deb https://download.rethinkdb.com/repository/ubuntu-$DISTRIB_CODENAME $ DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
deb https://download.rethinkdb.com/repository/ubuntu-focal focal main
imposs1ble @ SadorPC: ~ $ wget -qO- https://download.rethinkdb.com/repository/raw/pubkey.gpg | sudo apt-key add -
gpg: invalid key resource URL '/tmp/apt-key-gpghome.Uf8Yj236BN/home:manuelschneid3r.asc.gpg'
gpg: key block resource "(null)": General error
gpg: key 1488EB46E192A257: 1 signature was not checked due to missing key
gpg: key 1488EB46E192A257: 1 signature was not checked due to missing key
gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing key
gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing key
gpg: key 871920D1991BC93C: 1 signature was not checked due to missing key
gpg: Total keys processed: 7
gpg: new keys missed: 7
imposs1ble @ SadorPC: ~ $ sudo apt-get update
Old: 1 http://en.archive.ubuntu.com/ubuntu focal InRelease
Old: 2 http://en.archive.ubuntu.com/ubuntu focal-updates InRelease
Old: 3 http://en.archive.ubuntu.com/ubuntu focal-backports InRelease
Old: 4 https://repo.steampowered.com/steam stable InRelease
Old: 5 http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_20.04 InRelease
Download: 6 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Download: 7 https://download.rethinkdb.com/repository/ubuntu-focal focal InRelease [1546 B]
Error: 7 https://download.rethinkdb.com/repository/ubuntu-focal focal InRelease
  The following signatures could not be verified due to missing public key: NO_PUBKEY 1D85E93F801BB43F
Reading package lists ... Done
In: GPG error: https://download.rethinkdb.com/repository/ubuntu-focal focal InRelease: The following signatures could not be verified due to missing public key: NO_PUBKEY 1D85E93F801BB43F
E: The repository 'https://download.rethinkdb.com/repository/ubuntu-focal focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure (8) manpage for repository creation and user configuration details.
imposs1ble @ SadorPC: ~ $ sudo apt-get install rethinkdb
Reading package lists ... Done
Building a dependency tree
Reading status information ... Done
E: Could not find rethinkdb package

**Comment by srh** [comment] 2021-06-24 18:03
It is working for me.

My guess is, your GPG or apt-key setup is causing the issue:

```
gpg: invalid key resource URL '/tmp/apt-key-gpghome.Uf8Yj236BN/home:manuelschneid3r.asc.gpg'
```

You might be able to work around this with `apt-get --allow-unauthenticated install ...` if you don't want to worry right now about your GPG or apt-key setup.

You could also download the .deb directly from https://download.rethinkdb.com/repository/ubuntu-focal/pool/r/rethinkdb/rethinkdb_2.4.1~0focal_amd64.deb and install it with `dpkg -i`

Here is what a successful installation looks like:

```
srh@pcxvm1:~$ source /etc/lsb-release && echo "deb https://download.rethinkdb.com/repository/ubuntu-$DISTRIB_CODENAME $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
[sudo] password for srh: 
deb https://download.rethinkdb.com/repository/ubuntu-focal focal main
srh@pcxvm1:~$ wget -qO- https://download.rethinkdb.com/repository/raw/pubkey.gpg | sudo apt-key add -
OK
srh@pcxvm1:~$ sudo apt-get update
Get:1 https://download.docker.com/linux/ubuntu focal InRelease [52.1 kB]
Get:2 https://download.rethinkdb.com/repository/ubuntu-focal focal InRelease [1,546 B]
Hit:3 http://us.archive.ubuntu.com/ubuntu focal InRelease                      
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease          
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease           
Hit:6 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Get:7 https://download.rethinkdb.com/repository/ubuntu-focal focal/main amd64 Packages [913 B]
Fetched 54.6 kB in 1s (62.6 kB/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://download.rethinkdb.com/repository/ubuntu-focal focal InRelease' doesn't support architecture 'i386'
srh@pcxvm1:~$ sudo apt-get install rethinkdb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-5.8.0-53-generic linux-hwe-5.8-headers-5.8.0-53 linux-image-5.8.0-53-generic
  linux-modules-5.8.0-53-generic linux-modules-extra-5.8.0-53-generic
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  rethinkdb
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.2 MB of archives.
After this operation, 37.2 MB of additional disk space will be used.
Get:1 https://download.rethinkdb.com/repository/ubuntu-focal focal/main amd64 rethinkdb amd64 2.4.1~0focal [10.2 MB]
Fetched 10.2 MB in 1s (11.5 MB/s)     
Selecting previously unselected package rethinkdb.
(Reading database ... 237433 files and directories currently installed.)
Preparing to unpack .../rethinkdb_2.4.1~0focal_amd64.deb ...
Unpacking rethinkdb (2.4.1~0focal) ...
Setting up rethinkdb (2.4.1~0focal) ...
The RethinkDB startup service is installed but disabled. To enable it,
follow the instructions in the guide located at http://www.rethinkdb.com/docs/guides/startup/
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for systemd (245.4-4ubuntu3.7) ...
```

**Comment by srh** [comment] 2021-06-24 18:05
I am closing this under the presumption that there is not a bug here; if there is, feel free to reopen.

**Closed by srh** 2021-06-24 18:05 UTC

**Comment by imposs1bleuser** [comment] 2021-06-25 05:30
I installed it manually, its working, thanks for help.
