### ISSUE TITLE
100% Cache usage causing major performance degradation in writes

### ISSUE THREAD

**Issue by aviranco** [rethinkdb/rethinkdb#5829] opened 2016-06-05 08:22 UTC
I've made some inserts performance testing (using durability:'soft') and I've noticed that when the cache is 100% (I have no idea what does it mean, I can only guess its a temporary buffer used to store inserts in memory until writted to disk), it causing the insert speed to be about 50% than before.
I thought that it might be causing due to high insert rates, but the bad part is that the cache is keep being on 100% even if I stop using the database, and will only clear when stopping the process and raising it up, so it means that after a few seconds/minutes, there will be permanent performance issue.

I can use the --cache-size flag, but it will only give more time until 100% of the cache will be used, but when it will hit 100% I will get the same effect as before.

<img width="969" alt="performance-on-100-cache" src="https://cloud.githubusercontent.com/assets/1299681/15804412/b4c9cd32-2b0f-11e6-9e88-573b88713d78.png">

**Comment by danielmewes** [comment] 2016-06-05 08:35
That's pretty normal.

The cache is used to keep commonly used data in memory, so RethinkDB doesn't need to load it from disk.

As long as the cache size is larger than the total data size, all data will eventually be in cache which avoids disk reads during query execution completely (of course data still needs to be written to disk for durability reasons). If you restart RethinkDB, the cache starts out empty. You should actually see the worst performance right after restarting, since no data is in cache at all and every access requires reading from disk. As the cache gets "warmed up", performance should increase.

Once the data size is too large to fit into cache completely (i.e. when you reach 100% cache used), RethinkDB has to evict less recently used data from the cache. The next time that data is needed for any query, it will have to ask the operating system to fetch it. There's a second line of caching in the OS which can dampen the effect at first, though eventually the OS in turn will have to go all the way to disk. Just asking the operating system for the data is about an order of magnitude slower than when the data can be used from the cache directly. If the OS has to hit disk to read the data, you can multiply another one or two orders of magnitude.

This is expected behavior (and you will see this effect with any database), so I'm going to close this.

If you only do inserts, you can improve the efficiency of the cache somewhat by inserting new data with keys that are close to each other (rather than using the randomly generated UUIDs, which are all over the place). That will allow RethinkDB to evict parts of the index that are not currently used, and insert performance will be less affected by hitting the cache size.
The disadvantage is that this doesn't play too well with RethinkDB's range-based sharding, and all new documents will end up in the same shard (if your table is sharded).
A compromise might be using multiple "strands" of primary keys, where you generate keys from a certain fixed number of sequences. For example you can generate them from the sequences `["0", counter]`, `["1", counter]`, `["2", counter]`, ..., `["f", counter]`, where `counter` is an incrementing value in each one. That will make sure that indexes still distribute properly over shards, while providing cache locality within each sequence.

**Closed by danielmewes** 2016-06-05 08:35 UTC
