### ISSUE TITLE
Apt Repository GPG key expired

### ISSUE THREAD

**Issue by gpkfr** [rethinkdb/rethinkdb#6750] opened 2019-07-12 14:55 UTC
the repository's gpp key have expired. so apt update will failed.

**Comment by gabor-boros** [comment] 2019-07-12 15:12
@gpkfr thank you for reporting this issue!

@srh do we have access to the apt repository? Can we act on this? If not we should be able to release the 2.3.5/6 versions as soon as we can to not block anybody. If we need servers for this, then I can help with DigitalOcean droplets.

**Comment by gpkfr** [comment] 2019-07-12 15:18
i do not know if you have access to the apt repository. (http://download.rethinkdb.com/apt).

**Comment by srh** [comment] 2019-07-13 02:41
@gabor-boros I don't have access to the repository.

**Comment by gabor-boros** [comment] 2019-07-13 20:06
Doh! 😞

@srh what do you think, how big is the effort to re-release to bintray?

**Comment by srh** [comment] 2019-07-14 00:59
I have never used bintray.

**Comment by gabor-boros** [comment] 2019-07-15 04:10
@srh and @gpkfr this week I'll try to investigate if we can access the current repository and the download page. As soon as I know anything I'll let you know.

**Comment by BanzaiMan** [comment] 2019-07-18 12:37
Hello, there. Is there an update on this? We (Travis CI) would like to have RethinkDB working again without resorting to trusting an unverified package. Thank you!

**Comment by gabor-boros** [comment] 2019-07-19 05:26
Hello @BanzaiMan,

I’m still waiting for the info to know so we have access or not to the current repository. 

The best case scenario is that we can access the repo and we can solve it pretty quick. The worst case is that we need to repackage everything again.

@KittyBot, FYI

**Comment by TarekMSayed** [comment] 2019-07-21 06:29
@gabor-boros packages can be downloaded manually no need e repackage.

**Comment by gabor-boros** [comment] 2019-07-21 14:45
@TarekMSayed although it can be, we will need to set up CI/CD in the near future anyway ☺️

**Comment by rriixx** [comment] 2019-07-22 08:24
any update on this? We use Travis CI and it now breaks our deployment pipeline

**Comment by gabor-boros** [comment] 2019-07-22 20:14
@rriixx Still waiting for the credentials. :( 

I know this is not a “proper” answer, but as a workaround can’t you disable gpg check until we fix the issue?

**Comment by KingWaffleshnoz** [comment] 2019-07-25 06:08
Have been exploring potential workarounds; unfortunately, `sudo apt-get --allow-unauthenticated update` doesn't seem to be an option here, nor does `sudo apt-key adv --keyserver keys.gnupg.net --recv-keys [key]`.

**Comment by loeffel-io** [comment] 2019-07-29 09:13
ci workaround

```bash 
source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get -y --allow-unauthenticated install rethinkdb
rethinkdb --bind all &
```

**Comment by srh** [comment] 2019-07-30 17:09
I don't like the idea of unsigned packages floating around, so... yeah.

**Comment by BanzaiMan** [comment] 2019-07-30 21:01
I am sorry to report that we (Travis CI) have made the switch to the `--allow-unauthenticated` flag. I hope that the issue will be resolved soon, so that we can drop that flag.

**Comment by sholladay** [comment] 2019-08-03 07:21
@BanzaiMan has the `--allow-unauthenticated` flag actually been deployed? I am using Travis CI with the below config:

```yaml
addons:
  apt:
    packages:
      - rethinkdb
    sources:
      - sourceline: deb https://download.rethinkdb.com/apt trusty main
        key_url: https://download.rethinkdb.com/apt/pubkey.gpg
```

... but it fails, as others have noted, and shows:

```
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
```

Is there something I should add to the config?

**Comment by BanzaiMan** [comment] 2019-08-03 14:58
@sholladay You are using the `apt` addon. Use the `rethinkdb` addon instead. https://docs.travis-ci.com/user/database-setup/#rethinkdb

**Comment by sholladay** [comment] 2019-08-03 16:39
@BanzaiMan Awesome, I can confirm that worked for me! I didn't know about that feature, very cool. Thanks for supporting RethinkDB. 👍

**Comment by marens101** [comment] 2019-08-03 23:46
Does this have anything to do with this issue when trying to do a fresh install?
```
The following packages have unmet dependencies:
 rethinkdb : Depends: libprotobuf9v5 but it is not installable
```

**Comment by vmahadev** [comment] 2019-08-04 09:50
ANY CONTRIBUTOR TO ANSWER OUR QUERIES?

Just a key issue. No one is responding. Guys give us access we will do the needful

**Comment by gabor-boros** [comment] 2019-08-06 21:03
@vmahadev, This is our current issue as well as I mentioned before. I'm still waiting for access. If the access is not granted by the end of tomorrow, I'll escalate the issue to have the access.

**Comment by AaronRobinson** [comment] 2019-08-09 10:31
Just in case anyone hits this, the 
`

> ci workaround
> 
> ```shell
> source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
> wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
> sudo apt-get update
> sudo apt-get -y --allow-unauthenticated install rethinkdb
> rethinkdb --bind all &

For anyone that tries this on the command line, the `sudo apt-get update` still fails but the subsequent `sudo apt-get -y --allow-unauthenticated install rethinkdb` works

**Comment by mcao** [comment] 2019-08-09 22:37
Sorry, but it's been a full month now - when will the issue be resolved? This has been a roadblock with no sign of being resolved - tests are failing, it's difficult or risky at best to install rethinkdb on new machines, and `sudo apt-get update` will not work on machines with rethinkdb installed. Major roadblock with little to no indication of being resolved right now - hope to be proven wrong with a fix shortly, but I am considering switching to couchdb or mongodb.

**Comment by gabor-boros** [comment] 2019-08-11 08:08
@mcao we just got the credentials for everything. Currently @srh is looking into resigning the packages to resolve the issue.

Unfortunately, credentials were blockers for us too, and we were not able to get them earlier. It was a thing which was out of our control.

**Comment by AaronRobinson** [comment] 2019-08-11 13:39
Great to see these being obtained and the packages resigned. More progress.

**Comment by mcao** [comment] 2019-08-11 18:55
> @mcao we just got the credentials for everything. Currently @srh is looking into resigning the packages to resolve the issue.

Thank you 👍 hope to see fix out soon

**Comment by gabor-boros** [comment] 2019-08-14 20:24
Status update:
It seems that issue will be resolved this week. No promises but we are pretty close. We will test the new download site today/tomorrow.

**Comment by gabor-boros** [comment] 2019-08-15 15:39
Dear All,

**LT;DR;**
The download should not complain about expired GPG keys anymore. 🎉 🔑 

With the huge help of @srh, we were able to spin up the new machine which will serve https://download.rethinkdb.com and did the necessary work to resolve this issue. Both of us checked it (the apt repo) and it seems to work. The Bionic package is not uploaded **yet**, but it is on its way. 🙏 

**Note about the Bionic image**
_The Bionic release can't be built off of git tag v2.3.6, so @srh is building a v2.3.7 one for this. This release contains some bug fixes which are not released for other distros yet. The plan would be to have CI/CD and release it for every distro._

**Comment by AaronRobinson** [comment] 2019-08-15 15:55
Don't forget to run
`wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -`
before 
`sudo apt update`
otherwise you'll get
```
Err:8 https://download.rethinkdb.com/apt xenial Release.gpg
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY blah blah blah
```

**Comment by gabor-boros** [comment] 2019-08-15 16:03
Thank you @AaronRobinson! I forgot to mention this.

**Comment by gabor-boros** [comment] 2019-08-15 19:29
FYI: @BanzaiMan ^

**Comment by loeffel-io** [comment] 2019-08-16 09:08
🎉

**Comment by srh** [comment] 2019-08-16 10:19
A Bionic image versioned 2.3.7 is available.

**Comment by gabor-boros** [comment] 2019-08-16 11:01
Since it seems to work, at least nobody complained, I'm closing this issue. If you feel that we missed something or the issue still exists after running `wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -` and `apt-get update` feel free to reopen the issue.

Cheers 🥂

**Closed by gabor-boros** 2019-08-16 11:01 UTC
