### ISSUE TITLE
Change feed does not work properly with slice()

### ISSUE THREAD

**Issue by coldume** [rethinkdb/rethinkdb#4500] opened 2015-07-04 15:55 UTC
To repeat the problem:
```javascript
// Run in window 1.
r.tableCreate('user')
// Run in window 2.
r.table('user').orderBy({ index: r.desc('id') }).limit(100).changes().slice(5, 10)

// Run in window 1, repeat 10 times and insert 10 records. Change feed works expected in window 2 
r.table('user').insert({ name: 'foo' })
// Run in window 1. Change feed closed and does not work in window 2 
r.table('user').delete()
```

I have tested this on linux and osx, and have the same result, change feed upaded and works as expected when inserting data, but closed when you deleting more than 5 records. Is it intended or am I doing it wrong? Thanks.

P.S, the following alternative works:

```javascript
r.table('user').orderBy({ index: r.desc('id') }).limit(10).changes().skip(5)
```

**Comment by danielmewes** [comment] 2015-07-05 06:33
That sounds like the expected behavior. It will close the changefeed after the first 10 changes. What do you expect the slice to do?

**Comment by coldume** [comment] 2015-07-05 08:27
I expected rethinkdb to notify me all these 5 records I listened were deleted, but it just close the feed sliently. Anyway, `skip()` works for me.

**Comment by danielmewes** [comment] 2015-07-06 23:20
Generally if you add terms after the `changes()` command, they will be applied to the change events themselves, and not the documents in the table. So if you add `changes().slice(5, 10)`, that means that the first five changes will be ignored, then the next 5 changes will go through, and then the feed is done.
This does not correspond to any specific documents. Those changes can come from any documents. For example you might see the insertion of document A and the deletion of document B, but not vice versa.

If you want the 5-10th place in the orderBy, your alternative with `skip` isn't going to work properly either. If after the initial results for example the top document changes, you will still get a change notification for that.

RethinkDB doesn't currently have a way of getting changes on a certain subrange of the ordered documents as far as I know. I recommend getting all 10 top results and then filtering out the top 5 of those in your own code on the client.

**Comment by danielmewes** [comment] 2015-07-07 02:14
Closing as `notabug`, but please let us know if you think that something is still not working as expected @coldume .

**Closed** 2015-07-07 02:14 UTC

**Comment by Fristi** [comment] 2015-09-30 08:39
> RethinkDB doesn't currently have a way of getting changes on a certain subrange of the ordered documents as far as I know. I recommend getting all 10 top results and then filtering out the top 5 of those in your own code on the client.

This would be useful though. Use case: ordered paginated list which is navigated by pagination controls (next, previous, page X, etc). Would it be hard to implement such a thing?

**Comment by Fristi** [comment] 2015-10-01 09:15
@danielmewes Ping :bell: (mentioning you, because I don't know if it shows up for you :smile: ). Anyway what do you think about this?

**Comment by danielmewes** [comment] 2015-10-01 20:51
I think it's not too hard. I'm going to open a new issue for the feature request.

**Comment by danielmewes** [comment] 2015-10-01 20:55
@Fristi See https://github.com/rethinkdb/rethinkdb/issues/4909

**Comment by Fristi** [comment] 2015-10-01 21:14
Thanks ! Looking forward to it!
