### ISSUE TITLE
Constantly got error "Rejected a connection from server X since one is open already."

### ISSUE THREAD

**Issue by ntquyen** [rethinkdb/rethinkdb#5456] opened 2016-02-29 06:52 UTC
I've just upgraded my rethinkdb cluster v2.2.5 with 3 instances. There are 16 tables, ~17Gb data and this error show up continuously while all 3 instances are already connected:

```
Rejected a connection from server ff02cdcb-eeff-436f-9736-381dc64163dd since one is open already.
```

And there's heartbeat timeout error in the console logs:

```
Running on Linux 4.1.5-coreos x86_64
Loading data from directory /data
Listening for intracluster connections on port 29015
Connected to server "852c7df34d76_szm" ff02cdcb-eeff-436f-9736-381dc64163dd
Connected to server "9f214c8bca8d_e69" 0f9ba78a-5ed9-49b7-9d80-fe2c9571a15a
Connected to proxy 9056eeb9-aec4-41f5-bf10-7501506bfee9
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, 172.17.0.17, ::1, fe80::42:acff:fe11:11%36
Server ready, "8fe0b3a66357_imu" f429ade8-5ffb-4ace-8491-14c07e62e5a6
Connected to proxy e43443f9-7626-40bc-9aa6-75d2fe2cbf45
Disconnected from server "9f214c8bca8d_e69" 0f9ba78a-5ed9-49b7-9d80-fe2c9571a15a
Connected to server "9f214c8bca8d_e69" 0f9ba78a-5ed9-49b7-9d80-fe2c9571a15a
error: Heartbeat timeout, killing connection to peer [::ffff:192.168.167.231]:45931
Disconnected from server "9f214c8bca8d_e69" 0f9ba78a-5ed9-49b7-9d80-fe2c9571a15a
Connected to server "9f214c8bca8d_e69" 0f9ba78a-5ed9-49b7-9d80-fe2c9571a15a
```

I'm using docker 1.7.1 in CoreOS v773.0.0 to run my rethinkdb cluster. 

```
$ uname -a
Linux coreos-data-3 4.1.5-coreos #2 SMP Thu Aug 13 09:18:45 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz GenuineIntel GNU/Linux
```

**Comment by danielmewes** [comment] 2016-02-29 20:18
@ntquyen Thanks for the report.
A few questions:
- Which version were you running before?
- Apart from printing the warning over and over, does the database work properly?
- Does the issue go away if you restart the servers?

**Comment by ntquyen** [comment] 2016-03-01 01:09
@danielmewes Thanks for answering. My answer to your questions:

- Before I'm running version 2.2.3
- The data still working properly while that error appeared
- I haven't tried restart the node yet

By the way, I stop getting that error a few hours after I posted the issue.

**Comment by danielmewes** [comment] 2016-03-01 01:18
Ok we will investigate. It might be that some server(s) somehow got confused about which other servers they were already connected to. Right now this doesn't seem critical, but we should keep an eye on it.

**Comment by ntquyen** [comment] 2016-03-04 10:38
I'm getting that log again. It seem to happen after a heartbeat timeout and connections were killed between every nodes

**Comment by danielmewes** [comment] 2016-03-04 20:26
Thanks for the update @ntquyen .
I was able to get this message in a quick test after a heartbeat timeout, but it stops quickly for me once the servers are fully connected again (that behavior is pretty much expected with the current implementation).
Is it still printing the message continuously for you @ntquyen ?

To find the timestamp of the heartbeat timeout, you can grep the RethinkDB log file. You'll find it in the RethinkDB data folder of that node (or in a different location in case you explicitly specified another log file path).

**Comment by ntquyen** [comment] 2016-03-04 23:50
@danielmewes Yes, it still keeps printing the message continuously for over 20 hours and doesn't stop yet. This is the log in i tail in `log_file`
```
$ tail log_file
2016-03-04T23:47:46.640893098 490373.345862s info: Rejected a connection from server **** since one is open already.
2016-03-04T23:47:48.641090001 490375.346059s info: Rejected a connection from server **** since one is open already.
2016-03-04T23:47:49.337096066 490376.042065s info: Rejected a connection from server **** since one is open already.
2016-03-04T23:47:51.337272540 490378.042242s info: Rejected a connection from server **** since one is open already.
2016-03-04T23:47:56.410329619 490383.115299s info: Rejected a connection from server **** since one is open already.
2016-03-04T23:47:58.135267241 490384.840236s info: Rejected a connection from server **** since one is open already.
2016-03-04T23:47:58.454921951 490385.159891s info: Rejected a connection from server **** since one is open already.
2016-03-04T23:48:00.135373147 490386.840342s info: Rejected a connection from server **** since one is open already.
2016-03-04T23:48:12.603472958 490399.308442s info: Rejected a connection from server **** since one is open already.
2016-03-04T23:48:14.603565349 490401.308534s info: Rejected a connection from server **** since one is open already.
2016-03-04T23:48:19.905230539 490406.610200s info: Rejected a connection from server **** since one is open already.
2016-03-04T23:48:21.905325126 490408.610294s info: Rejected a connection from server **** since one is open already.
2016-03-04T23:48:26.666927455 490413.371897s info: Rejected a connection from server **** since one is open already.
2016-03-04T23:48:28.135466900 490414.840436s info: Rejected a connection from server **** since one is open already.
```

**Comment by vyerukon** [comment] 2016-03-09 21:44
We have a 9 node cluster with rethinkdb 2.2.4 and seeing the same error in the logs

2016-03-02T14:05:56.553092829 690944.959671s notice: Disconnected from server "XXXXX" 5f9a754d-8b70-47a3-9fff-dea23bc4fd00
2016-03-02T14:05:56.565463416 690944.972041s notice: Disconnected from server "XXXXX" 83e9ae96-5764-4e7b-97d5-0de81f8d9da7
2016-03-02T14:05:56.565487260 690944.972065s notice: Disconnected from server "XXXXX" d8979f5d-98a8-4200-b514-08e03938792f
2016-03-02T14:05:56.565492984 690944.972071s notice: Disconnected from proxy ad97b5f8-dfed-4aa0-8ff3-3ec6d06b62be
2016-03-02T14:05:56.565507994 690944.972086s notice: Disconnected from server "XXXXX" 0dc6de3d-4859-446b-8f67-09eaf8eecc42
2016-03-02T14:05:57.638735975 690946.045315s info: Rejected a connection from server 75863c38-3765-4284-a675-3fcf645876ae since one is open already.
2016-03-02T14:06:00.303944219 690948.710523s info: Rejected a connection from server 75863c38-3765-4284-a675-3fcf645876ae since one is open already.
2016-03-02T14:06:00.303957535 690948.710535s info: Rejected a connection from server 75863c38-3765-4284-a675-3fcf645876ae since one is open already.
2016-03-02T14:06:00.304033269 690948.710611s info: Rejected a connection from server 75863c38-3765-4284-a675-3fcf645876ae since one is open already.

**Comment by danielmewes** [comment] 2016-03-09 22:01
@vyerukon Thanks for letting us know. The logic around this was changed a bit in RethinkDB 2.2.5, so upgrading might fix this for you. It's also worth noting that occasionally seeing this message after a temporary disconnect is normal (note that it's only an "info", not a warning or error).

The weird thing that this bug is about is that it keeps on happening over an extended period of time.

**Comment by danielmewes** [comment] 2016-03-09 22:01
@ntquyen We haven't made any progress on understanding this yet btw.
Does it still print the message after more than 24 hours?

**Comment by stellanhaglund** [comment] 2016-03-10 16:08
Hi I seem to have the same problem, the db I'm experiencing this with is placed in a docker container and running 2.2.5, I also tried with another db that is not running in docker and has version 2.2.1 and there I'm not getting the error.

**Comment by stellanhaglund** [comment] 2016-03-10 16:13
and the node application I'm trying to run gives me this, Unhandled rejection ReqlDriverError: Could not connect to *.*.*.* so I'm not able to start my application

**Comment by stellanhaglund** [comment] 2016-03-10 16:23
Seems I forgot to bind the port to the docker container but it still gave me that issue, so the problems gone for me now.

**Comment by ntquyen** [comment] 2016-03-14 07:05
@danielmewes Sorry for late reply, I keep getting that error. And yes, for more than 24 hours. One thing to note that on instance is running on a CoreOS node that uses bonding NIC, mode 0 (round robin) in front of two physical NICs. And every one in a few days, one physical NIC is down and up for a ~1 minute.

**Comment by ntquyen** [comment] 2016-03-14 17:17
Another notice I've just dicovered: I have a bunch of rethinkdb proxies joined to ther cluster and in everyone of those, their `log_file` is constantly printing `info: Rejected a connection from server `[server-id]` since one is open already.` The `server-id`s are not listed in table `server_config` so I guess they are ids of the proxies. I can replicate the issue easily in different CoreOS environments: Run one-server rethinkdb cluster, and have about 10 rethinkdb proxies joining to the cluster. Check their log_file. 

All inside docker container.

**Comment by danielmewes** [comment] 2016-03-14 18:16
Thanks for the additional info @ntquyen .

I'm not familiar with bonding NICs. Does that mean that the server has two different IP addresses (which should be fine)? Or is this below the IP level?

Regarding the proxies: In the test with 10 proxies, are you running all of them on the same container, or each one in a separate container?

I think we currently don't print the proxy ID anywhere. I opened https://github.com/rethinkdb/rethinkdb/issues/5515 to address this in a future release.

**Comment by encryptio** [comment] 2016-03-14 20:28
In the help slack channel, @rosskukulinski had a similar issue (repeated "rejected connection ... because one is open already", bad connectivity inside the cluster) when running RethinkDB inside Kubernetes; Kubernetes has a complex networking system and ends up with each `rethinkdb` process on its own dynamically allocated IP (different from the node's IP), in addition to many other IPs.

He was able to solve it by setting the `canonical-address` config setting to the IP that was supposed to be accessible by the other cluster members.

**Comment by ntquyen** [comment] 2016-03-15 07:44
@danielmewes That's correct, the bonding NIC is load balancing (round robin) between 2 physical NICs which each has different IP, it just works the same as normal NIC (though I'm not sure if it's exactly the same) This is the related documentation I followed: https://coreos.com/os/docs/latest/network-config-with-networkd.html

For the proxies, I'm running it inside each kubernetes pod, along with a microservice that it serves requests. For example, I have microservice A and a rethinkdb proxy running in a same kubernetes pod so that A can connect to the proxy via `localhost:28015`. And I have ~20 pods like that.

@encryptio Thanks for your response. However my rethinkdb cluster is outside kubernetes. I used to put it inside kubernetes, but i was very painful, simply setting `canonical-address` can make it work, yes, but the performance is very poor. And I don't see any benefit to put it inside k8s after all.

**Comment by danielmewes** [comment] 2016-03-17 21:16
I've finally been able to reproduce this thanks to some additional info from @ntquyen .

I can trigger the described behavior by:
1. Starting two servers, say with `-o 0 -j localhost` and `-o 1 -j localhost`
2. Starting a proxy with two `-j` parameters: `-o 2 -j localhost -j localhost:29016`
3. Shutting down the proxy and restarting it with the same parameters again

**Comment by danielmewes** [comment] 2016-03-18 00:43
Working on a solution...

**Comment by danielmewes** [comment] 2016-03-19 00:44
A fix is in internal code review 3536.

**Comment by danielmewes** [comment] 2016-03-22 19:24
Fixed in v2.2.x via commit 0a70be3 , and in next via 19cbfdd.

**Comment by ntquyen** [comment] 2016-04-20 09:23
@danielmewes I've just upgraded my cluster from 2.2.5 to 2.2.6 but I still got error 
```
Rejected a connection from server 1f360f0b-a209-4e63-a43b-3dfdc629520a since one is open already.
```

Here how to reproduce it:

My cluster has only one instance, and I have some rethinkdb proxies connecting to it.

rethinkdb container running outside kubernetes:
```
"Cmd": [
      "rethinkdb",
      "-d",
      "/data",
      "--cache-size",
      "2000",
      "--bind",
      "all",
      "--canonical-address",
      "10.9.8.2:29015"
],
```

Each rethinkdb proxy runs in a kubernetes pod with my app container and bind to `localhost` so that my app can connect to the cluster via `localhost:28015`

```
- command:
    - rethinkdb
    - proxy
    - --join
    - 10.9.8.2:29015
```

A weird thing I see from the proxies `log_file` is that all proxies have the same uuid (`15f81be4-d716-4242-be1e-fb9237bf706f`):

**proxy 1 log_file:**
```
2016-04-20T07:39:04.036435371 0.490353s notice: Connected to server "b183f782f348_6pb" 1f360f0b-a209-4e63-a43b-3dfdc629520a
2016-04-20T07:39:04.038912451 0.492829s notice: Listening for client driver connections on port 28015
2016-04-20T07:39:04.038938250 0.492855s notice: Listening for administrative HTTP connections on port 8080
2016-04-20T07:39:04.038939150 0.492856s notice: Listening on addresses: 127.0.0.1, ::1
2016-04-20T07:39:04.038942450 0.492859s notice: To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
2016-04-20T07:39:04.038944350 0.492861s notice: Proxy ready
2016-04-20T07:39:04.038946250 0.492863s info: Rejected a connection from server proxy-2f59cfa0-4201-40c8-856b-18e2fcc82b81 since one is open already.
2016-04-20T07:39:04.039361347 0.493278s info: Rejected a connection from server proxy-2f59cfa0-4201-40c8-856b-18e2fcc82b81 since one is open already.
2016-04-20T07:39:04.039677744 0.493595s info: Rejected a connection from server proxy-2f59cfa0-4201-40c8-856b-18e2fcc82b81 since one is open already.
2016-04-20T07:39:04.039996041 0.493913s info: Rejected a connection from server proxy-2f59cfa0-4201-40c8-856b-18e2fcc82b81 since one is open already.
2016-04-20T07:39:04.040381638 0.494299s info: Rejected a connection from server proxy-2f59cfa0-4201-40c8-856b-18e2fcc82b81 since one is open already.
2016-04-20T07:39:04.040647236 0.494564s info: Rejected a connection from server proxy-2f59cfa0-4201-40c8-856b-18e2fcc82b81 since one is open already.
2016-04-20T07:39:04.041056033 0.494973s notice: Connected to proxy 15f81be4-d716-4242-be1e-fb9237bf706f
```

**proxy 2 log_file:**
```
2016-04-20T07:29:54.209393541 0.554126s notice: Listening for client driver connections on port 28015
2016-04-20T07:29:54.209449040 0.554181s notice: Listening for administrative HTTP connections on port 8080
2016-04-20T07:29:54.209453340 0.554185s notice: Listening on addresses: 127.0.0.1, ::1
2016-04-20T07:29:54.209456640 0.554188s notice: To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
2016-04-20T07:29:54.209460140 0.554192s notice: Proxy ready
2016-04-20T07:29:54.213236508 0.557969s info: Rejected a connection from server proxy-cf8a3398-560c-4436-b803-dadbba0462e1 since one is open already.
2016-04-20T07:29:54.214159700 0.558892s info: Rejected a connection from server proxy-cf8a3398-560c-4436-b803-dadbba0462e1 since one is open already.
2016-04-20T07:29:54.215506388 0.560239s info: Rejected a connection from server proxy-cf8a3398-560c-4436-b803-dadbba0462e1 since one is open already.
2016-04-20T07:29:54.216138282 0.560870s info: Rejected a connection from server proxy-cf8a3398-560c-4436-b803-dadbba0462e1 since one is open already.
2016-04-20T07:29:54.216864676 0.561597s info: Rejected a connection from server proxy-cf8a3398-560c-4436-b803-dadbba0462e1 since one is open already.
2016-04-20T07:29:54.217431171 0.562163s info: Rejected a connection from server proxy-cf8a3398-560c-4436-b803-dadbba0462e1 since one is open already.
2016-04-20T07:29:54.219317855 0.564051s notice: Connected to proxy 15f81be4-d716-4242-be1e-fb9237bf706f
2016-04-20T07:29:54.232933537 0.577666s notice: Connected to server "b183f782f348_6pb" 1f360f0b-a209-4e63-a43b-3dfdc629520a
```

as you said in this comment https://github.com/rethinkdb/rethinkdb/issues/4934#issuecomment-146987871, I'm still not sure why the proxies have the same uuid. If `15f81be4-d716-4242-be1e-fb9237bf706f` is the proxy id, then what is `proxy-cf8a3398-560c-4436-b803-dadbba0462e1`?

> One possible source of issues could be that proxies right now appear to try connecting to each other.
If all of the proxies only bind to localhost, different proxies might try to establish connections to localhost to reach some of the other proxies. However there they won't find the expected other proxies, but will end up connecting to themselves of course.

I think you don't need kubernetes, using docker container networking is enough to reproduce the case

**Comment by danielmewes** [comment] 2016-04-21 00:21
@ntquyen Are the "Rejected a connection from server" messages still repeating endlessly though? A few of these log entries are normal, especially if the servers are reachable through multiple addresses (e.g. one IPv6 and one IPv4 address). But they should stop once a connection has been established.

I think `15f81be4-d716-4242-be1e-fb9237bf706f` might have been a so called peer ID which is different from the "server ID" that has the form "proxy-...". We used to print the peer ID in the "Connected to proxy" message. We changed this message recently to print the server ID as well in order to be less confusing and more useful. I forgot if we did this change in 2.2.6 or only in 2.3.0 (looks like it was in 2.3.0 based on your logs).

It's odd that the peer ID would be the same though for two proxies. Maybe both "Connected to proxy" messages are actually referring to the same proxy?

Ignoring the log messages, is everything else working fine with your setup?

**Comment by ntquyen** [comment] 2016-04-21 08:12
When I restart the server, it runs well without any `Rejected a connection...` warning, but after about 10 - 15min, the warning appears and keep printing endlessly. 

The cluster is running fine, but I really concern that warning could affect the connection between nodes in cluster. I'm also facing the issue Heartbeat timeout while the cluster (of 3 nodes) is stress (read/write continuously for 1 or 2 hours, high CPU usage, 100% cache used). But may be our internal network is not stable that could make Heartbeat timeout is more likely to happen when cluster is stressing.

**Comment by danielmewes** [comment] 2016-06-15 22:35
Sorry I didn't get back to you earlier about this @ntquyen .

It looks like @ddombrow also can still see this issue (as reported in https://github.com/rethinkdb/rethinkdb/issues/5862 ). Maybe we can find something that yours and his configuration have in common.

@ddombrow what is the type of network you are running on, and how is it configured? Are there any firewalls, routers etc. in between the servers? Do the servers have multiple network interfaces, IP addresses and/or host names that they are available under?

@ntquyen @ddombrow could you each email me the output of `r.db('rethinkdb').table('server_status')` from the affected clusters? My email address is daniel@rethinkdb.com .

**Comment by ddombrow** [comment] 2016-06-15 23:48
@danielmewes sent

**Comment by erikdubbelboer** [comment] 2016-06-16 12:04
We seem to have a similar issue. We are also using proxies. One of our instances just crashed because it was out of memory. After restarting the Google Compute Instance and starting Rethinkdb it now can't connect to the cluster.

The other nodes are printing:
```
2016-06-16T11:44:07.150754703 271622.739051s info: Rejected a connection from server 7ad6857d-a706-47a2-aa84-351a47065604 since one is open already.
```

The disconnected server is named `rethinkdb-eu-1`.

`r.db('rethinkdb').table('server_status')` looks like:
```json
{

    "id": "62117ca1-4127-4a8a-8fc9-907d7d39c0b7" ,
    "name": "rethinkdb_eu_3" ,
    "network": {
        "canonical_addresses": [
            {
                "host": "10.240.0.40" ,
                "port": 29015
            } ,
            {
                "host": "127.0.0.1" ,
                "port": 29015
            }
        ] ,
        "cluster_port": 29015 ,
        "connected_to": {
            "proxy-14b773bb-1f2e-414d-bff3-97d258602678": true ,
            "proxy-3933629d-24d4-442a-af85-e4d7e67f8f5a": true ,
            "rethinkdb_eu_2": true
        } ,
        "hostname": "rethinkdb-eu-3" ,
        "http_admin_port": 8627 ,
        "reql_port": 28015 ,
        "time_connected": Mon Jun 13 2016 08:17:20 GMT+00:00
    } ,
    "process": {
        "argv": [
            "/usr/bin/rethinkdb" ,
            "--daemon" ,
            "--config-file" ,
            "/etc/rethinkdb/instances.d/api.conf" ,
            "--runuser" ,
            "rethinkdb" ,
            "--rungroup" ,
            "rethinkdb" ,
            "--pid-file" ,
            "/var/run/rethinkdb/api/pid_file" ,
            "--directory" ,
            "/var/lib/rethinkdb/api/data"
        ] ,
        "cache_size_mb": 1024 ,
        "pid": 20598 ,
        "time_started": Sun Jun 12 2016 21:57:40 GMT+00:00 ,
        "version": "rethinkdb 2.3.4~0trusty (GCC 4.8.2)"
    }

}
{

    "id": "0200c82f-caae-4e08-9986-2729ba4b5d85" ,
    "name": "rethinkdb_eu_2" ,
    "network": {
        "canonical_addresses": [
            {
                "host": "10.240.0.52" ,
                "port": 29015
            } ,
            {
                "host": "127.0.0.1" ,
                "port": 29015
            }
        ] ,
        "cluster_port": 29015 ,
        "connected_to": {
            "proxy-14b773bb-1f2e-414d-bff3-97d258602678": true ,
            "proxy-3933629d-24d4-442a-af85-e4d7e67f8f5a": true ,
            "rethinkdb_eu_3": true
        } ,
        "hostname": "rethinkdb-eu-2" ,
        "http_admin_port": 8627 ,
        "reql_port": 28015 ,
        "time_connected": Mon Jun 13 2016 08:17:20 GMT+00:00
    } ,
    "process": {
        "argv": [
            "/usr/bin/rethinkdb" ,
            "--daemon" ,
            "--config-file" ,
            "/etc/rethinkdb/instances.d/api.conf" ,
            "--runuser" ,
            "rethinkdb" ,
            "--rungroup" ,
            "rethinkdb" ,
            "--pid-file" ,
            "/var/run/rethinkdb/api/pid_file" ,
            "--directory" ,
            "/var/lib/rethinkdb/api/data"
        ] ,
        "cache_size_mb": 1024 ,
        "pid": 3555 ,
        "time_started": Mon Jun 13 2016 08:17:20 GMT+00:00 ,
        "version": "rethinkdb 2.3.4~0trusty (GCC 4.8.2)"
    }

} 
```

The log of the restarted server only contains:
```
2016-06-16T11:52:44.752638460 0.178866s notice: Running rethinkdb 2.3.4~0trusty (GCC 4.8.2)...
2016-06-16T11:52:44.755037005 0.181263s notice: Running on Linux 3.19.0-61-generic x86_64
2016-06-16T11:52:44.755086672 0.181311s notice: Loading data from directory /var/lib/rethinkdb/api/data
2016-06-16T11:52:44.829914648 0.256141s info: Cache size is set to 1024 MB
2016-06-16T11:52:44.834214488 0.260438s notice: Listening for intracluster connections on port 29015
2016-06-16T11:52:44.834417784 0.260642s info: Attempting connection to 2 peers...
```

**Comment by ntquyen** [comment] 2016-06-16 15:56
@danielmewes Sorry we are still using 2.5.5 on the affected cluster... And one good thing to note that we haven't experienced the issue anymore for the clusters that stop using proxies.

**Comment by ddombrow** [comment] 2016-06-16 15:58
Update: I updated the rethink config with the canonical address and restarted service, seemed to fix the issue at least for now.  Will report back if it reoccurs.

**Comment by danielmewes** [comment] 2016-06-16 19:18
@erikdubbelboer The node being unable to reconnect and the warnings being printed even though the node isn't currently connected is concerning. That sounds like there's some race condition in our code.
You can probably work-around the issue for the moment by restarting the other servers in the cluster.
Once the cluster is back up, could you also email me the output of `r.db('rethinkdb').table('server_status')` to daniel@rethinkdb.com? That might help us to figure out if this issue is somehow related to the network or server configuration.

@ddombrow Thanks for sending over the server output. It looks unsuspicious on first look.

**Comment by bsharpe** [comment] 2016-07-07 14:57
e.g. Node has been up for an hour and the logs are doing this:
```
2016-07-07T14:51:52.175310612 3864.922929s info: Rejected a connection from server proxy-fc089240-b81a-4833-973b-2f2f4bdfc7ce since one is open already.
2016-07-07T14:51:52.176940086 3864.924558s info: Rejected a connection from server proxy-dd4a2403-8f61-4d9e-887f-afadcb81d4fa since one is open already.
2016-07-07T14:51:52.207480029 3864.955098s info: Rejected a connection from server proxy-dd91cfbd-7eca-485a-9961-264572a6d06c since one is open already.
2016-07-07T14:51:52.305836461 3865.053455s info: Rejected a connection from server proxy-0a3776e9-d71d-4392-b187-9121dfd7d651 since one is open already.
2016-07-07T14:51:55.791137583 3868.538756s info: Rejected a connection from server cc141080-d077-4e55-bd58-d8bbd752ee83 since one is open already.
2016-07-07T14:52:00.460705955 3873.208324s info: Rejected a connection from server ae6b6a25-c66b-492b-a9d9-369dcb6e4659 since one is open already.

2016-07-07T14:52:07.177477231 3879.925095s info: Rejected a connection from server proxy-fc089240-b81a-4833-973b-2f2f4bdfc7ce since one is open already.
2016-07-07T14:52:07.178426052 3879.926044s info: Rejected a connection from server proxy-dd4a2403-8f61-4d9e-887f-afadcb81d4fa since one is open already.
2016-07-07T14:52:07.210945178 3879.958563s info: Rejected a connection from server proxy-dd91cfbd-7eca-485a-9961-264572a6d06c since one is open already.
2016-07-07T14:52:07.305481818 3880.053100s info: Rejected a connection from server proxy-0a3776e9-d71d-4392-b187-9121dfd7d651 since one is open already.
2016-07-07T14:52:10.805851603 3883.553469s info: Rejected a connection from server cc141080-d077-4e55-bd58-d8bbd752ee83 since one is open already.
2016-07-07T14:52:15.460833229 3888.208456s info: Rejected a connection from server ae6b6a25-c66b-492b-a9d9-369dcb6e4659 since one is open already.

2016-07-07T14:52:22.166643587 3894.914262s info: Rejected a connection from server proxy-fc089240-b81a-4833-973b-2f2f4bdfc7ce since one is open already.
2016-07-07T14:52:22.169767556 3894.917385s info: Rejected a connection from server proxy-dd4a2403-8f61-4d9e-887f-afadcb81d4fa since one is open already.
2016-07-07T14:52:22.239701312 3894.987319s info: Rejected a connection from server proxy-dd91cfbd-7eca-485a-9961-264572a6d06c since one is open already.
2016-07-07T14:52:22.312208802 3895.059827s info: Rejected a connection from server proxy-0a3776e9-d71d-4392-b187-9121dfd7d651 since one is open already.
2016-07-07T14:52:25.794674958 3898.542293s info: Rejected a connection from server cc141080-d077-4e55-bd58-d8bbd752ee83 since one is open already.
2016-07-07T14:52:30.460458426 3903.208076s info: Rejected a connection from server ae6b6a25-c66b-492b-a9d9-369dcb6e4659 since one is open already.
```
The other 2 node were restarted 10 hrs ago...

**Comment by marcusnielsen** [comment] 2016-08-21 14:26
I have gotten a bunch of these messages over a period of 3h.

```
Rejected a connection from server a94d1c1a-af95-4528-82a8-4c0abc6936d5 since one is open already.
Posted by a430f283b759_0iw
```

I followed https://github.com/stefanprodan/aspnetcore-dockerswarm/wiki/RethinkDB-Swarm on a local docker-machine virtualbox so it can very well be reproducable.

Unfortunately, we are just evaluating rethinkdb, so I don't know how much I can help with more info.

**Comment by danielmewes** [comment] 2016-08-22 17:51
We found that in some network configurations, servers attempt to connect to another server via a loopback address and then end up connecting to themselves instead. This used to be ignored, but in recent versions generates the "Rejected a connection from server ... since one is open already" message.

This isn't actually harmful, other than adding unnecessary noise to the logs.

The problem will eventually be fixed by https://github.com/rethinkdb/rethinkdb/pull/5720 , but we might ship a smaller patch for 2.3.x before that.

**Comment by danielmewes** [comment] 2016-08-22 18:26
The self-connect case is now handled via 50578bf. The patch will ship with RethinkDB 2.3.5.

This change is intentionally not merged into `next`, because it will be superseded by #5720 there.

**Comment by danielmewes** [comment] 2016-08-22 18:27
There might still be some cases other than the self-connect one. We'll re-open this if it comes up again after 2.3.5.

**Closed by danielmewes** 2016-08-22 18:26 UTC
Labels: tp:bug

**Comment by danielmewes** [comment] 2016-08-22 18:27
(this was internal code review number 3731)

**Comment by alf** [comment] 2016-10-31 14:32
We're seeing this in 2.3.5. :(
