### ISSUE TITLE
[feature] rethinkdb import from STDIN

### ISSUE THREAD

**Issue by kwando** [rethinkdb/rethinkdb#5262] opened 2016-01-07 07:13 UTC
It would be _nice_ to be able to pipe data into the import tool.

**Comment by danielmewes** [comment] 2016-01-08 02:08
Thanks for opening an issue. This is a duplicate of https://github.com/rethinkdb/rethinkdb/issues/3838

**Closed by danielmewes** 2016-01-08 02:08 UTC
