### ISSUE TITLE
db.table('table').delete() locks database

### ISSUE THREAD

**Issue by sctb** [rethinkdb/rethinkdb#3411] opened 2014-12-05 00:03 UTC
When running the above query on a large table, the
database has been unresponsive to additional 
requests for over 45 minutes so far. The RethinkDB
process has been using about 50% CPU during
this time. 

The table would have had less than 1M rows, each
with only a few fields.

**Comment by danielmewes** [comment] 2015-02-19 02:18
@sctb there's a good chance that we've found the problem with large deletes (and writes in general) blocking out reads for long periods of time.

We're working on a fix.

**Comment by danielmewes** [comment] 2015-03-26 22:37
The likely fix is going to ship with RethinkDB 2.0 FYI. It's also included in our RethinkDB 2.0 release candidate https://github.com/rethinkdb/rethinkdb/releases/tag/v2.0.0-0RC1 , though I don't recommend using that in production.

**Comment by sharipov-ru** [comment] 2015-03-27 03:11
:+1:

**Comment by danielmewes** [comment] 2015-04-16 22:03
RethinkDB 2.0 is out with a fix that often avoids blocking reads after writes in a clustered environment.

@sctb Should you find the time to re-test this with the original non-throttled query and RethinkDB 2.0, I'd be grateful to hear if the issue is actually gone.

**Comment by danielmewes** [comment] 2015-04-16 22:04
I'm going to be optimistic and close this, but we should re-open the issue in case there are remaining problems.

**Closed by danielmewes** 2015-04-16 22:04 UTC
Labels: pr:high, tp:performance

**Comment by sctb** [comment] 2015-04-16 22:15
@danielmewes Congrats on the release! I probably won't
go back and test this dataset again, but I'm glad it seems
to be resolved.

**Comment by danielmewes** [comment] 2015-04-16 22:21
@sctb Thanks, also for all your help in tracking down this issue!
