### ISSUE TITLE
r.and(r.args()) inconsistencies in 2.3

### ISSUE THREAD

**Issue by meenie** [rethinkdb/rethinkdb#5821] opened 2016-06-02 21:36 UTC
I'm getting some inconsistencies when using `r.args()` with `r.and()`.  Here is some reproducible code:
```javascript
const data = [
  {
    "sub_doc":[
      {
        "sub_field_id": 1
      },
      {
        "sub_field_id":2,
        "text":"some text"
      }
    ],
  }
];

r.expr(data)
  .filter(row =>
    row('sub_doc').contains(doc => {
      const firstCond = doc('sub_field_id').eq(2);
      const secondCond = doc('text').match(`(?i)TEXT`);

      return r.and(r.args([firstCond, secondCond]));
      //return r.and(firstCond, secondCond)
      // This does work, though.  Which I assumed was analogous to r.args()
      //return r.and.apply(null, [firstCond, secondCond])
    })
  )
```

This should return the supplied data, but does not.  If you uncomment the second return and comment out the first, it will work.

If you add something like `"text": "whatever"` as a sibling to `"sub_field_id": 1`, both statements will work.  Also, note that if you change both conditions to the constant `true`, it will work in either form of the data.

**Comment by danielmewes** [comment] 2016-06-02 23:13
Ohhh I understand what's happening here. Using `r.args` breaks the lazyness / short-circuit property of `r.and`. I'm not sure if this is necessarily a bug, but definitely something we need to document (if it isn't easy to change).

More specifically, for the first sub_doc
```js
{
    "sub_field_id": 1
}
```
the `firstCond` evaluates to `false`. So `r.and` will not even evaluate `secondCond` for this document. However if we use `r.args`, both `firstCond` and `secondCond` will be evaluated immediately. Evaluating `secondCond` throws a missing attribute exception, because the `text` field does not exist in the document. This breaks out of the `contains`, and causes the `filter` to skip the whole input.

**Comment by danielmewes** [comment] 2016-06-02 23:14
Ah I don't think it can be changed easily because `r.args` takes an array, and an array will always need to be evaluated eagerly.

I'll open an issue to document this for `r.args`.

**Comment by meenie** [comment] 2016-06-02 23:20
Okay, that makes a ton of sense!  If you add a `.default('')` before `.match(`(?i)TEXT`)` it works.

**Comment by danielmewes** [comment] 2016-06-03 00:32
I opened a documentation issue at https://github.com/rethinkdb/docs/issues/1136 . Closing this since it's actually not a bug.

**Closed by danielmewes** 2016-06-03 00:32 UTC
Labels: cp:reql, tp:bug
