### ISSUE TITLE
Suggestion: Move drivers to individual repositories

### ISSUE THREAD

**Issue by kethomassen** [rethinkdb/rethinkdb#4941] opened 2015-10-11 01:42 UTC
Spend a while looking for the code of the ruby driver, only to realise it was in the main repository under a different folder.

I think it would be a much much better practice to move individual drivers to their own repositories, in order to sort pull requests/issues more easily and also so finding them is easier.

Just my 2 cents!

**Comment by danielmewes** [comment] 2015-10-12 17:59
Thanks for the suggestion @kethomassen . We've discussed this before and decided for now to keep the drivers together with the server, since it simplifies testing and maintenance for us.

We'll probably move the drivers out eventually, once there are more of them and changes to ReQL become rare.

Closing as duplicate of https://github.com/rethinkdb/rethinkdb/issues/1740

**Closed by danielmewes** 2015-10-12 17:59 UTC
