### ISSUE TITLE
Web interface broken on Chrome v49

### ISSUE THREAD

**Issue by micky2be** [rethinkdb/rethinkdb#5300] opened 2016-01-20 01:48 UTC
Getting a "Uncaught SyntaxError: Unexpected end of input" error with Chrome 49.0.2621.0 (canary).
Which block completely the access of the database.

**Comment by dalanmiller** [comment] 2016-01-20 02:05
@micky2be Could you provide some line numbers? Or the traceback you get in the browser? That would help a lot!

**Comment by danielmewes** [comment] 2016-01-20 02:39
@micky2be Is this working with other browsers on the same machine?

What is your network setup? Is the RethinkDB server running locally or on a different machine?

**Comment by micky2be** [comment] 2016-01-20 10:41
It's working on Chrome 47.x for sure. 
The server is local. 

I'll give you a stacktrace asap.

**Comment by danielmewes** [comment] 2016-01-21 01:34
Just installed the latest unstable Chrome, and I can reproduce this on `49.0.2623.0 dev`

**Comment by danielmewes** [comment] 2016-01-21 02:27
We appear to be affected by https://bugs.chromium.org/p/v8/issues/detail?id=4665 because we use node.js' `Buffer` implementation.

That makes the `slice` call in this line `responseBuffer = this.buffer.slice(12, responseLength + 12);` fail. (this.buffer is of type `Uint8Array`, but with annotations that swap out the `slice` implementation by the one from `Buffer` as far as I can tell).

**Comment by danielmewes** [comment] 2016-01-21 02:35
If I understand correctly, the plan on the side of Google is to implement a fall back for compatibility with existing code (https://bugs.chromium.org/p/v8/issues/detail?id=4665#c17).

We should also watch https://github.com/nodejs/node/issues/4701 and update our dependencies once node.js has an updated implementation, or hack around it in some other way.

**Comment by littledan** [comment] 2016-01-21 03:10
Are you still seeing this issue? I thought it's fixed in recent Canary builds.

**Comment by danielmewes** [comment] 2016-01-21 03:27
@littledan I saw it on 49.0.2623.0 dev. Do you think that should have the fix?

**Comment by littledan** [comment] 2016-01-21 05:47
Ehh, oops, if it made it to dev, sounds like I need a backport. Thanks a lot for this bug report!

**Comment by danielmewes** [comment] 2016-01-21 20:03
Thanks for chiming in and looking into it @littledan!

**Comment by danielmewes** [comment] 2016-02-19 20:55
This is working again in Chrome 50.0.2652.0 dev.

I'll open a new issue to update our `Buffer` implementation when it's updated in `node.js`.

**Closed by danielmewes** 2016-02-19 20:55 UTC
Labels: cp:web-ui, pr:high, tp:bug

**Comment by AtnNn** [comment] 2017-07-23 02:43
A fix for this issue has been released in [RethinkDB 2.3.6](https://rethinkdb.com/blog/2.3.6-release/)
