### ISSUE TITLE
Javascript driver DeprecationWarning - Buffer in node v7

### ISSUE THREAD

**Issue by matth3wga0** [rethinkdb/rethinkdb#6161] opened 2016-10-28 12:37 UTC
Almost the same issue happened to the rethinkdb javascript driver.

```shell
node --trace-deprecation main.js

DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
    at Buffer (buffer.js:79:13)
    at Socket.<anonymous> (/node_modules/rethinkdb/net.js:550:55)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:10)
```

Ref: https://github.com/neumino/rethinkdbdash/issues/304

**Comment by chrisvariety** [comment] 2016-10-28 13:06
Thanks @matth3wga0 this is a duplicate of https://github.com/rethinkdb/rethinkdb/pull/6144

**Comment by marshall007** [comment] 2016-10-28 20:30
Closing as duplicate.

**Closed by marshall007** 2016-10-28 20:30 UTC
