### ISSUE TITLE
Prefixed UUID and sharding

### ISSUE THREAD

**Issue by LMnet** [rethinkdb/rethinkdb#5342] opened 2016-02-02 10:13 UTC
We are using prefixed UUID as a primary key in our schema, For example: `User:86d6444e-c3e6-4131-9a35-dac2a1780af8`. Can it somehow worsen id distribution accross shards or decrease performance? Or it absolutely unrelated to the id nature, I can use any unique strings and have the same id qualities?

**Comment by thelinuxlich** [comment] 2016-02-02 13:31
Yes it can, Rethinkdb does range sharding, so you'd need to periodically run rebalance() on your tables(and lose availability during the process)

**Comment by LMnet** [comment] 2016-02-02 14:43
So, all we can do now is change our ids and wait for #364, right?

**Comment by thelinuxlich** [comment] 2016-02-02 14:48
If you really need that prefix, yes :(

**Comment by thelinuxlich** [comment] 2016-02-02 14:49
Can you explain your need? Maybe I can think of a solution

**Comment by LMnet** [comment] 2016-02-02 15:29
We use RethinkDB with Scala. We have an `Id` class:
```case class Id[+T](id: UUID, klass: String)```
`+T`  is covariant type. For example, if we have:
```
class A
class B extends A
class C extennds A
```
So, `Id[A]` could be `Id[B]` or `Id[C]`.

In some of our tables we store `Id` of base type, not concrete. And sometimes we need to understand, what is concrete type of this `Id`. That's why we use this prefixes. For my example above, ids would looks like this:
```
B:082a7808-16cf-4f56-bf07-e2c2f8e248ca
C:bddef1af-2546-4a53-8817-da5199cd3e65
```

This works perfectly for our needs. But I tested sharding and noticed, that documents distibution across shards is not uniform. `rebalance()` solve this problem, but it's not suitable solution for production.

**Comment by thelinuxlich** [comment] 2016-02-02 15:31
if this prefix is used just to retrieve the document you can wrap your id in a UUIDv5:

r.uuid("B": + id)

And then you're back at good distribution

**Comment by danielmewes** [comment] 2016-02-02 20:19
Another alternative could be using a suffix instead of a prefix:
`86d6444e-c3e6-4131-9a35-dac2a1780af8:User`

That way you avoid an impact on the shard distribution.

As long as the ratios in how frequent the different prefixes are remains approximately the same over time, I think the issue isn't that big in the first place though. You should run `rebalance` once after inserting a representative sample of these documents, but after that shards should remain approximately balanced.

**Comment by danielmewes** [comment] 2016-02-02 20:47
Closing since this is not a bug or feature request. @LMnet let us know if you have more questions.

**Closed by danielmewes** 2016-02-02 20:47 UTC

**Comment by LMnet** [comment] 2016-02-03 04:40
@thelinuxlich It will not work for my case. UUID v5 namespaces are hashed. But I need to get namespaces in original form from id.
@danielmewes suffix idea sounds good, I will try it, thanks.
