### ISSUE TITLE
Make rethinkdbdash the official JS driver

### ISSUE THREAD

**Issue by Extarys** [rethinkdb/rethinkdb#6490] opened 2017-09-10 05:05 UTC
It might be confusing for new users since the doc in the official client driver suggest to install [rethinkdb](https://www.npmjs.com/package/rethinkdb), but the RethinkDB's blog put examples with `rethinkdbdash`.

Also, `rethinkdb` doesn't seem to be maintained anymore and `rethinkdbdash` still receive love,. It  have more options/functionality than the "official" `rethinkdb` driver.

This is just my thoughts as it does look _wierd_ using a non official driver on the official website.
See :
[How to validate user input in a NoSQL web application](https://www.rethinkdb.com/blog/validation-techniques/)

**Comment by robertjpayne** [comment] 2017-09-10 11:17
This is a dupe of #3771

**Comment by Extarys** [comment] 2017-09-11 01:03
I didn't see that sorry, my point still remain since both are used on the official website.

**Closed** 2017-09-12 13:48 UTC
