### ISSUE TITLE
Build a full and incremental backup command-line tool

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#89] opened 2012-11-20 00:34 UTC
I'm referencing this issue from the FAQ, so we can discuss architectural alternatives and track progress together with users.

**Comment by danielmewes** [comment] 2016-07-05 21:38
Closing the remaining part (incremental backup) as a duplicate of https://github.com/rethinkdb/rethinkdb/issues/5890 .

**Closed by danielmewes** 2016-07-05 21:38 UTC
Labels: tp:enhancement
