### ISSUE TITLE
error: Error in src/rdb_protocol/profile.cc at line 241

### ISSUE THREAD

**Issue by hwestbrook** [rethinkdb/rethinkdb#4430] opened 2015-06-18 23:20 UTC
rethinkdb server crashing on Ubuntu 14.04 with the following query when limit is changed to 1000: 

r.db('windMachine').table('Readings')
	.between(r.now().sub(1*60*60*24), r.now(), {index: "date"})
	.limit(100)
  .update({
    customerID: '688e4f39-3812-4d19-be33-47f9e3aea13c'
})

Same behavior does not exist on a retina MBP. Would this be related to low memory availability on a T1.micro instance?

2015-06-18T22:59:51.794852472 322.695876s error: Error in src/rdb_protocol/profile.cc at line 241:
2015-06-18T22:59:51.794920461 322.695944s error: Guarantee failed: [stop]
2015-06-18T22:59:51.794946210 322.695969s error: Backtrace:
2015-06-18T22:59:52.102475287 323.003506s error: Thu Jun 18 22:59:51 2015\n\n1: backtrace_t::backtrace_t() at ??:?\n2: format_backtrace(bool) at ??:?\n3: report_fatal_error(char const*, int, char const*, ...) at ??:?\n4: profile::duration(std::vector<boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > const&) at ??:?\n5: profile::sampler_t::new_sample() at ??:?\n6: do_a_replace_from_batched_replace(auto_drainer_t::lock_t, fifo_enforcer_sink_t*, fifo_enforcer_write_token_t const&, btree_loc_info_t const&, one_replace_t, ql::configured_limits_t const&, promise_t<superblock_t*>*, rdb_modification_report_cb_t*, bool, ql::datum_t*, profile::sampler_t*, profile::trace_t*, std::set<std::string, std::less<std::string>, std::allocator<std::string> >*) at ??:?\n7: std::_Function_handler<void (), std::_Bind<void (*(auto_drainer_t::lock_t, fifo_enforcer_sink_t*, fifo_enforcer_write_token_t, btree_loc_info_t, one_replace_t, ql::configured_limits_t, promise_t<superblock_t*>*, rdb_modification_report_cb_t*, bool, ql::datum_t*, profile::sampler_t*, profile::trace_t*, std::set<std::string, std::less<std::string>, std::allocator<std::string> >*))(auto_drainer_t::lock_t, fifo_enforcer_sink_t*, fifo_enforcer_write_token_t const&, btree_loc_info_t const&, one_replace_t, ql::configured_limits_t const&, promise_t<superblock_t*>*, rdb_modification_report_cb_t*, bool, ql::datum_t*, profile::sampler_t*, profile::trace_t*, std::set<std::string, std::less<std::string>, std::allocator<std::string> >*)> >::_M_invoke(std::_Any_data const&) at ??:?\n8: coro_pool_t<std::function<void ()> >::worker_run(std::function<void ()>, auto_drainer_t::lock_t) at ??:?\n9: callable_action_instance_t<std::_Bind<std::_Mem_fn<void (coro_pool_t<std::function<void ()> >::*)(std::function<void ()>, auto_drainer_t::lock_t)> (coro_pool_t<std::function<void ()> >*, std::function<void ()>, auto_drainer_t::lock_t)> >::run_action() at ??:?\n10: coro_t::run() at ??:?
2015-06-18T22:59:52.102817586 323.003841s error: Exiting.

Running rethinkdb 2.0.3~0trusty (GCC 4.8.2)...
Running on Linux 3.13.0-36-generic x86_64

**Comment by danielmewes** [comment] 2015-06-19 02:29
Thank you for the bug report @hwestbrook .
This doesn't look like a typical out of memory problem.
Does this happen every time you run the query or only intermittently?

Looking at the code, I believe that the way we use the profiler in `rdb_batched_replace` is wrong. We spawn multiple concurrent tasks that all add to the same profiler event log. This causes `sampler_t::new_sample()` to crash if one of the other parallel coroutines is in the middle of a profiled task.

**Comment by danielmewes** [comment] 2015-06-19 03:22
While I couldn't reproduce the crash, a likely fix for this is in code review 3004 by @mlucy .

@hwestbrook sorry for the inconvenience. How critical is this fix for you? We will release it with the next version of RethinkDB, but I could also send you a binary with the patch applied if you need it urgently.

**Comment by hwestbrook** [comment] 2015-06-19 15:59
Not a super critical fix for me. I can wait for the next version bump.

**Comment by hwestbrook** [comment] 2015-06-19 16:00
This happens every time I run the query when it encounters more than a few hundred records. Only on my t1.micro instance. on my rMBP it doesnt happen.

**Comment by danielmewes** [comment] 2015-06-19 19:11
Fixed in v2.0.x https://github.com/rethinkdb/rethinkdb/commit/619ea41769a9954861ece2a2427072aa0bb10239 and cherry-picked into `next` in 79fb0e3e7ef85addccaacc64128303a77ac9861d .

**Closed by danielmewes** 2015-06-19 19:11 UTC
Labels: pr:high, tp:bug
