### ISSUE TITLE
Consider JSON-PATCH RFC6902 for changes() stream.

### ISSUE THREAD

**Issue by jeregrine** [rethinkdb/rethinkdb#3575] opened 2015-01-15 21:58 UTC
https://tools.ietf.org/html/rfc6902

Seems weird to define a custom format for the changes feed when there is a standard around. May be a bit complex though for clients to use though, but if its kept to simple, remove/add/replace ops it wouldn't be so bad.

**Comment by mlucy** [comment] 2015-01-15 22:03
That appears to be a standard for applying a patch to a single document.  The documents sent by `changes` are instead "patches" to a set of documents, i.e. they only say to add or remove a particular document from the set rather than having to specify a path into a sub-field to be changed.  It would be cool to add support for JSON-PATCH when an element of the set has only changed by a small amount, though.  Thanks for the suggestion!

**Comment by jeregrine** [comment] 2015-01-15 22:05
@mlucy I was thinking it would be a good fit for the query.changes() format in the next release.

**Comment by mlucy** [comment] 2015-01-15 22:15
@jeregrine : maybe I don't understand what you mean.  Let's say you've run `r.table('test').orderby(index: 'score').limit(10).changes()`, and a new player enters the top 10; what would you expect to see?  (The current format would be `{old_val: player_leaving_top_10, new_val: player_entering_top_10}`.)

I could imagine us adapting the JSON-PATCH syntax to work for sets rather than single documents, but I'm not sure it would be better than what we have.

**Comment by AtnNn** [comment] 2015-01-15 22:22
jsonpatch would make a lot of sense for point changefeeds.

If users write apps or use libraries that support jsonpatch, it might be halpful to add `.diff` and `.patch` commands that could be used for things like `.replace(lambda row: row.patch(patch))`.

However I don't get the impression that jsonpatch support and use is very widespread. Please correct me if I am wrong.

**Comment by jeregrine** [comment] 2015-01-15 23:26
@AtnNn there is some neat stuff happening with orbit.js https://github.com/orbitjs/orbit.js/tree/master around syncing js clients.

**Comment by jasonkuhrt** [comment] 2015-05-23 04:14
Without being familiar with `JSON-PATCH RFC6902` specifically I would like to see diffs modeled better in rethinkDB. For example instead of 

```
{
"new_val":{"code_name":"monkey","id":"foobar2","linked_firmware_version":"1.5.150213z"},
"old_val":{"code_name":"bamboo","id":"foobar2","linked_firmware_version":"1.5.150213z"}
}
```
something that allows me to know:

- What document `id` changed?
- What fields changed?
- What fields were removed?
- What fields were added?

I would like to go deeper into the RFC and learn about it.

Wouldn't supporting diffs provide potentially significant performance benefits for size of data-over-the-wire?

**Comment by nicolasbabel** [comment] 2015-06-19 18:01
It does provide significant performance for size, but it obviously depends on the JSON and number of changes happening. You can test level of improvements on the base of an API here : streamdata.io. Put an API into the field and a graph will give you the quantity of data saved.

**Comment by danielmewes** [comment] 2015-08-18 20:11
Closing as a duplicate of the newer https://github.com/rethinkdb/rethinkdb/issues/4707, which is slightly more precise.

**Closed by danielmewes** 2015-08-18 20:11 UTC
Labels: tp:ReQL_proposal
