### ISSUE TITLE
polyglot/datum/string crashing server in next and 2.0 branches

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4019] opened 2015-04-07 00:14 UTC
The test `./test/rql_test/test-runner polyglot/datum/string.py` is crashing the server when run. Here is the backtrace:

```
2015-04-06T17:05:18.963824177 0.412195s error: Error in src/rdb_protocol/datum.cc at line 205:
2015-04-06T17:05:18.965108124 0.413479s error: Unreachable code: 
2015-04-06T17:05:18.965968131 0.414339s error: Backtrace:
2015-04-06T17:05:19.571159531 1.019535s error: Mon Apr  6 17:05:18 2015

1: rethinkdb_backtrace(void**, int) at rethinkdb_backtrace.cc:101
2: backtrace_t::backtrace_t() at backtrace.cc:203
3: lazy_backtrace_formatter_t::lazy_backtrace_formatter_t() at backtrace.cc:283
4: format_backtrace(bool) at backtrace.cc:198
5: report_fatal_error(char const*, int, char const*, ...) at errors.cc:83
6: ql::datum_t::data_wrapper_t::destruct() at datum.cc:205
7: ql::datum_t::data_wrapper_t::~data_wrapper_t() at datum.cc:147
8: ql::datum_t::~datum_t() at datum.cc:366
9: void std::_Destroy<ql::datum_t>(ql::datum_t*) at stl_construct.h:94
10: void std::_Destroy_aux<false>::__destroy<ql::datum_t*>(ql::datum_t*, ql::datum_t*) at stl_construct.h:103
11: void std::_Destroy<ql::datum_t*>(ql::datum_t*, ql::datum_t*) at stl_construct.h:129
12: void std::_Destroy<ql::datum_t*, ql::datum_t>(ql::datum_t*, ql::datum_t*, std::allocator<ql::datum_t>&) at stl_construct.h:154
13: std::vector<ql::datum_t, std::allocator<ql::datum_t> >::~vector() at stl_vector.h:351
14: countable_wrapper_t<std::vector<ql::datum_t, std::allocator<ql::datum_t> > >::~countable_wrapper_t() at counted.hpp:287
15: void counted_release<countable_wrapper_t<std::vector<ql::datum_t, std::allocator<ql::datum_t> > > >(slow_atomic_countable_t<countable_wrapper_t<std::vector<ql::datum_t, std::allocator<ql::datum_t> > > > const*) at counted.hpp:248
16: counted_t<countable_wrapper_t<std::vector<ql::datum_t, std::allocator<ql::datum_t> > > >::~counted_t() at counted.hpp:61
17: ql::datum_t::data_wrapper_t::destruct() at datum.cc:197
18: ql::datum_t::data_wrapper_t::~data_wrapper_t() at datum.cc:147
19: ql::datum_t::datum_t(std::vector<ql::datum_t, std::allocator<ql::datum_t> >&&, ql::configured_limits_t const&) at datum.cc:303
20: ql::split_term_t::eval_impl(ql::scope_env_t*, ql::args_t*, ql::eval_flags_t) const at string.cc:265
21: ql::op_term_t::term_eval(ql::scope_env_t*, ql::eval_flags_t) const at op.cc:217
22: ql::runtime_term_t::eval(ql::scope_env_t*, ql::eval_flags_t) const at term.cc:331
23: ql::query_cache_t::ref_t::run(ql::env_t*, Response*) at query_cache.cc:279
24: ql::query_cache_t::ref_t::fill_response(Response*) at query_cache.cc:243
25: ql::run(ql::query_id_t&&, ql::protob_t<Query>, Response*, ql::query_cache_t*, signal_t*) at term.cc:250
26: rdb_query_server_t::run_query(ql::query_id_t&&, ql::protob_t<Query> const&, Response*, ql::query_cache_t*, signal_t*) at query_server.cc:48
27: /home/ssd2/larkost/rethinkdb/build/debug/rethinkdb() [0x1a695b9] at 0x1a695b9 ()
28: /home/ssd2/larkost/rethinkdb/build/debug/rethinkdb() [0x1a69722] at 0x1a69722 ()
29: /home/ssd2/larkost/rethinkdb/build/debug/rethinkdb() [0x1a68af1] at 0x1a68af1 ()
30: std::_Function_handler<void (std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*), void query_server_t::connection_loop<json_protocol_t>(linux_tcp_conn_t*, unsigned long, ql::query_cache_t*, signal_t*)::{lambda(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*)#1}>::_M_invoke(std::_Any_data const&, std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*) at functional:1780
31: std::function<void (std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*)>::operator()(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*) const at functional:2162
32: std_function_callback_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::coro_pool_callback(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*) at coro_pool.hpp:30
33: coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::worker_run(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t) at coro_pool.hpp:69
34: std::_Mem_fn<void (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::*)(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)>::operator()(coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >*, std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t) const at functional:551
35: void std::_Bind<std::_Mem_fn<void (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::*)(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)> (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >*, std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)>::__call<void, , 0, 1, 2>(std::tuple<>&&, std::_Index_tuple<0, 1, 2>) at functional:1146
36: void std::_Bind<std::_Mem_fn<void (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::*)(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)> (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >*, std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)>::operator()<, void>() at functional:1206
37: callable_action_instance_t<std::_Bind<std::_Mem_fn<void (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::*)(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)> (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >*, std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)> >::run_action() at callable_action.hpp:31
38: callable_action_wrapper_t::run() at runtime_utils.cc:43
39: coro_t::run() at coroutines.cc:207
40: coro_t* coro_t::spawn_sometime<std::_Bind<std::_Mem_fn<void (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::*)(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)> (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >*, std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)> >(std::_Bind<std::_Mem_fn<void (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::*)(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)> (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >*, std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)>&&) at coroutines.hpp:58
41: coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::on_source_availability_changed() at coro_pool.hpp:86
42: availability_control_t::set_available(bool) at passive_producer.hpp:66
43: limited_fifo_queue_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, std::list<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, std::allocator<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > > > >::push(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > const&) at limited_fifo.hpp:35
44: /home/ssd2/larkost/rethinkdb/build/debug/rethinkdb() [0x1a68d7f] at 0x1a68d7f ()
45: void save_exception<void query_server_t::connection_loop<json_protocol_t>(linux_tcp_conn_t*, unsigned long, ql::query_cache_t*, signal_t*)::{lambda()#2}>(std::__exception_ptr::exception_ptr*, std::string*, cond_t*, void query_server_t::connection_loop<json_protocol_t>(linux_tcp_conn_t*, unsigned long, ql::query_cache_t*, signal_t*)::{lambda()#2}&&) at protob.cc:477
46: void query_server_t::connection_loop<json_protocol_t>(linux_tcp_conn_t*, unsigned long, ql::query_cache_t*, signal_t*) at protob.cc:558
47: query_server_t::handle_conn(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t) at protob.cc:412
48: std::_Mem_fn<void (query_server_t::*)(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t)>::operator()(query_server_t*, scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t) const at functional:551
49: void std::_Bind<std::_Mem_fn<void (query_server_t::*)(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t)> (query_server_t*, std::_Placeholder<1>, auto_drainer_t::lock_t)>::__call<void, scoped_ptr_t<linux_tcp_conn_descriptor_t>&, 0, 1, 2>(std::tuple<scoped_ptr_t<linux_tcp_conn_descriptor_t>&>&&, std::_Index_tuple<0, 1, 2>) at functional:1146
50: void std::_Bind<std::_Mem_fn<void (query_server_t::*)(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t)> (query_server_t*, std::_Placeholder<1>, auto_drainer_t::lock_t)>::operator()<scoped_ptr_t<linux_tcp_conn_descriptor_t>&, void>(scoped_ptr_t<linux_tcp_conn_descriptor_t>&&&) at functional:1206
51: std::_Function_handler<void (scoped_ptr_t<linux_tcp_conn_descriptor_t>&), std::_Bind<std::_Mem_fn<void (query_server_t::*)(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t)> (query_server_t*, std::_Placeholder<1>, auto_drainer_t::lock_t)> >::_M_invoke(std::_Any_data const&, scoped_ptr_t<linux_tcp_conn_descriptor_t>&) at functional:1780
52: std::function<void (scoped_ptr_t<linux_tcp_conn_descriptor_t>&)>::operator()(scoped_ptr_t<linux_tcp_conn_descriptor_t>&) const at functional:2162
53: linux_nonthrowing_tcp_listener_t::handle(int) at network.cc:933
54: std::_Mem_fn<void (linux_nonthrowing_tcp_listener_t::*)(int)>::operator()(linux_nonthrowing_tcp_listener_t*, int) const at functional:551
55: void std::_Bind<std::_Mem_fn<void (linux_nonthrowing_tcp_listener_t::*)(int)> (linux_nonthrowing_tcp_listener_t*, int)>::__call<void, , 0, 1>(std::tuple<>&&, std::_Index_tuple<0, 1>) at functional:1147
56: void std::_Bind<std::_Mem_fn<void (linux_nonthrowing_tcp_listener_t::*)(int)> (linux_nonthrowing_tcp_listener_t*, int)>::operator()<, void>() at functional:1206
57: callable_action_instance_t<std::_Bind<std::_Mem_fn<void (linux_nonthrowing_tcp_listener_t::*)(int)> (linux_nonthrowing_tcp_listener_t*, int)> >::run_action() at callable_action.hpp:31
58: callable_action_wrapper_t::run() at runtime_utils.cc:43
59: coro_t::run() at coroutines.cc:207
60: void coro_t::spawn_now_dangerously<std::_Bind<std::_Mem_fn<void (linux_nonthrowing_tcp_listener_t::*)(int)> (linux_nonthrowing_tcp_listener_t*, int)> >(std::_Bind<std::_Mem_fn<void (linux_nonthrowing_tcp_listener_t::*)(int)> (linux_nonthrowing_tcp_listener_t*, int)>&&) at coroutines.hpp:52
61: linux_nonthrowing_tcp_listener_t::accept_loop(auto_drainer_t::lock_t) at network.cc:901
62: std::_Mem_fn<void (linux_nonthrowing_tcp_listener_t::*)(auto_drainer_t::lock_t)>::operator()(linux_nonthrowing_tcp_listener_t*, auto_drainer_t::lock_t) const at functional:551
63: void std::_Bind<std::_Mem_fn<void (linux_nonthrowing_tcp_listener_t::*)(auto_drainer_t::lock_t)> (linux_nonthrowing_tcp_listener_t*, auto_drainer_t::lock_t)>::__call<void, , 0, 1>(std::tuple<>&&, std::_Index_tuple<0, 1>) at functional:1146
64: void std::_Bind<std::_Mem_fn<void (linux_nonthrowing_tcp_listener_t::*)(auto_drainer_t::lock_t)> (linux_nonthrowing_tcp_listener_t*, auto_drainer_t::lock_t)>::operator()<, void>() at functional:1206
65: callable_action_instance_t<std::_Bind<std::_Mem_fn<void (linux_nonthrowing_tcp_listener_t::*)(auto_drainer_t::lock_t)> (linux_nonthrowing_tcp_listener_t*, auto_drainer_t::lock_t)> >::run_action() at callable_action.hpp:31
66: callable_action_wrapper_t::run() at runtime_utils.cc:43
67: coro_t::run() at coroutines.cc:207
68: coro_t* coro_t::spawn_sometime<std::_Bind<std::_Mem_fn<void (linux_nonthrowing_tcp_listener_t::*)(auto_drainer_t::lock_t)> (linux_nonthrowing_tcp_listener_t*, auto_drainer_t::lock_t)> >(std::_Bind<std::_Mem_fn<void (linux_nonthrowing_tcp_listener_t::*)(auto_drainer_t::lock_t)> (linux_nonthrowing_tcp_listener_t*, auto_drainer_t::lock_t)>&&) at coroutines.hpp:58
69: linux_nonthrowing_tcp_listener_t::begin_listening() at network.cc:680
70: linux_tcp_listener_t::linux_tcp_listener_t(std::set<ip_address_t, std::less<ip_address_t>, std::allocator<ip_address_t> > const&, int, std::function<void (scoped_ptr_t<linux_tcp_conn_descriptor_t>&)> const&) at network.cc:966
71: query_server_t::query_server_t(rdb_context_t*, std::set<ip_address_t, std::less<ip_address_t>, std::allocator<ip_address_t> > const&, int, query_handler_t*, unsigned int) at protob.cc:293
72: rdb_query_server_t::rdb_query_server_t(std::set<ip_address_t, std::less<ip_address_t>, std::allocator<ip_address_t> > const&, int, rdb_context_t*) at query_server.cc:18
73: do_serve(io_backender_t*, bool, base_path_t const&, metadata_persistence::cluster_persistent_file_t*, metadata_persistence::auth_persistent_file_t*, serve_info_t const&, os_signal_cond_t*) at serve.cc:361
74: serve(io_backender_t*, base_path_t const&, metadata_persistence::cluster_persistent_file_t*, metadata_persistence::auth_persistent_file_t*, serve_info_t const&, os_signal_cond_t*) at serve.cc:510
75: run_rethinkdb_serve(base_path_t const&, serve_info_t*, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> > const&, uuid_u const*, cluster_semilattice_metadata_t const*, directory_lock_t*, bool*) at command_line.cc:797
76: void std::_Bind<void (*(base_path_t, serve_info_t*, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> >, uuid_u*, cluster_semilattice_metadata_t*, directory_lock_t*, bool*))(base_path_t const&, serve_info_t*, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> > const&, uuid_u const*, cluster_semilattice_metadata_t const*, directory_lock_t*, bool*)>::__call<void, , 0, 1, 2, 3, 4, 5, 6, 7, 8>(std::tuple<>&&, std::_Index_tuple<0, 1, 2, 3, 4, 5, 6, 7, 8>) at functional:1147
77: void std::_Bind<void (*(base_path_t, serve_info_t*, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> >, uuid_u*, cluster_semilattice_metadata_t*, directory_lock_t*, bool*))(base_path_t const&, serve_info_t*, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> > const&, uuid_u const*, cluster_semilattice_metadata_t const*, directory_lock_t*, bool*)>::operator()<, void>() at functional:1206
78: std::_Function_handler<void (), std::_Bind<void (*(base_path_t, serve_info_t*, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> >, uuid_u*, cluster_semilattice_metadata_t*, directory_lock_t*, bool*))(base_path_t const&, serve_info_t*, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> > const&, uuid_u const*, cluster_semilattice_metadata_t const*, directory_lock_t*, bool*)> >::_M_invoke(std::_Any_data const&) at functional:1780
79: std::function<void ()>::operator()() const at functional:2162
80: starter_t::run_wrapper(std::function<void ()> const&) at runtime.cc:61
81: std::_Mem_fn<void (starter_t::*)(std::function<void ()> const&)>::operator()(starter_t*, std::function<void ()> const&) const at functional:551
82: void std::_Bind<std::_Mem_fn<void (starter_t::*)(std::function<void ()> const&)> (starter_t*, std::function<void ()>)>::__call<void, , 0, 1>(std::tuple<>&&, std::_Index_tuple<0, 1>) at functional:1147
83: void std::_Bind<std::_Mem_fn<void (starter_t::*)(std::function<void ()> const&)> (starter_t*, std::function<void ()>)>::operator()<, void>() at functional:1206
84: std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (starter_t::*)(std::function<void ()> const&)> (starter_t*, std::function<void ()>)> >::_M_invoke(std::_Any_data const&) at functional:1780
85: std::function<void ()>::operator()() const at functional:2162
86: callable_action_instance_t<std::function<void ()>&>::run_action() at callable_action.hpp:31
87: callable_action_wrapper_t::run() at runtime_utils.cc:43
88: coro_t::run() at coroutines.cc:207
89: coro_t* coro_t::spawn_sometime<std::function<void ()>&>(std::function<void ()>&&&) at coroutines.hpp:58
90: starter_t::on_thread_switch() at runtime.cc:57
91: linux_message_hub_t::on_event(int) at message_hub.cc:154
92: epoll_event_queue_t::run() at epoll.cc:115
93: linux_thread_pool_t::start_thread(void*) at thread_pool.cc:160
94: /lib/x86_64-linux-gnu/libpthread.so.0(+0x7e9a) [0x7fe228d7ce9a] at 0x7fe228d7ce9a (/lib/x86_64-linux-gnu/libpthread.so.0)
95: clone+0x6d at 0x7fe228aa98bd (/lib/x86_64-linux-gnu/libc.so.6)
2015-04-06T17:05:19.574489873 1.022861s error: Exiting.
```

Note: this is a little more difficult to diagnose that it should be because of #4018. If someone meeds a quick way of getting output I can provide the lines to comment out as a hacky way of getting data.

**Comment by danielmewes** [comment] 2015-04-07 00:41
@mlucy could you look into this please?

@larkost Is that backtrace from `v2.0.x` or `next`? `split` has changed in `next` due to https://github.com/rethinkdb/rethinkdb/issues/2518.

**Comment by danielmewes** [comment] 2015-04-07 00:44
Looks like `next` actually. This line number
```
20: ql::split_term_t::eval_impl(ql::scope_env_t*, ql::args_t*, ql::eval_flags_t) const at string.cc:265
```
doesn't match v2.0.x.

We should double-check that this issue exists in v2.0.x.

**Comment by mlucy** [comment] 2015-04-07 01:35
I can only reproduce this in `next`.

**Comment by danielmewes** [comment] 2015-04-07 01:36
To 2.1 then (unless @larkost you were able to reproduce this on v2.0.x?)

**Comment by mlucy** [comment] 2015-04-07 01:49
This turned out to be pretty simple, it was just a misuse of rvalue references.  There's a fix in CR 2780 by @danielmewes.

**Comment by mlucy** [comment] 2015-04-07 04:27
This is fixed in next.

**Closed by mlucy** 2015-04-07 04:27 UTC
Labels: tp:bug
