### ISSUE TITLE
limit(n).delete() sometimes skips documents

### ISSUE THREAD

**Issue by cyounkins** [rethinkdb/rethinkdb#4450] opened 2015-06-25 03:12 UTC
I'm using rethinkdbdash to run a query like so:

```javascript
r.table(tables[index])
	.between(r.minval, r.now().sub(oldestDocAge), { index: 'time' })
	.orderBy({ index: r.asc('time') })
	.limit(deleteCount)
	.delete()
	.run()
	.then(doNext)
```

Full source: https://github.com/cyounkins/purge-db/blob/master/src/index.ts

As you can see, the limit() uses a constant. Why then does the result sometimes come back:

```
{ deleted: 96,
  errors: 0,
  inserted: 0,
  replaced: 0,
  skipped: 4,
  unchanged: 0 }
```

There are inserts going on (about 50 per second), but there are no other delete operations running.

The table in question has 2 shards, 2 replicas per shard, and two indices.

**Comment by cyounkins** [comment] 2015-06-25 03:18
I forgot, this is on Rethink 2.0.3, and the table in question has about 27M docs.

**Comment by mlucy** [comment] 2015-06-25 03:37
@cyounkins -- that's very strange behavior.  I don't think that should be able to happen unless there's a `delete`/`update`/`replace` going on at the same time that deletes some of the same rows.  Is there any chance that this `delete` query is itself being run multiple times concurrently?

If not, could you try running the skipping `delete` with `{returnChanges: 'always'}` and pasting the output here?

**Comment by cyounkins** [comment] 2015-06-25 03:50
@mlucy Here is a sample response with ```{returnChanges: 'always'}```:

```
{ changes: 
   [ { new_val: null, old_val: [Object] },
     { new_val: null, old_val: [Object] },
     ...
     { new_val: null, old_val: null },
     { new_val: null, old_val: [Object] },
     ...
     { new_val: null, old_val: [Object] } ],
  deleted: 99,
  errors: 0,
  inserted: 0,
  replaced: 0,
  skipped: 1,
  unchanged: 0 }
```

**Comment by cyounkins** [comment] 2015-06-25 04:21
> Is there any chance that this delete query is itself being run multiple times concurrently?

I think that would be a problem with the promise being fulfilled before the query is done executing. I *was* able to replicate this with the official rethinkdb javascript driver, so if it is a problem with the driver it affects both.

> unless there's a delete/update/replace going on at the same time

I tried this and saw nothing except the correct deletes:

```
r.db("rethinkdb").table("jobs")
  .filter(r.row('info')('query').match("(?s)^r\.table\\(\"logs\"\\).*(delete|update|replace)"))
	.changes()
```

**Comment by mlucy** [comment] 2015-06-25 05:11
It definitely looks like the database believes something else is deleting documents in the middle of the range delete.

Is `time` a multi-index by any chance?  That would also explain this behavior.

Would you be willing to share a copy of your data with us to help debug this?  We can sign an NDA if necessary.

**Comment by cyounkins** [comment] 2015-06-25 05:29
> Is time a multi-index by any chance?

Nope, ```time``` is not a multi-index.

> Would you be willing to share a copy of your data with us to help debug this?

I cannot imagine that would be necessary. Can you try to replicate my setup first?
1. Fill table with 25M docs
2. Have script insert new docs at ~25 per second
3. Run my script linked above

**Comment by mlucy** [comment] 2015-06-27 03:57
@cyounkins -- I'm having some trouble reproducing this.

I'm setting up the table like so:
```rb
r.table_create('test').run
r.table('test').index_create('time').run
arr = []
(0...25000000).each {|i|
  arr << {id: i, time: r.epoch_time(i)}
  if arr.size >= 1000
    r.table('test').insert(arr).run(durability: 'soft')
    PP.pp i
    arr = []
  end
}
```

Then I'm inserting documents like so in a loop:
```rb
while true
  (0...25).each {|x|
    r.table('test').insert({time: r.now}).run(noreply: true)
  }
  sleep 1
end
```

And running the following query:
```js
r.table('test')
    .between(r.minval, r.now(), { index: 'time' })
    .orderBy({ index: r.asc('time') })
    .limit(100)
    .delete()
```

And I'm always seeing the following return value:
```
{
"deleted": 100 ,
"errors": 0 ,
"inserted": 0 ,
"replaced": 0 ,
"skipped": 0 ,
"unchanged": 0
}
```

I have one node with one shard and only the primary replica.

Is that the behavior you see as well with the same setup?

(I *can* reproduce the behavior you see if I run two concurrent delete queries.  Is there any chance there's a second copy of your script running somewhere by accident?)

**Comment by cyounkins** [comment] 2015-07-01 14:34
@mlucy I'll try to set up a designated test table for this problem sometime this week.

**Comment by cyounkins** [comment] 2015-07-18 20:33
I tried to create a new table, had a node process inserting documents, and another node process delete them, but was *not* able to reproduce the issue.

I went back to the table I was originally seeing this on and *was* able to reproduce it just as I did last time.
I stopped the 2 services that were writing to the table, and was *not* able to reproduce the issue. I let the script run for ~5 mins and it had no skips.
I started one service which does very few writes (<5/sec) and *was* able to reproduce the issue. It had been running for maybe 30 seconds. But then I tried it again and it took 4 mins to happen again. So this one is a bit elusive.

I tried editing one of the services to duplicate its inserts to a second test table, but I was not able to reproduce the issue on that table.

So, a few thoughts on what this could be:
1. Something else is deleting from the table, as you suggested. While this seems most likely, I have reviewed the services and found nothing but inserts, and the query above to find any other deletes did not see any either.
2. An issue affecting this particular table and it's internal structure. I think this table has been around through rethinkdb version upgrades. Maybe some sort of fragmentation issue?

When I can, I'm going to transition writes to a new table and select and re-insert all the data from the first table. I'll see then if I can reproduce the issue. Then I'll rename it to the original name, revert changes to the services, and see again if I can reproduce the issue.

**Comment by mlucy** [comment] 2015-07-21 03:06
Thanks for your help reproducing this @cyounkins !  If it does turn out that this only happens with tables that have been upgraded through several versions that would be a pretty big hint.  @danielmewes, can you think of anything that happens when we upgrade that might produce behavior like this?

**Comment by danielmewes** [comment] 2015-07-21 03:09
‎Can't think of anything out of my head. Unless the table has primary keys with negative zero values in it maybe... @cyounkins are or were you using numbers in the primary key values? Is there a chance that some of them are/were negative 0?

**Comment by danielmewes** [comment] 2015-07-21 03:12
You could also run `python -m rethinkdb._negative_zero_check` to check for negative zeros in the table. This requires the Python driver to be installed.

**Comment by cyounkins** [comment] 2015-07-21 17:04
The primary index on the table is generated UUIDs, which I'm pretty sure cannot contain negative zeros.

There are two secondary indexes. The first is time, indexing a datetime element. The second is context.remoteAddress, which is a nested string element. I don't believe either of those could have negative zeros.

I'll try to move the producers over to a new database/table and see if the issue persists.

**Comment by cyounkins** [comment] 2015-07-21 17:36
The script confirms as well: `In 2 tables, found no rows with negative zero in their primary key.`

**Comment by danielmewes** [comment] 2015-07-21 18:58
Thanks for checking @cyounkins. @mlucy That was the only thing I'm aware of that we changed in recent versions and that could theoretically be related to this unfortunately.

**Comment by mlucy** [comment] 2015-07-31 00:42
@cyounkins -- any news on whether the issue persists in a new table?

**Comment by mlucy** [comment] 2015-09-25 21:38
Closing since we don't seem to have any leads on this right now, and our best guess is that it only happens for tables that have been upgraded through multiple versions.

**Closed by mlucy** 2015-09-25 21:38 UTC
