### ISSUE TITLE
Error while downloading the zip file

### ISSUE THREAD

**Issue by shubham763** [rethinkdb/rethinkdb#6898] opened 2020-07-22 07:50 UTC
**Error 404 page pops up**
I tried installing rethinkdb for windows, so when I click on the link: https://rethinkdb.com/docs/install/windows/ to download the file a page pops up which says error 404. I've attached the screenshot please have a look.

**Screenshots**
![image](https://user-images.githubusercontent.com/60926838/88149701-0b5dc000-cc1e-11ea-90f8-f2082d1e249d.png)

**System info**
 - OS: Windows 10
 - RethinkDB Version: 2.4.0

**Comment by McSneaky** [comment] 2020-07-22 09:04
Check the pinned issue: https://github.com/rethinkdb/rethinkdb/issues/6814

**Comment by gabor-boros** [comment] 2020-07-23 07:26
Duplicate of #6814

**Closed by gabor-boros** 2020-07-23 07:26 UTC
