### ISSUE TITLE
Error on Windows server 2012 R2

### ISSUE THREAD

**Issue by lomithrani** [rethinkdb/rethinkdb#5819] opened 2016-06-02 13:46 UTC
Hello I have an issue running Rethinkdb on my server.
When I run it I don't have any problem and it appears in my node manager at http://mycluster:8080 but as soon as I check it on 8080 it disapears (after a few seconds).

The command:

`/rethinkdb/2.3.3/rethinkdb.exe -d /rethinkdb/data -n web1 -j 136.***.***.*** --bind all`

The problem seems to be with the clock : 
```
2016-06-02T14:52:05.387613900 99.590913s error: Error in thread -1 in src\time.cc at line 153:
2016-06-02T14:52:05.387613901 99.590937s error: Guarantee failed: [t1.tv_nsec >= 0 && t1.tv_nsec < (1000LL * (1000LL * 1000LL))] 
2016-06-02T14:52:05.387613902 99.590952s error: Backtrace:
2016-06-02T14:52:05.403225200 99.594238s error: Thu Jun 2 14:52:05 2016\n\n1: 0x000007F681D52BAC [The specified module could not be found.]\n2: 0x000007F681D53337 [Attempt to access invalid address.]\n3: 0x000007F68213EBA1 [Attempt to access invalid address.]\n4: 0x000007F6824E82D1 [Attempt to access invalid address.]\n5: 0x000007F681E39805 [Attempt to access invalid address.]\n6: 0x000007F681E39035 [Attempt to access invalid address.]\n7: 0x000007F681D30CDA [Attempt to access invalid address.]\n8: BaseThreadInitThunk+26\n9: RtlUserThreadStart+33
2016-06-02T14:52:05.403225201 99.594345s error: Exiting.
```

Full log :
```
2016-06-02T14:50:25.827414900 0.017956s notice: In recursion: removing file 'C:\\rethinkdb\\data\\tmp'
2016-06-02T14:50:25.827414901 0.018279s warn: Trying to delete non-existent file 'C:\\rethinkdb\\data\\tmp'
2016-06-02T14:50:25.827414902 0.019612s notice: Initializing directory C:\\rethinkdb\\data
2016-06-02T14:50:25.827414903 0.020213s notice: Running rethinkdb 2.3.3-windows (MSC 190023506)...
2016-06-02T14:50:25.827414904 0.020242s notice: Running on 6.2.9200 (Windows 8, Server 2012)
2016-06-02T14:50:25.827414905 0.020261s notice: Loading data from directory C:\\rethinkdb\\data
2016-06-02T14:50:26.108675800 0.309442s info: Automatically using cache size of 28264 MB
2016-06-02T14:50:26.108675801 0.310920s notice: Listening for intracluster connections on port 29015
2016-06-02T14:50:26.108675802 0.311160s info: Attempting connection to 1 peer...
2016-06-02T14:50:26.124302100 0.313481s info: Rejected a connection from server 939d7977-c0a0-41f9-a90a-044b88277947 since one is open already.
2016-06-02T14:50:26.124302101 0.314285s info: Rejected a connection from server 939d7977-c0a0-41f9-a90a-044b88277947 since one is open already.
2016-06-02T14:50:26.124302102 0.315459s info: Rejected a connection from server 939d7977-c0a0-41f9-a90a-044b88277947 since one is open already.
2016-06-02T14:50:26.124302103 0.316447s info: Rejected a connection from server 939d7977-c0a0-41f9-a90a-044b88277947 since one is open already.
2016-06-02T14:50:26.124302104 0.317585s info: Rejected a connection from server 939d7977-c0a0-41f9-a90a-044b88277947 since one is open already.
2016-06-02T14:50:26.124302105 0.318999s info: Rejected a connection from server 939d7977-c0a0-41f9-a90a-044b88277947 since one is open already.
2016-06-02T14:50:26.124302106 0.320787s info: Rejected a connection from server 939d7977-c0a0-41f9-a90a-044b88277947 since one is open already.
2016-06-02T14:50:26.124302107 0.322283s info: Rejected a connection from server 939d7977-c0a0-41f9-a90a-044b88277947 since one is open already.
2016-06-02T14:50:26.124302108 0.324474s info: Rejected a connection from server 939d7977-c0a0-41f9-a90a-044b88277947 since one is open already.
2016-06-02T14:50:26.124302109 0.324480s notice: Connected to server "redis3" 0fc0472a-bab4-4d95-9c6e-8ef79f04e48c
2016-06-02T14:50:26.171180400 0.362920s notice: Listening for client driver connections on port 28015
2016-06-02T14:50:26.171180401 0.363148s notice: Listening for administrative HTTP connections on port 8080
2016-06-02T14:50:26.171180402 0.365909s notice: Listening on cluster addresses: 127.0.0.1, 5.9.138.79, 2002:509:8a4f::509:8a4f, fe80::200:5efe:5.9.138.79%16, fe80::41cc:1f89:2f62:cc94%13
2016-06-02T14:50:26.171180403 0.368096s notice: Listening on driver addresses: 127.0.0.1, 5.9.138.79, 2002:509:8a4f::509:8a4f, fe80::200:5efe:5.9.138.79%16, fe80::41cc:1f89:2f62:cc94%13
2016-06-02T14:50:26.171180404 0.368579s notice: Connected to proxy proxy-01a29a7a-90a5-4a5b-8026-a3a4fc49424f
2016-06-02T14:50:26.171180405 0.368602s notice: Listening on http addresses: 127.0.0.1, 5.9.138.79, 2002:509:8a4f::509:8a4f, fe80::200:5efe:5.9.138.79%16, fe80::41cc:1f89:2f62:cc94%13
2016-06-02T14:50:26.171180406 0.368603s notice: Server ready, "web1" 939d7977-c0a0-41f9-a90a-044b88277947
2016-06-02T14:50:26.171180407 0.371017s notice: Connected to server "data" 798735a3-8777-4ee8-b353-bfacc8a5c0b0
2016-06-02T14:50:26.171180408 0.371026s notice: Connected to proxy proxy-af4dbedc-44f5-44d5-9c1e-678428720114
2016-06-02T14:50:26.171180409 0.373310s notice: Connected to server "redis1" 4db0ec96-6143-4f07-8564-4690f26f4f51
2016-06-02T14:50:26.186804800 0.378082s notice: Connected to proxy proxy-0948f112-a92e-455b-ab28-02f77e4c873a
2016-06-02T14:50:26.186804801 0.378289s notice: Connected to server "db2" 938717e9-eb03-4187-abfb-a6bbf18098e1
2016-06-02T14:50:26.186804802 0.379383s notice: Connected to proxy proxy-04e4eb99-1e01-4a6c-ad83-5b9282bb6ed7
2016-06-02T14:50:26.186804803 0.380721s notice: Connected to server "db1" 53a762a9-82a4-42e5-9710-eed3a72e4b95
2016-06-02T14:50:26.186804804 0.380986s notice: Connected to server "redis2" 04223398-0d46-4f74-9dcd-6ef826e0e913
2016-06-02T14:50:26.358689200 0.559038s info: Rejected a connection from server proxy-01a29a7a-90a5-4a5b-8026-a3a4fc49424f since one is open already.
2016-06-02T14:50:26.483693900 0.675018s info: Rejected a connection from server 4db0ec96-6143-4f07-8564-4690f26f4f51 since one is open already.
2016-06-02T14:50:26.483693901 0.677919s info: Rejected a connection from server 04223398-0d46-4f74-9dcd-6ef826e0e913 since one is open already.
2016-06-02T14:50:28.140172900 2.329776s info: Rejected a connection from server 939d7977-c0a0-41f9-a90a-044b88277947 since one is open already.
2016-06-02T14:50:30.124806100 4.325246s error: ConnectEx failed: The network location cannot be reached. For information about network troubleshooting, see Windows Help.
2016-06-02T14:50:37.079110500 11.277637s info: Rejected a connection from server proxy-0948f112-a92e-455b-ab28-02f77e4c873a since one is open already.
2016-06-02T14:50:37.235367500 11.437040s info: Rejected a connection from server proxy-04e4eb99-1e01-4a6c-ad83-5b9282bb6ed7 since one is open already.
2016-06-02T14:50:37.250992600 11.447950s info: Rejected a connection from server 798735a3-8777-4ee8-b353-bfacc8a5c0b0 since one is open already.
2016-06-02T14:50:41.454301700 15.654403s info: Rejected a connection from server 0fc0472a-bab4-4d95-9c6e-8ef79f04e48c since one is open already.
2016-06-02T14:50:41.532561000 15.724686s info: Rejected a connection from server 53a762a9-82a4-42e5-9710-eed3a72e4b95 since one is open already.
2016-06-02T14:50:41.532561001 15.726794s info: Rejected a connection from server 938717e9-eb03-4187-abfb-a6bbf18098e1 since one is open already.
2016-06-02T14:50:47.157780300 21.346857s error: ConnectEx failed: The semaphore timeout period has expired.
2016-06-02T14:50:49.158049400 23.347100s error: ConnectEx failed: The semaphore timeout period has expired.
2016-06-02T14:50:56.379436600 30.580763s info: Rejected a connection from server proxy-01a29a7a-90a5-4a5b-8026-a3a4fc49424f since one is open already.
2016-06-02T14:51:26.399856300 60.597818s info: Rejected a connection from server proxy-01a29a7a-90a5-4a5b-8026-a3a4fc49424f since one is open already.
2016-06-02T14:51:56.433481700 90.622662s info: Rejected a connection from server proxy-01a29a7a-90a5-4a5b-8026-a3a4fc49424f since one is open already.
2016-06-02T14:52:05.387613900 99.590913s error: Error in thread -1 in src\\time.cc at line 153:
2016-06-02T14:52:05.387613901 99.590937s error: Guarantee failed: [t1.tv_nsec >= 0 && t1.tv_nsec < (1000LL * (1000LL * 1000LL))] 
2016-06-02T14:52:05.387613902 99.590952s error: Backtrace:
2016-06-02T14:52:05.403225200 99.594238s error: Thu Jun  2 14:52:05 2016\n\n1: 0x000007F681D52BAC [The specified module could not be found.]\n2: 0x000007F681D53337 [Attempt to access invalid address.]\n3: 0x000007F68213EBA1 [Attempt to access invalid address.]\n4: 0x000007F6824E82D1 [Attempt to access invalid address.]\n5: 0x000007F681E39805 [Attempt to access invalid address.]\n6: 0x000007F681E39035 [Attempt to access invalid address.]\n7: 0x000007F681D30CDA [Attempt to access invalid address.]\n8: BaseThreadInitThunk+26\n9: RtlUserThreadStart+33
2016-06-02T14:52:05.403225201 99.594345s error: Exiting.
```

**Comment by danielmewes** [comment] 2016-06-02 19:09
Thanks for the bug report @lomithrani.

Could you send us the full `log_file`s from all servers in the cluster? You can email them to me directly via daniel@rethinkdb.com .

We think that something goes wrong when reading the dates from the logs, though the dates in the part that you posted here look fine.

Another question: Which time zone do you have your Windows server configured in?

**Comment by danielmewes** [comment] 2016-06-02 19:34
If our suspicion is correct, it might help to delete the `log_file`s by the way (after you've made a copy for debugging purposes).

**Comment by lomithrani** [comment] 2016-06-02 22:05
The entirety of the log is already on the issue. I do eveything
programatically and as the 2.3.3 wasn't stable I reverted to 2.3.3-proxy
(thus erasing all the repertory) so I don't have the log_files anymore

**Comment by danielmewes** [comment] 2016-06-02 22:16
So this happened every time for you with 2.3.3?

I've tried using your log file and couldn't get the crash. I noticed the `-j 136....` option, so I thought there might be another server in the cluster (other than proxies). If there is, could you post / email the log file from that server as well the next time you try setting up 2.3.3?

Maybe this has something to do with the locale or timezone configuration of the system. Have you had a chance to check the timezone and locale configuration?

**Comment by danielmewes** [comment] 2016-06-03 18:20
Ah, I can reproduce it now by mixing a Windows and a Linux server in the same cluster. It seems to be an incompatibility in the cluster protocol. Looking into it.

**Comment by danielmewes** [comment] 2016-06-03 20:18
A fix for this is in code review 3655.

The cluster protocol was simply not compatible between Linux and Windows.

**Closed** 2016-06-03 20:45 UTC
Labels: tp:bug, windows

**Comment by danielmewes** [comment] 2016-06-04 06:29
@lomithrani Can you try this new binary? http://download.rethinkdb.com/windows/rethinkdb-2.3.4.zip
It should fix the issue.

**Comment by lomithrani** [comment] 2016-06-04 11:21
Works like a charm, Thank you very much
