### ISSUE TITLE
`min` and `max` on a selection should return a selection

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5027] opened 2015-10-30 21:19 UTC
Currently they only return a selection if called with an index.

**Comment by danielmewes** [comment] 2015-11-02 21:09
This is a duplicate of https://github.com/rethinkdb/rethinkdb/issues/3939 . Do you think we actually need a proposal discussion for this?

**Closed by danielmewes** 2015-11-02 21:09 UTC
Labels: tp:ReQL_proposal
