### ISSUE TITLE
"stack level too deep" error in Ruby 2.2

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4767] opened 2015-08-25 20:11 UTC
It seems that something has changed in Ruby 2.2 that is triggering a `stack level too deep (SystemStackError)` error in `polyglot/limits.rb2.2`. The command causing this does not look problematic:
```tbl.insert([{'id'=>7}, {'id'=>8}, {'id'=>9}, {'id'=>10}, {'id'=>11}, {'id'=>12}, {'id'=>13}]).get_field('inserted')```

The command to get here:
```./test/rql_test/test-runner -i rb2.2 polyglot/limits.rb```

And the full output is:
```
/Users/larkost/projects/rethinkdb-test/drivers/ruby/lib/func.rb:96:in `block (2 levels) in <class:RQL>': stack level too deep (SystemStackError)
	from /Users/larkost/projects/rethinkdb-test/test/rql_test/build/polyglot.limits.rb2.2:62:in `<main>'
	from /Users/larkost/projects/rethinkdb-test/test/rql_test/build/polyglot.limits.rb2.2:376:in `eval'
	from /Users/larkost/projects/rethinkdb-test/test/rql_test/build/polyglot.limits.rb2.2:376:in `test'
	from /Users/larkost/projects/rethinkdb-test/test/rql_test/build/polyglot.limits.rb2.2:575:in `<main>'
Ruby: 14 of 15 tests passed. 1 tests failed.
```

Our internal `newton` server does not yet have Ruby 2.2, so I should add it soon.

**Comment by mlucy** [comment] 2015-08-28 17:50
@larkost -- I installed Ruby 2.2 on Newton and am unable to reproduce this:

```
mlucy@newton:~/rethinkdb/test/rql_test$ ./test-runner -irb2.2 polyglot/limits.rb
Using rethinkdb binary /home/ssd2/mlucy/rethinkdb/build/debug_clang/rethinkdb
        Ruby 2.2 interpreter: /usr/bin/ruby2.2, driver: /home/ssd2/mlucy/rethinkdb/drivers/ruby
== Starting: polyglot/limits.rb2.2 (T+ 0.3 sec)
== Passed: polyglot/limits.rb2.2 in 5.5 sec + 0.0 sec setup (T+ 5.8 sec)

== Successfully passed the 1 test in 6.11 seconds!
```

Do you see it reliably on your machine?

**Comment by larkost** [comment] 2015-09-02 22:40
Yes it is reliably reproducible on my machine... and grr... not reproducible on `gantz`. So this is probably a timing/race condition issue. Either that, or something is borked on my machine with Ruby2.2 and only shows up in this test.

I am going to see if a machine that previously repeated timing issues that I saw will also do the same.

**Comment by larkost** [comment] 2015-09-03 00:01
The other machine is not showing the same issue, so I don't know what to say.

**Comment by mlucy** [comment] 2015-09-03 00:03
That's very strange.  Maybe we'd get some hints if we tried to get down to a smaller reproducible case?

**Comment by larkost** [comment] 2015-09-03 00:42
Ok, this goes away if I update to Ruby 2.2.3 (from 2.2.2). Not entirely sure what we want to do here.

**Comment by mlucy** [comment] 2015-09-03 00:54
I think if upgrading the Ruby version fixes it we should consider it OK.

**Comment by danielmewes** [comment] 2015-11-17 01:38
Closing since it was probably an issue with the specific version of Ruby.

**Closed by danielmewes** 2015-11-17 01:38 UTC
Labels: Ruby, tp:bug
