### ISSUE TITLE
secondary indexes mysteriously disappear 

### ISSUE THREAD

**Issue by dollschasingmen** [rethinkdb/rethinkdb#6155] opened 2016-10-25 01:28 UTC
Hi - we were vetting rethinkdb. We loaded some data to a table, built 3 secondary indexes on the table, ran a few queries against it. 

We ran`count()` query which took a long time to run and seemed to "lock up" the table from further querying.

While we were investigating this issue we suddenly noticed that all the indexes dissapeared. Also, on the table page, we now saw that it says "Uknown documents"

<img width="336" alt="screen shot 2016-10-24 at 9 26 33 pm" src="https://cloud.githubusercontent.com/assets/763803/19669844/970b7ef4-9a30-11e6-8ebc-b36b3d15c3cc.png">

Obviously, this is really strange and disturbing. 

What are some ways to debug this and try to figure out what might have happened? I saw nothing in the logs on the web UI. I logged into the nodes and checked the logs there but also nothing interesting. I checked out the `jobs` and `stats` system tables but also nothing to elucidating.

**Comment by dollschasingmen** [comment] 2016-10-26 22:07
Ok -- so, still not quite sure what the issue is. It seems like we can semi-reliably replicate the issue by

1. running a heavy query `r.table("my_table").group("my_agg").count()`
2. doing a few web ui queries

at some point the db becomes unresponsive to any queries. The UI shows that indexes are gone, or sometimes, even the tables and servers are gone. The dashboard, however, always seem to chug along. 

The only solution at that point is to restart the servers.

**Comment by thomasmodeneis** [comment] 2016-10-28 16:08
I'm also seeing this, and restarting servers seems to fix it.
I believe this is another one related to https://github.com/rethinkdb/rethinkdb/issues/4357

**Comment by dollschasingmen** [comment] 2016-10-31 15:01
yea restarting the server reliably fixes it. i have also noticed a one case where it fixed itself (took a few hours).

one other thing i observed is that while the web UI is messed up, the server itself is non responsive. running queries from client drivers, for example, hang. this is kind of a bigger issue than just the UI being unresponsive.

**Comment by marshall007** [comment] 2016-11-01 00:53
This is not an issue with the Web UI nor secondary indices. The UI (and RethinkDB server in general) can become unresponsive under load, which causes any queries the UI makes to fail.

Closing as duplicate of #5039. Please feel free to continue discussion or ask questions here or in #5039.

**Closed by marshall007** 2016-11-01 00:53 UTC

**Comment by dollschasingmen** [comment] 2016-11-01 15:31
yea -- that makes sense, i also feel like it is not about the UI specifically, but that the entire server kind of seized up. what do you mean by under load? as mentioned, i was looking at cpu, memory, iops, etc, and saw no load when the it sort of conked itself out.

**Comment by marshall007** [comment] 2016-11-01 15:59
@dollschasingmen in my experience, this tends to happen during large read operations (like a `.group(...).count()`). Not necessarily "load" as in high resource consumption, but rather any time RethinkDB is performing lots of read (or perhaps write?) ops.

As far as I can remember, I've only ever been able to reproduce this using `.count()` queries. If you're able to reliably reproduce, I would definitely mention it over in #5039. We've yet to pin down exactly what the scope of this problem is.

**Comment by dollschasingmen** [comment] 2016-11-02 23:56
cool i mentioned it in the other issue.
