### ISSUE TITLE
Proxy nodes are actually storing data

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3191] opened 2014-10-14 23:52 UTC
As reported by `pilt` in IRC:

> I have created a three server cluster. On client hosts I run `rethinkdb proxy -j server1 -j server2 ...` and it works. However, the proxy processes show up in the web gui as unassigned servers, and when I create tables these proxy instances are used for replicas

I haven't confirmed this.

**Comment by danielmewes** [comment] 2015-01-06 19:46
Closing because we haven't been able to reproduce it and don't have enough information to investigate further at this point.

**Closed by danielmewes** 2015-01-06 19:46 UTC
Labels: tp:bug
