### ISSUE TITLE
r.uuid(somestring)

### ISSUE THREAD

**Issue by wmira** [rethinkdb/rethinkdb#5425] opened 2016-02-19 13:31 UTC
Is it  guaranteed that passing an argument will generate the same value every time if we pass the same string?

**Comment by kwando** [comment] 2016-02-19 14:39
I think so, otherwise I'm in trouble.

**Comment by thelinuxlich** [comment] 2016-02-19 15:27
Yes it is

**Comment by VeXocide** [comment] 2016-02-19 15:36
Indeed, it will generate the same UUID given the same input.

I'll close this issue since it's not a bug, but please feel free to ask more questions here.

**Closed by VeXocide** 2016-02-19 15:36 UTC
