### ISSUE TITLE
Is r.merge() unreasonably slow?

### ISSUE THREAD

**Issue by webmasterkai** [rethinkdb/rethinkdb#5089] opened 2015-11-14 06:33 UTC
Let's say I want to create an object with 500 random keys. My first thought is to do something like:
```
r.range(500)
  .map(function(row){ return r.object(r.uuid(), row) })
  .reduce(function(left, right){ return left.merge(right) })
```
Except that takes 250ms. If you really want to get crazy, try doing 1500 instead of 500. For me, it takes over 2.5 seconds...

To cut the time in half I can do something like:

```
r.range(250)
  .map(function(row){ return r.object(r.uuid(), row) })
  .reduce(function(left, right){ return left.merge(right) })
  .merge(
    r.range(250)
    .map(function(row){ return r.object(r.uuid(), row) })
    .reduce(function(left, right){ return left.merge(right) })
  )
```

Ok, so it must be related to the number of keys?

The following does 500 merges on single key objects. It takes 11ms on my machine:

```
r.range(500)
  .map(function(row){ return [r.object(r.uuid(), row), r.object(r.uuid(), row.add(1))]})
  .map(function(row){ return row(0).merge(row(1)) })
```

~~If I have an object with 500 keys and I do a single merge with an empty object it takes around 7ms to evaluate the merge. Doing the reverse, take an empty object and merging the 500 key object onto it takes 8-10ms.~~ [edit] Looks like `Evaluating make_obj` is the thing slowing it downhere.

Using node Array.reduce and Object.assign() on an array of 1500 objects takes less than 10ms. Why is RethinkDB 250 times slower?

**Comment by mlucy** [comment] 2015-11-14 23:35
Hi @webmasterkai,

Every time you call `.merge` it constructs a new object.  So the code you wrote above will run in `O(n^2)` time, since it's constructing `n` objects of average size `n/2` during the `reduce` step.  The query language really isn't optimized for this case -- object construction is usually rare, so it's pretty expensive right now.

I'd write this query as `r.range(500).map(function(row) { return [r.uuid(), row.add(1)]; }).coerce_to('object')`, which should be much faster.

Leaving this issue open since we should probably optimize this case at some point in the future.

**Comment by webmasterkai** [comment] 2015-11-14 23:43
@mlucy The suggestion you provide to coerce an array of simple arrays into an object is the answer to any use case I had in mind. Thanks! :tada:

**Comment by marshall007** [comment] 2015-11-15 01:24
I think this is a duplicate of #3408.

**Comment by danielmewes** [comment] 2015-11-16 19:24
Yeah I think the solution discussed in https://github.com/rethinkdb/rethinkdb/issues/3408 would work for this as well.

**Closed by danielmewes** 2015-11-16 19:24 UTC
Labels: tp:performance
