### ISSUE TITLE
Fix jobs

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3884] opened 2015-03-04 21:39 UTC
The `rethinkdb.jobs` system table is currently broken in `raft`:

* The `jobs_manager_t` currently cannot find the `store_t`s, because the method through which it was finding them was changed in Raft.

* Backfill jobs need to be reimplemented.

**Comment by VeXocide** [comment] 2015-05-19 02:39
This is next.

**Comment by VeXocide** [comment] 2015-05-26 23:05
The fix for `"disk_compaction"` and `"index_construction"` jobs is in CR 2918 by @timmaxw, and I'm holding off on the `"backfill"` jobs until either @danielmewes or @timmaxw is here to give me a rundown of the code.

**Comment by VeXocide** [comment] 2015-06-02 03:26
Fix merged into `raft` via commit c4e45484d9b9c2e830198d936edc7c7a6bb33c99.

**Comment by danielmewes** [comment] 2015-06-16 02:12
FYI: The `regression.659` test is failing because of missing backfill jobs.

**Comment by VeXocide** [comment] 2015-06-16 21:21
Fixing backfill jobs is next

**Comment by VeXocide** [comment] 2015-06-24 23:22
In CR 3012 by @timmaxw.

**Comment by VeXocide** [comment] 2015-06-25 21:33
Merged into `next` via commit 5a2e9b25d108eeb2c114aa92f07d8518721b28f1.

**Closed by VeXocide** 2015-06-25 21:33 UTC
Labels: cp:clustering
