### ISSUE TITLE
RethinkDB doesn't detect which servers can act as primary properly

### ISSUE THREAD

**Issue by sontek** [rethinkdb/rethinkdb#4855] opened 2015-09-17 23:24 UTC
I have a 4 node cluster with 4 shards and 4 replicas which means every node in my cluster has all the data and we should be able to actively query even if all but 1 node is online.  After I shutdown 2 of the 4 nodes it no longer works:

![screenshot from 2015-09-17 16 19 17](https://cloud.githubusercontent.com/assets/151924/9948495/7669105a-5d58-11e5-8a31-2968f2a64b32.png)

and this is the error I get from the Python driver:

```
$ python test_rethink.py 
Traceback (most recent call last):
  File "test_rethink.py", line 145, in <module>
    data = get_single()
  File "test_rethink.py", line 126, in get_single
    result = r.table('test').run(conn)
  File "/home/local/CORP/johna/rethinkdb_env/lib/python3.4/site-packages/rethinkdb/ast.py", line 118, in run
    return c._start(self, **global_optargs)
  File "/home/local/CORP/johna/rethinkdb_env/lib/python3.4/site-packages/rethinkdb/net.py", line 580, in _start
    return self._instance.run_query(q, global_optargs.get('noreply', False))
  File "/home/local/CORP/johna/rethinkdb_env/lib/python3.4/site-packages/rethinkdb/net.py", line 454, in run_query
    raise res.make_error(query)
rethinkdb.errors.ReqlOpFailedError: Cannot perform read: primary replica for shard ["S3\xAAa\xBE", "S7\xEE\xEA\x17") not available in:
r.table('test')
^^^^^^^^^^^^^^^
```

**Comment by coffeemug** [comment] 2015-09-17 23:50
@sontek -- this is expected behavior.

In general, to survive K hardware failures, you need K * 2 + 1 servers. So, for example, to survive two hardware failures, you'd need a cluster of five servers. We need this for the Raft consensus -- we can't guarantee data consistency unless we can get a majority vote.

Hope this makes sense -- closing this issue, but feel free to comment if you have more questions.

**Closed by coffeemug** 2015-09-17 23:50 UTC

**Comment by dalanmiller** [comment] 2015-09-17 23:55
Hey @sontek, you might want to check out our failover page in our docs for some more info. 

https://rethinkdb.com/docs/failover/

**Comment by sontek** [comment] 2015-09-17 23:57
Thanks! That was my mistake. I had read the failover doc before and I thought it said you needed half your nodes but I see it actually says more than half :)

**Comment by danielmewes** [comment] 2015-09-18 00:03
@sontek Actually you *can* still read from a single node, but you need to tell RethinkDB that it's ok to ignore any writes that might since have been acknowledged on the other side of a potential netsplit.

The way to do that is to pass the `read_mode="outdated"` optarg to `table` or `run`.

**Comment by danielmewes** [comment] 2015-09-18 00:05
(note that if you do benchmarking, `read_mode="outdated"` is also going to affect how the reads are routed to the different replicas. With that flag, RethinkDB will usually try to execute those reads locally on the server that you're connecting to, rather than spreading them out over the cluster.)
