### ISSUE TITLE
[v2.1.x] failed to find expected metadata key

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#4649] opened 2015-08-08 02:10 UTC
Just built from source and ran it on a old data directory (not sure which version, probably 2.0.x). I got this stacktrace:

```
Version: rethinkdb 2.1.0-0BETA2-96-g94df20 (debug) (GCC 5.2.0)
error: Error in ./src/clustering/administration/persist/file.hpp at line 48:
error: Guarantee failed: [found] failed to find expected metadata key
error: Backtrace:
error: Fri Aug  7 19:01:40 2015
       
       1: rethinkdb_backtrace(void**, int) at rethinkdb_backtrace.cc:101
       2: backtrace_t::backtrace_t() at backtrace.cc:203 (discriminator 1)
       3: lazy_backtrace_formatter_t::lazy_backtrace_formatter_t() at backtrace.cc:283
       4: format_backtrace(bool) at backtrace.cc:198
       5: report_fatal_error(char const*, int, char const*, ...) at errors.cc:83 (discriminator 1)
       6: heartbeat_semilattice_metadata_t metadata_file_t::read_txn_t::read<heartbeat_semilattice_metadata_t>(metadata_file_t::key_t<heartbeat_semilattice_metadata_t> const&, signal_t*) at file.hpp:48 (discriminator 1)
       7: do_serve(io_backender_t*, bool, base_path_t const&, metadata_file_t*, serve_info_t const&, os_signal_cond_t*) at serve.cc:117 (discriminator 1)
       8: serve(io_backender_t*, base_path_t const&, metadata_file_t*, serve_info_t const&, os_signal_cond_t*) at serve.cc:640
       9: run_rethinkdb_serve(base_path_t const&, serve_info_t*, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> > const&, bool, uuid_u const*, server_config_versioned_t const*, cluster_semilattice_metadata_t const*, directory_lock_t*, bool*) at command_line.cc:805 (discriminator 1)
       10: run_rethinkdb_porcelain(base_path_t const&, name_string_t const&, std::set<name_string_t, std::less<name_string_t>, std::allocator<name_string_t> > const&, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> > const&, bool, bool, serve_info_t*, directory_lock_t*, bool*) at command_line.cc:837
       11: void std::_Bind<void (*(base_path_t, name_string_t, std::set<name_string_t, std::less<name_string_t>, std::allocator<name_string_t> >, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> >, bool, bool, serve_info_t*, directory_lock_t*, bool*))(base_path_t const&, name_string_t const&, std::set<name_string_t, std::less<name_string_t>, std::allocator<name_string_t> > const&, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> > const&, bool, bool, serve_info_t*, directory_lock_t*, bool*)>::__call<void, , 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul>) at functional:1074
       12: void std::_Bind<void (*(base_path_t, name_string_t, std::set<name_string_t, std::less<name_string_t>, std::allocator<name_string_t> >, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> >, bool, bool, serve_info_t*, directory_lock_t*, bool*))(base_path_t const&, name_string_t const&, std::set<name_string_t, std::less<name_string_t>, std::allocator<name_string_t> > const&, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> > const&, bool, bool, serve_info_t*, directory_lock_t*, bool*)>::operator()<, void>() at functional:1133
       13: std::_Function_handler<void (), std::_Bind<void (*(base_path_t, name_string_t, std::set<name_string_t, std::less<name_string_t>, std::allocator<name_string_t> >, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> >, bool, bool, serve_info_t*, directory_lock_t*, bool*))(base_path_t const&, name_string_t const&, std::set<name_string_t, std::less<name_string_t>, std::allocator<name_string_t> > const&, file_direct_io_mode_t, int, boost::optional<boost::optional<unsigned long> > const&, bool, bool, serve_info_t*, directory_lock_t*, bool*)> >::_M_invoke(std::_Any_data const&) at functional:1873
       14: std::function<void ()>::operator()() const at functional:2272
       15: starter_t::run_wrapper(std::function<void ()> const&) at runtime.cc:61
       16: void std::_Mem_fn_base<void (starter_t::*)(std::function<void ()> const&), true>::operator()<std::function<void ()>&, void>(starter_t*, std::function<void ()>&) const at functional:600 (discriminator 4)
       17: void std::_Bind<std::_Mem_fn<void (starter_t::*)(std::function<void ()> const&)> (starter_t*, std::function<void ()>)>::__call<void, , 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>) at functional:1075
       18: void std::_Bind<std::_Mem_fn<void (starter_t::*)(std::function<void ()> const&)> (starter_t*, std::function<void ()>)>::operator()<, void>() at functional:1133
       19: std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (starter_t::*)(std::function<void ()> const&)> (starter_t*, std::function<void ()>)> >::_M_invoke(std::_Any_data const&) at functional:1873
       20: std::function<void ()>::operator()() const at functional:2272
       21: callable_action_instance_t<std::function<void ()>&>::run_action() at callable_action.hpp:31
       22: callable_action_wrapper_t::run() at runtime_utils.cc:43
       23: coro_t::run() at coroutines.cc:207
       24: coro_t* coro_t::spawn_sometime<std::function<void ()>&>(std::function<void ()>&) at coroutines.hpp:58
       25: starter_t::on_thread_switch() at runtime.cc:57
       26: linux_message_hub_t::on_event(int) at message_hub.cc:154
       27: epoll_event_queue_t::run() at epoll.cc:115
       28: linux_thread_pool_t::start_thread(void*) at thread_pool.cc:166
       29: /usr/lib/libpthread.so.0(+0x7354) [0x7fd8ad9eb354] at 0x7fd8ad9eb354 (/usr/lib/libpthread.so.0)
       30: clone+0x6d at 0x7fd8ad729bfd (/usr/lib/libc.so.6)
error: Exiting.
Trace/breakpoint trap (core dumped)
```

Configure output 
```
michel@h9:~/projects/rethinkdb-all/rethinkdb$ ./configure --allow-fetch
* Detecting system configuration
Bash:                           4.3.39(1)-release
Use ccache:                     no
C++ Compiler:                   GCC 5.2.0 (/usr/bin/c++)
Host System:                    x86_64-unknown-linux-gnu
Build System:                   Linux 4.0.7-2-ARCH x86_64
Cross-compiling:                no
Host Operating System:          Linux
Build Architecture:             x86_64
C++11:                          ok
Precompiled web assets:         no
Protobuf compiler:              /usr/bin/protoc
python:                         python 2.7.10
Node.js package manager:        /usr/bin/npm
coffee:                         external/coffee-script_1.7.1
Browserify:                     external/browserify_3.24.13
bluebird:                       external/bluebird_2.9.32
web UI dependencies:            external/admin-deps_2.0.3
wget:                           /usr/bin/wget
curl:                           /usr/bin/curl
Google Test:                    external/gtest_1.6.0
termcap:                        -ltermcap
boost_system:                   -lboost_system
ssl:                            -lssl
protobuf:                       -lprotobuf
icui18n:                        -licui18n
icuuc:                          -licuuc
icudata:                        -licudata
v8 javascript engine:           external/v8_3.30.33.16
RE2:                            external/re2_20140111
z:                              -lz
crypto:                         -lcrypto
curl:                           -lcurl
malloc:                         jemalloc
jemalloc (static):              external/jemalloc_3.6.0
Test protobuf:                  ok
Test boost:                     ok
Installation prefix:            /usr/local
Configuration prefix:           /usr/local/etc
Runtime data prefix:            /usr/local/var
* Wrote configuration to config.mk
```

It looks like I can't upload a tar.gz on GitHub -_- but if you need the data directory I can probably send it, it's about 200kB.

**Comment by neumino** [comment] 2015-08-08 02:14
I forgot to write that it works fine if I removed the old data directory.

**Comment by danielmewes** [comment] 2015-08-08 02:14
Are you sure the data directory wasn't from an older version of next/2.1.x?

**Comment by neumino** [comment] 2015-08-08 02:16
Just digged a bit in the log. I was on commit 44b042c so that was probably an old 2.1.x version

**Comment by Tryneus** [comment] 2015-08-08 02:20
Yeah, the 2.1-beta is not compatible with the current `v2.1.x` because we added a new key to the metadata for the heartbeat timeout.

**Comment by Tryneus** [comment] 2015-08-08 02:21
Also, we now version the btree superblock using the magic number, so even if you got past that, it would crash when loading the tables (thinking that it's a `2.0.x` superblock that should have been migrated).

**Comment by danielmewes** [comment] 2015-08-08 02:23
Actually that commit seems to already have the heartbeat semilattice, which makes this specific type of failure a bit odd. Or maybe the data directory was an even older one? Could that be?

**Comment by neumino** [comment] 2015-08-08 04:30
It's not impossible but unlikely.

**Comment by danielmewes** [comment] 2015-08-11 18:06
Closing since this was probably caused by opening a beta DB file. Let's re-open if it ever happens again.

**Closed by danielmewes** 2015-08-11 18:06 UTC
