### ISSUE TITLE
Allow specifying a query in get params when linking to the data explorer

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3635] opened 2015-01-22 00:52 UTC
So, for example, we could create links from all over the webui that put a default query into the text box when you link to the data explorer. Something to think about might be whether to limit the queries to a prespecified subset for security reasons.

This would be nice for things like "open this table in the dataexplorer" kinds of things.

**Comment by danielmewes** [comment] 2015-01-22 00:58
I think this is a duplicate of https://github.com/rethinkdb/rethinkdb/issues/1298

**Comment by deontologician** [comment] 2015-01-22 01:03
Yes, if your comment at the end is how we actually do it. I agree it makes little sense to store it locally

**Comment by mglukhovsky** [comment] 2015-01-22 01:03
Agreed, this is a dupe.

**Closed** 2015-01-22 01:03 UTC
Labels: cp:web-ui
