### ISSUE TITLE
failed to build 2.3.6-5 cannot convert ‘boost::logic::tribool’ to ‘bool’

### ISSUE THREAD

**Issue by beenotung** [rethinkdb/rethinkdb#6742] opened 2019-06-01 19:39 UTC
## Build-time Error
Compile error: cannot convert ‘boost::logic::tribool’ to ‘bool’

## How I Found This Bug
The `libprotobuf.so` in my system is updated recently from `libprotobuf.so.17` to `libprotobuf.so.18` hence I need to reinstall rethinkdb.
I install rethinkdb (2.3.6-5) from yay (similar tools as yaourt).

## Console Log
Below is part of the the console log:
```
==> Verifying source file signatures with gpg...
    rethinkdb-2.3.6.tgz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting rethinkdb-2.3.6.tgz with bsdtar
==> Starting prepare()...
patching file mk/support/pkg/v8.sh
Hunk #1 succeeded at 46 (offset 2 lines).
Hunk #2 succeeded at 60 (offset 2 lines).
==> Sources are ready.
==> Making package: rethinkdb 2.3.6-5 (Sunday, June 02, 2019 AM03:20:54 HKT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
* Reading arguments from 'configure.default'
* Prepending the following arguments: --fetch re2 --fetch gtest --fetch v8 --fetch jemalloc
* Detecting system configuration
Bash:                           5.0.7(1)-release
CXXFLAGS:                       -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -I/usr/include/openssl-1.0
LDFLAGS:                        -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/lib/openssl-1.0
Use ccache:                     no
C++ Compiler:                   GCC 8.3.0 (/usr/bin/c++)
Host System:                    x86_64-pc-linux-gnu
Build System:                   Linux 5.1.2-arch1-1-ARCH x86_64
Cross-compiling:                no
Host Operating System:          Linux
Build Architecture:             x86_64
C++11:                          ok
Precompiled web assets:         yes
Protobuf compiler:              /usr/bin/protoc
python:                         python 2.7.16
Node.js package manager:        /usr/local/bin/npm
coffee:                         no
Browserify:                     no
bluebird:                       external/bluebird_2.9.32
web UI dependencies:            external/admin-deps_2.0.3
wget:                           /usr/bin/wget
curl:                           /usr/bin/curl
Google Test:                    external/gtest_1.7.0
termcap:                        -ltinfo
boost_system:                   -lboost_system
protobuf:                       -lprotobuf
v8 javascript engine:           external/v8_3.30.33.16-patched2
RE2:                            external/re2_20140111
z:                              -lz
crypto:                         -lcrypto
ssl:                            -lssl
curl:                           -lcurl
malloc:                         jemalloc
jemalloc:                       external/jemalloc_4.1.0
Test protobuf:                  ok
Test boost:                     ok
Test OpenSSL:                   ok
Installation prefix:            /usr
Configuration prefix:           /etc
Runtime data prefix:            /var
* Wrote configuration to config.mk
    [1/426] CP build/web_assets/web_assets.cc
    [2/426] INSTALL-INCLUDE gtest_1.7.0
    [3/426] CC build/release/obj/web_assets/web_assets.o
    [4/426] PROTOC build/proto/rdb_protocol/ql2.pb.cc
[libprotobuf WARNING google/protobuf/compiler/parser.cc:564] No syntax specified for the proto file: rdb_protocol/ql2.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
    [5/426] CC build/release/obj/rdb_protocol/ql2.pb.o
    [6/426] INSTALL-INCLUDE re2_20140111
...
    [360/426] CC build/release/obj/clustering/administration/auth/username.o
    [361/426] CC build/release/obj/clustering/administration/auth/user.o
src/clustering/administration/auth/user.cc: In member function ‘bool auth::user_t::has_read_permission(const database_id_t&, const namespace_id_t&) const’:
src/clustering/administration/auth/user.cc:199:20: error: cannot convert ‘boost::logic::tribool’ to ‘bool’ in return
             return table_permission;
                    ^~~~~~~~~~~~~~~~
src/clustering/administration/auth/user.cc:207:20: error: cannot convert ‘boost::logic::tribool’ to ‘bool’ in return
             return database_permission;
                    ^~~~~~~~~~~~~~~~~~~
src/clustering/administration/auth/user.cc:211:47: error: cannot convert ‘boost::logic::tribool’ to ‘bool’ in return
     return m_global_permissions.get_read() || false;
                                               ^~~~~
src/clustering/administration/auth/user.cc: In member function ‘bool auth::user_t::has_write_permission(const database_id_t&, const namespace_id_t&) const’:
src/clustering/administration/auth/user.cc:221:20: error: cannot convert ‘boost::logic::tribool’ to ‘bool’ in return
             return table_permission;
                    ^~~~~~~~~~~~~~~~
src/clustering/administration/auth/user.cc:229:20: error: cannot convert ‘boost::logic::tribool’ to ‘bool’ in return
             return database_permission;
                    ^~~~~~~~~~~~~~~~~~~
src/clustering/administration/auth/user.cc:233:48: error: cannot convert ‘boost::logic::tribool’ to ‘bool’ in return
     return m_global_permissions.get_write() || false;
                                                ^~~~~
src/clustering/administration/auth/user.cc: In member function ‘bool auth::user_t::has_config_permission() const’:
src/clustering/administration/auth/user.cc:237:49: error: cannot convert ‘boost::logic::tribool’ to ‘bool’ in return
     return m_global_permissions.get_config() || false;
                                                 ^~~~~
src/clustering/administration/auth/user.cc: In member function ‘bool auth::user_t::has_config_permission(const database_id_t&) const’:
src/clustering/administration/auth/user.cc:246:20: error: cannot convert ‘boost::logic::tribool’ to ‘bool’ in return
             return database_permission;
                    ^~~~~~~~~~~~~~~~~~~
src/clustering/administration/auth/user.cc: In member function ‘bool auth::user_t::has_config_permission(const database_id_t&, const namespace_id_t&) const’:
src/clustering/administration/auth/user.cc:260:20: error: cannot convert ‘boost::logic::tribool’ to ‘bool’ in return
             return table_permission;
                    ^~~~~~~~~~~~~~~~
src/clustering/administration/auth/user.cc: In member function ‘bool auth::user_t::has_connect_permission() const’:
src/clustering/administration/auth/user.cc:268:50: error: cannot convert ‘boost::logic::tribool’ to ‘bool’ in return
     return m_global_permissions.get_connect() || false;
                                                  ^~~~~
make[1]: *** [src/build.mk:392: build/release/obj/clustering/administration/auth/user.o] Error 1
make: *** [Makefile:53: make] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: rethinkdb
```

**Comment by beenotung** [comment] 2019-06-01 19:40
seems related to https://github.com/rethinkdb/rethinkdb/issues/6732

**Comment by srh** [comment] 2019-07-09 23:30
I'm closing as a duplicate of #6732.  This is definitely something that needs to be fixed.

**Closed by srh** 2019-07-09 23:30 UTC
