### ISSUE TITLE
Can't be installed on Ubuntu 19.04 Disco Dingo

### ISSUE THREAD

**Issue by martio** [rethinkdb/rethinkdb#6774] opened 2019-10-20 07:00 UTC
Hi,

Can't be installed on Ubuntu 19.04 Disco Dingo...

**Err:13 https://download.rethinkdb.com/apt disco Release
  404  Not Found [IP: 167.71.110.79 443]**

`$ source /etc/lsb-release && echo "deb https://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
deb https://download.rethinkdb.com/apt disco main`

`$ wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
OK`

`$ sudo apt-get update
Hit:1 https://repos.insights.digitalocean.com/apt/do-agent main InRelease
Hit:2 http://archive.ubuntu.com/ubuntu disco InRelease                                                                                                        
Hit:3 http://ppa.launchpad.net/certbot/certbot/ubuntu disco InRelease                                                                                         
Hit:4 https://deb.nodesource.com/node_12.x disco InRelease                                                                                                    
Ign:5 https://dl.bintray.com/rabbitmq/debian disco InRelease                                                                                                  
Hit:6 https://dl.yarnpkg.com/debian stable InRelease                                                                                                          
Hit:7 http://security.ubuntu.com/ubuntu disco-security InRelease                                                                                              
Get:8 https://dl.bintray.com/rabbitmq/debian disco Release [54.4 kB]                                 
Hit:9 http://mirrors.digitalocean.com/ubuntu disco InRelease                                                   
Hit:10 http://mirrors.digitalocean.com/ubuntu disco-updates InRelease                                          
Hit:11 http://mirrors.digitalocean.com/ubuntu disco-backports InRelease        
Ign:12 https://download.rethinkdb.com/apt disco InRelease                      
Err:13 https://download.rethinkdb.com/apt disco Release
  404  Not Found [IP: 167.71.110.79 443]
Reading package lists... Done
E: The repository 'https://download.rethinkdb.com/apt disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by srh** [comment] 2019-10-21 18:06
Dupe of #6773, which I'm working on.

**Closed by srh** 2019-10-21 18:06 UTC
