### ISSUE TITLE
Hanging `include_initial` `get_all`

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5157] opened 2015-11-30 19:25 UTC
@tatsujin1 reported this issue on Slack:
> in my test with 25000 documents a simple indexed query (using `get_all`) takes 50ms, no problem, but ​sometimes​ it can take over 30 seconds...
> this during frequent changes to the documents.
> oh, forgot to mention that the query is a changefeed, using
`include_initial`.... and the initial documents are received quite quickly, but the `ready` state document is not received until much later.
> query result is about 1000 documents
> sometimes it can even hang completely... and stopping the modifications at this time does not make the query's initial batch to be returned any faster...
> my complete query is simply:  `r.db('thedb').table('thetable').get_all(3, index='value').changes(include_initial=True, include_states=True).run()`
> in fact, it seems that if the `ready` state is not received within ~1 second - and at that time stopping the process modifying the table - the ready state will never be received

Also:
> just tried leaving the query running longer for once, and its still hanged after about ~1 hour

CPU load on the database was low, and judging from the load value of just 0.6 to 1.5, I suspect that i/o was also not a major bottleneck here.

@mlucy Could you take this one please?

**Comment by danielmewes** [comment] 2015-11-30 19:38
Also their document structure:
```js
{
    'id': 12345,
    '_modified': <timestamp>
    'value': 1234,
    'kw': <string, <50 chars>
    'bloat': <string, ~270 chars>
}
```

**Comment by tatsujin1** [comment] 2015-11-30 20:46
I've made a self-contained that almos-guarantee reproduces the problem. I'll post it tomorrow.

**Comment by tatsujin1** [comment] 2015-11-30 21:52
Had some time, so I'll post the test now :)

*test-modifier.py*
```
#! /usr/bin/env python3

db_name = 'test_db'
table_name = 'test_table'
print('(re)creating table: %s.%s' % (db_name, table_name))

import rethinkdb as r
r.connect().repl()
if db_name in r.db_list().run():
	r.db_drop(db_name).run()
r.db_create(db_name).run()
r.db(db_name).table_create(table_name, durability='soft').run()
	
table = r.db(db_name).table(table_name)
	
indexes = {'_modified', 'value'}
for index in indexes.difference(table.index_list().run()):
	table.index_create(index).run()

max_id = 25000
print('inserting %d ...' % max_id)
for doc_id in range(1, max_id + 1):
	table.insert({
		'id': doc_id,
		'_modified': r.now(),
		'value': doc_id % 20,
		'bloat': '#'*250,
	}).run(noreply=True)

import random
import time

print('modifying...')
while True:
	time.sleep(0.05)

	doc_id = random.randint(1, max_id)
	table.get(doc_id).update({
		'_modifed': r.now(),
		'value': max_id - doc_id,
	}).run()
	print('  ^^  ', doc_id)
```
Start it and leave it running.
It seems that the number of documents (25k) and the `bloat` field are not strictly required to reproduce the problem but increases the chance of it occurring a lot. Probably because of timing.

Then run this, *test-listen.py*:
```
#! /usr/bin/env python3

import time
import rethinkdb as r

r.connect().repl()

table = r.db('test_db').table('test_table')
	
print('receiving changes...')
startTime = time.time()

import sys
out=sys.stdout
def progress(t):
	out.write(t)
	out.flush()

missing = object()
count = 0
for change in table.get_all(3, index='value').changes(include_initial=True, include_states=True).run():
	state = change.get('state')
	if state:
		if state == 'ready':
			duration = time.time() - startTime
			print('\n%d initial in %.13f' % (count, duration))
			break
		continue

	new = change.get('new_val', missing)
	old = change.get('old_val', missing)
	
	if len(change) == 1:
		if new is None or old is None:
			pass   # skip 'None' events

		elif new is not None:
			progress('i')    # initial
			count += 1
	elif old is None:
		progress('a')        # add
	elif new is None:
		progress('d')        # delete
	else:
		progress('u')        # update
```
When there's no problem it will print a bunch of "i":s (initial) and then exit (printing the time it took to receive the `ready` state).
When the problem occurs, it will print a bunch of "i":s, then hang (take a longer time than normal), might print "u" (update). Now break the `test-modifier.py` process. Now, `test-listen.py` will never finish; the `ready` state will never be received.
So far, when the modifier process is stopped (at the right time) the query hangs 100% of all the tests I've run.

**Comment by tatsujin1** [comment] 2015-11-30 22:10
And yes, the io-load seems to be approximately zero, `iowait` hovers around 0.3% (according to iostat)

**Comment by danielmewes** [comment] 2015-11-30 22:11
Thanks a lot for the testing code! Again, this is super useful.

**Comment by tatsujin1** [comment] 2015-11-30 23:04
About the delete events; they are complete delete events for documents that are actually not deleted.
Maybe a side-effect of the actual problem, or the cause? ;)

**Comment by danielmewes** [comment] 2015-11-30 23:36
@tatsujin1 The deletions in this case are expected. What they mean is simply that a document that used to have a `value` of `3`, now has a different value.
That is they are "deletions" in the context of the result of `table.get_all(3, index='value')`

**Comment by danielmewes** [comment] 2015-11-30 23:38
I could reproduce the stall with your scripts btw.
What's weird is that once the `test-listen.py` script hangs, it doesn't even wake up if I drop the table. I would expect to get an exception in that case, as the changefeed should be terminated.

**Comment by tatsujin1** [comment] 2015-12-01 07:29
@danielmewes good about the reproduction. Regarding the deletions, yeah I figured it was something like that, but it's slightly confusing (at least, at first) as the `new_val` is `None`.

**Comment by tatsujin1** [comment] 2015-12-01 09:27
Side-node: I noticed that if the `test-modify.py` is simply paused by `^Z`, `test-listen.py` hangs, but it will finish if `test-modify.py` is resumed by `fg`.

**Comment by mlucy** [comment] 2015-12-15 09:52
A fix for this is in `next` and `2.2.x` and will go out in the next point release.

**Closed by mlucy** 2015-12-15 09:52 UTC
Labels: pr:high, st:review, tp:bug

**Comment by tatsujin1** [comment] 2015-12-15 10:43
Nice!

**Comment by williamstein** [comment] 2015-12-15 19:26
Thanks!!!

**Comment by danielmewes** [comment] 2015-12-21 22:59
@tatsujin1 @williamstein The fix for this shipped with RethinkDB 2.2.2 today.

**Comment by tatsujin1** [comment] 2015-12-22 11:44
Verified this (for me, yesterday), and it works!  And as a indirect bonus, receiving the initial batch is a lot faster!

**Comment by williamstein** [comment] 2015-12-28 10:08
I just installed RethinkDB 2.2.2, and it's a total disaster for me.  I getting this traceback constantly as rethinkdb crashes every few minutes:

```
2015-12-28T09:24:29.290186920 87.596129s error: Error in src/rdb_protocol/changefeed.cc at line 1916:
2015-12-28T09:24:29.290228713 87.596170s error: Guarantee failed: [env.has()]
2015-12-28T09:24:29.290242699 87.596184s error: Backtrace:
2015-12-28T09:24:29.542089903 87.848033s error: Mon Dec 28 09:24:29 2015\n\n1 [0xad946a]: backtrace_t::backtrace_t() at ??:?\n2 [0xad994a]: format_backtrace[abi:cxx11](bool) at ??:?\n3 [0xd65806]: report_fatal_error(char const*, int, char const*, ...) at ??:?\n4 [0x8efe46]: ql::changefeed::range_sub_t::apply_ops(ql::datum_t) at ??:?\n5 [0x8f03f3]: ql::changefeed::msg_visitor_t::operator()(ql::changefeed::msg_t::change_t const&) const::{lambda(ql::changefeed::range_sub_t*)#1}::operator()(ql::changefeed::range_sub_t*) const at ??:?\n6 [0x8e32bb]: void ql::changefeed::feed_t::each_sub_in_vec_cb<ql::changefeed::range_sub_t>(std::function<void (ql::changefeed::range_sub_t*)> const&, std::vector<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> >, std::allocator<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> > > > const&, std::vector<int, std::allocator<int> > const&, int) at ??:?\n7 [0x8ed96c]: void pmap<std::_Bind<std::_Mem_fn<void (ql::changefeed::feed_t::*)(std::function<void (ql::changefeed::range_sub_t*)> const&, std::vector<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> >, std::allocator<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> > > > const&, std::vector<int, std::allocator<int> > const&, int)> (ql::changefeed::feed_t*, std::reference_wrapper<std::function<void (ql::changefeed::range_sub_t*)> const>, std::reference_wrapper<std::vector<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> >, std::allocator<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> > > > const>, std::reference_wrapper<std::vector<int, std::allocator<int> > const>, std::_Placeholder<1>)> >(long, long, std::_Bind<std::_Mem_fn<void (ql::changefeed::feed_t::*)(std::function<void (ql::changefeed::range_sub_t*)> const&, std::vector<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> >, std::allocator<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> > > > const&, std::vector<int, std::allocator<int> > const&, int)> (ql::changefeed::feed_t*, std::reference_wrapper<std::function<void (ql::changefeed::range_sub_t*)> const>, std::reference_wrapper<std::vector<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> >, std::allocator<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> > > > const>, std::reference_wrapper<std::vector<int, std::allocator<int> > const>, std::_Placeholder<1>)> const&) at ??:?\n8 [0x8edb6f]: void ql::changefeed::feed_t::each_sub_in_vec<ql::changefeed::range_sub_t>(std::vector<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> >, std::allocator<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> > > > const&, rwlock_in_line_t*, auto_drainer_t::lock_t const&, std::function<void (ql::changefeed::range_sub_t*)> const&) at ??:?\n9 [0x8d69b0]: ql::changefeed::feed_t::each_range_sub(auto_drainer_t::lock_t const&, std::function<void (ql::changefeed::range_sub_t*)> const&) at ??:?\n10 [0x8edfec]: ql::changefeed::msg_visitor_t::operator()(ql::changefeed::msg_t::change_t const&) const at ??:?\n11 [0x8f5f1b]: boost::detail::variant::invoke_visitor<ql::changefeed::msg_visitor_t>::result_type boost::detail::variant::visitation_impl<mpl_::int_<0>, boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<5l>, ql::changefeed::msg_t::stop_t, boost::mpl::l_item<mpl_::long_<4l>, ql::changefeed::msg_t::change_t, boost::mpl::l_item<mpl_::long_<3l>, ql::changefeed::msg_t::limit_start_t, boost::mpl::l_item<mpl_::long_<2l>, ql::changefeed::msg_t::limit_change_t, boost::mpl::l_item<mpl_::long_<1l>, ql::changefeed::msg_t::limit_stop_t, boost::mpl::l_end> > > > > >, boost::mpl::l_iter<boost::mpl::l_end> >, boost::detail::variant::invoke_visitor<ql::changefeed::msg_visitor_t>, void const*, boost::variant<ql::changefeed::msg_t::stop_t, ql::changefeed::msg_t::change_t, ql::changefeed::msg_t::limit_start_t, ql::changefeed::msg_t::limit_change_t, ql::changefeed::msg_t::limit_stop_t>::has_fallback_type_>(int, int, boost::detail::variant::invoke_visitor<ql::changefeed::msg_visitor_t>&, void const*, mpl_::bool_<false>, boost::variant<ql::changefeed::msg_t::stop_t, ql::changefeed::msg_t::change_t, ql::changefeed::msg_t::limit_start_t, ql::changefeed::msg_t::limit_change_t, ql::changefeed::msg_t::limit_stop_t>::has_fallback_type_, mpl_::int_<0>*, boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<5l>, ql::changefeed::msg_t::stop_t, boost::mpl::l_item<mpl_::long_<4l>, ql::changefeed::msg_t::change_t, boost::mpl::l_item<mpl_::long_<3l>, ql::changefeed::msg_t::limit_start_t, boost::mpl::l_item<mpl_::long_<2l>, ql::changefeed::msg_t::limit_change_t, boost::mpl::l_item<mpl_::long_<1l>, ql::changefeed::msg_t::limit_stop_t, boost::mpl::l_end> > > > > >, boost::mpl::l_iter<boost::mpl::l_end> >*) at ??:?\n12 [0x8e1333]: ql::changefeed::real_feed_t::mailbox_cb(signal_t*, ql::changefeed::stamped_msg_t) at ??:?\n13 [0x8f65cf]: void std::_Mem_fn_base<void (ql::changefeed::real_feed_t::*)(signal_t*, ql::changefeed::stamped_msg_t), true>::operator()<signal_t*, ql::changefeed::stamped_msg_t, void>(ql::changefeed::real_feed_t*, signal_t*&&, ql::changefeed::stamped_msg_t&&) const at ??:?\n14 [0x905866]: mailbox_t<void (ql::changefeed::stamped_msg_t)>::read_impl_t::read(read_stream_t*, signal_t*) at ??:?\n15 [0xa07143]: /usr/bin/rethinkdb() [0xa07143] at 0xa07143 ()\n16 [0x9e68e2]: coro_t::run() at ??:?
2015-12-28T09:24:29.542260552 87.848202s error: Exiting.
```

Some information about my system:
```
salvus@db2:~$ rethinkdb -v
rethinkdb 2.2.2~0wily (GCC 5.2.1)
salvus@db2:~$ cat /etc/issue
Ubuntu 15.10 \n \l

salvus@db2:~$ uname -a
Linux db2 4.2.0-22-generic #27-Ubuntu SMP Thu Dec 17 22:57:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I reverted to running the merge of these two branches: mlucy_5085 and mlucy_5086, and with that everything started working again (`rethinkdb -v` outputs `rethinkdb 2.2.0-12-g2daced (GCC 5.2.1)`).  This was very, very stressful.

**Comment by danielmewes** [comment] 2015-12-28 12:31
@williamstein Wow that sucks. So sorry. I opened https://github.com/rethinkdb/rethinkdb/issues/5238, since this looks like an independent issue. Was this without using `include_initial`?

**Comment by williamstein** [comment] 2015-12-28 12:39
> Was this without using include_initial?

Yes.
