### ISSUE TITLE
"build/external/node_0.10.15/bin/npm: No such file or directory"

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4134] opened 2015-04-27 22:43 UTC
On `next` f77c999beb5b993e22df820ce7423f126d8404e3 on arclight:
```
$ ./configure --allow-fetch
* Detecting system configuration
Bash:                           4.2.25(1)-release
Use ccache:                     no
C++ Compiler:                   GCC 4.6.3 (/usr/bin/c++)
Host System:                    x86_64-linux-gnu
Build System:                   Linux 3.2.0-70-generic x86_64
Cross-compiling:                no
Host Operating System:          Linux
Build Architecture:             x86_64
C++11:                          ok
Precompiled web assets:         no
web UI dependencies:            external/admin-deps_2.0.1
Protobuf compiler:              /usr/bin/protoc
python:                         python 2.7.3
Node.js package manager:        external/node_0.10.15
coffee:                         external/coffee-script_1.7.1
Browserify:                     external/browserify_3.24.13
bluebird:                       external/bluebird_2.3.2
wget:                           /usr/bin/wget
curl:                           /usr/bin/curl
Google Test:                    external/gtest_1.6.0
termcap:                        -ltermcap
boost_system:                   -lboost_system
ssl:                            -lssl
protobuf:                       -lprotobuf
icui18n:                        -licui18n
icuuc:                          -licuuc
icudata:                        -licudata
v8 javascript engine:           external/v8_3.30.33.16
RE2:                            external/re2_20140111
z:                              -lz
crypto:                         -lcrypto
curl:                           -lcurl
malloc:                         jemalloc
jemalloc (static):              external/jemalloc_3.6.0
Test protobuf:                  ok
Test boost:                     ok
Installation prefix:            /usr/local
Configuration prefix:           /usr/local/etc
Runtime data prefix:            /usr/local/var
* Wrote configuration to config.mk

$ make clean
    [1/1] RM ./build

$ make -j 50
    [1/390] BUILD node_0.10.15
    [2/390] FETCH admin-deps_2.0.1
    [3/390] INSTALL-INCLUDE gtest_1.6.0
    [4/390] INSTALL-INCLUDE re2_20140111
    [5/390] INSTALL-INCLUDE v8_3.30.33.16
    [6/390] INSTALL-INCLUDE jemalloc_3.6.0
    [7/390] CP build/release/rethinkdb-gdb.py
    [8/390] CONVERT_PROTOFILE build/drivers/ruby/lib/ql2.pb.rb
    [9/390] CONVERT_PROTOFILE build/drivers/python/rethinkdb/ql2_pb2.py
    [10/390] CONVERT_PROTOFILE build/drivers/javascript/proto-def.js
    [11/390] PROTOC[CPP] src/rdb_protocol/ql2.proto
    [12/390] PROTOC[CPP] src/rdb_protocol/ql2_extensions.proto
    [13/390] CP ./build/drivers/ruby/lib
    [14/390] CP ./build/drivers/python/rethinkdb/
    [15/390] CC build/release/obj/rdb_protocol/ql2.pb.o
    [16/390] CC build/release/obj/rdb_protocol/ql2_extensions.pb.o
    [17/390] BUILD v8_3.30.33.16
    [18/390] BUILD re2_20140111
+ :
+ local pcdir=/home/daniel/rethinkdb/build/external/node_0.10.15/lib/pkgconfig
+ [[ -e /home/daniel/rethinkdb/build/external/node_0.10.15/lib/pkgconfig ]]
+ eval ''
+ pkg_fetch
+ pkg_make_tmp_fetch_dir
++ mktemp -d /home/daniel/rethinkdb/external/admin-deps_2.0.1.fetch-XXXXXXXX
+ tmp_dir=/home/daniel/rethinkdb/external/admin-deps_2.0.1.fetch-lWBBCLFA
+ cp /home/daniel/rethinkdb/admin/npm-shrinkwrap.json /home/daniel/rethinkdb/external/admin-deps_2.0.1.fetch-lWBBCLFA
+ cp /home/daniel/rethinkdb/admin/package.json /home/daniel/rethinkdb/external/admin-deps_2.0.1.fetch-lWBBCLFA
+ mkdir /home/daniel/rethinkdb/external/admin-deps_2.0.1.fetch-lWBBCLFA/node_modules
+ in_dir /home/daniel/rethinkdb/external/admin-deps_2.0.1.fetch-lWBBCLFA npm --cache /home/daniel/rethinkdb/external/admin-deps_2.0.1.fetch-lWBBCLFA/npm-cache install
+ local dir=/home/daniel/rethinkdb/external/admin-deps_2.0.1.fetch-lWBBCLFA
+ shift
+ cd /home/daniel/rethinkdb/external/admin-deps_2.0.1.fetch-lWBBCLFA
+ npm --cache /home/daniel/rethinkdb/external/admin-deps_2.0.1.fetch-lWBBCLFA/npm-cache install
++ mktemp -d /home/daniel/rethinkdb/external/npm_cache-XXXXXXXX
+ cache_dir=/home/daniel/rethinkdb/external/npm_cache-wh5kpZzZ
+ /home/daniel/rethinkdb/build/external/node_0.10.15/bin/npm --userconfig /home/daniel/rethinkdb/mk/support/config/npm.conf --cache /home/daniel/rethinkdb/external/npm_cache-wh5kpZzZ --cache /home/daniel/rethinkdb/external/admin-deps_2.0.1.fetch-lWBBCLFA/npm-cache install
/home/daniel/rethinkdb/mk/support/pkg/npm-pkg.inc: line 11: /home/daniel/rethinkdb/build/external/node_0.10.15/bin/npm: No such file or directory

Full error log: ./build/external/admin-deps_2.0.1_fetch.log
make[1]: *** [external/admin-deps_2.0.1] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [make] Error 2

$ ls build/external/node_0.10.15/bin/
node  npm

$ make -j 50
... it all works
```

This might be a race condition / missing dependency between build steps.

I tried the same earlier and when I looked into `build/external/` after the failed `make -j 50` the `node_0.10.15` directory actually wasn't there.

**Comment by danielmewes** [comment] 2015-04-27 22:43
@AtnNn any ideas?

**Comment by danielmewes** [comment] 2015-04-27 22:47
Actually the second `make -j 50` where I wrote "it all works" also failed somewhat later. This might be a completely unrelated issue:
```
$ make -j 50
...
    [368/373] BROWSERIFY build/drivers/javascript/rethinkdb.js
npm http 200 https://registry.npmjs.org/sha.js/-/sha.js-2.3.6.tgz
npm http 200 https://registry.npmjs.org/bn.js/-/bn.js-1.3.0.tgz
npm http 200 https://registry.npmjs.org/elliptic/-/elliptic-1.0.1.tgz
npm http 200 https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz
npm http 200 https://registry.npmjs.org/create-hash
npm http 200 https://registry.npmjs.org/optimist/-/optimist-0.3.7.tgz
npm http GET https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm http GET https://registry.npmjs.org/brorand/-/brorand-1.0.5.tgz
npm http GET https://registry.npmjs.org/hash.js/-/hash.js-1.0.2.tgz
npm http 200 https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm http GET https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm http GET https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm http 200 https://registry.npmjs.org/brorand/-/brorand-1.0.5.tgz
npm http 200 https://registry.npmjs.org/hash.js/-/hash.js-1.0.2.tgz
npm http 200 https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm http 200 https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/daniel/rethinkdb/external/admin-deps_2.0.1.fetch-GAiwOSgK/npm-debug.log
npm ERR! not ok code 0

Full error log: ./build/external/admin-deps_2.0.1_fetch.log
make[1]: *** [external/admin-deps_2.0.1] Error 1
make: *** [make] Error 2
```

The file `./build/external/admin-deps_2.0.1_fetch.log` is on newton in `/home/daniel/4134-admin-deps-fetch.log` and `/home/daniel/rethinkdb/external/admin-deps_2.0.1.fetch-GAiwOSgK/npm-debug.log` is on newton in `/home/daniel/4134-npm-debug.log`

**Comment by AtnNn** [comment] 2015-04-27 22:49
Thanks for the logs, I'll take a look

**Comment by AtnNn** [comment] 2015-04-28 13:32
Duplicate of  #4022

**Closed by AtnNn** 2015-04-28 13:32 UTC
Labels: cp:build
