### ISSUE TITLE
I am trying to install rethinkdb java driver, I add the compile code but it gives the following error

### ISSUE THREAD

**Issue by thatsVishal** [rethinkdb/rethinkdb#5911] opened 2016-07-02 18:40 UTC
**Error:Conflict with dependency 'junit:junit'. Resolved versions for app (4.10) and test app (4.12) differ. See http://g.co/androidstudio/app-test-app-conflict for details.**

**Error:Conflict with dependency 'org.hamcrest:hamcrest-core'. Resolved versions for app (1.1) and test app (1.3) differ. See http://g.co/androidstudio/app-test-app-conflict for details.**

**Comment by bchavez** [comment] 2016-07-02 22:56
Are you trying to build the java driver on android?

https://github.com/rethinkdb/rethinkdb/issues/5253

**Comment by thatsVishal** [comment] 2016-07-04 02:56
yes..

**Comment by deontologician** [comment] 2016-07-04 04:03
The Java driver only compiles with Java 8, and it's not recommended to use
it directly from a client app, since that would mean your database is
exposed across the web to anyone.

**Comment by danielmewes** [comment] 2016-07-06 19:54
Closing as a duplicate of https://github.com/rethinkdb/rethinkdb/issues/5253 (which we do not consider a bug).

@thatsVishal If you have further questions about how to integrate RethinkDB with your application, I suggest dropping by in our Slack channel. You can request an invitation at http://slack.rethinkdb.com

**Closed by danielmewes** 2016-07-06 19:54 UTC
