### ISSUE TITLE
JS driver: Callback when `close` has been called on a cursor

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5056] opened 2015-11-09 19:39 UTC
@ember-max brought this up in https://github.com/rethinkdb/rethinkdb/issues/2577#issuecomment-153793657

Currently if you close a cursor through `cursor.close()`, we don't call any callbacks to indicate that the cursor has been closed.

An argument in favor of the current behavior is that if the application calls `cursor.close()`, it could use its own mechanism to signal the component that consumes the cursor about it being closed, and it's not theoretically necessary to do anything on our end.

However it can be very useful to give the component that registers the callbacks by calling `each` a way to get notified when the cursor has been aborted. E.g. something that visualizes a cursor's results in a browser application might want to display a visual indication that the result is incomplete, or that no more updates are going to be received (in case of a changefeed).

Three options:

1. call the `onFinishedCallback` of the `each` function in case of a call to `cursor.close`. Pro: Uses the existing interface. Con: Makes it impossible to distinguish between the cursor being complete and the cursor being aborted.
2. call the `onFinishedCallback`, but with an additional parameter, e.g. a boolean `gotAborted`.
3. add a new event type `aborted` to the EventEmitter interface http://rethinkdb.com/api/javascript/event_emitter-cursor/. Pro: Users who don't need this type of event don't have to bother with any additional complexity. Con: More difficult to discover

My favorite is option 3, and we could do it together with https://github.com/rethinkdb/rethinkdb/issues/2577 to distinguish between the "cursor exhausted" and the "aborted" case.

**Comment by danielmewes** [comment] 2015-11-09 19:39
(Pinging @deontologician)

**Comment by ember-max** [comment] 2015-11-09 20:19
Given the fact that there's sort of two "interfaces" for using cursors, it seems like you might need option 2 and option 3 - option 3 for when you're using the `EventEmitter` interface, option 2 for when you're using `cursor.each()`. If there weren't the restrictions on using the `EventEmitter` interface after using other `cursor` methods, I would also lean toward just option 3.

I do agree that this can be handled purely with application code, and that's what we've done for now. It made things a little more awkward, and means that other code needs to aware of that application-level convention, whereas just wiring up callback listeners directly with the cursor would feel more standard and less brittle.

**Comment by marshall007** [comment] 2015-11-09 20:51
As mentioned in [#4784 (comment)](https://github.com/rethinkdb/rethinkdb/pull/4784#issuecomment-142113485) I think the `onFinishedCallback` should always act as the error handler (`null` if cursor completed without error).

```js
cursor.each(function(err, row), function()) // current

cursor.each(function(row), function(err)) // callback-style
cursor.each(function(row, done), function(err)) // callback-style w/ async handler
cursor.each(function(row)).catch(function(err)) // promise-style from #4784
```

This would unfortunately be a breaking change, but a trivial one to fix in user code. I think the end result is cleaner than any of the three options @danielmewes proposed. Plus we get to knock out #3702 and get rid of the dedicated `cursor.eachAsync` from #4784 (both would just be `cursor.each`).

**Comment by ember-max** [comment] 2015-11-09 21:24
I'm all for a promise-based API - we currently have our own app-level code wrapping `cursor.each` with a promise ... the breaking change nature of it is something I can't really comment on though.

Just to clarify, in the case of aborting via `cursor.close()`, would that trigger a rejection in the promise-based scenario (i.e., use `catch`)? Or a return value (i.e., `then(function(wasAborted) { ... }))`)?

**Comment by neumino** [comment] 2015-11-30 06:32
Just adding some thoughts here.

`cursor.close()` returns a promise in rethinkdbdash. The main reason is when that when the driver send a `STOP` query, it does get back a `SUCCESS_SEQUENCE` back, meaning that the server does acknowledge that the cursor is closed.
It probably require a bit of work in the driver as you may have to keep two callbacks (since you can have a pending `CONTINUE` query and a `STOP` query)

On a side note, there's some weird edge cases now when closing a cursor with a pending `CONTINUE` query. More info in this issue:
https://github.com/neumino/rethinkdbdash/issues/190

**Comment by deontologician** [comment] 2015-12-09 03:32
One thing to consider with backwards incompatible changes is that we don't follow semantic versioning conventions, which npm etc assume by default. So far it hasn't been much of an issue because we don't make breaking changes

**Comment by danielmewes** [comment] 2015-12-16 02:15
@deontologician That's a good point. From `2.2.x` to `2.3.x` we are theoretically only allowed to add functionality in a backwards-compatible way. Let's keep that separate from this discussion. We can discuss maybe decoupling the JS driver's version from the servers later.

I like @marshall007's proposal of replacing
```js
cursor.each(function(err, row), function()) // current with onFinishedCallback
cursor.each(function(err, row)) // current
```
by
```js
cursor.each(function(row), function(err)) // callback-style
cursor.each(function(row, done), function(err)) // callback-style w/ async handler
cursor.each(function(row)).catch(function(err)) // promise-style from #4784
```

We could either remove `eachAsync`, or keep it around as a simple alias for the third new `each` case.

--

I always forget how this works in JavaScript. Is there a way we can find out the arity of the functions that are passed into `each`? If there is, we could do the following instead which would maintain backwards compatiblity:
```js
cursor.each(function(err, row), function()) // current with onFinishedCallback
cursor.each(function(err, row)) // current

cursor.each(function(row), function(err)) // callback-style
cursor.each(function(row, done), function(err)) // callback-style w/ async handler
cursor.eachAsync(function(row)).catch(function(err)) // promise-style
```

Note that in that case we'd need to keep `eachAsync` around.

This proposal feels a bit unclear to me though, and I think it might be too confusing.

My vote would be for @marshall007's proposal and keeping `eachAsync` as a deprecated alias for `each`.

**Comment by marshall007** [comment] 2015-12-16 21:23
> I always forget how this works in JavaScript. Is there a way we can find out the arity of the functions that are passed into `each`?

@danielmewes yea, you can do `callback.length` which will give you the number of arguments declared in the function signature. This is sketchy at best though because people might reference the `arguments` object directly in the function body and not have anything specified in the signature. Some transpilers do this to support rest parameters and stuff like that, so it might break for people in unexpected ways.

Even if we went that route, I don't see how you would disambiguate between these two styles (since I think people would expect handling `err` to be optional in the second case):

```js
.each(function(err, row), function()) // current with onFinishedCallback
.each(function(row, done), function(err)) // callback-style w/ async handler
```

So I agree, assuming we can get away with the breaking change, I think the original proposal is more consistent and easier to understand.

**Comment by danielmewes** [comment] 2015-12-17 01:11
Yeah it would be quite fragile and probably wouldn't behave as users expect.

I'm going to go ahead and mark this as settled with:
```js
cursor.each(function(row), function(err)) // callback-style
cursor.each(function(row, done), function(err)) // callback-style w/ async handler
cursor.each(function(row)).catch(function(err)) // promise-style from #4784
```
and keeping `eachAsync` as a deprecated alias for the new `each` for now.

My only remaining concern is that it might be a bit of a hassle to implement the `cursor.each(function(row, done), function(err)` version. Assuming I understand it correctly, it will require that we only call the on-row callback after we've determined whether there are more rows or not.
@marshall007 How important do you think that variant is?

**Comment by danielmewes** [comment] 2015-12-17 01:38
Disregard my comment about `cursor.each(function(row, done), function(err)`. I was misremembering what the `done` argument was.

**Comment by neumino** [comment] 2015-12-17 03:31
Just a quick note about 
```
cursor.each(function(row)).catch(function(err)) // promise-style from #4784
```

It's a good syntax but if you want later to have feeds that can automatically resume, you cannot use this syntax (since you can get a change, an error, and then a change)

**Comment by marshall007** [comment] 2015-12-17 17:20
@neumino that's a good point, but I'm not sure it's unique to the promise-style. In the callback style, if the user-specified `onFinishedCallback` is called (regardless of whether an error occurred or not) you should be able to assume the `each` callback will not be fired again. It would be very unintuitive if this were not the case.

I think the solution would be for `each` to capture certain errors and automatically attempt to retry/resume the feed for some period of time before finally failing after some timeout interval or `n` attempts if we can't resume.

**Comment by danielmewes** [comment] 2015-12-17 21:39
I think if we transparently resume changefeeds, we probably won't generate error objects like that. We might insert special "error" documents into the stream to signal that the changefeed is temporarily stalled, but I don't think we would pass that as the "err" object as long as we can still recover from it.

**Comment by marshall007** [comment] 2015-12-18 01:01
@danielmewes yea, exactly. That makes sense for server-side errors; however, if you wanted feeds to be resumable after client-side errors (like disconnects), retry logic would also become necessary.

**Comment by neumino** [comment] 2015-12-18 01:49
Sounds good.
:+1: to @marshall007's proposal :)

**Comment by nighelles** [comment] 2016-02-15 22:36
Ok, trying to write down expected behavior somewhere:
Syntax:
`
cursor.each(function(row), function(err)) // callback-style
cursor.each(function(row, done), function(err)) // callback-style w/ async handler
cursor.each(function(row)).catch(function(err)) // promise-style from #4784
`
Getting to the end of the stream passes null to the error callback, or resolves to null in the promise case.
`done` is a function, and calling it triggers the next element to resolve it's callback.
If a stream is closed, then an error is passed to the error callback, or the promise rejects with an error.

**Comment by marshall007** [comment] 2016-02-16 00:43
@nighelles yep, that looks right. The only clarifications being:

1. With the promise-style, if a promise is returned from the callback it is awaited before iteration continues (just like if you're using `done` in the callback-style). This is how `eachAsync` works from #4784.
2. Decide on what to resolve in `cursor.each(...).then(...)`. Will we accumulate the results or just resolve with the result from the last iteration? I believe `eachAsync` currently resolves from the last iteration, but this is unspecified behavior.

**Comment by marshall007** [comment] 2016-02-16 00:47
Likewise with point (1) if the `done` callback is called with an error (i.e. `done(err, null)`) or if using the promise-style and the inner promise is rejected, these errors are propagated out to the user-specified error handler and iteration is aborted.

**Comment by nighelles** [comment] 2016-02-16 23:31
Is done supposed to be called with arguments?

**Comment by marshall007** [comment] 2016-02-17 00:21
@nighelles yea, I think it should take be a standard Node-style callback `(err, data)`. If `err != null` we're going to abort iteration and propagate the error to the `onFinished` callback. Analogous to what happens if you throw or return a rejected promise from `eachAsync` today. It's the mechanism to allow you to bail out early.

What we do (if anything) with the second argument `data` is an open question related to point (2) above. I think we should probably just ignore it for now because accumulating results by default would be bad if you're scanning an entire table or something.

Later on we could expose a `cursor.map()` which would have all the same semantics as `cursor.each()` but also accumulate the results for you.

**Comment by nighelles** [comment] 2016-02-19 18:58
This is in review 3482. Implemented in nighelles/5056.

**Comment by marshall007** [comment] 2016-02-19 21:55
@nighelles I was able to simplify this a bit by taking advantage of the handy utility functions built into `bluebird`: https://github.com/rethinkdb/rethinkdb/compare/nighelles/5056...marshall007:5056_refactor

Continuing to support the `return false` behavior from the callback feels dirty and too subtle now that we have the other mechanisms for terminating iteration early. I don't think we should allow you to do that anymore. Also, I thought we were implementing the new behavior on top of `.each()` and deprecating `.eachAsync()`. Is that still the plan?

**Comment by nighelles** [comment] 2016-02-19 22:09
I think @danielmewes and I discussed putting the new functionality into eachAsync to avoid breaking existing functionality.

**Comment by nighelles** [comment] 2016-02-22 20:04
@marshall007 
Can you issue a pull request for this change against my branch?

**Comment by marshall007** [comment] 2016-02-22 23:10
@nighelles PR up at #5436.

**Comment by nighelles** [comment] 2016-02-23 23:55
This is in next, was in review 3482.

Thanks @marshall007

**Closed by nighelles** 2016-02-23 23:55 UTC
Labels: JavaScript / Coffee, tp:API_settled, tp:ReQL_proposal
