### ISSUE TITLE
Delete is throwing an error on large documents

### ISSUE THREAD

**Issue by leolorenzoluis** [rethinkdb/rethinkdb#5368] opened 2016-02-06 20:15 UTC
I'm trying to clean up a table that has big number of documents in it. The number of documents probably is ~5-7 million. Obviously, I'm pushing it too hard, but even if I try to limit it to 100,000 or filter it with index then delete those, it still chokes up. I also tried restarting RethinkDB Server and clean up cache.

    r.db("database").table("sampletable").delete()

    e: Query terminated by an unknown cause in:
    r.db("database").table("sampletable").delete()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by danielmewes** [comment] 2016-02-07 02:59
Hi @leolorenzoluis, I think the query is timing out, which is something specific to the Data Explorer.

I recommend running the query with a different client (e.g. with the node.js REPL, or with Python), as the other official clients are not affected by this.

Related: https://github.com/rethinkdb/rethinkdb/issues/2316

The particular error message you're getting "Query terminated by an unknown cause" is not correct though. We've seen this happening before with Data Explorer timeouts, but haven't been able to find out why the wrong error message is shown. @Tryneus is there any particular information that @leolorenzoluis could provide for helping us with figuring out why the wrong interruption cause is generated?

**Comment by danielmewes** [comment] 2016-02-07 03:00
The bug for the incorrect error message is https://github.com/rethinkdb/rethinkdb/issues/5113 .

I'm closing this since the timeout itself is expected behavior in the Data Explorer, and we already have an issue for the error message.

**Closed** 2016-02-07 02:59 UTC

**Comment by leolorenzoluis** [comment] 2016-02-07 07:28
@danielmewes I tried running other client, but not the official clients (Python, Node) and still failed. I haven't investigate further if it's because the library from [here](https://github.com/hamiltop/rethinkdb-elixir) or it's rethinkdb.

**Comment by danielmewes** [comment] 2016-02-08 21:49
@leolorenzoluis Did you get the same error message with rethinkdb-elixir?
It looks like there's a `timeout` option to `run` in that driver, which defaults to 5,000 ms / 5 seconds if I'm reading it correctly:
https://github.com/hamiltop/rethinkdb-elixir/blob/master/lib/rethinkdb/connection.ex#L94

You can try overriding this.
