### ISSUE TITLE
segfault in rethinkdb 2.2.4

### ISSUE THREAD

**Issue by moserrya** [rethinkdb/rethinkdb#5502] opened 2016-03-11 00:36 UTC
appears similar to: https://github.com/rethinkdb/rethinkdb/issues/4675

```
2016-03-10T23:58:44.852393561 75754.601309s error: Error in src/arch/runtime/thread_pool.cc at line 359:
2016-03-10T23:58:45.157201653 75754.906429s error: Segmentation fault from reading the address 0x18.
2016-03-10T23:58:45.187055884 75754.934477s error: Backtrace:
```

There was no backtrace. The server hung until I restarted the EC2 instance. This happened while writing ~30 documents/s and building a secondary index on a timestamp on a 90M document table. This instance was deployed using the RethinkDB marketplace page. Please let me know what other details would be useful and I will do my best to provide them.

**Comment by danielmewes** [comment] 2016-03-11 00:45
Thanks for the bug report.
It's probably also the same as https://github.com/rethinkdb/rethinkdb/issues/5348

Unfortunately we still don't know why this happens, though inserting documents was mentioned in the other thread as well as a potential trigger for this.

We'll bump the priority of this and run additional tests on our end.

I'm going to close this as a duplicate of #5348, just to keep things in a single place.

**Closed by danielmewes** 2016-03-11 00:45 UTC
