### ISSUE TITLE
Error in changefeed.cc at line 1164

### ISSUE THREAD

**Issue by CodeX604** [rethinkdb/rethinkdb#6695] opened 2018-08-02 23:13 UTC
I was testing about ~4000 simultaneous change feeds, when I managed to crash rethinkdb.exe with the following info on screen:

Version: rethinkdb 2.3.6-windows (MSC 190024215)
error: Error in thread 3 in src\rdb_protocol\changefeed.cc at line 1164:
error: Guarantee failed: [inserted]
error: Backtrace:
error: Thu Aug  2 16:04:55 2018

       1: 0x00007FF69447372F [The specified module could not be found.]
       2: 0x00007FF694474277 [Attempt to access invalid address.]
       3: 0x00007FF69485A151 [Attempt to access invalid address.]
       4: 0x00007FF69491C187 [Attempt to access invalid address.]
       5: 0x00007FF6948BC19E [Attempt to access invalid address.]
       6: 0x00007FF69492A367 [Attempt to access invalid address.]
       7: 0x00007FF6948CC2AE [Attempt to access invalid address.]
       8: 0x00007FF6948CC763 [Attempt to access invalid address.]
       9: 0x00007FF69446CC5E [Attempt to access invalid address.]
       10: 0x00007FF69446AFB5 [Attempt to access invalid address.]
       11: GetOsSafeBootMode+241
error: Exiting.

And the following info in the log:

2018-08-02T16:04:55.778041200 4534.512346s error: Error in thread 3 in src\\rdb_protocol\\changefeed.cc at line 1164:
2018-08-02T16:04:55.779039800 4534.514055s error: Guarantee failed: [inserted] 
2018-08-02T16:04:55.780041100 4534.514719s error: Backtrace:
2018-08-02T16:04:55.800039700 4534.535016s error: Thu Aug  2 16:04:55 2018\n\n1: 0x00007FF69447372F [The specified module could not be found.]\n2: 0x00007FF694474277 [Attempt to access invalid address.]\n3: 0x00007FF69485A151 [Attempt to access invalid address.]\n4: 0x00007FF69491C187 [Attempt to access invalid address.]\n5: 0x00007FF6948BC19E [Attempt to access invalid address.]\n6: 0x00007FF69492A367 [Attempt to access invalid address.]\n7: 0x00007FF6948CC2AE [Attempt to access invalid address.]\n8: 0x00007FF6948CC763 [Attempt to access invalid address.]\n9: 0x00007FF69446CC5E [Attempt to access invalid address.]\n10: 0x00007FF69446AFB5 [Attempt to access invalid address.]\n11: GetOsSafeBootMode+241
2018-08-02T16:04:55.801039800 4534.536059s error: Exiting.

I'm not sure it's repeatable.  I'll update if it is.

Thanks.

**Comment by srh** [comment] 2018-08-03 05:36
Thanks for the bug report.

**Comment by CodeX604** [comment] 2018-08-07 15:47
Happened again under similar circumstances:

Version: rethinkdb 2.3.6-windows (MSC 190024215)
error: Error in thread 3 in src\rdb_protocol\changefeed.cc at line 1164:
error: Guarantee failed: [inserted]
error: Backtrace:
error: Tue Aug  7 08:40:31 2018

       1: 0x00007FF78AEA372F [The specified module could not be found.]
       2: 0x00007FF78AEA4277 [Attempt to access invalid address.]
       3: 0x00007FF78B28A151 [Attempt to access invalid address.]
       4: 0x00007FF78B34C187 [Attempt to access invalid address.]
       5: 0x00007FF78B2EC19E [Attempt to access invalid address.]
       6: 0x00007FF78B35A367 [Attempt to access invalid address.]
       7: 0x00007FF78B2FC2AE [Attempt to access invalid address.]
       8: 0x00007FF78B2FC763 [Attempt to access invalid address.]
       9: 0x00007FF78AE9CC5E [Attempt to access invalid address.]
       10: 0x00007FF78AE9AFB5 [Attempt to access invalid address.]
       11: GetOsSafeBootMode+241
error: Exiting.

2018-08-07T08:40:31.683262200 1424.142753s error: Error in thread 3 in src\\rdb_protocol\\changefeed.cc at line 1164:
2018-08-07T08:40:31.684261700 1424.143025s error: Guarantee failed: [inserted] 
2018-08-07T08:40:31.684261701 1424.143111s error: Backtrace:
2018-08-07T08:40:31.693262100 1424.152413s error: Tue Aug  7 08:40:31 2018\n\n1: 0x00007FF78AEA372F [The specified module could not be found.]\n2: 0x00007FF78AEA4277 [Attempt to access invalid address.]\n3: 0x00007FF78B28A151 [Attempt to access invalid address.]\n4: 0x00007FF78B34C187 [Attempt to access invalid address.]\n5: 0x00007FF78B2EC19E [Attempt to access invalid address.]\n6: 0x00007FF78B35A367 [Attempt to access invalid address.]\n7: 0x00007FF78B2FC2AE [Attempt to access invalid address.]\n8: 0x00007FF78B2FC763 [Attempt to access invalid address.]\n9: 0x00007FF78AE9CC5E [Attempt to access invalid address.]\n10: 0x00007FF78AE9AFB5 [Attempt to access invalid address.]\n11: GetOsSafeBootMode+241
2018-08-07T08:40:31.693262101 1424.152822s error: Exiting.

Please let me know if you'd like me to re-run with more tracing.

Thanks

**Comment by srh** [comment] 2018-08-08 21:43
I think people have seen crashes in limit change feeds before.  This crash involves a limit change feed.  You might want to avoid using limit() with change feeds.

**Comment by CodeX604** [comment] 2018-08-08 22:31
What are my alternatives if I need to use limit()?  For my use cases, I'm interested in changes in the top 'n' of something.  i.e. orderby().limit()

**Comment by srh** [comment] 2018-08-09 23:03
You could listen for all changes and maintain the top N list yourself.  Or you could poll the database every k seconds for a top N list.  My advice, if you need to ensure the top N list is accurate, but don't want a performance cost from polling frequently, is to use a change feed to figure out whether you can poll less often -- only recompute the list based on direct results of a single orderby().limit() query.

Don't try to piece together information out of the change feed entries to maintain the list in a clever manner.  That's complicated and easy to screw up because then you have to deal with problems like determining whether or not the change feed's changes were applied before or after your latest orderby().limit() query's results.

Another option is to have the bug in the database fixed.

**Comment by srh** [comment] 2019-01-29 12:59
I found a bug in limit changefeeds -- do_read incorrectly releases the superblock in some cases.  Maybe it's the cause.  Will hopefully fix it.

**Comment by srh** [comment] 2019-02-07 16:20
I am going to tentatively close this issue, because it might be fixed with #6710.

**Closed by srh** 2019-02-07 16:20 UTC
