### ISSUE TITLE
make Failure

### ISSUE THREAD

**Issue by alx696** [rethinkdb/rethinkdb#5645] opened 2016-04-12 01:38 UTC
$ make -j 4

[40/425] CC build/release/obj/clustering/immediate_consistency/backfillee.o
In file included from ./src/clustering/administration/servers/server_metadata.hpp:10:0,
                 from ./src/clustering/administration/tables/table_metadata.hpp:12,
                 from ./src/clustering/table_contract/contract_metadata.hpp:12,
                 from ./src/clustering/table_contract/coordinator/coordinator.hpp:6,
                 from ./src/clustering/table_manager/table_manager.hpp:5,
                 from ./src/clustering/table_manager/multi_table_manager.hpp:8,
                 from src/clustering/table_manager/multi_table_manager.cc:2:
./src/rpc/mailbox/typed.hpp: In member function ‘void mailbox_t<void(a0_t, a1_t, a2_t, a3_t, a4_t, a5_t, a6_t, a7_t)>::read_impl_t::read(read_stream_t_, signal_t_) [with arg0_t = uuid_u; arg1_t = multi_table_manager_timestamp_t; arg2_t = multi_table_manager_bcard_t::status_t; arg3_t = boost::optional<table_basic_config_t>; arg4_t = boost::optional<raft_member_id_t>; arg5_t = boost::optional<raft_persistent_state_t<table_raft_state_t> >; arg6_t = boost::optional<raft_start_election_immediately_t>; arg7_t = mailbox_addr_t<void()>]’:
./src/rpc/mailbox/typed.hpp:806:20: warning: ‘_((void_)& arg6 +4)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             arg6_t arg6;
                    ^

[424/425] BUILD openssl_1.0.1i
    [425/425] LD build/release/rethinkdb
/usr/bin/ld: /home/m/app/rethinkdb/build/external/openssl_1.0.1i/lib/libssl.a(ssl_algs.o): undefined reference to symbol 'EVP_dss1@@OPENSSL_1.0.0'
/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/build.mk:334: recipe for target 'build/release/rethinkdb' failed
make[1]: **\* [build/release/rethinkdb] Error 1
Makefile:52: recipe for target 'make' failed
make: **\* [make] Error 2

---

external/openssl_1.0.1i/lib not exists!

**Comment by VeXocide** [comment] 2016-04-12 01:57
The `-Wmaybe-uninitialized` error is a duplicate of #5635 which I fixed this morning, the link error is odd.

**Comment by danielmewes** [comment] 2016-04-19 18:47
@alx696 On which platform / operating system version was this? What was the output of the `configure` command?
Can you try running `make -j 4 ALLOW_WARNINGS=1` and see if the linker error still occurs?

**Comment by militant-daos** [comment] 2016-08-12 09:22
@danielmewes , I have also faced this issue when tried to run `make` command.
My platform is x86_64, OS - Bunsenlabs Linux (based on Debian Jessie).

I have tried to run `make` with `ALLOW_WARNINGS=1` but the issue still remains. As far as I understand this is not a problem with compilation but a missing DSO name for libcrypto target. 

Probably, this may be a particular issue with the external package, fetched by `configure`.

**Comment by militant-daos** [comment] 2016-08-12 09:34
@danielmewes , I think I have found the source of the problem. According to the output, generated by `make` target `build_crypto` fails during LD link stage:

> /usr/bin/ld: /home/victor/work/rethinkdb/build/external/openssl_1.0.1t/lib/libssl.a(ssl_algs.o): undefined reference to symbol 'EVP_dss1@@OPENSSL_1.0.0'
> //usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: error adding symbols: DSO missing from command line

Here we may see that LD tries to search DSOs in /usr/lib directory instead of `external` and this is the bug, because when I have tried to launch `make` for the first time I *have not installed libssl-dev* because I knew that it will be fetched by `configure`. So when LD had tried to find proper DSOs it had found them missing from their usual locations and it had not tried to look into `external`.

Currently, a quick fix for this issue is to install `libssl-dev` dependency manually via the packet manager, and do not fetch it with `configure`.

I have tried to locate the corresponding makefile but currently I'm not familiar enough with the source tree of the project; if the bug remains to be not fixed I may work on it in my fork repo later.

**Comment by jln1989** [comment] 2016-11-29 05:55
@militant-daos @danielmewes : Am still getting this issue with 2.3.5 branch version. Any solution as to how to proceed? I have tried to install libssl-dev seperately, make clean and other suggestions that I could find.

Both make and make install fails for me.

**Comment by AtnNn** [comment] 2016-11-29 22:06
If you are running into this issue, can you please share the contents of `config.mk` and `external/openssl*.log`?

**Comment by jln1989** [comment] 2016-11-30 05:13
@AtnNn : I have attached both the log files and let me know what else you need to help me out.
[configmk.txt](https://github.com/rethinkdb/rethinkdb/files/621033/configmk.txt)
[openssllog.zip](https://github.com/rethinkdb/rethinkdb/files/621038/openssllog.zip)

**Comment by yaguangtang** [comment] 2017-08-20 04:57
can't build with master branch on arm64 stretch with following error 

/usr/bin/ld: /rethinkdb/build/external/openssl_1.0.2l/lib/libssl.a(ssl_algs.o): undefined reference to symbol 'EVP_dss1@@OPENSSL_1.0.2d'
//usr/lib/aarch64-linux-gnu/libcrypto.so.1.0.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/build.mk:337: recipe for target 'build/release_system/rethinkdb' failed
make[1]: *** [build/release_system/rethinkdb] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2

**Comment by TheCyberRonin** [comment] 2017-09-26 01:50
Same issue as above^^

**Comment by srh** [comment] 2017-09-28 06:49
I have no clue about ARM but some amd64 stretch building news is here: https://github.com/rethinkdb/rethinkdb/issues/6375#issuecomment-332742675

**Comment by TheCyberRonin** [comment] 2017-09-28 13:14
I'm trying it out now, will update if it builds correctly.

**Closed** 2017-12-12 22:29 UTC
Labels: cp:build

**Comment by cyrixSpec** [comment] 2020-11-06 06:46
same issue here,
any hints to solve this ?

```
/usr/bin/ld: /home/rock/rethinkdb-2.4.1/build/external/openssl_1.0.2l/lib/libssl.a(ssl_cert.o): undefined reference to symbol 'OPENSSL_DIR_read@@OPENSSL_1_1_0'
/usr/bin/ld: //lib/aarch64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [src/build.mk:341: build/release_clang/rethinkdb] Error 1
make: *** [Makefile:53: make] Error 2
# make LIBS="-lssl -lcrypto"
make: Possibly unknown variables: LIBS
    [1/1] LD build/release_clang/rethinkdb
/usr/bin/ld: /home/rock/rethinkdb-2.4.1/build/external/openssl_1.0.2l/lib/libssl.a(ssl_cert.o): undefined reference to symbol 'OPENSSL_DIR_read@@OPENSSL_1_1_0'
/usr/bin/ld: //lib/aarch64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [src/build.mk:341: build/release_clang/rethinkdb] Error 1
make: *** [Makefile:53: make] Error 2

```

**Comment by srh** [comment] 2020-11-07 02:04
What platform and what RethinkDB version?
