### ISSUE TITLE
work out what goes wonky with .gitattributes

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5597] opened 2016-04-04 20:08 UTC
A few of us have had odd problems that were traced back to the `.gitattributes` addition recently. We should probably figure out exactly what is happen and work to mitigate those problems. One example was the first section of #5595.

For those who might be directed her to fix temporary problems, here is the workaround, do this from the root of the repository:
1.  `echo "" > ./.gitattributes` to wipe away the settings (temporarily)
2. `git checkout` everything that is having this problem
3. `git checkout .gitattributes` again to re-set it

**Comment by AtnNn** [comment] 2016-04-05 00:01
Sorry about that, I introduced the `.gitattributes` to fix issues with line endings on windows. I haven't ran into any problems with it myself. What odd problems have you run into? If I can reproduce them I would be happy to try to fix them.

**Comment by Tryneus** [comment] 2016-04-05 00:25
@AtnNn - I seem to be ending up with files that I haven't modified, but git reports them as modified, and I can't discard the changes.  This usually seems to show up when I'm switching/merging branches.  Example:

```
grey@newton:~/rethinkdb/src$ git checkout -- ../external
grey@newton:~/rethinkdb/src$ git status
# On branch grey_issue_5458
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#    modified:   ../external/gtest_1.7.0/msvc/gtest-md.sln
#    modified:   ../external/gtest_1.7.0/msvc/gtest-md.vcproj
#    modified:   ../external/gtest_1.7.0/msvc/gtest.sln
#    modified:   ../external/gtest_1.7.0/msvc/gtest.vcproj
#    modified:   ../external/gtest_1.7.0/msvc/gtest_main-md.vcproj
#    modified:   ../external/gtest_1.7.0/msvc/gtest_main.vcproj
#    modified:   ../external/gtest_1.7.0/msvc/gtest_prod_test-md.vcproj
#    modified:   ../external/gtest_1.7.0/msvc/gtest_prod_test.vcproj
#    modified:   ../external/gtest_1.7.0/msvc/gtest_unittest-md.vcproj
#    modified:   ../external/gtest_1.7.0/msvc/gtest_unittest.vcproj
```

**Comment by mbroadst** [comment] 2016-04-10 22:02
yeah on a fresh checkout for me (like absolutely fresh, new folder, new fork from github etc), I get this:

```
mbroadst@retinoid:rethinkdb-mbroadst (next=)$ git status
On branch next
Your branch is up-to-date with 'origin/next'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   admin/static/js/date-en-US.js
	modified:   test/performance/comparisons/jquery.tablesorter.js
	modified:   test/rql_test/connections/http_support/jinja2/LICENSE.txt
	modified:   test/rql_test/connections/http_support/werkzeug/LICENSE.txt
```

This is pretty annoying. I was fetching changes from upstream on my local fork to submit a patch, and now I have to run through a number of other hoops

**Comment by larkost** [comment] 2016-04-13 22:23
I worked on this a bit today and have come up with two solutions:
1. We remove the `*  text=auto` line that is telling `git` to guess which files we want to have it mange. We already have rules to auto-convert `.cc`, `.hpp`, `.h`, and `.tcc` files (we might want to add `.c`, but have nothing at the moment), and rules to prevent conversion of `.sh`, `./configure`, and everything in `./mk/support/pkg/`. This could have side-effects that I have not thought of, but would mostly just go back to the behavior we had before (blindly not caring), except controlling for issues that would get in the way of a Windows compile.
2. Commit the few changes that it is coming up with on a clean `clone`. These are all files that were brought in form other projects, and have CLRF line endings (in one case it has mixed line endings). For the issues that @Tryneus listed we would probably have to add those extensions to the `eol=lf` list. This solution would be more aggressive in managing the line endings, even when they don't have an effect on building Windows. Once we make it though some growing pains we should never have any more of these problems since `git` will be magically altering things for us (in theory).

A side note: I don't know whether our current process of bundling the `.js` files up for the WebUI normalizes line endings. But if we go with option 1 we might get subtle differences in the WebUI line endings depending on where you compile from. I don't think that this should matter, but if anyone ever checksums things they might see a difference.

**Comment by danielmewes** [comment] 2016-04-20 23:17
I committed the line ending changes for the files @mbroadst listed to next and v2.3.x in order to avoid #5622 for Ubuntu Xenial (#5697). (i.e. I did option 2).

It looks like the set of files that `git` wants to change is slightly different on different systems though, so there might still be a few files with wrong line endings.

**Comment by mbroadst** [comment] 2016-04-21 12:25
hm, I'm seeing a different list today when I pulled in next from upstream, with some familiar faces:

```
	modified:   admin/static/fonts/copse_OFL.txt
	modified:   admin/static/fonts/open-sans_LICENSE.txt
	modified:   admin/static/js/date-en-US.js
	modified:   test/performance/comparisons/jquery.tablesorter.js
	modified:   test/rql_test/connections/http_support/jinja2/LICENSE.txt
	modified:   test/rql_test/connections/http_support/werkzeug/LICENSE.txt
```

**Comment by danielmewes** [comment] 2016-04-21 18:58
@mbroadst Those are the files I committed. Can you try clearing out `.gitattributes` and then pulling again (and then checking out `.gitattributes` again)?

Alternatively I was able to resolve this in one case by deleting those files locally through `rm` (not `git rm`), and then checking them out again.

**Comment by mbroadst** [comment] 2016-04-21 19:05
@danielmewes yeah looks like they are indeed fixed, I had just pulled from your upstream repo into my local forks clone without cleaning up properly. I just did a fresh checkout of next and there are no "bad files"

**Comment by Tryneus** [comment] 2016-06-27 22:56
I just got this again today for these files:

```
#	modified:   admin/static/fonts/copse_OFL.txt
#	modified:   admin/static/fonts/open-sans_LICENSE.txt
#	modified:   admin/static/js/date-en-US.js
#	modified:   test/performance/comparisons/jquery.tablesorter.js
#	modified:   test/rql_test/connections/http_support/jinja2/LICENSE.txt
#	modified:   test/rql_test/connections/http_support/werkzeug/LICENSE.txt
```

**Comment by srh** [comment] 2017-12-21 01:44
Gonna close this -- wind0ze users plz get your act together :-)

**Closed by srh** 2017-12-21 01:44 UTC
