### ISSUE TITLE
@question - is it possible to configure rethinkdb to log to remote rsyslog server?

### ISSUE THREAD

**Issue by lewisbarber** [rethinkdb/rethinkdb#4940] opened 2015-10-10 12:01 UTC

**Comment by danielmewes** [comment] 2015-10-12 20:56
I'm not sure.
This might be possible by redirecting stdout and stderr of the RethinkDB process into an rsyslog client of some sort.

@larkost, @AtnNn do you have any ideas for this?

**Comment by danielmewes** [comment] 2015-10-12 20:58
Closing because it's not a bug or feature request. But we can still discuss possible answers on here.
For general questions about RethinkDB, our Google group might be the better place: https://groups.google.com/forum/#!forum/rethinkdb

**Closed by danielmewes** 2015-10-12 20:58 UTC

**Comment by encryptio** [comment] 2015-10-12 21:08
Piping data to `logger(1)` will send messages to the local syslog. You could send your messages to e.g. `local1` with `logger`'s command line flags and then could configure `/etc/rsyslog.conf` to forward those to a remote syslog server (and log them to local files too, if you want.) I don't know the precise details of all this, but it's what was used at multiple of my previous jobs.
