### ISSUE TITLE
Started multiple instances quickly and got issue for database that doesn't exist. 

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/rethinkdb#4788] opened 2015-09-02 19:46 UTC
![screenshot 2015-09-02 13 45 10](https://cloud.githubusercontent.com/assets/863286/9642357/ec338676-5178-11e5-99df-9298e039228c.png)

![screenshot 2015-09-02 13 47 25](https://cloud.githubusercontent.com/assets/863286/9642396/2cccfb18-5179-11e5-89a6-120f48311d32.png)

![screenshot 2015-09-02 13 48 15](https://cloud.githubusercontent.com/assets/863286/9642421/483baa20-5179-11e5-9951-1ae0edcd7099.png)

Had single instance running with multiple tables that have no shading/replication rules and now can't fix because the database doesn't exist. I can also not remove the database but the issue persists.

**Comment by dalanmiller** [comment] 2015-09-02 19:54
Even though the "__deleted_database__" wasn't listed in the database list, and I couldn't change the sharding/replication settings, the GUI did allow me to click the "Operations" dropdown and delete the database which removed the issue but I think this issue should remain open and may be related to #4727

**Comment by danielmewes** [comment] 2015-09-02 20:10
What exactly do you mean by "started multiple instances quickly"? Did you restart servers that were already in a cluster? Or did you join new servers to an existing cluster?

When and where did you create the tables?

**Comment by dalanmiller** [comment] 2015-09-03 05:16
All happening locally, I keep one primary instance running with `launchd`, I then added two additional instances manually and joined them to the launchd instance. Shortly after creating them, I shut them down but from what I saw they had completely started up. 

All the tables were already created on this primary instance prior to joining these two instances.

**Comment by danielmewes** [comment] 2015-09-03 20:30
Ok that definitely makes it odd that there would be a table without a database after this.

Was the `questions` table the only one that was affected or were did the other tables also lose their database(s)?

**Comment by dalanmiller** [comment] 2015-09-03 22:55
That was the only table that was affected afaik since that was the only one that was listed in the issues dropdown. All other tables are/were fine.

**Comment by danielmewes** [comment] 2015-09-03 23:25
Could that table have existed on one of the additional two nodes before you joined them to the existing ones?

I wonder if the servers somehow synchronized their tables, but didn't have time to synchronize the database semilattice.

**Comment by danielmewes** [comment] 2015-10-29 19:14
As far as I know, we couldn't reproduce this again.
It seems plausible that this was a consequence of very quickly starting and stopping a server, which might have synchronized some parts of the metadata to the other servers but not other parts before getting shut down again.

I suspect that fixing this completely is more work than what it's worth. Closing as `wontfix` under the assumption that the problem is rare. If this occurs again, we can re-open the issue.

**Closed by danielmewes** 2015-10-29 19:14 UTC
Labels: tp:bug
