### ISSUE TITLE
Consider string-array polymorphism

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#264] opened 2013-01-29 22:56 UTC
If we treat strings as arrays of characters, every operation that works on an array can work on a string and vice versa. This sounds like it's worth doing both because of pragmatism and beauty.

**Comment by danielmewes** [comment] 2015-01-20 23:42
I think we should implement `.count` for strings. It should count the number of Unicode characters, and not the number of bytes. Should be pretty easy now that @gchpaco has implemented UTF-8 support for `split`.
`count` would be O(n) on strings, but I think that's fine.

Similarly I think `splice` would be useful, and it should be UTF-8 aware.

**Comment by gchpaco** [comment] 2015-01-21 00:01
I have no issue with this provided we define it as counting codepoints. (characters is sort of fuzzy semantically.)

**Comment by danielmewes** [comment] 2015-01-21 00:09
Ah yeah, code points sound reasonable.

**Comment by neumino** [comment] 2015-02-04 05:59
Any chance to schedule that for 2.0?

Especially `count`/`length` and `slice` (to extract snippets). It's kind of frustrating when people run into that.

**Comment by coffeemug** [comment] 2015-02-04 06:21
I think we should open specific issues for the commands that we want to make polymorphic on strings arrays (the two that always come up are `count` and `slice`). I don't think it's worth keeping the general issue around.

**Comment by marshall007** [comment] 2015-02-05 05:19
`match` is another one, see #2578. The specific issue for `count` #1146 was closed as a dupe of this so that should be reopened if this is to be closed.

**Comment by danielmewes** [comment] 2015-05-13 19:34
Sorry this was pushed back for a while.
I opened https://github.com/rethinkdb/rethinkdb/issues/4227 and https://github.com/rethinkdb/rethinkdb/issues/4228 for `slice` and `count`.

**Comment by danielmewes** [comment] 2015-05-13 19:35
Closing this one instead.

**Closed by danielmewes** 2015-05-13 19:35 UTC
Labels: cp:reql, tp:ReQL_proposal
