### ISSUE TITLE
Allow Hyphen-minus in db names and table names

### ISSUE THREAD

**Issue by oliverjanik** [rethinkdb/rethinkdb#5658] opened 2016-04-13 04:51 UTC
https://en.wikipedia.org/wiki/Hyphen-minus

I tried searching around. Couldn't find anything about why it's not allowed.

**Comment by encryptio** [comment] 2016-04-13 19:02
Closing as a dupe of https://github.com/rethinkdb/rethinkdb/issues/5537

I personally agree it should be allowed. :P

**Closed by encryptio** 2016-04-13 19:02 UTC
Labels: tp:ReQL_proposal
