### ISSUE TITLE
GetAll and orderBy with indexes

### ISSUE THREAD

**Issue by alehano** [rethinkdb/rethinkdb#4325] opened 2015-06-02 09:57 UTC
I have an object like this:

```go
Company {
  Enable bool
  Pro bool
  Type int
  Categories []int
}
```
So, how can I make query to retrieve all objects that Enable=true, Categories contains, for example, "1" and order by Pro and Type. I have more than 200,000 records so I have to to that efficient with indexes.

**Comment by alehano** [comment] 2015-06-02 15:38
I try to use this:
```go
r.db("test_main").table("companies").indexCreate("ListAll", function(comp) {
    return comp("Categories").map(function(cat) {
        return [ comp("Pro"), comp("CompType"), comp("Enabled"), cat  ];
    });
}, {multi: true})


r.db("test_main").table("companies").between([false, 0, true, 1],
  [r.maxval, r.maxval, true, 1], {index:"ListAll"}).orderBy({index:r.desc("ListAll")}).limit(100)
```
But categories doesn't match.

**Comment by danielmewes** [comment] 2015-06-02 18:40
Hi @alehano,

Compound indexes are ordered lexicographically. That means that you have to put the components that are constant in your query first, and the ones that can vary to the end:

```js
r.db("test_main").table("companies").indexCreate("ListAll", function(comp) {
    return comp("Categories").map(function(cat) {
        return [ comp("Enabled"), cat, comp("Pro"), comp("CompType") ];
    });
}, {multi: true})

r.db("test_main").table("companies").between([true, 1, r.minval, r.minval],
  [true, 1, r.maxval, r.maxval], {index:"ListAll"}).orderBy({index:r.desc("ListAll")}).limit(100)
```

**Comment by danielmewes** [comment] 2015-06-02 18:41
Closing because this is not a bug, but please feel free to ask further questions.

**Closed by danielmewes** 2015-06-02 18:41 UTC

**Comment by alehano** [comment] 2015-06-02 19:55
Thanks, @danielmewes 
But, I want to select category range, e.g. from 1 to 10 but at the same time order by "Pro" and then by "CompType". But in case if I put "cat" before, it'll be sorted by "cat".

**Comment by danielmewes** [comment] 2015-06-03 00:33
Oh I see. I missed that part.
How many categories are we talking about?
Maybe you could just use a `union` ( rethinkdb.com/api/javascript/union/ ) and do multiple `between` queries as described above for each category individually?

**Comment by alehano** [comment] 2015-06-03 04:18
But if I'll be using Union it'll  just concat cats group, and in the end also be sorted by category isn't it?

**Comment by danielmewes** [comment] 2015-06-03 18:36
You're right, I wasn't thinking that through. Unfortunately there isn't a great way of doing this in ReQL at the moment. The best you can do is to do the sorting without an index at the end. It's a bit slower, but probably fine for a moderate number of results. How many results do you typically expect from this query (that is before the `limit(100)`)?

**Comment by danielmewes** [comment] 2015-06-03 18:41
I opened https://github.com/rethinkdb/rethinkdb/issues/4338 to add such a functionality to ReQL. I can't tell for sure when we'll get to it yet, but we'll keep it on our list.

**Comment by bloodknight2010** [comment] 2017-08-01 09:33
Hell All,
My Query is `self.questions.get_all(user_id,index='userId').order_by(r.desc('stamp')).slice(0,30).run(time_format="raw")`
I want to create get_all and order_by timestamp with indexes. How to do?Pls help me.

**Comment by chrisvariety** [comment] 2017-08-01 13:00
@bloodknight2010 You'll need to setup a compound index:

```
r.table('questions').indexCreate('userIdAndStamp', function(question) {
  return [question('userId'), question('stamp')];
})
```

From there, you can use that index with a `between` to accomplish what you need:

```
r.table('questions').between([user_id, r.minval], [user_id, r.maxval], {index: 'userIdAndStamp'}).orderBy({index: r.desc('userIdAndStamp')}).slice(0, 30)`
```

Apologies, this is JS-ReQL syntax and will need to be converted into whatever language you are using (python?)

**Comment by bloodknight2010** [comment] 2017-08-02 03:56
Thanks for your replied. I use the python. I will try it with your reference codes.
