### ISSUE TITLE
Admin console stuck on "Loading..." for Google Chrome Canary

### ISSUE THREAD

**Issue by aleclarson** [rethinkdb/rethinkdb#6059] opened 2016-08-16 19:41 UTC
Macbook Pro - El Capitan v10.11.3
Google Chrome v53.0.2766.0 canary (64-bit)

- Tried refreshing http://localhost:8080
- Tried restarting Google Chrome
- Everything works fine in Safari

**Comment by danielmewes** [comment] 2016-08-16 23:40
Thanks for reporting this @aleclarson . Does this happen every time?

Can you check if there's any error in the developer JavaScript console?

**Comment by aleclarson** [comment] 2016-08-17 01:50
Ack, sorry. I should have pasted that before. It seems to be working now. Not sure what changed. 😐

**Comment by danielmewes** [comment] 2016-08-17 01:53
Ok, thanks for the update. I'm going to close this for now since it doesn't seem reproducible and there's not much to go by (Chrome canary is also inherently unstable). We can re-open the issue if it re-appears.

**Closed by danielmewes** 2016-08-17 01:53 UTC
Labels: cp:web-ui

**Comment by nathan130200** [comment] 2017-09-05 20:26
Too for me in Google Chrome (Canary and Default Version), Internet Explorer, Microsoft Edge, Opera and Firefox, same loading infinite.

**Comment by nathan130200** [comment] 2017-09-05 20:29
See:

![image](https://user-images.githubusercontent.com/14365254/30082018-b54baee8-925f-11e7-9700-db01a0b67495.png)

**Comment by Dawid777** [comment] 2018-09-07 16:55
@nathan130200 Hello! Did you resolve this issue? I can't access google admin console and this is very frustrating for me :/

**Comment by srh** [comment] 2018-09-07 20:07
@Dawid777 This thread isn't about any google admin console -- I think you're looking for something else.
