### ISSUE TITLE
Why can't I get out of waiting for primary state?

### ISSUE THREAD

**Issue by cggaurav** [rethinkdb/rethinkdb#5206] opened 2015-12-14 09:08 UTC
![](http://d.pr/i/GDCW+)

**Comment by cggaurav** [comment] 2015-12-14 09:10
The table reconfigure has started and doesn't finish. Is unsafe rollback the only way I get out of this state?

**Comment by danielmewes** [comment] 2015-12-14 18:45
Thanks for reporting this @cggaurav. This seems to be a duplicate of https://github.com/rethinkdb/rethinkdb/issues/4706 . I'm going to write a reply there with some suggestions shortly.

**Closed by danielmewes** 2015-12-14 18:45 UTC
