### ISSUE TITLE
My all databases got removed automatically, admin console says connected to unknown

### ISSUE THREAD

**Issue by tashbalrai** [rethinkdb/rethinkdb#6074] opened 2016-08-26 08:08 UTC
My local Rethinkdb, stopped working all of sudden. When i start it, it do not show any error message but when i connect to localhost:8080 it shows "Connected to Unknown". Under tables it shows no databases and tables while yesterday i had three databases and more than 10 tables.

Now if i want to add a new database, by clicking on add database button it keeps loading and do not create any database.

I tried to upgrading to the newer version of the db i.e. 2.3.4 from 2.3.3. Even i now setup entire new setup but still it give the same issue.

I also tried to run it with rethinkdb --bind all, then connecting through local IP and still same problem.

I am on windows 8 and downloaded the official package from official website.

Please help.

**Comment by danielmewes** [comment] 2016-08-26 20:14
The good news is that it's extremely unlikely that all of your databases just disappeared.

The "Connected to Uknown" suggests though that the web UI has issues retrieving information from the database server, which is probably also why it doesn't list any databases or tables (since it's still trying to retrieve the database list). Are you able to run any queries in the Data Explorer or with a client driver?
Does `r.dbList()` give you a list of databases?

What are the last few lines of the RethinkDB log_file (in the data directory)?

**Comment by danielmewes** [comment] 2016-08-26 20:16
Oh maybe it's this: There's some problem which we still have to resolve when accessing the web UI through Microsoft Edge that has the same effect as what you describe. Can you try opening it with Internet Explorer or another browser?

**Comment by danielmewes** [comment] 2016-09-14 19:02
I'm not sure if Edge is available on Windows 8, but in any case we don't have enough information here to take further steps.

Closing due to missing information, though it might be a duplicate of of https://github.com/rethinkdb/rethinkdb/issues/5878

**Closed by danielmewes** 2016-09-14 19:02 UTC

**Comment by CJC626** [comment] 2017-08-08 16:26
Hello,

I am facing this issue now with the Admin UI.  The DB's still exist and I can access them through the PythonAPI.  It's just the Admin UI shows zero servers and "connected to Unknown".  Was this ever addressed?  This happens both in supported versions of Chrome and Firefox with RethinkDB v2.3.5.  Thanks!

**Comment by marshall007** [comment] 2017-08-08 16:46
@CJC626 the web UI can become unresponsive if the server you're connecting to is under heavy load. Does this happen consistently even when the server is not under load? Have you tried connecting to another server in your cluster to view the web UI?

**Comment by marshall007** [comment] 2017-08-08 16:47
Also, have you tried executing queries in the data explorer while this is happening?

**Comment by CJC626** [comment] 2017-08-08 21:54
@marshall007 Thanks for the reply.  I am using a single node (no cluster) in this case, and there is no activity on the DB at all.  When I try to execute queries in data explorer, the spinner graphic just sits there.

The strange part is, there was no problem with this 2 weeks ago, and I had not worked in RethinkDB at all since then.

**Comment by marshall007** [comment] 2017-08-08 22:31
@CJC626 can you open up the dev tools in your browser and see if there are any errors or failed network requests? I assume you're port forwarding over SSH when connecting to the web UI?

**Comment by CJC626** [comment] 2017-08-09 16:40
@marshall007 I'm not doing any port forwarding or any other configuration beyond a 'quickstart'.  I'm simply running the rethinkdb executable that starts the server with the default ports and going to localhost:8080.  

There are a few browser errors in the console of Developer Tools on Chrome:

`
localhost/:1 Uncaught SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at r.t._data (cluster-min.js:1799)
    at XMLHttpRequest.<anonymous> (cluster-min.js:1799)
localhost/:1 Uncaught SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at r.t._data (cluster-min.js:1799)
    at XMLHttpRequest.<anonymous> (cluster-min.js:1799)
localhost/:1 Uncaught SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at r.t._data (cluster-min.js:1799)
    at XMLHttpRequest.<anonymous> (cluster-min.js:1799)
localhost/:1 Uncaught SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at r.t._data (cluster-min.js:1799)
    at XMLHttpRequest.<anonymous> (cluster-min.js:1799)
`

The 'unexpected token' looks like this:

![image](https://user-images.githubusercontent.com/5581089/29132957-ec95415e-7cff-11e7-9f52-bc3d799248c3.png)

**Comment by CJC626** [comment] 2017-08-10 16:41
Update:  The admin UI works fine in IE 11.  I face the issue above in Chrome v60 and Firefox v54 (32-bit).

**Comment by jhartzell** [comment] 2017-08-22 09:45
> Update: The admin UI works fine in IE 11. I face the issue above in Chrome v60 and Firefox v54 (32-bit).

Same result here, IE works fine, Chrome Version 60.0.3112.90 (Official Build) (64-bit) all wacky and broken.

**Comment by chrisvariety** [comment] 2017-08-22 14:09
May be a windows thing? Admin UI works fine for me on Mac OS X in Chrome 60.0.3112.90.

**Comment by bchavez** [comment] 2017-08-22 15:55
JSON parsing error is probably related to: https://github.com/rethinkdb/rethinkdb/issues/6342
