### ISSUE TITLE
It seems that download server is down. So apt won't work. https://download.rethinkdb.com/

### ISSUE THREAD

**Issue by WhitewaterDave** [rethinkdb/rethinkdb#7155] opened 2024-09-26 00:32 UTC
It seems that download server is down. So apt won't work. https://download.rethinkdb.com/

_Originally posted by @dotnetCarpenter in https://github.com/rethinkdb/rethinkdb/issues/7151#issuecomment-2282259582_

The repo data is gone from some of the Ubuntu versions including Noble which is 24.04. Without the repo data, APT will throw an error. The packages are still there to download. The repo data needs to be restored.

**Comment by ohmsl** [comment] 2024-10-14 12:34
@gabor-boros can we have our rethink download server back up pretty please 🙂

**Comment by gabor-boros** [comment] 2024-10-14 12:40
@ohmsl Oh, that's new to me, I didn't see it. Are you on slack or discord?

**Comment by ohmsl** [comment] 2024-10-14 12:42
@gabor-boros discord yes!

Seems it is fully down now, returning a 502

Also seems the paths for Nobel has changed causing the instructions on the website to not work?

**Comment by gabor-boros** [comment] 2024-10-14 12:49
@ohmsl how about clarifying some things real quick on Discord? I couldn't find you in the [rethinkdb server](https://discord.gg/ZvVj38zm), though my handle is `gaborboros`.

**Comment by gabor-boros** [comment] 2024-10-14 13:09
The download server is back online. Most probably, it was killed by OOM. Java memory consumption for the win... cc: @WhitewaterDave

**Comment by gabor-boros** [comment] 2024-10-14 13:50
Metadata got rebuilt as well, though some error still happens.

**Comment by WhitewaterDave** [comment] 2024-10-15 06:37
> The download server is back online. Most probably, it was killed by OOM. Java memory consumption for the win... cc: @WhitewaterDave

Thanks. I had no issues installing it on Debian Linux.

I'm not going to close this because others may experience errors. If you see a reason to close it, go ahead and do so.

**Comment by gabor-boros** [comment] 2024-10-15 12:35
Ah, that's great to hear that even metadata issues are resolved. Yesterday, from the docker container I was using, I couldn't install rethinkdb, but either time was needed or I made a human error.

**Comment by ohmsl** [comment] 2024-10-15 19:45
Thanks @gabor-boros, especially for the quick response 🫡

**Comment by yosifkit** [comment] 2024-11-12 18:27
@gabor-boros, it looks like it is down again (https://github.com/rethinkdb/rethinkdb/issues/7157) and we are getting a 502 trying to rebuild the `rethinkdb:2.4.4-bookworm-slim` image after our regular Debian update.

From GitHub actions build logs (https://github.com/docker-library/meta/actions/runs/11801903698/job/32876318126):
```console
#13 [3/5] RUN apt-get -qqy update 	&& apt-get install -y rethinkdb=2.4.4~0bookworm 	&& rm -rf /var/lib/apt/lists/*
#13 7.725 W: Failed to fetch https://download.rethinkdb.com/repository/debian-bookworm/dists/bookworm/InRelease  502  Bad Gateway [IP: 167.172.11.96 443]
#13 7.725 W: Some index files failed to download. They have been ignored, or old ones used instead.
#13 7.732 Reading package lists...
#13 8.205 Building dependency tree...
#13 8.335 Reading state information...
#13 8.342 E: Unable to locate package rethinkdb
#13 ERROR: process "/bin/sh -c apt-get -qqy update \t&& apt-get install -y rethinkdb=$RETHINKDB_PACKAGE_VERSION \t&& rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
```

**Comment by gabor-boros** [comment] 2024-11-12 19:42
Hey @yosifkit,
thanks for letting me know. I'll take a look at it in the morning.

**Comment by gabor-boros** [comment] 2024-11-13 05:47
The download server is up and running again! Closing this issue as I fixed the root cause as well.

**Closed by gabor-boros** 2024-11-13 05:47 UTC
