### ISSUE TITLE
StackOverflow user reporting changefeed bug after long idle period

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#4572] opened 2015-07-24 00:57 UTC
http://stackoverflow.com/questions/31595593/rethinkdb-changefeeds-lost-connection

We should look into this and see if we can reproduce it.

**Comment by freedombird9** [comment] 2015-07-24 06:09
I encountered the above problem. I'm running Ubuntu 14.04 LTS on Google Compute Engine. The network setting should be the default settings on the compute engine. I've encountered the issue twice, but I'm not sure if it is reproducible since I haven't tried to do so.

**Comment by freedombird9** [comment] 2015-07-24 23:19
I've reproduced the issue today. My rethinkdb just lay idle (no change is made to the database table) for about half an hour, and then it cannot get any change feeds. But after restarting the program, the problem was gone. So I have to do something like:

while True:
        conn = get_rdb_connection()
        feed = rdb.table('skydata').changes(squash=False).run(conn)
        while True:
            try:
                change = feed.next(wait=300) # 5 minutes timeout
            except RqlTimeoutError:
                feed.close()
                conn.close(noreply_wait=False)
                logger.warn("connection may not be alive, reconnecting...")
                del conn
                del feed
                break

to keep the connection "alive"

**Comment by danielmewes** [comment] 2015-07-24 23:27
@mlucy I was wondering if maybe we should re-enable some very slow polling (i.e. batch timeout) for open changefeed cursors to avoid this? That would have the advantage of being a pure server-side change that doesn't require changes in the drivers.

**Comment by freedombird9** [comment] 2015-07-24 23:33
Also in the documentation, the exception thrown by next(wait=secs) is documented as 'RqlDriverError', but actually it is "RqlTimeoutError". ref: http://rethinkdb.com/api/python/next/  @danielmewes Please take a look. Thanks.

**Comment by mlucy** [comment] 2015-07-24 23:43
@freedombird9 -- we talked about this a bit internally.  Theoretically TCP should prevent this from happening, but apparently we've had experiences in the past where that doesn't happen for whatever reason.  The solution is probably to add explicit keepalive messages to the driver protocol.

@danielmewes -- We could do that but I think it would be better to add explicit keepalive messages.  That would also solve problems like "I opened this connection, waited an hour and then ran a query on it." or "I ran this really long analytics query that took more than an hour to return".

**Comment by freedombird9** [comment] 2015-07-24 23:51
@mlucy Thank you for your help. I hope it will be solved soon. Right now I can just manually renew the connection.

**Comment by danielmewes** [comment] 2015-07-31 00:33
I can reproduce this behavior btw. if I use `iptables` to stop all further communication on a given RethinkDB connection. Rethinkdbdash doesn't raise an error, and the changefeed simply sits there without receiving any updates.
Not entirely sure yet what the best way is to detect this.

**Comment by mlucy** [comment] 2015-07-31 00:44
@danielmewes -- what's the scope of this issue do you think?  Should we just add occasional messages from the server to the client to keep the TCP session alive, or should the client also produce an error if it doesn't get one of these messages for long enough?

**Comment by danielmewes** [comment] 2015-07-31 00:48
@mlucy I'm still trying to figure that out. I wonder if it's enough to enable TCP keepalive on the client.

**Comment by mlucy** [comment] 2015-08-04 05:00
@danielmewes -- any updates from your testing?

**Comment by danielmewes** [comment] 2015-08-04 19:02
My first results have been inconclusive. We already enable TCP keepalive for client connections on the server. I also turned it on in rethinkdbdash.
However it still took the driver a very long time (in the range of an hour) before it detected the loss of the connection. There might be some parameters that we can tune to make it react more quickly.

**Comment by danielmewes** [comment] 2015-08-04 19:06
I'm also not sure if enabling TCP keepalive will stop routers from dropping the connection prematurely, given that the server already enables keepalive. That being said I don't understand enough of the details of TCP keepalive to make a good prediction on its effects on a router.

**Comment by danielmewes** [comment] 2015-08-07 00:05
I took a better measurement and with TCP keepalive enabled in the client it takes about 11 minutes with the default settings on Linux until a dead connection is noticed by the driver.
This isn't great, but certainly better than nothing.

The timeout can be reduced by tuning kernel parameters:
`/proc/sys/net/ipv4/tcp_keepalive_time`: The time of inactivity until the first keepalive probe is sent in milliseconds (default: 7200 = 7.2s)
`/proc/sys/net/ipv4/tcp_keepalive_intvl`: The interval at which subsequent keepalive probes are sent in seconds (default: 9s)
`/proc/sys/net/ipv4/tcp_keepalive_probes`: The number of missing probes after which the connection is considered dead (default: 75)

So by default it takes 7.5s + 74 * 9s = 673.5 seconds or a bit over 11 minutes.

By setting `tcp_keepalive_intvl` to 1s and `tcp_keepalive_probes` to 10 for example, this time can be reduced to 7.5s + 9 * 1s = 16.5 seconds.

**Comment by danielmewes** [comment] 2015-08-07 00:10
Opened a PR with rethinkdbdash for enabling TCP keepalive: https://github.com/neumino/rethinkdbdash/pull/125

**Comment by danielmewes** [comment] 2015-08-07 00:19
http://stackoverflow.com/a/14855726/2413884 has an overview of how to set the available options from Python on Linux and OS X, and it also has a link to Windows' documentation on the topic. 

It looks like we could tune the timeout parameters on Python, though it wouldn't be portable (i.e. we would need different code for different platforms).
I couldn't find a way to set these options in Node.js except for the initialDelay, but that doesn't help much.

**Comment by danielmewes** [comment] 2015-08-07 00:26
Going to just turn this on with the defaults in our drivers which should work on all major platforms.

In the long term, we can either implement our own protocol-level heartbeat, or add code to set the TCP keepalive parameters on a per-platform basis. For node.js there might be a way of doing it with https://www.npmjs.com/package/raw-socket .

**Comment by danielmewes** [comment] 2015-08-07 00:53
In CR 3128

**Comment by danielmewes** [comment] 2015-08-07 01:16
TCP keepalive will be enabled by our official drivers starting with RethinkDB 2.1.0.
Merged into `next` ceabacfb4c4be100675d7b4fba516d279627a4ab

**Comment by danielmewes** [comment] 2015-08-07 01:19
Created a follow-up issue https://github.com/rethinkdb/rethinkdb/issues/4641 . Closing this one.

**Closed by danielmewes** 2015-08-07 01:19 UTC
Labels: tp:bug

**Comment by danielmewes** [comment] 2015-08-07 21:13
Actually http://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/ says that the unit of `/proc/sys/net/ipv4/tcp_keepalive_time` is seconds and not milliseconds. This would explain why they picked a default of 7200, which is 2 hours.
However it doesn't explain why I'm actually getting the timeout after 11-12 minutes.

**Comment by v3ss0n** [comment] 2015-08-08 16:27
ACKs are blocking? May be a wireshark capture will reveal.
