### ISSUE TITLE
Import from Command Line "freezing up"

### ISSUE THREAD

**Issue by x10ba** [rethinkdb/rethinkdb#3458] opened 2014-12-18 15:46 UTC
Sys stuff: node, MAC, rethinkDB driver
importing JSON file of ~300K documents

I used the following:
$ rethinkdb import -f file.json --table db.file

and, the following is occurring in BASH (is stuck on this):
no primary key specified, using default primary key when creating table
[                                                              ]  0%

while, the following is occurring in rethinkDB (WebUI, stuck here):
r.db.table('file').count()
// returns 1035 and nothing else

When I 'kill' the Import via command line I get the following response:
0 rows imported in 1 table
Interrupted

I figure the import has found something at document 1036 that it doesn't like (and isn't erroring out), but it appears that the import does not occur 'serially' so I can't find the issue via text editor. The Log is not helpful either.

additionally, as a point of perspective, I've imported over 4Million documents without issue up until this point.

Any thoughts?

**Comment by danielmewes** [comment] 2015-02-23 22:51
@x10ba I know it has been a while. Any news on the NDA? Can you still reproduce the freeze after installing the latest version of the Python driver?

**Comment by x10ba** [comment] 2015-02-24 02:06
Hi Daniel,
I had forgotten about the NDA since I never heard back from legal-- typical
;)

I'll test with the Python upgrade and get back to you in a few days.

Thanks for following up-- love the product

X10ba

**Comment by danielmewes** [comment] 2015-03-26 22:33
@x10ba any updates?

**Comment by x10ba** [comment] 2015-03-27 00:41
Hi Daniel,
It was a UTF8 issue derived from source-- which, in this instance was oracle. We resolved issue at source and now import to rDB is fully functional. 
I can test with UTF8 errors if that would help to resolve.

Thanks

X10BA

**Comment by danielmewes** [comment] 2015-03-27 00:45
@x10ba Thanks for the update! Happy to hear it's now working.
If it's no trouble for you, it would be interesting for us to know the sort of encoding that causes the issue so we can test for it. If it's effort for you to get that data back don't worry though.

**Comment by x10ba** [comment] 2015-03-27 01:12
Hi
We isolated to Brazil, Poland and Japan, but affected any special or accented char. 
For example, oracle was writing São Paulo as S😞o Paulo to the tables-- we inherited the oracle db so it took a bit to figure out. I'd normally script the fix, but at scale better to setup source correctly, and tested import to rDB without error.

On phone so smiley face is placeholder for the blocked symbol and my grammar is suspect.

Does that help?
X10BA

**Comment by danielmewes** [comment] 2015-03-27 20:31
Thanks @x10ba. It would be easier if we had the actual character encoding, but don't worry.

@Tryneus: I think we should do a little bit of testing how `rethinkdb import` reacts to illegal UTF-8 encodings.

**Comment by Tryneus** [comment] 2015-03-28 00:25
@danielmewes, this is what happens in `next` and `v2.0.x` (and probably `v1.16.x`):

```
> rethinkdb import -f test.json --table test.test
[                                        ]   0%
0 rows imported in 1 table
'utf8' codec can't decode byte 0xc3 in position 0: invalid continuation byte
In file: ~/rethinkdb/drivers/python/test.json
Errors occurred during import
```

**Comment by danielmewes** [comment] 2015-03-28 00:36
Ok that looks good enough.

Let's close the issue. We can re-open if anyone finds a byte sequence that causes a hang.

**Closed by danielmewes** 2015-03-28 00:36 UTC
Labels: tp:bug

**Comment by AtnNn** [comment] 2015-03-28 00:38
I remmeber at least two other users who ran into this issue in 1.16. Both were import non-ascii unicode data. One user claimed to have fixed this issue by removing duplicate keys in the data. I was never able to reproduce it myself.

**Comment by danielmewes** [comment] 2015-03-28 00:40
Wonder if it could be depending on the Python version...

**Comment by ravi** [comment] 2015-04-24 14:30
I have a similar issue. Trying to upgrade my server from 1.11.x to 2.0.0-1. Did the export from the 1.11.x server using the 2.0.0-1 binary. Maybe that was wrong but it seems to have worked! When I try to run the import to 2.0.0-1 (using the 2.0.0-1 binary) it proceeds to 2% but hangs at that point, for hours (10+ hours in my last run). The DB and tables are created but no data is imported. My DB has three tables, only one of which has records, about ~60k. The total size of data is in the order of tens of MBs.

Command:

````
./bin/rethinkdb import -c 127.0.0.1:28016 -a ...... --format json -d /tmp/collectiondb
````

I just tried again using `--clients 1` and that seems to make things worse: it now hangs at 0% though once again the DB and tables seem to be created.

**Comment by danielmewes** [comment] 2015-04-24 20:51
@ravi a few questions: when you say
> Did the export from the 1.11.x server using the 2.0.0-1 binary

do you mean that you ran `rethinkdb export` after updating the server binary to 2.0? I think that shouldn't matter, since the `rethinkdb` binary is really just a thing wrapper around the underlying `rethinkdb-export` Python script.

After you had exported the data, did you update the RethinkDB Python driver?
The actual import logic comes with the Python driver, so you might have to update that before importing into the new server:
`$ sudo pip install --upgrade rethinkdb`

Let me know if that works.

**Comment by ravi** [comment] 2015-04-24 21:02
@danielmewes Thank you for the response. Yes on the first: I ran rethinkdb after updating the server binary to 2.0. You know this stuff infinitely better than me but I am puzzled to learn that the `rethinkdb` binary, which is the same one used to run the actual server, is a thin wrapper. I am guessing I have misunderstood your message possibly.

One important point missing from my earlier message: my older version of RethinkDB (1.11.x) was installed using `apt-get` while the new one (2.0.0-1) was built by me from source.

Regarding the second, I did not explicitly update the driver, so I am guessing it must be the old driver. If I were to upgrade the driver as suggested, will my earlier (1.11.x) DB be impacted? I cannot, unfortunately, afford that.

**Comment by danielmewes** [comment] 2015-04-24 22:39
@ravi It's a thin wrapper as far as the export functionality is concerned. The actual server is of course in the binary.

We'd like to change that in the future to make scenarios like this one easier, but for now the actual export script is a part of the Python driver and not the core server.

Updating your system-wide driver would indeed interfere with accessing your 1.11 DB, assuming you are using the Python driver for that. Even if you don't, it would make it very tricky to do a new export from your 1.11 DB later.

Here's a work-around to use the 2.0 export script and driver directly without installing it system-wide.
I assume that you are in the RethinkDB source directory.
```bash
rethinkdb$ cd drivers/python
rethinkdb/drivers/python$ make
    [1/3] CP ../../build/drivers/python/rethinkdb/
    [2/3] CONVERT_PROTOFILE ../../build/drivers/python/rethinkdb/ql2_pb2.py
    [3/3] CONVERT_PROTOFILE ../../drivers/python/rethinkdb/ql2_pb2.py
rethinkdb/drivers/python$ cp rethinkdb/_import.py rethinkdb/_backup.py ./
rethinkdb/drivers/python$ nano _import.py
     ... look for the line "from ._backup import *" and replace it by "from _backup import *" ...
     ... save the file and exit (of course you can use another editor) ...
rethinkdb/drivers/python$ python _import.py -c 127.0.0.1:28016 -a ...... --format json -d /tmp/collectiondb
     ... should now run the import script with the latest driver...
```
Once you are done, you can delete the `_import.py` and `_backup.py` files in `rethinkdb/drivers/python`
