### ISSUE TITLE
Very slow reads from table while writing

### ISSUE THREAD

**Issue by apa512** [rethinkdb/rethinkdb#3787] opened 2015-02-16 20:56 UTC
I'm having problems with a table being basically useless for reads while doing relatively moderate writes.

Without any writes a get operation returns in about 200 ms. When doing ~50-60 inserts a second I get results like these for the same operation:
```js
{
  "description":  "Perform read." ,
  "duration(ms)": 24411.997251 ,
  "sub_tasks": [
  {
    "parallel_tasks": [
    [{
       "description":  "Perform read on shard." ,
       "duration(ms)": 24410.180832 ,
...
```

- The inserted documents have about 20-25 fields with mostly strings of a sentence or two and I'm using soft durability, update on conflict and no batching (one insert per query).

- The machine has 64GB memory and a SSD disk and is configured with 512 io-threads and memory set to 40000 (I've also tried 64 and 128 io-threads and letting RethinkDB allocate memory on its own but with similar results).

- The table has 110 million records

Anything that stands out?

In general, RethinkDB isn't giving me the performance I would like so what's the next step if I can't change to a bigger machine? Would it help if I got more machines and set them up as replicas or shards?

**Comment by danielmewes** [comment] 2015-02-16 21:16
Hi @apa512. That's indeed very very slow. Thank you for opening an issue.

We're currently investigating a possibly related case where writes are heavily prioritized over reads, slowing reads down over-proportionally. However that's only when using much larger batched inserts so I'm not sure if this is the same problem.

Can I ask you a few additional questions?
- Which operating system are you using?
- Which version of RethinkDB is this with?
- You say that a normal get without writes takes 200ms. This already seems incredibly high. What is the exact read query you are running? Is is just a `r.table(...).get(id)` or something more complicated?
- How much CPU usage and disk I/O is RethinkDB causing while running a) only the read and b) the read together with the writes?
- Is there a chance you can send us your data and queries so we can try to debug this issue locally? We can sign an NDA if the data is sensitive.

I think there's something wrong here that updating to a bigger machine likely wouldn't solve. Judging from the amount of memory your machine is already pretty big?

**Comment by apa512** [comment] 2015-02-16 22:14
Sure. Thanks for looking into this issue.

- Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-24-generic x86_64)
- rethinkdb 1.15.3~0trusty (GCC 4.8.2)
- It's just a simple get(id)
- With writes: ~400 % CPU and ~70 % according to top. Read/Write about 12 M/s according to iotop.
  Stopping the writes lowered CPU to about half but memory didn't change and IO actually increased a little bit). 
- I will get back to you about the dump.

One thing that I forgot to mention is that the primary keys are two element arrays. Perhaps that's not ideal? I also have quite a few secondary indexes (32 in total and one is defined by a simple function that uses the primary key).

Is it possible that RethinkDB gets overwhelmed by updating all the indexes?

**Comment by danielmewes** [comment] 2015-02-16 22:39
Thanks for the data. The 32 secondary indexes can definitely have a significant impact on performance under writes.
I don't think having a two-element array as the primary should cause any issues though.

I think we should first try to find out why the gets without any writes are so slow. How are you running the gets? Are many of them running at the same time? How many gets are you doing in total per second?

If you have no other load on the server, and just run a single `get`, how long does that take?
(a note on measuring the latency of the read: If you're using the Data Explorer it might be slow to transfer and format the result. I recommend looking at the "server time" field in the profiler result instead of the total execution time).

**Comment by apa512** [comment] 2015-02-16 23:06
200 ms was including round-trip time. Server time for a read with nothing else going on is just a few ms.

**Comment by danielmewes** [comment] 2015-02-17 01:38
Ok that makes sense and sounds about right.

Here are two small things that might be worth trying in case this is actually bottle-necked in the UI subsystem:
- *reduce* the io pool size. Maybe to 4 or 8 threads. While this will reduce overall i/o throughput, it might also reduce i/o latency.
- run the server with the `--no-direct-io` option

I think it's more likely that the problem lies somewhere else, but it might be worth a try.

If you can give us a data dump that would be ideal. Then we could try to reproduce this locally and could debug the issue more effectively. Please let me know if this is possible. I can send you upload instructions for a secure upload server.

**Comment by apa512** [comment] 2015-02-17 17:14
@danielmewes I sent an email regarding the dump to the address listed on your website.

**Comment by danielmewes** [comment] 2015-02-19 02:52
@apa512 , thank you for providing the data. I'm still downloading it, but we just had a roughly comparable case and it turns out that the problem there was that reads have to queue up behind writes. So if you have lots of secondary indexes and do certain types of inserts (especially batched inserts) the reads might get blocked for an relatively long time waiting for all the writes to finish up.

The idea behind this blocking is to guarantee ordering between reads and writes, specifically that each read always sees the effect of any previous write. This is unnecessarily strict in its current implementation however, and we're working on a fix for that which will hopefully ship with RethinkDB 2.0 in a few weeks.

So far the speculative part. I yet have to actually verify that on your data. Will update you shortly once I have done some testing.

**Comment by v3ss0n** [comment] 2015-02-19 12:51
Interesting Issue, anything new on this?

**Comment by danielmewes** [comment] 2015-02-19 20:31
@v3ss0n Not since my comment from 18 hours ago, but working on it.

**Comment by realfilip** [comment] 2015-02-27 18:40
Hi, I'm @coffeemug. Talking to the user at StarBucks. Pinging myself.

**Comment by danielmewes** [comment] 2015-02-27 18:49
Hi @coffeemug @realfilip . I'm currently testing the patch on the data set. It just takes some time to setup because it's a pretty large data set...

**Comment by coffeemug** [comment] 2015-02-27 20:07
Ok, on my own computer now.

How is `useOutdated` implemented (with respect to this issue)? Does it bypass the write lock? Is that possible to do? For @realfilip's use case, it would be perfectly acceptable to set `useOutdated` to `true`, but I'm not sure if it actually bypasses the locks on a single machine use case.

**Comment by danielmewes** [comment] 2015-02-27 20:14
It only bypasses some of the locks. I don't think it would fully solve the problem.

**Comment by danielmewes** [comment] 2015-02-28 02:38
Actually thinking about it, using outdated reads might be a useful work-around in this specific case, since you are only doing point inserts (no batch inserts).
@realfilip @apa512 it might be worth a try specifying the `useOutdated: true` optarg on `table` in the read queries (http://rethinkdb.com/api/javascript/table/).

(I still didn't get to the point where I could check whether our fix works for your case. It's currently constructing secondary indexes, which will probably take about another hour. Will update you once I could run the tests.)

**Comment by danielmewes** [comment] 2015-03-03 02:22
@apa512 Was the `profiles` table sharded? Was it replicating across multiple servers by any chance? (I cannot reproduce the issue on a single server at the moment, but I might not be giving it enough load?)

**Comment by apa512** [comment] 2015-03-03 12:31
Nope, neither sharded nor replicated. I do have two servers but the profiles table only interacts with one of them, unless I'm missing something:
![2015-03-03-132403_987x647_scrot](https://cloud.githubusercontent.com/assets/319058/6462420/5a0eb900-c1a9-11e4-8991-318885d0912b.png)


40 writes per second seem to work fine, but 50 or more and reads start getting slower and slower.

**Comment by danielmewes** [comment] 2015-03-03 19:04
@apa512 Thanks for the info. I'll fiddle a bit with the write load to see if I can get this.

Have you had a chance yet to try `useOutdated` reads?

**Comment by apa512** [comment] 2015-03-12 01:32
Sorry for the delay @danielmewes. We're currently working around this issue by using an intermediate storage and then batch insert, but I try to make the table slow again and see if ```useOutdated``` helps.

**Comment by danielmewes** [comment] 2015-03-26 22:42
Haven't been able to reproduce this locally. My suspicion is that it depends on the characteristics of the i/o system and possibly the exact write queries.
My best guess at the moment is that it was caused by https://github.com/rethinkdb/rethinkdb/issues/1606 , but that's difficult to say for sure without testing it.

@apa512 As long as you're just testing RethinkDB on non-production data at the moment, I recommed giving the 2.0 release candidate a shot. You can download it at https://github.com/rethinkdb/rethinkdb/releases/tag/v2.0.0-0RC1
The RC includes a fix for #1606, so if that was the issue here there's a good chance that it will solve it.

**Comment by danielmewes** [comment] 2015-04-16 22:27
@apa512 We have released RethinkDB 2.0 which comes with some optimizations that might be relevant for this. Any chance you could re-try with 2.0?

**Comment by danielmewes** [comment] 2015-08-06 02:07
@apa512 Any update on this? Have you had a chance to retry with RethinkDB 2.0?

**Comment by danielmewes** [comment] 2015-10-05 21:35
Closing since we haven't been able to reproduce this and are not sure if the issue still persists with more recent versions of RethinkDB.
However please re-open @apa512 if you still run into this when you disable your work-around.

**Closed by danielmewes** 2015-10-05 21:35 UTC
Labels: tp:performance
