### ISSUE TITLE
Failed to compile on alpine s390x

### ISSUE THREAD

**Issue by levivic** [rethinkdb/rethinkdb#6479] opened 2017-09-01 18:43 UTC
Trying to build rethinkdb from source on alpine on s390x. Got following error about undefined reference `backtrace`

```
    [1/2] BUILD v8_3.28-s390
    [2/2] LD build/release/rethinkdb
/usr/lib/gcc/s390x-alpine-linux-musl/6.3.0/../../../../s390x-alpine-linux-musl/bin/ld: warning: libssl.so.43, needed by /usr/lib/gcc/s390x-alpine-linux-musl/6.3.0/../../../../lib/libcurl.so, may conflict with libssl.so.1.0.0
/usr/lib/gcc/s390x-alpine-linux-musl/6.3.0/../../../../s390x-alpine-linux-musl/bin/ld: warning: libcrypto.so.41, needed by /usr/lib/gcc/s390x-alpine-linux-musl/6.3.0/../../../../lib/libcurl.so, may conflict with libcrypto.so.1.0.0
./build/release/obj/backtrace.o: In function `backtrace_frame_t::initialize_symbols()':
/root/rethinkdb/src/backtrace.cc:276: undefined reference to `backtrace_symbols'
./build/release/obj/rethinkdb_backtrace.o: In function `rethinkdb_backtrace(void**, int)':
/root/rethinkdb/src/rethinkdb_backtrace.cc:108: undefined reference to `backtrace'
collect2: error: ld returned 1 exit status
make[1]: *** [src/build.mk:335: build/release/rethinkdb] Error 1
make: *** [Makefile:53: make] Error 2
```

Any ideas?

**Comment by mundaym** [comment] 2017-09-06 01:08
Looks like musl libc isn't currently supported, see #6337 for example, so this will be fun :)

`backtrace_symbols` is a GNU extension that glibc implements but musl libc does not. It looks like there is a third party library, libexecinfo, that might do the trick. It looks like it might be available on alpine on s390x: https://pkgs.alpinelinux.org/package/edge/main/s390x/libexecinfo.

**Comment by levivic** [comment] 2017-09-08 14:42
@mundaym yes, the problem resides in the libexecinfo. This package was not probably ported to Alpine/s390x.

**Comment by gabor-boros** [comment] 2021-09-10 06:20
Duplicate of #6441

(If we build for s390x both issues must be fixed so one of the issues is not needed)

**Closed by gabor-boros** 2021-09-10 06:20 UTC
