### ISSUE TITLE
How to make a case insensitive and accent insensitive query?

### ISSUE THREAD

**Issue by Agamennon** [rethinkdb/rethinkdb#4856] opened 2015-09-17 23:41 UTC
As per the title how do i perform this query?  `.eq()`  does not seem to have any other option then exact. `match` has regular expression, that could do this:
```javascript
r.table('users').filter(function(doc){
    return doc('name').match("(?i)john")
}).run(conn, callback)
``` 
but that still will differentiate between `á` and `a` , so how to make a query that is case insensitive and also accent insensitive?

**Comment by coffeemug** [comment] 2015-09-17 23:45
An easy way to make a case insensitive query is do `doc('name').downcase().eq('foo')`. I'm not sure about the accents -- can someone who understands this chime in? (@mlucy?)

**Comment by mlucy** [comment] 2015-09-17 23:47
We don't currently have a good way to remove accents.  The best you could do is call `split` on the string, map over the characters and transform them, then use `reduce` to concatenate them back together into a single string.

**Comment by Agamennon** [comment] 2015-09-17 23:56
@mlucy that's unfortunate, it's too much hassle, rethinkdb should have ways to deal with this, perhaps a collation option in the future or something similar?

**Comment by danielmewes** [comment] 2015-09-18 00:00
@Agamennon Yeah, we will introduce collation-aware comparison operators with https://github.com/rethinkdb/rethinkdb/issues/2040 , but that's probably a few releases away.
There might be a way to get this functionality through a JavaScript function and `r.js`, though it might be a bit slow.

**Comment by danielmewes** [comment] 2015-09-18 00:02
I'm going to close this as a duplicate of #2040, but please feel free to ask any further questions here.

**Closed by danielmewes** 2015-09-18 00:02 UTC

**Comment by codermapuche** [comment] 2016-05-05 23:55
Hi, this is not the best solution but works.
You can use this function over the input value:

```
caseAndAccentInsensitive = (function () {
	
  const accentMap = (function(letters) {
	  
    let map = {};
	
	while(letters.length>0) {
		
	  let letter = "[" + letters.shift() + "]",
	      chars = letter.split('');
		  
	  while(chars.length>0) {
	    map[chars.shift()] = letter;
	  }
	  
	}
	
	return map;
	
  })([
    'aàáâãäå', // a
    'cç',      // c
    'eèéêë',   // e
    'iìíîï',   // i
    'nñ',      // n
    'oòóôõöø', // o
    'sß',      // s
    'uùúûü',   // u
    'yÿ'       // y
  ]);

  return function (text) {
    var textFold = '';

    if (!text)
      return textFold;

    text = text.toLowerCase();

    for (var idx = 0; idx < text.length; idx++) {
	  let charAt = text.charAt(idx);
	  
      textFold += accentMap[charAt] || charAt;	  
	}

    return "(?i)" + textFold;
  }

})();
```
Easy to extend, you can add any other case to array inside of a function.

Example: 

```
r.table('users').filter(function(doc){
    return doc('name').match(caseAndAccentInsensitive("john"))
}).run(conn, callback);

caseAndAccentInsensitive("hello") == caseAndAccentInsensitive("helló") == "(?i)h[eèéêë]ll[oòóôõöø]"
```
