### ISSUE TITLE
Alternatives to NOT IN / filtering with contains().not()

### ISSUE THREAD

**Issue by isaldarriaga** [rethinkdb/rethinkdb#5779] opened 2016-05-19 01:51 UTC
Is there a known mechanism to specify the index into a lambda of a filter function? or can this type of query be map reduced / concatMap in some way?

queries specially the count() are taking 40 minutes to compute in my database. I want to prevent Full table scans as much as possible, but the filter function doesn't seem to allow this kind of optimization. 

as you know getAll() can accept the index hint but it's the opposite to what i really want (a NOT IN)

example: 
r.db('my_db').table('left_table')
   .filter(function (left) {
        return r.db('other_db').table('right_table')
                     .hasFields('fk')
                      .getField('fk')
                      .contains(left('pk')).not()
})

tks.

**Comment by danielmewes** [comment] 2016-05-19 02:04
You can try the following:
1. Create a multi-index on the `fk` field of `right_tabl`:
```js

**Comment by danielmewes** [comment] 2016-05-19 02:15
(I accidentally pressed enter on an incomplete response with an idea that ended up not working out.)

Do I understand correctly that you want to find documents in the left table for which there is *at least* one document in the right table that doesn't contain the left document's `id` in its `fk` field?

Or do you want to find documents in the left table for which there is *no* document in the right table that contains the left document's `id` in its `fk` field?

The first one is hard to optimize as far as I can tell, but the second one can be made to use an index.

**Comment by isaldarriaga** [comment] 2016-05-19 16:32
I want to find documents in the left table for which there is no document in the right table that contains the left document's id in its fk field.

how to specify the use of the index? tks.

**Comment by danielmewes** [comment] 2016-05-19 18:25
Ok that is the easier case luckily :-)

You can try the following:
1. Create a multi index on the right table:
```js
r.db('other_db').table('right_table').indexCreate("fk_multi", r.row('fk'), {multi: true})
```
2. Use the following query:
```js
r.db('my_db').table('left_table')
.filter(function (left) {
return r.db('other_db').table('right_table')
.getAll(left('pk'), {index: "fk_multi"}).isEmpty()
})
```

This should be pretty efficient. Let me know if it works.

(I'm going to close the issue because it's not a bug, but feel free to add more comments if the solution doesn't work)

**Closed by danielmewes** 2016-05-19 18:25 UTC

**Comment by jlhawn** [comment] 2016-05-19 18:38
> Or do you want to find documents in the left table for which there is no document in the right table that contains the left document's `id` in its `fk` field?

I have the same concern. Since there's no equivalent of `ON DELETE CASCADE` I have a job that runs regularly which cleans up "orphaned" data from some tables. For example, say I have 3 tables:

- `users`: Fields(name, id, etc.)
- `teams`: Fields(name, id, etc.)
- `team_members`: Fields(team_id, user_id)

The `team_members` table is used to store which users are members of which teams. However, users or teams may be deleted from the database leaving documents in the `team_members` table which have no corresponding team or user. I want a periodic job to run which deletes these "orphaned" rows.

So far, I've only thought of this query (given indexes on the `id` fields):

```javascript
r.db("app").table("team_members").filter(function (membership) {
	return r.or(
		r.db("app").table("users").getAll(membership("user_id"), {index: "id"}).isEmpty(),
		r.db("app").table("teams").getAll(membership("team_id"), {index: "id"}).isEmpty()
	)
}).delete()
```

This still requires a linear scan of the `team_members` table though which is okay, but is this the most efficient that I could hope for?

**Comment by danielmewes** [comment] 2016-05-19 18:53
I can't think of a good way for avoiding the table scan on the left table. I think fully avoiding this would require cross-table transactions so you could stop orphaned data from being possible in the first place. Unfortunately that's a pretty complex feature in a distributed database.

**Comment by jlhawn** [comment] 2016-05-19 18:54
👍  Okay, that's a totally acceptable trade-off in my opinion.

**Comment by isaldarriaga** [comment] 2016-05-19 23:56
it worked very wel!!
thank you danielmewes.
