### ISSUE TITLE
r.geojson atomic?

### ISSUE THREAD

**Issue by donpdonp** [rethinkdb/rethinkdb#3864] opened 2015-03-03 18:10 UTC
calling r.update() with a parameter of r.geojson() throws a nonatomic query error. the query references no other tables. a chat in #rethink irc suggested the floating point operations were the source of concern for the driver and its possible that the query is atomic after all. I'm filing this issue for someone to look into it and possibly lifting the exception thrown here. thanks!

```javascript
Possibly unhandled RqlRuntimeError: Could not prove function deterministic.  Maybe you want to use the non_atomic flag? in:
r.table("fences").get("b660fccc-bd09-4b2d").update({created_at: r.ISO8601("2015-02-26T18:26:33.315Z"), geojson: r.geojson({type: "Feature", properties: {}, geometry: {type: "Polygon", coordinates: [[[-122.64613151550293, 45.516712268974466], [-122.63463020324706, 45.5164717017978], [-122.63454437255858, 45.50805120269171], [-122.6455307006836, 45.50817150440647], [-122.6462173461914, 45.5122014632718], [-122.64862060546875, 45.51214131675321], [-122.6475477218628, 45.51568483978007], [-122.64613151550293, 45.516712268974466]]]}}), id: "b660fccc-bd09-4b2d", name: "Home", user_id: "c0b190d2-ed9c-4346-be43-2084ad041fca"})
```

**Comment by danielmewes** [comment] 2015-03-03 19:27
Hi @donpdonp 
the problem are indeed floating point rounding discrepancies. Different platforms and libcs round certain floating point operations (e.g. sine) slightly differently. Geospatial operations are generally affected by this.
In the case of `r.geojson` the part that might potentially diverge is the validation that it performs. Depending on rounding `r.geojson` might reject a piece of geometry on one server, but accept it on another.

If an update is considered atomic, the update operation will be applied independently on all replicas of the table. Now if some of them have different libraries and/or CPUs, they might update the same document with different data. In that case you end up having divergent data on different replicas, which can lead to inconsistent query results and other weird effects.

The long-term solution to this is https://github.com/rethinkdb/rethinkdb/issues/3009

The work-around for now is to run the update with `{nonAtomic: true}` (see http://rethinkdb.com/api/javascript/update/ for details). This will make sure that the update function with the `r.geojson` term is only evaluated once on a single server, before having its result distributed to the replicas.

**Comment by danielmewes** [comment] 2015-03-03 19:27
(Closing as duplicate of https://github.com/rethinkdb/rethinkdb/issues/3009)

**Closed by danielmewes** 2015-03-03 19:27 UTC
