### ISSUE TITLE
Admin console apparently doesn't work in Firefox (48.0.2 / Windows 7)

### ISSUE THREAD

**Issue by nltesown** [rethinkdb/rethinkdb#6110] opened 2016-09-15 08:31 UTC
After some time without using the console, it stopped working when I tried again recently - and that's apparently related to the fact that Firefox had been updated in the meantime. (I'm also using the latest version of RethinkDB : 2.3.5).

With the default configuration, opening the console in Firefox gives this: no connection (whereas the connection is active with the Node.js client, for instance). At the hint of a Stackoverflow user, I tried in Chrome and it works.

![rethinkdb-admin](https://cloud.githubusercontent.com/assets/2790608/18543174/cc13e9cc-7b2e-11e6-8e16-f359313c69f7.png)

**Comment by danielmewes** [comment] 2016-09-15 18:39
Thanks for reporting this @nltesown . I suspect that it's the same cause as https://github.com/rethinkdb/rethinkdb/issues/5878 . We have a fix for it. Will try to release this quickly!

**Comment by danielmewes** [comment] 2016-09-15 18:39
Closing as duplicate of https://github.com/rethinkdb/rethinkdb/issues/5426

**Closed by danielmewes** 2016-09-15 18:39 UTC

**Comment by danielmewes** [comment] 2016-09-15 21:25
There's a work-around that you can be used until the patch is released: https://github.com/rethinkdb/rethinkdb/issues/5426#issuecomment-247459503
