### ISSUE TITLE
Publish server binary to npm

### ISSUE THREAD

**Issue by sholladay** [rethinkdb/rethinkdb#6294] opened 2017-03-10 15:50 UTC
## Problem

Automated testing for apps that use RethinkDB is harder than it should be. Currently, we have to assume that someone is running the database globally, which is a dependency that cannot be expressed in a package manifest. That leads to confusion, especially for new users, and means that we have to set up CI environments with this prerequisite.

## Solution

The testing process would be significantly easier if we could launch a local database instance as part of the test suite. 

Using [bin](https://docs.npmjs.com/files/package.json#bin) in package.json, you can expose a command line interface to users in a way that can be used either globally or locally. This can rely upon [native code](https://nodejs.org/api/addons.html) or a [`prepublish` / `preinstall`](https://docs.npmjs.com/misc/scripts) script as necessary. I propose exposing the `rethinkdb` CLI there.

If this were to be implemented I would then be able to do something like this in my package.json.

```json
{
  "name": "my-app",
  "scripts": {
    "pretest": "rm -rf rethindb_data && rethinkdb create && rethinkdb serve",
    "test": "xo && ava"
  },
  "dependencies": {
    "rethinkdb": "^2.3.3"
  }
}
```

The key here is that `rethinkdb create` and `rethinkdb serve` above would give preference to the locally installed `rethinkdb` CLI (thanks to npm scripts' [PATH feature](http://www.2ality.com/2016/01/locally-installed-npm-executables.html)). When people run `npm install` on my package, `rethinkdb` would come along with it, rather than needing a separate step.

**Comment by bchavez** [comment] 2017-03-10 17:28
Hi. I have a few questions:

* How is NPM going to determine which binary to run? **Windows**, **Linux**, **MacOS**?
* Further, how will NPM determine which flavor of Linux binary to run? `jessie`, `sasucy`, `xenial`, `yakkety`?
* How does node's [`native code`](https://nodejs.org/api/addons.html) work? Is your idea here to compile RethinkDB sources from NPM?
* Would using RethinkDB's docker image be more appropriate? https://hub.docker.com/_/rethinkdb/
* What might be wrong with adding an additional `scripts`>`installdb` in your `project.json` that would execute the appropriate commands for your particular scenario to get RethinkDB setup locally? (ie: linux:`keystuff && apt-get install rethinkdb` or windows:`powershell wget http://rethinkdb.zip`)

Brian

:crystal_ball: :dolls: ***["Magic and technology. Voodoo dolls and chants. Electricity. Were makin weird science..."](https://www.youtube.com/watch?v=Jm-upHSP9KU)***

**Comment by sholladay** [comment] 2017-03-11 02:18
> How is NPM going to determine which binary to run? Windows, Linux, MacOS?

The preferred route is to use `prepublish` to build a cross-platform binary on the author's machine (whoever is releasing the `rethinkdb` package) and then publish it. This provides the best user experience and install performance. In this case, everyone runs the same executable regardless of their platform.

If that's not possible, and I'm guessing it isn't for RethinkDB, then you use the [native code](https://nodejs.org/api/addons.html) system and npm will compile `rethinkdb` at install time. In this case the user ends up with an appropriately built binary based on their platform. Check out [fullname-native](https://github.com/sindresorhus/fullname-native) for a clean, minimal usage example and [electron](https://github.com/electron/electron) for a much more complicated example.

Note that `fullname-native` isn't a command line tool, but the principles are all the same, just needs some very trivial tweaks (add a `#!/usr/bin/env node` hashbang if the CLI's entrypoint is a `.js` file and point to it from `bin` in package.json).

> Further, how will NPM determine which flavor of Linux binary to run? jessie, sasucy, xenial, yakkety?

See previous answer. Basically, if `rethinkdb` actually needs *nix-version-specific compilation, then that would be handled already by the build process. If it doesn't, there's nothing to do.

> How does node's native code work? Is your idea here to compile RethinkDB sources from NPM?

It is a bridge between JavaScript and C/C++, bringing some very powerful capability to Node by making it easy to import C/C++-based libraries within JS. To be clear, you can ship a command line tool written in any language to the npm registry and npm can install and run it. If RethinkDB were written in Haskell, we could still do what I am suggesting here. The only reason I mentioned the native code system is that it may make things easier to compile.

> Would using RethinkDB's docker image be more appropriate? 

I... dislike docker. _\*ducks for cover\*_

> What might be wrong with adding an additional scripts>installdb in your project.json

That is very problematic, hence this issue. For one, writing such a script is clumsy and error prone, with lots of `try` / `catch` nonsense for different platforms and kinds of package managers. Second, those package managers install globally, I don't want my test suite to affect the rest their machine outside of my project's directory, similar to the concept of "pure" functions in functional programming. Third, having a setup script is not very maintainable as it needs to be duplicated across every project that relies upon `rethinkdb`. Fourth, that puts the concern at the wrong layer, as dependencies should come pre-compiled and should be expressed within a package manifest for all kinds of reasons.

**Comment by bchavez** [comment] 2017-03-11 03:35
For **MacOS** and **Windows** the RethinkDB server package is self-contained  (dmg, zip) and can both run similar to the behavior you're looking for without installing RethinkDB globally. In fact, the RethinkDB C# driver test suite does exactly this by downloading the .zip, extracting `rethinkdb.exe` and running the server on a clean VM. No problems there.

The problem I think is with Linux and dynamic linked libraries in different distributions. Maybe there is a silver bullet for making portable Linux binaries that run everywhere but AFAIK I don't think that is an easy problem to solve. Maybe static linking could help, dunno.

> If that's not possible, and I'm guessing it isn't for RethinkDB, then you use the native code system and npm will compile rethinkdb at install time.

FWIW, it can take almost 30 minutes to an hour just to compile RethinkDB depending on your CPU :muscle:. Install time is not the only issue but external dependencies need to be downloaded and compiled. Additionally, globally `apt-get install`'ed compiler tools are a prerequisite for building from source.

TBH tho... I really don't think it is very practical to compile `rethinkdb` on every npm install.

On a small side thought :thought_balloon: I think the ethos of Node and JavaScript is that JavaScript pretty much runs everywhere using a runtime. And RethinkDB server needs to run natively on the OS without a runtime and goes against that belief. Perhaps something like [`reqlite`](https://github.com/neumino/reqlite) made by the crafty **Michael(neumino)** can help you with what you're looking to do on Node/JavaScript/NPM. See https://github.com/neumino/reqlite.

--
:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=wOjGmpmvGz8#t=2m)***

**Comment by sholladay** [comment] 2017-03-11 04:59
> it can take almost 30 minutes to an hour just to compile RethinkDB

That's rough. Still, I would take it for the ability for my users to simply run `npm install && npm test` without the platform-specific crap. I'd rather answer valid questions about why it takes so long than teach someone why `apt: command not found` is their fault. The number of support issues I get like that is astounding.

> Maybe there is a silver bullet for making portable Linux binaries that run everywhere

Shaun over at [Linuxbrew](http://linuxbrew.sh/) figured out some black magic to do this. If we need it I can ping him for some insight on how the package manager does it.

> globally apt-get install'ed compiler tools are a prerequisite for building from source

Fair. I guess [node-pre-gyp](https://github.com/mapbox/node-pre-gyp/) is a better option in that case and it should solve the other problems as well. You basically point it at a base URL where your prebuilt binaries live and it takes care of the rest.

**Comment by AtnNn** [comment] 2017-03-11 22:43
Building a binary package of the rethinkdb server for npmjs should be possible, but doing so in a portable and sustainable way seems like a maintenance nightmare and a large source of hard to reproduce bug reports.

Are there any other such packages?

For testing, I would recommend mocking out reql calls, perhaps using something like https://github.com/neumino/reqlite

**Comment by sholladay** [comment] 2017-03-12 03:59
> should be possible, but doing so in a portable and sustainable way seems like a maintenance nightmare

I believe we can make it easy with tools the community has already made. Per the above discussion, it seems like the path of least resistance may be [node-pre-gyp](https://github.com/mapbox/node-pre-gyp).

> Are there any other such packages?

Here is a list of implementations using `node-pre-gyp`:
https://www.npmjs.com/browse/depended/node-pre-gyp

I couldn't quickly find _database server_ binaries on npm, there is a huge preference for database drivers in the search results. But I'm sure someone has done it.

There are lots of examples of compiled packages in general. Mainly libraries, but some CLIs. How they go about it varies on their needs.

For example, things like JAR files are easy. Someone put [Selenium directly on npm](https://github.com/sheerun/bundled-selenium) and there are JavaScript wrappers around Selenium, like [grunt-selenium-webdriver](https://github.com/levexis/grunt-selenium-webdriver) which [spawns Selenium](https://github.com/levexis/grunt-selenium-webdriver/blob/master/tasks/selenium_webdriver.js#L151) under the hood.

> For testing, I would recommend mocking out reql calls

This reminds me of people using [phantomjs](http://phantomjs.org/) instead of putting in the effort to spin up real browsers on [BrowserStack](https://www.browserstack.com/). It's worth it, I promise!

**Comment by AtnNn** [comment] 2017-03-12 05:23
I don't think it'll be as easy as you make it seem, but I would love to be proven wrong. I'm willing to help if you or someone else wants to go ahead and do this.

**Comment by oliverjanik** [comment] 2017-03-13 02:59
What's the issue with using your OS package manager or docker? Do you propose a PIP package, or a Nuget package, perhaps a gem? 

NPM and node-gyp is an absolute maintenance nightmare. Please check these threads as evidence:
https://github.com/nodejs/node-gyp/issues/629
https://github.com/npm/npm/issues/2006

Language specific repos are built to support libs for those languages, not to distribute and install random software.

**Comment by sholladay** [comment] 2017-03-13 04:35
> Language specific repos ...

npm has almost zero knowledge of the language of the programs it provides. It does optimize for a specific runtime environment by putting things in `node_modules`, for example, but even this is inconsequential as npm provides commands to get paths, just like any good package manager.

> NPM and node-gyp is an absolute maintenance nightmare

Publishing and maintaining packages on npm is easier than any other ecosystem I am aware of. It is compiled software that is a nightmare. 😄 

The issues you linked to were fixed and closed long ago. I had problems with `node-gyp` in the early days, too, but these all vanished once it became an official thing and folded into the foundation. In the case of the npm issue, I'm not clear on what you think is needed here outside of [pre-gyp](https://github.com/mapbox/node-pre-gyp)

**Comment by oliverjanik** [comment] 2017-03-13 04:44
I heard this one before. No one cares about NPM outside of JS ecosystem. In my experience it barely works for JS let alone anything else, hence the yarn effort, etc.

Have you read the links I posted? https://github.com/npm/npm/issues/2006 is closed as WONTFIX.
The other one clearly states: This issue is fixed (kinda)

You're free to do this yourself of course, but I'd rather people with chops to work on RethinkDB spent their time on core improvements rather than supporting random languages package managers and their quirks.

**Comment by marshall007** [comment] 2017-03-16 01:02
@sholladay my understanding is that `node-gyp` is used for compiling [Node.js Addons](https://nodejs.org/api/addons.html). This is useful when you want interop between JS and C/C++ code, but that is not what you're asking for here. I have never seen it used to compile and publish standalone C/C++ binaries as `npm` packages. If you can point to an example of this being done I'm all ears.

**Comment by sholladay** [comment] 2017-03-16 18:01
> This is useful when you want interop between JS and C/C++ code

Correct, but I don't think RethinkDB would want or need to use the JS side of things. I'm throwing out suggestions to try to keep this as simple as possible to implement and it seems like the fact that `npm` can automatically compile C/C++ on your behalf at install time may be useful here. I could be totally wrong!

> I have never seen it used to compile and publish standalone C/C++ binaries

To my knowledge there is no particular constraint around this. But for convenience, I believe [pre-gyp](https://github.com/mapbox/node-pre-gyp/) would be useful to reduce the boilerplate to a minimum. I think it provides most of what would be needed out of the box. Though I don't have a ton of insight there.

**Comment by srh** [comment] 2017-05-24 16:03
I welcome anybody who wants to, to create and maintain their own NPM package and then we can make it "official" (whatever that means) if that turns out to be a good idea.

**Closed by srh** 2017-05-24 16:03 UTC
Labels: cp:packaging

**Comment by srh** [comment] 2017-05-24 16:04
Maybe there should be "a lot of effort, somebody else do it" milestone.  This isn't exactly wontfix.
