### ISSUE TITLE
Allow for custom ids

### ISSUE THREAD

**Issue by mbrevda** [rethinkdb/rethinkdb#4883] opened 2015-09-24 19:29 UTC
We prefer keeping hyphens out if our UUID's. It would be nice if ids could be configured somehow.

**Comment by danielmewes** [comment] 2015-09-24 22:10
I think this will be part of https://github.com/rethinkdb/rethinkdb/issues/117 . Would you mind commenting in that thread with the requirements you have for the primary key generation scheme?

For the moment, I'd recommend generating the keys explicitly on the client when inserting data. The server isn't doing anything special with its UUIDs (it just picks a random one when evaluating the insert).

**Comment by danielmewes** [comment] 2015-09-24 22:10
Closing as duplicate of #117.

**Closed by danielmewes** 2015-09-24 22:10 UTC
