### ISSUE TITLE
Efficient way to find orphaned documents?

### ISSUE THREAD

**Issue by marshall007** [rethinkdb/rethinkdb#4566] opened 2015-07-23 17:44 UTC
I'm basically trying to do an inverse of `eqJoin` where the right-hand side is null. Is there an efficient way to do something like this?

```js
r.table('diff_results').eqJoin('diff_id', r.table('diffs')).filter({ right: null })
```

Using `filter` is proving to be rather slow. Left table contains ~1.7M docs, right table contains ~4K docs:

```js
r.table('diff_results').filter(function (row) {
  return r.table('diffs').get(row('diff_id')).eq(null);
})
```

**Comment by marshall007** [comment] 2015-07-23 17:46
I think this would be solved by the `include_missing` optarg mentioned in #2720, but is there a workaround in the meantime?

**Comment by thelinuxlich** [comment] 2015-07-23 19:50
Outer join(hope that someday this will be easier to write)
```
r.table("foo").concatMap(function(s) {
    return r.table("bar").getAll(s("client_id")).coerceTo('ARRAY').do(function(data) {
      return r.branch(data.isEmpty(),[{left: s, right: null}],data.map(function(c) {
        return { left: s, right: c };
    	}));
    });
})
```

**Comment by danielmewes** [comment] 2015-07-23 20:16
I think at the moment the filter with the get is the most efficient one. At least I cannot think of a more efficient alternative. I suspect that the outer join that @thelinuxlich describes is also going to be a bit slower than the `filter(other.get.ne(null))`.

**Comment by marshall007** [comment] 2015-07-24 05:13
Thanks for the suggestions. I also tried loading all the keys in from the right table first, but that didn't help much either:

```js
r.table('right')('id')
.map(r.object(r.row, true))
.reduce(function (l, r) { return l.merge(r); })
.do(function (keys) {
  return r.table('left').filter(function (row) {
    return keys.hasFields(row('right_id')).not()
  })
})
```

I would have thought that loading 4K keys into a hashmap upfront and doing lookups against that would have been significantly faster than calling `.get()` 1.7M times. @danielmewes any insight into this?

Aside from that, my questions have been answered so feel free to close this in favor of #2720.

**Comment by danielmewes** [comment] 2015-07-24 19:00
@marshall007 Ah, that's an interesting thought. While objects aren't stored as hash-maps on the server (instead they are sorted arrays of key/value pairs, on which we perform binary search to look up a key), I would still imagine this to be somewhat faster if there are few documents in the second table since it avoids all kinds of usual subquery processing overhead.

I wonder if the slow part in this case is building the object with 4K keys one by one. Every element being added to the object in the reduction function will essentially build a new object structure, including having the keys sorted again.

A slightly different way of doing that step that might or might not be faster is:
```
r.table('right')('id')
.map([[r.row, true]])
.reduce(function (l, r) { return l.add(r); })
.coerceTo('object')
.do(function (keys) {
  return r.table('left').filter(function (row) {
    return keys.hasFields(row('right_id')).not()
  })
})
```

**Comment by marshall007** [comment] 2015-07-24 23:10
@danielmewes I was mistaken yesterday, loading the keys upfront is actually ~4-5x faster!

You're right, good catch. I always forget about #3408. The time it took to build up the object was pretty negligible compared to the total query duration, though.

Your suggestion can be further simplified which also makes it a bit faster:

```js
r.table('right')('id').map([ r.row, true ]).coerceTo('array').coerceTo('object')

// original:             500ms
// coerceTo:             55ms
// coerceTo simplified:  38ms
```

I found it slightly odd that `sequence.coerceTo('object')` fails. It seems like that should implicitly coerce to array first.

**Comment by mlucy** [comment] 2015-07-24 23:11
@marshall007 -- long term the plan is to implement https://github.com/rethinkdb/rethinkdb/issues/2721 which should fix the `.coerceTo('object')` case as a side-effect.

**Comment by danielmewes** [comment] 2015-07-24 23:14
Ah, good to know that this is faster.

Closing as a duplicate of #2720.
Once this functionality is supported by a join command, we should just spend our effort on making that generic command as fast as possible.

**Closed by danielmewes** 2015-07-24 23:14 UTC

**Comment by marshall007** [comment] 2015-07-25 02:15
Sorry to bump this again, but one more quick question. I don't know enough about how indices are persisted or the data structures used to speak about this intelligently (is it documented somewhere?), but would it be possible to optimize the case of getting primary/secondary index values from a table? For example, is `table('id')` any more efficient than `table('any_other_field')` or do both require scanning every document? Likewise, it seems like `table.distinct({ index: 'secondary' })` ends up doing a lot of reads and I'd be interested to better understand why that's necessary.

**Comment by danielmewes** [comment] 2015-07-25 02:27
@marshall007 This is currently not optimized and whether you read the primary key or another field is equally expensive. See https://github.com/rethinkdb/rethinkdb/issues/4342 for the secondary index case. In short it's often not necessary. We just need to implement the optimized code path for this case.
