### ISSUE TITLE
2.4.0 Release Candidate

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#6266] opened 2017-02-16 15:53 UTC
There are a few issues to fix and some documentation to write before the release is ready. The `2.4.x` branch has been forked from `next`. New commits to `next` will go into version 2.5.

# Checklist

- [x] Close remaining issues in this [milestone](https://github.com/rethinkdb/rethinkdb/milestone/120)
- [x] Close remaining issues in the [docs for 2.4](https://github.com/rethinkdb/docs/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.4)
- [ ] Import the documentation
- [ ] Write release notes
- [x] Tag and push v2.4.0-0RC1
- [x] Pass tests
- [x] Build packages
- [ ] Make packages available for download and testing

(updates by @gabor-boros)
- [ ] Create Dockerfiles
- [ ] Make sure Homebrew is working for linux and osx
- [ ] Close issue #6747 
- [ ] Update DigitalOcean marketplace
- [x] Release new driver version for Python, Ruby, Javascript, (Java)
- [ ] Share the release on the Blog

CR: http://thanos.atnnn.com/jobset/rethinkdb/release-v2.4.0#tabs-jobs

**Comment by srh** [comment] 2017-12-11 03:34
[ ] Also handle issues (or bump the milestone for) for the 2.3.x milestone, and other <2.4 milestones.

**Comment by srh** [comment] 2017-12-23 05:34
FWIW under ./test/run, all the tests pass except the one regression.known_failures_1774

**Comment by srh** [comment] 2017-12-30 06:07
- [ ] Might want to include the ARM64 fix which is 433cbe7c7a6714e57ec1f999c0b7f81157005775 in next.

**Comment by AtnNn** [comment] 2018-04-03 12:06
@srh Do these instructions still work for you on stretch and artful? http://samuelhughes.com/rethinkdb/build_instructions.html

- On Stretch with clang, I get a lot of errors reporting missing symbols in `std`
- On Artful, the V8 build segfaults while building the snapshot

**Comment by srh** [comment] 2018-04-04 06:03
I only had time to test Stretch this evening but the instructions worked perfectly on a fresh VM, with branch v2.4.x or next (and a git clean -ffxd in between).

**Comment by FilipeRamalho** [comment] 2018-05-20 18:07
What is meant with importing the docs ?

**Comment by srh** [comment] 2018-05-20 21:12
Nobody mentioned importing the docs here. (??)

**Comment by FilipeRamalho** [comment] 2018-05-20 21:13
@srh 
"Import the documentation" on the main post.

**Comment by srh** [comment] 2018-05-20 21:17
Oh, I can't read.

**Comment by srh** [comment] 2019-10-03 06:07
I'm trying to make a list of code changes we want for 2.4.

- [ ] get macOS build working, with pregenerated web-assets.  I've applied this fix in https://github.com/srh/rethinkdb/tree/srh/pregen , I just need to fix up some debian/ubuntu package scripts, and maybe build-rpm.sh too.

- [ ] Figure out how to build on Alpine Linux.  I get linking errors at the end because `backtrace` isn't present.  (It uses musl.)  Figure out what Alpine Linux people do.

**Comment by definitiontv** [comment] 2019-10-07 15:31
Re 2:/  Does this help?
https://alpinelinux.org/posts/Alpine-Linux-has-switched-to-musl-libc.html

**Comment by definitiontv** [comment] 2019-10-07 15:48
I sent wrong link -- ..good discussion here https://github.com/pi-hole/FTL/issues/552

**Comment by srh** [comment] 2019-11-16 02:55
AFAICT all we need to do is:

[ ] merge the [write hooks docs PR](https://github.com/rethinkdb/docs/pull/1241).  It's approved, and AFAICT should be merged right now.
[ ] Import the documentation
[ ] Tag a  v2.4.0-RC1 release, and publish packages

**Comment by srh** [comment] 2019-11-23 08:12
I tagged an unofficial RC and built and uploaded packages here: https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-special-3

If you want to have an official RC and then release 2.4.0, well, you have everything you need to do that.

**Comment by gabor-boros** [comment] 2020-05-24 04:48
Closing this since 2.4.0 is out

**Closed by gabor-boros** 2020-05-24 04:48 UTC
