### ISSUE TITLE
The web ui's Reconfigure dialog breaks when the table is unavailable.

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4419] opened 2015-06-17 20:24 UTC
![reconfigure-error](https://cloud.githubusercontent.com/assets/706854/8217583/db65176a-152d-11e5-8819-cd1930a1200e.png)

And in the  console:

```
ReferenceError: Handlebars is not defined
```

In `admin/static/coffee/modals.coffee`.

**Comment by deontologician** [comment] 2015-06-17 20:36
Ah, this is a dupe of #4365, but I didn't notice the ReferenceError before

**Closed** 2015-06-17 21:19 UTC
