### ISSUE TITLE
Conditional check not working in setWriteHook

### ISSUE THREAD

**Issue by lanipark** [rethinkdb/rethinkdb#6897] opened 2020-07-20 06:37 UTC
**Describe the bug**
Based on setWriteHook document(https://rethinkdb.com/api/javascript/set_write_hook), user can write hooks with just regular conditional statement, but any conditional statement didn't work inside writeHook function body.
Run, test with javascript.

**To Reproduce**
1. Open rethinkdb Data Explorer.
2. Running this query.
```javascript
// replace name
r.db('yourdb').table('yourtable').setWriteHook(function (context, oldVal, newVal) {
  if (oldVal) {
    return newVal.merge({
      updatedAt: context('timestamp'),
    });    
  } else {
    return newVal.merge({
      createdAt: context('timestamp'),
    });
  }
})
```
3. Check created hook.
```javascript
{
  "function": <binary, 166 bytes, "24 72 65 71 6c 5f..."> ,
  "query": "setWriteHook(function(var55, var56, var57) { return var57.merge({"updatedAt": var55("timestamp")}); })"
}
```
4. Insert some document for testing hook.
```javascript
r.db('yourdb').table('yourtable').insert({ 
  name: 'aa'
});
r.db('yourdb').table('yourtable').get('25097114-6e2d-4b58-af70-0e3cab1fbaf8');
// result:
{
  "id": "25097114-6e2d-4b58-af70-0e3cab1fbaf8" ,
  "name": "aa" ,
  "updatedAt": Mon Jul 20 2020 06:22:31 GMT+00:00
}
```

**Expected behavior**
Conditional check must work inside wirteHook function.

**System info**
 - OS: Debian GNU/Linux 10(Docker)
 - RethinkDB Version: 2.4.0

**Comment by srh** [comment] 2020-07-20 08:32
The way this works is that functions in ReQL get evaluated on the client-side with dummy parameters (an object representing a variable name), so that the inner AST gets returned and thus a query can get serialized and sent to the server.

If you want conditional logic in your write hook, use `r.branch`.

Closing as not a bug.

**Closed by srh** 2020-07-20 08:32 UTC
