### ISSUE TITLE
Server quiting with data corruption error on queries

### ISSUE THREAD

**Issue by gato** [rethinkdb/rethinkdb#3090] opened 2014-09-23 20:35 UTC
Hi!
I had this error a time ago running a cluster with 2 servers in a full replicated configuration. it was loaded with 5 million  4kb documents. (and the final installation will have more than 20M)
the error always happens in the same server. I tried switching which server was master and which was replica but always got the error pasted below. 
I've checked the disk for errors but found none.
I've rebuilt the installation using rotational disks (3Tb 7200 RPM) but the resulting database was really slow (more than 2 days to create a compound index, compared with about 3h to create the same one in an ssd) 
```
2014-08-21T11:47:19.362082555 0.128185s info: Running rethinkdb 1.13.4-0ubuntu1~trusty (GCC 4.8.2)...
2014-08-21T11:47:19.371603714 0.137707s info: Running on Linux 3.13.0-34-generic x86_64
2014-08-21T11:47:19.371719661 0.137822s info: Using cache size of 512 MB
2014-08-21T11:47:19.371927697 0.138030s warn: Requested cache size is larger than available memory.
2014-08-21T11:47:19.371969235 0.138072s info: Loading data from directory /mnt/v1/rethinkdb/data
2014-08-21T11:47:19.430678029 0.196781s info: Listening for intracluster connections on port 29015
2014-08-21T11:47:19.432559790 0.198662s info: Listening for client driver connections on port 28015
2014-08-21T11:47:19.432733746 0.198836s info: Listening for administrative HTTP connections on port 8080
2014-08-21T11:47:19.433650128 0.199753s info: Listening on addresses: 127.0.0.1, 127.0.1.1, 10.160.221.51, 10.160.222.51, ::1, fe80::218:71ff:fee3:6e6d%2, fe80::218:71ff:fee3:6e6e%3
2014-08-21T11:47:19.433665661 0.199768s info: Server ready
2014-08-21T11:47:46.608890602 27.374993s info: Connected to server "moev0" a130e6e5-f65f-413e-9162-45dbef72b80d
2014-08-21T12:24:00.783312435 2201.549415s error: Error in src/rdb_protocol/lazy_json.cc at line 22:
2014-08-21T12:24:00.783498550 2201.549601s error: Guarantee failed: [res == archive_result_t::SUCCESS] Deserialization of rdb value failed with error archive_result_t::RANGE_ERROR.
2014-08-21T12:24:00.783590087 2201.549693s error: Backtrace:
2014-08-21T12:24:02.018490331 2202.784594s error: Thu Aug 21 12:24:00 2014\n\n1: backtrace_t::backtrace_t() at 0xad8350 (/usr/bin/rethinkdb)\n2: format_backtrace(bool) at 0xad86e3 (/usr/bin/rethinkdb)\n3: report_fatal_error(char const*, int, char const*, ...) at 0xca3055 (/usr/bin/rethinkdb)\n4: get_data(rdb_value_t const*, buf_parent_t) at 0x98a142 (/usr/bin/rethinkdb)\n5: lazy_json_t::get() const at 0x98a2b4 (/usr/bin/rethinkdb)\n6: rget_cb_t::handle_pair(scoped_key_value_t&&, concurrent_traversal_fifo_enforcer_signal_t) at 0x90f665 (/usr/bin/rethinkdb)\n7: concurrent_traversal_adapter_t::handle_pair_coro(scoped_key_value_t*, semaphore_acq_t*, fifo_enforcer_write_token_t, auto_drainer_t::lock_t) at 0xa74e10 (/usr/bin/rethinkdb)\n8: callable_action_instance_t<std::_Bind<std::_Mem_fn<void (concurrent_traversal_adapter_t::*)(scoped_key_value_t*, semaphore_acq_t*, fifo_enforcer_write_token_t, auto_drainer_t::lock_t)> (concurrent_traversal_adapter_t*, scoped_key_value_t*, semaphore_acq_t*, fifo_enforcer_write_token_t, auto_drainer_t::lock_t)> >::run_action() at 0xa74c54 (/usr/bin/rethinkdb)\n9: coro_t::run() at 0xa20578 (/usr/bin/rethinkdb)
2014-08-21T12:24:02.018751993 2202.784855s error: Exiting.
```

this error is the original one, i will rebuild the installation with the lastest version and update the ticket.

**Comment by danielmewes** [comment] 2015-01-30 19:04
@gato We've just released RethinkDB 1.16.
When you get a chance to try it out, please let us know if it improves memory consumption for you.

**Comment by danielmewes** [comment] 2015-02-23 22:55
@gato Any updates? Are you still seeing this with 1.16?

**Comment by gato** [comment] 2015-02-24 13:08
Sorry, haven't tried yet, i'm currently working on something else right now and do not have quick access to the servers. Will try to make me some time soon and test it. 
Regards.
Marcelo

**Comment by danielmewes** [comment] 2015-02-24 20:09
No worries. Thanks for keeping us posted @gato .

**Comment by gato** [comment] 2015-03-31 17:42
Hi @danielmewes,
I've finally got the time to run the tests again, but i'm afraid i have to tell you that server started to swap memory early and the import process hung 15 hs later, having completed ~76% of the original data set (16M of 21M docs)  with one server swapping 1.5 GB (the one that also has the import client running) and ~330MB of swap the other one.
version tested was 1.16.3~0trusty (GCC 4.8.2) 
none other process were running in those servers.
Regards.
Marcelo

**Comment by danielmewes** [comment] 2015-03-31 19:04
@gato Thanks a lot. I really appreciate you took the time to re-try this.

At this point we might have to conclude that 2 GB of RAM (is that still the hardware you're using?) isn't enough for importing this data set with the default configuration at the moment (we should look into that more though).

To get past the import stage, you can run `rethinkdb import` with the `--clients 1` parameter. That reduces the number of concurrently inserting connections from the default of 8 to a single one, which I expect will reduce the peak memory consumption during import.

**Comment by gato** [comment] 2015-03-31 19:13
Yes, all hardware is the same, in the same conditions and with the same data.
i will run the import process again with --clients 1 to see what happens and let you know.

**Comment by danielmewes** [comment] 2015-05-06 00:41
@gato did you get a chance to try the `--clients 1` import? Did it work?

**Comment by gato** [comment] 2015-05-06 15:13
Hi @danielmewes,
Yes I've tried, after hitting some out of disk errors (my fault) I was able to load the data using --clients 1 although it was painfully slow (like 3 and 1/2 days).
At the end of the import process some swapping had occurred like 350 ~ 400 MB swap in one node and a little less in the other.
After that, I've tried a simple count query (which i knew had to traverse the whole dataset) and the server started to swap like crazy, heartbeat between the nodes failed and query hung. 
I haven't done anything after that.
Sorry.
Marcelo

**Comment by danielmewes** [comment] 2015-05-06 21:08
@gato Thanks for the info. Sorry this isn't working. I know you must have spent a lot of time on this.

So it seems like the 2 GB servers aren't enough for this.

I'll try again to reproduce this and will run some memory profiling, but I'm not sure how quickly we can bring the memory usage down enough for making this work.

For now the only option seems to be bigger servers unfortunately.

**Comment by gato** [comment] 2015-05-07 13:41
Hi @danielmewes 
I'm almost sure now that 2GB isn't enough but those are old servers and it has no point buying memory for them anyway.
So, don't waste much time chasing this issue, as this is some edge situation (lots of data in old & small hardware). Feel free to close the issue or move it to the end of your backlog.
Thanks for your support 
Marcelo

**Comment by danielmewes** [comment] 2016-04-29 20:24
Closing this. We might still want to look into reducing memory usage, but I think there's nothing specific left to do for this issue.

**Closed by danielmewes** 2016-04-29 20:24 UTC
Labels: tp:performance
