### ISSUE TITLE
Suggestion: time.resolution([resolution-spec]) → time

### ISSUE THREAD

**Issue by elifarley** [rethinkdb/rethinkdb#3962] opened 2015-03-22 15:08 UTC
The 'resolution' (or 'precision') function can help in grouping by a given duration.

It should return the same time, but rounded to a lower precision (like an hour precision, or 10-minute precision and so on).

Take [InfluxDB's example] (http://influxdb.com/docs/v0.8/api/aggregate_functions.html#count):

```SQL
SELECT COUNT(column_name) FROM series_name group by time(10m) ...
```

In ReQL:

```Python
r.table('series_name').group(lambda x: x['when'].resolution(10.minutes)).count()...
```

For group in intervals of 2 hours and a half:
```Python
r.table('series_name').group(lambda x: x['when'].resolution(2.hours + 30.minutes)).count()...
```

or

```Python
r.table('series_name').group(lambda x: x['when'].resolution(2.hours.30.minutes)).count()...
```

Or maybe:
```Python
r.table('series_name').group(lambda x: x['when'].resolution(r.duration('2h 30min')).count()...
```

**Comment by danielmewes** [comment] 2015-03-23 17:38
Hi @elifarley, thank you for your great proposal.
The issue itself looks like a duplicate of https://github.com/rethinkdb/rethinkdb/issues/1408 . I copied your proposal to there.

**Closed by danielmewes** 2015-03-23 17:38 UTC
