### ISSUE TITLE
Suggestion: Automatic DB/Table creation 

### ISSUE THREAD

**Issue by lucidfrontier45** [rethinkdb/rethinkdb#5538] opened 2016-03-18 01:27 UTC
In mongodb, database or collection will be created if not exist when referred.
I don't see any of this kind feature in RethinkDB.
How about  adding automatic db/table creation in RethinkDB?

For example

```python
conn = r.connect()
r.db("test_db").table("test_table").insert(x).run(conn)
```

will automatically create DB `test_db` and Table `test_table`.

**Comment by aaronorosen** [comment] 2016-03-18 05:47
My 2 cents is that I like that it throws an error, if the table does not exist. This adds an extra layer of protection to ensure it's not just a typo in some query for the table name rather than automatically creating it.

**Comment by lucidfrontier45** [comment] 2016-03-18 06:24
@aaronorosen 
How about adding an option in connect ?

```python
conn = r.connect(auto_create=True)
```

I think writing this kind of code every time to ensure the db and table exists is a little annoying.

```python
if db_name not in r.db_list().run(conn):
    r.db_create(db_name).run(conn)

if table_name not in r.db[db_name].table_list().run(conn):
    r.db[db_name].create_table(table_name).run(conn)
```

**Comment by aaronorosen** [comment] 2016-03-18 06:36
imho explicitly creating the tables directly your self is better. Also, creating a table takes sometime to occur so it's probably better to have your application create these on startup rather on first insert of data.

**Comment by VeXocide** [comment] 2016-03-18 14:51
This appears to be a duplicate of #2355, I'll close this issue in favour of that given the amount of discussion there.

**Closed** 2016-03-18 14:51 UTC
