### ISSUE TITLE
Can't install RethinkDB on Windows

### ISSUE THREAD

**Issue by achenws** [rethinkdb/rethinkdb#6892] opened 2020-07-07 05:11 UTC
**Describe the bug**
 I cannot download the ZIP of RethinkDB.

**To Reproduce**
1. Go to https://rethinkdb.com/docs/install/windows/#:~:text=%20Running%20RethinkDB%20%201%20Press%20Win%20,click%20%E2%80%9CRun%2C%E2%80%9D%20and%20type%20%E2%80%9Ccmd%E2%80%9D%20ENTER%20More%20.
2. Attempt to download the ZIP archive.
3. Error 404
**Expected behavior**
Supposed to download the ZIP archive.

**Screenshots**
![image](https://user-images.githubusercontent.com/24927137/86715990-9cedf080-bfd5-11ea-84f4-9990c2c277d2.png)

**System info**
 - OS: [Windows 10]
 - RethinkDB Version: [e.g. 2.4.0]

**Additional context**

**Comment by ochukochris** [comment] 2020-07-16 13:31
I am facing this same issue and it's terrifying as I have not been able to proceed with using rethinkdb

**Comment by McSneaky** [comment] 2020-07-16 14:07
There are several issues about it already and they all have the same answer: https://github.com/rethinkdb/rethinkdb/issues/6814#issuecomment-596061021

**Comment by ochukochris** [comment] 2020-07-16 15:58
> There are several issues about it already and they all have the same answer: [#6814 (comment)](https://github.com/rethinkdb/rethinkdb/issues/6814#issuecomment-596061021)

Thank you so much I found a solution

**Comment by gabor-boros** [comment] 2020-07-23 07:31
Duplicate of #6896

**Closed by gabor-boros** 2020-07-23 07:31 UTC
