### ISSUE TITLE
Make sure EventEmitter in the JS driver has a `done` event

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#5030] opened 2015-11-02 19:47 UTC
Currently the EventEmitter cursor API in the JS RethinkDB driver doesn't seem to have a `done` event, so it's impossible to tell when the cursor is closed (according to @Tryneus).

We should add a `done` event that gets fired when the cursor is empty, and document it properly.

/cc @deontologician

**Comment by deontologician** [comment] 2015-11-02 20:14
I think this is a dupe of #2577

**Comment by danielmewes** [comment] 2015-11-02 20:18
That sounds right. Closing in favor of #2577.

**Closed by danielmewes** 2015-11-02 20:18 UTC
