### ISSUE TITLE
Incorrect server uptime

### ISSUE THREAD

**Issue by whyando** [rethinkdb/rethinkdb#5541] opened 2016-03-18 16:07 UTC
I'm new to rethinkdb but this must be a bug
http://prntscr.com/agvcp3
somehow it thinks the server has been running 369 years
additionally it lists all the log entries as being within a minute although that's not true

**Comment by mglukhovsky** [comment] 2016-03-18 16:17
@whyando: what version of RethinkDB are you running, and on what operating system?

**Comment by whyando** [comment] 2016-03-18 16:26
printscreen of rethinkdb.exe:
http://prntscr.com/agvmek

version 2.2.4-windows-alpha-4 (debug)
I'm on windows 10 but it thinks I'm running windows 8 server

**Comment by mglukhovsky** [comment] 2016-03-18 16:42
@whyando: thanks! It looks like this is a duplicate of #5388 -- we're working on a fix.

**Closed by mglukhovsky** 2016-03-18 16:42 UTC
