### ISSUE TITLE
No error on changefeed after server restart in Java driver

### ISSUE THREAD

**Issue by gyim** [rethinkdb/rethinkdb#5439] opened 2016-02-23 15:45 UTC
I set up a changefeed for a table and restarted RethinkDB. After restarting the database the application did not receive any notifications about the changes, and no exceptions were thrown.

How to reproduce the issue:

- Start the latest official RethinkDB docker image (2.2.4, image ID `eeff71def8c6`)
- Create the table `test_table` in database `test`
- Start the code below
- Make any changes in the `test_table` table => the code logs the changes
- Run `docker stop rethinkdb; sleep 1; docker start rethinkdb`
- Make any changes in the table => the code does not log anything, but the app jumps to 100% CPU usage. (I waited a minute to make sure that if the client wants to reconnect, it has enough time for that).

Test code:

```java
package hu.gyim.rethinkdb_test;

import com.rethinkdb.RethinkDB;
import com.rethinkdb.net.Connection;
import com.rethinkdb.net.Cursor;

public class Main {

    public static void main(String[] args) {
        try {
            Connection conn = RethinkDB.r.connection().hostname("192.168.99.100").port(28015).connect();
            conn.use("test");

            Cursor cur = RethinkDB.r.table("test_table").changes().run(conn);
            for (Object change : cur) {
                System.out.println(change);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

Stack trace after the restart:

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at sun.nio.ch.FileDispatcherImpl.read0(FileDispatcherImpl.java:-1)
      at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
      at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
      at sun.nio.ch.IOUtil.read(IOUtil.java:197)
      at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
      - locked <0x416> (a java.lang.Object)
      at com.rethinkdb.net.SocketWrapper.recvall(SocketWrapper.java:107)
      at com.rethinkdb.net.ConnectionInstance.readResponse(ConnectionInstance.java:70)
      at com.rethinkdb.net.Connection.readResponse(Connection.java:130)
      at com.rethinkdb.net.Cursor$DefaultCursor.getNext(Cursor.java:172)
      at com.rethinkdb.net.Cursor.next(Cursor.java:110)
      at hu.gyim.rethinkdb_test.Main.main(Main.java:15)
```

**Comment by deontologician** [comment] 2016-02-23 16:41
Hi @gyim , this is unfortunately the expected behavior at the moment. Changefeed data structures aren't persisted to disk currently, so there's no ability to restart them after the database goes down. We have an issue for restarting feeds after a client crash (#3471) but this doesn't currently track surviving a database restart. (@danielmewes I don't think we have an issue for surviving db restarts right?)

One thing that's possible now, is to use [include_initial](http://rethinkdb.com/api/java/changes/) when you reconnect, to catch back up. This would involve probably throwing out any state you had before and rebuilding it, so you wouldn't want to do this if you have a changefeed on something large, like a table.

**Comment by danielmewes** [comment] 2016-02-23 16:47
‎There should be an exception though when the connection gets closed. We need to look into that.

**Comment by deontologician** [comment] 2016-02-23 16:48
Ah, good call, I overlooked that part.

**Comment by deontologician** [comment] 2016-02-23 16:51
I bet it's related to #5417

**Comment by bchavez** [comment] 2016-02-23 16:52
Here's the relevant part in .NET: https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Net/SocketWrapper.cs#L201

**Comment by pires** [comment] 2016-02-25 12:06
> at com.rethinkdb.net.ConnectionInstance.readResponse(ConnectionInstance.java:70)

`ConnectionInstance` is gone in the latest version, `2.2-beta-5`.

**Comment by pires** [comment] 2016-02-25 12:11
@bchavez yes it does, but in a different manner.

https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/SocketWrapper.java#L129
https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L155

I believe having the _awaiter_ facility in `SocketWrapper` is misleading. `SocketWrapper` in Java is responsible for socket management and (de)serialization stuff alone. `Connection` is the one handling all the hurdle around multi-threading, etc. Hence, this is where I put the logic about handling network exceptions there.

**Comment by bchavez** [comment] 2016-02-25 16:01
@pires, there's a subtle bug in the code when processing exceptions this way.

https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L139

After the pump is finished processing a response cleanly, suppose the connection drops outside of the `try{}catch{}` statement. The pump isn't around to catch it. `!isOpen` is `true`. The `while(true)` loop breaks in **Line 145**. `.close` is never called. Hence, leaving all awaiting queries hanging.

**Comment by pires** [comment] 2016-02-25 16:10
@bchavez you are right. Opening an issue

I'd like to add that the only way to recover from a disconnection is to reconnect, and this the driver doesn't do - and AFAIK never did by design.

**Comment by danielmewes** [comment] 2016-04-07 18:04
Renamed to "No error on changefeed after server restart in Java driver" to better reflect what the remaining issue is.

**Comment by pires** [comment] 2016-04-07 18:29
@gyim can you try with latest release, `2.3.0`?

**Comment by danielmewes** [comment] 2016-04-20 00:00
Since https://github.com/rethinkdb/rethinkdb/issues/5660 has more information by now, I'm closing this as a duplicate.

**Closed by danielmewes** 2016-04-20 00:00 UTC
Labels: Java, tp:bug
