### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by MIFD670** [rethinkdb/rethinkdb#6852] opened 2020-03-31 23:45 UTC

**Comment by MIFD670** [comment] 2020-03-31 23:46
While trying to download zip folder for Windows.

**Comment by ronen12333** [comment] 2020-04-01 11:21
same

**Comment by McSneaky** [comment] 2020-04-01 11:55
Duplicate of https://github.com/rethinkdb/rethinkdb/issues/6814

As last comment by srh in there you can see that he made unofficial build for Windows, you can test that out

**Comment by srh** [comment] 2020-04-01 20:56
Thanks for the report and the answer.  Closing as duplicate.

**Closed by srh** 2020-04-01 20:56 UTC
