### ISSUE TITLE
What is this error saying, "failed to parse JSON response: Missing a name for object member.."

### ISSUE THREAD

**Issue by sirvon** [rethinkdb/rethinkdb#5546] opened 2016-03-19 20:46 UTC
this is the structure of the json..
https://github.com/sirvon/LoQooNYC/blob/master/database/data/marketplaces/by_city/bronx_marketplaces.json
here's the query..
```python
def insertJsonOneDoc(collection, jsonUrl):
    try:
       conn = xna.whichRethinkdb()
       res = r.table(collection).insert( \
       r.http(jsonUrl,result_format='json')).run(conn)
       print(res)
    except Exception as e:
        print(e)
        exc_type, exc_value, exc_traceback = sys.exc_info()
        msg = traceback.format_exc()
        print(msg)
res = insertJsonOneDoc("bronx_marketplaces",
"https://raw.githubusercontent.com/xxxx/xxxxx/master/database/data/marketplaces/
by_city/bronx_marketplaces.json")
print(res)

```
what am i missing?

**Comment by VeXocide** [comment] 2016-03-19 23:03
It appears to be invalid JSON, trying to parse it using Python's `json` module cause the following exception.
```
ValueError: Expecting property name: line 60 column 6 (char 1580)
```

There's at least one problem here:
```
      "fbHandle": "",
    	},
```
Note the `,` after `""`, the JSON parser expects another key to follow.

**Comment by VeXocide** [comment] 2016-03-19 23:04
I'm closing this issue as it's not a bug, but feel free to ask more questions here.

**Closed by VeXocide** 2016-03-19 23:04 UTC

**Comment by sirvon** [comment] 2016-03-19 23:25
Rethinkdb team is super helpful! Thank you.
