### ISSUE TITLE
Demote server from being primary for any tables

### ISSUE THREAD

**Issue by wereHamster** [rethinkdb/rethinkdb#4633] opened 2015-08-05 16:46 UTC
Recently I had to shut a server down because it was replaced by a new one in a different datacenter. The  old server was still acting as primary for some shards. To shut it down cleanly I was looking for a way to demote the server from any primary roles it had. I could not find any easy way to do that through the web UI, instead I had to manipulate the internal tables (`table_config`) through the data explorer interface. It would be nice if the web UI had native controls to demote or promote a particular server.

Version 2.0.4

**Comment by danielmewes** [comment] 2015-08-05 22:58
Thanks for the feedback @wereHamster .

This looks like a duplicate of https://github.com/rethinkdb/rethinkdb/issues/2941 , except for the web UI aspect.

I'm going to merge these two issues.

**Closed** 2016-05-06 20:33 UTC
Labels: cp:web-ui, tp:enhancement
