### ISSUE TITLE
changeFeed question

### ISSUE THREAD

**Issue by thaiat** [rethinkdb/rethinkdb#4278] opened 2015-05-25 15:04 UTC
the result i get between 2 different change feed are confusing:
```js
r.table('Customer').changes(); 
```
returns nothing untill there is a change in Customer table

```js
r.table('Customer').limit(10).changes();
```
returns an initial feed with 10 entries.

Is this the expected behavior ?

I'm trying to implement a generic mechanism for executing reactive queries on the client side.
As i don't know if the client will use `limit` or not, is my best option to always returns a first `run()` resultset and then execute the `changes()` and emit them to the client ?

**Comment by deontologician** [comment] 2015-05-25 19:53
Hi @thaiat, right now this is the expected behavior. In the 2.2 release (the one after next), we'll be adding the [return_initial](https://github.com/rethinkdb/rethinkdb/issues/3579) option, which will give you better control over this.

Closing as a duplicate of #3579, but feel free to ask more questions here if you need more explanation

**Closed by deontologician** 2015-05-25 19:53 UTC

**Comment by deontologician** [comment] 2015-05-25 19:54
Sorry, missed this:

> As i don't know if the client will use limit or not, is my best option to always returns a first run() resultset and then execute the changes() and emit them to the client ?

Right now, yes, that's the best option. Limit is different right now because the assumption was that it would be used for "top ten lists" etc, and in that case you really need the initial values.

**Comment by thaiat** [comment] 2015-05-25 21:20
@deontologician thanks for the explanation. Any idea when the feature will be available ?

**Comment by mlucy** [comment] 2015-05-26 05:52
@thaiat probably in 2-3 months would be my guess.
