### ISSUE TITLE
Building for armhf

### ISSUE THREAD

**Issue by elfgoh** [rethinkdb/rethinkdb#6427] opened 2017-07-10 17:04 UTC
1st question: the output from `configure --allow-fetch` indicated that `* Warning: ARM support is still experimental` Does this mean I shouldnt bother at all for ARM

2nd question, due to the lack of armhf binaries, i am trying to compile and ran into this error

```
 [5/428] CC build/release/obj/rdb_protocol/ql2.pb.o                                                                                               build/proto/rdb_protocol/ql2.pb.cc: In member function 'virtual google::protobuf::uint8* VersionDummy::InternalSerializeWithCachedSizesToArray(bool,
google::protobuf::uint8*) const':                                                                                                                    build/proto/rdb_protocol/ql2.pb.cc:613:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {                                                                                            ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function 'virtual google::protobuf::uint8* Query_AssocPair::InternalSerializeWithCachedSizesToArray(boo
l, google::protobuf::uint8*) const':                                                                                                                 build/proto/rdb_protocol/ql2.pb.cc:907:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {                                                                                            ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function 'virtual google::protobuf::uint8* Query::InternalSerializeWithCachedSizesToArray(bool, google:
:protobuf::uint8*) const':                                                                                                                           build/proto/rdb_protocol/ql2.pb.cc:1324:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function 'virtual google::protobuf::uint8* Frame::InternalSerializeWithCachedSizesToArray(bool, google:
:protobuf::uint8*) const':
build/proto/rdb_protocol/ql2.pb.cc:2011:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]                                            bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function 'virtual google::protobuf::uint8* Backtrace::InternalSerializeWithCachedSizesToArray(bool, goo
gle::protobuf::uint8*) const':
build/proto/rdb_protocol/ql2.pb.cc:2404:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {                                                                                            ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function 'virtual google::protobuf::uint8* Response::InternalSerializeWithCachedSizesToArray(bool, goog
le::protobuf::uint8*) const':
build/proto/rdb_protocol/ql2.pb.cc:2946:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~                                                                                                                              build/proto/rdb_protocol/ql2.pb.cc: In member function 'virtual google::protobuf::uint8* Datum_AssocPair::InternalSerializeWithCachedSizesToArray(boo
l, google::protobuf::uint8*) const':
build/proto/rdb_protocol/ql2.pb.cc:3592:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function 'virtual google::protobuf::uint8* Datum::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
build/proto/rdb_protocol/ql2.pb.cc:4018:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function 'virtual google::protobuf::uint8* Term_AssocPair::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
build/proto/rdb_protocol/ql2.pb.cc:5053:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function 'virtual google::protobuf::uint8* Term::InternalSerializeWithCachedSizesToArray(bool, google::
protobuf::uint8*) const':
build/proto/rdb_protocol/ql2.pb.cc:5406:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
src/build.mk:385: recipe for target 'build/release/obj/rdb_protocol/ql2.pb.o' failed
make[1]: *** [build/release/obj/rdb_protocol/ql2.pb.o] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
```

**Comment by AtnNn** [comment] 2017-07-10 17:12
ARM support was a best effort project. We tried to keep it working, but didn't consistently run tests or build packages for it. For example, cross-compiling from linux x86 to arm used to be possible, but I don't think it'll work out of the box anymore.

But RethinkDB is now a community project. If you or someone else wants to get more involved, we could improve it.

You can ignore those warnings by calling `make` with `ALLOW_WARNINGS=1`. That should be the current default if you build from git.

**Comment by elfgoh** [comment] 2017-07-12 10:34
For completeness, applying `make` with `ALLOW_WARNINGS=1` results in the following error

```
    [43/419] CC build/release/obj/rdb_protocol/serialize_datum.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
src/build.mk:390: recipe for target 'build/release/obj/rdb_protocol/serialize_da
tum.o' failed
make[1]: *** [build/release/obj/rdb_protocol/serialize_datum.o] Error 4
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2

real    499m55.927s
user    7m58.964s
sys     3m49.932s

```

**Comment by AtnNn** [comment] 2017-07-12 17:08
That error usually indicates that compilation ran out of memory. The solution is more RAM or more swap.

**Comment by elfgoh** [comment] 2017-07-13 02:46
@AtnNn Adding a swap file and giving this another go. 

No promises, but would it be helpful if I can assist in running tests and building packages? I am probably inexperienced but with good documentation and guidance where necessary, I probably can follow along

**Comment by elfgoh** [comment] 2017-07-13 05:14
More progress made but stuck here now

```
[88/415] CC build/release/obj/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.o
...
src/build.mk:390: recipe for target 'build/release/obj/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.o' failed
make[1]: *** [build/release/obj/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.o] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
```

**Comment by AtnNn** [comment] 2017-07-13 05:22
@elfgoh Your snippet is missing the important error message from the compiler.

**Comment by elfgoh** [comment] 2017-07-13 05:25
Sorry @AtnNn. Updated the above snippet

**Comment by AtnNn** [comment] 2017-07-13 05:43
Those errors look like #6406. It doesn't seem specific to ARM. What compiler and version are you using?

**Comment by elfgoh** [comment] 2017-07-13 05:51
Should be using gcc

```
# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 6.4.0-1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 6.4.0 20170704 (Debian 6.4.0-1)
```

**Comment by AtnNn** [comment] 2017-07-13 09:19
@elfgoh I'm guessing the errors are caused by a newer version of openssl or some other dependency.

Perhaps try re-running `./configure` with `--fetch crypto --fetch openssl` and then re-run `make`.

**Comment by elfgoh** [comment] 2017-07-19 00:46
Running `./configure --allow-fetch --fetch crypto --fetch openssl; time make ALLOW_WARNINGS=1`. Seems like it may be a dependency issue. Any idea which?

```
 [100/427] CC build/release/obj/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.o
In file included from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:0:
./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:502:10: error: field 'bn_' has incomplete type 'BIGNUM {aka bignum_st}'
   BIGNUM bn_;
          ^~~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:103,
                 from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'BIGNUM {aka struct bignum_st}'
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:0:
./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h: In constructor 'geo::ExactFloat::ExactFloat()':
./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:562:15: error: 'BN_init' was not declared in this scope
   BN_init(&bn_);
               ^
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc: In function 'geo::uint64 geo::BN_ext_get_uint64(const BIGNUM*)':
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:85:9: error: invalid use of incomplete type 'const BIGNUM {aka const struct bignum_st}'
   if (bn->top == 0) return 0;
         ^~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:103,
                 from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'BIGNUM {aka struct bignum_st}'
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:86:9: error: invalid use of incomplete type 'const BIGNUM {aka const struct bignum_st}'
   if (bn->top == 1) return BN_get_word(bn);
         ^~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:103,
                 from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'BIGNUM {aka struct bignum_st}'
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:88:33: error: invalid use of incomplete type 'const BIGNUM {aka const struct bignum_st}'
   return (static_cast<uint64>(bn->d[1]) << 32) + bn->d[0];
                                 ^~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:103,
                 from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'BIGNUM {aka struct bignum_st}'
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:88:52: error: invalid use of incomplete type 'const BIGNUM {aka const struct bignum_st}'
   return (static_cast<uint64>(bn->d[1]) << 32) + bn->d[0];
                                                    ^~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:103,
                 from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'BIGNUM {aka struct bignum_st}'
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc: In function 'int geo::BN_ext_count_low_zero_bits(const BIGNUM*)':
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:96:25: error: invalid use of incomplete type 'const BIGNUM {aka const struct bignum_st}'
   for (int i = 0; i < bn->top; ++i) {
                         ^~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:103,
                 from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'BIGNUM {aka struct bignum_st}'
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:97:20: error: invalid use of incomplete type 'const BIGNUM {aka const struct bignum_st}'
     BN_ULONG w = bn->d[i];
                    ^~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:103,
                 from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'BIGNUM {aka struct bignum_st}'
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc: In constructor 'geo::ExactFloat::ExactFloat(double)':
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:111:15: error: 'BN_init' was not declared in this scope
   BN_init(&bn_);
               ^
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc: In constructor 'geo::ExactFloat::ExactFloat(int)':
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:134:15: error: 'BN_init' was not declared in this scope
   BN_init(&bn_);
               ^
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc: In copy constructor 'geo::ExactFloat::ExactFloat(const geo::ExactFloat&)':
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:146:15: error: 'BN_init' was not declared in this scope
   BN_init(&bn_);
               ^
src/build.mk:390: recipe for target 'build/release/obj/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.o' failed
make[1]: *** [build/release/obj/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.o] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
```

**Comment by AtnNn** [comment] 2017-07-20 14:53
It looks like you might need #6407

**Comment by srh** [comment] 2017-09-27 09:28
This might now be fixed.  At least the last error looks like it would be fixed.

**Comment by gabor-boros** [comment] 2022-05-08 12:48
Arm is already supported. Closing.

**Closed by gabor-boros** 2022-05-08 12:48 UTC
