### ISSUE TITLE
Failed I/O error in Docker container

### ISSUE THREAD

**Issue by alehano** [rethinkdb/rethinkdb#6284] opened 2017-03-04 07:37 UTC
I got this error a couple of times on my dev OSX machine under a docker container.
I used 2.3.4 version. Many days I used container without errors. Error occurred when I removed the container and tried to run docker-compose again to build from image. I don't remember did I remove the container before. My /data dir is mounted to volume.
Is it Mac OSX related problem or a bug?

```
Running rethinkdb 2.3.5~0jessie (GCC 4.9.2)...
Running on Linux 4.9.8-moby x86_64
Loading data from directory /data/rethinkdb_data
error: Failed I/O: we tried to read from behind the end of the file. Either the file got truncated, or there is a bug in RethinkDB.
Version: rethinkdb 2.3.5~0jessie (GCC 4.9.2)
error: Error in src/arch/types.cc at line 35:
error: I/O operation failed. (Invalid argument) (offset = 0, count = 512)
error: Backtrace:
error: Sat Mar  4 07:31:58 2017
       
       1 [0xae7500]: backtrace_t::backtrace_t() at 0xae7500 (rethinkdb)
       2 [0xae7879]: format_backtrace(bool) at 0xae7879 (rethinkdb)
       3 [0xd9f6c3]: report_fatal_error(char const*, int, char const*, ...) at 0xd9f6c3 (rethinkdb)
       4 [0x9f688c]: linux_iocallback_t::on_io_failure(int, long, long) at 0x9f688c (rethinkdb)
       5 [0x9e7183]: linux_disk_manager_t::done(stats_diskmgr_t::action_t*) at 0x9e7183 (rethinkdb)
       6 [0x9d58fa]: conflict_resolving_diskmgr_t::done(accounting_diskmgr_action_t*) at 0x9d58fa (rethinkdb)
       7 [0x9ccd82]: blocker_pool_t::on_event(int) at 0x9ccd82 (rethinkdb)
       8 [0x9f3186]: epoll_event_queue_t::run() at 0x9f3186 (rethinkdb)
       9 [0x9f122d]: linux_thread_pool_t::start_thread(void*) at 0x9f122d (rethinkdb)
       10 [0x7f5757cec064]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x8064) [0x7f5757cec064] at 0x7f5757cec064 (/lib/x86_64-linux-gnu/libpthread.so.0)
       11 [0x7f5757a2162d]: clone+0x6d at 0x7f5757a2162d (/lib/x86_64-linux-gnu/libc.so.6)
error: Exiting.
```

**Comment by AtnNn** [comment] 2017-03-12 04:17
There has been a very similar in the past, #5864, which was fixed with a kernel upgrade.

My first hypothesis would be that the error is caused by your stack of unusual file systems. I don't know how docker volumes work on macos, but I would imagine you might have a version of RethinkDB built for Linux trying to talk to an HFS+ file system through layers of VirtualBox NFS and unionfs.

Perhaps you could work around this error by upgrading docker, virtualbox or macos?

**Comment by alehano** [comment] 2017-03-12 16:05
Thanks for answer.

**Closed** 2017-03-12 16:05 UTC

**Comment by extem** [comment] 2019-10-25 08:09
Hello.
The same error occurred.
Two replica servers crashed during the replication test.
The primary replica is working normally.
We were able to start by restarting, but we will inform you as information.

macOS 10.15.0 Catalina
Rethinkdb 2.3.6

```
Running rethinkdb 2.3.6 (CLANG 10.0.0 (clang-1000.10.43.1))...
Running on Darwin 19.0.0 x86_64
Loading data from directory /Volumes/TB3SSD/sub2_db_data
Listening for intracluster connections on port 29017
Connected to proxy proxy-4cfe3fa9-db6b-4462-b12e-4f8a8c9fd839
Connected to server "main_db_server" 627e7e10-2e71-4cf7-afe3-fc87f3c7b122
Connected to server "test_server_local_teb" bbd7594c-ee54-4014-9cb6-73ec44d8fd09
Listening for client driver connections on port 28017
Listening for administrative HTTP connections on port 8082
Listening on cluster addresses: 127.0.0.1, ::1
Listening on driver addresses: 127.0.0.1, ::1
Listening on http addresses: 127.0.0.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by adding `bind=all' to the config file (/Users/test/clusters/sub2_db.confg).
Server ready, "test_server_local_lbm" 28556b1b-0ac7-4b69-9c5f-b59f9a6465ce
error: Heartbeat timeout, killing connection to peer 192.168.100.17:29115
Disconnected from proxy proxy-4cfe3fa9-db6b-4462-b12e-4f8a8c9fd839
error: Heartbeat timeout, killing connection to peer 192.168.100.17:29015
Disconnected from server "main_db_server" 627e7e10-2e71-4cf7-afe3-fc87f3c7b122
Connected to proxy proxy-4cfe3fa9-db6b-4462-b12e-4f8a8c9fd839
Connected to server "main_db_server" 627e7e10-2e71-4cf7-afe3-fc87f3c7b122
error: Heartbeat timeout, killing connection to peer 192.168.100.17:29015
error: Heartbeat timeout, killing connection to peer 192.168.100.17:29115
Disconnected from server "main_db_server" 627e7e10-2e71-4cf7-afe3-fc87f3c7b122
Disconnected from proxy proxy-4cfe3fa9-db6b-4462-b12e-4f8a8c9fd839
Disconnected from server "test_server_local_teb" bbd7594c-ee54-4014-9cb6-73ec44d8fd09
Version: rethinkdb 2.3.6 (CLANG 10.0.0 (clang-1000.10.43.1))
error: Error in src/arch/types.cc at line 35:
error: I/O operation failed. (Input/output error) (offset = 12083200, count = 4096)
error: Backtrace:
error: Fri Oct 25 16:08:39 2019
       
       1 [0x10b937149]: 0   rethinkdb                           0x000000010b937149 _ZN11backtrace_tC2Ev + 61 at 0x10b937149 ()
       2 [0x10b9382a7]: 0   rethinkdb                           0x000000010b9382a7 _ZN26lazy_backtrace_formatter_tC2Ev + 39 at 0x10b9382a7 ()
       3 [0x10b936d01]: 0   rethinkdb                           0x000000010b936d01 _Z16format_backtraceb + 25 at 0x10b936d01 ()
       4 [0x10b902c0e]: 0   rethinkdb                           0x000000010b902c0e _Z18report_fatal_errorPKciS0_z + 411 at 0x10b902c0e ()
       5 [0x10bd24073]: 0   rethinkdb                           0x000000010bd24073 _ZN18linux_iocallback_t13on_io_failureEixx + 121 at 0x10bd24073 ()
       6 [0x10bd1b3ef]: 0   rethinkdb                           0x000000010bd1b3ef _ZN20linux_disk_manager_t4doneEPN15stats_diskmgr_t8action_tE + 125 at 0x10bd1b3ef ()
       7 [0x10b9440df]: 0   rethinkdb                           0x000000010b9440df _ZNKSt3__18functionIFvPN3alt15throttler_acq_tEEEclES3_ + 31 at 0x10b9440df ()
       8 [0x10b9440df]: 0   rethinkdb                           0x000000010b9440df _ZNKSt3__18functionIFvPN3alt15throttler_acq_tEEEclES3_ + 31 at 0x10b9440df ()
       9 [0x10bd17794]: 0   rethinkdb                           0x000000010bd17794 _ZN28conflict_resolving_diskmgr_t4doneEP27accounting_diskmgr_action_t + 1094 at 0x10bd17794 ()
       10 [0x10b9440df]: 0   rethinkdb                           0x000000010b9440df _ZNKSt3__18functionIFvPN3alt15throttler_acq_tEEEclES3_ + 31 at 0x10b9440df ()
       11 [0x10b9440df]: 0   rethinkdb                           0x000000010b9440df _ZNKSt3__18functionIFvPN3alt15throttler_acq_tEEEclES3_ + 31 at 0x10b9440df ()
       12 [0x10b9440df]: 0   rethinkdb                           0x000000010b9440df _ZNKSt3__18functionIFvPN3alt15throttler_acq_tEEEclES3_ + 31 at 0x10b9440df ()
       13 [0x10bd0e38b]: 0   rethinkdb                           0x000000010bd0e38b _ZN14blocker_pool_t8on_eventEi + 113 at 0x10bd0e38b ()
       14 [0x10bd1fc31]: 0   rethinkdb                           0x000000010bd1fc31 _ZN20kqueue_event_queue_t3runEv + 181 at 0x10bd1fc31 ()
       15 [0x10bd20b7b]: 0   rethinkdb                           0x000000010bd20b7b _ZN19linux_thread_pool_t12start_threadEPv + 769 at 0x10bd20b7b ()
       16 [0x7fff68b5ad36]: 0   libsystem_pthread.dylib             0x00007fff68b5ad36 _pthread_start + 125 at 0x7fff68b5ad36 ()
       17 [0x7fff68b5758f]: 0   libsystem_pthread.dylib             0x00007fff68b5758f thread_start + 15 at 0x7fff68b5758f ()
error: Exiting.
```
