### ISSUE TITLE
[JS Driver] Support IE 10

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#162] opened 2012-12-17 21:28 UTC
So we don't know why Internet Explorer 10 doesn't support the JavaScript Driver.
IE 10 supports DataView and Uint8Array so it should work...

Tagging in backlog.

**Comment by mikemintz** [comment] 2015-07-08 21:51
I'm pretty sure it doesn't work with IE10 because IE10 doesn't support `__proto__`, which is used in TermBase's constructor.

https://github.com/rethinkdb/rethinkdb/blob/89144e1b3689667a1fd9d295faa60c9473a99413/drivers/javascript/ast.coffee#L56

Removing that line gives me the same error in chrome that I get in IE10, so I'm fairly sure it's a culprit.

I'm trying to work out how to get the same behavior without `__proto__`, but I'm not sure what that constructor is doing exactly.

**Comment by neumino** [comment] 2015-07-09 06:01
In the constructor, the driver creates a function that maps to `bracket`, switches its internal prototype (`__proto__`) to Termbase. This is what let you do things like
```
r.expr({foo: "bar"})("foo")
// instead of
r.expr({foo: "bar"}).bracket("foo")
```

You could have TermBase be an empty constructor and everything will work fine. You'll have to use `.bracket(...)` instead of `(...)` though.
If you really want to remove `__proto__` without changing the same behavior, you can use ES6 proxy, but I think it's supported on Chrome and Firefox only :) It's also heavy-ish to do as you have to define the getter for all methods every time

**Comment by danielmewes** [comment] 2015-07-09 18:35
@mikemintz Is IE 10 support important for you?

**Comment by mikemintz** [comment] 2015-07-09 21:36
@danielmewes Yes, it's important for my use case with [rethinkdb-websocket-client](https://github.com/mikemintz/rethinkdb-websocket-client), which wraps the official driver for use in the browser. But it sounds like the javascript API would have to change in order to support that, which is pretty unfortunate.

Unless there's another way to allow function calls on objects with prototypes, it's probably best not to change it. Ideally it would check if `__proto__` is supported in the current environment, and if not, fail gracefully in a way that only disables the `bracket` shorthand.

@neumino I've tried changing TermBase to have an empty constructor (and a variety of other implementations) and I still get errors, e.g. `orderBy` is not a function. I don't have any bracket operations in my query. So I think there is more to do in order to get everything else working without `__proto__`.

**Comment by marshall007** [comment] 2015-07-09 23:20
This should be possible, but may require significant refactoring. `jQuery`, for example, implements this same sort of API and they do so without modifying `__proto__`. Take a look at the code [here](https://github.com/jquery/jquery/blob/master/src/core.js#L18).

Their implementation is arguably cleaner than how things are currently being done in `ast.coffee`, but like I said this would require a decent amount of work not a quick-fix.

**Comment by neumino** [comment] 2015-07-10 00:44
@mikemintz -- Did you replace the TermBase constructor with `function() { return this }`?
It works fine for me.

@marshall007 -- jQuery API is a less fexible. `$` is a function but not what it returns
```
$("div")("foo") // not defined and doesn't work
r.expr("div")("foo") // does work
```

**Comment by mikemintz** [comment] 2015-07-10 01:10
@neumino My bad, that actually does work for me. Turns out there I was doing `r.row('createdAt')` which was using the bracket shorthand.

I still have other issues with IE10, but let me spend some time getting to the root cause of them.

**Comment by mikemintz** [comment] 2015-07-10 01:34
The other IE10 issues were my own unrelated issues.

After taking @neumino's suggestion to replace the TermBase constructor, and adding explicit `.bracket(...)` calls to my queries, the driver works in IE10.

Would it be acceptable to modify the TermBase constructor, to something like this (sorry, not familiar with coffeescript so hopefully my syntax is right)?

```coffeescript
constructor: ->
    if ({})['__proto__']
        self = (ar (field) -> self.bracket(field))
        self.__proto__ = @.__proto__
        return self
    else
        return this
```

**Comment by danielmewes** [comment] 2015-07-14 18:00
@deontologician How does that change to `TermBase` look to you?

**Comment by deontologician** [comment] 2015-07-14 18:50
That seems reasonable

**Comment by deontologician** [comment] 2015-07-14 19:05
Created PR #4534 for this if/when it gets scheduled

**Comment by deontologician** [comment] 2015-07-21 22:35
Turns out this fails some tests. I've reverted the change, we'll have to revisit it later.

**Comment by mikemintz** [comment] 2016-02-17 20:20
Would it be possible to publish a new RethinkDB JavaScript driver release on npm? The latest published is 2.2.1, but I think the pull request https://github.com/rethinkdb/rethinkdb/pull/5067 that fixes the `__proto__` issue in IE10 was only merged into 2.2.2 and later.

**Comment by danielmewes** [comment] 2016-02-17 21:05
@mikemintz It's currently only scheduled to be part of 2.2.3. But we can backport it.

**Comment by mikemintz** [comment] 2016-02-17 21:09
Thanks, no need to spend extra time backporting it. I just want to make sure there's a plan to update the driver on npm sometime so I can confirm it works.

**Comment by danielmewes** [comment] 2016-02-17 21:16
I'll apply it to `v2.2.x` so we can ship it with RethinkDB 2.2.5.

**Comment by mikemintz** [comment] 2016-03-09 21:48
@danielmewes It looks like I mixed up my commits somehow. In https://github.com/rethinkdb/rethinkdb/pull/5067 I had intended to correct the earlier problem of omitting the `return` statement, but it looks like my commit was still missing `return` before `@`. I'l submit a fixed PR.

**Comment by danielmewes** [comment] 2016-03-09 22:33
Fixed by https://github.com/rethinkdb/rethinkdb/pull/5499

**Closed by danielmewes** 2016-03-09 22:33 UTC
Labels: good_for_contributors, JavaScript / Coffee, tp:enhancement

**Comment by mikemintz** [comment] 2016-03-30 21:06
Now that this is merged and 2.2.6 is released, could you publish a new RethinkDB JavaScript driver release on npm?

**Comment by danielmewes** [comment] 2016-03-30 21:40
@mikemintz The latest JavaScript driver 2.2.3 includes the change. Have you tried it?

**Comment by mikemintz** [comment] 2016-03-31 00:15
@danielmewes you're right, I am able to get it to work with 2.2.3 in IE10. Thanks!
