### ISSUE TITLE
allow limiting memory usage

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5943] opened 2016-07-13 20:05 UTC
We currently allow people to set a cache size limit for our disk cache, so nicely control the RAM usage for indexes and data, but there is no way of setting concrete limits on the memory used to service queries, other than the indirect one of resetting `array-limit`. The effect of this is that sys-admins have no way of limiting their exposure to the OOM killer.

One solution to this would be to have a way of limiting our memory usage for queries by watching allocations and simply failing queries when they hit this limit. However, this fixes the problem by pushing it to another layer, which is not the best design. A better one would be something like MySQL does when it spools large queries to disk for things like sorts. However that would be a lot more complicated, and would beg the question of limiting disk usage as well.

**Comment by danielmewes** [comment] 2016-07-13 20:38
This is basically https://github.com/rethinkdb/rethinkdb/issues/1375 .

The on-disk sorting is interesting and I think might actually be easier. I remember us having some discussion about this a long time ago, but I can't find an issue for it. I'll open a new one for that part and close this as a duplicate of #1375.

**Closed by danielmewes** 2016-07-13 20:38 UTC

**Comment by danielmewes** [comment] 2016-07-13 20:45
Opened https://github.com/rethinkdb/rethinkdb/issues/5944 for sorting of large intermediate results.
