### ISSUE TITLE
waitFor as optarg for run()

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#5208] opened 2015-12-14 21:58 UTC
Instead of wrapping all queries with something like ```r.wait({waitFor: "ready_for_reads"}).run().then(...)``` because for those that need periodical rebalancing(because of the lack of hash sharding) this is a bit annoying(and adds latency)

**Comment by danielmewes** [comment] 2015-12-16 01:16
Thanks for the suggestion @thelinuxlich .

I think wrapping operations in a `table.wait()` might be the wrong way of doing this, since `wait` can be very slow. At the very least it adds additional roundtrips to all replicas of the table. When waiting for write availability, it will even do a test write to ensure that the table is ready.
Having `wait` complete also doesn't guarantee that a subsequent query succeeds, since something could go wrong in the middle. Though it will of course increase the chances.

The way I'd prefer for handle this - at least for read queries - is to fire the query first. Then, only if the query fails because of missing availability, do a `table.wait({waitFor: "ready_for_reads"})`. Once that finishes, try the query again and continue in a loop until the query succeeds.

This is basically https://github.com/rethinkdb/rethinkdb/issues/4331.

Until that functionality is available on the server, the error to catch for this on the client would be the `ReqlAvailabilityError`.

**Comment by danielmewes** [comment] 2015-12-16 01:17
Going to close this as a duplicate of https://github.com/rethinkdb/rethinkdb/issues/4331, since I think these are solving the same issue.

**Closed by danielmewes** 2015-12-16 01:17 UTC
