### ISSUE TITLE
Python/gevent - Changefeed lifecycle

### ISSUE THREAD

**Issue by gdude2002** [rethinkdb/rethinkdb#6673] opened 2018-05-29 21:46 UTC
My community (a large Python programming Discord guild) is using a combination of Flask, gevent and rethinkdb to power its website. We currently have a need for live communication between our site and another application, and I figured that pushing events into a rethinkdb table and watching it using changefeeds, using webscokets for delivery, would be a good option.

And, well, it works! But I've noticed an issue that is preventing us from really taking control of things. To lay it out:

* We're using gevent-websockets as our websocket backend, and that's working fine
* At some point, we have to enter the `for document in r.table(...).changes(...).run(...)` loop - this "blocks" until any document can be delivered to the changefeed watcher
* When a document comes in, we send it down the websocket and remove it from the table

Our system allows only a single client to be connected on this endpoint, for the sake of simplicity. The thing is, there's no way to control the lifecycle of this changefeed iteration.

Here's how it currently works:

```py
keep_going = True
for document in ...changes().run(conn):
    # Do something with the document
    if not keep_going :
        break  # This is how we stop the iteration
```

The current method means that our websockets stick around long after the actual WS has closed. We're stuck waiting for another document from the changefeed, but we should have stopped waiting as soon as (or as close as possible to) the websocket was closed. 

Here's the best way I can think of solving this problem:

```py
keep_going = True
cursor = ...changes().run(conn)

while keep_going:
    doc = cursor.get(timeout=10)

    if doc is None:
        if some_check:
            keep_going = False
        continue
```

The advantage of the latter option is that the "cursor" can be stored, and its lifecycle doesn't purely rely on the pipeline of documents - For example, we can set `keep_going` from some other part of our application, and we know that it'll take effect within the next ten seconds or so.

---

Is there already some way to solve this problem? Am I missing something?

**Comment by srh** [comment] 2018-05-30 14:14
I'm not familiar with the Python ecosystem or driver. Is your problem, rephrased, that waiting for the next document from a cursor is not interruptible?

**Comment by gdude2002** [comment] 2018-05-30 14:16
That's about half of the problem.

It would also be nice to be able to set a waiting timeout of sorts - with the Python driver, when the timeout is reached then `None` would be returned instead of a document.

**Comment by gdude2002** [comment] 2018-05-30 15:10
I think that would work ideally, but the problem is that there's no way to detect that the websocket closed server-side, as it's stuck waiting for a document - the server is never notified that the websocket closed.

While it'd be possible to have the client send this, that won't be reliable as it won't be sent on, eg, connection drops

**Comment by allanlei** [comment] 2018-05-30 16:24
I would think the websocket part is unrelated to rethink changefeeds.

Also, it seems like it would be difficult achieving what you want with just a simple `for`/`while` for a producer/consumer pattern. It would be beneficial to introduce some concurrency using threads,coroutines,etc

For the websocket close detection, you would have to send heartbeats ([`OPCODE_PING = 0x09`](https://github.com/jgelens/gevent-websocket/blob/6d45a74282beeb096ed2c8b64765aad19bb6f9b9/geventwebsocket/websocket.py#L33)) to handle the un-expected connection drops/timeouts.  For regular connection close, client/server should be sending close ([`OPCODE_CLOSE = 0x08`](https://github.com/jgelens/gevent-websocket/blob/6d45a74282beeb096ed2c8b64765aad19bb6f9b9/geventwebsocket/websocket.py#L32)) according to the spec.

* https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Pings_and_Pongs_The_Heartbeat_of_WebSockets
* [Close](https://tools.ietf.org/html/rfc6455#section-5.5.1)
* [Ping](https://tools.ietf.org/html/rfc6455#section-5.5.2)
    > NOTE: A Ping frame may serve either as a keepalive or as a means to
   verify that the remote endpoint is still responsive.

**Comment by gdude2002** [comment] 2018-05-30 16:29
The correct opcodes are being sent as they should be, I'm not implementing the websocket protocol myself here. This is an issue specifically relating to how the current changefeed behaviour works alongside gevent.

Gevent does use a form of coroutine under the hood, but the user-facing API doesn't expose them for the most part - that's part of the Gevent philosophy. A while loop - or, indeed, a for loop - with some kind of timeout system would solve the problem in this case. Gevent is a little opaque when it comes to things like this so it's tricky to point at exactly what's going on under the hood, but it seems to me that the websocket handling code prevents anything from happening while that code is stuck in a `for` loop.

**Comment by gabor-boros** [comment] 2019-11-25 06:38
Hello @gdude2002 ,
Is this still a problem for you?

**Comment by gdude2002** [comment] 2019-11-25 08:38
Hiya, thanks for the follow-up.

Unfortunately we ended up moving away from Rethink, so I can no longer say
whether or not this is still a problem.

Thanks anyway, though!

**Comment by gabor-boros** [comment] 2020-01-23 12:14
Since this issue is not reported since then and can not reproduce I’m closing this issue

**Closed by gabor-boros** 2020-01-23 12:14 UTC
