### ISSUE TITLE
JS crashes server

### ISSUE THREAD

**Issue by let4be** [rethinkdb/rethinkdb#4634] opened 2015-08-05 18:32 UTC
I was very surprised to see rethinkdb server crashed, when I dived into logs I saw this:

```

2015-08-02T15:53:19.320166650 0.255873s notice: Server ready, "dev_af5" 4c92ac8d-f927-4a35-804a-a10f873cb207
2015-08-02T19:44:12.407482170 13853.343191s error: Error in src/extproc/js_runner.cc at line 178:
2015-08-02T19:44:12.407541948 13853.343249s error: Guarantee failed: [fn_id != __null]
2015-08-02T19:44:12.407555753 13853.343262s error: Backtrace:
2015-08-02T19:44:12.960427980 13853.896137s error: Sun Aug  2 19:44:12 2015\n\n1: backtrace_t::backtrace_t() at ??:?\n2: format_backtrace(bool) at ??:?\n3: report_fatal_error(char const*, int, char const*, ...) at ??:?\n4: js_runner_t::call(std::string const&, std::vector<ql::datum_t, std::allocator<ql::datum_t> > const&, js_runner_t::req_config_t const&) at ??:?\n5: ql::js_func_t::call(ql::env_t*, std::vector<ql::datum_t, std::allocator<ql::datum_t> > const&, ql::eval_flags_t) const at ??:?\n6: ql::func_t::call(ql::env_t*, ql::datum_t, ql::eval_flags_t) const at ??:?\n7: ql::map_trans_t::lst_transform(ql::env_t*, std::vector<ql::datum_t, std::allocator<ql::datum_t> >*, ql::datum_t const&) at ??:?\n8: ql::ungrouped_op_t::operator()(ql::env_t*, std::map<ql::datum_t, std::vector<ql::datum_t, std::allocator<ql::datum_t> >, optional_datum_less_t, std::allocator<std::pair<ql::datum_t const, std::vector<ql::datum_t, std::allocator<ql::datum_t> > > > >*, ql::datum_t const&) at ??:?\n9: ql::eager_datum_stream_t::next_grouped_batch(ql::env_t*, ql::batchspec_t const&, std::map<ql::datum_t, std::vector<ql::datum_t, std::allocator<ql::datum_t> >, optional_datum_less_t, std::allocator<std::pair<ql::datum_t const, std::vector<ql::datum_t, std::allocator<ql::datum_t> > > > >*) at ??:?\n10: ql::eager_datum_stream_t::next_batch_impl(ql::env_t*, ql::batchspec_t const&) at ??:?\n11: ql::datum_stream_t::next_batch(ql::env_t*, ql::batchspec_t const&) at ??:?\n12: ql::query_cache_t::ref_t::serve(ql::env_t*, Response*) at ??:?\n13: ql::query_cache_t::ref_t::fill_response(Response*) at ??:?\n14: ql::run(ql::query_id_t&&, ql::protob_t<Query>, Response*, ql::query_cache_t*, signal_t*) at ??:?\n15: rdb_query_server_t::run_query(ql::query_id_t&&, ql::protob_t<Query> const&, Response*, ql::query_cache_t*, signal_t*) at ??:?\n16: void save_exception<void query_server_t::connection_loop<json_protocol_t>(linux_tcp_conn_t*, unsigned long, ql::query_cache_t*, signal_t*)::{lambda(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*)#1}::operator()(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*) const::{lambda()#1}>(std::__exception_ptr::exception_ptr*, std::string*, cond_t*, void query_server_t::connection_loop<json_protocol_t>(linux_tcp_conn_t*, unsigned long, ql::query_cache_t*, signal_t*)::{lambda(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*)#1}::operator()(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*) const::{lambda()#1}&&) at ??:?\n17: void query_server_t::connection_loop<json_protocol_t>(linux_tcp_conn_t*, unsigned long, ql::query_cache_t*, signal_t*)::{lambda(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*)#1}::operator()(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*) const at ??:?\n18: std_function_callback_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::coro_pool_callback(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*) at ??:?\n19: coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::worker_run(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t) at ??:?\n20: callable_action_instance_t<std::_Bind<std::_Mem_fn<void (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::*)(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)> (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >*, std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)> >::run_action() at ??:?\n21: coro_t::run() at ??:?
2015-08-02T19:44:12.960562205 13853.896269s error: Exiting.
2015-08-02T19:47:26.141743199 0.084675s notice: Running rethinkdb 2.0.4~0trusty (GCC 4.8.2)...
2015-08-02T19:47:26.159450259 0.102384s notice: Running on Linux 3.13.0-32-generic x86_64

```

Any ideas?

**Comment by let4be** [comment] 2015-08-05 18:34
I'm running this JS
```
function (e) {
    return Object.keys(e).reduce(function(a, counterName) {
        a[counterName] = Object.keys(e[counterName]).reduce(function(counterSum, counterShardName) {
            return counterSum + parseInt(e[counterName][counterShardName]);
        }, 0);
        return a;
    }, {});
}
```

in the query(gorethink db driver)
```
r.Table("batches").
Map(r.Row.Field("counters")).
Changes().
Map(r.Row.Field("new_val")).
Map(r.JS("(" + countersAggregation + ")"))
```

countersAggregation is JS provided above

**Comment by let4be** [comment] 2015-08-05 18:42
Seems to be related/similar to the issue: https://github.com/rethinkdb/rethinkdb/issues/4611

**Comment by let4be** [comment] 2015-08-05 18:47
I spent few hours trying to write this js query in ReQL instead but did not succeed,
and anyway for me it seems like in the end it's going to be executed in JS land anyway
am I right?

**Comment by danielmewes** [comment] 2015-08-05 19:07
Thanks for reporting this @let4be . This indeed looks like a duplicate of #4611. 

Does this ReQL function do what you need?
I'm writing this in the syntax for the JavaScript driver. You'll have to translate it for Go (I'm not familiar with Go):
```js
var reqlCountersAggregation = function(e) {
    return e.coerceTo('array').map(function(keyValue) {
        return [
            keyValue(0),
            keyValue(1)
                .map(function(stringNum) { return stringNum.coerceTo('number'); } )
                .sum() ];
    }).coerceTo('object');
}

....map(reqlCountersAggregation)
```

The trick is in the `e.coerceTo('array')`. This converts an object such as `{x: ["1", "2"], y: ["3"]}` into an array of key-value pairs: `[["x", ["1", "2"]], ["y", ["3"]]]`.

Does that do what you need?

**Comment by danielmewes** [comment] 2015-08-05 19:08
ReQL queries that don't use `r.js` are not executed in the JS interpreter by the way, so that would certainly avoid the problem.

**Closed by danielmewes** 2015-08-05 19:08 UTC

**Comment by danielmewes** [comment] 2015-08-05 19:10
Closing as duplicate of #4611 

(@Tryneus you might be interested in @let4be 's test case, though I couldn't (quickly) reproduce the crash with that)

**Comment by let4be** [comment] 2015-08-05 19:29
JS did the job perfectly well and crash appeared out of nowhere... So I
guess it's not easily reproducible bug. This is the single JS call inside
my rethinkdb queries so I'm quite sure about the source.

And BIG thanks, Daniel, for the help with translation of JS into ReQL will
test this tomorrow :)

Closing as duplicate of #4611
<https://github.com/rethinkdb/rethinkdb/issues/4611>

(@Tryneus <https://github.com/Tryneus> you might be interested in @let4be
<https://github.com/let4be> 's test case, though I couldn't (quickly)
reproduce the crash with that)

—
Reply to this email directly or view it on GitHub
<https://github.com/rethinkdb/rethinkdb/issues/4634#issuecomment-128113293>.

**Comment by let4be** [comment] 2015-08-06 07:29
Had to slightly modify your query @danielmewes but thanks for getting me to the right direction

simplified version without `.changes()` call
```
r.table('batches')
.filter(r.row.hasFields('counters'))
.map(r.row('counters'))
.map(function(e){
    return e.coerceTo('array').map(function(keyValue) {
        return [
            keyValue(0),
            keyValue(1).coerceTo('array').map(function(stringNum) { return stringNum(1).coerceTo('number'); } )
                .sum() ]
    }).coerceTo('object');
})
```

**Comment by let4be** [comment] 2015-08-06 07:32
There is still one thing unclear to me regarding how such complex queries with lambas inside can be executed without using JS server-side...

Basically this query has 3 anonymous nested functions and I don't see a way how this can be executed without interpreting JS inside, and if this is the case this can hit performance if done each time the record is being passed thru those `.map()` functions

Would appreciate any insight

**Comment by danielmewes** [comment] 2015-08-06 07:38
@let4be While you write these functions as JS lambda functions (or Python lambda functions, or Ruby lambda functions etc. depending on which driver you're using), they are translated into a ReQL function in the driver and then send to the server. No JavaScript code is ever sent to the server, unless you use `r.js`.
http://rethinkdb.com/blog/lambda-functions/ has an explanation of the process.

**Comment by let4be** [comment] 2015-08-06 07:45
Thanks you very much! Totally makes sense
