### ISSUE TITLE
Error: write EPIPE when inserting 54MB file

### ISSUE THREAD

**Issue by llambda** [rethinkdb/rethinkdb#4529] opened 2015-07-10 02:52 UTC
Hello, first of all thank you for this great and fantastic database software.

Now, I wanted to report an issue I am encountering of inserting files of 54MB size; for instance, the Atom RPM ( easily downloadable at https://atom.io/download/rpm ) into a test RethinkDB database. (I was able to upload 20MB and smaller files without error. I have not tried other sizes yet.)

Linux version 4.0.6-300.fc22.x86_64, iojs v2.3.4. Fedora 22. rethinkdb node module 2.0.2, rethinkdb 2.0.4 database.

This is the error in the console:

```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at Object.exports._errnoException (util.js:814:11)
    at exports._exceptionWithHostPort (util.js:837:20)
    at WriteWrap.afterWrite (net.js:758:14)
```

And this is a test case:

```
npm -i bluebird stream-to-buffer
```

```
var Promise = require('bluebird');
Promise.longStackTraces();

var fs = require('fs');

var streamToBuffer = Promise.promisify(require('stream-to-buffer'));
var r = require('rethinkdb');

var file = fs.createReadStream('/tmp/atom.rpm');

streamToBuffer(file)
.then(function (buffer) {
    return r.connect()
    .then(function (conn) {
        return r.table('test')
        .insert({
            size: buffer.length,
            date: new Date(),
            file: buffer
        })
        .run(conn, function (err, ok) {
            console.error(err)
            console.log(ok)
        })
    })
})
```

Edit: After running a bunch of times, one time I got this message:

```
{ [RqlClientError: Query size (76321093) greater than maximum (67108863) in:
r.table("test").insert({size: 57240724, date: r.ISO8601("2015-07-10T03:04:43.647Z"), file: r.binary(<data>)})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^]
  name: 'RqlClientError',
  msg: 'Query size (76321093) greater than maximum (67108863).',
  frames: [],
  message: 'Query size (76321093) greater than maximum (67108863) in:\nr.table("test").insert({size: 57240724, date: r.ISO8601("2015-07-10T03:04:43.647Z"), file: r.binary(<data>)})\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^' }
```

**Comment by mlucy** [comment] 2015-07-11 05:34
Hi @llambda --

Thanks for the report.  It looks like you're hitting the query size limit.  `r.binary` was designed to hold smallish chunks of binary data, not large files, so in general the way to solve this is to split your files into chunks.

We could certainly make the default query size limit higher though; moving this into 2.2 and tagging as `ReQL_proposal` to discuss whether or not we should do that.

**Comment by llambda** [comment] 2015-07-12 15:38
Ah, makes sense. I'm not sure how much binary data my app needs to store, I might be better off putting in files and storing references in the DB. I'd be quite interested in any info to come out as far as query limit size / effects / recommendation of storing lots of binary data in rethinkdb. Thanks for the reply.

**Comment by larkost** [comment] 2015-07-15 18:53
Linking in the discussions we had on `r.binary` and allowing (arbitrarily sized) files: #2647 and #137.

**Comment by danielmewes** [comment] 2015-07-16 00:49
@llambda Apart from the query size limitation (the limit is 64 MB in BASE64 encoding + some overhead), storing very large documents can use a lot of memory during backfills and when running certain queries that have to load data into memory. If you have a chunky server with a lot of RAM that might not be a problem, but it's one of the reasons for why we recommend not storing files of more than a few MB directly in a table at the moment.

**Comment by Morgul** [comment] 2015-08-13 15:35
Just to hop in here; I've only just run into this issue myself. The lack of error message is, I think the worst problem here, unlike @llambda, I have never gotten an error message back. Here's my test case:

```javascript

var fs = require('fs');
var r = require('rethinkdb');

//----------------------------------------------------------------------------------------------------------------------

var filename = "test.pdf";
var meta = {
    reinYear: 2015,
    policy: 555555,
    form: 1101
};

//----------------------------------------------------------------------------------------------------------------------

r.connect({ db: 'document_store' })
    .then(function(conn)
    {
        fs.readFile('./' + filename, function(error, fileData)
        {
            if(error)
            {
                console.error('Error reading file:', error.stack || error.message);
            }
            else
            {
                meta.filename = filename;
                meta.data = fileData;

                return r.table('documents').insert(meta).run(conn)
                    .then(function(results)
                    {
                        // Return the newly created document id
                        return results.generated_keys[0];
                    })
                    .then(function(id)
                    {
                        console.log("File stored as '%s'.", id);
                    })
                    .catch(function(error)
                    {
                        console.error("Failed to store file:", error.stack || error.message);
                    })
                    .finally(function()
                    {
                        process.exit();
                    });
            } // end if
        });
    });
```

As long as `test.pdf`is larger than ~50mb, then I get the following printed out to the console:

```bash
[ccase:dt-ccase-lnx] ~/d/r/examples > node fileUpload.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
```

It would be nice if what was wrong was a little more clear.

(Obviously, I'm also looking to try and store 'large' binaries in RethinkDB, so I'll probably be chiming in on #2647.)

**Comment by danielmewes** [comment] 2015-08-15 02:08
@Morgul Which version of RethinkDB was this with?

**Comment by Morgul** [comment] 2015-08-17 15:17
@danielmewes this was with `2.1.0+1~0vivid` (as reported on the page for the server)

**Comment by deontologician** [comment] 2015-08-27 19:05
So is the proposal here to increase the query size limit or make the error better?

**Comment by danielmewes** [comment] 2015-08-27 19:09
This is about increasing the limit (https://github.com/rethinkdb/rethinkdb/issues/4529#issuecomment-120578254)

**Comment by danielmewes** [comment] 2015-08-27 19:13
I opened https://github.com/rethinkdb/rethinkdb/issues/4771 for the problem of the error message not being shown.

**Comment by danielmewes** [comment] 2015-08-27 19:16
I think having some limit here is useful, because very large queries could have a lot of performance side effects on the server that we aren't testing for.

Now that storing binary data has become more common, I think 128 MB would be a more reasonable limit. That way you can transmit a 64 MB document + overhead in a query.

**Comment by VeXocide** [comment] 2015-08-27 19:17
Is there a reason not to make this configurable by the user?

**Comment by deontologician** [comment] 2015-08-27 19:17
Is there any principled way to decide what the limit should be? There's always going to be some way of going over it

**Comment by danielmewes** [comment] 2015-08-27 19:24
@VeXocide complexity I guess. But I'm not opposed to making it configurable in principle. Unfortunately we don't have anything in the protocol that allows configuring the current connection at the moment. We could either add a new command to our protocol for these purposes, or make it a cluster setting configurable through `r.db('rethinkdb').table('cluster_config')`. I feel like either option might be too much work for this at the moment.

@deontologician none that I know of. It's pretty vague. I think the main risk in setting the limit too high is that someone tries doing a batch insert of a full data set at once, and it will knock out his entire cluster (because it will run out of memory, or get heartbeat timeouts because we don't yield during parsing, etc.). We know that 64 MB queries are pretty safe in this respect. I think 128 MB are still ok. I wouldn't go much higher than that from my experience.

**Comment by VeXocide** [comment] 2015-08-27 19:27
@danielmewes -- I'd be perfectly fine with bumping this up to 128 MB and making it configurable later.

**Comment by danielmewes** [comment] 2015-09-08 20:44
Marking as settled for bumping the limit to 128 MB for now.

**Comment by nighelles** [comment] 2016-02-05 00:53
This is in review 3463,
implemented in nighelles/4529.

**Comment by nighelles** [comment] 2016-02-17 18:40
This is in next.

**Closed by nighelles** 2016-02-17 18:40 UTC
Labels: tp:API_settled
