### ISSUE TITLE
Consider removing support for all pre-2.0 versions in 2.1

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#4148] opened 2015-04-29 21:42 UTC
@Tryneus mentioned this to me in a review.  @danielmewes, how would you feel about this?

**Comment by danielmewes** [comment] 2015-04-29 21:51
What's the motivation for doing this apart from getting rid of some legacy code?

**Comment by mlucy** [comment] 2015-04-29 22:02
The motivations are:
1. It simplifies the code.
2. It gives us a clear backward-compatibility message: "If you've upgrading from 1.x to 2.y, you have to upgrade to 2.0 first to migrate everything." rather than "If you're upgrading from 1.3 to 2.1, 1.4/1.5 to 2.4, 1.6 to 2.13, ..., then you have to upgrade to one below that number first to migrate."

**Comment by danielmewes** [comment] 2015-04-29 22:11
I don't think we should do that.

It would be interesting to check the update server statistics for how many users are still on 1.16 though. If almost nobody is still on 1.16, chances are that even fewer people are on older versions and doing this wouldn't be so bad.

**Comment by Tryneus** [comment] 2015-04-30 07:36
I think we should offer 'milestone' releases for well-defined upgrade paths - these should probably coincide with the LTS releases.  Then, it would be very easy to support upgrades from all versions since the previous milestone up until the next milestone.

On a personal note, it would make my life much easier in the no-protobuf branch if we could drop support for pre-1.16 in 2.1.

**Comment by danielmewes** [comment] 2015-04-30 20:53
I think there's not enough need to do this for 2.1.
However the milestone release idea sounds reasonable in the long run.

**Comment by danielmewes** [comment] 2015-04-30 20:58
Closing as duplicate of https://github.com/rethinkdb/rethinkdb/issues/3457 for the general discussion of our policy on backwards compatibility.

**Closed by danielmewes** 2015-04-30 20:58 UTC
Labels: tp:hygiene
