### ISSUE TITLE
download link broken for windows build

### ISSUE THREAD

**Issue by Notedop** [rethinkdb/rethinkdb#6851] opened 2020-03-31 21:01 UTC
The download link on the website still results in a 404 not found response:

https://rethinkdb.com/docs/install/windows/

https://download.rethinkdb.com/windows/rethinkdb-2.4.0.zip

**Comment by srh** [comment] 2020-03-31 23:18
Thank you for reporting.  This is a duplicate of #6814 .  There is an unofficial build linked there.

**Closed by srh** 2020-03-31 23:18 UTC
