### ISSUE TITLE
Segmentation fault from reading the address (nil).

### ISSUE THREAD

**Issue by mjdean** [rethinkdb/rethinkdb#4591] opened 2015-07-28 13:04 UTC
Hi, I can consistently crash the server on Ubuntu 14.04 when running the following query.

Let me know if I can supply anymore info.

```
var testData = [
  {id: 1, x: 1, y: 1},
  {id: 2, x: 1, y: 2},
  {id: 3, x: 2, y: 1},
  {id: 4, x: 2, y: 2}
];

r.db('test').table('test').orderBy('x', 'y');           // This works
r.db('test').table('test').orderBy(r.args(['x', 'y'])); // This crashes the server
```

```
version: rethinkdb 2.0.4~0trusty (GCC 4.8.2)
error: Error in src/arch/runtime/thread_pool.cc at line 354:
error: Segmentation fault from reading the address (nil).
error: Backtrace:
error: Tue Jul 28 21:24:12 2015

       1: backtrace_t::backtrace_t() at 0x9fcee0 (/usr/bin/rethinkdb)
       2: format_backtrace(bool) at 0x9fd273 (/usr/bin/rethinkdb)
       3: report_fatal_error(char const*, int, char const*, ...) at 0xbaddc5 (/usr/bin/rethinkdb)
       4: linux_thread_pool_t::fatal_signal_handler(int, siginfo_t*, void*) at 0x929993 (/usr/bin/rethinkdb)
       5: /lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f9b9ed70340] at 0x7f9b9ed70340 (/lib/x86_64-linux-gnu/libpthread.so.0)
       6: ql::orderby_term_t::eval_impl(ql::scope_env_t*, ql::args_t*, ql::eval_flags_t) const at 0x83749f (/usr/bin/rethinkdb)
       7: ql::op_term_t::term_eval(ql::scope_env_t*, ql::eval_flags_t) const at 0x7c69e0 (/usr/bin/rethinkdb)
       8: ql::runtime_term_t::eval(ql::scope_env_t*, ql::eval_flags_t) const at 0x88faca (/usr/bin/rethinkdb)
       9: ql::query_cache_t::ref_t::run(ql::env_t*, Response*) at 0x70afc1 (/usr/bin/rethinkdb)
       10: ql::query_cache_t::ref_t::fill_response(Response*) at 0x70c59e (/usr/bin/rethinkdb)
       11: ql::run(ql::query_id_t&&, ql::protob_t<Query>, Response*, ql::query_cache_t*, signal_t*) at 0x88ff3e (/usr/bin/rethinkdb)
       12: rdb_query_server_t::run_query(ql::query_id_t&&, ql::protob_t<Query> const&, Response*, ql::query_cache_t*, signal_t*) at 0x7c36cf (/usr/bin/rethinkdb)
       13: query_server_t::handle(http_req_t const&, http_res_t*, signal_t*) at 0x9f45c8 (/usr/bin/rethinkdb)
       14: routing_http_app_t::handle(http_req_t const&, http_res_t*, signal_t*) at 0x97065d (/usr/bin/rethinkdb)
       15: routing_http_app_t::handle(http_req_t const&, http_res_t*, signal_t*) at 0x97065d (/usr/bin/rethinkdb)
       16: http_server_t::handle_conn(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t) at 0x97ec74 (/usr/bin/rethinkdb)
       17: std::_Function_handler<void (scoped_ptr_t<linux_tcp_conn_descriptor_t>&), boost::_bi::bind_t<void, boost::_mfi::mf2<void, http_server_t, scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t>, boost::_bi::list3<boost::_bi::value<http_server_t*>, boost::arg<1>, boost::_bi::value<auto_drainer_t::lock_t> > > >::_M_invoke(std::_Any_data const&, scoped_ptr_t<linux_tcp_conn_descriptor_t>&) at 0x982224 (/usr/bin/rethinkdb)
       18: linux_nonthrowing_tcp_listener_t::handle(int) at 0x913e3c (/usr/bin/rethinkdb)
       19: coro_t::run() at 0x92bf48 (/usr/bin/rethinkdb)

```

**Comment by danielmewes** [comment] 2015-07-28 17:09
Thank you for the bug report @mjdean , and sorry you're running into this.

This turns out to be a duplicate of https://github.com/rethinkdb/rethinkdb/issues/4143 . However in the other issue we assumed that the server wouldn't crash but would return an error instead. It turns out that the error is returned only in a debug mode binary, but not in the release binaries.

We have a proper fix for the problem of `r.args` not working with `orderBy`, but unfortunately it's part of a larger rewrite and we cannot backport it to 2.0.x. It won't be in the upcoming 2.1 release either, but will ship with RethinkDB 2.2 instead.

I'd like to keep this issue open with a more limited scope: We have to change the debug-only check that's described in #4134 to a release-mode check that provides a proper error message, explaining the fact that `r.args` cannot be used in `order_by` at the moment. @thelinuxlich mentioned in the other issue that `between` might also be affected by this problem, and we should check that as well.

@mlucy could you fix this in `next` and also backport to `v2.0.x` please?
From what I can tell this just needs an `rcheck` on `get_src()->args(0).type()` to detect the `r.args` in `orderby_term_t::eval_impl`.

@mjdean independently of the crash (which we're going to fix obviously), `r.args` is still not going to work with `orderBy` until RethinkDB 2.2.0.
As a work-around in JavaScript, I recommend using `.apply` to call `orderBy` with a variable number of arguments like this:
```js
var table = r.db('test').table('test');
table.orderBy.apply(table, ['x', 'y'])
```
(there might be a more concise way of writing this)

**Comment by danielmewes** [comment] 2015-07-28 20:04
@mlucy never mind, working on this now.

**Comment by danielmewes** [comment] 2015-07-28 20:38
A fix that turns the crash into a query error is in code review 3100 by @mlucy .

**Closed** 2015-07-29 03:37 UTC
Labels: tp:bug

**Comment by danielmewes** [comment] 2015-07-29 03:43
Also backported to v2.0.x in 40aeaa118a3fce6b956344aad0544788f4d1a8df

The patch fill ship with RethinkDB 2.1.0
