### ISSUE TITLE
RethinkDB becomes unresponsive when running dump

### ISSUE THREAD

**Issue by zabojnik** [rethinkdb/rethinkdb#5855] opened 2016-06-14 10:37 UTC
Server version: rethinkdb 2.2.4~0trusty (GCC 4.8.2)
Client version: 2.2.0-3

We have a large rethinkdb database that we backup daily. We use the `dump` command for that. When the dump command runs, which takes around 20-40 minutes, the server becomes unresponsive. Otherwise the server runs just fine. We are using the adaptive cache.

Do you have any recommendations on how to safely backup the database and keep the server responsive?

**Comment by danielmewes** [comment] 2016-06-14 22:28
Hi Ondrej,

someone just asked almost the same question on GitHub in
https://github.com/rethinkdb/rethinkdb/issues/5856 .

I'd like to continue the discussion there so that we have it in one place
if you don't mind.

Assuming you ran into this issue independently, you can take a look at my
reply on the GitHub thread and comment on the questions I asked there so we
can find out why this is happening in your case.

- Daniel

**Comment by danielmewes** [comment] 2016-06-14 22:29
...For some reason I thought that this was coming from our mailing list rather than from GitHub.
I'm going to close close this issue as a duplicate of https://github.com/rethinkdb/rethinkdb/issues/5856 .

**Closed by danielmewes** 2016-06-14 22:29 UTC
