### ISSUE TITLE
Community effort for triaging issues?

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#6634] opened 2018-03-07 23:38 UTC
Currently, we have almost 1500 issues and this gives RethinkDB a bad image for newcomers, they think the project is dead and not production-ready. I'm opening yet another issue, but one to call the community to help those who have admin privileges in this repo to triage the issues.

@srh If we read ALL issues and mark you wherever it seems stale, fixed, duplicate or simply notabug would  it help you?

**Comment by srh** [comment] 2018-03-08 06:14
If you mark me on an issue telling me to do so I'll close it. Or whatever is appropriate.

**Comment by srh** [comment] 2018-03-08 06:16
I started going through methodically at some point and maybe got 10 pages in from both the oldest and newest issues.  The problem is a lot of issues are "not likely" but technically a possible feature.

**Comment by thelinuxlich** [comment] 2018-03-12 17:22
We should have a issue template in this repo for whenever someone opens an issue, he will see the discord link for questions, understand that this should be used solely for bugs and feature requests, and in the future point the link for donations.

**Comment by sagivf** [comment] 2018-03-13 19:52
I agree with @thelinuxlich. @srh In my humble opinion the best thing would be to close all the issues.
Then if there is a feature or bug that somebody really wants fixed, he can ask for it to be reopened and add more details on why. If it's feasible to try to solve in lets say a years time then it should remain open. I think the issue labels, tags and branches should also be cleared up.

Rethink has obviously moved to different pace of movement and development so it's best to be realistic and communicate that. Most people realise and except that as long as some/any sort of road map is clear.

**Comment by srh** [comment] 2018-03-16 03:48
Yeah, maybe close it and mark with a tag.

**Comment by AlexanderKaraberov** [comment] 2018-03-19 12:02
Hello @srh 
Just wanted to ask is RethinkDB is still actively developed or the project is completely abandoned? Because I see that the latest commit was done a year ago

**Comment by sagivf** [comment] 2018-03-19 12:58
@Aleaxander There are commits on other branches. There is a version waiting to be released.
So it's being developed, but at a very low velocity. Hopefully it will get better.
Follow the community channels for more details (currently slack but that might change).

**Comment by Smackzter** [comment] 2018-03-21 18:13
@sagivf the slack.rethinkdb.com link is down currently so it's a bit hard to do so.

**Comment by sagivf** [comment] 2018-03-21 22:07
@Smackzter use rethinkdb.slack.com.

**Comment by srh** [comment] 2018-03-26 01:40
@thelinuxlich So far the triaging has been great, thanks.

**Comment by thelinuxlich** [comment] 2018-03-29 22:20
Ok, so I took a look over all issues and there were a bunch worth closing because of being obsolete or duplicate.

**Comment by gabor-boros** [comment] 2022-05-08 13:08
The scope of this issue could grow day by day, hence doesn't make sense to keep track of it. Especially that the issues were already triaged. Closing.

**Closed by gabor-boros** 2022-05-08 13:08 UTC
