### ISSUE TITLE
'openssl'/evp.h' not found - Mac OS X 10.11.3

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/rethinkdb#5358] opened 2016-02-04 19:37 UTC
While building on OS X after running `./configure --allow-fetch --fetch npm --fetch node` which outputted:

```
* Detecting system configuration
Bash:                           3.2.57(1)-release
Use ccache:                     no
C++ Compiler:                   CLANG 7.0.2 (/usr/bin/c++)
Host System:                    x86_64-apple-darwin15.3.0
Build System:                   Darwin 15.3.0 x86_64
Cross-compiling:                no
Host Operating System:          Darwin
Build Architecture:             x86_64
stdlib:                         -lc++
C++11:                          ok
Precompiled web assets:         no
Protobuf compiler:              /usr/local/bin/protoc
python:                         python 2.7.11
Node.js package manager:        external/node_0.12.2
coffee:                         external/coffee-script_1.10.0
Browserify:                     external/browserify_12.0.1
bluebird:                       external/bluebird_2.9.32
web UI dependencies:            external/admin-deps_2.0.3
wget:                           /usr/local/bin/wget
curl:                           /usr/bin/curl
Google Test:                    external/gtest_1.7.0
termcap:                        -ltermcap
boost_system:                   external/boost_1.56.0
ssl:                            -lssl
protobuf:                       external/protobuf_2.5.0
v8 javascript engine:           external/v8_3.30.33.16
RE2:                            external/re2_20140111
z:                              -lz
crypto:                         -lcrypto
curl:                           -lcurl
malloc:                         system
Test protobuf:                  external/protobuf_2.5.0
Test boost:                     external/boost_1.56.0
Test OpenSSL:                   external/openssl_1.0.1i
Installation prefix:            /usr/local
Configuration prefix:           /usr/local/etc
Runtime data prefix:            /usr/local/var
* Wrote configuration to config.mk
```

Then `make -j 4`:

```
[79/395] CC build/release_clang/obj/client_protocol/server.o
src/client_protocol/server.cc:8:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h> // NOLINT(build/include_order)
         ^
    [80/395] CC build/release_clang/obj/clustering/administration/artificial_reql_cluster_interface.o
1 error generated.
make[1]: *** [build/release_clang/obj/client_protocol/server.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by dalanmiller** [comment] 2016-02-04 19:51
Fixed this by adding `--fetch openssl` to my `./configure`. I think my system version of OpenSSL was too new since I usually have the most recent version thanks to `brew`.

**Comment by VeXocide** [comment] 2016-02-04 20:01
Closing as a duplicate of #4963.

**Closed by VeXocide** 2016-02-04 20:01 UTC
