### ISSUE TITLE
Node uses all swap and won't give it back without a restart

### ISSUE THREAD

**Issue by bsharpe** [rethinkdb/rethinkdb#5935] opened 2016-07-11 14:44 UTC
One of our nodes repeatedly uses all of it's swap space (~2G) despite having 256G of RAM (200 of which is for rethink cache). Rethink is the only large app running on this box.    A restart of the node releases the swap, but within hours it will happen again.   It does not happen gradually.   It happens during some event and then goes away, but never releases the swap.   e.g.  Currently the server is using 164G out of 252G with 1.8G in swap.

using `swapoff -a` does work; but causes the server to be extremely slow while it's happening

Rethink 2.3.4 built from source as per instructions in docs.
Ubuntu 14.04.01 on raw hardware (no virtualization)

We believe this is related to the index bloat issue we've seen with multi-indexes.  
https://github.com/rethinkdb/rethinkdb/issues/5923

**Comment by larkost** [comment] 2016-07-11 18:35
The swap behavior your describe sounds like normal behavior, since once a system goes into swap it rarely lets go of it (least-used-memory goes in first, which therefore is unlikely to leave). So the issue here is ore about why you are getting the memory high-water event. There are generally two area where we use memory in RethinkDB: disk cache (reduce time-consuming reads from disk, this includes all index data) and in handling queries. We have a limiter on the first[1], but there are a number of types of queries who's memory usage is not limited (except indirectly by the array-size limitations).

If you happen to hit one of these, then unfortunately this is expected behavior. Other than figuring out the query that is causing it, and rewriting it to avoid that route (typically via an index), there is not much that can be done there.

@bsharpe: Just to be sure about things, you can check the effective cache-size limitation with this query in the Data Explorer: `r.db('rethinkdb').table('server_config')`

[1] `--cache-size` on the command line, `cache-size` in the config file, or 1/2 of available memory at startup by default

**Comment by bsharpe** [comment] 2016-07-11 21:10
@larkost Thank you for looking at this.

We initially had our cache size at the default -- 1/2 of our available 256G.   But we upped it to 200G after a long period of seeing minimal ram use.

Then, we acquired some new customers who's datasets were very large.  We ended having to emergently increase the array_limit to 500,000 from 100,000 for a few specific queries just to get through the onboarding process.   We are currently working on ways around the array limit altogether in those queries.

So, perhaps it's just one of those queries that eats up the available ram.

**Comment by larkost** [comment] 2016-07-13 20:07
Since it sounds like this is probably normal (if unfortunate) behavior, I am going to close this issue. Feel free to ask more questions, and we will re-open if it looks like there is something more to do.

Inspired by this I have filed #5943 which is trying to spit-ball a way of better controlling memory usage to solve this sort of problem for sysadmins.

**Closed by larkost** 2016-07-13 20:07 UTC
