### ISSUE TITLE
Windows server uptime is wrong

### ISSUE THREAD

**Issue by simonratner** [rethinkdb/rethinkdb#5388] opened 2016-02-11 00:27 UTC
![rethink-alpha4-uptime](https://cloud.githubusercontent.com/assets/667283/12966420/fd53af08-d012-11e5-8a39-3a7b99602827.PNG)

Actual system boot time:
```
$ net stats srv | grep since | awk -v tz=$TZ '{print $3,$4,$5,tz}'
2016-02-08 11:18:45  America/Los_Angeles
```

Windows version:
```
Microsoft Windows [Version 10.0.10586]
```

**Comment by simonratner** [comment] 2016-02-11 00:32
Windows version according to rethinkdb.exe:
```
Running rethinkdb 2.2.4-windows-alpha-4 (debug) (MSC 190023506)...
Running on 6.2.9200 (Windows 8, Server 2012)
```

**Comment by AtnNn** [comment] 2016-02-11 00:35
Thanks for the report, I was able to reproduce the wrong uptime.

It looks like we're also not detecting the windows version correctly.

**Comment by bchavez** [comment] 2016-02-11 00:36
This discussion in `BugTrap` might help in determining the correct `win_ver` in **C**:

https://github.com/bchavez/BugTrap/issues/5

**Comment by danielmewes** [comment] 2016-05-31 20:21
This is fixed in the branch atnnn/windows3 which will soon become the basis of future Windows releases.

**Closed by danielmewes** 2016-05-31 20:21 UTC
Labels: tp:bug, windows
