### ISSUE TITLE
RethinkDB installation stopped working

### ISSUE THREAD

**Issue by sergeymorkovkin** [rethinkdb/rethinkdb#5814] opened 2016-06-01 20:01 UTC
Console output states:

```
vagrant@vagrant-ubuntu-trusty-32:~$ sudo apt-get install -y rethinkdb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  rethinkdb
0 upgraded, 1 newly installed, 0 to remove and 65 not upgraded.
1 not fully installed or removed.
Need to get 202 B of archives.
After this operation, 39.4 MB of additional disk space will be used.
Get:1 http://download.rethinkdb.com/apt/ trusty/main rethinkdb i386 2.3.3~0trusty [202 B]
Fetched 10.7 MB in 4s (2,377 kB/s)     
E: Failed to fetch http://download.rethinkdb.com/apt/pool/trusty/main/r/rethinkdb/rethinkdb_2.3.3~0trusty_i386.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Tried to update apt, tried with --fix-missing.
Could anybody, please, help fixing this?

**Comment by danielmewes** [comment] 2016-06-01 20:09
Thanks for reporting this. I'll check if I can reproduce the issue...

In the meantime, can you run `sudo apt-get update` and try again? Maybe this was a temporary glitch while we were uploading the new 2.3.3 version.

**Comment by beanieboi** [comment] 2016-06-01 20:12
still happening to me since a couple of hours maybe. anything we can help with?

**Comment by danielmewes** [comment] 2016-06-01 20:13
Ok I was able to reproduce the issue. Looking into it.

**Comment by danielmewes** [comment] 2016-06-01 20:21
We're rebuilding the repository. I'll update you once the new one is uploaded.

**Comment by danielmewes** [comment] 2016-06-01 20:30
Ok should be fixed now.
Thanks again for bringing this to our attention and sorry for the inconvenience.

**Closed by danielmewes** 2016-06-01 20:30 UTC

**Comment by beanieboi** [comment] 2016-06-01 21:56
thanks for being so quick <3

**Comment by sergeymorkovkin** [comment] 2016-06-02 04:43
Daniel, you're awesome!
