### ISSUE TITLE
Possible to create duplicate tables

### ISSUE THREAD

**Issue by thejsj** [rethinkdb/rethinkdb#5900] opened 2016-06-30 23:37 UTC
Got [this bug report for `rethinkdb-init`](https://github.com/thejsj/rethinkdb-init/issues/15) describing a scenario in which multiple tables with the same name being created and thought this wasn't really possible or related to my npm module, but @tjmehta showed me this today. 

<img width="1236" alt="screen shot 2016-06-30 at 4 25 12 pm" src="https://cloud.githubusercontent.com/assets/1981198/16507666/6f315756-3ee0-11e6-9376-c90c2b430bf9.png">

<img width="1013" alt="screen shot 2016-06-30 at 4 27 05 pm" src="https://cloud.githubusercontent.com/assets/1981198/16507668/70a3c588-3ee0-11e6-8757-6db6bba9eb4b.png">

**Question:** Is this expected behavior? I'm guessing this is some kind of race condition. Any way to avoid it? I'm guessing it's not a bug if there's error messages/UI for it.

**Comment by thejsj** [comment] 2016-06-30 23:38
BTW, hello to all my lovely friends at RethinkDB :)

**Comment by encryptio** [comment] 2016-07-01 18:04
This is a known race condition, yes. Table (and database) creation isn't serializable across the cluster.

Closing as a duplicate of #4898, which also goes into several ways to fix the server-side implementation.

Unfortunately I don't think there is a way to non-racily "ensure a table exists" without outside synchronization (e.g. rows in another table/some external lock mechanism/manually making a new schema update run once before deploying to multiple systems).

For reference, [horizon currently solves this](https://github.com/rethinkdb/horizon/blob/ef91b8fabd4537a8f63bb7180981ef8abcc1ada9/server/src/metadata/metadata.js) by having an extra "collections" table (in another database) which maps collection names to table names with random IDs at the end (since the rows of that table can be atomically updated, you can recover from races.) However, since it's a massive pain for people who want to touch ReQL outside of horizon, [that's going to be replaced with a mutex row](https://github.com/rethinkdb/horizon/issues/498) in the future (also in a separate table).

**Closed by encryptio** 2016-07-01 18:04 UTC
