### ISSUE TITLE
Some WebUI queries report their execution time twice

### ISSUE THREAD

**Issue by chrisvariety** [rethinkdb/rethinkdb#3927] opened 2015-03-11 22:41 UTC
Hi All,

So it looks like some queries in the WebUI are returning their execution time twice. I click 'run' once, and below the WebUI says 'Executed in xx', but no actual results are returned. About a second later the Executed time changes and results are returned.

Seeing is believing:

![executed](https://cloud.githubusercontent.com/assets/44855/6608537/ff5ec772-c804-11e4-9efa-b0265f77dcdb.gif)

This is most prevalent in queries that involve subqueries, but I'm not sure exactly what about the query is causing it. Can reproduce 100% of the time with this query:

```
r.db('fw').table('issuedbundlelicenses').filter(function(license) {
  return r.db('fw').table('recurringsubscription').filter({CustomerID: license('CustomerId')}).nth(0).default(null).eq(null);
}).filter({ProductId: 369});
```

This is on latest rethinkdb 1.16.2-1. Obviously not too big of a deal but figured I'd throw it your way! :star2:

**Comment by deontologician** [comment] 2015-03-11 22:47
Which browser are you in? I've seen this happen in firefox. We have a change to this logic on the v2.0.x branch that might fix it (or maybe not)

**Comment by chrisvariety** [comment] 2015-03-11 22:49
Chrome Version 41.0.2272.89 (64-bit) (aka latest) on Mac OS X Yosemite.

I'm happy to re-test once 2.0 is out!

**Comment by deontologician** [comment] 2015-03-11 22:51
thanks for the report, I'll check it out

**Comment by danielmewes** [comment] 2015-03-18 19:04
Also pinging @AtnNn, since - being the last person to have worked on the Data Explorer - he might have an idea about this.

**Comment by AtnNn** [comment] 2015-03-18 19:20
The execution time is incremented for every batch, causing it to sometimes go up after clicking on the "load next batch" button. It's possible that this behaviour is caused by having multiple server batches in a single page of results.

**Comment by danielmewes** [comment] 2015-03-18 20:41
Ah I see.

How about in case of batched results, we change the message from
`Executed in <time>. <rows> rows returned, <disp> displayed.`
to
`<rows> rows returned in <time>, <disp> displayed.`?

This would make it clear that the displayed execution time only accounts for the data retrieved so far, and does not reflect the time required for retrieving the whole query result.

**Comment by AtnNn** [comment] 2015-06-11 03:12
Fixed in review 2981 assigned to @deontologician.

**Comment by AtnNn** [comment] 2015-06-13 01:39
Improved the message in 96b59f5

**Closed by AtnNn** 2015-06-13 01:39 UTC
Labels: cp:web-ui, JavaScript / Coffee, tp:bug
