### ISSUE TITLE
Proposal: array-to-string (opposite of split)

### ISSUE THREAD

**Issue by mike-marcacci** [rethinkdb/rethinkdb#5336] opened 2016-01-29 03:39 UTC
Hi there! I'm looking to join an array of strings into one string using a delimiter (the exact inverse of `split`) to this effect:
```js
r.expr('foo:bar:baz').split(':').join('.');
// => "foo.bar.baz"
```

I feel like I must be missing something, but the best solution I've come up with breaks if `reduce` is parallelized.

This works, and probably always will:
```js
r.expr('foo:bar:baz').split(':').reduce((l,r) => l.add('.').add(r));
// => "foo.bar.baz"
```

But this might not:
```js
r.table('sequence').orderBy({index: 'weight'})('value').reduce((l,r) => l.add(':').add(r));
```

While I don't really have a use case for the latter, it makes me uncomfortable to use a RQL reduce function that makes an assumption of order. Another option might be to add an option argument to `reduce` that could accept `{parallel: false}`, although I imagine that would be a bit more work to write, and a `join` or `concat` string method would be nice for symmetry.

**Comment by mlucy** [comment] 2016-01-29 21:23
@mike-marcacci -- Thanks for opening this!  We'll be adding a `fold` term (https://github.com/rethinkdb/rethinkdb/issues/3736) in RethinkDB 2.3 that will let you do a reduce-like operation that's guaranteed to be applied in a particular order.  Closing as a duplicate of that issue.

**Closed by mlucy** 2016-01-29 21:23 UTC

**Comment by mike-marcacci** [comment] 2016-01-30 00:07
Wonderful! I hadn't seen that issue - thanks!
