### ISSUE TITLE
Proxy and several servers in cluster, confusing documentation/init script?

### ISSUE THREAD

**Issue by goors** [rethinkdb/rethinkdb#5887] opened 2016-06-26 08:57 UTC
I have just two servers in cluster. Now when need more I can add to my config:

```
join=ip:port
join=ip1:port
```
**Question(s) no 1**.
and that is fine, but now when doing restart on node where i have that joins in config, what will happen to my app?
Does proxy routes traffic to other nodes?

**Question(s) no 2**. is about Proxy server when want to add more nodes.
I need to restart (better say kill ) proxy script that is adding joins to proxy --join ip:port --join ip1:port and so on.

By killing that my app will go to some exception or server 500 error and I will have downtime.
My question is how to tell proxy that one,  two or more servers are now in cluster?

In your docs you are saying that app can connect to localhost, but you are forgetting what if i have 
10 or more app servers. Doing proxy join -- on each of them would be just nightmare for devOps but
then this would solve my **Question no 2** since my app will never lose connection to db like this.

**Question no 3.**
Is there some sort of "include" directive where I can keep for example joins?

Anyway, I really hope that you can provide some answers regarding this and maybe add to documentation lets say some "infrastructure sample".

**Comment by mlucy** [comment] 2016-06-30 06:41
Hi goors,

If the proxy connects to at least one node in your cluster, that node will tell it about all the other nodes in your cluster, and the proxy will then start talking to them.  If you add new nodes to the cluster, the proxy should automatically start talking to them.

Closing since this isn't a bug, but feel free to ask more questions here.

**Closed by mlucy** 2016-06-30 06:41 UTC

**Comment by goors** [comment] 2016-07-10 09:29
I know that this is not issue it is more like your docs are not clear. Can you please checkout http://stackoverflow.com/questions/38290371/rethinkdb-cluster-what-if-primary-server-is-down and give some answer.

**Comment by goors** [comment] 2016-07-10 10:28
If I stop any server in cluster my app crash and I got like 30 messages saying "Table db.table is available for outdated reads, but not up-to-date reads or writes.". I really hope you can help me out with this. 

Is this all point of your cluster to have table shards and that is it?

**Comment by mlucy** [comment] 2016-07-10 20:26
@goors -- I answered over on StackOverflow.  It sounds like automatic failover isn't working, which is most commonly caused by not having at least 3 replicas (but could also be caused by something else).

**Comment by larkost** [comment] 2016-07-11 16:56
@goors also emailed me directly with the added detail that he has 2 replicas per shard, so that sounds like the problem indeed.
