### ISSUE TITLE
Exception in Python Driver when using orderby on getall with compound index

### ISSUE THREAD

**Issue by JOE95443** [rethinkdb/rethinkdb#5567] opened 2016-03-28 13:10 UTC
This is an issue with the latest version of the RethinkDB Python driver. When trying to run a query with get_all and then order_by, an exception is thrown when using a compound index.

To reproduce:
The database table looks like this: `id | feed | datetime | content`

Create the index:
 ```python
r.db('main').table('data').index_create("feedByTime", lambda x: [x["feed"], x["datetime"]]).run(conn)
```

Try to use the index in a query, like so:
 ```python
#The ID of a feed; eg:
feedid = 'J39438-DKIEOP-3934'
print r.db('main').table('data').between([feedid, r.minval], [feedid, r.maxval], index="feedByTime").order_by(index="feedByTime").run(conn)
```

This error should be thrown:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 196, in __str__
    val_str = ', '.join(map(repr, self.items[:10]))
TypeError: sequence index must be integer, not 'slice'
```

I added a `try: except:` around line 196 of net.py to `pass` all exceptions. Everything worked as expected with the try in place. It seems that this exception should cause a warning (maybe) rather than throwing an error and making the query fail.

[Related Stackoverflow.com question](http://stackoverflow.com/questions/36238817/rethinkdb-getall-ordered-by-date-with-index?noredirect=1)

**Comment by danielmewes** [comment] 2016-03-28 18:17
Thanks for the bug report @JOE95443 .
This is probably the same issue that @nighelles mentioned in https://github.com/rethinkdb/rethinkdb/issues/5331 . It will be fixed with RethinkDB 2.3.0.

The issue is triggered by calling `print` directly on a cursor result by the way. You can probably avoid it by adding a `.to_array()` behind the `run()` before calling `print` on the result.

It also shouldn't affect any application that actually iterates over the cursor.

Closing since it's already fixed in `next` by https://github.com/rethinkdb/rethinkdb/commit/4c84e3364a833f25745eb5efd5b0494a81144fca

**Closed by danielmewes** 2016-03-28 18:17 UTC
