### ISSUE TITLE
'db_list' kills server with error: Guarantee failed: [names_out->count(database) == 0]

### ISSUE THREAD

**Issue by elifarley** [rethinkdb/rethinkdb#3858] opened 2015-03-02 13:50 UTC
RethinkDB 1.16.2
VPS with 2 GB RAM
cache size of 200 MB
~4.4 K documents in txstats_p

Every time I issue the command below:
```
rethinkdb export -e txstats_p --format csv --fields company,method,count,sum,min,avg,max -d /tmp/txstats-p-export
```

I get this error:

```
Version: rethinkdb 1.16.2-1 (GCC 4.8.2)
error: Error in src/clustering/administration/artificial_reql_cluster_interface.cc at line 36:
error: Guarantee failed: [names_out->count(database) == 0]
error: Backtrace:
addr2line: 'rethinkdb': No such file
addr2line: 'rethinkdb': No such file
error: Mon Mar  2 08:44:41 2015

       1: backtrace_t::backtrace_t() at 0xc287c0 (rethinkdb)
       2: format_backtrace(bool) at 0xc28b20 (rethinkdb)
       3: report_fatal_error(char const*, int, char const*, ...) at 0xdaed00 (rethinkdb)
       4: artificial_reql_cluster_interface_t::db_list(signal_t*, std::set<name_string_t, std::less<name_string_t>, std::allocator<name_string_t> >*, std::string*) at 0xcfb910 (rethinkdb)
       5: ql::db_list_term_t::eval_impl(ql::scope_env_t*, ql::args_t*, ql::eval_flags_t) const at 0xa8df17 (rethinkdb)
       6: ql::op_term_t::term_eval(ql::scope_env_t*, ql::eval_flags_t) const at 0xa33080 (rethinkdb)
       7: ql::runtime_term_t::eval(ql::scope_env_t*, ql::eval_flags_t) const at 0xae760d (rethinkdb)
       8: ql::run(ql::protob_t<Query>, rdb_context_t*, signal_t*, ql::stream_cache_t*, ip_and_port_t const&, Response*) at 0xae7e85 (rethinkdb)
       9: rdb_query_server_t::run_query(ql::protob_t<Query> const&, Response*, client_context_t*, ip_and_port_t const&) at 0xa2f9dd (rethinkdb)
       10: void query_server_t::connection_loop<json_protocol_t>(linux_tcp_conn_t*, client_context_t*) at 0xc2427e (rethinkdb)
       11: query_server_t::handle_conn(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t) at 0xc210cd (rethinkdb)
       12: std::_Function_handler<void (scoped_ptr_t<linux_tcp_conn_descriptor_t>&), std::_Bind<std::_Mem_fn<void (query_server_t::*)(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t)> (query_server_t*, std::_Placeholder<1>, auto_drainer_t::lock_t)> >::_M_invoke(std::_Any_data const&, scoped_ptr_t<linux_tcp_conn_descriptor_t>&) at 0xc22955 (rethinkdb)
       13: linux_nonthrowing_tcp_listener_t::handle(int) at 0xb4788c (rethinkdb)
       14: coro_t::run() at 0xb5eca8 (rethinkdb)
error: Exiting.
[1]+  Trace/breakpoint trap   rethinkdb --cache-size 200
```

And when I fire up the server again, this error line is printed:

```
Server ready, "nb" 53a72d77-c0f5-4b70-8cb4-0248af661380
error: worker process failed to resynchronize with main process
```

I then tried this command:

```
rethinkdb export
ReQL error during 'table list': Connection is closed.
```

And the error is:

```
Version: rethinkdb 1.16.2-1 (GCC 4.8.2)
error: Error in src/clustering/administration/artificial_reql_cluster_interface.cc at line 36:
error: Guarantee failed: [names_out->count(database) == 0]
error: Backtrace:
addr2line: 'rethinkdb': No such file
addr2line: 'rethinkdb': No such file
error: Mon Mar  2 09:14:57 2015

       1: backtrace_t::backtrace_t() at 0xc287c0 (rethinkdb)
       2: format_backtrace(bool) at 0xc28b20 (rethinkdb)
       3: report_fatal_error(char const*, int, char const*, ...) at 0xdaed00 (rethinkdb)
       4: artificial_reql_cluster_interface_t::db_list(signal_t*, std::set<name_string_t, std::less<name_string_t>, std::allocator<name_string_t> >*, std::string*) at 0xcfb910 (rethinkdb)
       5: ql::db_list_term_t::eval_impl(ql::scope_env_t*, ql::args_t*, ql::eval_flags_t) const at 0xa8df17 (rethinkdb)
       6: ql::op_term_t::term_eval(ql::scope_env_t*, ql::eval_flags_t) const at 0xa33080 (rethinkdb)
       7: ql::runtime_term_t::eval(ql::scope_env_t*, ql::eval_flags_t) const at 0xae760d (rethinkdb)
       8: ql::run(ql::protob_t<Query>, rdb_context_t*, signal_t*, ql::stream_cache_t*, ip_and_port_t const&, Response*) at 0xae7e85 (rethinkdb)
       9: rdb_query_server_t::run_query(ql::protob_t<Query> const&, Response*, client_context_t*, ip_and_port_t const&) at 0xa2f9dd (rethinkdb)
       10: void query_server_t::connection_loop<json_protocol_t>(linux_tcp_conn_t*, client_context_t*) at 0xc2427e (rethinkdb)
       11: query_server_t::handle_conn(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t) at 0xc210cd (rethinkdb)
       12: std::_Function_handler<void (scoped_ptr_t<linux_tcp_conn_descriptor_t>&), std::_Bind<std::_Mem_fn<void (query_server_t::*)(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t)> (query_server_t*, std::_Placeholder<1>, auto_drainer_t::lock_t)> >::_M_invoke(std::_Any_data const&, scoped_ptr_t<linux_tcp_conn_descriptor_t>&) at 0xc22955 (rethinkdb)
       13: linux_nonthrowing_tcp_listener_t::handle(int) at 0xb4788c (rethinkdb)
       14: coro_t::run() at 0xb5eca8 (rethinkdb)
error: Exiting.

[1]+  Trace/breakpoint trap   rethinkdb --cache-size 400

```

**Comment by danielmewes** [comment] 2015-03-02 16:49
Ouch, sorry you ran into this @elifarley and thank you for the issue report.

@timmaxw can you look into this please?

**Comment by AtnNn** [comment] 2015-03-04 00:54
This could be caused by having a database named `rethinkdb` that conflicts with the system database, which should be impossible.

In RethinkDB 1.16, `r.dbCreate('rethinkdb')` fails with “RqlRuntimeError: Database `rethinkdb` already exists`”

When upgrading from RethinkDB 1.15 to 1.16, if a database is called `rethinkdb` it gets renamed:

> warn: Found an existing database named `rethinkdb` when migrating metadata. Since `rethinkdb` is a reserved database name as of RethinkDB 1.16, the existing database has been renamed to `rethinkdb_`.

**Comment by AtnNn** [comment] 2015-03-04 01:25
The server lets you rename a database to `rethinkdb`, but then crashes if `r.dbList()` is called.

@elifarley does this query return anything?

`r.db('rethinkdb').table('db_config').filter({name:'rethinkdb'})`

If so, you can rename the `rethinkdb` database. This should ensure the server doesn't crash when running `rethinkdb export`.

```
r.db('rethinkdb').table('db_config').filter({name:'rethinkdb'}).update({name:'rethinkdb_renamed'})
```

**Comment by elifarley** [comment] 2015-03-04 20:04
It does:

```
r.db('rethinkdb').table('db_config').filter({name:'rethinkdb'})

->

{
"id":  "4fe111cc-6c76-4799-b45e-9bb5c468ee45" ,
"name":  "rethinkdb"
}
```

I guess exporting will work now. Thanks !

**Comment by danielmewes** [comment] 2015-03-04 21:34
We should make sure that databases cannot be renamed to `rethinkdb`.

@timmaxw could you write a fix for that?

Also moving to 2.0, since there's a work-around and this should be pretty rare.

**Comment by timmaxw** [comment] 2015-03-04 21:37
Sounds good. I will write the fix today or tomorrow.

**Closed** 2015-03-05 01:46 UTC
Labels: tp:bug
