### ISSUE TITLE
Support null characters in strings

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3163] opened 2014-10-09 17:48 UTC
The discussion came up in https://github.com/rethinkdb/rethinkdb/issues/2699 (among others)

We should consider allowing null characters in strings.

There are likely going to be some technical obstacles:
- cJSON cannot handle them I believe (we discussed replacing cJSON a few times before)
- @srh pointed out in https://github.com/rethinkdb/rethinkdb/issues/2699#issuecomment-50084639 that there could be issues with null characters in btree keys

This is pretty low priority.

**Comment by coffeemug** [comment] 2015-04-10 00:53
Moving to subsequent and marking high priority -- this came up in some internal conversations with customers.

**Comment by danielmewes** [comment] 2015-04-10 02:06
I'll check if RapidJSON supports this from the JSON side... Then we would just need to make sure that btree serialization handles it.

**Comment by danielmewes** [comment] 2015-04-10 04:24
Null bytes are now supported in the branch `daniel_rapidjson` as far as the JSON side is concerned (will be merged as part of https://github.com/rethinkdb/rethinkdb/issues/3844).

However datums still disallow null bytes, and we need to escape strings when converting them to btree keys similar to what we do with binary data.
The slightly tricky thing will be how to migrate old primary keys that contain strings with 1 bytes (these would need to be escaped too, since the escaping mechanism uses 1 bytes as escape bytes to escape null bytes).
I think we can get away with continuing to disallow null bytes in primary keys of existing tables, and require creating a new table to start using them.

Another minor thing left is that utf8 validation is currently called on a C-string in some places, but that should be easy to change (I believe the code already supports other string types).

**Comment by mlucy** [comment] 2015-04-10 05:03
@danielmewes -- we could use a different type tag in the serialization format.  `S` means string and `S+` means string with escaped NULL bytes.

**Comment by danielmewes** [comment] 2015-04-10 05:08
@mlucy That wouldn't sort correctly if you had a mixture of both though.

**Comment by mlucy** [comment] 2015-04-10 05:21
Er, right, forgot.  I guess it probably isn't worth implementing non-lexicographic key comparison just for this.

**Comment by encryptio** [comment] 2015-09-14 19:12
As discussed with @danielmewes offline, we're going to allow indexing strings containing null bytes for new secondary indexes only (disallowed in primary indexes.) Datums in general will be unrestricted wrt strings containing null bytes.

_Reasoning: Adding support for null bytes in primary keys would require adding versioning support to the primary index, which gets to be a nasty change for many reasons. We can do that later if need be._

**Comment by encryptio** [comment] 2015-09-24 21:38
In review with @mlucy.

**Comment by coffeemug** [comment] 2015-09-25 18:21
:clap: :cake:

**Comment by mlucy** [comment] 2015-10-01 01:30
Re-opening: this change broke the `polyglot/datum/object` tests in `next` because it changed some error messages.

**Comment by mlucy** [comment] 2015-10-01 01:31
Also broke `polyglot/regression/1132`.

**Comment by encryptio** [comment] 2015-10-01 23:49
Fixed in f510b09 now in `next`, reviewed by @danielmewes in person.

**Closed by encryptio** 2015-10-01 23:49 UTC
Labels: pr:high, tp:enhancement
