### ISSUE TITLE
Compound multi index

### ISSUE THREAD

**Issue by massimiliano-mantione** [rethinkdb/rethinkdb#5068] opened 2015-11-10 15:29 UTC
I have not been able to make a multi index work when the indexed values are compound.

The documentation states that "the keys in a multi index can be single values, compound values or even arbitrary expressions" so I thought it should be possible.

I need to model something like a group chat, where each message should be seen by a specific (always small) set of users.

One way to model a set of message would be this:

```
r.table("msg").insert({time: 1, topic: "t1", users: ["a", "b"], msg: "m1"});
r.table("msg").insert({time: 2, topic: "t2", users: ["a", "c"], msg: "m1"});
r.table("msg").insert({time: 3, topic: "t2", users: ["c", "b"], msg: "m1"});
r.table("msg").insert({time: 4, topic: "t1", users: ["a", "b"], msg: "m1"});
r.table("msg").insert({time: 5, topic: "t1", users: ["a", "c"], msg: "m1"});
r.table("msg").insert({time: 6, topic: "t2", users: ["c", "b"], msg: "m1"});
```

I would then need to be able to filter by time (a range), topic (a single one), and user (again, a single one).
So the ideal query would be something like
```
...between([2, "t2", "c"], [4, "t2", "c"], {index: "myIndex"})...
```

I did a few attempts but I have  not been able to obtain an index that works in this way.
The closest I got was reworking the data like this:

```
r.table("msg").insert({k:[[1,"t1","a"], [1,"t1","b"]], msg: "m1"});
r.table("msg").insert({k:[[2,"t2","a"], [2,"t2","c"]], msg: "m2"});
r.table("msg").insert({k:[[3,"t2","c"], [3,"t2","b"]], msg: "m3"});
r.table("msg").insert({k:[[4,"t1","a"], [4,"t1","b"]], msg: "m4"});
r.table("msg").insert({k:[[5,"t1","a"], [5,"t1","c"]], msg: "m5"});
r.table("msg").insert({k:[[6,"t2","c"], [6,"t2","b"]], msg: "m6"});
r.table("msg").indexCreate("imc", r.row("k"), {multi:true})
```

The idea is that "k" is a multi-value, and each value is a compound.
Then I can filter by time, but the behavior of the other values is inconsistent (or at least I don't understand it).
For instance, this query:

```
r.table("msg").between([1, r.minval, "a"], [1, r.maxval, "a"], {index:"imc"})
```

returns two entries for "m1" (I would expect one), and this returns none:

```
r.table("msg").between([1, "t1", "a"], [1, "t1", "a"], {index:"imc"})
```

(again, I would expect one).

Is this a bug, or am I doing something wrong?
If I'm doing something wrong I volunteer to make a pull request to clarify the docs! :-)

**Comment by danielmewes** [comment] 2015-11-10 20:08
I think the problem is just with the ordering. A compound index in RethinkDB is simply an index over an array, where the array is composed from multiple fields in the document.

The ordering on arrays in ReQL is defined through lexicographical ordering on its elements. In particular that means that if you do a `between([2, "t2", "c"], [4, "t2", "c"], {...})`, values such as `[3, "a", "b"]` will be in the range. In fact any value that has a 3 as a first element, as well as all values with a 2 as the first element and a second element larger than `"t2"` etc. will be inside the range.

If you want to match all but one components of the compound index exactly, while specifying a range for the remaining component, you can do that, but you have to make sure that the component that you want to specify the range on is the last one in the compound index.

In your example, you'd need to put the time at the end of the index, and then query like this:
`between(["t2", "c", 2], ["t2", "c", 4], {index: "topic_user_time"})`

Note that only the last component (the time) is different between the left and the right bound.

**Comment by danielmewes** [comment] 2015-11-10 20:11
Closing since it's not a bug.

If you can think of a good way to improve http://www.rethinkdb.com/docs/secondary-indexes/python/#compound-indexes accordingly, a pull request to https://github.com/rethinkdb/docs/ would be most welcome! Another place that we could consider for an example like this might be the cookbook http://www.rethinkdb.com/docs/cookbook/ .

**Closed by danielmewes** 2015-11-10 20:11 UTC
