### ISSUE TITLE
Import/Export Database from Web UI

### ISSUE THREAD

**Issue by aranw** [rethinkdb/rethinkdb#4281] opened 2015-05-26 14:17 UTC
I've come into a situation where I can't use the command line to import/export the database due to using docker containers and I went into the Web UI expecting to be able to this from there but found I can't. I think it'll be a really useful feature to be able to import/export database from the Web UI

**Comment by deontologician** [comment] 2015-05-26 18:44
Hi @aranw thanks for the suggestion. This seems like a reasonable idea.

One thing you may try in the meantime is to use `r.http` from the dataexplorer to send your data to an external api. Something like:

```js
r.http("http://my.receiving.api.com/", {method="POST", data=r.table('foo').coerceTo('array').toJSON()})
```

This will only work for tables smaller than 100K elements (the array size limit since we're coercing the table to an array), but it may be useful depending on your use case.

**Comment by danielmewes** [comment] 2015-08-25 20:36
This is actually a duplicate of https://github.com/rethinkdb/rethinkdb/issues/2202 .

**Closed by danielmewes** 2015-08-25 20:36 UTC
Labels: cp:web-ui, tp:enhancement
