### ISSUE TITLE
Raft - Restarting a server temporary makes the table unavailable for reads

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#4492] opened 2015-07-02 04:31 UTC
Just played a bit with the auto failover, it's awesome :)

I have a table with 3 replicas on a table with 3 servers. I'm just doing point reads.
- If I kill the master, I may loose availability, and this seems reasonable. It's basically the time to find a new master.
- If I restart the master I just killed, my point read may fail (not always) with
```
{ [ReqlRuntimeError: Cannot perform read: primary replica for shard ["", +inf) not available in:
r.db("test").table("test").get("ping")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
]
  message: 'Cannot perform read: primary replica for shard ["", +inf) not available in:\nr.db("test").table("test").get("ping")\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
  frames: [] }
```

I found that surprising that restarting the master create a loose of availability. What happens there?
The acting master get the read after it has delegates the master position to the available old master? If yes, could it forward the read there?

**Comment by larkost** [comment] 2015-07-02 15:25
When you created the table and configured it to replicate across the three servers one of the three was configured (probably automatically, but you can specify this) as the primary. When it went away a second was chosen as an interim replacement and between the detection of the first server being killed and the moment of handover is the first availability loss. When you brought back the first master it was now possible for the system to return to it's configure state and so it did, and the handover there caused the second (hopefully brief) loss of availability.

Implementing #4331 would pave over this gap in the majority of cases. Or you could change the read mode so that the read does not have to go to the master.

**Comment by danielmewes** [comment] 2015-07-02 18:10
Yeah I think this is a duplicate of #4331.
Forwarding requests from the old primary to the new one is an interesting alternative, though I think #4331 that would be the more general solution.

**Closed by danielmewes** 2015-07-02 18:10 UTC
