### ISSUE TITLE
RethinkDB v2.4.0 for Windows not working

### ISSUE THREAD

**Issue by dps910** [rethinkdb/rethinkdb#6837] opened 2020-02-22 22:15 UTC
Please change this to something else like "released soon" or something.

**Comment by AmilkarDev** [comment] 2020-03-04 11:17
I downloaded the latest version for windows from here [https://download.rethinkdb.com/windows/](url)

I found the link in official github repository in [here](https://github.com/rethinkdb/rethinkdb-download)

**Comment by srh** [comment] 2020-03-07 08:21
@dps910 and @AmilkarDev : Try my unofficial build at https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-win-1

**Comment by davidroman0O** [comment] 2020-05-18 15:41
Even the link on https://rethinkdb.com/docs/install/windows/ is dead ! :(

**Comment by gabor-boros** [comment] 2020-08-07 06:35
Duplicate of https://github.com/rethinkdb/rethinkdb/issues/6814

**Closed by gabor-boros** 2020-08-07 06:35 UTC
