### ISSUE TITLE
Concurrency problem

### ISSUE THREAD

**Issue by digi604** [rethinkdb/rethinkdb#4129] opened 2015-04-27 15:32 UTC
I have a lock table and i want to update the lock to True and set the current time if the lock is False or lock time now() - 60s.

If i have multiple threads connecting to the db this works with concurrent threads trying to acquire a lock :

    r.table('status').get('event_import_lock').update(
            lambda lock: r.branch((lock["blocked"] == False) | (lock['block_time'] < r.now()-60),
            {'blocked': True, 'block_time': r.now()},
            {}
            ), return_changes=True).run(conn)

but with this query if 2 threads try to acquire a lock sometimes they both end up with the lock:

    res = r.table("status").filter(
       (r.row["id"] == 'event_import_lock') & (
       (r.row["blocked"] == False) | (r.row['block_time'] < r.now() - 60))).update(
        {'blocked': True, 'block_time': r.now()}, return_changes=True).run(conn)

Do i not understand something here? Is the filter and update not executed at the same time? Did i do something wrong?

**Comment by mlucy** [comment] 2015-04-27 19:39
Hi @digi604,

You're correct; `.filter.update` isn't atomic, but `.update` by itself is.  We're planning to change that since other people have found it confusing as well (see https://github.com/rethinkdb/rethinkdb/issues/3992).  Closing as a duplicate of the proposal in #3992.  Sorry you ran into this!

**Closed by mlucy** 2015-04-27 19:39 UTC
