### ISSUE TITLE
Segmentation Fault in thread pool

### ISSUE THREAD

**Issue by qusiax** [rethinkdb/rethinkdb#4675] opened 2015-08-12 12:57 UTC
2015-08-12T03:19:53.765451462 1.656409s info: Table 9824314b-4015-499a-a53e-e7ad0610bdcb: Starting a new Raft election for term 1.
    2015-08-12T03:19:53.771887232 1.662845s info: Table 9824314b-4015-499a-a53e-e7ad0610bdcb: This server is Raft leader for term 1. Latest log index is 0.
    2015-08-12T03:19:53.858543007 1.749501s info: Table f90a5f7f-922c-4224-944d-21b6eb4995b7: Starting a new Raft election for term 1.
    2015-08-12T03:19:53.862674668 1.753632s info: Table f90a5f7f-922c-4224-944d-21b6eb4995b7: This server is Raft leader for term 1. Latest log index is 0.
    2015-08-12T03:19:53.908493032 1.799451s info: Table 56d71f1a-f8b1-4c2c-b57f-be3dbf415470: Starting a new Raft election for term 1.
    2015-08-12T03:19:53.911731865 1.802690s info: Table 56d71f1a-f8b1-4c2c-b57f-be3dbf415470: This server is Raft leader for term 1. Latest log index is 0.
    2015-08-12T03:19:54.186623241 2.077581s info: Table bb06c418-1efd-46df-988c-dceea897d268: Starting a new Raft election for term 1.
    2015-08-12T03:19:54.190539402 2.081497s info: Table bb06c418-1efd-46df-988c-dceea897d268: This server is Raft leader for term 1. Latest log index is 0.
    2015-08-12T03:19:54.355193397 2.246151s info: Table 9c17ca6d-cb57-46d3-9354-6a7e394ad9a5: Starting a new Raft election for term 1.
    2015-08-12T03:19:54.460760182 2.351718s info: Table ab2d4143-c356-44eb-9543-0a2a624a54b2: Starting a new Raft election for term 1.
    2015-08-12T03:19:54.631099340 2.522057s info: Table 9c17ca6d-cb57-46d3-9354-6a7e394ad9a5: This server is Raft leader for term 1. Latest log index is 0.
    2015-08-12T03:19:54.631207608 2.522165s info: Table ab2d4143-c356-44eb-9543-0a2a624a54b2: This server is Raft leader for term 1. Latest log index is 0.
    2015-08-12T12:50:12.633780640 34220.524739s error: Error in src/arch/runtime/thread_pool.cc at line 354:
    2015-08-12T12:50:12.641042701 34220.532001s error: Segmentation fault from reading the address 0x18.
    2015-08-12T12:50:12.641062470 34220.532020s error: Backtrace:

This happened when there were approx 50 documents per second being written to the db by one process and a group query (limit 10) being run over all documents through an index. cpu utilization went to 100% and lots of threads (~10 threads on single core machine) were active. then it crashed.

**Comment by danielmewes** [comment] 2015-08-12 15:10
Thank you for the bug report @qusiax and sorry you ran into this.

A few additional questions:
* Did this happen with 2.1.0 or with the beta release?
* Which operating system are you using?
* How did you install ReethinkDB (e.g. from package vs. compiled from source)?
* What is the exact `group` query you were running?
* Is the crashed server part of a cluster? If yes, of how many machines? Were the tables sharded and/or replicated?

**Comment by marshall007** [comment] 2015-08-12 21:44
@danielmewes I just ran into the same while trying to drop a database through the web UI. This was shortly after I killed a `rethinkdb restore` I was in the middle of, but I'm not sure that had anything to do with the crash:

```
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "marshall_macbook_local_keq" d0be05dd-8743-4ffa-944e-9e2fa7414e5f
Removing file /usr/local/lib/rethinkdb/data/10277161-0498-42f0-acce-814d6ded801f
Removing file /usr/local/lib/rethinkdb/data/a2d63fab-6a92-455a-affd-fc87348c918a
...
Removing file /usr/local/lib/rethinkdb/data/c0ea7756-3238-47df-9f7e-0b7361302d99
Removing file /usr/local/lib/rethinkdb/data/e82769a9-c145-452f-b669-a961002dc6b4
Version: rethinkdb 2.1.0-1 (CLANG 6.1.0 (clang-602.0.53))
error: Error in src/arch/runtime/thread_pool.cc at line 354:
error: Segmentation fault from reading the address 0x0.
error: Backtrace:
error: Wed Aug 12 15:50:54 2015
error: Exiting.
```

I'm running v2.1.0 installed via homebrew on OSX 10.10.3. The machine was not part of a cluster and none of the tables were sharded/replicated.

**Comment by danielmewes** [comment] 2015-08-12 23:47
@marshall007 trying to reproduce this at the moment. Do you remember if you did anything else before the `rethinkdb restore`? Or did you basically start a fresh server with an empty data directory, ran half of the restore, and then dropped the DB?

**Comment by marshall007** [comment] 2015-08-13 00:33
@danielmewes I haven't walked through it all again to try and reproduce yet, but here's what I did:

Started with a v2.0 data directory which loaded up and told me I needed to recreate the secondary indices. I instead just dropped each database one at a time (without issue). Then started `rethinkdb restore` from a v1.15.0 backup (just contained one database) and killed it early:

```
$ rethinkdb restore ./rethink-2015-08-12-04-30.tar.gz
Unzipping archive file...
  Done (43 seconds)
Importing from directory...
[======                                  ]  15% ^C
527967 rows imported in 11 tables
Interrupted
Interrupted
```

When I attempted to drop this database I had just partially restored (via web UI button) it successfully dropped all but one table then the exception occurred.

**Comment by danielmewes** [comment] 2015-08-15 02:03
Couldn't reproduce this yet, but still trying.

@qusiax which operating system were you using? How did you install RethinkDB? This information would be really helpful for us, so we can track down which kind of environment might trigger the error.

**Comment by qusiax** [comment] 2015-08-15 14:34
Sorry for the delay:

- happened on the 2.1 release
- Operating System: ubuntu 14.04
- installed by package (apt-get)
- the server is not part of a cluster. just a single instance with web interface disabled
- i can't give the exact group query since i was exploring the data in a cli. however, i think it was a group on a key running over a stream (after a filter or something), so no index. not sure if that helps.

**Comment by danielmewes** [comment] 2015-08-20 19:21
@marshall007 , @qusiax 
have you used changefeeds at any time before the crash happened?

**Comment by marshall007** [comment] 2015-08-20 21:06
@danielmewes I probably had changefeeds open on another database, but not the one I was dropping.

**Comment by qusiax** [comment] 2015-08-21 07:35
no

On Thu, Aug 20, 2015 at 2:06 PM, Marshall Cottrell <notifications@github.com

**Comment by soplakanets** [comment] 2015-08-25 12:01
Hello. Have same error in my log file:
```
2015-08-25T07:55:49.980850858 139.342448s error: Error in src/arch/runtime/thread_pool.cc at line 354:
2015-08-25T07:55:49.980958987 139.342556s error: Segmentation fault from reading the address 0x7f6249ad1b10.
2015-08-25T07:55:49.980980209 139.342577s error: Backtrace:
```

This happens when I run a big delete query by secondary index:
```
r.db('queue').table('score').getAll(1440446404, 1440453606, {index: 'runSequence'}).delete();
```

Data set affected by this query is about 350K records.

My specs are:
```
$ rethinkdb --version
rethinkdb 2.1.1~0trusty (GCC 4.8.2)
$ uname -a
Linux rdbm.stg.rove.me 3.13.0-52-generic #85-Ubuntu SMP Wed Apr 29 16:44:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Please let me know how can I help to reproduce this issue.

**Comment by danielmewes** [comment] 2015-08-25 21:01
Thanks @soplakanets. A few quick questions:
Are you using changefeeds, or were you previously using them on the `score` table?
Are there any additional related lines after the "error: Backtrace" one in the log file?

You say that this was a big delete query. Do you mean that the two keys given to `getAll` were matching a large number of documents?

**Comment by soplakanets** [comment] 2015-08-25 21:05
@dalanmiller 

> Are you using changefeeds, or were you previously using them on the score table?
No, and I am quite sure I never used them at all on this database.

> Are there any additional related lines after the "error: Backtrace" one in the log file?
Unfortunately, no. After that line goes normal startup info "notice: Running rethinkdb..."

> You say that this was a big delete query. Do you mean that the two keys given to getAll were matching a large number of documents?
Yes, that is exactly what I meant. the `getAll()` matched ~350K documents.

**Comment by soplakanets** [comment] 2015-08-26 11:37
I just had a similar issue with running `r.db('db').table('table').delete()`, effectively deleting all data from a large collection (2M+ records). This time the error is different, but still had a server crash. Here is all the info from logfile:

```
2015-08-26T07:33:33.876239129 84846.890462s error: Error in src/rdb_protocol/lazy_json.cc at line 22:
2015-08-26T07:33:33.877062396 84846.891285s error: Guarantee failed: [res == archive_result_t::SUCCESS] Deserialization of rdb va
lue failed with error archive_result_t::RANGE_ERROR.
2015-08-26T07:33:33.877088609 84846.891311s error: Backtrace:
2015-08-26T07:33:34.412469472 84847.426696s error: Wed Aug 26 07:33:33 2015\n\n1: backtrace_t::backtrace_t() at ??:?\n2: format_b
acktrace(bool) at ??:?\n3: report_fatal_error(char const*, int, char const*, ...) at ??:?\n4: get_data(rdb_value_t const*, buf_pa
rent_t) at ??:?\n5: lazy_json_t::get() const at ??:?\n6: rget_cb_t::handle_pair(scoped_key_value_t&&, concurrent_traversal_fifo_e
nforcer_signal_t) at ??:?\n7: concurrent_traversal_adapter_t::handle_pair_coro(scoped_key_value_t*, semaphore_acq_t*, fifo_enforc
er_write_token_t, auto_drainer_t::lock_t) at ??:?\n8: callable_action_instance_t<std::_Bind<std::_Mem_fn<void (concurrent_traversal_adapter_t::*)(scoped_key_value_t*, semaphore_acq_t*, fifo_enforcer_write_token_t, auto_drainer_t::lock_t)> (concurrent_traversal_adapter_t*, scoped_key_value_t*, semaphore_acq_t*, fifo_enforcer_write_token_t, auto_drainer_t::lock_t)> >::run_action() at ??:?\n9: coro_t::run() at ??:?
2015-08-26T07:33:34.412617835 84847.426840s error: Exiting.
```

**Comment by soplakanets** [comment] 2015-08-26 11:46
Created a separate issue: https://github.com/rethinkdb/rethinkdb/issues/4769

**Comment by danielmewes** [comment] 2015-09-03 18:02
We found an issue that could lead to memory corruption in #4769, which will be fixed in the upcoming RethinkDB 2.1.3 release.
It's possible that this bug was the cause of the other segmentation faults as well. We'll keep this open and observer if anything still happens after 2.1.3.

**Comment by danielmewes** [comment] 2015-09-08 20:31
We shipped a fix for https://github.com/rethinkdb/rethinkdb/issues/4769 in RethinkDB 2.1.3, which might have fixed this issue as well (though that's hard to say, and there might be something else to this one).

We strongly recommend updating to RethinkDB 2.1.3 quickly, to avoid any potential future data corruption.

**Comment by Bacto** [comment] 2015-09-14 09:49
Hi guys,

First I would like to thank you for the amazing work you do on RethinkDB! I love it!

Unfortunately I have RethinkDB 2.1.3 and I have a similar bug.

I have a cluster of 2 servers but the table I have a problem with is only on one server.
When I try to delete all the datas (~2M documents) of this table, the server crash.
There is no other access on this table during the crash.

```
r.db('test').table('maxMindBlocksIPv4').delete()
```

```
2015-09-13T15:28:19.198159460 197.522587s error: Error in src/arch/runtime/thread_pool.cc at line 359:
2015-09-13T15:28:19.264949298 197.589377s error: Segmentation fault from reading the address 0x7f018563ff76.
2015-09-13T15:28:19.302892953 197.627320s error: Backtrace:
2015-09-13T15:28:20.187061917 198.511491s error: Sun Sep 13 15:28:19 2015\n\n1: backtrace_t::backtrace_t() at ??:?\n2: format_backtrace(bool) at ??:?\n3: report_fatal_error(char const*, int, char const*, ...) at ??:?\n4: linux_thread_pool_t::fatal_signal_handler(int, siginfo_t*, void*) at ??:?\n5: /lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f02eea29340] at 0x7f02eea29340 (/lib/x86_64-linux-gnu/libpthread.so.0)\n6: /lib/x86_64-linux-gnu/libc.so.6(+0x1524d4) [0x7f02ee7a54d4] at 0x7f02ee7a54d4 (/lib/x86_64-linux-gnu/libc.so.6)\n7: leaf::garbage_collect(value_sizer_t*, leaf_node_t*, int, int*, boost::optional<int>) at ??:?\n8: leaf::move_elements(value_sizer_t*, leaf_node_t*, int, int, int, leaf_node_t*, int, int, std::vector<void const*, std::allocator<void const*> >*) at ??:?\n9: leaf::level(value_sizer_t*, int, leaf_node_t*, leaf_node_t*, btree_key_t*, std::vector<void const*, std::allocator<void const*> >*) at ??:?\n10: check_and_handle_underfull(value_sizer_t*, buf_lock_t*, buf_lock_t*, superblock_t*, btree_key_t const*, value_deleter_t const*) at ??:?\n11: apply_keyvalue_change(value_sizer_t*, keyvalue_location_t*, btree_key_t const*, repli_timestamp_t, value_deleter_t const*, key_modification_callback_t*, delete_mode_t) at ??:?\n12: kv_location_delete(keyvalue_location_t*, store_key_t const&, repli_timestamp_t, deletion_context_t const*, delete_mode_t, rdb_modification_info_t*) at ??:?\n13: rdb_replace_and_return_superblock(btree_loc_info_t const&, btree_point_replacer_t const*, deletion_context_t const*, promise_t<superblock_t*>*, rdb_modification_info_t*, profile::trace_t*) at ??:?\n14: do_a_replace_from_batched_replace(auto_drainer_t::lock_t, fifo_enforcer_sink_t*, fifo_enforcer_write_token_t const&, btree_loc_info_t const&, one_replace_t, ql::configured_limits_t const&, promise_t<superblock_t*>*, rdb_modification_report_cb_t*, bool, ql::datum_t*, profile::trace_t*, std::set<std::string, std::less<std::string>, std::allocator<std::string> >*) at ??:?\n15: std::_Function_handler<void (), std::_Bind<void (*(auto_drainer_t::lock_t, fifo_enforcer_sink_t*, fifo_enforcer_write_token_t, btree_loc_info_t, one_replace_t, ql::configured_limits_t, promise_t<superblock_t*>*, rdb_modification_report_cb_t*, bool, ql::datum_t*, profile::trace_t*, std::set<std::string, std::less<std::string>, std::allocator<std::string> >*))(auto_drainer_t::lock_t, fifo_enforcer_sink_t*, fifo_enforcer_write_token_t const&, btree_loc_info_t const&, one_replace_t, ql::configured_limits_t const&, promise_t<superblock_t*>*, rdb_modification_report_cb_t*, bool, ql::datum_t*, profile::trace_t*, std::set<std::string, std::less<std::string>, std::allocator<std::string> >*)> >::_M_invoke(std::_Any_data const&) at ??:?\n16: coro_pool_t<std::function<void ()> >::worker_run(std::function<void ()>, auto_drainer_t::lock_t) at ??:?\n17: callable_action_instance_t<std::_Bind<std::_Mem_fn<void (coro_pool_t<std::function<void ()> >::*)(std::function<void ()>, auto_drainer_t::lock_t)> (coro_pool_t<std::function<void ()> >*, std::function<void ()>, auto_drainer_t::lock_t)> >::run_action() at ??:?\n18: coro_t::run() at ??:?
2015-09-13T15:28:20.248535860 198.572963s error: Exiting.
```

An other example:
```
2015-09-13T15:50:39.321047629 1298.095524s error: Error in src/buffer_cache/alt.cc at line 718:
2015-09-13T15:50:39.360596908 1298.135073s error: Guarantee failed: [ret != repli_timestamp_t::invalid]
2015-09-13T15:50:39.398113181 1298.172589s error: Backtrace:
2015-09-13T15:50:40.017122232 1298.791599s error: Sun Sep 13 15:50:39 2015\n\n1: backtrace_t::backtrace_t() at ??:?\n2: format_backtrace(bool) at ??:?\n3: report_fatal_error(char const*, int, char const*, ...) at ??:?\n4: buf_lock_t::get_recency() const at ??:?\n5: btree_depth_first_traversal(counted_t<counted_buf_lock_and_read_t>, key_range_t const&, depth_first_traversal_callback_t*, access_t, direction_t, btree_key_t const*, btree_key_t const*, signal_t*) at ??:?\n6: btree_depth_first_traversal(counted_t<counted_buf_lock_and_read_t>, key_range_t const&, depth_first_traversal_callback_t*, access_t, direction_t, btree_key_t const*, btree_key_t const*, signal_t*) at ??:?\n7: btree_depth_first_traversal(counted_t<counted_buf_lock_and_read_t>, key_range_t const&, depth_first_traversal_callback_t*, access_t, direction_t, btree_key_t const*, btree_key_t const*, signal_t*) at ??:?\n8: btree_depth_first_traversal(counted_t<counted_buf_lock_and_read_t>, key_range_t const&, depth_first_traversal_callback_t*, access_t, direction_t, btree_key_t const*, btree_key_t const*, signal_t*) at ??:?\n9: btree_depth_first_traversal(superblock_t*, key_range_t const&, depth_first_traversal_callback_t*, access_t, direction_t, release_superblock_t, signal_t*) at ??:?\n10: btree_concurrent_traversal(superblock_t*, key_range_t const&, concurrent_traversal_callback_t*, direction_t, release_superblock_t) at ??:?\n11: rdb_rget_slice(btree_slice_t*, key_range_t const&, superblock_t*, ql::env_t*, ql::batchspec_t const&, std::vector<boost::variant<ql::map_wire_func_t, ql::group_wire_func_t, ql::filter_wire_func_t, ql::concatmap_wire_func_t, ql::distinct_wire_func_t, ql::zip_wire_func_t, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<ql::map_wire_func_t, ql::group_wire_func_t, ql::filter_wire_func_t, ql::concatmap_wire_func_t, ql::distinct_wire_func_t, ql::zip_wire_func_t, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > const&, boost::optional<boost::variant<ql::count_wire_func_t, ql::sum_wire_func_t, ql::avg_wire_func_t, ql::min_wire_func_t, ql::max_wire_func_t, ql::reduce_wire_func_t, ql::limit_read_t, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > const&, sorting_t, rget_read_response_t*, release_superblock_t) at ??:?\n12: do_read(ql::env_t*, store_t*, btree_slice_t*, real_superblock_t*, rget_read_t const&, rget_read_response_t*, release_superblock_t) at ??:?\n13: rdb_read_visitor_t::operator()(rget_read_t const&) at ??:?\n14: store_t::protocol_read(read_t const&, read_response_t*, real_superblock_t*, signal_t*) at ??:?\n15: store_t::read(read_t const&, read_response_t*, read_token_t*, signal_t*) at ??:?\n16: replica_t::do_read(read_t const&, state_timestamp_t, signal_t*, read_response_t*) at ??:?\n17: primary_dispatcher_t::read(read_t const&, fifo_enforcer_sink_t::exit_read_t*, order_token_t, signal_t*, read_response_t*) at ??:?\n18: primary_execution_t::on_read(read_t const&, fifo_enforcer_sink_t::exit_read_t*, order_token_t, signal_t*, read_response_t*, admin_err_t*) at ??:?\n19: primary_query_server_t::client_t::perform_request(boost::variant<primary_query_bcard_t::read_request_t, primary_query_bcard_t::write_request_t, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, signal_t*) at ??:?\n20: multi_client_server_t<boost::variant<primary_query_bcard_t::read_request_t, primary_query_bcard_t::write_request_t, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, primary_query_server_t*, primary_query_server_t::client_t>::client_t::on_request(signal_t*, boost::variant<primary_query_bcard_t::read_request_t, primary_query_bcard_t::write_request_t, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) at ??:?\n21: mailbox_t<void (boost::variant<primary_query_bcard_t::read_request_t, primary_query_bcard_t::write_request_t, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>)>::read_impl_t::read(read_stream_t*, signal_t*) at ??:?\n22: /usr/bin/rethinkdb() [0x944a02] at 0x944a02 ()\n23: coro_t::run() at ??:?
2015-09-13T15:50:40.069366756 1298.843842s error: Exiting.
```

r.db('test').table('maxMindBlocksIPv4').config():
```
{
"db":  "test" ,
"durability":  "hard" ,
"id":  "5f369b90-ab69-4b8e-b2e1-a8d4209477c8" ,
"indexes": [
"toDelete"
] ,
"name":  "maxMindBlocksIPv4" ,
"primary_key":  "id" ,
"shards": [
{
"nonvoting_replicas": [ ],
"primary_replica":  "s1" ,
"replicas": [
"s1"
]
}
] ,
"write_acks":  "majority"
}
```

rethinkdb --version
```
rethinkdb 2.1.3~0trusty (GCC 4.8.2)
```

I run the server on Linux 3.16.3, Ubuntu 14.04.1 and had install RethinkDB from deb packages.

If you need more informations or a copy of the table, just let me know.

Thanks,
Adrien

**Comment by danielmewes** [comment] 2015-09-14 22:33
@Bacto please see my comment in the other issue https://github.com/rethinkdb/rethinkdb/issues/4769#issuecomment-140224309 . I think things might be an after-effect of the problem described over there. I'd like to take a look at the data file first to confirm this though.

**Comment by l3x** [comment] 2015-09-27 00:16
```
Version: rethinkdb 2.1.4 (CLANG 7.0.0 (clang-700.0.72))
error: Error in src/arch/runtime/thread_pool.cc at line 359:
error: Segmentation fault from reading the address 0x8.
```

Occurs when attempting to ".update" data.  Reads seem to work fine.

System: OSX 10.10.5

**Comment by danielmewes** [comment] 2015-09-28 17:33
@l3x are you using any changefeeds on `orderBy.limit` queries? Or any other changefeeds?
Is the crash reproducible or did this only happen once?

**Comment by mariostallone** [comment] 2015-10-25 14:52
I had a similar crash today.

I have a cluster of 3 machines. The table that I'm using has 3 shards with 2 replicas each.

Two of the machines had died. I found logs pertaining to the crash on one of the machines.

These were the last set of logs from the first machine (rdb1)

```
2015-10-25T19:51:27.502841709 102121.439010s error: Heartbeat timeout, killing connection to peer [::ffff:<IP RDB2>]:40188
2015-10-25T19:51:27.502863749 102121.439029s error: Heartbeat timeout, killing connection to peer [::ffff:<IP RDB2>]:40188
2015-10-25T19:51:27.503254817 102121.439420s error: Heartbeat timeout, killing connection to peer [::ffff:<IP RDB2>]:40188
2015-10-25T19:51:27.503333625 102121.439499s notice: Disconnected from server "rethinkdb3" <hash>
2015-10-25T19:51:27.503964712 102121.440130s error: Heartbeat timeout, killing connection to peer [::ffff:<IP RDB2>]:40188
2015-10-25T19:51:27.504183276 102121.440348s error: Heartbeat timeout, killing connection to peer [::ffff:<IP RDB2>]:40188
2015-10-25T19:51:27.504380053 102121.440545s error: Heartbeat timeout, killing connection to peer [::ffff:<IP RDB2>]:40188
2015-10-25T19:51:35.677498523 102129.613664s notice: Disconnected from server "rethinkdb2" <hash>
2015-10-25T19:51:38.248917423 102132.185083s error: Error in src/arch/runtime/thread_pool.cc at line 359:
2015-10-25T19:51:38.249094215 102132.185259s error: Segmentation fault from reading the address 0x3f.
2015-10-25T19:51:38.249111636 102132.185277s error: Backtrace:
```

**Comment by danielmewes** [comment] 2015-10-26 17:36
@mariostallone Was this on 2.1.4 or 2.1.5?

**Comment by mariostallone** [comment] 2015-10-27 04:34
@danielmewes This was on 2.1.4 as well... I'll look at upgrading to 2.1.5...

**Comment by danielmewes** [comment] 2015-11-17 01:47
We've fixed a bunch of issues that could lead to segmentation faults in the last few releases (including a few more in RethinkDB 2.2.0).
I'm going to close this, but I'd like to encourage everyone to open a new issue if you see a segmentation fault with a current version.

**Closed by danielmewes** 2015-11-17 01:47 UTC
Labels: pr:high, tp:bug
