### ISSUE TITLE
Add an optarg to `getAll` that preserves ordering.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#6036] opened 2016-08-06 19:43 UTC
For `union`, we let people decide whether to have the order of the arguments affect the order of the results, but for `getAll` we don't.

**Comment by danielmewes** [comment] 2016-08-08 18:17
Duplicate of https://github.com/rethinkdb/rethinkdb/issues/5187 .

Did this come up for a particular use case?

**Closed by danielmewes** 2016-08-08 18:17 UTC
Labels: tp:ReQL_proposal
