### ISSUE TITLE
.between returns everything 

### ISSUE THREAD

**Issue by velocityzen** [rethinkdb/rethinkdb#5287] opened 2016-01-14 19:35 UTC
Initial state:
```js
r.table('test').insert([
 { id: ['a', 'b'] },
 { id: ['b', 'a'] }
])
```

this query works fine:
```js
r.table('test').between(['a', r.minval], ['a', r.maxval])
```

But this one returns the whole table:
```js
r.table('test').between([r.minval, 'a'], [r.maxval, 'a'])
```
Expected:  `{ id: ['b', 'a'] }`

**Comment by mlucy** [comment] 2016-01-14 19:38
Hi @velocityzen,

That's the expected behavior.  The way arrays sort, `[r.minval, 'a']` is less than both of the documents you inserted, and `[r.maxval, 'a']` is greater than both of the documents.

Closing since this isn't a bug, but feel free to ask more questions here.

**Closed by mlucy** 2016-01-14 19:38 UTC

**Comment by velocityzen** [comment] 2016-01-26 07:05
@mlucy got it. thanks.
