### ISSUE TITLE
Better handling of table name conflicts

### ISSUE THREAD

**Issue by niieani** [rethinkdb/rethinkdb#6123] opened 2016-09-26 17:55 UTC
An issue and a feature request:

**Enhancement**: I have a database initialization script which gets run by a micro-service before it starts (creating tables, indexes, etc.). The micro-service is designed to be run in the cloud, i.e. it's deployed to many servers at once. If I add a new table to the initialization script and deploy, sometimes the table is created many times, resulting in conflicts. As a workaround I can deploy the initialization on one server only, but it would be good if there was some built-in logic that merged tables with the same name that were created on different shards. 
For extra safety, that could maybe only happen if neither table duplicate contains any of the documents yet (i.e. it's empty).

**Bug**: When there are two tables with the same name (e.g. after being created simultaneously on a different server) and you try to delete just one of them from the WebUI, both get deleted. :(

**Comment by VeXocide** [comment] 2016-09-26 21:43
Hi @niieani, I'm going to close this as a duplicate of #4898 which should take care of this.

**Closed by VeXocide** 2016-09-26 21:43 UTC
