### ISSUE TITLE
crash in 2.3.4: Guarantee failed: [machinery->can_be_removed()]

### ISSUE THREAD

**Issue by raarts** [rethinkdb/rethinkdb#5993] opened 2016-07-23 14:22 UTC
I had rethinkdb running for a while on my OSX 10.11.6 (using horizon), I pressed Ctrl-C, and got the following output:

```
Recursively removing directory /Users/raarts/work/react-todo-list/rethinkdb_data/tmp
Initializing directory /Users/raarts/work/react-todo-list/rethinkdb_data
Running rethinkdb 2.3.4 (CLANG 7.3.0 (clang-703.0.31))...
Running on Darwin 15.6.0 x86_64
Loading data from directory /Users/raarts/work/react-todo-list/rethinkdb_data
warn: Cache size does not leave much memory for server and query overhead (available memory: 1003 MB).
warn: Cache size is very low and may impact performance.
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on cluster addresses: 127.0.0.1, ::1
Listening on driver addresses: 127.0.0.1, ::1
Listening on http addresses: 127.0.0.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "Rons_Air_lan_m0j" c8b6ccc3-8f70-4cd7-9839-a4e65b5dd9e6
^CServer got SIGINT from pid 614, uid 501; shutting down...
Shutting down client connections...
All client connections closed.
Shutting down storage engine... (This may take a while if you had a lot of unflushed data in the writeback cache.)
Version: rethinkdb 2.3.4 (CLANG 7.3.0 (clang-703.0.31))
error: Error in src/rdb_protocol/artificial_table/cfeed_backend.cc at line 122:
error: Guarantee failed: [machinery->can_be_removed()]
error: Backtrace:
error: Sat Jul 23 16:17:41 2016

       1 [0x108aa5b34]: 0   rethinkdb                           0x0000000108aa5b34 _Z19rethinkdb_backtracePPvi + 132 at 0x108aa5b34 ()
       2 [0x108689d88]: 0   rethinkdb                           0x0000000108689d88 _ZN11backtrace_tC2Ev + 80 at 0x108689d88 ()
       3 [0x10868ae99]: 0   rethinkdb                           0x000000010868ae99 _ZN26lazy_backtrace_formatter_tC2Ev + 39 at 0x10868ae99 ()
       4 [0x108689a16]: 0   rethinkdb                           0x0000000108689a16 _Z16format_backtraceb + 25 at 0x108689a16 ()
       5 [0x1088abd93]: 0   rethinkdb                           0x00000001088abd93 _Z18report_fatal_errorPKciS0_z + 406 at 0x1088abd93 ()
       6 [0x1088e6bac]: 0   rethinkdb                           0x00000001088e6bac _ZN32cfeed_artificial_table_backend_t28begin_changefeed_destructionEv + 152 at 0x1088e6bac ()
       7 [0x1087ced53]: 0   rethinkdb                           0x00000001087ced53 _ZN39table_config_artificial_table_backend_tD2Ev + 25 at 0x1087ced53 ()
       8 [0x1087cee14]: 0   rethinkdb                           0x00000001087cee14 _ZN39table_config_artificial_table_backend_tD0Ev + 14 at 0x1087cee14 ()
       9 [0x10872a565]: 0   rethinkdb                           0x000000010872a565 _ZN25admin_artificial_tables_tD2Ev + 245 at 0x10872a565 ()
       10 [0x108727464]: 0   rethinkdb                           0x0000000108727464 _Z8do_serveP14io_backender_tbRK11base_path_tP15metadata_file_tRK12serve_info_tP16os_signal_cond_tRKNSt3__112basic_stringIcNSB_11char_traitsIcEENSB_9allocatorIcEEEE + 11424 at 0x108727464 ()
       11 [0x108728334]: 0   rethinkdb                           0x0000000108728334 _Z5serveP14io_backender_tRK11base_path_tP15metadata_file_tRK12serve_info_tP16os_signal_cond_t + 99 at 0x108728334 ()
       12 [0x108707316]: 0   rethinkdb                           0x0000000108707316 _Z19run_rethinkdb_serveRK11base_path_tP12serve_info_tRKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE21file_direct_io_mode_tiRKN5boost8optionalINSF_IyEEEEPK11server_id_tPK25server_config_versioned_tPK30cluster_semilattice_metadata_tP16directory_lock_tPb + 2365 at 0x108707316 ()
       13 [0x108707afd]: 0   rethinkdb                           0x0000000108707afd _Z23run_rethinkdb_porcelainRK11base_path_tRK13name_string_tRKNSt3__13setIS2_NS5_4lessIS2_EENS5_9allocatorIS2_EEEERKNS5_12basic_stringIcNS5_11char_traitsIcEENS9_IcEEEE21file_direct_io_mode_tiRKN5boost8optionalINSN_IyEEEEbP12serve_info_tP16directory_lock_tPb + 1238 at 0x108707afd ()
       14 [0x10871c808]: 0   rethinkdb                           0x000000010871c808 _ZNSt3__110__function6__funcINS_6__bindIPFvRK11base_path_tRK13name_string_tRKNS_3setIS6_NS_4lessIS6_EENS_9allocatorIS6_EEEERKNS_12basic_stringIcNS_11char_traitsIcEENSC_IcEEEE21file_direct_io_mode_tiRKN5boost8optionalINSQ_IyEEEEbP12serve_info_tP16directory_lock_tPbEJRS3_RS6_RSE_RSL_RKSO_RiRSS_RbSW_SY_SZ_EEENSC_IS1B_EEFvvEEclEv + 100 at 0x10871c808 ()
       15 [0x108686401]: 0   rethinkdb                           0x0000000108686401 _ZN9starter_t11run_wrapperERKNSt3__18functionIFvvEEE + 17 at 0x108686401 ()
       16 [0x108682d43]: 0   rethinkdb                           0x0000000108682d43 _ZN6coro_t3runEv + 63 at 0x108682d43 ()
error: Exiting.
Trace/BPT trap: 5
```

**Comment by danielmewes** [comment] 2016-07-25 17:59
Thanks for the bug report @raarts . This looks like it's the same as https://github.com/rethinkdb/rethinkdb/issues/5332 . We don't know what causes it yet, but it seems to be some (relatively rare) race condition on shutdown.

Closing this as a duplicate of https://github.com/rethinkdb/rethinkdb/issues/5332 .

**Closed by danielmewes** 2016-07-25 17:59 UTC
