### ISSUE TITLE
Using SSL tunnels with Blue-Green Deployment

### ISSUE THREAD

**Issue by shastingspod** [rethinkdb/rethinkdb#4102] opened 2015-04-23 17:39 UTC
We are trying to set up blue-green deployment for updates to our RethinkDB cluster.  For regulatory reasons, we need all intracluster traffic to be encrypted.  We are using stunnel to encrypt traffic between the nodes within a cluster, which works great when we set up a single cluster and know all the configuration details when launching stunnel and RethinkDB.  However, we're not sure the best way to make it work when trying to replicate from blue-to-green during an update.

Specifically, consider the following cluster arrangment:
    We start up 3 amazon AWS servers.  Install rethinkdb and stunnel on all of them.  We then modify rethinkdb and stunnel to communicate in and out through seperate ports (i.e. server 1 will talk to server 2 through port A and listen to server 2 on port B)(see figure).  This cluster will be considered our Blue cluster.  Each node in the cluster has 2*(n) connections. Now, for example, say that Blue is out of date.  Since we don't want our servers to have any down time, we start up another cluster and call it our Green cluster.  Now we want to move the data over from Blue to Green using encripted channels.  Ideally we would like to connect one node from each cluster via stunnel and replicate across that one connection.  However, when that connection is made, RethinkDB recognizes that there are nodes that aren't connected accross the two clusters.  This prevents the replication process.  The reason for replication rather than just pulling down the data from the Blue cluster and uploading it to the Green cluster is because we would like there to be zero downtime between shutting down blue and migrating to green.

Is there a way you recommend to do this without restarting the nodes?

Figure:
In this chart we would like to connect the two clusters through one connection.  Since every stunnel connection uses a different port, it would be cumbersome to connect all 6 nodes.  Ideally this connection would allow us to replicate from Blue (indicated by a, b, c in blue) to Green (indicated by 1, 2, 3 in green).  After the replication process is finished we could then cut ties with the Blue cluster and use our newly created Green cluster.

![rdb_bluegreen_stunnel](https://cloud.githubusercontent.com/assets/7713695/7303290/a1bc3e9e-e9bd-11e4-960f-0d7094d40199.png)

**Comment by danielmewes** [comment] 2015-04-23 23:54
Hi @shastingspod, at the moment establishing full connectivity between allservers is the only way I can think of to do this (@timmaxw any other ideas?).

We're currently working on a new clustering subsystem that will allow configuring and replicating tables while some servers are absent (this will ship with RethinkDB 2.2). However it will still require direct connectivity between the backfill sender and backfill receiver.
If you make sure that the primaries for all tables in the blue cluster are on server A, and you add a new replica for these tables on server 1 in the green cluster, the red connection between servers A and 1 might be sufficient (@timmaxw do you think this would work?). However this isn't really a supported configuration. RethinkDB isn't specifically build to deal with non-transitive connectivity like in this case.

**Comment by danielmewes** [comment] 2015-05-02 08:24
Another option might be to copy the data from the blue to the green cluster through the `rethinkdb export` and rethinkdb import` tools. This has lower consistency guarantees than backfilling if the data is being written to while `rethinkdb export` is running, but wouldn't require taking down the blue cluster while copying out the data. By lower consistency guarantees I mean that it might miss some of the changes that happen during the export but have others that happen after those.

As a third option, I'd suggest using LVM or file system snapshots (for example with BTRFS). If you make sure that server A is an up to date replica for all tables at a given moment, you can just take a file system / or LVM snapshot of the data partition. Then you can copy over the rethinkdb data directory from the snapshot to server 1 in the green cluster without taking the blue cluster down. In this scenario you should make sure that the green and blue cluster never connect to each other, or you will get issues with duplicate server IDs.

**Comment by danielmewes** [comment] 2015-05-02 08:24
Closing because it's not a bug, but feel free to ask follow up questions @shastingspod

**Closed by danielmewes** 2015-05-02 08:24 UTC

**Comment by shastingspod** [comment] 2015-05-04 14:40
Thanks for your help @danielmewes.  I've been looking over the issues, I see #3151 and #3158 which will encrypt intracluster communications.  Will this feature automatically create encrypted connections to all existing nodes when new nodes are added?  That would effectively solve our problem. Is this feature scheduled in any near-future releases?

**Comment by danielmewes** [comment] 2015-05-05 20:52
@shastingspod We haven't determined the details of how we're going to implement encrypted intracluster connections yet, but I think it will work as your describe.

The feature is planned for one of the upcoming releases, but not scheduled for a specific one yet.
