### ISSUE TITLE
Building v2.2.6 fails when using pre-installed NPM

### ISSUE THREAD

**Issue by fkollmann** [rethinkdb/rethinkdb#5594] opened 2016-04-04 00:15 UTC
**Error**

Command: `/usr/bin/npm --userconfig /mnt/resource/rethinkdb_build/rethinkdb-2.2.6/mk/support/config/npm.conf --cache /mnt/resource/rethinkdb_build/rethinkdb-2.2.6/external/npm_cache-E5b39eIe --no-registry install /mnt/resource/rethinkdb_build/rethinkdb-2.2.6/external/admin-deps_2.0.3`

NPM error message: `registry URL is required`

**Workaround**

Allow NPM to download packages online, by calling:

`sed -i -r 's/--no-registry *//g' mk/support/pkg/npm-pkg.inc`

This will patch the file and disable offline-mode for NPM.

**Build Log**

```
    [415/419] BUILD admin-deps_2.0.3
02:11:39Info
+ in_dir /mnt/resource/rethinkdb_build/rethinkdb-2.2.6/build/external/admin-deps_2.0.3 npm --no-registry install /mnt/resource/rethinkdb_build/rethinkdb-2.2.6/external/admin-deps_2.0.3
02:11:39Info
+ local dir=/mnt/resource/rethinkdb_build/rethinkdb-2.2.6/build/external/admin-deps_2.0.3
02:11:39Info
+ shift
02:11:39Info
+ cd /mnt/resource/rethinkdb_build/rethinkdb-2.2.6/build/external/admin-deps_2.0.3
02:11:39Info
+ npm --no-registry install /mnt/resource/rethinkdb_build/rethinkdb-2.2.6/external/admin-deps_2.0.3
02:11:39Info
++ mktemp -d /mnt/resource/rethinkdb_build/rethinkdb-2.2.6/external/npm_cache-XXXXXXXX
02:11:39Info
+ cache_dir=/mnt/resource/rethinkdb_build/rethinkdb-2.2.6/external/npm_cache-E5b39eIe
02:11:39Info
+ /usr/bin/npm --userconfig /mnt/resource/rethinkdb_build/rethinkdb-2.2.6/mk/support/config/npm.conf --cache /mnt/resource/rethinkdb_build/rethinkdb-2.2.6/external/npm_cache-E5b39eIe --no-registry install /mnt/resource/rethinkdb_build/rethinkdb-2.2.6/external/admin-deps_2.0.3
02:11:39Info
npm ERR! Linux 3.12.51-52.39-default
02:11:39Info
npm ERR! argv "/opt/nodejs/bin/node" "/usr/bin/npm" "--userconfig" "/mnt/resource/rethinkdb_build/rethinkdb-2.2.6/mk/support/config/npm.conf" "--cache" "/mnt/resource/rethinkdb_build/rethinkdb-2.2.6/external/npm_cache-E5b39eIe" "--no-registry" "install" "/mnt/resource/rethinkdb_build/rethinkdb-2.2.6/external/admin-deps_2.0.3"
02:11:39Info
npm ERR! node v4.4.1
02:11:39Info
npm ERR! npm  v3.8.5
02:11:39Error
make[1]: *** [build/external/admin-deps_2.0.3/bin/gulp] Error 1
02:11:39Info
npm ERR! registry URL is required
02:11:39Info
npm ERR! 
02:11:39Info
npm ERR! If you need help, you may report this error at:
02:11:39Info
npm ERR!     <https://github.com/npm/npm/issues>
02:11:39Error
make[1]: *** Waiting for unfinished jobs....
02:11:39Info
npm ERR! Please include the following file with any support request:
02:11:39Info
npm ERR!     /mnt/resource/rethinkdb_build/rethinkdb-2.2.6/build/external/admin-deps_2.0.3/npm-debug.log
02:11:39Info
Full error log: ./build/external/admin-deps_2.0.3_install.log
02:11:39Info
mk/support/build.mk:121: recipe for target 'build/external/admin-deps_2.0.3/bin/gulp' failed
```

**Comment by danielmewes** [comment] 2016-04-05 16:52
@larkost have you seen this one before?

@fkollmann As a work-around, I recommend calling `configure` with the `--fetch npm` flag.

**Comment by larkost** [comment] 2016-04-05 20:22
This is a dupe of #5230, and is about the changing options to `npm`, specially `--no-registry` vs. `--registry http://disabled-registry`.

**Closed by larkost** 2016-04-05 20:22 UTC
Labels: cp:build
