### ISSUE TITLE
Attempt to acquire an `auto_drainer_t` lock that's already pulsed.

### ISSUE THREAD

**Issue by VeXocide** [rethinkdb/rethinkdb#3920] opened 2015-03-10 23:47 UTC
In shutting down the following `guarantee` triggered.

```
#0  auto_drainer_t::lock_t::lock_t (this=0x7f5109956800, p=0x7f510d856b48) at src/concurrency/auto_drainer.cc:22
#1  0x0000000001dd59c3 in ql::changefeed::client_t::maybe_remove_feed (this=0x7f510d856ad0, uuid=...) at src/rdb_protocol/changefeed.cc:2495
#2  0x0000000001de055e in ql::changefeed::real_feed_t::maybe_remove_feed (this=0x7f50f83ecc00) at src/rdb_protocol/changefeed.cc:1186
#3  0x0000000001dd412c in ql::changefeed::feed_t::del_sub_with_lock(rwlock_t *, std::function<unsigned long ()> &) (this=0x7f50f83ecc00, rwlock=0x7f50f83eccd8, f=...) at src/rdb_protocol/changefeed.cc:2217
#4  0x0000000001dd44ca in ql::changefeed::feed_t::del_limit_sub (this=0x7f50f83ecc00, sub=0x7f5109841000, sub_uuid=...) at src/rdb_protocol/changefeed.cc:2275
#5  0x0000000001df0582 in std::_Mem_fn<void (ql::changefeed::feed_t::*)(ql::changefeed::limit_sub_t*, uuid_u const&)>::operator() (this=0x7f510980eee0, __object=0x7f50f83ecc00, __args=..., __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/functional:550
#6  0x0000000001df04cd in std::__call<void, , 0, 1, 2>(<unknown type in /home/ssd3/vexocide/rethinkdb/build/debug_clang/rethinkdb, CU 0x4464074, DIE 0x4552a53>) (this=0x7f510980eee0, 
    __args=<unknown type in /home/ssd3/vexocide/rethinkdb/build/debug_clang/rethinkdb, CU 0x4464074, DIE 0x4552a53>) at /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/functional:1145
#7  0x0000000001df0426 in std::operator()<void> (this=0x7f510980eee0) at /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/functional:1203
#8  0x0000000001defe8d in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (ql::changefeed::feed_t::*)(ql::changefeed::limit_sub_t *, const uuid_u &)> (ql::changefeed::feed_t *, ql::changefeed::limit_sub_t *, uuid_u)> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/functional:1777
#9  0x000000000150c7ae in std::function<void ()>::operator()(void) const (this=0x7f5109956c68) at /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/functional:2160
#10 0x0000000001dd3961 in ql::changefeed::subscription_t::destructor_cleanup(std::function<void ()> &) (this=0x7f5109841000, del_sub=...) at src/rdb_protocol/changefeed.cc:2163
#11 0x0000000001def7c9 in ql::changefeed::limit_sub_t::~limit_sub_t (this=0x7f5109841000) at src/rdb_protocol/changefeed.cc:1553
#12 0x0000000001de6125 in ql::changefeed::limit_sub_t::~limit_sub_t (this=0x7f5109841000) at src/rdb_protocol/changefeed.cc:1552
#13 0x0000000001de6149 in ql::changefeed::limit_sub_t::~limit_sub_t (this=0x7f5109841000) at src/rdb_protocol/changefeed.cc:1552
#14 0x0000000001de373f in scoped_ptr_t<ql::changefeed::subscription_t>::reset (this=0x7f5109979320) at ./src/containers/scoped.hpp:72
#15 0x0000000001de36e1 in scoped_ptr_t<ql::changefeed::subscription_t>::~scoped_ptr_t (this=0x7f5109979320) at ./src/containers/scoped.hpp:34
#16 0x0000000001de0015 in scoped_ptr_t<ql::changefeed::subscription_t>::~scoped_ptr_t (this=0x7f5109979320) at ./src/containers/scoped.hpp:33
#17 0x0000000001de1c46 in ql::changefeed::stream_t::~stream_t (this=0x7f51099792a0) at src/rdb_protocol/changefeed.cc:2006
#18 0x0000000001de1995 in ql::changefeed::stream_t::~stream_t (this=0x7f51099792a0) at src/rdb_protocol/changefeed.cc:2006
#19 0x0000000001de19b9 in ql::changefeed::stream_t::~stream_t (this=0x7f51099792a0) at src/rdb_protocol/changefeed.cc:2006
#20 0x000000000184eb03 in counted_release<ql::datum_stream_t> (p=0x7f51099792b8) at ./src/containers/counted.hpp:189
#21 0x000000000184ea11 in counted_t<ql::datum_stream_t>::~counted_t (this=0x7f51098536e0) at ./src/containers/counted.hpp:60
#22 0x0000000001849c85 in counted_t<ql::datum_stream_t>::~counted_t (this=0x7f51098536e0) at ./src/containers/counted.hpp:59
#23 0x0000000001b63599 in ql::query_cache_t::entry_t::~entry_t (this=0x7f5109853640) at src/rdb_protocol/query_cache.cc:356
#24 0x0000000001b61f7a in ql::query_cache_t::async_destroy_entry (entry=0x7f5109853640) at src/rdb_protocol/query_cache.cc:183
#25 0x0000000001b65823 in std::_Bind<void (*(ql::query_cache_t::entry_t *))(ql::query_cache_t::entry_t *)>::__call<void, , 0>(<unknown type in /home/ssd3/vexocide/rethinkdb/build/debug_clang/rethinkdb, CU 0x313c8dd, DIE 0x31a513a>) (
    this=0x7f51098479f8, __args=<unknown type in /home/ssd3/vexocide/rethinkdb/build/debug_clang/rethinkdb, CU 0x313c8dd, DIE 0x31a513a>) at /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/functional:1145
#26 0x0000000001b657d6 in std::_Bind<void (*(ql::query_cache_t::entry_t *))(ql::query_cache_t::entry_t *)>::operator()<void>(void) (this=0x7f51098479f8) at /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/functional:1203
#27 0x0000000001b6572c in callable_action_instance_t<std::_Bind<void (*(ql::query_cache_t::entry_t *))(ql::query_cache_t::entry_t *)> >::run_action(void) (this=0x7f51098479f0) at ./src/arch/runtime/callable_action.hpp:31
#28 0x000000000150dcc2 in callable_action_wrapper_t::run (this=0x7f51098479e0) at src/arch/runtime/runtime_utils.cc:42
#29 0x0000000001515c97 in coro_t::run () at src/arch/runtime/coroutines.cc:204
#30 0x0000000000000000 in ?? ()
```

A copy of the executable and core file is in `newton:/home/vexocide/mlucy/3920`.

**Comment by mlucy** [comment] 2015-03-10 23:49
@VeXocide -- Thanks!  Is this reproducible enough that if I give you a branch you can tell whether or not it went away?

**Comment by VeXocide** [comment] 2015-03-10 23:50
@mlucy -- let me run through the test suite again

**Comment by VeXocide** [comment] 2015-03-11 00:00
@mlucy -- I wasn't able to reproduce it in a second run, so that's a no unfortunately

**Comment by mlucy** [comment] 2015-03-11 00:13
Hm, well that's unfortunate again.  A fix is in CR 2707 by @VeXocide .

**Comment by mlucy** [comment] 2015-03-11 00:14
(Fortunately this was a straightforward fix; in both the case that crashed and another case that looked equally sketchy, we were acquiring a lock that was already safely held by our caller.  We now instead just pass the lock down to prove we have it.)

**Comment by mlucy** [comment] 2015-03-11 00:35
In next and 2.0.x.

**Comment by mlucy** [comment] 2015-03-11 00:35
(@vexocide said he'd try to run some more shutting down tests since it seems to be a fruitful source of bugs.)

**Closed by mlucy** 2015-03-11 00:35 UTC
Labels: tp:bug
