### ISSUE TITLE
How can I generate RethinkDB UUIDv5 on the client-side?

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#5127] opened 2015-11-21 15:25 UTC

**Comment by VeXocide** [comment] 2015-11-21 22:27
I've described this for Python at https://github.com/rethinkdb/docs/issues/953, the important thing to note is the namespace we use, namely `91461c99-f89d-49d2-af96-d8e2e14e9b58`. There seems to be a library available for most languages that all work in a similar fashion.

I'll close this issue as it's not a bug, but please feel free to ask more questions here.

**Closed by VeXocide** 2015-11-21 22:27 UTC

**Comment by thelinuxlich** [comment] 2015-11-22 01:20
@VeXocide so basically is sha1("91461c99-f89d-49d2-af96-d8e2e14e9b58" + key) ?

**Comment by VeXocide** [comment] 2015-11-22 02:53
Essentially that's the idea, there's a tad more to an actual implementation though, let me explain. I'm going to use Python here as that's what I'm familiar with but this will obviously work with any language that has basic string manipulation and a SHA-1 implementation. The following is what we're going to replicate.

```py
>>> import uuid
>>> uuid.uuid5(uuid.UUID('91461c99-f89d-49d2-af96-d8e2e14e9b58'), 'foo')
UUID('aa32a020-8c2d-5ff1-823b-ad3fa5d067eb')
```

First off we must convert our namespace UUID to bytes, that gives us the following.
```py
>>> import uuid
>>> uuid.UUID("91461c99-f89d-49d2-af96-d8e2e14e9b58").bytes
'\x91F\x1c\x99\xf8\x9dI\xd2\xaf\x96\xd8\xe2\xe1N\x9bX'
```
Note that from a UUID perspective they're equivalent, just a different representation, and going forward you could simply use this series of bytes.

Next we use our SHA-1 implementation, in Python this is `hashlib.sha1`, and string essentially as you mentioned.
```py
>>> import hashlib
>>> hashlib.sha1('\x91F\x1c\x99\xf8\x9dI\xd2\xaf\x96\xd8\xe2\xe1N\x9bX' + 'foo').digest()
'\xaa2\xa0 \x8c-/\xf1\xc2;\xad?\xa5\xd0g\xeb\xac\r\xab\xb5'
```

This gives us the basis of our new UUID, but note that it's too long, so we simply take the first 16 bytes.
```py
>>> len('\x91F\x1c\x99\xf8\x9dI\xd2\xaf\x96\xd8\xe2\xe1N\x9bX')
16
>>> len('\xaa2\xa0 \x8c-/\xf1\xc2;\xad?\xa5\xd0g\xeb\xac\r\xab\xb5')
20
>>> '\xaa2\xa0 \x8c-/\xf1\xc2;\xad?\xa5\xd0g\xeb\xac\r\xab\xb5'[:16]
'\xaa2\xa0 \x8c-/\xf1\xc2;\xad?\xa5\xd0g\xeb'
>>> len('\xaa2\xa0 \x8c-/\xf1\xc2;\xad?\xa5\xd0g\xeb')
16
```

Next we must incorporate the variant and version of the UUID into this series of bytes, https://en.wikipedia.org/wiki/Universally_unique_identifier#Variants_and_versions nicely explains this. Note that since Python won't allow me to do bitwise operations on the series of bytes I convert it to a list of integers, this might not be necessary in other languages.
```py
>>> bytes = map(ord, '\xaa2\xa0 \x8c-/\xf1\xc2;\xad?\xa5\xd0g\xeb')
>>> bytes[6] = (bytes[6] & 0x0f) | 0x50
>>> bytes[8] = (bytes[8] & 0x3f) | 0x80
>>> ''.join(map(chr, bytes))
'\xaa2\xa0 \x8c-_\xf1\x82;\xad?\xa5\xd0g\xeb'
```

Awesome, now we're basically there, all we must do is convert this to the canonical representation.
```py
>>> uuid.UUID(bytes='\xaa2\xa0 \x8c-_\xf1\x82;\xad?\xa5\xd0g\xeb')
UUID('aa32a020-8c2d-5ff1-823b-ad3fa5d067eb')
```

The functions that convert between the canonical and byte representations of a UUID are left as an exercise for the user, but you can peek in https://github.com/rethinkdb/rethinkdb/blob/next/src/containers/uuid.cc for hints. Last but not least, this is all described in https://tools.ietf.org/html/rfc4122.
