### ISSUE TITLE
"Query terminated by an unknown cause" when running on Windows

### ISSUE THREAD

**Issue by NameOfTheDragon** [rethinkdb/rethinkdb#5564] opened 2016-03-25 16:47 UTC
See also http://stackoverflow.com/questions/36211224/why-is-my-rethinkdb-update-query-terminated-by-an-unknown-cause

When I run this query:

```
    r.db('geodata').table('os50kgazetteer')
      .getAll(false, { index: 'has_geolocation' })
      .update({'geolocation': r.point(r.row('Coordinates')(0),r.row('Coordinates')(1))}
    )

```
after several minutes of activity (a lot of reads followed by some writes) I receive the following error message:

<pre>
e: Query terminated by an unknown cause in:
r.db("geodata").table("os50kgazetteer").getAll(false, {"index": "has_geolocation"}).update({"geolocation": r.point(r.row("Coordinates")(0), r.row("Coordinates")(1))})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</pre>

Some of the documents get updated, but only a few thousand out of the 250K+ in the table.

I would have thought it should always be possible to know the cause of an error - that seems sloppy to me and makes the error message essentially worthless.

Documents in the table look like this (this is one that has been correctly updated, as it has the `geolocation` field):

[![Screen shot showing JSON document][1]][1]

Is there anything obviously wrong with this query?

NOTE: I'm running the preview release of the Windows version of RethinkDB (2.2.4-windows-alpha-4) and I have tried both with and without multiple shards and replicas.

  [1]: http://i.stack.imgur.com/znAwO.png

**Comment by danielmewes** [comment] 2016-03-25 17:05
It looks like you ran into https://github.com/rethinkdb/rethinkdb/issues/5113 . The Data Explorer has a limit of 5 minutes for running queries. I recommend running the query from one of the other drivers.

Closing as a duplicate of https://github.com/rethinkdb/rethinkdb/issues/5113 for the bad error message.

**Closed by danielmewes** 2016-03-25 17:05 UTC
