### ISSUE TITLE
Render an object if it doesn't exist in another table

### ISSUE THREAD

**Issue by Fantasim** [rethinkdb/rethinkdb#6388] opened 2017-06-10 08:43 UTC
I've actually two tables : **posts** and **votes**

**Post** object look like that :

```
type Post struct {
    ID string 
    Content string
    UserID string
}
```
**Vote** object look like that :

```
type Vote struct {
    ID string 
    PostID string 
    Favorable bool
    UserID string
}
```
I would like to render a list of posts **for which user didn't vote yet**. So i need to pick up some post and check for each if vote is related or not with userID and postID parameters. But how can i do that ?

Thank you

**Comment by riyadhzen** [comment] 2017-06-10 09:56
Hi
Sorry for not fully understanding your question. Do you want to renders list of posts where
1) a given user didn't vote yet
2) no votes yet (by any user)

Is is 1 or 2?

**Comment by riyadhzen** [comment] 2017-06-10 11:55
I am assuming that you are looking for option 1

```
r.do(
  r.table('votes').filter({UserID: 44})('PostID').coerceTo('array'),
  function(votes) {
    return r.table('posts').filter(function(post){
      return r.not(votes.contains(post.getField('ID')));
    })
  }
)
```

This has been test in the data explorer

**Comment by Fantasim** [comment] 2017-06-10 12:21
@riyadhzen i'm sorry my english isn't great.

Each user can vote only once on a post.
I would like to get a list of post for which current user has not yet voted.

Do you understand what i mean?

**Comment by Fantasim** [comment] 2017-06-10 15:02
Hi,

this func return null every time.

```
r.do(
  r.table('votes').filter({UserID: 44})('PostID').coerceTo('array'),
  function(votes) {
    return r.table('posts').filter(function(post){
      return r.not(votes.contains(post.getField('ID')));
    })
  }
)
```

**Comment by riyadhzen** [comment] 2017-06-10 16:56
Have you tried running my code in your data explorer?

If yes, Did it return anything?

**Comment by Fantasim** [comment] 2017-06-10 22:30
yes, i got this error in data explorer : 

http://www.yagoshack.fr/?v=capturiqi.png

**Comment by riyadhzen** [comment] 2017-06-11 04:48
From your error it seems that the db named 'Soul' doesn't exist. Make sure that you create that database. 

Also I provided {UserID: 44}, just as an example, you have to supply another ID that you have for a user instead of 44.

Cheers.

**Comment by Fantasim** [comment] 2017-06-11 12:30
Hi,

Database exist, and i know for UserID, i've just copy/paste your code :/

**Comment by riyadhzen** [comment] 2017-06-11 15:15
Ok, I think the issue is with referencing the db in the right place. In my case I am using the test db so I just write r.table('----').

Write the following
```
r.do(
  r.db('Soul').table('votes').filter({UserID: '44'})('PostID').coerceTo('array'),
  function(votes) {
    return r.db('Soul').table('posts').filter(function(post){
      return r.not(votes.contains(post.getField('ID')));
    })
  }
)
```

Hope it works for you (bare in mind that I created a database 'Soul', tested the query on it and it works).
Also, I changed the UserID to '44' as String to make it correspond to your schema:
```
type Post struct {
    ID string 
    Content string
    UserID string
}
```

**Comment by riyadhzen** [comment] 2017-06-17 10:07
Don't forget to close the issue if it was solved.

**Closed** 2017-07-13 18:06 UTC
