### ISSUE TITLE
"undefined is not a function" in data explorer

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3599] opened 2015-01-18 07:16 UTC
I'm not sure if this is avoidable or not, but I was just using the data explorer and typed ".coerce_to" instead of ".coerceTo", resulting in the following error:
```
TypeError: undefined is not a function
```

No indication of which function name was mistyped (or even that a function name was mistyped) and no line number for the error.

I don't know much about JS or how the data explorer is structured, but we should try to do better if we can.  @deontologician, do you know if that's possible?

**Comment by VeXocide** [comment] 2015-01-18 08:32
This is a duplicate of #3566, incidentally also using `coerceTo` as an example.

**Closed by VeXocide** 2015-01-18 08:32 UTC
Labels: tp:enhancement
