### ISSUE TITLE
Data Explorer: Favorite queries

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#4105] opened 2015-04-23 19:22 UTC
It would be awesome to have a "Favorites" panel alongside the History.

**Comment by deontologician** [comment] 2015-04-23 19:46
This is a duplicate of #3928

**Closed by deontologician** 2015-04-23 19:46 UTC

**Comment by deontologician** [comment] 2015-04-23 19:47
@thelinuxlich let me know if you had something else in mind
