### ISSUE TITLE
Discuss naming of new ReQL error types

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4544] opened 2015-07-16 23:11 UTC
The current error hierarchy https://github.com/marshall007/rethinkdb/blob/marshall_4472_js/drivers/javascript/errors.coffee#L24-L38 has caused some confusion about what a specific error type means.

Let's have a brief discussion on the naming of the errors before the final 2.1 release.

I would prefer not the change the actual error hierarchy at this point, but am open to it if there's a really good reason to do so.

Pinging @mlucy @Tryneus @larkost @VeXocide @deontologician @coffeemug

**Comment by danielmewes** [comment] 2015-07-16 23:13
@mlucy could you provide a quick summary of what the different error types mean to get this started please? From looking at the error names this isn't always obvious to me.

**Comment by mlucy** [comment] 2015-07-17 00:16
* `INTERNAL` -- The query was aborted because of an internal error (i.e. a server bug rather than the query being wrong).
* `RESOURCE` -- a resource limit was exceeded (e.g. the array size limit).
* `LOGIC` -- most ReQL errors are logic errors.
  - `NON_EXISTENCE` -- logic errors that result from something missing, can be handled by `default`.  (E.g. accessing a non-existent field.)
* Operation errors -- errors in writes and reads that are caused by cluster state, configuration, the presence or absence of tables, etc. etc.  The line between operation errors and logic errors is sometimes a little fuzzy.
  - `OP_FAILED` -- an operation is known to have failed.
  - `OP_INDETERMINATE` -- an operation may or may not have failed (e.g. if we were disconnected from the master after sending the write but before hearing whether or not it succeeded).
* `USER` -- an error produced by `r.error`.

**Comment by deontologician** [comment] 2015-07-17 00:38
What's the reason `NON_EXISTENCE` is a sub-class of `LOGIC` ? I feel like a field not being present isn't a logic error (unless logic error has no other definition than being a catch-all category)

**Comment by mlucy** [comment] 2015-07-17 00:40
Logic errors might be better called ReQL logic errors.  Adding a number to a string for example.  Accessing a field that doesn't exist seems like a ReQL logic error to me (the same way trying to add a number to a field that's a string is a ReQL logic error).  Non-existence errors are basically the subset of logic errors that we decided we wanted `default` to handle.

**Comment by danielmewes** [comment] 2015-07-17 00:42
Thanks @mlucy.
These seem generally reasonable to me, with the exception that I'd like to find a better name for logic errors. I'll try to come up with some suggestions.
I also wonder if there's a better word to use instead of `op`/`operation`, since those terms can mean different things (like you can think of a ReQL term as an operation, or `op` could even be short for `operator`).

**Comment by deontologician** [comment] 2015-07-17 00:44
Ok, that makes sense to me then

**Comment by larkost** [comment] 2015-07-17 18:24
@VeXocide and I just went over this, and this is what we came up with:

`INTERNAL` and `USER` look good. And we would rather `RESOURCE` be something like "LIMIT" since that is less ambiguous.

There is not much point in separating `LOGIC`, `NON_EXISTENCE`, and the "presence or absence of tables" portion of `OP_FAILED`. It is very unlikely that those can be handled programmatically, so there is little point in separating them. Of course they should still have separate error texts so developers can figure them out.

In our envisioning `RqlQueryError` would include things like nonexistent tables and databases (not to be confused with ones currently unavailable due to clustering issues), but not include errors for keys missing at runtime.

Conversely we felt it was valuable to separate and group things that are the result of (hopefully) transient cluster issues, and so put those as `RqlAvailabilityError` under `RqlRuntimeError`. There was an unresolved discussion about whether there should be both a `RqlDeterminateError` and a `RqlIndeterminateError`, just the latter, or that should just be a marker field on the error type.

Additionally we moved the existing `RqlCursorEmpty` outside the hierarchy, since this is not really an error and should generally not be caught by the same handlers.

And we added `RqlAuthError` as that did not feel like a driver error, but rather something a user/administrator should address.

So here is the hierarchy as we see it (python class names):
- RqlCursorEmpty (client side)
- RqlError
  - RqlQueryError
  - RqlRuntimeError
    - RqlLimitError
    - RqlUserError
    - RqlInternalError
    - RqlTimeoutError (client side)
    - RqlAvailabilityError
      - RqlIndeterminateError
  - RqlDriverError
  - RqlAuthError

**Comment by danielmewes** [comment] 2015-07-17 19:23
A few comments on @larkost's + @VeXocide's proposal:

`RqlLimitError` instead of `RqlResourceError`: :+1: , it sounds better to me

Regarding separating `NON_EXISTENCE`: I think we should keep the separate class. In general I think more granularity is better than less here (in the long term I think we will make these things yet a lot more granular). In this specific case, the distinction is relevant because people handle this specific type of error all the time, by using `default` in their queries. It's only logical I think to provide the same option to client side code.

I don't fully understand what `RqlQueryError` is supposed to be apart from table and database nonexistence. Is it basically our current `RqlCompileError` + `RqlLogicError`?
I think combining those error types into that class might be outside the scope of this issue, since the RqlCompileError vs. RqlRuntimeError distinction as far as I understand is pretty deeply related to how we're processing queries. We can reconsider that distinction and come up with something that makes more sense from the user's perspective, but I feel like this should be a separate change (I could also be wrong and changing this might be trivial, @mlucy ?).

What if we make `RqlLogicErrors` just plain `RqlRuntimeError`s?

`RqlAvailabilityError` instead of `RqlOpError`: :+1: I like that name much better.

I think we should have separate classes for definite and indeterminate failures. This is a pretty important distinction if someone wants to make use of the consistency guarantees we provide (and it happens to be at the core of why we introduced error classes for 2.1 in the first place).
I'm not super happy with the names of the `RqlAvailabilityError` subclasses yet. `RqlOpFailedError` and `RqlOpIndeterminateError` (or just `RqlIndeterminateError`) might be ok, but they don't make it clear that they refer to failures due to availability problems. I think I could live with them though.

Moving `RqlCursorEmpty` outside the hierarchy sounds good (this is a Python-specific thing right?)
`RqlAuthError` as a separate type also sounds useful.

Modified version of the hierarchy:
- RqlCursorEmpty (client side)
- RqlError
  - RqlCompileError (for 2.1 at least)
  - RqlRuntimeError (includes current RqlLogicErrors)
    - RqlNonExistenceError
    - RqlLimitError
    - RqlUserError
    - RqlInternalError
    - RqlTimeoutError (client side)
    - RqlAvailabilityError
      - RqlOpFailedError
      - RqlIndeterminateError
  - RqlDriverError
  - RqlAuthError

**Comment by larkost** [comment] 2015-07-17 20:30
We had an off-line conversation amongst a few of us in the office. Here are the points I got from that:

- The best argument for `RqlNonExistenceError` is so that programs can distinguish when a particular record is missing a value whit having to list the keys and check that. So I am in agreement to separate those.

- More thinking is probably needed about subclasses of `RqlAvailabilityError`. All three of the proposals are logically equivalent, and so the lead argument might be the difficulty of getting good names for the subclasses.

- The argument to combine `RqlCompileError` and `RqlLogicError` now rather than later is that it would be easier for developers to have one big change to adapt to rather than two smaller ones.

- A possible strategy around `RqlQueryError` and `RqlCompileError` would be to alias them together. @danielmewes though that there might be cases where people were deliberately using these distinctions. That would have to be examined in detail.

**Comment by mlucy** [comment] 2015-07-18 00:49
I like `ResourceError` a lot better than `LimitError`.  Isn't `resource` the usual term for this?  Cursory googling suggests that the former is more common (googling "resource error" turns up other projects using the same term, "limit error" turns up nothing).

I definitely don't think `LogicError`s should just be `RuntimeError`s; they're a specific type of runtime error and obscuring that doesn't seem very useful.  It's especially weird because they'd then be the only type of `RuntimeError` that we *don't* have a subclass for.  I agree we could probably find a better name though.  Maybe `ExecutionError`?

I like `AvailabilityError` a lot; I think that's a much better name for it.  `AuthError` seems good too.

What's going on with `RqlTimeoutError`?  I was under the impression that we just used the native timeout exception types in the client languages.  If so, I think we should continue doing that; it always annoys me when projects duplicate existing exception types.

Here's the hierarchy I'd propose:

- RqlCursorEmpty (client side) // this is a Python-only thing, right?
- RqlError
  - RqlCompileError
  - RqlRuntimeError
    - RqlLogicError
      - RqlNonExistenceError
    - RqlResourceError
    - RqlUserError
    - RqlInternalError
    - RqlTimeoutError (client side) // maybe, not sure what's going on with this
    - RqlAvailabilityError
      - RqlOpFailedError
      - RqlOpIndeterminateError
  - RqlDriverError
  - RqlAuthError

**Comment by deontologician** [comment] 2015-07-18 16:11
What about `ResourceLimitError`?

**Comment by mlucy** [comment] 2015-07-21 00:29
`ResourceLimitError` sounds good to me.

**Comment by danielmewes** [comment] 2015-07-21 00:30
@mlucy could you define logic errors a bit more?
I don't fully understand what their characteristics are yet.
Judging by their names, `ExecutionError` sounds like it wouldn't add much to `RuntimeError`.

`ResourceLimitError` sounds good to me as well.

**Comment by mlucy** [comment] 2015-07-21 00:35
A `RuntimeError` is anything that happens at runtime (so the driver sent the query correctly and the query compiled correctly, and now we're running it).

Logic errors are runtime errors that are produced by incorrect query logic -- e.g. trying to add a number to a string.  This makes them distinct from errors caused by e.g. a netsplit.  If you get a logic error, it 100% means you need to rewrite your query (or possibly change your data).  This makes them distinct from the other errors -- resource errors can be fixed by bumping up your limits, availability errors can be fixed by resolving netsplits, and internal / timeout errors aren't really your fault.  (Arguably `UserError` should be a subset of `LogicError`, but it isn't because user errors are usually produced by the query working as intended and aborting in a certain circumstance rather than the query being incorrect.)

**Comment by danielmewes** [comment] 2015-07-21 00:43
Ok that makes sense. In that case I like @larkost 's proposal to call them `RqlQueryError`. That seems to capture the idea best so far (unless I'm still missing something about that error class).

As mentioned before, I think we should reconsider the CompileError vs. RuntimeError distinction at some point. From a user's perspective I think the distinction between compilation and runtime phase isn't clear, and both CompileErrors and logic errors require rewriting the query. But let's keep that for a separate discussion later.

**Comment by mlucy** [comment] 2015-07-21 01:24
`RqlQueryError` sounds way too general to me.  I would expect `RuntimeError` and `CompileError` to be subsets of `QueryError` personally.  (Although maybe that's an argument in favor of your point that the `RuntimeError` and `CompileError` distinction should go away.)

What about `EvaluationError`?

**Comment by deontologician** [comment] 2015-07-21 01:30
`QueryLogicError`?

**Comment by danielmewes** [comment] 2015-07-21 01:42
`RqlInvalidQueryError`?

**Comment by mlucy** [comment] 2015-07-21 01:43
`QueryLogicError` works for me.  (It's interesting that worked for both this case and `ResourceLimitError`.

Also, as long as we're renaming things, we should take this opportunity to change `Rql -> Reql`.  We've been meaning to do that for ~2 years (the exception names were chosen before we standardized on ReQL as the abbreviation).

**Comment by mlucy** [comment] 2015-07-21 01:43
We should consider keeping the old names around as deprecated synonyms though to avoid breaking people's code.

**Comment by danielmewes** [comment] 2015-07-21 01:45
:+1: on `Rql` -> `Reql` while keeping the `Rql*` types around for at least 2.1. So we would make the new types derive from the equivalent old types right?

**Comment by danielmewes** [comment] 2015-07-21 01:48
`QueryLogicError` sounds ok to me.

**Comment by mlucy** [comment] 2015-07-21 01:52
I would make them Synonyms.  (In Ruby this is as easy as writing `RqlRuntimeError = ReqlRuntimeError`, I'm not sure about the other languages.)

**Comment by mlucy** [comment] 2015-07-21 01:53
(This will slightly change behavior because the stringified version of the exception will look different, but I think that's OK.)

**Comment by danielmewes** [comment] 2015-07-21 01:53
Ah ok, even better.

**Comment by danielmewes** [comment] 2015-07-21 20:09
Alright, updated proposal:

- ReqlCursorEmpty (client side, Python)
- ReqlError
  - ReqlCompileError
  - ReqlRuntimeError
    - ReqlQueryLogicError
      - ReqlNonExistenceError
    - ReqlResourceLimitError
    - ReqlUserError
    - ReqlInternalError
    - ReqlTimeoutError (client side, only if we already have this)
    - ReqlAvailabilityError
      - ReqlOpFailedError
      - ReqlOpIndeterminateError
  - ReqlDriverError
  - ReqlAuthError

...with `Rql*` aliases/synonyms for the existing error types (`RqlCompileError`, `RqlServerError`, `RqlRuntimeError`, `RqlDriverError`).

**Comment by danielmewes** [comment] 2015-07-21 20:11
Edit for email readers: Took `RqlServerError` from the list of backwards-compatible synonyms since we don't have a direct equivalent in the new hierarchy.

**Comment by larkost** [comment] 2015-07-21 21:19
Side note on `ReqlTimeoutError`: As of Python3.3 the `TimeoutError` has been added and I have added code to make our current `RqlTimeoutError` use it as a base class where possible.

There are a number of new [`OSError` subclasses](https://docs.python.org/3/library/exceptions.html#os-exceptions), a couple of them might be worth doing the same thing for in the new model. Most notably we would probably want `ReqlDriverError` and `ReqlAuthError` to be (additionally) subclassed from `ConnectionError`.

**Comment by larkost** [comment] 2015-07-21 21:33
@VeXocide and I just talked through making `ReqlAuthError` (new) a subclass of `ReqlDriverError`. There are logical arguments for and against this, but the willer for us was that currently auth errors are `RqlDriverError`s, so doing so would keep backwards compatibility.

**Comment by danielmewes** [comment] 2015-07-21 22:44
> There are logical arguments for and against this, but the willer for us was that currently auth errors are `RqlDriverErrors`, so doing so would keep backwards compatibility.

That's fair, probably a good idea to put it under there.

**Comment by mlucy** [comment] 2015-07-21 23:53
+1 for the list with `AuthError` deriving from `DriverError`.

**Comment by danielmewes** [comment] 2015-07-22 00:13
I call that an agreement :-)

- ReqlCursorEmpty (client side, Python)
- ReqlError
  - ReqlCompileError
  - ReqlRuntimeError
    - ReqlQueryLogicError
      - ReqlNonExistenceError
    - ReqlResourceLimitError
    - ReqlUserError
    - ReqlInternalError
    - ReqlTimeoutError (client side, only if we already have this)
    - ReqlAvailabilityError
      - ReqlOpFailedError
      - ReqlOpIndeterminateError
  - ReqlDriverError
      - ReqlAuthError

**Closed** 2015-07-25 09:17 UTC
Labels: tp:ReQL_proposal
