### ISSUE TITLE
Cover the codebase with Doxygen documentation

### ISSUE THREAD

**Issue by thedrow** [rethinkdb/rethinkdb#6175] opened 2016-11-16 11:31 UTC
In order to keep the project alive we need proper code documentation.
I suggest using Doxygen or something similar and tracking the coverage using https://github.com/alobbs/doxy-coverage for example.

**Comment by AtnNn** [comment] 2016-11-16 12:50
There's a Doxyfile in the [doxygen](cbfbe24) branch, it can be used to generate a nice cross-referenced overview of the code. It's not in `next` because the cost of maintaining it has so far outweighed its usefulness.

Improving the code documentation and comments is a great idea. I don't know if the Doxygen markup style would be a good fit.

I don't like the idea of measuring comment coverage. We need better documented code, not more comments. I personally think that code should be self documenting and comments should only be used when the code isn't clear. I never liked commits that add too many comments, they usually lead to comments being out of sync with the code, and make the code harder to read. For example, I think that most of 9a1298ac would have been better as a separate article or post.

**Comment by srh** [comment] 2017-05-26 02:32
This issue will never be "complete" (not that anybody's working on it) so I'm going to close it.

Also kind of a dupe of #6248.

**Closed by srh** 2017-05-26 02:32 UTC
