### ISSUE TITLE
How to floor seconds at a query ?

### ISSUE THREAD

**Issue by aj07mm** [rethinkdb/rethinkdb#4418] opened 2015-06-17 20:19 UTC
im trying this:
```
group_by = [
            r.row['createdAt'].year(), 
            r.row['createdAt'].day(), 
            r.row['createdAt'].month(), 
            r.row['createdAt'].hours(), 
            r.row['createdAt'].minutes(), 
            r.row['createdAt'].seconds().floor()
        ]
```
but the floor doesn't work, i need to group by seconds not miliseconds, there is currently a way to do that?

**Comment by VeXocide** [comment] 2015-06-17 20:55
Our next release will introduce an `r.floor` and related functions, see https://github.com/rethinkdb/rethinkdb/issues/866 for more information for more information on those.

In the meantime you can use `.seconds().info()("value").split(".")(0).coerceTo("NUMBER")` which essentially takes the string representation, splits it at the dot, and coerces the leading part back to a number. It's not pretty but should help you bridge the time until that next release.

Hope that helps. I'm closing this since it's not a bug, but feel free to ask any more questions here and we'll answer them for you.

**Closed by VeXocide** 2015-06-17 20:55 UTC

**Comment by aj07mm** [comment] 2015-06-17 21:53
thanks @VeXocide

**Comment by aj07mm** [comment] 2015-06-18 04:16
@VeXocide How i implement snippet in python? Im not using js

**Comment by VeXocide** [comment] 2015-06-18 05:15
@aj07mm I suspect you missed the `["value"]` after `info()`, `.seconds().info()["value"].split(".")[0].coerce_to("NUMBER")` should do the trick. Note that `.info()["value"]` is functionally equivalent to `.coerce_to("STRING")`, thus you might want to use that for clarity.

**Comment by aj07mm** [comment] 2015-06-18 17:43
true, many thanks!
