### ISSUE TITLE
Exclude non-voting replicas from outdated reads

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#5324] opened 2016-01-27 16:28 UTC
There should be an option, maybe not related with non-voting replicas, but with server tags, to remove them from outdated reads, so we can use modest hardware for live backup.

**Comment by danielmewes** [comment] 2016-01-29 23:17
This is a duplicate of https://github.com/rethinkdb/rethinkdb/issues/1858 (but yeah, we should try to come up with a design/API for this).

**Closed by danielmewes** 2016-01-29 23:17 UTC
