### ISSUE TITLE
GetAll does not support list input

### ISSUE THREAD

**Issue by sandesh-kulkarni** [rethinkdb/rethinkdb#5727] opened 2016-04-27 11:11 UTC
r.table('xyz').getAll([1,2]) - in data explorer displays - "No results returned."

Similarly in python - r.table('xyz').get_all([1,2]).run(con).next() - results in error message saying cursor is empty.

The feature is important as one can define the list of values in a variable and pass the variable to getAll like -

x=[1,2]
r.table('xyz').getAll(x) 

What works: r.table('xyz').getAll(1,2) - works. This means that getAll currently accepts comma separated values but does not accept list of values.

Note: Table 'xyz' contains a primary_key which has values 1,2,3,... This behaviour is same for secondary index. 

Note2: pluck does accept list of column names as input which makes life a lot easier.   

Update: I understood the problem in giving out the feature. The list is supposed to be used with a compound index. The get around would be to allow a list of list or a tuple as input for getAll for a simple index for plucking particular rows from the database.

**Comment by marshall007** [comment] 2016-04-27 17:21
@sandesh-kulkarni the reason this doesn't work is because arrays are also valid primary key values. Thus, `.getAll([1, 2])` will try to find rows where `id: [1, 2]`. To get this to work you just need to wrap your array argument in an `r.args(...)`, which basically acts like a spread operator.

```js
r.table('xyz').getAll(r.args([1,2]))

let x = [1,2]
r.table('xyz').getAll(r.args(x))
```

**Comment by danielmewes** [comment] 2016-04-27 18:25
Closing, since this is expected behavior and there is `r.args` for this reason as @marshall007 explained.

**Closed by danielmewes** 2016-04-27 18:25 UTC

**Comment by chrisabrams** [comment] 2016-06-23 03:29
I would highly recommend adding this to the docs as I would be lost without this issue.

**Comment by encryptio** [comment] 2016-06-23 17:44
I checked, and this is already in the docs at https://rethinkdb.com/api/javascript/get_all/ - see the section "Example: You can use args with getAll to retrieve multiple documents whose keys are in a list."

**Comment by chrisabrams** [comment] 2016-06-23 19:10
What I mean is, show an example using `r.args`. As someone who didn't know what `r.args` was until yesterday, I did not understand :/

**Comment by danielmewes** [comment] 2016-06-23 19:19
@chrisabrams Any suggestions for how to make the wording in the document that @encryptio linked easier to understand / discover?

**Comment by chrisabrams** [comment] 2016-06-23 20:27
You can get multiple documents in a single call to get_all.

Example 1: 

`r.table('dc').getAll('superman', 'ant man').run(conn, callback)`

Example 2:

`r.table('dc').getAll(r.args(['superman', 'ant man'])).run(conn, callback)`

In the second example, `r.args` is used to specify the first argument in `getAll` is a list of keys, and not a ______.

I put a blank there because I don't understand how `.getAll(['superman', 'ant man'])` works. That probably should be used for Example #3 to make things even more clear. :O
