### ISSUE TITLE
Sharding with Multi-index causes severe file bloat

### ISSUE THREAD

**Issue by bsharpe** [rethinkdb/rethinkdb#5923] opened 2016-07-07 14:11 UTC
We have a table in our DB that has 20MM rows in it.   Each row is a small bit of data and an array of integers representing dates.   That array can be 10 to 1600 entries (average 30).  The base data is approximately 10G. The primary key is 56-bytes (sha3-224bit).
Array data looks like: `[1443398400, 1443484800, 1443571200, 1443657600]`

We multi-index on that array to be able to quickly find items that apply to a specific date for a specific account quickly.

The index is defined like this: (Ruby syntax)
```
->(d){ d['dates'].map{|e| [d['account_id'], e]} }, multi: true
```

Note: We tried a compound index with account_id and two dates (start & end) -- but the secondary indexes don't filter as intuitively as imagined with dates involved. This required us to `filter` results after using the index which is 10x slower than the mutli-index approach.

We have 2 nodes (db-1 & db-2), which according to the admin panel have 9.5MM rows each.
The table is set to 2 shards/2 replicas.
- on db-1 this table takes up: 242G (1 shard + 1 replica)
- on db-2 this table takes up: 241G (1 shard + 1 replica)

We were adding a 3rd node and resharding this table to be (3/3) -- the data on db-3 exceeded 1.3T

We've had trouble with this table before...  
Here's the part where we believe there's a bug:
```
Deleting and rebuilding just this one index can reduce the space by as much as 50%.
```

This is seriously impacting our ability to grow (we can't add a 3rd node, for example).   We have tables with 40MM entries where the rows are much larger but the file takes up less space.

Our Math:
```
(56bytes for ID + ~20bytes for each date in the index) 
 * 30 dates(average per row) 
 * 20MM rows = ~45G

our db-3 server was needing 31x that amount of space for this one table.
```

FYI:  
  - RethinkDB 2.3.4 from your APT repos on Ubuntu 14.04.1 w/ no virtualization using XFS
  - Servers have 256G RAM, 24 cores, 1.4T storage

**Comment by scottrobertson** [comment] 2016-07-09 07:08
Update: We rebuilt the index, then added the 3rd server back in. It hit 100% disk usage and went offline. The other servers are fine.

**Comment by bsharpe** [comment] 2016-07-10 20:32
and by 100% disk usage -- we mean that a table of ~11G of raw data created an index that filled a 1.4T drive...  this was the only table sharding to this node when the "out of space" error occurred.

We have learned that if we delete this index -- shard -- and rebuild the index -- things will fit.  But building the index takes ~24hrs. for 20 million rows w/ an avg of 30 entries in the index each.

**Comment by danielmewes** [comment] 2016-07-11 18:43
We'll need to investigate this.

I suspect that it's some interaction with the garbage collector and the particular write load that is generated when adding an additional replica for a table with an index.
@bsharpe If you experience this again, could you take a look at the entry for the table+server pair in `r.db('rethinkdb').table('stats')`? It should have a `storage_engine` field, with details on the current amount of garbage in the file among some other numbers. I wonder what those numbers are when seeing the disk size bloat.

This *could* have to do with https://github.com/rethinkdb/rethinkdb/issues/4730. Normally there are provisions in place that make sure that index construction and backfilling data from another node don't run at the same time, because that can reduce the efficiency of both. However there has been some indication that this doesn't currently work as expected.

**Comment by bsharpe** [comment] 2016-07-11 18:53
@danielmewes while it's difficult for us to give up a node to recreate this error again... we can show you the current 2 nodes for this particular table:   The table is set to 2 shards/ 2 replicas -- which should mean that they have the same data on each, correct?

```
{
"db":  "data_collector_production" ,
"id": [
"table_server" ,
"333946de-78d6-42b4-8ec1-2b13b2cf6cb3" ,
"ed6e64cf-f22d-4bcc-91cc-70a92a35ea0b"
] ,
"query_engine": {
"read_docs_per_sec": 37.353371279 ,
"read_docs_total": 211264640 ,
"written_docs_per_sec": 0 ,
"written_docs_total": 5108262
} ,
"server":  "db3" ,
"storage_engine": {
"cache": {
"in_use_bytes": 12088887056
} ,
"disk": {
"read_bytes_per_sec": 4129.38883584 ,
"read_bytes_total": 181072080384 ,
"space_usage": {
"data_bytes": 282207265280 ,
"garbage_bytes": 33699323392 ,
"metadata_bytes": 3743416320 ,
"preallocated_bytes": 2097152
} ,
"written_bytes_per_sec": 0 ,
"written_bytes_total": 1009213819392
}
} ,
"table":  "bare_dr_states"
} {
"db":  "data_collector_production" ,
"id": [
"table_server" ,
"333946de-78d6-42b4-8ec1-2b13b2cf6cb3" ,
"cc141080-d077-4e55-bd58-d8bbd752ee83"
] ,
"query_engine": {
"read_docs_per_sec": 19.616001844 ,
"read_docs_total": 11852559 ,
"written_docs_per_sec": 0 ,
"written_docs_total": 738250
} ,
"server":  "db1" ,
"storage_engine": {
"cache": {
"in_use_bytes": 17280042496
} ,
"disk": {
"read_bytes_per_sec": 6994.624987136 ,
"read_bytes_total": 22368799232 ,
"space_usage": {
"data_bytes": 280211814912 ,
"garbage_bytes": 44825773568 ,
"metadata_bytes": 4030726144 ,
"preallocated_bytes": 2097152
} ,
"written_bytes_per_sec": 0 ,
"written_bytes_total": 74527582208
}
} ,
"table":  "bare_dr_states"
}
```

none of our other 30+ tables exhibit this sort of behavior with their indexes...  This table is the only one that is really making use of the multi-index option.

It should be noted that we saw this table balloon up when we were deleting/rewriting a lot of data to it during development.   But reindexing always fixed it.

**Comment by bsharpe** [comment] 2016-07-11 18:59
We may be able to produce an export file to send you that could recreate this for you.

**Comment by bsharpe** [comment] 2016-07-13 12:29
could be related to https://github.com/rethinkdb/rethinkdb/issues/5942

**Comment by danielmewes** [comment] 2016-07-13 18:32
Another report that is very likely describing the same effect by @Calavoow from #5942:

--

When creating a database we usually create indices when setting up the database. But this resulted in some unusually large index sizes for multi-indexes. After playing around a bit it seems that first importing the data and then adding the indices results in a 10x smaller database file size compared to first creating indices and then inserting the data.

I have uploaded files with which I can reproduce this behaviour here: https://gist.github.com/Calavoow/c6d6b2d58635e003ffcc8ea7da1795fa
First generate items for the db with the generate script. Then set up the database without the index. Import the json with the command from the generate script. Then create an index with
```js
        r.db('multibloat').table("multibloat").indexCreate("byTagTitle", function( row ){
            return row('full_tags').map( function( tag ){
                return [row('view_id'), tag, row('title').downcase()];
            });
        }, {multi: true})
```
Compare the resulting database size to the one with the index created at setup time (remove the comment slashes from setup.js) and then the data imported.

I get the following difference. Index created before inserting data:
```
3.3G Jul 13 14:15 d2f699c2-fffd-4a7c-ade3-488d76ec9935
```
After:
```
646M Jul 13 14:14 71e0a88b-888f-4bad-a89f-5e2e46878d3f
```

**Comment by danielmewes** [comment] 2016-07-13 18:56
@Calavoow do you have the superheroes.js file that the generate.js script requires as well?

**Comment by danielmewes** [comment] 2016-07-13 18:58
Never mind, I just hard-coded a superhero name...

**Comment by Calavoow** [comment] 2016-07-13 19:28
@danielmewes It is an npm package https://www.npmjs.com/package/superheroes

**Comment by danielmewes** [comment] 2016-07-13 21:33
It looks like the garbage collector cannot keep up with the high write load when running `rethinkdb import` on a table with a multi-index.

This is partially because `rethinkdb import` uses soft-durability writes, which do not slow down as quickly as hard-durability writes if the storage backend can't keep up. So the write rate stays high for a while before the garbage collector can start catching up.
Running `rethinkdb import` with the `--hard-durability` flag seems to avoid the issue for the case of data imports, but is not a general solution.

I suspect that backfilling data from another replica puts a similar amount of stress on the garbage collector, and that that's why the file size goes up so much when adding a replica. I haven't verified this yet.

I'm currently experimenting with tuning the aggressiveness of the garbage collector. In @Calavoow's test case, the file size with the existing index is still about 1.9 GB on the system I'm testing on (it will depend on the performance characteristics of the I/o system and some other factors). It's better than before, but not quite perfect yet.

@bsharpe and @Calavoow: If I send you a new binary with the tuned GC parameters, would you be able to test these scenarios again on your systems? @Calavoow I'll also need the operating system / distribution + version that you're running on.

**Comment by bsharpe** [comment] 2016-07-14 03:16
@danielmewes Yes, we would be open to running a GC tuned version.  👍

**Comment by Calavoow** [comment] 2016-07-14 07:42
@danielmewes I have tested this on two systems:

1. Arch linux with rethinkdb 2.3.1 (the repos are behind and building rethinkdb gives me an error)
2. Ubuntu LTS 14.04 with rethinkdb 2.3.4

I can test this the binary on either system. You can contact me on the rethinkdb slack.
We were also wondering if it is possible to defragment / garbage collect an existing database. Then it would be possible to reduce the size after importing.

**Comment by danielmewes** [comment] 2016-07-15 04:35
@Calavoow @bsharpe I've uploaded a RethinkDB 2.3.4 package with modified GC settings for Ubuntu 14.04 to https://www.dropbox.com/s/afyi8omw0lgtdew/rethinkdb_2.3.4-GC-testing-0trusty_amd64.deb?dl=0 .

Please let me know if this version helps with the issue when you get a chance to try it out.

**Comment by Calavoow** [comment] 2016-07-15 12:25
Results for the test data set. With setting index after importing:
```
714M Jul 15 12:21 d072651d-2e4d-46e5-81bb-0f6f82b4d048
```
After importing
```
3.4G Jul 15 12:23 c8bf7a33-50da-4a31-8514-527494114dfd
```

So it did not change much. Just to check
```
⟫ rethinkdb --version
rethinkdb 2.3.4+11+gfd1651~0trusty (GCC 4.8.2)
```

**Comment by bsharpe** [comment] 2016-07-15 13:11
We saw a nice drop in "garbage" space with the new binary... average table went from 13% to 9% saving us a ton of space.  However, here's a picture of a table that was backfilling after the relaunch with the new binary:
```
                bare_subscription_states   db1 21.9%   6.70 GiB  37.21 GiB
                bare_subscription_states   db2  6.6%   2.08 GiB  33.81 GiB
                bare_subscription_states   db3 20.1%   6.23 GiB  37.15 GiB
```
1 & 3 are backfilling...

**Comment by danielmewes** [comment] 2016-07-18 22:09
Thanks for the feedback.

@Calavoow If you run the server through the init script, it should automatically restart when updating the dpkg. So it looks like this change didn't help much for your scenario unfortunately.

@bsharpe A 22% garbage ratio from backfilling is somewhat high, but not necessarily outside the expected range. Do those tables have a multi index?

**Comment by scottrobertson** [comment] 2016-07-18 23:28
Hey @danielmewes. Just filling in for @bsharpe as he is away.

That table does not have a multi index.

**Comment by danielmewes** [comment] 2016-07-27 20:28
We've implemented some more efficiency improvements for the garbage collector. They are still in code review, but I think we'll wait with 2.3.5 and include them in that release.

I'm not sure if they are enough to fully resolve this issue (I suspect not quite), but they should make things a bit better. The changes also improve performance for heavy sustained write workloads, so they are an improvement regardless.

**Comment by danielmewes** [comment] 2016-07-27 20:29
(those are improvements in addition to the ones that were in the test binary that I sent you before)

**Comment by danielmewes** [comment] 2016-08-05 23:26
The mentioned improvements to the garbage collector are now in `next` via f91f965 and `v2.3.x` via 3fab787. They will ship with RethinkDB 2.3.5.

I'm closing this for record-keeping for the 2.3.5 release. If we find that the issue still persists after 2.3.5, we'll just re-open it.

**Closed by danielmewes** 2016-08-05 23:26 UTC
Labels: tp:bug

**Comment by danielmewes** [comment] 2016-08-30 01:52
@bsharpe @Calavoow RethinkDB 2.3.5, which we released today, includes a few efficiency improvements for the garbage collector. Those improvements are different from the ones that were in the testing binary that I had sent you before (the ones in RethinkDB 2.3.5 go further). I'm not certain if this fully solves the problem, but it should make it less severe. If you get a chance to try it out, I'd be interested in hearing what your results are.
