### ISSUE TITLE
Meteor integration

### ISSUE THREAD

**Issue by ccorcos** [rethinkdb/rethinkdb#4476] opened 2015-06-30 19:28 UTC
Hey guys, I'm working integrating RethinkDB with Meteor. 

- [driver](https://github.com/ccorcos/meteor-rethink)
- [example](https://github.com/ccorcos/meteor-any-db/tree/master/examples/rethink)

I'm having some issue with change feeds though. I need to be able to implement [`cursor.observerChanges`](http://docs.meteor.com/#/full/observe_changes) based on the changefeed but I'm running into two roadblocks:

1) Rethink doesn't consistently provide the initial documents. In fact, the documentation is explicitly vague about this inconsistency:

> Point changefeeds will always return initial values and have an initializing state; feeds that return changes on unfiltered tables will never return initial values. Feeds that return changes on more complex queries may or may not return return initial values, depending on the kind of aggregation.

2) They don't support movement in ordered queries. When a document changes position in an ordered query, I would expect the changefeed to reflect that.

If we can solve these two issues, integrating rethinkdb with Meteor will be a breeze!

**Comment by mlucy** [comment] 2015-06-30 20:14
Hi Chet!

> Rethink doesn't consistently provide the initial documents.

Sorry about this one.  Efficiently returning initial documents for large
range queries took a little longer to implement than we would have liked,
but this feature is mostly implemented and will be released in 2.2 (you can
track progress at https://github.com/rethinkdb/rethinkdb/issues/3579).

> They don't support movement in ordered queries.

The feature was originally written with the assumption that you'd be
storing the rows in an ordered tree (ordered by the same field you're
ordering on in the query) so that you could quickly find the old row to
remove it and quickly insert the new row.  Doing that would take care of
position changes automatically.  You aren't the first person to have asked
for this though.  You can track progress at
https://github.com/rethinkdb/rethinkdb/issues/3714 .

**Comment by danielmewes** [comment] 2015-06-30 20:25
@ccorcos that's really cool. As @mlucy pointed out, these things will become easier with the RethinkDB 2.2 release.

Have you seen https://github.com/Slava/meteor-rethinkdb by the way?

**Comment by danielmewes** [comment] 2015-06-30 20:25
Closing as duplicate of #3579 and #3714.

**Closed by danielmewes** 2015-06-30 20:25 UTC

**Comment by ccorcos** [comment] 2015-07-01 00:37
Thanks for the links -- I'm following them now.

> The feature was originally written with the assumption that you'd be
storing the rows in an ordered tree (ordered by the same field you're
ordering on in the query) so that you could quickly find the old row to
remove it and quickly insert the new row.

I'm not sure this would work for some queries with non-trivial sorting and joins, etc.

**Comment by ccorcos** [comment] 2015-07-01 00:37
Is there a rethinkdb roadmap?

**Comment by danielmewes** [comment] 2015-07-01 00:53
@ccorcos we use milestones in the GitHub issue tracker as sort of an implicit roadmap. If you look at the 2.1 and 2.2 milestones, you can see what's scheduled for the respective releases. There are also "2.x-polish" milestones with issues that would be nice to get in, but for which we wouldn't hold the release. In addition issues in the `subsequent` milestone are those that we're considering for one of the upcoming releases, but that haven't been scheduled for a specific one yet.

**Comment by ccorcos** [comment] 2015-07-01 01:29
Hmm. So it seems I won't have these features for at least several months :'(

**Comment by danielmewes** [comment] 2015-07-01 01:31
@ccorcos Well for #3714, there is https://github.com/rethinkdb/rethinkdb/issues/3719 which can be seen as a work-around for that limitation at least for small-ish result sets. And that one is scheduled for 2.2, which we currently estimate to be out in about 2 months. Sorry it's not going to be available earlier.

**Comment by ccorcos** [comment] 2015-07-01 01:41
I see. So you're going to give the full arrays of before and after.... That doesn't make things terribly efficient though. In this case, I may as well just run the query all over again -- I'll have to diff them anyways.

That said, it would be awesome if I could just get some kind of event that says something (anything) changes within the query cursor (including the sort order). That way, I can rerun the query and do all the diff'ing through Meteor on the server.
