### ISSUE TITLE
raft branch: showing `'all_replicas_ready': True` in response to rebalance

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4289] opened 2015-05-26 22:27 UTC
The `./test/run -v interface.shard_balancing` test is failing in the raft branch because the dict response to `rebalance` is showing `'all_replicas_ready': True`. My guess is that this is another timing issue where the old status is being read out before the operation is starting. In this particular case the shards are not moving, only the shard boundaries should be.

**Comment by timmaxw** [comment] 2015-05-26 22:30
I suspect this is caused by the same thing as #4265.

**Comment by VeXocide** [comment] 2015-05-26 22:39
Yep, this is very likely the same bug.

**Comment by VeXocide** [comment] 2015-06-02 00:22
In CR 2935 by @timmaxw. Note that this causes the `interface.shard_balancing` test to block forever due to another bug.

**Comment by VeXocide** [comment] 2015-06-02 03:49
Merged into `raft` via commit 19f42a4f5089af3271032acec36d6704c241f637.

**Closed by VeXocide** 2015-06-02 03:49 UTC
