### ISSUE TITLE
issue linking rethinkdb-unittest on raft branch on MacOS

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4257] opened 2015-05-21 19:38 UTC
On the `raft` branch I am unable to link the `rethinkdb-unittest ` executable. I am getting the following error:
```
    [1/1] LD build/debug_clang/rethinkdb-unittest
Undefined symbols for architecture x86_64:
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >& boost::operator<<<char, std::__1::char_traits<char>, uuid_u>(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, boost::optional<uuid_u> const&)", referenced from:
      void testing_internal::DefaultPrintNonContainerTo<boost::optional<uuid_u> >(boost::optional<uuid_u> const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*) in clustering_contract_coordinator.o
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >& boost::operator<<<char, std::__1::char_traits<char>, std::__1::set<uuid_u, std::__1::less<uuid_u>, std::__1::allocator<uuid_u> > >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, boost::optional<std::__1::set<uuid_u, std::__1::less<uuid_u>, std::__1::allocator<uuid_u> > > const&)", referenced from:
      void testing_internal::DefaultPrintNonContainerTo<boost::optional<std::__1::set<uuid_u, std::__1::less<uuid_u>, std::__1::allocator<uuid_u> > > >(boost::optional<std::__1::set<uuid_u, std::__1::less<uuid_u>, std::__1::allocator<uuid_u> > > const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*) in clustering_contract_coordinator.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [build/debug_clang/rethinkdb-unittest] Error 1
make: *** [make] Error 2
```
I have been able to reproduce this on gantz as well.

**Comment by Tryneus** [comment] 2015-05-21 20:03
Looks like one of the `EXPECT_EQ` in `unittest/clustering_contract_coordinator.cc` might be trying to print something out that it doesn't know how to.  Looking into this.

**Comment by Tryneus** [comment] 2015-05-22 01:05
So, I'm not really familiar enough with our build system to fix this, but there's a similar problem here with a possible solution that involves changing the parameters to `configure` for `gtest`:

http://stackoverflow.com/questions/21267682/gtest-fails-to-link-on-mac-with-the-default-compiler

**Comment by danielmewes** [comment] 2015-06-10 00:38
@AtnNn is this something we could do for compiling `gtest`?

**Comment by AtnNn** [comment] 2015-06-10 02:14
If it's an issue with conflicting std libs, it should be easy to fix. We can copy the code from here:

https://github.com/rethinkdb/rethinkdb/blob/next/mk/support/pkg/protobuf.sh#L34-L39

#3473 is another solution that doesn't involve copy-pasting but that has other disadvantages.

**Comment by danielmewes** [comment] 2015-06-10 19:29
After trying copying over the section from protobuf.sh I'm not sure if this is actually the solution. It didn't solve it for me on gantz.

In fact the gtest Makefile already sets `-stdlib=libc++`
```
ifeq ($(UNAME),Darwin)
CXXFLAGS += -stdlib=libc++
endif
```

Even changing this to
```
ifeq ($(UNAME),Darwin)
CXX = clang++
CXXFLAGS += -std=c++11 -stdlib=libc++
endif
```

still runs into the same linking problem described in the original post.

**Comment by AtnNn** [comment] 2015-06-12 15:21
@larkost @neumino What version of boost do you have installed? Could you please test if the build still fails with `./configure --fetch boost`?

I wasn't able to reproduce this issue. The error seems to indicate that `boost::operator<<` is missing for `std::set<uuid_u>` and `std::optional<uuid_u>`.

**Comment by danielmewes** [comment] 2015-06-12 19:31
@AtnNn I can reproduce this on `gantz`. I'm still getting it with `./configure --fetch boost --allow-fetch`.

Here's the configure output:
```
* Detecting system configuration
Bash:                           3.2.57(1)-release
Use ccache:                     no
C++ Compiler:                   CLANG 6.1.0 (/usr/bin/c++)
Host System:                    x86_64-apple-darwin14.1.0
Build System:                   Darwin 14.1.0 x86_64
Cross-compiling:                no
Host Operating System:          Darwin
Build Architecture:             x86_64
stdlib:                         -lc++
C++11:                          ok
Precompiled web assets:         no
Protobuf compiler:              /usr/local/bin/protoc
python:                         python 2.7.6
Node.js package manager:        /usr/local/bin/npm
coffee:                         coffee 1.7.1
Browserify:                     browserify 3.24.13
bluebird:                       external/bluebird_2.9.25
web UI dependencies:            external/admin-deps_2.0.2
wget:                           no
curl:                           /usr/bin/curl
Google Test:                    external/gtest_1.6.0
termcap:                        -ltermcap
boost_system:                   external/boost_1.56.0
ssl:                            -lssl
protobuf:                       external/protobuf_2.5.0
icui18n:                        external/icu_54.1
icuuc:                          external/icu_54.1
icudata:                        external/icu_54.1
v8 javascript engine:           external/v8_3.30.33.16
RE2:                            external/re2_20140111
z:                              -lz
crypto:                         -lcrypto
curl:                           -lcurl
malloc:                         system
Test protobuf:                  external/protobuf_2.5.0
Test boost:                     external/boost_1.56.0
Installation prefix:            /usr/local
Configuration prefix:           /usr/local/etc
Runtime data prefix:            /usr/local/var
* Wrote configuration to config.mk
```

**Comment by AtnNn** [comment] 2015-06-12 22:49
The file causing this test failure is `clustering_contract_coordinator.cc`.

This failure seems unique to boost 1.56, related to https://svn.boost.org/trac/boost/ticket/10825 . The solution recommended in that thread does not work.

Upgrading boost to 1.58 seems to fix this issue, but it causes other build failures on newton. Boost 1.58 doesn't seem to like GCC 4.6's libstdc++.

I tried overloading `operator<<` for `boost::optional<uuid_u>`, but couldn't get the compiler to pick it over `boost::operator<<`.

**Comment by larkost** [comment] 2015-06-29 20:28
I just checked bumping a build on newton to Boost 1.58 with GCC 4.6.3 and it was happy building, as was a build locally on MacOS[1]. @AtnNn was there a specific version of GCC that was blowing up on this? If not I would love to clear out this issue so MacOS could run unittests.

Pinging @VeXocide for any comments about Boost 1.58.

[1] There are enough general problems in testing right now that I don't want to venture any assertions about the quality of the executable that this produces.

**Comment by AtnNn** [comment] 2015-06-29 20:46
The build fails when boost 1.58 is built with clang 3.2 and libstdc++ 4.6. It detects it as version 4.7, and enables missing features.

That corresponds to the versions of clang and gcc on ubuntu precise used on newton and by recc.

**Comment by danielmewes** [comment] 2015-06-30 21:43
As @AtnNn explained to me, the thing that triggers this in our code is the comparison of two `boost::optional`s in an `EXPECT_EQ` macro. `EXPECT_EQ` tries to format the values of its arguments in case of an error, for which it uses the `operator<<` overload that isn't properly generated in this case.

For 2.1.0, we're going to work around this by splitting the `EXPECT_EQ` into one that compares whether the optional has a value, and a second one that checks the values themselves if they exist.
This work-around is in code review 3034.

**Comment by danielmewes** [comment] 2015-07-01 02:58
Fixed in https://github.com/rethinkdb/rethinkdb/commit/e1e5fc4c625e13d9c86f09df5c8812cca525e073

**Closed by danielmewes** 2015-07-01 02:58 UTC
