### ISSUE TITLE
init scripts does not restart rethinkdb if process dies

### ISSUE THREAD

**Issue by aaronorosen** [rethinkdb/rethinkdb#5746] opened 2016-05-04 16:46 UTC
I noticed that my rethinkdb instance died (log below from dmesg). After the instance died I had to manually start it again. It would be nice if the init scripts would start rethinkdb again if it dies.  The version of rethinkdb that was being run was: 2.3.0~0trusty

I'm not sure if the crash below is related to a bug in rethinkdb or more so because there was not enough free memory and no swap. This is the first time I've seen this happen. 

[4228574.083768] Out of memory: Kill process 11911 (rethinkdb) score 448 or sacrifice child
[4228574.087446] Killed process 11912 (rethinkdb) total-vm:165464kB, anon-rss:13012kB, file-rss:0kB
[4228574.146697] rethinkdb invoked oom-killer: gfp_mask=0x201da, order=0, oom_score_adj=0
[4228574.146706] rethinkdb cpuset=/ mems_allowed=0
[4228574.146711] CPU: 0 PID: 11915 Comm: rethinkdb Not tainted 3.13.0-76-generic #120-Ubuntu
[4228574.146714] Hardware name: OpenStack Foundation OpenStack Nova, BIOS Bochs 01/01/2011
[4228574.146717]  0000000000000000 ffff8800378af968 ffffffff81724b70 ffff880118823000
[4228574.146723]  ffff8800378af9f0 ffffffff8171f177 ffffffff81067a76 ffff8800378af9c8
[4228574.146726]  ffffffff810c7acc 0000000000000000 ffff88011fff8e38 0000000000000000
[4228574.146730] Call Trace:
[4228574.146745]  [<ffffffff81724b70>] dump_stack+0x45/0x56
[4228574.146752]  [<ffffffff8171f177>] dump_header+0x7f/0x1f1
[4228574.146759]  [<ffffffff81067a76>] ? put_online_cpus+0x56/0x80
[4228574.146786]  [<ffffffff810c7acc>] ? rcu_oom_notify+0xcc/0xf0
[4228574.146793]  [<ffffffff8115308e>] oom_kill_process+0x1ce/0x330
[4228574.146800]  [<ffffffff812d85a5>] ? security_capable_noaudit+0x15/0x20
[4228574.146804]  [<ffffffff811537c4>] out_of_memory+0x414/0x450
[4228574.146809]  [<ffffffff81159b00>] __alloc_pages_nodemask+0xa60/0xb80
[4228574.146816]  [<ffffffff81198073>] alloc_pages_current+0xa3/0x160
[4228574.146828]  [<ffffffff8114fc47>] __page_cache_alloc+0x97/0xc0
[4228574.146831]  [<ffffffff81151655>] filemap_fault+0x185/0x410
[4228574.146837]  [<ffffffff8117652f>] __do_fault+0x6f/0x530
[4228574.146841]  [<ffffffff8117a3b2>] handle_mm_fault+0x482/0xf10
[4228574.146867]  [<ffffffff812096f9>] ? timerfd_poll+0x59/0x70
[4228574.146874]  [<ffffffff81730cb4>] __do_page_fault+0x184/0x570
[4228574.146877]  [<ffffffff81206bc9>] ? ep_scan_ready_list.isra.9+0x199/0x1c0
[4228574.146881]  [<ffffffff81206d23>] ? ep_poll+0x113/0x340
[4228574.146885]  [<ffffffff817310ba>] do_page_fault+0x1a/0x70
[4228574.146889]  [<ffffffff81730729>] do_async_page_fault+0x29/0xe0
[4228574.146893]  [<ffffffff8172d418>] async_page_fault+0x28/0x30
[4228574.146896] Mem-Info:
[4228574.146899] Node 0 DMA per-cpu:
[4228574.146902] CPU    0: hi:    0, btch:   1 usd:   0
[4228574.146903] CPU    1: hi:    0, btch:   1 usd:   0
[4228574.146905] Node 0 DMA32 per-cpu:
[4228574.146907] CPU    0: hi:  186, btch:  31 usd:   0
[4228574.146909] CPU    1: hi:  186, btch:  31 usd:   0
[4228574.146911] Node 0 Normal per-cpu:
[4228574.146913] CPU    0: hi:  186, btch:  31 usd:   0
[4228574.146915] CPU    1: hi:  186, btch:  31 usd:   0
[4228574.146919] active_anon:971038 inactive_anon:81 isolated_anon:0
[4228574.146919]  active_file:40 inactive_file:21 isolated_file:0
[4228574.146919]  unevictable:0 dirty:0 writeback:5 unstable:0
[4228574.146919]  free:21244 slab_reclaimable:2757 slab_unreclaimable:4706
[4228574.146919]  mapped:35 shmem:140 pagetables:4017 bounce:0
[4228574.146919]  free_cma:0
[4228574.146924] Node 0 DMA free:15908kB min:264kB low:328kB high:396kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15992kB managed:15908kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:0kB slab_unreclaimable:0kB kernel_stack:0kB pagetables:0kB unstable:0kB bounce:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
[4228574.146930] lowmem_reserve[]: 0 3488 3935 3935
[4228574.146934] Node 0 DMA32 free:61428kB min:59668kB low:74584kB high:89500kB active_anon:3474744kB inactive_anon:280kB active_file:124kB inactive_file:84kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:3653624kB managed:3574596kB mlocked:0kB dirty:0kB writeback:0kB mapped:76kB shmem:508kB slab_reclaimable:5940kB slab_unreclaimable:12732kB kernel_stack:1400kB pagetables:12500kB unstable:0kB bounce:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:320 all_unreclaimable? yes
[4228574.146939] lowmem_reserve[]: 0 0 447 447
[4228574.146943] Node 0 Normal free:7640kB min:7644kB low:9552kB high:11464kB active_anon:409408kB inactive_anon:44kB active_file:36kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:524288kB managed:457752kB mlocked:0kB dirty:0kB writeback:28kB mapped:64kB shmem:52kB slab_reclaimable:5088kB slab_unreclaimable:6092kB kernel_stack:424kB pagetables:3568kB unstable:0kB bounce:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:58 all_unreclaimable? yes
[4228574.146948] lowmem_reserve[]: 0 0 0 0
[4228574.146951] Node 0 DMA: 1*4kB (U) 0*8kB 0*16kB 1*32kB (U) 2*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 1*1024kB (U) 1*2048kB (R) 3*4096kB (M) = 15908kB
[4228574.146965] Node 0 DMA32: 498*4kB (UEM) 428*8kB (UEM) 396*16kB (UEM) 270*32kB (UEM) 167*64kB (UE) 88*128kB (UE) 49*256kB (UE) 9*512kB (UEM) 2*1024kB (U) 0*2048kB 0*4096kB = 61544kB
[4228574.146978] Node 0 Normal: 67*4kB (UEM) 69*8kB (UEM) 49*16kB (UE) 40*32kB (UE) 19*64kB (UEM) 8*128kB (UE) 4*256kB (UM) 1*512kB (M) 1*1024kB (M) 0*2048kB 0*4096kB = 7684kB
[4228574.146992] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[4228574.146994] 183 total pagecache pages
[4228574.147012] 0 pages in swap cache
[4228574.147014] Swap cache stats: add 0, delete 0, find 0/0
[4228574.147015] Free swap  = 0kB
[4228574.147017] Total swap = 0kB
[4228574.147019] 1048476 pages RAM
[4228574.147020] 0 pages HighMem/MovableOnly
[4228574.147021] 16634 pages reserved
[4228574.147023] [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
[4228574.147029] [  225]     0   225     6482      101      15        0             0 mountall
[4228574.147032] [  635]     0   635     3814       69      12        0             0 upstart-socket-
[4228574.147035] [  723]   102   723     9832      131      22        0             0 dbus-daemon
[4228574.147037] [  792]   101   792    64057     5194      36        0             0 rsyslogd
[4228574.147040] [  813]     0   813     3851       74      12        0             0 upstart-file-br
[4228574.147042] [  860]     0   860    22792      338      42        0             0 nginx
[4228574.147045] [  862]    33   862    23625     1253      44        0             0 nginx
[4228574.147047] [  863]    33   863    23539     1205      44        0             0 nginx
[4228574.147049] [  867]     0   867     3634       41      12        0             0 getty
[4228574.147052] [  870]     0   870     3634       39      12        0             0 getty
[4228574.147054] [  875]     0   875     3634       39      11        0             0 getty
[4228574.147057] [  876]     0   876     3634       40      10        0             0 getty
[4228574.147059] [  878]     0   878     3634       41      11        0             0 getty
[4228574.147062] [  912]     0   912    15344      170      34        0         -1000 sshd
[4228574.147065] [  914]     0   914     4784       43      13        0             0 atd
[4228574.147067] [  928]     0   928     1091       35       8        0             0 acpid
[4228574.147070] [  933]     0   933     4797       63      13        0             0 irqbalance
[4228574.147073] [ 1249]     0  1249     3634       41      11        0             0 getty
[4228574.147076] [ 1258]     0  1258     3196       37      13        0             0 getty
[4228574.147078] [11911]   106 11911   698907   452743    1340        0             0 rethinkdb
[4228574.147081] [11998]   106 11998    44439     3768      72        0             0 rethinkdb
[4228574.147084] [15257]  1001 15257   180980    13653      69        0             0 nodejs
[4228574.147086] [15258]  1001 15258   180219     8428      61        0             0 nodejs
[4228574.147089] [15259]  1001 15259   179833     8248      58        0             0 nodejs
[4228574.147091] [15765]  1001 15765   181021    13785      69        0             0 nodejs
[4228574.147094] [10508]     0 10508     4868       49      13        0             0 upstart-udev-br
[4228574.147097] [10511]     0 10511    12397      111      27        0         -1000 systemd-udevd
[4228574.147100] [10580]     0 10580    10862       89      27        0             0 systemd-logind
[4228574.147102] [17984]  1001 17984   376765   142939     399        0             0 nodejs
[4228574.147105] [17986]  1001 17986   298699    64125     439        0             0 nodejs
[4228574.147107] [24864]  1001 24864   451859   219284     744        0             0 nodejs
[4228574.147110] [32735]     0 32735     1081       22       8        0             0 collectdmon
[4228574.147113] [32737]     0 32737   233240     1453      81        0             0 collectd
[4228574.147115] [26328]     0 26328     5913       63      17        0             0 cron
[4228574.147118] [  565]  1001   565   204331    21337     102        0             0 nodejs
[4228574.147120] [ 1509]  1001  1509   402796     7001      68        0             0 phantomjs
[4228574.147123] [ 2767]  1000  2767    17319     5337      36        0             0 rethinkdb-expor
[4228574.147125] Out of memory: Kill process 11911 (rethinkdb) score 448 or sacrifice child
[4228574.149956] Killed process 11911 (rethinkdb) total-vm:2795628kB, anon-rss:1810972kB, file-rss:0kB

**Comment by danielmewes** [comment] 2016-05-04 20:32
Thanks for opening a feature request @aaronorosen . This is a duplicate of https://github.com/rethinkdb/rethinkdb/issues/5746 .
This will become very easy once we get https://github.com/rethinkdb/rethinkdb/issues/2037 in.

**Closed by danielmewes** 2016-05-04 20:32 UTC

**Comment by encryptio** [comment] 2016-05-04 21:23
@danielmewes this *is* #5746. Instead, this is a duplicate of #2327.

**Comment by danielmewes** [comment] 2016-05-04 21:28
@encryptio Thanks, mixed up the links (#2327 was the one I meant). I edited my post to point to the right issue.
