### ISSUE TITLE
Error: Guarantee failed: [mandatory - end_rcost >= free_space(sizer) / 2 - leaf_epsilo n(sizer)]

### ISSUE THREAD

**Issue by soplakanets** [rethinkdb/rethinkdb#4867] opened 2015-09-20 11:43 UTC
Hi. Yet another "Guarantee failed" error. Which happened twice for me already on same db/data.

Stacktarce:
```
2015-09-20T04:39:06.650146895 1801.609996s error: Error in src/btree/leaf_node.cc at line 1029:
2015-09-20T04:39:06.650277653 1801.610127s error: Guarantee failed: [mandatory - end_rcost >= free_space(sizer) / 2 - leaf_epsilo
n(sizer)]
2015-09-20T04:39:06.650299570 1801.610148s error: Backtrace:
2015-09-20T04:39:06.915002574 1801.874856s error: Sun Sep 20 04:39:06 2015\n\n1: backtrace_t::backtrace_t() at ??:?\n2: format_ba
cktrace(bool) at ??:?\n3: report_fatal_error(char const*, int, char const*, ...) at ??:?\n4: leaf::split(value_sizer_t*, leaf_nod
e_t*, leaf_node_t*, btree_key_t*) at ??:?\n5: check_and_handle_split(value_sizer_t*, buf_lock_t*, buf_lock_t*, superblock_t*, btr
ee_key_t const*, void*, value_deleter_t const*) at ??:?\n6: apply_keyvalue_change(value_sizer_t*, keyvalue_location_t*, btree_key_t const*, repli_timestamp_t, value_deleter_t const*, key_modification_callback_t*, delete_mode_t) at ??:?\n7: kv_location_set(keyvalue_location_t*, store_key_t const&, ql::datum_t, repli_timestamp_t, deletion_context_t const*, rdb_modification_info_t*) at ??:?\n8: rdb_replace_and_return_superblock(btree_loc_info_t const&, btree_point_replacer_t const*, deletion_context_t const*, promise_t<superblock_t*>*, rdb_modification_info_t*, profile::trace_t*) at ??:?\n9: do_a_replace_from_batched_replace(auto_drainer_t::lock_t, fifo_enforcer_sink_t*, fifo_enforcer_write_token_t const&, btree_loc_info_t const&, one_replace_t, ql::configured_limits_t const&, promise_t<superblock_t*>*, rdb_modification_report_cb_t*, bool, ql::datum_t*, profile::trace_t*, std::set<std::string, std::less<std::string>, std::allocator<std::string> >*) at ??:?\n10: std::_Function_handler<void (), std::_Bind<void (*(auto_drainer_t::lock_t, fifo_enforcer_sink_t*, fifo_enforcer_write_token_t, btree_loc_info_t, one_replace_t, ql::configured_limits_t, promise_t<superblock_t*>*, rdb_modification_report_cb_t*, bool, ql::datum_t*, profile::trace_t*, std::set<std::string, std::less<std::string>, std::allocator<std::string> >*))(auto_drainer_t::lock_t, fifo_enforcer_sink_t*, fifo_enforcer_write_token_t const&, btree_loc_info_t const&, one_replace_t, ql::configured_limits_t const&, promise_t<superblock_t*>*, rdb_modification_report_cb_t*, bool, ql::datum_t*, profile::trace_t*, std::set<std::string, std::less<std::string>, std::allocator<std::string> >*)> >::_M_invoke(std::_Any_data const&) at ??:?\n11: coro_pool_t<std::function<void ()> >::worker_run(std::function<void ()>, auto_drainer_t::lock_t) at ??:?\n12: callable_action_instance_t<std::_Bind<std::_Mem_fn<void (coro_pool_t<std::function<void ()> >::*)(std::function<void ()>, auto_drainer_t::lock_t)> (coro_pool_t<std::function<void ()> >*, std::function<void ()>, auto_drainer_t::lock_t)> >::run_action() at ??:?\n13: coro_t::run() at ??:?
2015-09-20T04:39:06.915224254 1801.875073s error: Exiting.
```

System info:
```
$ rethinkdb --version
rethinkdb 2.1.4~0trusty (GCC 4.8.2)
$ uname -a
Linux rdb02 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I can not say which query caused it though or which table was targeted. We have a couple of background jobs doing heave read/write which probably triggered it. Restarting the server helped but it reappeared again.

**Comment by danielmewes** [comment] 2015-09-21 17:34
Sorry you ran into this.
We're investigating...

**Comment by danielmewes** [comment] 2015-09-21 17:43
This is not a data corruption issue by the way.
I have to double check, but it's probably safe to simply remove the guarantee to keep your servers running @soplakanets . We can send you a special binary to use if you want to until we release a full fix for this.

**Comment by danielmewes** [comment] 2015-09-22 04:09
@soplakanets do you have older tables from RethinkDB 2.1.3 (or earlier) or did you re-create everything with RethinkDB 2.1.4?

**Comment by soplakanets** [comment] 2015-09-22 06:33
@danielmewes I have some tables from 1.x. What do you mean by recreating? Dump/restore would suffice?

**Comment by danielmewes** [comment] 2015-09-22 19:08
@soplakanets Yes, dump/restore would count.
I'm not recommending doing that just yet though.

We're still looking into how this issue could happen. We were just wondering if it could be something in the data. Is there a chance you could upload a new copy of your data directory (unfortunately you'll need to briefly shut down the server before making the copy)? I've enabled the `scp` access to our upload server again like last time.

**Comment by soplakanets** [comment] 2015-09-23 08:23
@danielmewes The issue started to reappear all to often and I had dropped all auto-generated tables we had, after that the issue does not appear anymore. I do not think the data I have now will help you.

**Comment by danielmewes** [comment] 2015-11-17 01:32
We have done some extensive testing of the btree code trying to catch this bug, but couldn't reproduce it. I'm going to close this issue since there's nothing else we can do at the moment without any data. It's possible that this crash was an after effect of some corruption in the data files from an earlier version.

**Closed by danielmewes** 2015-11-17 01:32 UTC
Labels: pr:high, tp:bug
