### ISSUE TITLE
We do not handle `-0` correctly.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3637] opened 2015-01-22 00:55 UTC
```
irb(main):4759:0> r.table('test').insert([{id: 0}, {id: r(0).mul(-1)}]).run
{"deleted"=>0, "errors"=>0, "inserted"=>2, "replaced"=>0, "skipped"=>0, "unchanged"=>0}
irb(main):4760:0> r.table('test').run
#<RethinkDB::Cursor:70353332560980 (enumerable): r.table("test")
[{"id"=>0}, {"id"=>0}]>
irb(main):4761:0> r(0).eq(r(0).mul(-1)).run
true
```

I'm almost certain that having two values which are considered equal but serialize to different values is a bug, and in any case it's incorrect because the distinction is discarded by our clients.

@danielmewes -- this is a pretty bad bug, but it's old and I'm not sure it's worth holding the release for.

**Comment by gchpaco** [comment] 2015-01-22 00:59
FYI: `-0` and `+0` are different in IEEE floating point, although I think they're supposed to be equal.  The difference matters sometimes in the complex plane, I think.

**Comment by danielmewes** [comment] 2015-01-22 01:05
This is not unreasonable given that we use doubles in some places, but it's pretty weird that we have an inconsistency between indexes and `eq`.

I wonder what the JSON standard with respect to 0 and -0 is, if it says anything about that case at all.

**Comment by danielmewes** [comment] 2015-01-22 01:09
@gchpaco Oh if they are supposed to evaluate as equal according to the standard then that actually explains why `eq` says they are equal, but our serialization is different.

We should probably just standardize on one and convert any -0 to +0.

I don't think it's release critical, and there's the problem that this affects the primary index so we have to think about how to fix this a little more.

**Comment by gchpaco** [comment] 2015-01-22 01:19
The reason why `-0` and `+0` both exist is important for subtle numerical reasons (mostly to do with the complex plane, as I recall).  @mlucy and I both looked at this, and came up with some weird stuff.  In Chrome:
```javascript
> -0
< -0
> JSON.stringify(-0)
< "0"
> JSON.parse("-0")
< -0
```
That is Chrome does not roundtrip this itself.  Python as it happens does handle this properly:
```python
>>> import json
>>> -0.
-0.0
>>> json.dumps(-0.0)
'-0.0'
>>> json.loads("-0.0")
-0.0
```
In Ruby, I get this:
```ruby
irb(main):001:0> -0.0
=> -0.0
irb(main):002:0> require 'json'
=> true
irb(main):003:0> -0.0.to_json
=> "-0.0"
irb(main):007:0> JSON.parse("[-0.0]")
=> [-0.0]
```
(I have to wrap it in an array for some weird Ruby reason).

**Comment by gchpaco** [comment] 2015-01-22 01:22
FYI node v0.10.35 does not distinguish:
```javascript
> -0.0
0
> JSON.stringify(-0.0)
'0'
> JSON.parse("-0.0")
0
```

**Comment by mlucy** [comment] 2015-01-22 01:23
Alright, so here's the current state of things:
* You can have two values which compare equal but serialize to different things.  I'm pretty sure our code was written assuming that this *isn't* true, and that if you actually have data like that in one of your tables it's going to trip an assert somewhere.
* Ruby and JS both discard information on whether 0 is negative in some circumstances (Ruby parses "-0" incorrectly but "-0.0" correctly, for example), which means that currently you can have two rows in your table which are different but which are indistinguishable in the client with our current JSON serialization.  It also means that `x = r.table('test').get(key).run; r.table('test').get(key).delete.run; r.table('test').insert(x).run` is no longer a no-op, and we've worked very hard to preserve that property in the past.

We need to fix that, but it's not clear what the correct behavior is.

**Comment by gchpaco** [comment] 2015-01-22 01:48
Added fun:
```python
>>> -0.0 == 0.0
True
>>> -0.0 < 0.0
False
>>> -0.0 > 0.0
False
```

**Comment by danielmewes** [comment] 2015-01-22 01:48
After talking to @gchpaco I've changed my mind in that I now think that it might be better to support both -0 and +0 as distinct values. I suggest that instead of making them the same, we change our implementation of datum equality to consider them as different.

This has the big advantage that we won't break any indexes.

There's also a concern that the difference between -0 and +0 might matter quite a bit for some geo operations, which suggests that making them the same in datums could lead to bad behavior.

Apart from changing our comparison function for datums, there's the separate question of how clients serialize and deserialize -0. I'm not sure how much we can do about that. I personally also think that it's enough of a corner case to ignore.

**Comment by gchpaco** [comment] 2015-01-22 01:50
Yeah, client serialization / deserialization is Fun and I don't think we can work around it easily in something like Chrome.  FYI Python has the same flaw that Ruby has around `-0`, even when decoding JSON (integer conversion generally does not respect -0.0 / +0.0).

**Comment by danielmewes** [comment] 2015-01-22 01:51
We could consider patching cJSON on the server to serialize -0 as `-0.0`, so that at least Ruby would preserve the sign.

**Comment by gchpaco** [comment] 2015-01-22 01:54
I'm all for that, actually.  Would work around the Python limitation too.

**Comment by gchpaco** [comment] 2015-01-22 02:12
For folks looking for larger discussion of the -0 issue, see http://en.wikipedia.org/wiki/Signed_zero

**Comment by danielmewes** [comment] 2015-01-22 03:35
We could also use smart (i.e. non-lexicographical) key comparison functions in the btree to make -0 and 0 be considered equal, and thereby making ReQL equality consistent with btree key equality again. There's a risk that doing so for the primary key will have an impact on performance, but that's just speculation and we could test it pretty easily.

It seems like we want to use custom comparison functions for the btree soonish anyway (e.g. to implement collation-aware secondary indexes), so it wouldn't add that much development cost overall.
The disadvantage is that this would break existing tables if they contain a -0 primary key (because it would now sort to a slightly different location). We could efficiently detect this though by maintaining the old comparison semantics for this purpose, and could even offer users to fix the issue by re-inserting the problematic document to its new location in the tree. Only if there was both a -0 and +0 key we could not migrate the table automatically. In that case we could potentially just change the primary key of that document to something like `"THIS_USED_TO_BE_NEGATIVE_0_<UUID>"`, re-insert it, and tell the user about the conflict.

**Comment by danielmewes** [comment] 2015-01-22 20:24
... or of course rather than replacing the key comparison function for primary keys we could just make -0 serialize as +0 in key serialization. That sounds much easier and avoids a performance regression for primary key comparison.

**Comment by mlucy** [comment] 2015-02-07 23:57
@danielmewes -- how important do you think it is to get this into 2.0?

**Comment by danielmewes** [comment] 2015-02-09 22:18
Just talked about this with @Tryneus.

I think we should do the following:
- change the key serialization function to serialize -0 the same way it serializes +0
- patch cJSON on the server to serialize `-0` as `-0.0` to make Ruby preserve -0
- don't worry about other languages that don't preserve -0 (JS). There's not much we can do there.
- provide a script that users can run that checks if they have any documents with -0 in their primary keys. I think so few users (if any) are going to be affected that this alone will be enough, but optionally we could offer them to re-insert those documents.

I think we should try to get this into 2.0.

**Comment by mlucy** [comment] 2015-02-09 22:51
Wait, so I'd be able to write `r.table('test').get(0)['id']` and get back either `-0.0` or `0.0`?  If we're going to make them serialize to the same key, we might just want to turn `-0.0` into `0` and be done with it (or at least always send `0` back to the user).

**Comment by mlucy** [comment] 2015-02-09 22:52
(Tagging this as a RQL_proposal since we'll probably be changing the query language in some way to fix it.)

**Comment by danielmewes** [comment] 2015-02-09 23:01
@mlucy 
> Wait, so I'd be able to write `r.table('test').get(0)['id']` and get back either `-0.0` or `0.0`?

Yes, since according to the IEEE standard -0 and 0 compare equal apparently.

We will still *preserve* the -0 in the document though, which makes this different from generally turning -0 into 0.

**Comment by mlucy** [comment] 2015-02-09 23:07
Are we sure that's what we want (especially since there's the problem of JS being able to parse/generate it)?  Why is that superior to turning `-0` into `0`?

**Comment by danielmewes** [comment] 2015-02-10 03:16
@mlucy Mostly because we won't silently modify user's data. The distinction between 0 and -0 can be important for some users.

**Comment by Tryneus** [comment] 2015-03-11 04:35
The fix for key serialization and the script to check for inaccessible rows is up in review 2708.

**Comment by Tryneus** [comment] 2015-03-11 04:58
This has been approved and the fix, tests, and script merged to `next` in commits 54a467e, 6032cb4, and 8863ac1 (respectively), and cherry-picked into `v2.0.x` in commits 1592d3e, 7b7a3d1, and 58d07ff.

A user with the python driver installed who wants to check for rows made inaccessible by the upgrade to 2.0 can run `python -m rethinkdb._negative_zero_check [args]` to get a list of affected rows.

**Closed by Tryneus** 2015-03-11 04:58 UTC
Labels: tp:bug, tp:RQL_proposal

**Comment by danielmewes** [comment] 2015-03-11 09:14
Minor nitpick post-review:
This line https://github.com/rethinkdb/rethinkdb/blob/next/src/rdb_protocol/datum.cc#L617 doesn't do what it looks like it does.
```
 // Sort negative zero as equivalent to 0
double value = as_num();
if (value == -0.0) {
    value = abs(value);
}
```

Since both +0.0 and -0.0 compare equal to -0.0, the `if` will trigger on both. It stil works, since `abs(+0.0)` is a no-op though.
Feel free to leave it as it is, just thought it would be worth pointing out that testing for -0.0 isn't generally that easy.

**Comment by Tryneus** [comment] 2015-03-11 15:00
@danielmewes, I know, I just wanted it be more obvious what the code was trying to do.
