### ISSUE TITLE
JSON Decode Error upon asyncio connection

### ISSUE THREAD

**Issue by Phxntxm** [rethinkdb/rethinkdb#6086] opened 2016-08-30 22:30 UTC
Traceback: https://ghostbin.com/paste/qk7mm
I'm unsure what is causing this, I know what I'm sending to r.connect() is fine, trying to set the variables manually instead of unpacking a dictionary does the same exact thing, even if I only specify the host to connect to and nothing else, same error.

When removing:
`r.set_loop_type("asyncio")`
And just removing await, I am able to connect fine, so I do not know what the issue may be.

**Comment by danielmewes** [comment] 2016-08-30 23:10
How exactly are you calling `r.connect`?

Are you using the latest Python driver (2.3.0.post6)?

**Comment by Phxntxm** [comment] 2016-08-30 23:15
```
async def get_content(key: str):
    r.set_loop_type("asyncio")
    conn = await r.connect(host='REDACTED')

loop = asyncio.get_event_loop()
loop.run_until_complete(get_content('test'))
```

```
>>> r.__version__
'2.3.0.post6'
```

**Comment by danielmewes** [comment] 2016-08-30 23:25
I tried this locally on Python 3.5.2 and it seemed to work. Does this error happen every time for you or does it work occasionally?

Which RethinkDB server version are you connecting to? Are you using a (admin) password with the RethinkDB server?

**Comment by Phxntxm** [comment] 2016-08-30 23:31
No admin password, it is everytime I try to connect
```
rethinkdb --version
rethinkdb 2.3.5 (GCC 4.8.2)
```

I edited the part where it tries to decode the response, and printed right before that happened, and it doesn't print anything:
```
            print("Response was: {}".format(response))
            json = self._json_decoder.decode(response)
```

```
Response was:
```

**Comment by Phxntxm** [comment] 2016-08-30 23:43
After a little more testing, it appears this only happens if I have a driver key and cert setup, the same cert works for normal connections but not with asyncio
In configuration file for the instance:
```
driver-tls-key=/etc/rethinkdb/instances.d/key.pem
driver-tls-cert=/etc/rethinkdb/instances.d/cert.pem
```

The exact line I'm using to test atm:
```
async def get_content(key: str):
    r.set_loop_type("asyncio")
    conn = await r.connect(host='REDACTED', ssl={'ca_certs': '/etc/rethinkdb/instances.d/cert.pem'})
```

**Comment by danielmewes** [comment] 2016-08-30 23:45
Ah, probably a duplicate of https://github.com/rethinkdb/rethinkdb/pull/5921 then. Sorry you had to run into this. There's a fix on the way.

**Closed by danielmewes** 2016-08-30 23:45 UTC
Labels: Python, tp:bug
