### ISSUE TITLE
RethinkDB insert on java is too Slow

### ISSUE THREAD

**Issue by ahmetbardiz** [rethinkdb/rethinkdb#6475] opened 2017-08-23 16:12 UTC
I have made a simple insert test by just looping the same object with MongoDb and RethinkDB. 10K documents took just 2 seconds to insert on Mongo. However I faced with very extraordinary situation that RethinkDB took 20 minutes with same notations. The java code is below. I doubt myself whether I made something wrong.

import org.bson.Document;
import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.rethinkdb.RethinkDB;
import com.rethinkdb.gen.ast.Table;
import com.rethinkdb.net.Connection;

public class App {
	public static final RethinkDB r = RethinkDB.r;

	public static void main(String[] args) {
		Connection reThinkConn = r.connection().hostname("localhost").port(28015).connect();
		Table reTable = r.table("myDb");

		MongoClient mongoClient = new MongoClient( "localhost" , 27017 );
		MongoDatabase mongoDatabase = mongoClient.getDatabase("myDb");
		MongoCollection<Document> mongoCollection =mongoDatabase.getCollection("myCollection");
	    
		
		Thread mongo = new Thread(new Runnable() {

			@Override
			public void run() {
				long startTime = System.currentTimeMillis();
				System.out.println("başladı mo");
				for (int i = 0; i < 10000; i++) {
					Document document = new Document("title", "MongoDB") 
				    	      .append("id", i)
				    	      .append("description", "database") 
				    	      .append("likes", 100) 
				    	      .append("url", "http://www.tutorialspoint.com/mongodb/") 
				    	      .append("by", "tutorials point");
					mongoCollection.insertOne(document); 
				}
				long estimatedTime   = System.currentTimeMillis() - startTime;
				double seconds = (double)estimatedTime/1000;
				System.out.println("Mongo Time: "+seconds);	
			}
		});
		mongo.start();

		Thread rethink = new Thread(new Runnable() {
			@Override
			public void run() {
				long startTime = System.currentTimeMillis();
				for (int i = 0; i < 10000; i++) {
					Document document = new Document("title", "MongoDB") 
				    	      .append("id", i)
				    	      .append("description", "database") 
				    	      .append("likes", 100) 
				    	      .append("url", "http://www.tutorialspoint.com/mongodb/") 
				    	      .append("by", "tutorials point");
					reTable.insert(document).run(reThinkConn);

				}
				long estimatedTime   = System.currentTimeMillis() - startTime;
				double seconds = (double)estimatedTime/1000;
				System.out.println("Rethink Time: "+seconds);
			}
		});
		rethink.start();

	}
}

**Comment by robertjpayne** [comment] 2017-09-01 13:11
By default RethinkDB's writes flush to disk (hard durability), I may be mistaken but I'm fairly certain MongoDB's are not unless you setup the write concern properly.

You should try to run your RethinkDB writes using soft durability (see the docs for more info) and report back if you still think it is excessively slow.

Also you'll get way better performance batching your writes.

**Comment by marshall007** [comment] 2017-09-07 03:24
@robertjpayne is correct. You can increase write throughput by tweaking your consistency guarantees ((see docs)[https://rethinkdb.com/docs/consistency/]) and batching writes. Closing since this is not a bug, but feel free to continue discussion.

**Closed by marshall007** 2017-09-07 03:24 UTC
