### ISSUE TITLE
rethinkdb restore - should use TMPDIR env variable

### ISSUE THREAD

**Issue by nickpoorman** [rethinkdb/rethinkdb#2955] opened 2014-08-25 20:20 UTC
When I do a `rethinkdb restore` it tries to untar the huge database file into my /tmp directory which is impossible because the partition is too small.

There should be an option to specify the TMPDIR.

**Comment by larkost** [comment] 2016-07-16 03:01
I am going to take this one over, as I am working "in the neighborhood".

**Comment by larkost** [comment] 2016-07-19 23:03
I can't reproduce this issue with the current `next`, and so am going to close it. I don't see an obvious place where it got fixed along the way, but checks with driver hacked to print the file locations it is using show everything where I put them with `TMPDIR`, both when using the driver directly and indirectly through the `rethinkdb` binary.

Just to be pedantic: the version I tested (minus two `print` statements) will be out with the 2.4 version of RethinkDB, but is available in `next` at the moment.

**Closed by larkost** 2016-07-19 23:03 UTC
Labels: good_for_contributors, Python, tp:enhancement
