### ISSUE TITLE
2.1 arity errors + null.info()

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#4803] opened 2015-09-07 01:29 UTC
I just tried to run the test for reqlite with rethinkdb 2.1.

The arity errors are returned without frames (granted that it used to return an empty array) and therefore the driver doesn't print the query anymore. Was that done on purpose? I tested 2.0.4 and backtraces are still there.

One more thing `r.expr(null).info()` since 2.0.4 doesn't fill the `value` field. It still does for 2.0.3.
Same question. Was it done on purpose?

If it was done on purpose, feel free to close the issue and I'll fix reqlite.
If it's not I'll just be lazy and wait for an update on your side :-)

**Comment by mlucy** [comment] 2015-09-07 18:20
The change to `info` was intentional (I can't find the issue, but I think it was making the return value consistent with `r.minval.info` etc.).

Missing backtraces for arity errors sounds like a bug to me.

**Comment by neumino** [comment] 2015-10-14 16:10
The issue with backtraces is actually an issue in the JS driver. The backtrace is properly printed in 2.0 but not 2.1.

**Comment by mlucy** [comment] 2015-10-14 19:10
@neumino -- are all backtraces broken in the JS driver, or is it just some small subset?

**Comment by mlucy** [comment] 2015-10-14 19:11
Moving into 2.1.x if this is a driver regression rather than just the server changing behavior (ping @deontologician).

**Comment by deontologician** [comment] 2015-10-14 20:00
Could you paste which test you're using to get this? I can't think of any changes off the top of my head that would affect printing or backtraces

**Comment by neumino** [comment] 2015-10-15 01:09
@mlucy -- only the backtraces for arity errors as far as I can tell.

@deontologician -- `r.time(1986, 11, 3)` for example doesn't include the backtrace anymore.

**Comment by neumino** [comment] 2015-10-15 01:38
Err actually it's because the server return a ReqlCompileError now instead of a ReqlRuntimeError and that the driver doesn't build a backtrace for ReqlCompileError.

**Comment by neumino** [comment] 2015-10-15 01:58
For what it's worth, if an argument is `r.args`, the server returns an ReqlRuntimeError, not a ReqlCompileError

**Comment by danielmewes** [comment] 2015-10-15 02:04
> Err actually it's because the server return a ReqlCompileError now instead of a ReqlRuntimeError and that the driver doesn't build a backtrace for ReqlCompileError.

Ah that explains why it changed in 2.1.

Is there a reason for why we don't attach backtraces to ReqlCompileErrors or is that just an oversight? (@mlucy, @deontologician )

**Comment by deontologician** [comment] 2015-10-15 02:14
It looks like the reason is that CompileErrors don't inherit from RuntimeErrors, which is where the query formatting code goes. I think this should be simple, just moving the formatting code to the top level exception (ReqlError)

**Comment by deontologician** [comment] 2015-10-15 02:28
OK, fixing this has set of a raft of test failures hinging based on whether or not the error message ends with a period...

**Comment by deontologician** [comment] 2015-10-15 02:41
OK, the code is up in 29c1305 Once another review I have goes through I'll put this one up

**Comment by danielmewes** [comment] 2015-11-17 01:36
@deontologician Is this still waiting on something or can you put this up for review now?

**Comment by deontologician** [comment] 2015-11-17 01:45
I actually have the CR created I just forgot about it. I'll put it up for review

**Comment by deontologician** [comment] 2015-11-17 03:09
OK, reviewed by @Tryneus in CR 3284, merged to next

**Comment by deontologician** [comment] 2015-11-17 03:09
@danielmewes do you think we should backport this?

**Closed by deontologician** 2015-11-17 03:09 UTC
Labels: tp:bug

**Comment by danielmewes** [comment] 2015-11-17 19:32
@deontologician Yeah let's backport it.

**Comment by deontologician** [comment] 2015-11-23 21:54
Ok, finally did this. Cherry-picked onto 2.2.x in dcc80d9
