### ISSUE TITLE
e: Query terminated by an unknown cause in ...

### ISSUE THREAD

**Issue by utvk** [rethinkdb/rethinkdb#5113] opened 2015-11-18 23:34 UTC
Hi,

I have an issue with a table when I try to copy it to a new table using the data explorer. The job seems to run well for some time, but after a while I get the following error: e: Query terminated by an unknown cause in ... 

Wonder how I can dig deeper here to find the error message or if it's possible to understand the origin of the error. It's a table with around 250K entries that I'm trying to copy.

To copy I use the following command: r.db('db').table('table1').insert(r.db('db').table('table2').pluck('field'))

Table has around 250K entries.

It runs for some time, then fails with the error above. Tried to look in the output from rethinkdb but nothing there.

**Comment by danielmewes** [comment] 2015-11-19 00:09
I think this might just be timing out, which is specific to the Data Explorer.
Can you try running this query with one of the other clients? (Python, node.js, Ruby or others)

It looks like the message isn't right though. Pinging @Tryneus about that.

**Comment by NameOfTheDragon** [comment] 2016-03-25 18:21
You can close this if you want, but I think you're putting your head into the sand. It is a massive usability issue.  "Query failed for an **_unknown cause_**". Not "the connection timed out" or "the data explorer has a limit of 5 minutes". An Unknown Cause, which apparently is completely known. How's a user supposed to figure out what the problem is?

**Comment by danielmewes** [comment] 2016-03-25 18:27
@NameOfTheDragon Yes I agree, that's what this issue is about and why it's open.
We have no intention of closing it before it's fixed. Sorry if there was a misunderstanding.

**Comment by NameOfTheDragon** [comment] 2016-03-25 18:32
Yes you're right. I hadn't realised the original issue was still open. My bad.

**Comment by nighelles** [comment] 2016-04-29 22:02
This should be fixed in next, implemented in nighelles/5113.

**Closed by nighelles** 2016-04-29 22:02 UTC
Labels: tp:bug

**Comment by danielmewes** [comment] 2016-04-29 22:09
@nighelles can you cherry-pick to v2.3.x as well please?

**Comment by nighelles** [comment] 2016-04-29 22:25
Cherry-picked into v2.3.x in 59c99da
