### ISSUE TITLE
JavaScript: ChangeFeed on get(...).pluck(...) error

### ISSUE THREAD

**Issue by rclai** [rethinkdb/rethinkdb#4267] opened 2015-05-22 18:34 UTC
```
$ rethinkdb --version
rethinkdb 2.0.1~0trusty (GCC 4.8.2)
```
```js
// Using 2.0.0 driver
var r = require('rethinkdb');

r.connect({ host: 'localhost',
  port: 28015,
  db: 'test' },
function(err, conn) { 
  r.table('cities').get("374d2d80-4a1e-4c33-8900-506a85a62384").pluck("id", "b", "c").changes().run(conn, function(err, cursor) {
    if (err) {
      throw new Error(err)
    } else {
      cursor.each(console.log)
    }
  });
});
```
Error:
```
Error: RqlRuntimeError: Cannot convert OBJECT to SEQUENCE in:
r.table("cities").get("374d2d80-4a1e-4c33-8900-506a85a62384").pluck("id", "b", "c").changes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    at /root/rethink-node-app/index.js:9:13
    at tryCatcher (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:24:31)
    at Promise.errorAdapter (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/nodeify.js:35:34)
    at Promise._settlePromiseAt (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:528:21)
    at Promise._settlePromises (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

Shouldn't this work?

**Comment by thejsj** [comment] 2015-05-22 18:49
`pluck` is not yet supported in changefeeds. You can, however, do the following: 

```
r.table('cities').get("374d2d80-4a1e-4c33-8900-506a85a62384").changes()('new_val').pluck("id", "b", "c")
```
The [documentation on chagenfeeds](http://rethinkdb.com/docs/changefeeds/javascript/) seems to imply that you can use `.pluck`, but that's not the case.

**Comment by mlucy** [comment] 2015-05-22 22:48
@rclai -- this isn't supported right now.  You can track progress on adding this at https://github.com/rethinkdb/rethinkdb/issues/3623 .  In the meantime you can work around it by writing `r.table('test').get(0).changes().map(function(row) { return {new_val: row('new_val').pluck(FIELDS), old_val: row('old_val').pluck(FIELDS)})`.

**Comment by mlucy** [comment] 2015-05-22 22:48
(Closing as a duplicate of #3623.)

**Closed by mlucy** 2015-05-22 22:48 UTC

**Comment by marshall007** [comment] 2015-05-22 23:05
@rclai are you trying to filter the changefeed to only include documents where `id`, `b`, or `c` have changed? If so the workaround is a bit more involved than what @mlucy suggested. I've wanted to do the same thing before (see #3099). Here's what I've used:

```js
var fields = r.expr([ 'id', 'b', 'c' ]);
r.table('cities').get(...).changes().filter(function (row) {
  return fields.contains(function (field) {
    // compare the fields we care about
    return row('new_val')(field).ne(row('old_val')(field)).default(true);
  })
})
```

**Comment by rclai** [comment] 2015-05-23 14:34
Okay, thanks guys.

**Comment by graphicore** [comment] 2017-11-15 03:52
Maybe this is obvious (also  #3623 kind of mentions it), but 

```js
r.table('cities').getAll("a-unique-id").pluck("id", "b", "c").changes()...
```
Seems works fine. I'm not sure though if a filter like the one of @marshall007 is needed here to avoid change notes when something else than the plucked fields in the doc has changed.
