### ISSUE TITLE
getAll always empty for nested field

### ISSUE THREAD

**Issue by xpepermint** [rethinkdb/rethinkdb#4268] opened 2015-05-22 21:32 UTC
Hi. I'm using `rethinkdb-2.0.2`. When running `getAll` on secondary index of a nested field always returns `no results`.

```js
r.db('miner').tableCreate('tracks');
r.db('miner').table('tracks').indexCreate('key');
r.db('miner').table('tracks').indexCreate('identity.key');
r.db('miner').table('tracks').insert({
  key: 2,
  identity: { key: '2' }
});
r.db('miner').table('tracks').getAll('2' {index: 'key'}); // works (the result returns 1 document)
r.db('miner').table('tracks').getAll('2' {index: 'identity.key'}); // not working (no documents)
```

Is that expected? How can I test that my indexes are working?

**Comment by thenightwassave** [comment] 2015-05-22 21:38
Indexing by nesting fields doesn't work the way you are trying to do it. You need to use:

````
r.db('miner').table('tracks').indexCreate('indexName', r.row("identity")("key"));
````

For 'indexName' you could use 'identity.key' but that is just a string identifier. 'identityKey' or anything else would be just as valid.

More info available at http://rethinkdb.com/api/javascript/index_create/

**Comment by deontologician** [comment] 2015-05-22 21:39
Hi @xpepermint this is expected. `indexCreate('identity.key')` looks for a top level document like `{"identity.key": "foo"}`, so it won't do what you want. Instead you can use a function to define the index:

```js
r.db('miner').table('tracks').indexCreate('identity.key', r.row('identity')('key'))
```

Note that `identity.key` is just a name we gave the index so we can refer to it later, it can be any string you like.

Then you can do queries for it with:

```js
r.db('miner').table('tracks').getAll('2' {index: 'identity.key'})
```

And it will do what you expect.

Incidentally, a normal key index is really just a function index underneath. These two are identical:

```js
r.table('foo').indexCreate('bar')
r.table('foo').indexCreate('bar', r.row('bar'))
```

Hope that helps. I'm closing this since it's not a bug, but feel free to ask any more questions you want here and we'll answer them for you.

**Closed by deontologician** 2015-05-22 21:39 UTC

**Comment by xpepermint** [comment] 2015-05-22 21:44
I missed that part. Thanks!
