### ISSUE TITLE
Data Explorer: name and save queries 

### ISSUE THREAD

**Issue by FLIR31207** [rethinkdb/rethinkdb#4172] opened 2015-05-01 07:43 UTC
I love the "history" feature of the Data Explorer. It would be even better if one could give a name to queries and mark them as "keep" or something similar so when one cleans up the history, those marked queries do not get removed.

**Comment by deontologician** [comment] 2015-05-01 17:04
Closing as a dupe of #4105, but feel free to comment there if there is something specific you'd like to see

**Comment by deontologician** [comment] 2015-05-01 17:05
I edited my previous comment to refer to the right issue

**Closed by deontologician** 2015-05-01 17:04 UTC
