### ISSUE TITLE
Write-after-free during blob append

### ISSUE THREAD

**Issue by dekimir** [rethinkdb/rethinkdb#5991] opened 2016-07-22 18:14 UTC
When I change a few numbers in `blob_test.cc` and run `make unit`, I get the following error on MacOS:

```
rethinkdb-unittest(84138,0x700000104000) malloc: *** error for object 0x7fe14b016c08: incorrect checksum for freed object - object was probably modified after being freed.
```

Here are the changes I've made to get this error:

```diff
diff --git a/src/unittest/blob_test.cc b/src/unittest/blob_test.cc
index 8d71fae..8ee0b55 100644
--- a/src/unittest/blob_test.cc
+++ b/src/unittest/blob_test.cc
@@ -24,7 +24,7 @@ public:
     }
 
     explicit blob_tracker_t(size_t maxreflen)
-        : buf_(alloc_emptybuf(maxreflen), maxreflen), blob_(max_block_size_t::unsafe_make(4096),
+        : buf_(alloc_emptybuf(maxreflen), maxreflen), blob_(max_block_size_t::unsafe_make(8192),
                                                             buf_.data(), maxreflen) { }
 
     void check_region(txn_t *txn, int64_t offset, int64_t size) {
@@ -145,13 +145,14 @@ void small_value_test(cache_t *cache) {
     cache_conn_t cache_conn(cache);
     txn_t txn(&cache_conn, write_durability_t::SOFT, 0);
 
-    blob_tracker_t tk(251);
+    blob_tracker_t tk(5000);
 
     tk.append(&txn, "a");
     tk.append(&txn, "b");
     tk.unappend(&txn, 1);
     tk.unappend(&txn, 1);
-    tk.append(&txn, std::string(250, 'd'));
+    tk.append(&txn, std::string(6000000, 'd'));
+    return;  // Early return to prove the error happens above.
     for (int i = 0; i < 250; ++i) {
         tk.unappend(&txn, 1);
     }
```

Not sure if this violates some implicit `blob_t` rule, but I couldn't find anything in the interface description that would suggest that.  Even if the modified test is incorrect, I'd expect the code to catch the violation instead of writing into free memory.

clang -v:
```
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
```

**Comment by danielmewes** [comment] 2016-07-22 18:25
The actual block size is determined by the cache, not by the `blob_t`. The `block_size` that you pass into `blob_t` and which you modified is only used for runtime-checks, and doesn't actually lead to larger blocks being allocated.

The problem occurs when you pass a `maxreflen` size in this line that is too large to fit into a block:
```C++
blob_tracker_t tk(5000);
```

Normally the `blob_t` constructor would catch this and crash with a more meaningful error, but since the block size that you pass to the `blob_t` constructor does not match the actual block size that the cache uses it can't detect the issue.

If you want to test larger block sizes, you'll have to change the size of btree leaf nodes.
Have a look at the file `src/config/args.hpp`. You can try modifying the `DEFAULT_BTREE_BLOCK_SIZE` value there. Note that changing this value hasn't been tested for a long long time, so there might be other issues.

Closing since this is not a bug in RethinkDB and the code behaves as expected. Thanks for reporting it though!

**Closed by danielmewes** 2016-07-22 18:25 UTC

**Comment by dekimir** [comment] 2016-07-22 18:51
Ah, so a blob constructor's block size must match the transaction cache's block size when `append_region()` is called?  Isn't that a guarantee that `append_region()` can enforce?

**Comment by danielmewes** [comment] 2016-07-22 19:02
@dekimir That's right. `append_region` can't enforce it I think because the block size passed to the `blob_t` constructor isn't saved anywhere. Theoretically it could perform the same guarantee checks that are in the constructor a second time though I think, since it should know the `maxreflen`. That would of course come with a runtime overhead, albeit likely a small one.
