### ISSUE TITLE
r.http() https access not working on OSX

### ISSUE THREAD

**Issue by datarefinery** [rethinkdb/rethinkdb#3112] opened 2014-09-29 18:38 UTC
RDB 1.15 on OSX 10.9.5

in Data Explorer:
r.http("https://api.github.com/repos/rethinkdb/rethinkdb/stargazers")

results in:
RqlRuntimeError: Error in HTTP GET of `https://api.github.com/repos/rethinkdb/rethinkdb/stargazers`: Peer certificate cannot be authenticated with given CA certificates.
header:
null
body:
null in:
r.http("https://api.github.com/repos/rethinkdb/rethinkdb/stargazers")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

from my initial research this might be an OSX CA certificates thing in that they are not implemented in OSX libcurl and/or openssl apparently..
if that's the case I guess unfixable until appropriate libraries fixed

**Comment by danielmewes** [comment] 2015-08-28 23:43
Re-opening. This doesn't work in 2.1.x.

**Comment by danielmewes** [comment] 2015-08-28 23:44
(I bet the problem is that this line https://github.com/rethinkdb/rethinkdb/commit/bc3801e9fc9c4c2c5a4b2d684fbd76b311b2a81a#diff-8cc1830f84de3483fa3bf7d3716c3261R12 still reads `sslCommand` instead of `ssl_command`. Testing right now)

**Comment by danielmewes** [comment] 2015-08-28 23:53
Yeah that was it. Fixed in 6a06e7f in `v2.1.x` and  	c237672 in `next`.

**Closed** 2015-08-28 23:52 UTC
Labels: tp:bug
