### ISSUE TITLE
javascript driver: valid connection checking false negative

### ISSUE THREAD

**Issue by joeybaker** [rethinkdb/rethinkdb#4302] opened 2015-05-28 17:59 UTC
### Steps to repro
1. require two different instances of the rethinkdb js driver
2. connect to a db with one of the drivers
3. run a query from the other driver, but pass in the connection from the first driver

### What happens
An invalid connection error

### What should happen
No error should be thrown.

I suspect that part of the check uses `instanceof` to determine if the passed object is a connection. Unfortunately, that treats rethinkdb as a singleton, which isn't necessary and causes the breakage described here.

**Comment by marshall007** [comment] 2015-05-28 19:35
This is a duplicate of #3263. See [#3796 (my comment)](https://github.com/rethinkdb/rethinkdb/issues/3796#issuecomment-74973755) for a possible workaround.

**Comment by deontologician** [comment] 2015-05-28 19:37
Closing as duplicate of #3263. It's in subsequent, so this is on our radar for fixing. Thanks for reporting it @joeybaker

**Comment by joeybaker** [comment] 2015-05-28 19:38
Thanks, sorry for the dupe!

**Closed by deontologician** 2015-05-28 19:37 UTC
