### ISSUE TITLE
changes() with get_all() does not return initial values

### ISSUE THREAD

**Issue by nviennot** [rethinkdb/rethinkdb#4323] opened 2015-06-01 22:57 UTC
```ruby
r.table("users").get(1).changes(:include_states => true)
# returns:
#   {"state"=>"initializing"}
#   {"new_val"=>{...}}
#   {"state"=>"ready"}

r.table("users").get_all(1).changes(:include_states => true)
# returns:
#   {"state"=>"ready"}

r.table("users").get_all(1,2,3).changes(:include_states => true)
# returns:
#   {"state"=>"ready"}
#   {"state"=>"ready"}
#   {"state"=>"ready"}
```

It would be helpful to get each initial values when using `get_all`.

**Comment by mlucy** [comment] 2015-06-02 00:36
Hi @nviennot,

Thanks for the feature request.  Closing as a duplicate of https://github.com/rethinkdb/rethinkdb/issues/3579 .  In 2.2 you'll be able to get the initial values for a much broader set of queries.

**Closed by mlucy** 2015-06-02 00:36 UTC
