### ISSUE TITLE
Tile with Rethinkdb

### ISSUE THREAD

**Issue by GeoCloud** [rethinkdb/rethinkdb#3854] opened 2015-02-28 22:01 UTC
Hello,

I'm working in a GeoSpatial Department and i would like to know the performance with the Geospatial queries. Do you have a benchmark ? 
What is the roadmap for the next geospatial functions ?

I have a project of web mapping. For each pan in my map, i would like to make a new request to Rethinkdb with a bounding box: TileJson or Tile Topojson (I made the same project with nodejs and postgis, and the results is very good.)
What do you think ? 
Is it possible (i think yes but i don't know the performance with rethinkdb)?

Thank you

**Comment by danielmewes** [comment] 2015-03-02 22:42
Hi @GeoCloud,
we don't have any official benchmarks at the moment. We're planning to implement support for compound geospatial indexes at some point (i.e. mixing geospatial coordinates with non-geo data in the same index) https://github.com/rethinkdb/rethinkdb/issues/2855 , but we're currently focussing on some other features.
Are there specific geospatial features that you would need?

Getting a subset of the data that's intersecting with a given bounding box is usually easy and pretty efficient. You can use the `getIntersecting` term for that and pass in a polygon that's describing the bounding box. http://rethinkdb.com/api/javascript/get_intersecting/

Please let us know if you have more questions.

**Comment by danielmewes** [comment] 2015-03-02 22:42
(closing because this is not a bug nor a specific feature request, but feel free to ask more questions here)

**Closed by danielmewes** 2015-03-02 22:42 UTC
