### ISSUE TITLE
Complex Event Processing

### ISSUE THREAD

**Issue by sirinath** [rethinkdb/rethinkdb#6299] opened 2017-03-12 16:32 UTC
RTDB has a solid event based processing model. Can this be extended to support CEP?

**Comment by AtnNn** [comment] 2017-03-18 00:02
What do you mean by "Complex Event Processing"? What would be the advantages over the current API?

**Comment by srh** [comment] 2017-05-24 15:55
Closing because the issue is vague about what to do, no followup.

**Closed by srh** 2017-05-24 15:55 UTC
