### ISSUE TITLE
Suggestion: Inner Changefeeds

### ISSUE THREAD

**Issue by elifarley** [rethinkdb/rethinkdb#3964] opened 2015-03-22 20:19 UTC
RethinkDB could provide the same functionality as [InfluxDB's Continuous Queries](http://influxdb.com/docs/v0.8/api/continuous_queries.html).

A continuous query looks essentially like a Changefeed in which the client is a table in the cluster itself, or an _Inner_ Changefeed.

From their documentation:

> When writing in large amounts of raw data, you will often want to query a downsampled variant of the data for viewing or analysis. In some cases, this downsampled data may be needed many times in the future, and repeatedly computing the same rollups is wasteful. Continuous queries let you precompute these expensive queries into another time series in real-time. 

InfluxDB query syntax:

``` SQL
select count(type) from events group by time(10m), type 
into events.count_per_type.10m
```

In ReQL:

``` Python

r.table('events').group( lambda x: [x['type'], x['when'].resolution(10.minutes)] ).count() \
.into('events_count_per_type_10m')

# or

r.table("events_count_per_type_10m").insert(
r.table('events').group( lambda x: [x['type'], x['when'].resolution(10.minutes)] ).count()
, continuous=True)

```

**Comment by danielmewes** [comment] 2015-03-23 17:49
This looks like materialized views https://github.com/rethinkdb/rethinkdb/issues/3171

The `into` syntax you're proposing looks interesting, though it poses the question of what happens if someone else also writes into the same table. It might be easier to have explicit "materialized view" tables that you could create somewhat like this:
```
r.viewCreate(
    "events_count_per_type_10m",
    r.reql(r.table('events').group( lambda x: [x['type'], x['when'].resolution(10.minutes)] ).count()) )
```
This relies on something like https://github.com/rethinkdb/rethinkdb/issues/3740 (here I'm using `r.reql` as a possible term).

**Comment by danielmewes** [comment] 2015-03-23 17:50
Would you mind if I closed this as a duplicate of https://github.com/rethinkdb/rethinkdb/issues/3171 ?

**Comment by elifarley** [comment] 2015-03-23 18:21
Maybe the table created by 'into' should only be writable by the command that created it.

Please note that an *inner changefeed* query will automatically write more items to the table (even after a cluster is restarted) until it is cancelled by a separate command some day.

See how it works in InfluxDB:
>**[Downsampling Continuous Queries] (http://influxdb.com/docs/v0.8/api/continuous_queries.html#downsampling-continuous-queries)**
This is expected to be the primary use case for continuous queries. When a continuous query is created from a select query that contains a group by time() clause, InfluxDB will write the aggregate into the target time series when each time interval elapses. **On creation, the cluster will backfill old data asynchronously in the background**.
Each hour, this query will count the number of points written into the time series called clicks and write a single point into the target time series called clicks.count.1h. It’s important to note that **this happens as soon as the hour has elapsed**

So I'm not totally sure the current issue is really a duplicate of #3171.

But I could be misinterpreting something, so feel free to close the current issue as a duplicate :)

**Comment by danielmewes** [comment] 2015-03-23 23:33
Thanks for the additional info @elifarley .
I think it is extremely similar to materialized views (unless I still misunderstand something). Materialized views would also be persistent and would be brought back up to date if a server was restarted.

The only difference I can see is that a materialized view would update the most recent time group every time the underlying data changes, and not only when the full hour / 10 minutes (in this example) have elapsed. So you will need to discard the count for the last group if you want to consider only completed time periods.

**Comment by elifarley** [comment] 2015-03-24 01:36
So it's best to close this as duplicate of #3171. I'll add the *into* syntax there.

**Comment by danielmewes** [comment] 2015-03-24 02:37
Thanks @elifarley !

**Comment by thelinuxlich** [comment] 2018-03-26 17:32
@srh  should close this in favor of #3171

**Closed** 2018-03-29 07:16 UTC
