### ISSUE TITLE
[next][web ui]No error is returned in the sharding modal when a server is down

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#3587] opened 2015-01-16 03:45 UTC
Following https://github.com/rethinkdb/rethinkdb/issues/3586, I had one server down.

When I try to reshard, I get an error on the web ui (on the "Sharding and replication for test.test") modal.

```
The server returned the following error:
```

But no error is actually displayed.

**Comment by deontologician** [comment] 2015-01-16 04:01
I think this is a dupe of #3507

**Closed** 2015-01-16 18:51 UTC
