### ISSUE TITLE
Reproducible crash 

### ISSUE THREAD

**Issue by alimoeeny** [rethinkdb/rethinkdb#3837] opened 2015-02-26 12:46 UTC
I am running rethinkdb in a docker container, using boot2docker on a mac, using the go driver `gorethink` I can reproduce a crash. Below is the log of the db on crash. Is this something that you guys want to investigate? I can privately send you my code. 
Also my rethinkdb version `rethinkdb 1.16.2+1~0trusty (GCC 4.8.2)` 
and this is my arch `Linux rethinkdb 3.18.5-tinycore64 #1 SMP Sun Feb 1 06:02:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux` [inside the container of course]

Also I understand that I need to find a way to mount my data volume that supports the syc api or whatever it is that is rethinkdb is complaining about. any guidance for that is also appreciated.

``` log
2015-02-26T12:33:15.723886942Z warn: Parent directory of log file (/data/rethinkdb_data/log_file) could not be synced. (Invalid argument)
2015-02-26T12:33:15.725200903Z Recursively removing directory /data/rethinkdb_data/tmp
2015-02-26T12:33:15.726182123Z In recursion: removing file /data/rethinkdb_data/tmp/post_construction_0e24ac38-e7e1-4dac-bfe4-843f12a7154a.create
2015-02-26T12:33:15.726804406Z In recursion: removing file /data/rethinkdb_data/tmp/post_construction_0fd2b587-c565-4876-906a-53644417e958.create
2015-02-26T12:33:15.727320659Z In recursion: removing file /data/rethinkdb_data/tmp/post_construction_3ce0de33-576a-4c91-9ac1-84fbf8c4eeb8.create
2015-02-26T12:33:15.727944221Z In recursion: removing file /data/rethinkdb_data/tmp/post_construction_c5889da9-eab0-447f-96b4-97807bca68e8.create
2015-02-26T12:33:15.728637214Z In recursion: removing file /data/rethinkdb_data/tmp
2015-02-26T12:33:15.730020932Z warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
2015-02-26T12:33:15.734563543Z Running rethinkdb 1.16.2+1~0trusty (GCC 4.8.2)...
2015-02-26T12:33:15.737741432Z Running on Linux 3.18.5-tinycore64 x86_64
2015-02-26T12:33:15.737802441Z Loading data from directory /data/rethinkdb_data
2015-02-26T12:33:15.743892492Z warn: Failed to sync parent directory of "/data/rethinkdb_data/metadata" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
2015-02-26T12:33:15.751912946Z warn: Failed to sync parent directory of "/data/rethinkdb_data/auth_metadata" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
2015-02-26T12:33:15.819894812Z Listening for intracluster connections on port 29015
2015-02-26T12:33:15.822518841Z Listening for client driver connections on port 28015
2015-02-26T12:33:15.823086523Z Listening for administrative HTTP connections on port 8080
2015-02-26T12:33:15.825917346Z warn: Failed to sync parent directory of "/data/rethinkdb_data/1c4708bf-b516-43bb-b5df-0f683fab162c" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
2015-02-26T12:33:15.860653823Z Listening on addresses: 127.0.0.1, 172.17.0.4, ::1, fe80::42:acff:fe11:4%10
2015-02-26T12:33:15.861016035Z Server ready, "06fcccdeb5cb_yzd" 57cd3832-2199-4b19-85f2-790401eb4e7d
[2015-02-26T12:37:28.626647587Z] warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/post_construction_0256c9ea-a9aa-42c9-adb7-2224829a17b0.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
[2015-02-26T12:37:28.627144944Z] warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/post_construction_033197b6-b373-4f5b-80ed-30ca41b6d1a6.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
[2015-02-26T12:37:28.627735210Z] warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/post_construction_3e4d4f55-75d0-41e8-9a79-281a8f731c59.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
[2015-02-26T12:37:28.630693657Z] warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/post_construction_9298520c-b00d-46a8-96f6-b76ccb73f985.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
[2015-02-26T12:37:28.631918406Z] warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/post_construction_fd4bc326-16be-4bf7-b1c1-30fbe136613d.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
[2015-02-26T12:37:28.633551724Z] warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/post_construction_0960ddf5-ce53-40bb-b948-64e51f6afd0b.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
[2015-02-26T12:37:28.637275333Z] warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/post_construction_c2f5ded9-0dca-43eb-b012-dadb25a1ff02.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
[2015-02-26T12:37:28.639697057Z] warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/post_construction_64553ebf-fa8d-4ddd-a037-53da48064e07.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
[2015-02-26T12:37:28.652881865Z] warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/post_construction_0256c9ea-a9aa-42c9-adb7-2224829a17b0.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
[2015-02-26T12:37:28.653537464Z] warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/post_construction_033197b6-b373-4f5b-80ed-30ca41b6d1a6.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
[2015-02-26T12:37:28.657749318Z] warn: Failed to sync parent directory of "/data/rethinkdb_data/tmp/post_construction_9298520c-b00d-46a8-96f6-b76ccb73f985.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
[2015-02-26T12:37:28.669844893Z] Version: rethinkdb 1.16.2+1~0trusty (GCC 4.8.2)
[2015-02-26T12:37:28.669907033Z] error: Error in src/arch/io/disk.cc at line 247:
[2015-02-26T12:37:28.671310097Z] error: ftruncate failed.  (No such file or directory) (target size = 4194304)
[2015-02-26T12:37:28.673264807Z] error: Backtrace:
[2015-02-26T12:37:28.691110867Z] addr2line: 'rethinkdb': No such file
[2015-02-26T12:37:28.697575783Z] addr2line: 'rethinkdb': No such file
[2015-02-26T12:37:28.714234342Z] error: Thu Feb 26 12:37:28 2015
[2015-02-26T12:37:28.714234342Z]
[2015-02-26T12:37:28.714234342Z]        1: backtrace_t::backtrace_t() at 0xb9d9f0 (rethinkdb)
[2015-02-26T12:37:28.714234342Z]        2: format_backtrace(bool) at 0xb9dd83 (rethinkdb)
[2015-02-26T12:37:28.714234342Z]        3: report_fatal_error(char const*, int, char const*, ...) at 0xd49fe5 (rethinkdb)
[2015-02-26T12:37:28.714234342Z]        4: rethinkdb() [0xac2050] at 0xac2050 ()
[2015-02-26T12:37:28.714234342Z]        5: linux_disk_manager_t::done(stats_diskmgr_t::action_t*) at 0xac49a3 (rethinkdb)
[2015-02-26T12:37:28.714234342Z]        6: conflict_resolving_diskmgr_t::done(accounting_diskmgr_action_t*) at 0xab4594 (rethinkdb)
[2015-02-26T12:37:28.714234342Z]        7: blocker_pool_t::on_event(int) at 0xaaf3e2 (rethinkdb)
[2015-02-26T12:37:28.714234342Z]        8: epoll_event_queue_t::run() at 0xacfeee (rethinkdb)
[2015-02-26T12:37:28.714234342Z]        9: linux_thread_pool_t::start_thread(void*) at 0xace6c5 (rethinkdb)
[2015-02-26T12:37:28.714234342Z]        10: /lib/x86_64-linux-gnu/libpthread.so.0(+0x8182) [0x7f4483de4182] at 0x7f4483de4182 (/lib/x86_64-linux-gnu/libpthread.so.0)
[2015-02-26T12:37:28.714234342Z]        11: clone+0x6d at 0x7f4483b1100d (/lib/x86_64-linux-gnu/libc.so.6)
[2015-02-26T12:37:28.715102377Z] error: Exiting.
```

**Comment by alimoeeny** [comment] 2015-02-26 13:08
Actually it has nothing to do with the driver, I can reproduce it with the web ui too. It happens when I try to create a secondary index.

**Comment by danielmewes** [comment] 2015-02-26 17:07
Hi @alimoeeny, which file system are the data files stored on (inside the container I mean)?

This is most likely a duplicate of https://github.com/rethinkdb/rethinkdb/issues/3791 , which is caused by an access pattern that a few special file systems don't support. So far we have seen it for VirtualBox shared folders, but there might be other ones.

**Closed** 2015-02-26 17:09 UTC

**Comment by alimoeeny** [comment] 2015-02-26 22:01
@danielmewes it's an `ubuntu:14.04` container, I am not sure what is inside. It is running on `boot2docker` and is actually mounting the local OSX folder as a `/data` volume.

**Comment by danielmewes** [comment] 2015-02-26 22:09
@alimoeeny Thanks. It turns out #3791 was also inside a boot2docker container, so I assume it's the same issue. We'll try to work around it in the next release.

At the moment I fear RethinkDB doesn't run inside a boot2docker container, at least not with the default configuration. I don't know much about how boot2docker works. It might be possible to make it not use a VirtualBox shared folder for the data, but I'm not sure.

**Comment by alimoeeny** [comment] 2015-02-26 22:11
Thanks @danielmewes , I'll keep you posted if I made any progress.
