### ISSUE TITLE
JS driver: connections fail without calling back

### ISSUE THREAD

**Issue by stuartpb** [rethinkdb/rethinkdb#3807] opened 2015-02-20 13:00 UTC
Run this code on a server with no running instance of RethinkDB:

```
require('rethinkdb').connect({},function(err,conn) {
  console.error(err);
})
```

The script will just return immediately without saying anything (as opposed to the result if the default server is running, where the server will connect and remain connected). This just cost me ~3 hours of debugging to realize.

**Comment by danielmewes** [comment] 2015-02-20 19:51
Sorry you ran into this @stuartpb .

@deontologician do you have an idea what's going on? Is this a bug in the driver?

**Comment by chrisvariety** [comment] 2015-02-20 19:55
FYI I get this when running the above code:

```
require('rethinkdb').connect({},function(err,conn) {
  console.error(err);
});

=> 

{ [RqlDriverError: Could not connect to localhost:28015.
connect ECONNREFUSED]
  name: 'RqlDriverError',
  msg: 'Could not connect to localhost:28015.\nconnect ECONNREFUSED',
  message: 'Could not connect to localhost:28015.\nconnect ECONNREFUSED' }
```

node v0.11.14, rethinkdb (npm package) v1.14.0-0 (so a bit old)

Could be a regression or an issue on a specific node version?

**Comment by deontologician** [comment] 2015-02-20 21:12
@stuartpb are you using the 1.16 driver?

**Comment by stuartpb** [comment] 2015-02-21 00:37
Yes, with a 1.16.0 server (when connecting).

**Comment by deontologician** [comment] 2015-02-21 00:52
I am not able to reproduce this problem, I also get the exception. Also it
seems we have a test for this behavior in
test/rql_test/connections/connection.js. So if it's not happening, I think
it's an intermittent issue of some kind, or maybe a platform issue.


On Fri, Feb 20, 2015 at 4:37 PM, Stuart P. Bentley <notifications@github.com

**Comment by stuartpb** [comment] 2015-02-21 01:38
I repro'd this last night on two separate hosts (running trusty), and again just now in a fresh Cloud9 workspace:

```bash
npm install rethinkdb
node -e 'require("rethinkdb").connect({},function(err,conn) {console.error(err);});'
# returns immediately
```

https://ide.c9.io/stuartpb/rethinkdb-test

**Comment by stuartpb** [comment] 2015-02-21 05:00
Uh, on debugging, it looks like the error is https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/net.coffee#L929 - the "once" listener gets called for the first error, *and then the `on` listener never gets called*. Maybe this was a change in how `once` event listeners work between 0.10 and 0.11?

**Comment by stuartpb** [comment] 2015-02-21 05:06
I think this is probably the problem: https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/net.coffee#L1041

In my compiled JS from the published module, the line says to emit 'close', not 'error':

    this.rawSocket.on('error', (function(_this) {
      return function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (_this.isOpen()) {
          _this.close({
            noreplyWait: false
          });
        }
        return _this.emit('close');
      };
    })(this));

**Comment by deontologician** [comment] 2015-02-21 22:54
Ok, glad it's solved. Closing as a dupe of #3733, thanks for following up @stuartpb

**Closed by deontologician** 2015-02-21 22:54 UTC
Labels: tp:bug

**Comment by stuartpb** [comment] 2015-02-22 00:54
Well, no, it's *not* solved. I still have this issue in any app I deploy, because this bug is in the latest published version.

**Comment by stuartpb** [comment] 2015-02-22 01:17
Or, well, I guess there technically is a sort of workaround in trying a raw socket connection *before* making the RethinkDB connection, if you want to catch this error (which you can kind of otherwise detect, if you already know it happens).

I'm still anxiously awaiting a new published client driver.
