### ISSUE TITLE
Database shows up twice in Web UI, refreshing clears it

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#921] opened 2013-05-29 03:28 UTC
I have no idea how this happened, but here's a screenshot:
![screen shot 2013-05-28 at 8 26 29 pm](https://f.cloud.github.com/assets/552910/576698/ac2f758e-c80f-11e2-8684-cdd09e5b6cb9.png)

Looking at the semilattice, there was only one database:
```
"databases": {
    "e1f05d75-fa27-4f12-9e23-e585628fd52d": {
        "name": "test"
    }
},
```

Refreshing made it go back to normal.

**Comment by danielmewes** [comment] 2015-01-21 00:27
I can't reproduce this in `next` anymore, and the logic of the tables index has changed significantly with the ReQL admin rewrite. Closing for now.

**Closed by danielmewes** 2015-01-21 00:27 UTC
Labels: cp:web-ui

**Comment by neumino** [comment] 2015-01-21 02:05
Quick note to confirm that this was done here:
https://github.com/rethinkdb/rethinkdb/blob/538dd801bfa4c7cebc6728a7c8b5308700584be4/admin/static/coffee/tables/index.coffee#L182
