### ISSUE TITLE
Add the ability to join a node to a cluster after start (without --join)

### ISSUE THREAD

**Issue by andyburke** [rethinkdb/rethinkdb#4488] opened 2015-07-01 21:00 UTC
I'd like to be able to join a RethinkDB node into a new cluster after start, not using the --join command line option. (Specifically, this would be useful for me w/ my docker + deployment setup.)

Riak handles this well:

```
riak-admin cluster join riak@192.168.1.10
```

Or via their web interface:

![riak admin console](http://docs.basho.com/shared/2.1.1/images/control_cluster_management_staged.png?1435766058)

You can enter a riak node name (which includes an ip) to add into the cluster and then you will see the proposed change and can commit it.

I think having both of these options would be beneficial for RethinkDB, eg:

From new node, to join existing cluster:
```
rethinkdb join <ip of existing cluster node>
```

or

From existing cluster node, to add a new node:
```
rethinkdb add <ip of new cluster node>
```

**Comment by danielmewes** [comment] 2015-07-01 22:37
Thanks for opening an issue for this @andyburke .
This is a duplicate of https://github.com/rethinkdb/rethinkdb/issues/1473 actually, but it's interesting to see how Riak is doing this.

**Closed** 2015-07-01 22:38 UTC
