### ISSUE TITLE
Getting query size issue

### ISSUE THREAD

**Issue by hk4774** [rethinkdb/rethinkdb#6320] opened 2017-04-03 22:35 UTC
I ran the following query and it gave the error: Query size (152170809) greater than maximum (134217727).

conn = r.connect(host='localhost',
          port=28015,
          db='topsite')
r.table('crawldata').insert([{
                    'id': str(i + 1),
                    'URL': str(url),
                    'Title': str(title),
                    'Description': str(description),
                    'Keywords': str(keyword),
                    'Content': str(content),
                    'Last_Modified': str(last_modified),
                    'Category': str(category)
                }]).run(conn)

**Comment by srh** [comment] 2017-04-03 23:17
I guess the maximum query size is 2^27.  You have a long content string, I take it.

**Comment by srh** [comment] 2017-05-16 03:35
Having a maximum query size is not a bug, so I'm closing.  But if this is still a problem for you, I'd love to hear it.  Maybe RethinkDB needs and alternate solution.

**Closed by srh** 2017-05-16 03:35 UTC
