### ISSUE TITLE
Metadata writes are very slow on rotational drives

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#4279] opened 2015-05-25 20:47 UTC
The `metadata_file_t` often writes in the following pattern: Start a `txn_t` in hard durability mode and do some writes. Call `~txn_t`, but before it finishes, start another `txn_t` in hard durability mode and do some writes. Repeat.

When this happens, the storage engine is apparently doing all of the writes serially; it waits for each write to completely commit before starting the next one. I've observed `~txn_t` taking more than five seconds to return on rotational drives.

@danielmewes, I think you mentioned that this is a known flaw in the buffer cache. Is it practical to fix? If not, we could work around it by running the transactions themselves in soft durability mode and then using a `pump_coro_t` to flush them.

**Comment by danielmewes** [comment] 2015-05-27 14:55
@timmaxw 
> the storage engine is apparently doing all of the writes serially; it waits for each write to completely commit before starting the next one.

The buffer cache currently only merges block writes of transactions that are active at the same time. Once one of them begins flushing (usually when `~txn_t` is called, but before it completes), it initiates a complete set of writes for that transaction so it can be acknowledged with as little latency as possible. This motivation of course isn't quite correct in a concurrent setting.
The solution I can think of would be to intentionally *delay* the flush of transaction A in the hope that we can combine it with the flush of transaction B and get better overall throughput.
The amount of delay would probably have to be dependent on how many writes are currently pending, so that we only delay if the i/o system is saturated.
This might be as easy to fix as adding a semaphore around the flushes in the cache, so that not too many can be going on at the same time and hence more of them will be combined into the same "flushable transaction set" as our cache calls them (then they will be flushed together).

I'm not sure how well this would work and haven't thought about it carefully enough to say if there are any potential regressions or disadvantages to watch out for.

In theory soft durability mode shouldn't make a difference here. All that soft durability does is that it makes `~txn_t` not wait for the flush to complete. It sounds like you're already not doing that in `metadata_file_t`, so it should be equivalent.

Is there an easy way in `metadata_file_t` to use a `pump_coro_t` to combine multiple writes into the same `txn_t`?

**Comment by danielmewes** [comment] 2015-05-27 15:01
Actually for the metadata writes to be particularly slow on rotational drives it likely has to be a problem with doing too many index writes and them not being merged for some reason. Superfluous data writes should be approximately equally fast for SSDs and rotational drives, since they are sequential.
I'd have to look at the details of the cache and how the writes are done exactly to make a guess about why that's the case...

**Comment by timmaxw** [comment] 2015-05-27 19:11
Suppose I have the following workload: Start 100 `txn_t`s in hard durability mode. Do some writes on the first `txn_t` and call its destructor. Before the destructor returns, do some writes on the second `txn_t` and call its destructor. Repeat. Will this work properly, or will it wait for all 100 `txn_t`s to be destroyed before it flushes any of them?

**Comment by danielmewes** [comment] 2015-06-02 03:09
@timmaxw I think that should work properly. As long as the second `txn_t` hadn't acquired any blocks before the first one has its destructor called, the first one should start flushing immediately.
Only if a subsequent transaction acquires a block for writing before a previous transaction gets into its destructor, it will create a dependency and the earlier transaction(s) will need to wait for the later one to destruct as well.

**Comment by danielmewes** [comment] 2015-06-02 03:10
That is I believe the time where you call the destructor is relevant for flushing dependencies, not the time where it finishes (but I'll double check this).

**Comment by danielmewes** [comment] 2015-06-03 19:57
We are not entirely sure what happens that makes this so slow. Going to do some more research.

**Comment by danielmewes** [comment] 2015-06-04 20:04
Some improvements to this went into the `raft` branch as of c8789464bec788eae9eb43c0225429c0c3c43f04 (code review 2951). Those speed up sharding a table to 32 shards on rotational drives by a factor of 2 or a bit more, but don't completely solve the issue.

**Comment by danielmewes** [comment] 2015-07-18 03:12
Reconfiguring a single table to 32 shards now takes about 5 seconds on a hard disk. This seems ok.
I suspect that this becomes faster per table if multiple tables are reconfigured at the same time, but I'm still testing that.

**Comment by danielmewes** [comment] 2015-07-28 00:57
Reconfiguring 150 tables to 32 shards takes about 2 seconds per table.
Not super fast, but I don't think this will be a problem in practice.

**Closed by danielmewes** 2015-07-28 00:57 UTC
Labels: tp:bug
