### ISSUE TITLE
How Can I Upgrade Rethinkdb?

### ISSUE THREAD

**Issue by muratgozel** [rethinkdb/rethinkdb#5818] opened 2016-06-02 07:52 UTC
I am using a version 2.3.2 of Rethinkdb. I was install it with the `brew install rethinkdb` command.

Today, console warned me about the new version: `A newer version of the RethinkDB server is available: 2.3.3. You can read the changelog at...` 

I looked up but couldn't find any answer about how to upgrade Rethinkdb to a new version?

**Comment by larkost** [comment] 2016-06-02 18:41
`brew update rethinkdb` would work fine in this case. `v2.3.2` and `v2.3.3` are fully compatible so there is no upgrade process at all on our side (most of the time that is the case, but we always mention those things in our [release notes](https://github.com/rethinkdb/rethinkdb/releases)).

I am going to close this, as it is not a bug. A better place for questions like this is probably our Slack channel or Google Groups mailing list: http://rethinkdb.com/community/

**Closed by larkost** 2016-06-02 18:41 UTC
