### ISSUE TITLE
Disk space occupation increases quickly when load json file using rethinkdb import

### ISSUE THREAD

**Issue by Shengli-Lu** [rethinkdb/rethinkdb#6042] opened 2016-08-09 05:36 UTC
The RethinkDB version is 2.3.4, and I imported around 1.5M json objects to one table, and each object has around 20 fields. When I created 10 indexes for the table and then started loading the json file, a very strange issue is the RethinkDB was eating storage quickly, there was about 50G got fulled, and I have to stop the data loading. But when I loaded the json data into the table without those indexes, the rethinkdb generated a table file around 1.2G, and then I created the 10 indexes for the table, the final table file size is about 3.3 G.

Why is the result so different? 50G vs 3.3G..., Is there any issues at there? Thanks.

C_ommand Line in Linux Server:
rethinkdb import -c server:port -f mydata.json --table mydb."mytable" --force --max-document-size 500000000

**Comment by danielmewes** [comment] 2016-08-09 18:27
Thanks for reporting this @Shengli-Lu . This seems to be essentially the same issue as https://github.com/rethinkdb/rethinkdb/issues/5923 .

In a nutshell, the reason for this is that doing many small updates to secondary indexes creates more "garbage" in the files, compared to creating the index afterwards which uses more efficient mechanisms to batch index updates together.
RethinkDB uses an incremental garbage collector to reclaim the garbage space, but it looks like the GC is too inefficient to keep up for certain loads in the current release of RethinkDB, which in turn causes the file to grow in size more quickly during the data load.
We've done a couple of improvements, which will ship soon with RethinkDB 2.3.5. We'll have to see if those are enough to avoid this issue, or if there's more we need to do.

Closing as a duplicate of #5923 .

**Closed by danielmewes** 2016-08-09 18:27 UTC

**Comment by Shengli-Lu** [comment] 2016-08-10 02:00
Awesome Daniel! I didn't expect the response so quickly from the RethinkDB team, but you guys did. I'm looking forward to seeing the next version RethinkDB with the improvement, thanks for your contribution!
