### ISSUE TITLE
Provide way to run rethinkdb proxy node via init scripts

### ISSUE THREAD

**Issue by aaronorosen** [rethinkdb/rethinkdb#5539] opened 2016-03-18 04:51 UTC
Currently, one must manually edit the init file for rethinkdb if they would like to start an additional instance to run as a proxy node. It would be nice if there was an option to specify this in config file in instances.d/<instance>.conf if the node should run as a proxy instead. This would make automating the install/setup process of rethinkdb easier.

**Comment by danielmewes** [comment] 2016-03-18 20:49
Agreed. This is actually a duplicate of https://github.com/rethinkdb/rethinkdb/issues/5138.

**Closed by danielmewes** 2016-03-18 20:49 UTC
