### ISSUE TITLE
`.default()` is a potentially giant performance pitfall

### ISSUE THREAD

**Issue by cristicbz** [rethinkdb/rethinkdb#6352] opened 2017-05-05 14:29 UTC
`some_object(key).default(value)` is _extremely_ slow if `some_object` is a large object (presumably because the non-existence error serializes the entire object to a string):

In IPython:
```
In [70]: z = r.expr({os.urandom(18).encode('hex'): os.urandom(4).encode('hex') for _ in xrange(1000)})

In [71]: %timeit -r1 -n1 r.table('comments').filter(lambda x: (z[x['ci']] != x['di']).default(True)).count().run()
1 loop, best of 1: 3m 43.01 s per loop

In [72]: %timeit -r1 -n1 z.do(lambda e: r.table('comments').filter(lambda x: e.has_fields(x['ci']).not_().or_(e[x['ci']] != x['di'])).count()).run()
1 loop, best of 1: 2.08 s per loop
```

Where comments is a table with about 700K rows. The difference is HUGE! We had this both in some queries, but also in some index functions which made inserts extremely slow.

I think `default` should come with performance warning in the docs, but also there's a case for a `get_or_default` function on objects, to avoid having to write the `has_fields` version all the time.

I think this is the issue in #6119 too.

**Comment by AtnNn** [comment] 2017-05-08 16:20
Thanks for opening the issue. This seems closely related to #4271, which seems to indicate that a failed `get_field` is slow even without the `default`.

**Comment by robertjpayne** [comment] 2017-07-23 09:31
Yea just digging into this specifically I don't think the `default` is actually the issue. Rather it's the `get_field` lookup which is implicit via brackets on `z[x['ci']]`.

I'd close this in favour of #4271 as well.

**Comment by cristicbz** [comment] 2017-07-23 09:56
Fair enough. The thing is this issue makes `get_field.default`into an antipattern (with quadratic perf), compared to the linear `branch.has_fields.get_field`. It feels like at least a documented perf warning on `default`'s page is warranted.

**Comment by robertjpayne** [comment] 2017-07-23 11:13
@cristicbz I mean really this should just be fixed, it'd be a HUGE performance win for a lot of queries, in my use of RethinkDB I used `default` *a lot*.

**Comment by thelinuxlich** [comment] 2018-03-29 21:43
@srh, duplicate of #1232

**Closed** 2018-03-30 04:07 UTC
Labels: tp:performance
