### ISSUE TITLE
e: Array over size limit `100000` in:

### ISSUE THREAD

**Issue by edwardsmarkf** [rethinkdb/rethinkdb#5664] opened 2016-04-14 15:12 UTC
hello - and thank you very much for rethinkdb.  

my issue was first[ raised here:](https://groups.google.com/forum/#!topic/rethinkdb/wo6M4d7DZsU)

to reproduce the issue:
1) unzip/tar attached, or [download here](http://edwardsmark.com/issue.tar.gz)
2) rethinkdb import -f parentTable.json --table test.parentTable --pkey id  ;
3) rethinkdb import -f childTable.json --table test.childTable --pkey id      ;

r.db('test').table('childTable').eqJoin('parentTable_id',r.db('test').table('parentTable'),{index:'id'}).count()  

result:
e: Array over size limit `100000` in:

please note that this index did not help, VERY surprisingly (which is another issue i might raise)
r.db('test').table('childTable').indexCreate('parentTable_id')

the UUID keys were all created using the mariaDB UUID() function - i have to wonder if that might be part of the issue, however unlikely. 

[issue.tar.gz](https://github.com/rethinkdb/rethinkdb/files/219362/issue.tar.gz)

**Comment by mlucy** [comment] 2016-04-14 23:51
Thanks for the bug report @edwardsmarkf !

@nighelles, is it possible this is related to the new `eq_join` implementation in 2.3?

**Comment by nighelles** [comment] 2016-04-15 00:07
Hey @edwardsmarkf ,

I tried importing your data into a RethinkDB 2.3 instance running on Ubuntu 14.04, and the command you listed above returns successfully on my end.

Is there something about your system that might be different from my end?

**Comment by edwardsmarkf** [comment] 2016-04-15 01:00
>>> Is there something about your system that might be different from my
end?

probably!  can you give me a few commands i can run, such as "uname -a"

its a centos7 installation running on virtualbox.


Thank you,

Mark Edwards

**Comment by danielmewes** [comment] 2016-04-15 01:05
@nighelles could this be related to how big the batches get? Maybe if the server reads over 100k documents within the default 500ms batch duration limit?

**Comment by nighelles** [comment] 2016-04-15 01:18
@danielmewes That's an interesting thought.

**Comment by nighelles** [comment] 2016-04-15 23:39
@edwardsmarkf Can you tell me the settings you're using for the virtualbox instance?

**Comment by nighelles** [comment] 2016-04-25 17:30
Hey @edwardsmarkf ,

If this is still an issue for you, would you mind letting me know what settings you're using for the virtualbox? I'm still trying to reproduce this.

**Comment by danielmewes** [comment] 2016-07-20 00:35
Closing, since we are missing critical information on the issue.

@edwardsmarkf Please let us know if you're still seeing this issue, and we'll open it again.

**Closed by danielmewes** 2016-07-20 00:35 UTC
Labels: not reproduced yet, tp:bug
