### ISSUE TITLE
RethinkDB Browser Client: Memory leak

### ISSUE THREAD

**Issue by ipastushenko** [rethinkdb/rethinkdb#4100] opened 2015-04-23 09:47 UTC
Browser: Google Chrome.
OS: Linux(Ubuntu 14.04).
Page: Dashboard.

**Comment by deontologician** [comment] 2015-04-23 14:32
Did you run into trouble with this or did you just notice the leak? (This will help with prioritizing)

**Comment by djelic** [comment] 2015-04-23 18:19
Hi, first, thanks for all the great work on RethinkDB.
I can confirm this issue. If you open Task Manager in Chrome (Shift + Esc on Linux) and look at RethinkDB Administration Console tab memory usage, you'll see that number is constantly growing. It seems that if tab is out of focus, memory usage climbs faster by almost 1MB/s.
After certain amount of time, tab stops responding and Chrome kills it.

Browser: Google Chrome
OS: Debian Testing
RethinkDB: 2.0.0

**Comment by danielmewes** [comment] 2015-04-23 18:45
That's a rather worryingly high growth rate. Thanks for bringing this to our attention @ipastushenko and @djelic .

**Comment by FLIR31207** [comment] 2015-04-23 19:39
Is this a "Linux only" issue? 
At least **I** do not see it in Chrome on OSX ...

**Comment by coffeemug** [comment] 2015-04-24 01:32
I seem to be able to reproduce this on Chrome and OSX. It should be fairly easy to track down with Chrome's heap profiler.

**Comment by deontologician** [comment] 2015-04-27 21:46
Looking at this now

**Comment by deontologician** [comment] 2015-04-28 01:39
So it seems the culprit is indeed the graph library. That leaves us with a few options (that I can think of):

1. Put in the time to fix the graph library. This probably won't be trivial since it's not JS heap that's out of control, that stayed relatively constant while the task memory kept increasing by leaps and bounds.
2. Replace the graph library with something else (i.e. #3720 ). This has it's own risks: it may not solve the problem, it may also introduce new problems. This is likely too much for a point release and would have to be put out in 2.1 or 2.2 depending on scheduling. We could potentially shave some time off this if we didn't tweak the visual style of the graph too much and stuck with default styling, even if it didn't fit in with the rest of the style of the webui.
3. Set the update resolution on the graph to something much lower. It seems the speed of memory increase is linked to how fast the graph is scrolling. This is a quick bandaid which doesn't really solve the problem, but it would be quick to implement and could reasonably go out in a point release, with us solving the problem properly later.

@danielmewes @mglukhovsky thoughts?

**Comment by danielmewes** [comment] 2015-04-28 01:53
What's the update resolution at the moment?

How difficult is it to profile what in the graph library is using up the memory? Do you have some general ideas what besides the JS heap can theoretically be using memory?

**Comment by deontologician** [comment] 2015-04-28 02:03
General ideas: since it's not happening in firefox, I'm assuming it's something with how surfaces/textures etc are managed in chrome. This is corroborated by the memory consumption going up once you switch tabs. If you don't have to actually render it to the screen, the graph library can crank through memory that much faster.

Here's the heap profile I'm seeing (peak is 36MB js objects):

![selection_030](https://cloud.githubusercontent.com/assets/1366/7361584/0204d518-ed10-11e4-9c2a-24b7d21c8c62.png)

It's hard to get a profile of memory usage in the native code (task memory = JS heap + native heap), but I'm compiling a custom chrome now that has compile flags turned on for deep memory profiling.

When I look at counts of dom node usage (something else that doesn't show up in the JS heap directly), it doesn't seem to be growing without bound either, so I don't think it's that.

**Comment by deontologician** [comment] 2015-04-28 02:12
We might also try updating to a more recent version of cubism.js. It doesn't seem like they have this problem in the graphs that are on their demo page: (https://square.github.io/cubism/)

**Comment by coffeemug** [comment] 2015-04-28 07:41
I don't know if we can easily update to the new version of cubism -- I hacked it to display line graphs and added support for multiple lines. We'd have to port this code to the new version, which is a pain.

I'd like to propose two alternative solutions:

- every five minutes, destroy the cubism canvas and start from scratch
- use the same library we use on rethinkdb.com. Using d3 directly was a massive pain (which is why we used cubism), but graphing libraries have gotten much better since then. It would probably be very easy to replace cubism with the same library we use on the landing page.

**Comment by deontologician** [comment] 2015-04-28 13:56
I'll try seeing today if destroying the canvas works. Reloading the page didn't drop the task memory consumption, so it may not be that easy, but it's definitely the best shot.  

I thought the graph on the front page was the cubism fork we use in the real webui. I didn't realize the work had already been done to replace it

**Comment by mglukhovsky** [comment] 2015-04-28 15:38
@coffeemug: we use D3 on the landing page. I'm looking to replace it with another library, due to excessive CPU usage.

**Comment by danielmewes** [comment] 2015-04-28 18:53
CPU usage is a bit less of a concern for the web UI.

It would be interesting to find out what in Cubism is actually causing so much memory consumption. It's possible that it's doing something stupid and there's an easy fix.

Replacing it with d3 sounds like a reasonable solution, assuming it has the functionality we need by now.

**Comment by deontologician** [comment] 2015-04-28 20:15
Testing this in chrome 44 dev, the problem disappears. It's still high memory consumption (230M or so), and it seems we're doing a lot of inefficient things with listeners (creating and destroying a lot of listeners and dom nodes that need to be garbage collected), but it seems the memory usage is stable in a newer Chrome. I'd like to try it out on OS X etc to verify, but this looks like it may have been a chrome memory leak triggered by the way we render the graph.

**Comment by deontologician** [comment] 2015-04-28 21:48
This issue seems to be completely absent on OS X Yosemite with Chrome 41, 42 and Chrome Canary (currently 44).

So far I've only been able to replicate it on Chrome 42 on linux (I used arch linux, so it's unlikely to be a Ubuntu bug).

I think all signs point to Chrome 42 here. @djelic @ipastushenko could you guys post which version of Chrome/Chromium you're using? Also, are either of you running linux in a VM?

**Comment by djelic** [comment] 2015-04-28 22:21
I'm using Chrome 42.0.2311.90.
Just tried in Chrome Beta (43.0.2357.37) and it seems the issue has gone. Waited for about 5 minutes, tab memory sticks around 215mb.

**Comment by deontologician** [comment] 2015-04-29 20:17
OK, I was able to conclusively replicate it in Chromium 42.0.2311.90 on Linux, and it is definitely gone in the most recent update Chromium 42.0.2311.135

I think it's safe to say this was a leak in chrome and they've put out an update fixing the problem. @ipastushenko Ubuntu has the new version now, so you should be able to update and it should resolve the problem. @djelic you should probably be able to update as well, though I'm not familiar with the Debian release cycle.

Closing as outdated

**Closed by deontologician** 2015-04-29 20:17 UTC
Labels: cp:web-ui, tp:bug

**Comment by deontologician** [comment] 2015-04-29 20:19
Note that the webui isn't totally innocent here, it's still inefficient. But I think issue #3720 is the issue to watch for rejiggering the graph not to use so much memory
