### ISSUE TITLE
Error when importing into RethinkDB 2.1.1 

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/rethinkdb#4766] opened 2015-08-25 18:54 UTC
Attempting to import into 2.1.1 from an instance of 2.1.1.

From within the created export directory: 
```
$  rethinkdb import -d . --force
[                                        ]   0%
27 rows imported in 2 tables
ReQL error during 'create table': Binary blob passed to index create could not be interpreted as a reql_index_function (Deserialization of sindex description failed with error archive_result_t::RANGE_ERROR.).
In file: /rethinkdb_export_2015-08-25T11:45:26/telemetry_pi/observations.json
```

If I instead do:
```
rethinkdb import -f ./telemetry_pi/observations.json --table telemetry_pi.observations 
```

Everything works fine.

**Comment by Tryneus** [comment] 2015-08-25 19:23
It's possible this is due to an index created in `v1.13.x` - @dalanmiller, where can I find the import data?

**Comment by danielmewes** [comment] 2015-08-25 20:02
The data and indexes appear to import fine for some builds of RethinkDB (tested with 2.1.0 on Mac and 2.1.1 on Linux).
Haven't tried with a brewed version yet.

**Comment by dalanmiller** [comment] 2015-08-25 21:04
D'oh, forgot `brew` doesn't automatically restart RethinkDB when updated. Had `2.1.1` installed but the instance running was `2.1.0`. This may be closed.

**Comment by danielmewes** [comment] 2015-08-25 21:06
Hmm that's still kind of unexpected I think.
2.1.1 and 2.1.0 should be compatible.

**Comment by Tryneus** [comment] 2015-08-27 05:03
I did some testing and found that importing a v1.13 secondary index would cause a `fail_due_to_user_error`, which means a query could crash the server.  I've uploaded a fix in review 3190 to make this situation result in a ReqlRuntimeError.

The original problem in this issue is likely caused by the incomplete secondary index version handling in v2.1.0, wherein we would correctly handle outdated `cluster_version_t`s, but not `reql_version_t`s.  This has been fixed in v2.1.1 and up.

**Comment by Tryneus** [comment] 2015-08-27 21:46
The fix has been approved and merged to `next` in commit 6587140, and cherry-picked into `v2.1.x` in commit 4ce5fee.  Will be in release 2.1.3.

**Closed by Tryneus** 2015-08-27 21:46 UTC

**Comment by dalanmiller** [comment] 2016-01-28 20:24
@Tryneus this came up again in IRC:


[12:05:25]  <heath>	ReQL error during 'create table': Binary blob passed to index create could not be interpreted as a reql_index_function (Deserialization of sindex description failed with error archive_result_t::RANGE_ERROR.). In file: /var/folders/rh/bv6l6qs557s5_6dql410625r0000gn/T/tmpo5qh88/example/geo.json
[12:09:26]  <dalanmiller>	Did you do a `rethinkdb export` @heath and are now trying to import? 
[12:09:54]  <heath>	i get this error when attempting to import data from a dump. example is a pseudonym for the db, and i've tried importing from 2.1.5 to 2.0.5 as well as 2.1.5 to 2.2.1, both times this error was thrown. i'm happy to open an issue on github if this is a legitimate problem and not a user error

**Comment by Tryneus** [comment] 2016-01-28 20:44
You typically can't import secondary indexes into an earlier version of RethinkDB than the version used to create the indexes, so failing to import from 2.1.5 to 2.0.5 is no surprise.  Failing from 2.1.5 to 2.2.1 is a problem, though.  I can try to reproduce it myself, but it would be helpful to see the corresponding info file for the table (probably `geo.info` given the filename in the error message).
