### ISSUE TITLE
RethinkDB Docker up and running but not functional

### ISSUE THREAD

**Issue by aviranco** [rethinkdb/rethinkdb#6917] opened 2020-10-02 21:04 UTC
**Edit**
After even running a fresh new RethinkDB container went stale, while other dockers are ok, I've restarted the Ubuntu and now it works.

**Describe the bug**
After about 4 years of when I initially tried RethinkDB (before it shut down) and came back to try and use it for a small project. 
I must admit I've noticed many times the docker crashed due to some basic development stage usage, so it's very disturbing, but now I got into a bigger issue - Running rethink docker on ubuntu 20.04, restarting the machine caused the docker to be up and running but not functioning, both via web interface (port 8080) or the regular connections via node.js. Restarting the Docker container did not solve the issue, which is again, super disturbing.

I would now map the volume to the host, so if this issue reoccurs on dev/prod I will be able to delete and re-create the container and hopefully, it will work and the data will persist. However, if the issue is not about the container state but the data volume being corrupted, I won't be able to recover the data in such case as well - it is a BIG problem.

Docker logs (after I did docker restart):
```
Server got SIGTERM from pid 0, uid 0; shutting down...
Shutting down client connections...
All client connections closed.
Shutting down storage engine... (This may take a while if you had a lot of unflushed data in the writeback cache.)
Storage engine shut down.
Running rethinkdb 2.4.1~0buster (CLANG 7.0.1 (tags/RELEASE_701/final))...
Running on Linux 5.4.0-48-generic x86_64
Loading data from directory /data/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on cluster addresses: 127.0.0.1, 172.17.0.2
Listening on driver addresses: 127.0.0.1, 172.17.0.2
Listening on http addresses: 127.0.0.1, 172.17.0.2
Server ready, "c8e0c2a686eb_kyo" e78427a4-019d-4756-8e45-4cd891ba90b1
```

Node.js logs (Not being able to connect to RethinkDB):
```
ReqlDriverError: The connection was closed before the query could be completed
(node:8569) UnhandledPromiseRejectionWarning: ReqlDriverError: None of the pools have an open connection and failed to open a new one.
```

I've created the docker container using the following command:
`sudo docker run -d --restart always -p 8080:8080 -p 28015:28015 -p 29015:29015 --name some-rethink -v "home/aviranco/logs" -d rethinkdb `

**To Reproduce**
I shut down the ubuntu machine and it caused the docker container to go stale.

**Expected behavior**
Expect if the docker container is up - be in a valid state.

**System info**
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

Running on VM using 12GB RAM and 4 CPU.

**Comment by srh** [comment] 2020-10-03 23:52
Duplicate of #6895.  See the workarounds there!

**Closed by srh** 2020-10-03 23:52 UTC
