### ISSUE TITLE
windows install showing 404

### ISSUE THREAD

**Issue by seeyouin2x5x** [rethinkdb/rethinkdb#6821] opened 2020-01-16 11:29 UTC
Hey guys the windows download link isn't working.
https://download.rethinkdb.com/windows/rethinkdb-2.4.0.zip

**Comment by gabor-boros** [comment] 2020-01-21 06:38
Hello @seeyouin2x5x , I'm closing this issue because it is a duplicate of https://github.com/rethinkdb/rethinkdb/issues/6814. We will mitigate this issue as soon as we can

**Closed by gabor-boros** 2020-01-21 06:38 UTC
