### ISSUE TITLE
getAll is not working ?

### ISSUE THREAD

**Issue by githubitsme** [rethinkdb/rethinkdb#6224] opened 2017-01-10 14:56 UTC
hi,
```
   let getFeedFromThesePeople = ['a','b','c']
    let RemoveArray = "'"+getFeedFromThesePeople.join("','")+"'";
                            console.log(RemoveArray);//'a','b','c'
                
                             r.table("posts").getAll(RemoveArray,{index:'username'}).orderBy(r.desc("postedTime")).limit(20).run(conn).then(response => {
                                 console.log(response)
                             })
```
Above code return empty array

but if i change like this it is working
```
 r.table("posts").getAll('a','b','c',{index:'username'}).orderBy(r.desc("postedTime")).limit(20).run(conn).then(response => {
                                 console.log(response)
                             })
```
I don't know whats happening

**Comment by AtnNn** [comment] 2017-01-10 18:19
Duplicate of #6225

**Closed by AtnNn** 2017-01-10 18:19 UTC
