### ISSUE TITLE
return_changes suppresses "changes" in result for unchanged documents

### ISSUE THREAD

**Issue by simonratner** [rethinkdb/rethinkdb#4179] opened 2015-05-04 21:52 UTC
For a conditional update query:
```js
r.table(table).get(id).update(function(doc) {
  return r.branch(
    some_predicate_on_doc,
    some_expression_of_doc,
    null
  )
}, {returnChanges: true})
```
the goal is to atomically apply an update only if the predicate is satisfied. The result of the operation is used to update the local model of the data with new values without doing another read. 

As of 2.0, the query no longer returns changes if nothing has changed (perhaps #3697), however it is still useful to update the local model with the most up-to-date state of the document. With concurrent writes, the client does not know what the state of the document is at the time of executing the query, so it is left to perform another read after receiving an {unchanged: ...} result. That seems wasteful, considering we just paid for reading the document.

The behaviour is also inconsistent with errors, leading to the following workaround, which does return the state of the document at the time of the query:
```js
r.table(table).get(id).update(function(doc) {
  return r.branch(
    some_predicate_on_doc,
    some_expression_of_doc,
    r.error('unchanged')
  )
}, {returnChanges: true})
```

**Comment by mlucy** [comment] 2015-05-04 21:59
Sorry you ran into this!  Closing as a duplicate of #4068.  We'll provide the old behavior as an option soon.

**Closed by mlucy** 2015-05-04 21:59 UTC
