### ISSUE TITLE
`polyglot/changefeeds/sindex` test occasionally hangs

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#3821] opened 2015-02-23 18:47 UTC
Reproduced in `next` using `./test-runner polyglot/changefeeds/sindex -i rb`.  Usually the test takes 3-4 seconds, but sometimes it hangs and is killed by a timeout.
```
== Starting: polyglot/changefeeds/sindex.rb1.9 (T+ 0.3 sec)
>>> Timed out polyglot/changefeeds/sindex.rb1.9 after 300 seconds after 300.2 sec (T+ 300.5 sec)

Timed out after 300 seconds
Using driver port #{DRIVER_PORT}
Created table: test.polyglot_changefeeds_sindex_rb1_9, will be: tbl
TEST FAILURE: polyglot/changefeeds/sindex.rb1.9/17
	BODY: idmax2.to_a
	VALUE: <SignalException "SIGTERM">
	EXPECTED: [{"new_val"=>{"a"=>7, "id"=>2}},
 {"new_val"=>{"a"=>6, "id"=>3}, "old_val"=>{"a"=>7, "id"=>2}}]

Failed 1 tests
Ruby: 19 of 20 tests passed. 1 tests failed.

<<< end Timed out: polyglot/changefeeds/sindex.rb1.9

== Failed 1 test (of 1) in 300.79 seconds!
	polyglot/changefeeds/sindex.rb1.9
```

**Comment by mlucy** [comment] 2015-02-23 20:19
This is probably another one of those "things are sometimes squashed and sometimes not" problems.

**Comment by Tryneus** [comment] 2015-03-04 23:12
Not sure if this is related or if it should be its own issue, but the following tests now fail (with some randomness) in `next`:

	polyglot/changefeeds/idxcopy
	polyglot/changefeeds/point
	polyglot/changefeeds/squash
	polyglot/changefeeds/sindex
	polyglot/changefeeds/table
	polyglot/mutation/atomic_get_set

**Comment by danielmewes** [comment] 2015-03-05 00:55
We should fix these before shipping 2.0.

It's possible that the behavior of some of these operations changed due to us now running multiple queries at once across all clients.

**Comment by Tryneus** [comment] 2015-03-05 00:57
These tests were fairly reliable last week after the parallel queries, the `query_cache_t`, and the new interruption code were all in.  Some recent change to `next` seems to have made these more volatile.

**Comment by danielmewes** [comment] 2015-03-05 04:43
The `atomic_get_set` test broke because of https://github.com/rethinkdb/rethinkdb/issues/3697 (I have a fix for it).

**Comment by danielmewes** [comment] 2015-03-05 23:20
I merged the `atomic_get_set` fix into next https://github.com/rethinkdb/rethinkdb/commit/9c05b97b582b36ebac124d15e27d6fbf9e9814a5 .
The changefeed tests are still flaky and usually failing. I wonder if those might get improved by @larkost's changes in CR 2661 (those are originally for https://github.com/rethinkdb/rethinkdb/issues/3157 I believe)?

**Comment by mlucy** [comment] 2015-03-06 00:09
This might have been caused by the change where we now return the first empty changefeed batch immediately.

**Comment by larkost** [comment] 2015-03-06 19:36
Most of the flakiness is because of timing differences on the first batch, and implicit squashing. I have an idea of how to work around this by making the upcoming `fetch` command allow for a timeout to all for things like "get 2 or 3", then another command to return just the last N items. That would allow for us to pave over that difference.

**Comment by mlucy** [comment] 2015-03-17 00:55
I'll take this.

**Comment by mlucy** [comment] 2015-03-17 01:20
I can't reproduce this.  We've made a lot of small changes/fixes since then, so I think it's likely it was fixed by one of those.

**Closed by mlucy** 2015-03-17 01:20 UTC
Labels: cp:testing
