### ISSUE TITLE
Can't get one-to-many query working

### ISSUE THREAD

**Issue by knownasilya** [rethinkdb/rethinkdb#3774] opened 2015-02-12 23:43 UTC
Tried this in the data explorer:

```js
r.db('mydb').table('workouts').get('0e4c4970-cd9d-47e4-b14f-e85c66a4db7d').merge(function (workout) {
  return {
    routines: r.db('mydb').table('routines').filter(function (routine) {
      return workout('routines').contains(routine('id'));
    })
  }
})
```

but get:

```no-highlight
RqlRuntimeError: Expected type DATUM but found SELECTION:
OPAQUE SELECTION ON table(routines) in:
r.db("fitforms").table("workouts").get("0e4c4970-cd9d-47e4-b14f-e85c66a4db7d").merge(function(var_4) { return {routines: r.db("fitforms").table("routines").filter(function(var_5) { return var_4("routines").contains(var_5("id")); })}; })
```

`workout('routines')` is an array of ids.

**Comment by danielmewes** [comment] 2015-02-12 23:49
Can you try adding a `.coerceTo('ARRAY')` after the value for `routines` like this:
```
r.db('mydb').table('workouts').get('0e4c4970-cd9d-47e4-b14f-e85c66a4db7d').merge(function (workout) {
  return {
    routines: r.db('mydb').table('routines').filter(function (routine) {
      return workout('routines').contains(routine('id'));
    }).coerceTo('ARRAY')
  }
})
```

I think the problem is that `r.table(...).filter(...)` returns a stream, which cannot directly be stored into the field of an object unless it's first converted into an array.

I think this is probably going to be addressed by https://github.com/rethinkdb/rethinkdb/issues/2721 eventually.

**Comment by knownasilya** [comment] 2015-02-13 00:16
@danielmewes thanks, that worked.

Is there a way to put the contents of the `workout` into it's own attribute? Like:

```js
{
  workout: {
    // workout data
  },

  routines: [
    // routines
  ]
}
```

**Comment by danielmewes** [comment] 2015-02-13 00:25
How about this?
```js
r.db('mydb').table('workouts').get('0e4c4970-cd9d-47e4-b14f-e85c66a4db7d').map(function (workout) {
  return {
    workout: workout,
    routines: r.db('mydb').table('routines').filter(function (routine) {
      return workout('routines').contains(routine('id'));
    }).coerceTo('ARRAY')
  }
})
```

Note that I'm using `map` in this query instead of `merge`, which allows me to place the workout data wherever I like.

**Comment by danielmewes** [comment] 2015-02-13 00:25
(closing since not a bug, but feel free to ask more questions)

**Closed by danielmewes** 2015-02-13 00:25 UTC

**Comment by knownasilya** [comment] 2015-02-13 00:59
@danielmewes I get `RqlRuntimeError: Expected type SEQUENCE but found SINGLE_SELECTION:` with that. Maybe I have to coerce it to an array first? Since map is for arrays..

**Comment by danielmewes** [comment] 2015-02-13 01:11
@knownasilya Ah my mistake. `map` only works on sequences and arrays. For a single document we have to use `do`:

```
r.db('mydb').table('workouts').get('0e4c4970-cd9d-47e4-b14f-e85c66a4db7d').do(function (workout) {
  return {
    workout: workout,
    routines: r.db('mydb').table('routines').filter(function (routine) {
      return workout('routines').contains(routine('id'));
    }).coerceTo('ARRAY')
  }
})
```
