### ISSUE TITLE
Subquery as a filter

### ISSUE THREAD

**Issue by vskr** [rethinkdb/rethinkdb#4885] opened 2015-09-25 06:24 UTC
Hey all. I realize github is not the right place to ask usage related questions, but I haven't had luck posting my question on stackoverflow/freenode IRC channel.

Here is my question:

I have two tables 'tasks' (task_id primary key,....) and finished_tasks (task_id, user_id). I want to select rows in 'tasks' that are not finished by user: user_id.

This is what I tried but it is giving me an error

     r.table('tasks').filter( lambda task : task['id'] 
                    not in 
                    r.table('finished_tasks').filter('user_id':user_id).pluck('task_id').run().values()).run()

**Comment by vskr** [comment] 2015-09-25 06:48
I found this to be working. Let me know if this is the best/effective/efficient way.

     r.table('tasks').filter(lambda task : r.not_(r.table('finished_tasks')['task_id'].contains(task['id']))).run\
()

My concern is will the subquery be run for each row/document in 'tasks' table.

Please note that this is just a simplified version of my problem. Please don't suggest changes to schema :)

**Comment by danielmewes** [comment] 2015-09-25 18:39
Hi @vskr, the subquery will indeed run for every row, and it might become pretty slow once the `'finished_tasks'` table becomes bigger.

To optimize it, I recommend creating an index on the `'finished_tasks'` table to allow for efficient lookups by `task_id`:
```py
r.table('finished_tasks').index_create('task_id'),run()
```

Then you can change your filter query as follows (indentation for readability):
```py
 r.table('tasks')
  .filter(lambda task:
    r.table('finished_tasks').get_all(task['id'], index='task_id').is_empty()
   ).run()
```

**Comment by danielmewes** [comment] 2015-09-25 18:40
Closing the issue since it's not a bug or feature suggestion, but please feel free to ask further questions if you have any.

**Closed by danielmewes** 2015-09-25 18:40 UTC
