### ISSUE TITLE
RethinkDB Windows Platform can't create DB

### ISSUE THREAD

**Issue by dhemdhem** [rethinkdb/rethinkdb#6178] opened 2016-11-19 02:07 UTC
RethinkDB 2.3.5-windows
Windows 10

Every time I try to create a new database, the process was stuck and just loading endlessly

**Comment by AtnNn** [comment] 2016-11-19 20:09
Thanks for reporting the issue.

How are you attempting to create the database? Are there any warnings or notices in the server log?

If you are using the web UI: What browser are you using? Are there any errors in the Javascript console?

**Comment by dhemdhem** [comment] 2016-11-20 23:35
I'm using the web UI (Firefox & Edge). 
I've tried creating a database from "+Add Database" menu and invoking r.dbCreate('mydatabase'), server logs said nothing, but the JavaScript console gives me `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` every time I try to make a new database

**Comment by kwasam** [comment] 2016-11-30 04:15
RethinkDB 2.3.5-windows
Windows 10

Works perfectly with chrome.

After doing some digging , I discovered loading underscre.js [Opening http://localhost:8080/js/underscore.js] is stalled in both Edge and Firefox on application startup causing a cascading effect.

**Comment by dhemdhem** [comment] 2016-11-30 08:27
I can confirm this. Using chrome solved the problem

**Comment by Misteralex007** [comment] 2017-04-11 21:30
Just for information, i got the same problem. And it works with Google Chrome as said previously =)

But if we could use firefox, I will appreciate. 
RethinkDB 2.3.5-windows
Windows 10

**Comment by Chinafreak** [comment] 2017-06-07 12:04
I can confirm, too. Firefox isn't working. Chrome is working fine. But I mostly use firefox!

Windows 10
RethinkDB 2.3.5-windows

**Comment by srh** [comment] 2017-12-12 21:51
Closing as a presumed duplicate of #6269.

**Closed by srh** 2017-12-12 21:51 UTC
Labels: tp:bug
