### ISSUE TITLE
Changing a change feed query without re-pulling all the values

### ISSUE THREAD

**Issue by paralin** [rethinkdb/rethinkdb#6073] opened 2016-08-25 17:06 UTC
In, for example, a time series application, I might be interested in all datapoints between time X and Y. I also know new datapoints might come in while I'm watching this range of time values, so I subscribe to a change feed with include_initial set to true. I might later become interested in datapoints between time X-5 and Y+10. I'd rather not re-pull the data I already have, but I do need to pull the data that changing the query adds to the cursor.

One solution is to do the following:

 - Fetch data from the window of time before and after the current window, and add this data to the working set
 - Close the old cursor and subscribe to the entire range with include_initial unset.

However, this is clunky as it does not allow for other types of changes to the query, like further filtering, without competely redoing the query.

My proposal is to allow the cursor to be manipulated a bit to change the scope of the query, and then use change feeds to reflect that change. So, if I expanded my min/max filters in a cursor, I would expect some ADD events to come through the change feed, and vise-versa.

This might be too complex to implement and out of scope of the DB, but I can think of loads of applications where I'd like to change the scope of a cursor without having to re-fetch all the data.

**Comment by deontologician** [comment] 2016-08-26 00:44
Seems similar to #5283

**Comment by paralin** [comment] 2016-08-26 00:51
I think it's the same, probably

**Comment by danielmewes** [comment] 2016-08-26 00:55
Thanks for opening an issue @paralin. Closing as a duplicate of #5283.

**Closed by danielmewes** 2016-08-26 00:55 UTC
