### ISSUE TITLE
Connectng from internal host to host in AWS.

### ISSUE THREAD

**Issue by scottder** [rethinkdb/rethinkdb#5629] opened 2016-04-08 16:27 UTC
I am connecting from an internal host to an AWS instance with a public IP. I have the AWS public IP set as the canonical-address and if the internal host has it's own canonical address set I get the following error.

`
2016-04-08T16:24:42.294560853 11.325906s error: Connected to peer with unresolvable hostname: internal.domain.com, closing connection.  Consider using the '--canonical-address' launch option
`

and if not the AWS instance crashes with this error:

` 2016-04-08T16:21:35.687969881 7.276926s error: Fri Apr  8 16:21:35 2016\n\n1 [0xab4a60]: backtrace_t::backtrace_t() at 0xab4a60 (/usr/bin/rethinkdb)\n2 [0xab4df3]: format_backtrace(bool) at 0xab4df3 (/usr/bin/rethinkdb)\n3 [0xd35a6d]: report_fatal_error(char const*, int, char const*, ...) at 0xd35a6d (/usr/bin/rethinkdb)\n4 [0xd35cc4]: rdb_terminate_handler() at 0xd35cc4 (/usr/bin/rethinkdb)\n5 [0x7f25a42e66d6]: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e6d6) [0x7f25a42e66d6] at 0x7f25a42e66d6 (/usr/lib/x86_64-linux-gnu/libstdc++.so.6)\n6 [0x7f25a42e6703]: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e703) [0x7f25a42e6703] at 0x7f25a42e6703 (/usr/lib/x86_64-linux-gnu/libstdc++.so.6)\n7 [0x7f25a42e6976]: __cxa_rethrow+0x46 at 0x7f25a42e6976 (/usr/lib/x86_64-linux-gnu/libstdc++.so.6)\n8 [0x9cdbf9]: hostname_to_ips(std::string const&) at 0x9cdbf9 (/usr/bin/rethinkdb)\n9 [0x9ce4e6]: host_and_port_t::resolve() const at 0x9ce4e6 (/usr/bin/rethinkdb)\n10 [0x9ce72c]: peer_address_t::peer_address_t(std::set<host_and_port_t, std::less<host_and_port_t>, std::allocator<host_and_port_t> > const&) at 0x9ce72c (/usr/bin/rethinkdb)\n11 [0x9ddfda]: connectivity_cluster_t::run_t::handle(keepalive_tcp_conn_stream_t*, boost::optional<peer_id_t>, boost::optional<peer_address_t>, auto_drainer_t::lock_t, bool*, int) at 0x9ddfda (/usr/bin/rethinkdb)\n12 [0x9dea82]: connectivity_cluster_t::run_t::on_new_connection(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, int, auto_drainer_t::lock_t) at 0x9dea82 (/usr/bin/rethinkdb)\n13 [0x9dfd58]: std::_Function_handler<void (scoped_ptr_t<linux_tcp_conn_descriptor_t>&), std::_Bind<std::_Mem_fn<void (connectivity_cluster_t::run_t::*)(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, int, auto_drainer_t::lock_t)> (connectivity_cluster_t::run_t*, std::_Placeholder<1>, int, auto_drainer_t::lock_t)> >::_M_invoke(std::_Any_data const&, scoped_ptr_t<linux_tcp_conn_descriptor_t>&) at 0x9dfd58 (/usr/bin/rethinkdb)\n14 [0x9c02f6]: linux_nonthrowing_tcp_listener_t::handle(int) at 0x9c02f6 (/usr/bin/rethinkdb)\n15 [0x9d4fa8]: coro_t::run() at 0x9d4fa8 (/usr/bin/rethinkdb)`

All instances are 2.3.0~0trusty

**Comment by danielmewes** [comment] 2016-04-08 17:20
Hi @scottder , have you set the canonical addresses to publicly reachable addresses? Can the internal host reach the public one on the cluster port (29015), as well as the public one the internal one through its canonical address?

The first error suggests that maybe the address passed to `--join` / `-j` isn't a public address. Could that be?


That crash with the backtrace definitely looks like a bug. Pinging @Tryneus .

I wonder if it could be related to https://github.com/rethinkdb/rethinkdb/issues/4470#issuecomment-120178753 . Can you check if you can find any messages "Invalid address family returned by `getaddrinfo`, are you using nscd with EGLIBC 2.19?" in the rethinkdb log?
Can you email us your `ifconfig` output from the affected server as well (daniel@rethinkdb.com)?

**Comment by scottder** [comment] 2016-04-08 17:28
So the internal host can reach the public AWS host on port 29015 and I have the public IP address set as the canonical in AWS.

The AWS instance can't route publicly over the internet back to 29015 however. In previous testing this didn't prevent things from working in my previous tests ( the AWS instance doesn't have join statements back to the internal either.

**Comment by scottder** [comment] 2016-04-08 17:36
And I did not see that error.

**Comment by scottder** [comment] 2016-04-08 17:38
Also in the internal instance I see this: 

`2016-04-08T13:37:21.363213729 5.130731s warn: We were unable to connect to the following peer, or the --join address does not match the peer's canonical address: <AWS_Public_IP>:29015`

But onthe AWS end I do have the canonical-address set to that IP.

**Comment by scottder** [comment] 2016-04-11 13:10
Also, i tried giving the internal instance name in /etc/hosts on the AWS instance and it gave the same backtrace error as above.

**Comment by Tryneus** [comment] 2016-04-11 21:41
I believe I have a fix for the crash - which appears to be an uncaught exception.  Unfortunately, though, I don't think it will fix your connectivity issues, @scottder.  The fix addresses a problem where one peer connects to a second peer, and is informed of a _third_ peer which has an unresolvable address (in review 3593).

This will not fix the connectivity problems because the first peer still cannot resolve the address to the third peer, and you will not get full connectivity.  I may be misunderstanding your situation, but it sounds like you only have two nodes (one internal, one on AWS), so it's a little confusing where the third peer address would be coming from.  This could be explained by stale peer information being kept alive by one of the peers from an old configuration.  If this is the case, shutting down both nodes then restarting them should work.

**Comment by scottder** [comment] 2016-04-11 21:57
Sorry, there are three internal peers that already connected in a cluster. So that may be where the issue is. Thanks

**Comment by Tryneus** [comment] 2016-04-12 21:51
Ok, the fix has been approved and merged to `next` in commit 3e2b6ed, and cherry-picked into `v2.3.x` in commit f7c4e3d.  Will be in release 2.3.1.  I believe this concludes the issue, since the cause of your connectivity issues is understood, @scottder.  Thanks for submitting this issue!

If you're still having problem getting your servers to connect, keep in mind that all members of your cluster should be able to open TCP connections to at least one of the canonical addresses of each other member of the cluster.

**Closed by Tryneus** 2016-04-12 21:51 UTC
Labels: tp:bug

**Comment by cggaurav** [comment] 2016-04-27 07:25
By the way, we solved this using our dockerized rethink containers is by specifying the docker ```--add-host``` parameter that adds mapping to /etc/host in the container so the hostname can be found.

**Comment by danielmewes** [comment] 2016-04-28 00:55
@cggaurav thanks, that's useful to know.
