### ISSUE TITLE
rethinkdb fail to start on windows subsystem for ubuntu!

### ISSUE THREAD

**Issue by anlexN** [rethinkdb/rethinkdb#6606] opened 2018-01-28 03:14 UTC
i'm sure that i successfully install rethinkdb:
![image](https://user-images.githubusercontent.com/8686739/35478613-aa2c1870-041c-11e8-8c31-bddc195d497d.png)

but always stop here!
![image](https://user-images.githubusercontent.com/8686739/35478595-2d1621aa-041c-11e8-80d5-b821014b0ca3.png)

**Comment by srh** [comment] 2018-01-28 16:38
RethinkDB doesn't support the Windows subsystem for Linux.  Or maybe the Windows subsystem for Linux doesn't support RethinkDB...

**Comment by anlexN** [comment] 2018-01-29 03:43
@jackchammons @russalex @bitcrazed @benhillis @scooley @therealkenc @aseering @alexandair, 
can you help me?

**Comment by aseering** [comment] 2018-01-29 06:39
Works for me:

```
bash$ rethinkdb
Recursively removing directory /mnt/c/Users/aseer/tmp/rethinkdb_data/tmp
Initializing directory /mnt/c/Users/aseer/tmp/rethinkdb_data
Running rethinkdb 2.3.6~0xenial (GCC 5.3.1)...
Running on Linux 4.4.0-17083-Microsoft x86_64
Loading data from directory /mnt/c/Users/aseer/tmp/rethinkdb_data
warn: Cache size does not leave much memory for server and query overhead (available memory: 1110 MB).
warn: Cache size is very low and may impact performance.
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on cluster addresses: 127.0.0.1, 127.0.1.1, ::1
Listening on driver addresses: 127.0.0.1, 127.0.1.1, ::1
Listening on http addresses: 127.0.0.1, 127.0.1.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "SLAB_7ym" 16e3861d-8b21-4533-975f-31893eba1ed9
```

What Windows build are you using?  Maybe you need a newer version of Windows?  WSL is still under development and missing functionality is being added regularly.  This is what I'm running:

```
cmd> ver                                                                                                                                                                                                                              Microsoft Windows [Version 10.0.17083.1000]
```

If you do have an older build, you might try running rethinkdb from a directory under `/home`, rather than under `/mnt`.  The POSIX-filesystem support under `/home` is much more complete.  The trade-off is, you can't safely access directories there from non-Linux applications.

**Comment by anlexN** [comment] 2018-01-30 03:42
![default](https://user-images.githubusercontent.com/8686739/35546947-4ee9bfe4-05b1-11e8-8422-cdefee25e841.PNG)

![image](https://user-images.githubusercontent.com/8686739/35547127-42295034-05b2-11e8-9c5a-04c3367d3a83.png)
@aseering , what happened in my desktop ? Because of chinese version? what rethinkdb version do you use?

**Comment by aseering** [comment] 2018-01-30 14:55
I'm using rethinkdb 2.3.6~0xenial.

I'm actually using the latest [Windows Insider build](https://insider.windows.com/en-us/getting-started/) on my laptop.  It's a free program, easy to switch to, gets you newer Windows builds, but the builds may be less stable than regular Windows.  You have the latest stable version of Windows.  So maybe this is an issue that's fixed in a more-recent Windows build?

WSL issues aren't fixed in Windows hotfixes; they go out as service packs a few times per year.  So you could get an updated version by switching to Insider builds, or by waiting a few months for the next Windows release.

**Comment by bitcrazed** [comment] 2018-01-30 21:28
@anlexN - Hi - PM at Microsoft for WSL & Console here.

Could I also ask you to file an issue in our WSL Issues repo: https://github.com/microsoft/wsl. 

When you do, please complete the issue template, and also:
1. Please paste text from terminal/console rather than screenshots of text - text can be searched, images typically cannot
2. Please provide as much detail about the issue. Repro steps, versions of OS & software used, etc. are very helpful & makes it much easier to repro & diagnose :)

Thanks in advance.

**Comment by anlexN** [comment] 2018-01-31 02:18
@aseering , i don't dare install Windows Insider build , ever, my computer can't be power on and always is black screen because of insider build. can you help me think of other solutions? thanks~
@bitcrazed , i have posted a [issue](https://github.com/Microsoft/WSL/issues/2892) on wsl repo. thanks too!
#### i love wsl and rethinkdb very much.

**Comment by gabor-boros** [comment] 2022-05-03 11:33
Closing as the microsoft issue couldn't reproduce it either.

**Closed by gabor-boros** 2022-05-03 11:33 UTC

**Comment by srh** [comment] 2022-05-06 08:54
It has been reported to me that RethinkDB works on WSL 2.
