### ISSUE TITLE
Crash when opening newer data directory

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/rethinkdb#3750] opened 2015-02-09 02:14 UTC
When trying to open a 1.16 data directory on 1.15-3 on OS X:

```
orpheus:~ michael$ rethinkdb
info: Running rethinkdb 1.15.3-1 (CLANG 6.0 (clang-600.0.56))...
info: Running on Darwin 14.1.0 x86_64
info: Using cache size of 100 MB
warn: Requested cache size is larger than available memory.
warn: Cache size is very low and may impact performance.
info: Loading data from directory /Users/michael/rethinkdb_data
Version: rethinkdb 1.15.3-1 (CLANG 6.0 (clang-600.0.56))
error: Data version not recognized. Is the data directory from a newer version of RethinkDB? (version on disk: 4)
Version: rethinkdb 1.15.3-1 (CLANG 6.0 (clang-600.0.56))
Crashing while already crashed. Printing error message to stderr.
Guarantee failed: [this->prev_ == this] non-empty intrusive list destroyedVersion: rethinkdb 1.15.3-1 (CLANG 6.0 (clang-600.0.56))
Crashing while already crashed. Printing error message to stderr.
Guarantee failed: [this->next_ == this] inconsistent intrusive list (end node)!Version: rethinkdb 1.15.3-1 (CLANG 6.0 (clang-600.0.56))
Crashing while already crashed. Printing error message to stderr.
Guarantee failed: [size_ == 0] empty intrusive list destroyed with non-zero size
```

**Comment by coffeemug** [comment] 2015-02-09 07:57
Please post what you would expect to happen. (Presumably in this case you'd expect us not to print all the guarantees/crashing info)

**Comment by mglukhovsky** [comment] 2015-02-09 08:03
Sorry, I thought it was evident from the log: we shouldn't crash, nor dump a lot of output when a user accidentally tries to run the wrong version on a newer directory.

**Comment by danielmewes** [comment] 2015-02-09 19:20
Duplicate of https://github.com/rethinkdb/rethinkdb/issues/3698 (except this one is triggered by a different version check, but the crash seems to be the same)

**Closed by danielmewes** 2015-02-09 19:20 UTC
