### ISSUE TITLE
Error in Import on Big json file

### ISSUE THREAD

**Issue by sebadiaz** [rethinkdb/rethinkdb#4451] opened 2015-06-25 11:17 UTC
When I have a big json file an error occur during the parsing phase because the json file is more than the buffer size
misys@ubuntu:~/project/cnam/airbase$ rethinkdb import -f data/AT_meta.xml.json --table test.users --force --debug 
[                                        ]   0% 
0 rows imported in 1 table
Expecting object: line 957981 column 11 (char 67108863)
ValueError traceback: [('/usr/local/lib/python2.7/dist-packages/rethinkdb/_import.py', 548, 'table_reader', 'exit_event)'), ('/usr/local/lib/python2.7/dist-packages/rethinkdb/_import.py', 420, 'json_reader', 'json_data[offset] == "[")'), ('/usr/local/lib/python2.7/dist-packages/rethinkdb/_import.py', 371, 'read_json_array', '(obj, offset) = decoder.raw_decode(json_data, idx=offset)'), ('/usr/lib/python2.7/json/decoder.py', 382, 'raw_decode', 'obj, end = self.scan_once(s, idx)')]
In file: /home/misys/project/cnam/airbase/data/AT_meta.xml.json
Errors occurred during import

**Comment by danielmewes** [comment] 2015-06-25 18:47
Thanks for the report and pull request (https://github.com/rethinkdb/rethinkdb/pull/4452) @sebadiaz !

I'm wondering if there's a way to avoid having to set the buffer size manually for large files. I think that isn't very user friendly. Could we adapt it automatically to the file size, or use some different data structure that grows automatically? I don't know much about what that buffer is currently used for in the import script unfortunately.
Pinging @Tryneus .

**Comment by Tryneus** [comment] 2015-06-25 23:21
I suspect this isn't the reason for the failure.  The problem isn't the size of the file, but the size of the rows.  This failure occurs when we have buffered 128 MB of the file and can't parse out a valid json object from it.  I'm fairly sure we can't import rows that large (due to protobuf limits).  I think it's more likely that the JSON file has a syntax error in it.

**Comment by danielmewes** [comment] 2015-06-25 23:30
Oh... I think our size limit is still 64 MB per query right?

@sebadiaz Were you actually able to import the affected json file with your patch?

**Comment by sebadiaz** [comment] 2015-06-26 07:51
I suspect an other error, my case is easy I have just one file containing one json structure and not starting with a list. I m not sure that having a limit in term of row, more exactly a json object in multiple file line, is the real error. Perhaps,it is the mix between [{ and not [{ . effectively on the same json I have some json array , sometime in big quantity.
My patch has permitted to read the values without errors. But effectively , an other patch could be more smart in term of automatic setting. 
I'm reading the code to search an other solution.

**Comment by sebadiaz** [comment] 2015-06-26 08:18
The reason appear more clear on a big document when an arry is not finished we extend the file reading to continue on the array parsing
code extracted 
before_len = len(json_data) -> we take the size of the actual structure
to_read = max(json_read_chunk_size, before_len) -> we get this previous measure as max
json_data += file_in.read(min(to_read, json_max_buffer_size - before_len)) -> finally we use json_max_buffer_size - before_len because < to_read --> could be negative on non raising step(see next lines)

after reading we have
elif before_len == len(json_data) or len(json_data) >= json_max_buffer_size: --> this is the error , we can't raise on unfinished array 
                raise


Two solutions
  - set a big json_max_buffer_size with two solutions : 
	- fixed at starting
	- set to the file size
  - continue to read unless size limit exceed my new patch proposition in removing json_max_buffer_size
	except (ValueError, IndexError):
            before_len = len(json_data)
            to_read = max(json_read_chunk_size, before_len)
            json_data += file_in.read(to_read)
            if json_array and json_data[offset] == ",":
                offset = json.decoder.WHITESPACE.match(json_data, offset + 1).end()
            elif (not json_array) and before_len == len(json_data):
                break  # End of JSON
            elif before_len == len(json_data):
                raise
            progress_info[0].value = file_offset

**Comment by Tryneus** [comment] 2015-06-26 18:39
@sebadiaz, if I understand your situation correctly, you're saying you have a JSON file containing a single JSON object (not an array of objects) larger than 128 MB in size?  If so, this isn't supported by the server (and I'm wondering if this is related to the error you reported in #4462).

**Comment by sebadiaz** [comment] 2015-06-26 18:53
To resume yes and more particular during serialization of an array of the object

**Comment by danielmewes** [comment] 2015-07-01 23:47
@sebadiaz We're still a bit unsure what's happening in your case. Is it a single document that's more than 200 MB or is that the total file size? The thing is that there's a 64 MB limit on the size of data that can be imported into a table in a single query, so we would expect the import of such a document to fail.
Theoretically if the JSON encoded document has a lot of whitespaces in it (e.g. if it's indented), that might explain why a much larger JSON file can still be imported though.

In general I would still prefer a solution that doesn't add additional parameters to the import tool though.

**Comment by sebadiaz** [comment] 2015-07-15 09:41
Hi, I have pushed a version without parameters.
For sure that the file is extensive in buffering size during the parsing, but not in document size.

**Comment by danielmewes** [comment] 2015-07-22 00:49
This was fixed by https://github.com/rethinkdb/rethinkdb/pull/4452 and will ship with RethinkDB 2.1.0. Thanks @sebadiaz

**Closed by danielmewes** 2015-07-22 00:49 UTC
Labels: tp:bug
