### ISSUE TITLE
Nodes in the cluster disconnecting when running query

### ISSUE THREAD

**Issue by r-marques** [rethinkdb/rethinkdb#5280] opened 2016-01-12 08:11 UTC
##### Setup

- 12 node cluster in ec2 m3.2xlarge (8 cores, 30GiB memory, ssd storage)
- table with 5 million documents, 12 shards , and 1 replicas
- python 3.4.3
- driver rethinkdb 2.2.0.post1

##### Example document

```javascript
{

    "assignee": "3049301306072a8648ce3d020106082a8648ce3d030101033200045a86875b2ac478d153dfff03c0ff41a7fd0e9a19a7a02e3e6b8693e979393dbbb329969e0f1fb058dbad655262f65a77" ,
    "id": "cdfb20ec2991226a567b37dd9a99259cd18ffe735a095d91ebb768084cb243fe" ,
    "signature": "303502187f06fb907a8c86d95b8f2bcb352d03eeb0d3301a139f54e7021900830ac501a050de370353b29aed0593dca21f189e9c960933" ,
    "transaction": {
        "current_owner": "3049301306072a8648ce3d020106082a8648ce3d03010103320004e160db58228809222568e77439ac6c3530b8ce1d9b49c58cf175439df7adaf364af2145e4ab3f3e3173b7cfe55ce87d4" ,
        "data": {
            "hash": "4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45"
        } ,
        "input": null ,
        "new_owner": "3049301306072a8648ce3d020106082a8648ce3d0301010332000475c70719081277fe5271075069ee5a5d509d1cef95afa1b32161dc28bcefc82c3e34ffa278ad7357d00946a6ba6f56d0" ,
        "operation": "CREATE" ,
        "timestamp": "1450277322.428634"
    }

}
```

##### Secondary Index
```python
r..table('backlog')\
        .index_create("assignee__transaction_timestamp", [r.row["assignee"], r.row["transaction"]["timestamp"]])\
        .run()
```

##### Query
```python
cursor = r.table('backlog')\
            .between([b.me, r.minval], [b.me, r.maxval], index='assignee__transaction_timestamp')\
            .order_by(index=r.asc('assignee__transaction_timestamp'))\
            .run(b.conn)
```

When running this query some nodes in the cluster get disconnected.
Both `assignee` and `timestamp` are strings and have always the same length.
This query returns around 350k documents.

Looking at the logs the only error messages I see are `Heartbeat timeout`
```bash
2016-01-08T10:21:36.636116610 268443.333925s error: Heartbeat timeout, killing connection to peer [::ffff:172.31.29.224]:40390
2016-01-09T13:04:49.253478030 364635.951287s error: Heartbeat timeout, killing connection to peer 172.31.30.149:29015
2016-01-11T10:39:26.090469596 528712.788278s error: Heartbeat timeout, killing connection to peer 172.31.25.145:29015
2016-01-11T10:39:49.998998159 528736.696806s error: Heartbeat timeout, killing connection to peer [::ffff:172.31.25.59]:45783
```

This may be related to #5279 although I don't see a high utilization of io or RAM when running the query.

**Comment by danielmewes** [comment] 2016-01-12 18:52
Thanks for the report @r-marques .

@mlucy Do you think this could be caused by key truncation? Maybe we don't yield if there are a lot of documents with the same truncated key?

@r-marques Would it be an option to make the `assignee` shorter? For example you could use `r.uuid` (http://rethinkdb.com/api/javascript/uuid) to hash the assignee string. I think this might give you better performance, though I'm not sure if this will resolve the issue or not.

**Comment by mlucy** [comment] 2016-01-12 19:42
@danielmewes -- We *should* be yielding even for truncated keys because all that logic does is prevent the normal iteration logic from aborting when it normally would, but it's certainly possible there's a bug related to that.  It's also possible that there's somewhere else where we don't yield when processing the batch, and if the batch is sufficiently large (which you'd get in this case with truncated keys) then we take a long time to yield.

**Comment by r-marques** [comment] 2016-01-13 07:38
@danielmewes I will try using r.uuid.

For now I replaced the cursor with a changefeed with `include_initial=True` and I no longer have this problem, don't know if this helps

**Comment by danielmewes** [comment] 2016-01-13 22:47
@r-marques That is very interesting. In the version of RethinkDB you're running (2.2.0), an `include_initial=True` changefeed indeed used different logic to read the initial data. Note that this changed with RethinkDB 2.2.2, where it became more similar to a normal read. So you should be careful when upgrading about a possible performance regression (though in general I would still recommend upgrading, since there also were some bugs in the old `include_initial` implementation).

I'm don't understand why exactly the issue would go away with `include_initial=True` though. So this is still a bit of a mystery. At the moment we think that it might have to do with the comparably long keys in the secondary index. It's usually a good idea to keep the total key length of a secondary index below 128 bytes.
Note that you could even use `r.uuid` inside the index function, instead of changing the fields you're storing in the documents:
```js
r.table('backlog')\
        .index_create("assigneeU__transaction_timestamp", [r.uuid(r.row["assignee"]), r.row["transaction"]["timestamp"]])\
        .run()
```

Then when querying, you'll need to apply `r.uuid` to the `between` boundaries as well.

**Comment by danielmewes** [comment] 2016-01-13 22:48
Oh sorry I misread that. 2.2.0.post1 was the version of the driver of course.
Which version of the RethinkDB server are you running?

**Comment by r-marques** [comment] 2016-01-14 09:38
We are using the latest version 2.2.3-1. We are not in production yet so we always upgrade to the latest version.

I will use the r.uuid trick when creating the index and test again

**Comment by mlucy** [comment] 2016-01-14 19:41
If changefeeds are faster here, it's probably because they aren't respecting the ordering.  `table.orderBy(...).changes(include_initial: true)` is *not* guaranteed to return the initial values in any particular order, although it will usually return them in something close to the ascending ordering for whatever index you use.

**Comment by r-marques** [comment] 2016-01-15 07:23
@mlucy In this case the problem is not speed. When doing the same query without changefeed nodes start to disconnect from the cluster and with changefeeds that does not happen.

Its good to know that the ordering may not be respected but that is not covered in the documentation and in fact there are examples using `orderBy` in the `changes` documentation

**Comment by mlucy** [comment] 2016-01-15 08:06
@r-marques -- are there examples that look like `r.table('test').orderBy(index: ...).changes()` in the docs?  There should be examples that look like `r.table('test').orderBy(index: ...).limit(n).changes()`, where you need the ordering to define the extrema that you want to subscribe to changes on, but if there are examples with `orderBy` but no `limit` we should probably remove them to avoid confusion.

**Comment by r-marques** [comment] 2016-01-15 10:30
@mlucy The examples do have `limit` in them. I realized that in the documentation it says "order_by requires limit; neither command works by itself." I am not using limit and it works.

So from what I understand is that using `order_by` without `limit` in a changefeed does not guarantee correct ordering, right?

And if I do use limit how can I get all the documents with `include_initial=True`?

**Comment by mlucy** [comment] 2016-01-16 01:47
@r-marques -- changefeeds really aren't designed to provide documents in a particular order, they're designed to provide changes in the order they happen.  There isn't really support right now for getting initial values in a guaranteed order.

**Comment by danielmewes** [comment] 2016-01-16 01:58
@r-marques Sorry about the confusion regarding `orderBy.changes`. I think we should actually disallow this query, since it doesn't currently do what it looks like. I opened https://github.com/rethinkdb/rethinkdb/issues/5293 to discuss that change.

We still need to figure out the reason for the initial performance issue.
Please let us know when you get a chance to try the uuid keys.

**Comment by r-marques** [comment] 2016-01-18 14:54
@danielmewes I did not test the code with `r.uuid` but I changed the code to have the `assignee` field with a length of 60 characters. I ran the queries again and I had no disconnect problems with a smaller size `assignee` so maybe the problem was with the size of the secondary index.

**Comment by danielmewes** [comment] 2016-01-18 19:14
Ok that makes sense. You'll probably see better efficiency of the query with the shorter indexes in general.

We'll look into why it caused a disconnect before, but this gives us a pretty good idea of what the disconnects might be related to and where to look.

**Comment by nighelles** [comment] 2016-02-04 01:32
A fix for this is in review 3461,
implemented in nighelles/5280.

**Comment by nighelles** [comment] 2016-02-08 18:35
This is in next.

**Closed by nighelles** 2016-02-08 18:35 UTC
Labels: pr:high, tp:performance

**Comment by danielmewes** [comment] 2016-02-09 19:21
It's worth noting that @nighelles 's patch also makes ordered secondary index reads significantly more CPU efficient by optimizing the comparison operation.

It can save close to 50% CPU time in some cases.

**Comment by r-marques** [comment] 2016-02-09 22:51
that's really awesome, thanks

**Comment by danielmewes** [comment] 2016-02-09 22:53
@nighelles could you cherry-pick this change into `v2.2.x` as well please?
Should be as easy as checking out `v2.2.x` and doing `git cherry-pick 72bd1ec4553fd1f949a5de56193b9411c4f5df2a`

**Comment by nighelles** [comment] 2016-02-09 23:11
Ok, this is in v2.2.x
