### ISSUE TITLE
Server crashes when adding an index to an empty table

### ISSUE THREAD

**Issue by niieani** [rethinkdb/rethinkdb#4025] opened 2015-04-07 23:24 UTC
Executing the following commands crashes the server:

```javascript
r.dbCreate('newdb')
r.db('newdb').tableCreate('bubbles')
r.db('newdb').table("bubbles").indexCreate("hash")
```

The process simply quits.

**Comment by mlucy** [comment] 2015-04-07 23:31
@niieani -- thanks for the bug report!  I can't seem to reproduce this behavior.  What version of RethinkDB are  you running, and on what platform?

**Comment by niieani** [comment] 2015-04-07 23:34
I'm running the official Docker distribution of RethinkDb, that's running inside a VirtualBox. I've installed it using Kitematic. The version in the Docker repository seems to be 1.16.2-1.

**Comment by mlucy** [comment] 2015-04-07 23:36
@danielmewes -- I seem to recall we've had trouble with VirtualBox before, do you remember the context?

**Comment by danielmewes** [comment] 2015-04-07 23:41
Hi @niieani, sorry you're running into this.
The problem is that VirtualBox shared folders behave differently from normal file systems, which triggers this crash.

We're going to work around this in our upcoming 2.0 release, which will work just fine on shared folders. We'll release it next week. You can also try our 2.0 release candidate https://github.com/rethinkdb/rethinkdb/releases/tag/v2.0.0-0RC1 .

Also see https://github.com/stuartpb/rethinkdb-dockerfiles/issues/4

This is a duplicate of https://github.com/rethinkdb/rethinkdb/issues/3791

**Closed by danielmewes** 2015-04-07 23:41 UTC
Labels: tp:bug
