### ISSUE TITLE
Keys are invalid 

### ISSUE THREAD

**Issue by vmahadev** [rethinkdb/rethinkdb#6754] opened 2019-08-04 09:46 UTC
"W:GPG error: http://download.rethinkdb.com/apt trusty Release: The following signatures were invalid: EXPKEYSIG CF9BDC6F03D1F02B RethinkDB Packaging <packaging@rethinkdb.com>, E:The repository 'http://download.rethinkdb.com/apt trusty Release' is not signed."}

**Comment by gabor-boros** [comment] 2019-08-06 21:07
This issue is a duplicate of https://github.com/rethinkdb/rethinkdb/issues/6750

**Closed by gabor-boros** 2019-08-06 21:07 UTC
