### ISSUE TITLE
Version tag in make process is incorrect.

### ISSUE THREAD

**Issue by Panoplos** [rethinkdb/rethinkdb#6378] opened 2017-05-30 08:20 UTC
I have built and installed rethinkdb from git `next` branch, but when running the server it is telling me that the version is some random windows branch tag.

### Build Config
```fish
⟩ ./configure --allow-fetch --prefix=/opt CXX=g++-5
* Detecting system configuration
Bash:                           4.4.7(1)-release
Use ccache:                     no
C++ Compiler:                   GCC 5.4.1 (g++-5)
Host System:                    x86_64-linux-gnu
Build System:                   Linux 4.10.0-21-generic x86_64
Cross-compiling:                no
Host Operating System:          Linux
Build Architecture:             x86_64
C++11:                          ok
Precompiled web assets:         no
Protobuf compiler:              /usr/bin/protoc
python:                         python 2.7.13
Node.js package manager:        /usr/bin/npm
coffee:                         external/coffee-script_1.10.0
Browserify:                     external/browserify_13.1.0
bluebird:                       external/bluebird_2.9.32
web UI dependencies:            external/admin-deps_2.0.4
wget:                           /usr/bin/wget
curl:                           /usr/bin/curl
Google Test:                    external/gtest_1.7.0
termcap:                        -ltermcap
boost_system:                   -lboost_system
protobuf:                       -lprotobuf
v8 javascript engine:           external/v8_3.30.33.16-patched
RE2:                            external/re2_2015-11-01
z:                              -lz
crypto:                         -lcrypto
ssl:                            -lssl
curl:                           external/curl_7.40.0
malloc:                         jemalloc
jemalloc (static):              external/jemalloc_4.1.0
Test protobuf:                  ok
Test boost:                     ok
Installation prefix:            /opt
Configuration prefix:           /opt/etc
Runtime data prefix:            /opt/var
* Wrote configuration to config.mk
```
### Version Reported by RethinkDB
```fish
⟩ rethinkdb --version
rethinkdb 2.3.2-windows-beta-405-gb51d7c (GCC 5.4.1)
```
### Expected
`2.3.5` or `HEAD` or something of this manner as this is pulled from `next`.
```fish
⟩ git branch 
* next
```
The culprit seems to be in `scripts/gen-version.sh`'s `git_gen_version`, as it is calling `git describe --tags --match "v[0-9]*" --abbrev=6 HEAD`, which finds the most recent tagged version in repo that matches "v[0-9]*". This logic is broken. :rofl:

**Comment by AtnNn** [comment] 2017-06-08 21:21
That behaviour is expected. The issue is that we have a `v2.3.2-windows-beta` tag that is newer than `v2.3.5` because of how windows releases were managed. This will be fixed once v2.4.0 is released.

As a workaround, you can `make PVERSION=HEAD` or `echo HEAD > VERSION.OVERRIDE`

**Closed** 2017-06-08 21:21 UTC
