### ISSUE TITLE
Backup rethinkdb_data folder instead of rethinkdb dump?

### ISSUE THREAD

**Issue by cggaurav** [rethinkdb/rethinkdb#5323] opened 2016-01-27 12:46 UTC
We are running rethink in a docker container and I am interested to know the downsides if we do a backup of the rethinkdb_data folder on the host for the master instance instead of backing up the zipped rethinkdb dump file which can be run only from the container.

**Comment by encryptio** [comment] 2016-01-28 19:24
Backing up `rethinkdb_data` will only get you a copy of the data currently written to that disk. There are many problems with this:
- Using a non-atomic snapshot (`tar`, `rsync`, etc) does not guarantee that the writes rethinkdb does are ordered properly, and would probably result in a corrupted backup most of the time.
- Taking an atomic snapshot usually involves a deliberate pause of all filesystem activity (see e.g. `fsfreeze`), which may cause issues with availability if it takes longer than expected.
- You can only do this on a single node database; once you get to a cluster, it no longer works. (The raft implementation depends on the nodes' storage not going backwards in time; restoring from a backup would effectively run the nodes backwards, and would violate some consistency guarantees.)
- You have to run the snapshot on the same physical hardware as the database.

None of these restrictions apply to `rethinkdb dump`.

Also note that `rethinkdb dump` just uses the python client library, and you can run it from anywhere, not just inside the same container the DB is running in; that's probably your best bet.

Closing because this is not a bug, but feel free to continue to ask questions here if you like.

**Closed by encryptio** 2016-01-28 19:24 UTC

**Comment by danielmewes** [comment] 2016-01-29 20:12
There are certain ways of making this work by having a special single replica that receives all the data. 

It is important that that replica is shut down before taking the `rethinkdb_data` folder backup (or that some sort of atomic filesystem-level snapshot is taken).

Additional care must be taken when restoring from such a backup for the reasons @encryptio mentioned, specifically a server started from a backup must *never* be allowed to join with other servers in the cluster that still have their data directories. Otherwise the cluster can get in an into a bad state which can lead to crashes and/or data loss.

I wouldn't generally recommend this strategy, unless there are special reasons that rule out `rethinkdb dump` as an option.
