### ISSUE TITLE
server_test.rb1.9 failure

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3581] opened 2015-01-16 00:15 UTC
```
~/rethinkdb/test/rql_test $ ./test-runner server_test
Warning: did not find any tests for javascript
Warning: did not find any tests for python 2.6
Using rethinkdb binary /home/ssd2/mlucy/rethinkdb/build/debug_clang/rethinkdb
        ruby 1.9 interpreter: /usr/bin/ruby1.9, driver: /home/ssd2/mlucy/rethinkdb/drivers/ruby
== Starting: server_test.rb1.9 (T+ 0.3 sec)
>>> Failed server_test.rb1.9 with exit code 1 after 9.9 sec (T+ 10.6 sec)

Run options:

# Running tests:

...F

Finished tests in 9.593413s, 0.4170 tests/s, 29.3952 assertions/s.

  1) Failure:
test_malformed_queries(ClientTest) [/home/ssd2/mlucy/rethinkdb/test/rql_test/server_test.rb:133]:
<{"t"=>16, "b"=>[], "r"=>["Protocol error, connection closed."]}> expected but was
<{"t"=>16, "r"=>["Client is buggy (failed to deserialize query)."], "b"=>[]}>.

4 tests, 282 assertions, 1 failures, 0 errors, 0 skips

<<< end Failed: server_test.rb1.9

== Failed 1 test (of 1) in 11.06 seconds!
        server_test.rb1.9
```

**Comment by mlucy** [comment] 2015-01-16 00:16
It's plausible this one is my fault since it seems to involve the Ruby driver; if nobody else gets to it I'll look into it once I'm done with the 1.16 stuff I'm working on now.

**Comment by larkost** [comment] 2015-01-16 00:35
Duplicate of #3375

**Closed by larkost** 2015-01-16 00:35 UTC
