### ISSUE TITLE
r.js causes a crash in a worker process if total system memory is 1GB or less

### ISSUE THREAD

**Issue by elifarley** [rethinkdb/rethinkdb#3703] opened 2015-01-30 18:17 UTC
Rethinkdb 1.15.3 and 1.16 (installed from rethinkdb's Yum repo)
Cache size of 100 MB
Total system memory: 1 GB
~5400 documents
Fedora release 20 (Heisenbug)  Kernel 2.6.32-042stab093.4 x86_64 under OpenVZ

Every time I run the query below, I get this error:

RqlRuntimeError: Javascript query `(function(row) {return {mime2: row.mime}; })` caused a crash in a worker process in:
r.table("en").hasFields("file_name").pluck("file_name", "title", "mime").merge(r.js("(function(row) {return {mime2: row.mime}; })"))
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
The query that returned an error is:

r.table('en').hasFields('file_name').pluck('file_name','title','mime').merge( r.js("(function(row) {return {mime2: row.mime}; })") ) 

---

But there's a workaround: use 'limit' after 'table', like this:

r.table('en2').insert(r.table('en').hasFields('file_name').pluck('mime'))
r.table('en2').count(): 3203
r.table('en2'). merge( r.js("(function(row) {return {mime2: row.mime}; })") ) : NOT OK!
r.table('en2').limit(5000). merge( r.js("(function(row) {return {mime2: row.mime}; })") ) : OK!

**Comment by danielmewes** [comment] 2015-01-30 19:15
Thank you for the bug report @elifarley and sorry you had to run into this.

Which Linux distribution are you using?

Is there a chance you can send us your database so we can try reproducing this locally? We can send you instructions on how to upload your data files to us safely.

**Comment by elifarley** [comment] 2015-01-30 19:35
I could send you another table with fake values. Is there a simple ReQL command (like SELECT ... INTO TABLE) to do this?

**Comment by danielmewes** [comment] 2015-01-30 19:43
Thanks for the info. Does the bug happen on the table with the fake values as well?
For copying from one table into another, you can run `r.table("dest").insert(r.table("src"))`
For dumping a specific table to a file, you can use the console command `rethinkdb dump -e <db>.<table>` (e.g. `rethinkdb dump -e test.en` to dump the table `en` in the default database `test`).

**Comment by elifarley** [comment] 2015-01-30 22:45
r.table('en2').insert(r.table('en').hasFields('file_name').pluck('mime'))
r.table('en2').count(): 3203
r.table('en2').limit(5000). merge( r.js("(function(row) {return {mime2: row.mime}; })") )  :          OK!
r.table('en2').                   merge( r.js("(function(row) {return {mime2: row.mime}; })") )  : NOT OK!

How can upload the dump file (76 KB) ?

**Comment by danielmewes** [comment] 2015-01-31 00:03
Very interesting. I have no idea out of my head why the `limit(5000)` would make a difference, but we'll try to find out.

If the file is just 76 KB, can you just send it to me in an email? daniel@rethinkdb.com

Thanks for your help in debugging this by the way, we really appreciate it.

**Comment by danielmewes** [comment] 2015-02-11 03:10
@elifarley Not sure if I missed your email. Did you get a chance to send me the dump file so we can start looking into the bug?

**Comment by elifarley** [comment] 2015-02-11 04:48
Yep, I sent it on Jan 30th. I'll re-send it now, just in case.

Thanks,

Elifarley Cruz

**Comment by danielmewes** [comment] 2015-02-11 05:23
Sorry my fault. Thank you for resending the data @elifarley .
I just had a quick try using the CentOS package as well as the Ubuntu Precise package. I couldn't reproduce the crash yet, but will try this more tomorrow.

@elifarley Did you compile from source or are you using our Yum repository?

**Comment by danielmewes** [comment] 2015-02-11 06:58
@elifarley Another question: Can you send us the log file and/or server console output from when the JS crash happened? It might contain additional information on where exactly the query was aborted.

You can find the log file in your rethinkdb_data directory.

**Comment by elifarley** [comment] 2015-02-11 12:31
@danielmewes: I've installed from your Yum repo.

After upgrading my VPS server from 1 GB to 2 GB RAM, I'm unable to reproduce the error, even if I use '--cache 100'.

**Comment by danielmewes** [comment] 2015-02-11 19:04
Thanks for the update @elifarley. Hmm maybe it just ran out of memory and the kernel killed the worker process...

**Comment by elifarley** [comment] 2015-02-12 19:09
So by using limit(5000) in my query memory consumption is reduced?

Would it be advisable to always try to use limit(some-big-integer) just to conserve memory?

**Comment by danielmewes** [comment] 2015-02-12 20:04
@elifarley the `limit(5000)` causes the `r.js` processing to be limited to one CPU core, while without the limit it's being parallelized over all cores. That might have affected memory consumption.

In general I do not recommend putting a `limit` into every query, because it will also slow some queries down.

**Comment by danielmewes** [comment] 2015-02-12 23:59
So I think this is probably not a bug but just a memory issue.
In a very quick test using the variant without `limit(5000)` definitely used more memory, but I'm not 100% sure if that was actually what was causing the `r.js` worker to terminate / be terminated.

Since it went away for you @elifarley after upgrading memory, I would like to close this issue the issue shows up again.
I'm going to open a separate issue to discuss what we can do to limit `r.js` memory requirements.

**Closed by danielmewes** 2015-02-12 23:59 UTC

**Comment by danielmewes** [comment] 2015-02-13 02:51
I just did another test and the difference in memory consumption between running the query with and without `limit` is about 300 MB. So that makes the "running out of memory" theory look very plausible.

**Comment by danielmewes** [comment] 2015-02-13 03:01
@elifarley Actually that test was on a machine with many CPU cores, and I think the memory overhead will be smaller if you have less than 8 cores (in the range of 50 MB per core). How many cores does your server have?

**Comment by elifarley** [comment] 2015-02-13 11:04
It's got 3 cores.
