### ISSUE TITLE
 Error: ReqlOpFailedError: primary replica issues

### ISSUE THREAD

**Issue by honkycat** [rethinkdb/rethinkdb#5891] opened 2016-06-28 19:06 UTC
I've got a cluster of rethinkdb boxes running in gcloud on ubuntu 14.04 virtual machines.

`"version":  "rethinkdb 2.3.4~0trusty (GCC 4.8.2)"`

Talking to this cluster I have a kubernetes cluster, which is running  a number of rethinkdb proxy nodes, hidden behind a load balancer.

Most of the time, the requests work fine, but I see quite often errors such as these:

```
Error: ReqlOpFailedError: Cannot perform read: lost contact with primary replica in:
```

and:

```
Error: ReqlOpFailedError: Cannot perform read: primary replica for shard ["", "S2\x84\x912") not available in:
```

I’ve thought it’s a race condition, where we’re doing a write and a non-outdated read at the same time, but I’m unsure if this is a likely scenario. 

I feel that bad network conditions are unlikely, due to the frequency which we see these errors, and it’s all inter-network communication.

web console looks fine, as does the `r.db('rethinkdb').table('server_status')` query.

Any assistance debugging this issue would be greatly appreciated!

**Comment by csaintc** [comment] 2016-06-28 19:32
Additional info: proxy nodes are running 2.3.0

**Comment by mlucy** [comment] 2016-06-30 06:49
Hi csaintc,

You should only see those particular errors if the proxy node can't talk to one or more of your RethinkDB nodes.  I'm not sure what would cause that in your case.

Is there any pattern to when the errors occur?  Do they usually last for a while, or is it that a single request fails and then the next request is fine?

**Comment by csaintc** [comment] 2016-06-30 18:28
I've noticed that if I'm only running ONE proxy node, it works fine.

**Comment by danielmewes** [comment] 2016-07-05 22:26
@csaintc Can you share the log files from the RethinkDB servers with us? You can send them via email as well if you prefer: daniel@rethinkdb.com

**Comment by analytik** [comment] 2016-07-08 09:13
We're having the same issue, I think.

We have 5 servers and 8 proxies. The servers have numbered names, rethinkdb1-5 (so - one replication controller with one pod and one service allocated to one machine), but proxies have one name - `rethinkdb`. 

Should we use canonical name for the proxy? In current setup we do. I wonder if proxies or databases just get confused sometimes, since by default, Kubernetes proxy creates one IP address for this domain name, rethinkdb, and then round-robins the connections between those 8 rethinkdb proxies.

When this problem occurs, the admin UI shows the "some servers are not available" message, even if all servers seem to be connected to each other, but only proxies have connectivity issues.

Today, we fixed this problem by restarting one of the servers. The last time, this got fixed by restarting one proxy which couldn't connect to one server.

We start servers by `--join`ing the 4 other servers. We're starting proxies by `--join`ing all 5 servers.

We also don't use `SessionAffinity` for the proxies right now. This means if anyone uses the domain name for proxy, it returns a round-robin'd IP address for any of the proxies. I guess this could cause an issue if any of the servers would ever want to access one specific proxy by its canonical address?

**Comment by danielmewes** [comment] 2016-07-13 00:06
@analytik With the round-robin IP that Kubernetes creates, I would highly recommend specifying a `canonical-address` explicitly for each proxy. The canonical address must be unique for the particular proxy server, and the other RethinkDB servers should be able to connect to it to reach the proxy.

RethinkDB relies on being able to reach the same server (including proxies) consistently under their respective canonical addresses.

(the same holds for the non-proxy servers, in case they have a round-robin IP as well).

**Comment by analytik** [comment] 2016-08-30 08:12
Oh, I forgot to reply here. For us, this issue got resolved when we forced rethinkdb proxies to use unique `canonical-address` (using a Kubernetes PetSet). Thanks for the clarification Daniel!

In case it helps anyone, we created a custom startup script, put these things in the PetSet definition yaml:
```
kind: PetSet
...
spec:
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
...
    spec:
      containers:
        command:
        - /run_proxy.sh
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
...
```

And the startup script is something like this:
```
#!/usr/bin/env bash
echo "$(date) Starting RethinkDB proxy $MY_POD_NAME on $MY_POD_IP ($(hostname))"

echo "$MY_POD_IP $(hostname).rethinkdbproxy" >> /etc/hosts
/usr/bin/rethinkdb proxy \
  --bind all \
  --join rethinkdb1 \
  --canonical-address $(hostname).rethinkdbproxy \
  --cluster-reconnect-timeout 300
```

Modifying `/etc/hosts` is done because once in a blue moon, DNS for its own hostname doesn't get resolved. And `--join rethinkdb1` is done only because this way we can use the same script also for dev env with only 1 db node, but of course in production you'd probably want to join all db nodes there.

This creates host pods like `rethinkdbproxy-0`, resolved with `rethinkdbproxy-0.rethinkdbproxy`. If you still need a round robin to connect to any available proxy, you cannot use `rethinkdbproxy` directly, but that's easily solved by creating another kubernetes service with `selector: name: rethinkdbproxy`. (And you don't create any RC/RS for that service.)

**Comment by csaintc** [comment] 2016-11-10 15:04
I've removed all proxy nodes from my cluster, and I continue to see this issue. Please advise.

**Comment by mick-h** [comment] 2016-12-27 11:24
We're seeing this on our production cluster.  Three data nodes, one proxy node.  The proxy node sees log entries like this:
```
2016-12-26T06:05:57.015845021 2266927.169780s error: Heartbeat timeout, killing connection to peer 10.22.7.53:29015
2016-12-26T06:05:57.025228873 2266927.179163s notice: Disconnected from server "rethinkdb_prod_01" aa54e3a2-055f-4465-9055-f1e491e03c4c
2016-12-26T06:08:10.540055358 2267060.693989s notice: Connected to server "rethinkdb_prod_01" aa54e3a2-055f-4465-9055-f1e491e03c4c
```

The 2+ minutes it takes to re-establish connectivity are causing quite a few `Cannot perform read: primary replica for shard [\"\", \"S50db406c\\x2Ddd82\\x2D4da0\\x2D9c03\\x2Db394a55222d4\") not
 available"]` errors.  Setting `read_mode` to `outdated` helps, but we still see timeouts for simple index lookups when this happens.

All nodes running 2.3.5 on Ubuntu 14.04.2.

**Comment by thomasmodeneis** [comment] 2017-01-04 12:16
Hi,

I definitely gave up on using RethinkDB on VPS due to issues like this.
It happens all the time and there is not much you can do, except avoid at all costs to host databases on VPS.
After I changed it all to dedicated machines with xeon +16GB the issue is gone and my cluster is always healthy.
I would recommend using something at least 3x (i5-2300 4c / 4t - 16 GB) on main servers and setup a consul for your cluster should help keeping ip-addrs and healthchecks in one place, like this demo: http://demo.consul.io/ui/#/nyc3/services/redis

Cheers.

**Comment by jeffzimmerlin** [comment] 2017-03-02 03:36
We have three RethinkDB servers running on virtual machines in three different data centers, and we're experiencing the same issue.  All servers are running `rethinkdb 2.3.5~0xenial (GCC 5.3.1)`.  We're not using RethinkDB proxies.

We get these errors quite often.  It'll usually resolve itself after sometime (_usually_), but interestingly enough, if we reboot the entire cluster, the problem goes away immediately.

That, plus the frequency with which this issue pops up makes me think it's not a network connectivity issue, but rather a bug in RethinkDB.

**Relevant app errors**
`
==> /var/log/rc/error.log <==
Wed, 01 Mar 2017 18:30:01 -0800 - PHP rExceptionsRqlServerError: "Runtime error: Cannot perform read: primary replica for shard ["", +inf) not available" (0) in /srv/rc/git/rc/lib/rethinkdb-php/Connection.php on line 389 (e3910d6c3e68e5313bcf1e7707368293)
Wed, 01 Mar 2017 18:30:01 -0800 - PHP rExceptionsRqlServerError: "Runtime error: Cannot perform read: primary replica for shard ["", +inf) not available" (0) in /srv/rc/git/rc/lib/rethinkdb-php/Connection.php on line 389 (c3399140816af04df8c330208975d299)
`

**Log files for each server attached.**
[log_files.zip](https://github.com/rethinkdb/rethinkdb/files/812710/log_files.zip)

**rc-lin-dfw-aux1 server status**
`
[
    {
        "id": "0ef40d37-51ed-4252-a986-35076cd7fd28",
        "name": "rc_lin_dfw_aux1",
        "network": {
            "canonical_addresses": [
                {
                    "host": "127.0.0.1",
                    "port": 29015
                },
                {
                    "host": "192.168.186.187",
                    "port": 29015
                },
                {
                    "host": "2600:3c00::f03c:91ff:fef1:ef16",
                    "port": 29015
                },
                {
                    "host": "72.14.183.146",
                    "port": 29015
                },
                {
                    "host": "::1",
                    "port": 29015
                },
                {
                    "host": "fe80::f03c:91ff:fef1:ef16%3",
                    "port": 29015
                }
            ],
            "cluster_port": 29015,
            "connected_to": {
                "298cfada-35d6-4449-9a7c-f0ba8fa64055": false,
                "rc_lin_ewr_aux1": true
            },
            "hostname": "rc-lin-dfw-aux1",
            "http_admin_port": 8080,
            "reql_port": 28015,
            "time_connected": {
                "date": "2017-02-26 10:00:47.984000",
                "timezone_type": 1,
                "timezone": "+00:00"
            }
        },
        "process": {
            "argv": [
                "\/usr\/bin\/rethinkdb",
                "--daemon",
                "--config-file",
                "\/etc\/rethinkdb\/instances.d\/rc.conf",
                "--runuser",
                "rethinkdb",
                "--rungroup",
                "rethinkdb",
                "--pid-file",
                "\/var\/run\/rethinkdb\/rc\/pid_file",
                "--directory",
                "\/var\/lib\/rethinkdb\/rc\/data"
            ],
            "cache_size_mb": 1379.310546875,
            "pid": 3770,
            "time_started": {
                "date": "2017-02-26 10:00:47.977000",
                "timezone_type": 1,
                "timezone": "+00:00"
            },
            "version": "rethinkdb 2.3.5~0xenial (GCC 5.3.1)"
        }
    },
    {
        "id": "dd60d638-463d-4d85-bbe0-70320997ae9c",
        "name": "rc_lin_ewr_aux1",
        "network": {
            "canonical_addresses": [
                {
                    "host": "127.0.0.1",
                    "port": 29015
                },
                {
                    "host": "192.168.216.30",
                    "port": 29015
                },
                {
                    "host": "2600:3c03::f03c:91ff:fe16:91ce",
                    "port": 29015
                },
                {
                    "host": "45.56.97.146",
                    "port": 29015
                },
                {
                    "host": "::1",
                    "port": 29015
                },
                {
                    "host": "fe80::f03c:91ff:fe16:91ce%3",
                    "port": 29015
                }
            ],
            "cluster_port": 29015,
            "connected_to": {
                "298cfada-35d6-4449-9a7c-f0ba8fa64055": true,
                "rc_lin_dfw_aux1": true
            },
            "hostname": "rc-lin-ewr-aux1",
            "http_admin_port": 8080,
            "reql_port": 28015,
            "time_connected": {
                "date": "2017-02-26 10:00:50.955000",
                "timezone_type": 1,
                "timezone": "+00:00"
            }
        },
        "process": {
            "argv": [
                "\/usr\/bin\/rethinkdb",
                "--daemon",
                "--config-file",
                "\/etc\/rethinkdb\/instances.d\/rc.conf",
                "--runuser",
                "rethinkdb",
                "--rungroup",
                "rethinkdb",
                "--pid-file",
                "\/var\/run\/rethinkdb\/rc\/pid_file",
                "--directory",
                "\/var\/lib\/rethinkdb\/rc\/data"
            ],
            "cache_size_mb": 1377.4140625,
            "pid": 3829,
            "time_started": {
                "date": "2017-02-26 10:00:50.694000",
                "timezone_type": 1,
                "timezone": "+00:00"
            },
            "version": "rethinkdb 2.3.5~0xenial (GCC 5.3.1)"
        }
    }
][
    {
        "id": "0ef40d37-51ed-4252-a986-35076cd7fd28",
        "name": "rc_lin_dfw_aux1",
        "network": {
            "canonical_addresses": [
                {
                    "host": "127.0.0.1",
                    "port": 29015
                },
                {
                    "host": "192.168.186.187",
                    "port": 29015
                },
                {
                    "host": "2600:3c00::f03c:91ff:fef1:ef16",
                    "port": 29015
                },
                {
                    "host": "72.14.183.146",
                    "port": 29015
                },
                {
                    "host": "::1",
                    "port": 29015
                },
                {
                    "host": "fe80::f03c:91ff:fef1:ef16%3",
                    "port": 29015
                }
            ],
            "cluster_port": 29015,
            "connected_to": {
                "298cfada-35d6-4449-9a7c-f0ba8fa64055": false,
                "rc_lin_ewr_aux1": true
            },
            "hostname": "rc-lin-dfw-aux1",
            "http_admin_port": 8080,
            "reql_port": 28015,
            "time_connected": {
                "date": "2017-02-26 10:00:47.984000",
                "timezone_type": 1,
                "timezone": "+00:00"
            }
        },
        "process": {
            "argv": [
                "\/usr\/bin\/rethinkdb",
                "--daemon",
                "--config-file",
                "\/etc\/rethinkdb\/instances.d\/rc.conf",
                "--runuser",
                "rethinkdb",
                "--rungroup",
                "rethinkdb",
                "--pid-file",
                "\/var\/run\/rethinkdb\/rc\/pid_file",
                "--directory",
                "\/var\/lib\/rethinkdb\/rc\/data"
            ],
            "cache_size_mb": 1379.310546875,
            "pid": 3770,
            "time_started": {
                "date": "2017-02-26 10:00:47.977000",
                "timezone_type": 1,
                "timezone": "+00:00"
            },
            "version": "rethinkdb 2.3.5~0xenial (GCC 5.3.1)"
        }
    },
    {
        "id": "dd60d638-463d-4d85-bbe0-70320997ae9c",
        "name": "rc_lin_ewr_aux1",
        "network": {
            "canonical_addresses": [
                {
                    "host": "127.0.0.1",
                    "port": 29015
                },
                {
                    "host": "192.168.216.30",
                    "port": 29015
                },
                {
                    "host": "2600:3c03::f03c:91ff:fe16:91ce",
                    "port": 29015
                },
                {
                    "host": "45.56.97.146",
                    "port": 29015
                },
                {
                    "host": "::1",
                    "port": 29015
                },
                {
                    "host": "fe80::f03c:91ff:fe16:91ce%3",
                    "port": 29015
                }
            ],
            "cluster_port": 29015,
            "connected_to": {
                "298cfada-35d6-4449-9a7c-f0ba8fa64055": true,
                "rc_lin_dfw_aux1": true
            },
            "hostname": "rc-lin-ewr-aux1",
            "http_admin_port": 8080,
            "reql_port": 28015,
            "time_connected": {
                "date": "2017-02-26 10:00:50.955000",
                "timezone_type": 1,
                "timezone": "+00:00"
            }
        },
        "process": {
            "argv": [
                "\/usr\/bin\/rethinkdb",
                "--daemon",
                "--config-file",
                "\/etc\/rethinkdb\/instances.d\/rc.conf",
                "--runuser",
                "rethinkdb",
                "--rungroup",
                "rethinkdb",
                "--pid-file",
                "\/var\/run\/rethinkdb\/rc\/pid_file",
                "--directory",
                "\/var\/lib\/rethinkdb\/rc\/data"
            ],
            "cache_size_mb": 1377.4140625,
            "pid": 3829,
            "time_started": {
                "date": "2017-02-26 10:00:50.694000",
                "timezone_type": 1,
                "timezone": "+00:00"
            },
            "version": "rethinkdb 2.3.5~0xenial (GCC 5.3.1)"
        }
    }
]
`

**rc-lin-atl-aux1 server status**

`
[
    {
        "id": "dd60d638-463d-4d85-bbe0-70320997ae9c",
        "name": "rc_lin_ewr_aux1",
        "network": {
            "canonical_addresses": [
                {
                    "host": "127.0.0.1",
                    "port": 29015
                },
                {
                    "host": "192.168.216.30",
                    "port": 29015
                },
                {
                    "host": "2600:3c03::f03c:91ff:fe16:91ce",
                    "port": 29015
                },
                {
                    "host": "45.56.97.146",
                    "port": 29015
                },
                {
                    "host": "::1",
                    "port": 29015
                },
                {
                    "host": "fe80::f03c:91ff:fe16:91ce%3",
                    "port": 29015
                }
            ],
            "cluster_port": 29015,
            "connected_to": {
                "0ef40d37-51ed-4252-a986-35076cd7fd28": true,
                "rc_lin_atl_aux1": true
            },
            "hostname": "rc-lin-ewr-aux1",
            "http_admin_port": 8080,
            "reql_port": 28015,
            "time_connected": {
                "date": "2017-02-27 04:35:47.377000",
                "timezone_type": 1,
                "timezone": "+00:00"
            }
        },
        "process": {
            "argv": [
                "\/usr\/bin\/rethinkdb",
                "--daemon",
                "--config-file",
                "\/etc\/rethinkdb\/instances.d\/rc.conf",
                "--runuser",
                "rethinkdb",
                "--rungroup",
                "rethinkdb",
                "--pid-file",
                "\/var\/run\/rethinkdb\/rc\/pid_file",
                "--directory",
                "\/var\/lib\/rethinkdb\/rc\/data"
            ],
            "cache_size_mb": 1377.4140625,
            "pid": 3829,
            "time_started": {
                "date": "2017-02-26 10:00:50.694000",
                "timezone_type": 1,
                "timezone": "+00:00"
            },
            "version": "rethinkdb 2.3.5~0xenial (GCC 5.3.1)"
        }
    },
    {
        "id": "298cfada-35d6-4449-9a7c-f0ba8fa64055",
        "name": "rc_lin_atl_aux1",
        "network": {
            "canonical_addresses": [
                {
                    "host": "127.0.0.1",
                    "port": 29015
                },
                {
                    "host": "192.168.141.166",
                    "port": 29015
                },
                {
                    "host": "2600:3c02::f03c:91ff:fef1:eff6",
                    "port": 29015
                },
                {
                    "host": "45.79.199.53",
                    "port": 29015
                },
                {
                    "host": "::1",
                    "port": 29015
                },
                {
                    "host": "fe80::f03c:91ff:fef1:eff6%3",
                    "port": 29015
                }
            ],
            "cluster_port": 29015,
            "connected_to": {
                "0ef40d37-51ed-4252-a986-35076cd7fd28": false,
                "rc_lin_ewr_aux1": true
            },
            "hostname": "rc-lin-atl-aux1",
            "http_admin_port": 8080,
            "reql_port": 28015,
            "time_connected": {
                "date": "2017-02-26 10:01:22.264000",
                "timezone_type": 1,
                "timezone": "+00:00"
            }
        },
        "process": {
            "argv": [
                "\/usr\/bin\/rethinkdb",
                "--daemon",
                "--config-file",
                "\/etc\/rethinkdb\/instances.d\/rc.conf",
                "--runuser",
                "rethinkdb",
                "--rungroup",
                "rethinkdb",
                "--pid-file",
                "\/var\/run\/rethinkdb\/rc\/pid_file",
                "--directory",
                "\/var\/lib\/rethinkdb\/rc\/data"
            ],
            "cache_size_mb": 1378.896484375,
            "pid": 3788,
            "time_started": {
                "date": "2017-02-26 10:01:22.263000",
                "timezone_type": 1,
                "timezone": "+00:00"
            },
            "version": "rethinkdb 2.3.5~0xenial (GCC 5.3.1)"
        }
    }
]
`

**rc-lin-ewr-aux1 server status**
`
[
    {
        "id": "0ef40d37-51ed-4252-a986-35076cd7fd28",
        "name": "rc_lin_dfw_aux1",
        "network": {
            "canonical_addresses": [
                {
                    "host": "127.0.0.1",
                    "port": 29015
                },
                {
                    "host": "192.168.186.187",
                    "port": 29015
                },
                {
                    "host": "2600:3c00::f03c:91ff:fef1:ef16",
                    "port": 29015
                },
                {
                    "host": "72.14.183.146",
                    "port": 29015
                },
                {
                    "host": "::1",
                    "port": 29015
                },
                {
                    "host": "fe80::f03c:91ff:fef1:ef16%3",
                    "port": 29015
                }
            ],
            "cluster_port": 29015,
            "connected_to": {
                "rc_lin_atl_aux1": false,
                "rc_lin_ewr_aux1": true
            },
            "hostname": "rc-lin-dfw-aux1",
            "http_admin_port": 8080,
            "reql_port": 28015,
            "time_connected": {
                "date": "2017-02-26 10:00:50.675000",
                "timezone_type": 1,
                "timezone": "+00:00"
            }
        },
        "process": {
            "argv": [
                "\/usr\/bin\/rethinkdb",
                "--daemon",
                "--config-file",
                "\/etc\/rethinkdb\/instances.d\/rc.conf",
                "--runuser",
                "rethinkdb",
                "--rungroup",
                "rethinkdb",
                "--pid-file",
                "\/var\/run\/rethinkdb\/rc\/pid_file",
                "--directory",
                "\/var\/lib\/rethinkdb\/rc\/data"
            ],
            "cache_size_mb": 1379.310546875,
            "pid": 3770,
            "time_started": {
                "date": "2017-02-26 10:00:47.977000",
                "timezone_type": 1,
                "timezone": "+00:00"
            },
            "version": "rethinkdb 2.3.5~0xenial (GCC 5.3.1)"
        }
    },
    {
        "id": "dd60d638-463d-4d85-bbe0-70320997ae9c",
        "name": "rc_lin_ewr_aux1",
        "network": {
            "canonical_addresses": [
                {
                    "host": "127.0.0.1",
                    "port": 29015
                },
                {
                    "host": "192.168.216.30",
                    "port": 29015
                },
                {
                    "host": "2600:3c03::f03c:91ff:fe16:91ce",
                    "port": 29015
                },
                {
                    "host": "45.56.97.146",
                    "port": 29015
                },
                {
                    "host": "::1",
                    "port": 29015
                },
                {
                    "host": "fe80::f03c:91ff:fe16:91ce%3",
                    "port": 29015
                }
            ],
            "cluster_port": 29015,
            "connected_to": {
                "rc_lin_atl_aux1": true,
                "rc_lin_dfw_aux1": true
            },
            "hostname": "rc-lin-ewr-aux1",
            "http_admin_port": 8080,
            "reql_port": 28015,
            "time_connected": {
                "date": "2017-02-26 10:00:50.728000",
                "timezone_type": 1,
                "timezone": "+00:00"
            }
        },
        "process": {
            "argv": [
                "\/usr\/bin\/rethinkdb",
                "--daemon",
                "--config-file",
                "\/etc\/rethinkdb\/instances.d\/rc.conf",
                "--runuser",
                "rethinkdb",
                "--rungroup",
                "rethinkdb",
                "--pid-file",
                "\/var\/run\/rethinkdb\/rc\/pid_file",
                "--directory",
                "\/var\/lib\/rethinkdb\/rc\/data"
            ],
            "cache_size_mb": 1377.4140625,
            "pid": 3829,
            "time_started": {
                "date": "2017-02-26 10:00:50.694000",
                "timezone_type": 1,
                "timezone": "+00:00"
            },
            "version": "rethinkdb 2.3.5~0xenial (GCC 5.3.1)"
        }
    },
    {
        "id": "298cfada-35d6-4449-9a7c-f0ba8fa64055",
        "name": "rc_lin_atl_aux1",
        "network": {
            "canonical_addresses": [
                {
                    "host": "127.0.0.1",
                    "port": 29015
                },
                {
                    "host": "192.168.141.166",
                    "port": 29015
                },
                {
                    "host": "2600:3c02::f03c:91ff:fef1:eff6",
                    "port": 29015
                },
                {
                    "host": "45.79.199.53",
                    "port": 29015
                },
                {
                    "host": "::1",
                    "port": 29015
                },
                {
                    "host": "fe80::f03c:91ff:fef1:eff6%3",
                    "port": 29015
                }
            ],
            "cluster_port": 29015,
            "connected_to": {
                "rc_lin_dfw_aux1": false,
                "rc_lin_ewr_aux1": true
            },
            "hostname": "rc-lin-atl-aux1",
            "http_admin_port": 8080,
            "reql_port": 28015,
            "time_connected": {
                "date": "2017-02-27 04:35:45.892000",
                "timezone_type": 1,
                "timezone": "+00:00"
            }
        },
        "process": {
            "argv": [
                "\/usr\/bin\/rethinkdb",
                "--daemon",
                "--config-file",
                "\/etc\/rethinkdb\/instances.d\/rc.conf",
                "--runuser",
                "rethinkdb",
                "--rungroup",
                "rethinkdb",
                "--pid-file",
                "\/var\/run\/rethinkdb\/rc\/pid_file",
                "--directory",
                "\/var\/lib\/rethinkdb\/rc\/data"
            ],
            "cache_size_mb": 1378.896484375,
            "pid": 3788,
            "time_started": {
                "date": "2017-02-26 10:01:22.263000",
                "timezone_type": 1,
                "timezone": "+00:00"
            },
            "version": "rethinkdb 2.3.5~0xenial (GCC 5.3.1)"
        }
    }
]
`

**Comment by AtnNn** [comment] 2017-03-12 06:20
@analytik Examining your logs, I notice that:

The `ewr` server doesn't seem to have connection issues. The issue seems to be between `atl` and `dfw`. 

Your `atl` server is the one that seems to time out, and the `dfw` server is the one that notices it (saying `Heartbeat timeout, killing connection`). When this happens, the `atl` server doesn't detect it immediately and seems to delay the reconnection effort.

```
info: Rejected a connection from server 0ef40d37-51ed-4252-a986-35076cd7fd28 since one is open already.
notice: Disconnected from server "rc_lin_dfw_aux1" 0ef40d37-51ed-4252-a986-35076cd7fd28
notice: Connected to server "rc_lin_dfw_aux1" 0ef40d37-51ed-4252-a986-35076cd7fd28
```

Are there any cpu, memory, I/O or network latency spikes on your `atl` server when the errors happen? How about on `dfw`?
Is it possible one of those servers is on a crowded VPS or a crowded network?

I also see a lot of `Raft election timed out` messages, but I think they might be unrelated (#4482, #5616)

This issue seems possibly related to #1654, #2841, #5456, #5587 and #5720

**Comment by jeffzimmerlin** [comment] 2017-03-13 00:46
> Are there any cpu, memory, I/O or network latency spikes on your atl server when the errors happen? How about on dfw?

I'll check next time it happens...

> Is it possible one of those servers is on a crowded VPS or a crowded network?

It's possible.  All of the servers in the cluster are hosted on Linode VMs (4GB RAM, 2 CPUs, SSD drives).

I might try upgrading to larger instances or finding dedicated servers and seeing if the problem goes away.

**Comment by analytik** [comment] 2017-04-26 11:02
Thanks for the reply, AtnNn - while your reply was aimed at jeffzimmerlin, and we don't have this issue anymore since we switched to static IPs in kubernetes, I'll still add comments if they help anyone:

It's very likely that crowded network exacerbated the issue. We pay for a 1Gbit network, however our current bare metal server provider is notorious for hosting torrent boxes, and their routers have mysterious issues every couple of months, so I would easily lay blame on unreliable network. (Sometimes both bandwidth and latencies to internet are better than within their datacenter.)

On many occasions, CPU usage was high, but not saturated at any point. There was likely 100MB/s+ intra-cluster traffic, up to cca 30MB/s per server; with about 20-30MB/s cluster traffic in "idle". Sadly I don't have access to monitoring graphs that far back, but it was not unusual to have saturated disk IO on their "enterprise-grade SSDs", usually through a combination of triple subselect-map-reduce query and another read query with poorly chosen indexes on a 300GB table.

**Closed** 2018-03-23 15:55 UTC
Labels: cp:clustering
