### ISSUE TITLE
Does Rethinkdb support thousands of tables?

### ISSUE THREAD

**Issue by gebrits** [rethinkdb/rethinkdb#4389] opened 2015-06-12 09:47 UTC
Does RethinkDb support creating/managing thousands of tables?

Usecase: Tenant managed tables, without preknown schema.

**Comment by joaojeronimo** [comment] 2015-06-12 12:38
Probably, except if you plan to use the administrative UI:  https://github.com/rethinkdb/rethinkdb/issues/2012

**Comment by danielmewes** [comment] 2015-06-12 18:31
@gebrits I think this is possible, but not super well supported at the moment.

There's a memory overhead of about 8-12 MB per table, regardless of its size.

In RethinkDB 2.0, you will also see a slowdown of meta operations (such as table creation, reconfiguration, restarting a server etc.) as you get to a lot of tables. That part is going to improve somewhat with the upcoming release (2.1), but the memory overhead remains for the time being.

If you keep the overhead in mind, you'll probably be fine with a few thousand tables in RethinkDB 2.1, especially if they are not (heavily) sharded. Note though that we haven't heavily tested this scenario, so there might be some other issues we're not aware of.

You might want to follow https://github.com/rethinkdb/rethinkdb/issues/1861 , which is basically about this scenario. Closing this as a duplicate of #1861, but feel free to ask further specific questions here.

**Closed by danielmewes** 2015-06-12 18:31 UTC
