### ISSUE TITLE
Raft Cluster client: Allow client connect to multiple host and retry if possible

### ISSUE THREAD

**Issue by QianJin2013** [rethinkdb/rethinkdb#5880] opened 2016-06-23 00:01 UTC
I known RethinkDB server is using Raft protocol for clustering, but it seems 
the client driver (at least Java Client Driver) is not ready for Raft failover scenario, e.x:

(1).when primary node crashes, the client does not connect to other node randomly to retry.
(2). when primary node returns error about replica node, the client does not retry.

So, i suggest add following functionality to client driver:

(1). Allow connect to multiple host.

```
connect( host1:port1, host2:port2, host3:port3 )
``` 

(2). Allow retry when network error or node error.

**Comment by chrisvariety** [comment] 2016-06-23 00:27
I believe a 3rd party driver called Rethinkdbdash has the functionality you are looking for: https://github.com/neumino/rethinkdbdash (maybe not the retries, but definitely connecting to multiple servers)

**Comment by QianJin2013** [comment] 2016-06-23 00:37
@chrisvariety thank you. Follow your hint, i realize retry is not a good idea, it is really a pity.
https://github.com/neumino/rethinkdbdash/issues/142#issuecomment-133654639
```
Yeah, I guess you're right and there's no way to implement this safely at the level of database driver.
I initially thought about a single document inserts/updates, but only adding autoretry to certain operations will only make matters more confusing.
```

About "connect to multiple host", there are also other consideration, such as use network load balancer integrated hub to provide a single ip to client yet can choose active host.

If no any other idea about this topic, i will close this issue in several days.

**Comment by bchavez** [comment] 2016-06-23 00:37
FWIW. C# Driver (ported from Java)

##### Code
https://github.com/bchavez/RethinkDb.Driver/tree/master/Source/RethinkDb.Driver/Net/Clustering

##### Documentation
https://github.com/bchavez/RethinkDb.Driver/wiki/Connections-&-Pooling

##### Technical Design Notes
https://github.com/bchavez/RethinkDb.Driver/issues/17

##### Java Related
https://github.com/rethinkdb/rethinkdb/pull/5649 

*and* ... no :ocean: :boat: raft protocol implementation required.

:boom: :fire: [***"Set it ablaze like a candle wick... Light it up, light it up..."***](https://www.youtube.com/watch?v=qDcFryDXQ7U)

**Comment by QianJin2013** [comment] 2016-06-23 00:38
@bchavez thank you

**Comment by bchavez** [comment] 2016-06-23 00:50
Also, just a quick recommendation, if you plan to do this based of the C# design, I'd recommend just implementing the **Round Robin** pooling strategy first. Not sure how useful **Epsilon Greedy** pooling strategy is quite yet. I haven't heard any feedback on it. IIRC, **Epsilon Greedy** complicated things much more than it should have.

:ocean: :boat: [***"Set sail!..."***](https://www.youtube.com/watch?v=_MqA0a5iw5k)

**Comment by neumino** [comment] 2016-06-23 04:59
rethinkdbdash can connect to multiple instances of RethinkDB and round robin the query, but honestly, if you start to consider failover, load balancing etc, this should be done by a real load balancer.

If you use Kubernetes, juste create a service for your RethinkDB connections, and have rethinkdbdash create a pool for this service. Then as long as your cluster is partially up (as long as you have the majority avaialble), rethinkdbdash will run your query.

**Comment by QianJin2013** [comment] 2016-06-23 05:05
@neumino thanks for your experience share. Now i agree a real load balancer is better.

**Comment by danielmewes** [comment] 2016-06-24 18:13
I'm going to close this as a duplicate of https://github.com/rethinkdb/rethinkdb/issues/281

**Closed by danielmewes** 2016-06-24 18:13 UTC
