### ISSUE TITLE
JSON parse error: Missing a name for object member.

### ISSUE THREAD

**Issue by OktavioS** [rethinkdb/rethinkdb#7104] opened 2023-01-08 12:33 UTC
I downloaded some unity project from github, and ther is one problem appeared while it was opening.
It's image of issue in unity:
![image](https://user-images.githubusercontent.com/87369834/211196232-256e2944-0c05-4c74-8091-f4a174499f05.png)

It's image of JSON file:
![image](https://user-images.githubusercontent.com/87369834/211196199-c49096be-6991-46eb-9d15-4423de638539.png)

**Comment by lsabi** [comment] 2023-01-08 13:46
The code in the second image is not valid `JSON`. If you did not change the file, then the problem is likely to be in the unity project. It may be that it requires pre processing before inputting it to the database (just guessing, since I have no clue which project you're referring to)

**Comment by OktavioS** [comment] 2023-01-08 14:12
> The code in the second image is not valid `JSON`. If you did not change the file, then the problem is likely to be in the unity project. It may be that it requires pre processing before inputting it to the database (just guessing, since I have no clue which project you're referring to)

The project I downloaded
link: https://github.com/TheJustLink/2048-3d

**Comment by lsabi** [comment] 2023-01-08 14:49
The file that is causing the trouble is [https://github.com/TheJustLink/2048-3d/blob/main/Assets/Plugins/Hierarchy%202/Runtime/Hierarchy2Runtime.asmdef](https://github.com/TheJustLink/2048-3d/blob/main/Assets/Plugins/Hierarchy%202/Runtime/Hierarchy2Runtime.asmdef) which seems fine. Did you modify the program or run something before using it?

I would try overwriting the local file with the one I linked, though it may not be a final solution.

Nevertheless, this is not a problem related to the database itself (or so it looks like), therefore I'm going to close the issue.

**Closed by lsabi** 2023-01-08 14:49 UTC

**Comment by OktavioS** [comment] 2023-01-09 09:59
So I added some string to that file, because there were some problems, i googled them and i found a solution to add this string:
public VisualElement(), after i added this all problems gone but one appeared, appeared that problem that i asked you to help with.

**Comment by OktavioS** [comment] 2023-01-09 11:01
Okey, I deleted that string, and the problem disappeare, sorry)
