### ISSUE TITLE
binary installs ?

### ISSUE THREAD

**Issue by joeblew99** [rethinkdb/rethinkdb#5588] opened 2016-04-01 15:25 UTC
At the moment all the releases are package with other stuff.
It woudl be great if you can also just release the binary. 
The reason i am asking for this is because the binary for OSX, linux, windows is all i need for packaging into the main applications i build.

rethinkdb is great because it can run with just the binary and not even a config !!
So make it easy, since it is that easy to run it :)

**Comment by Wargog** [comment] 2016-04-01 16:17
You can download the [Windows binary](https://download.rethinkdb.com/windows/rethinkdb-dev-preview-0.zip) at any time, Linux and OSX is a bit more tricky as there are dependencies that must be installed on the users system as well since those OSes don't support native binaries like Windows does. But that is just my 2 cents, I will leave it to the Rethink guys to give a final answer.

**Comment by eatnut** [comment] 2016-04-01 16:37
+1

**Comment by larkost** [comment] 2016-04-01 19:01
We actually have no dependencies at all in the MacOS package, and our installer only installs the single file at `/usr/local/bin/rethinkdb` (#4507 would change that). We make sure that everything needed is either in the system install, or statically linked.

For users on MacOS X I would rather not add an additional official route for the following reasons:
1. Using a `.pkg` installer means that upgrades are nicely handled for us. We can add or remove files and not worry about it. If you take a peek into our uninstall tool for MacOS you will see that we take advantage of this same mechanism to make our uninstaller "just work".
2. For anything I would see someone wanting to package for deployment on MacOS X they should probably be using `.pkg` to deploy their code. Tools like [Packages](http://s.sudre.free.fr/Software/Packages/about.html) make adding our `.pkg` into yours easier. Of course that assumes you don't want to pull the RethinkDB binary into your own bundle (there are cases where this would be better).
3. For the few users who could benefit from this it is not too difficult to pull `.pkg` files apart (do this in a temporary folder):
  - `xar -xzf PATH_TO_PKG`
  - `tar xzvf rethinkdb_server.pkg/Payload`
  - `ls -l rethinkdb`

I should note that regardless of how you redistributed the RethinkDB server, you would of course need to include our `COPYRIGHT` file to keep everything on the level.

**Comment by larkost** [comment] 2016-04-01 19:03
For the linux side of things, that might be handled at some point with #5392, but there probably needs to be more in-depth discussion there.

**Comment by danielmewes** [comment] 2016-04-01 23:19
I'm going to close this as a duplicate of https://github.com/rethinkdb/rethinkdb/issues/5392 , since the Mac side is mostly covered by what @larkost explained.

On Linux, you can build a statically compiled package yourself by compiling like this:
```
./configure --fetch all --static call
make STRIP_SYMBOLS=1 -j 8
```
You'll find the resulting binary in build/release/rethinkdb afterwards.

**Closed by danielmewes** 2016-04-01 23:19 UTC

**Comment by joeblew99** [comment] 2016-04-02 12:29
This does not seem to be based on my experiences.

@joshua
On OSX and windows it's a single binary. At the moment I have to install
the complete package and copt out the single binary and then delete the
package.

Building from source is a huge inconvenience.

I get its not a priority, but still registering my objections :)

**Comment by larkost** [comment] 2016-04-04 20:32
@joeblew99: Can you elaborate? Your last comment does not have much to go on.

**Comment by joeblew99** [comment] 2016-04-04 22:41
Sorry I guess I am too in my head...
Basically when for example I go to download OSX, I can only download a PKG,
which is not great when all you want is the rethinkdb binary executable
only.

The exe is all I need for OSX ( and also windows and Linux ), in order to
run my code ( golang in my case ) to talk to rethinkdb.

I place the rethinkdb exe inside the main deployed tar or zip that gets
deployed to my devices and servers.

Does this explain why all the packaging does not help me, but actually
slows me down each time you do a release ?

**Comment by larkost** [comment] 2016-04-05 17:08
@joeblew99: specifically on MacOS X, `.pkg` is a far better tool than wrapping things up as a `.zip` or '.tar.*', for the reasons I have highlighted above. That is why it is the preferred format for almost [1] all of the MacOS deployment solutions I know of: AutoDMG, Caspar, DeployStudio, Imagr, Munki, NetRestore, and Puppet. Even FileWave has a digester. Having done a lot of work in this area, I would strongly advise that if you are rolling your own without using `.pkg` you are doing extra work with lesser results. Even if you have never done it before, the Packages tool I mentioned above makes it really easy to create `.pkg`s.

And I have already listed the two steps you need to do to unwrap the binary out of the `.pkg` for those rare cases where it is a better idea not to use `.pkg`. So this is not much of a speed bump, especially if you have this automated.

[1] The lone exception that comes to mind is Radmind, but that is a horse of another color.

**Comment by joeblew99** [comment] 2016-04-06 16:01
Thanks. I have been doing that already.

Does not help with the real issue though.
