### ISSUE TITLE
2.1.3 server very slow, high load and high iowait

### ISSUE THREAD

**Issue by hwestbrook** [rethinkdb/rethinkdb#4835] opened 2015-09-13 22:49 UTC
After updating to 2.1.3, my server has become extremely slow. Investingating possible causes has focused me on the high load and high iowait stats. I'm running rethinkdb on a t3.micro. 

Stats

iostat:

```
ubuntu@ip-172-31-18-121:~$ iostat -x 5 5
Linux 3.13.0-48-generic (ip-172-31-18-121)  09/13/2015  _x86_64_    (1 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           2.45    0.00    0.79   77.20   19.44    0.13

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
xvda              2.28     1.18   61.50    5.65  1173.37   266.14    42.87    29.50  439.36  441.02  421.23  11.99  80.49
xvdf              0.03     1.12    0.16    0.04     0.75     4.65    52.90     0.00    1.53    0.54    5.31   0.77   0.02

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           1.81    0.00    0.40   96.38    1.41    0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
xvda              0.00     5.63   87.93    6.24   915.09    57.95    20.67    18.11  181.07  184.51  132.52  10.53  99.15
xvdf              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
```

top: 

```
top - 22:40:19 up 30 min,  2 users,  load average: 64.20, 63.86, 54.29
%Cpu(s):  6.1 us,  1.0 sy,  0.0 ni,  0.0 id, 92.6 wa,  0.0 hi,  0.0 si,  0.3 st
%Cpu(s):  3.1 us,  0.3 sy,  0.0 ni,  0.0 id, 96.3 wa,  0.0 hi,  0.0 si,  0.3 st
MiB Mem:   992.473 total,  927.391 used,   65.082 free,    0.484 buffers
MiB Swap: 5119.996 total,   22.984 used, 5097.012 free.   30.223 cached Mem

    1 root      20   0   32.7m   1.0m   0.0m S  0.0  0.1   0:01.14 init
 1133 rethink+  20   0 1263.2m 827.4m   4.6m S  5.3 83.4   1:11.82 rethinkdb
    1 root      20   0   32.7m   1.0m   0.0m S  0.0  0.1   0:01.14 init
    2 root      20   0    0.0m   0.0m   0.0m S  0.0  0.0   0:00.00 kthreadd
    3 root      20   0    0.0m   0.0m   0.0m S  0.0  0.0   0:00.00 ksoftirqd/0
```

sar 1: 

```
ubuntu@ip-172-31-18-121:~$ sar 1
Linux 3.13.0-48-generic (ip-172-31-18-121)  09/13/2015  _x86_64_    (1 CPU)

10:41:10 PM     CPU     %user     %nice   %system   %iowait    %steal     %idle
10:41:11 PM     all      1.02      0.00      1.02     96.94      1.02      0.00
10:41:12 PM     all      2.06      0.00      1.03     96.91      0.00      0.00
10:41:13 PM     all      0.00      0.00      0.00    100.00      0.00      0.00
10:41:14 PM     all      0.00      0.00      0.00     98.99      1.01      0.00
10:41:15 PM     all      2.02      0.00      1.01     96.97      0.00      0.00
10:41:16 PM     all     14.85      0.00      1.98     83.17      0.00      0.00
10:41:17 PM     all      2.94      0.00      1.96     95.10      0.00      0.00
10:41:18 PM     all      6.06      0.00      1.01     92.93      0.00      0.00
10:41:19 PM     all      3.92      0.00      1.96     94.12      0.00      0.00
10:41:20 PM     all      1.04      0.00      0.00     97.92      1.04      0.00
10:41:21 PM     all      1.01      0.00      1.01     97.98      0.00      0.00
10:41:22 PM     all      4.00      0.00      1.00     95.00      0.00      0.00
```

sar -w 1:

```
ubuntu@ip-172-31-18-121:~$ sar -w 1
Linux 3.13.0-48-generic (ip-172-31-18-121)  09/13/2015  _x86_64_    (1 CPU)

10:41:12 PM    proc/s   cswch/s
10:41:13 PM      0.00   1792.78
10:41:14 PM      0.00    725.51
10:41:15 PM      0.00   1597.98
10:41:16 PM      0.00   1894.06
10:41:17 PM      0.00   2175.49
10:41:18 PM      0.00   1243.43
10:41:19 PM      0.00   1517.82
10:41:20 PM      0.00   1563.92
10:41:21 PM      0.00   1329.00
10:41:22 PM      0.00   1420.20
10:41:23 PM      0.00   1267.68
10:41:24 PM      0.00   1163.00
10:41:25 PM      0.00    987.13
10:41:26 PM      0.00   1247.47
10:41:27 PM      0.00   1288.66
```

iotop single process: 

```
Total DISK READ :     407.56 K/s | Total DISK WRITE :      59.35 K/s
Actual DISK READ:     407.56 K/s | Actual DISK WRITE:     265.11 K/s
  PID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
 1133 be/4 rethinkd  407.56 K/s   59.35 K/s  0.00 % 23.98 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
    1 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % init
    2 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [kthreadd]
    3 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [ksoftirqd/0]
    5 be/0 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [kworker/0:0H]
    6 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [kworker/u30:0]
```

iotop threads: 

```
Total DISK READ :    1024.98 K/s | Total DISK WRITE :     161.63 K/s
Actual DISK READ:    1024.98 K/s | Actual DISK WRITE:     701.72 K/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
 1157 be/4 rethinkd   39.42 K/s  102.50 K/s  0.00 % 76.82 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1158 be/4 rethinkd   23.65 K/s    0.00 B/s  0.00 % 52.24 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1153 be/4 rethinkd   59.13 K/s    3.94 K/s  0.00 % 51.23 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1142 be/4 rethinkd   19.71 K/s    0.00 B/s  0.00 % 46.86 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1188 be/4 rethinkd   15.77 K/s    0.00 B/s  0.00 % 46.83 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1201 be/4 rethinkd   15.77 K/s    3.94 K/s  0.00 % 46.80 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1172 be/4 rethinkd  402.11 K/s   11.83 K/s  0.00 % 45.95 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1166 be/4 rethinkd   11.83 K/s    0.00 B/s  0.00 % 43.95 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1204 be/4 rethinkd   86.73 K/s    0.00 B/s  0.00 % 43.37 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1165 be/4 rethinkd   11.83 K/s    0.00 B/s  0.00 % 42.99 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1151 be/4 rethinkd    7.88 K/s    0.00 B/s  0.00 % 42.02 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1141 be/4 rethinkd   11.83 K/s    0.00 B/s  0.00 % 41.02 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1160 be/4 rethinkd   11.83 K/s    3.94 K/s  0.00 % 40.04 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1170 be/4 rethinkd   11.83 K/s    0.00 B/s  0.00 % 39.06 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1182 be/4 rethinkd    7.88 K/s    3.94 K/s  0.00 % 38.07 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1176 be/4 rethinkd   31.54 K/s    0.00 B/s  0.00 % 37.04 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1196 be/4 rethinkd   15.77 K/s    0.00 B/s  0.00 % 36.92 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1147 be/4 rethinkd   15.77 K/s    0.00 B/s  0.00 % 36.07 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1168 be/4 rethinkd   27.60 K/s    0.00 B/s  0.00 % 32.54 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1164 be/4 rethinkd   51.25 K/s    3.94 K/s  0.00 % 29.55 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1189 be/4 rethinkd    7.88 K/s    3.94 K/s  0.00 % 23.65 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1185 be/4 rethinkd    7.88 K/s    0.00 B/s  0.00 % 22.64 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1154 be/4 rethinkd    3.94 K/s    0.00 B/s  0.00 % 21.66 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1163 be/4 rethinkd    3.94 K/s    0.00 B/s  0.00 % 20.67 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1171 be/4 rethinkd    3.94 K/s    0.00 B/s  0.00 % 19.69 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1187 be/4 rethinkd    0.00 B/s    3.94 K/s  0.00 % 18.72 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1190 be/4 rethinkd    3.94 K/s    0.00 B/s  0.00 % 18.70 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1186 be/4 rethinkd    3.94 K/s    3.94 K/s  0.00 % 17.80 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1180 be/4 rethinkd   11.83 K/s    0.00 B/s  0.00 % 17.75 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1162 be/4 rethinkd   11.83 K/s    0.00 B/s  0.00 % 17.01 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1150 be/4 rethinkd    7.88 K/s    0.00 B/s  0.00 % 16.84 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1144 be/4 rethinkd   11.83 K/s    0.00 B/s  0.00 % 15.80 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1198 be/4 rethinkd    7.88 K/s    3.94 K/s  0.00 % 15.76 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1184 be/4 rethinkd    0.00 B/s    0.00 B/s  0.00 % 15.35 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
  205 be/3 root        0.00 B/s    0.00 B/s  0.00 % 15.27 % [jbd2/xvda1-8]
 1156 be/4 rethinkd    7.88 K/s    0.00 B/s  0.00 % 14.79 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1175 be/4 rethinkd    3.94 K/s    3.94 K/s  0.00 % 14.78 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1183 be/4 rethinkd    0.00 B/s    0.00 B/s  0.00 % 14.41 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1152 be/4 rethinkd    0.00 B/s    0.00 B/s  0.00 % 14.30 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1159 be/4 rethinkd    0.00 B/s    0.00 B/s  0.00 % 14.30 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1174 be/4 rethinkd    3.94 K/s    3.94 K/s  0.00 % 13.79 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1194 be/4 rethinkd    7.88 K/s    3.94 K/s  0.00 % 13.73 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1155 be/4 rethinkd    7.88 K/s    0.00 B/s  0.00 % 12.81 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1149 be/4 rethinkd   15.77 K/s    0.00 B/s  0.00 % 12.75 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
 1146 be/4 rethinkd    7.88 K/s    0.00 B/s  0.00 % 11.83 % rethinkdb --daemon --config-file /etc/rethinkdb/instances.d/instance1.c~thinkdb/instance1/pid_file --directory /var/lib/rethinkdb/instance1/data
```

Not sure what the issue is, after doing research about this. Some other notes:
- DB is about 12GB, taking up 75% of disk. 
- only running on this one AWS server, not sharded
- RethinkDB is the only real application running on this server
- RethinkDB has 768MB memory
- An index is currently being rebuilt on a large (7M document) table, but this was happening before that was started
- The server is not under a lot of load, avg 200 reads per second, 50 writes per second (only while index being rebuilt)

**Comment by KishCom** [comment] 2015-09-14 03:26
I am seeing a very similar problem -- similar db setup as reporter:

* DB is only about 1GB
* only running on this one digital ocean server, not sharded
* RethinkDB is the only real application running on this server
* RethinkDB has 768MB memory (out of 1024GB)
* I have recently added a new index to my biggest table
* The server is not under a lot of load, way less than 200 reads per second, 50 writes per second. Occasional large bursts, but previous versions handled this with ease.

It occasionally locks up completely and needs to be restarted. [Here's a small graph from my Zabbix reporter](https://kishcom.com/temp/rethink_cpuuse.jpg) showing normal operations with the large cpu use spike.

**Comment by danielmewes** [comment] 2015-09-14 23:42
Thanks for the reports @hwestbrook and @KishCom.

@hwestbrook From the `top` output, it looks like the server is a bit tight on RAM:
```
MiB Mem:   992.473 total,  927.391 used,   65.082 free,    0.484 buffers
```

Maybe it's going into swap?

A cache size of 768 MB is probably too high for a 1 GB node. I'd try reducing it to something closer to ~200 MB and see if that helps.

**Comment by hwestbrook** [comment] 2015-09-15 00:10
Yes, I think it is going into swap. Wouldn't I see this in the performance monitoring above, though? 

I am attempting the 200MB change you suggest above. 

Also, looking again at my config file and I see that you can change the io-threads. Is there documentation regarding what this should be set at? I would imagine this would be different for different servers.

**Comment by hwestbrook** [comment] 2015-09-15 00:21
Cache size set to 256MB, and seeing some improvement in the issue, but not a lot. Still sitting at close to 100% iowait.

**Comment by danielmewes** [comment] 2015-09-15 00:42
@hwestbrook Hmm, is the index migration done or is that still running?

There's relatively rarely a reason to reduce `io-threads`. The original reason we added that parameter was to limit the Linux `load` average for people who are on virtualized servers where the provider enforces a limit based on the load value. You can try reducing it to something like `8`, and it might reduce the load (simply because of how `load` is calculated), but I doubt it will have a positive impact on the actual performance.

**Comment by hwestbrook** [comment] 2015-09-25 20:52
I ended up migrating to another server, as I needed to get this db back up and running. No longer experiencing the problem, so you can go ahead and close, even though I do not think this is resolved.

**Comment by danielmewes** [comment] 2015-09-25 23:07
@hwestbrook Thanks for the update. Is that because there's more RAM on the new server?

**Comment by hwestbrook** [comment] 2015-09-26 00:13
Yes moved over to digital ocean and using a server with 2GB memory

**Comment by danielmewes** [comment] 2015-11-17 01:33
Moving to `backlog`. We should try to reproduce the original scenario at some point to track down where the slowness is coming from.

**Closed** 2017-06-05 21:56 UTC
Labels: tp:performance
