### ISSUE TITLE
dump/restore to/from stdout/stdin without any intermediate files

### ISSUE THREAD

**Issue by nh2** [rethinkdb/rethinkdb#5530] opened 2016-03-16 01:37 UTC
My PR for #5525 adds dump/restore to/from stdout/stdin which already helps to implement the `ssh otherhost rethinkdb-dump --file=- | rethinkdb-restore - --force` workflow I had in mind.

But since `dump`/`restore` are still based on the `export`/`import` commands, which are directory based, it still writes temporary files, both for `dump` and `restore`.

There are situations when you don't want that for security reasons, e.g. if you want to use the `ssh otherhost rethinkdb-dump --file=- | rethinkdb-restore - --force` workflow to ensure the data is never written to (potentially unencrypted) disk anywhere, not even temporary files.

To cover this case, we would have to switch the `export`/`import` commands to support a streaming fashion, and then use them accordingly from `dump`/`restore`.

**Comment by larkost** [comment] 2016-04-12 22:41
I am going to close this one as a duplicate of #3755.

**Closed by larkost** 2016-04-12 22:41 UTC
