### ISSUE TITLE
Allow compound secondary indexes to use the first part(s) of the index

### ISSUE THREAD

**Issue by bselack** [rethinkdb/rethinkdb#6150] opened 2016-10-17 15:23 UTC
In most relational databases and some NoSQL databases, when the index is comprised of multiple fields you can use the beginning field(s) to get data. 

For example if a table looks like this

```

{
	"id": "01037ecf-94ac-4d0f-b259-70af7bf57f30",
	"product": "Marvel - Black Widow Figurine",
	"product_id": "9cc3d6a0-aa88-40da-9247-b4a629a44ad7",
	"product_type": "toy",
	"status": "owned",
	"user_id": "95d9e83a-4aa7-43e5-95ec-d66bb559a982"
}

```

and I create an index like this

```
r.table('user_product').indexCreate('productsByUser',  [r.row("user_id"), r.row("status"), r.row("product_type")])

```

I'm able to query like this

```

r.table('user_product').getAll(['1bc1a736-0c13-405e-86f2-3fbd74d253b5', 'owned', 'toy'], {index: 'productsByUser'})

```

but not like this to get all of the user's owned products (regardless of product_type)

```

r.table('user_product').getAll(['1bc1a736-0c13-405e-86f2-3fbd74d253b5', 'owned'], {index: 'productsByUser'})

```

or not like this to get all the user's products (regardless or status or producty_type)

```

r.table('user_product').getAll(['1bc1a736-0c13-405e-86f2-3fbd74d253b5'], {index: 'productsByUser'})

```

**Comment by marshall007** [comment] 2016-10-17 17:35
@bselack you can accomplish this by using a `.between` instead of a `.getAll`. From your example:

```js
r.table('user_product').between(
  ['1bc1a736-0c13-405e-86f2-3fbd74d253b5', 'owned', r.minval],
  ['1bc1a736-0c13-405e-86f2-3fbd74d253b5', 'owned', r.maxval],
  {index: 'productsByUser'}
)
```

**Comment by AtnNn** [comment] 2016-10-17 22:12
Duplicate of #5080

**Closed by AtnNn** 2016-10-17 22:12 UTC
