### ISSUE TITLE
Add optarg to `union` that makes it ordered.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5090] opened 2015-11-14 08:45 UTC
So it will consume all of the first stream, then all of the second stream, etc. instead of mixing the results together.

We should also consider adding some sort of mergesort-like-thing to the server, either as part of this or as a separate term.

**Comment by VeXocide** [comment] 2015-11-14 21:28
I suspect this is a duplicate of #4595.

**Comment by mlucy** [comment] 2015-11-14 23:29
Good catch.  I closed #4595 in favor of this one since this once also mentions the "mergesort-like-thing".

**Comment by danielmewes** [comment] 2015-11-25 01:01
The merge-sort like thing is also discussed in https://github.com/rethinkdb/rethinkdb/issues/4338

**Comment by mlucy** [comment] 2015-12-09 03:04
Alright, I'd like to propose we add an optarg `merge` with three options:
* `'interleaved'` -- this is the current behavior, and will be the default value.
* `'ordered'` -- we read everything from the first stream, then everything from the second, etc.
  - This should produce an error if any stream except the last is an infinite stream.
* A function -- this should be a comparison function implementing `<`, and will be used to do a mergesort-like thing.

**Comment by AtnNn** [comment] 2015-12-09 04:52
`'merge'` may have other connotations, perhaps `'mode'` instead?

`'ordered'` makes me think that the result would be ordered. Perhaps `'add'`, `'append'`, `'argument_order'` or `'left_to_right'` instead?

Perhaps we could also allow specifying the order in the same way as in `order_by`? Either by allowing something like `.order_by(sort=lambda a, b: a < b)` or `.union(comparing=r.desc('a'))` or both. Otherwise using `order_by` and `union` together would be confusing and inconsistent.

**Comment by AtnNn** [comment] 2015-12-09 05:10
See also https://github.com/rethinkdb/rethinkdb/issues/4338

**Comment by mlucy** [comment] 2015-12-09 05:15
That's a good point.  I think you're right that we should probably make the interface the same as the interface for `order_by`, but that adds the complication that we can't name the different ways of combining streams with strings because there might be fields with those names.

How about this: we have an optarg called `interleave`.  It defaults to `true`, but can be set to `false` if you want to do left-to-right unioning.  It can also be set to a string, an array of strings, or a function, which will perform a mergesort with the same semantics as `order_by`.  (So the function is a selector, not a comparator -- you'd write `.union(..., interleaved: function(row) { return row('field'); })` as a synonym for `.union(..., interleaved: 'field')`.)

Also, if you set `interleaved` in a way that causes a mergesort, we should assert that the input streams are in fact ordered by whatever you specify and throw if they aren't.

**Comment by danielmewes** [comment] 2015-12-15 00:46
The selector-function proposal sounds reasonable to me. Would you be able to return `r.desc("foo")` from the function?

I think the optarg should be called `interleave`, not `interleaved` by the way.
I'm not completely happy with the name `interleave`, but I don't have any other idea right now that hasn't been mentioned yet.

**Comment by mlucy** [comment] 2015-12-15 00:58
`interleave` sounds fine to me.  `interleave: r.desc('field')` would definitely work.  Currently returning `r.desc` from a function doesn't work, but we should probably add support for that since I think Fusion needs it to work.

**Comment by danielmewes** [comment] 2015-12-17 00:54
Marking settled as described here https://github.com/rethinkdb/rethinkdb/issues/5090#issuecomment-163110597

**Comment by nighelles** [comment] 2016-01-28 02:45
This is in review 3440,
implemented in nighelles/5090
https://github.com/rethinkdb/rethinkdb/tree/nighelles/5090

**Comment by nighelles** [comment] 2016-02-16 01:48
This is in next.

**Closed by nighelles** 2016-02-16 01:48 UTC
Labels: tp:API_settled, tp:ReQL_proposal
