### ISSUE TITLE
Group on large table causes crash/network split.

### ISSUE THREAD

**Issue by barkerja** [rethinkdb/rethinkdb#4925] opened 2015-10-07 22:32 UTC
First posted on the google group, but bringing the issue here: https://groups.google.com/forum/#!topic/rethinkdb/Hx3DLD193I8

Cluster is a 3-node, each with 9GB of ram (compose.io — so I believe that's 9GB per server, not 9GB for the total cluster, but I can't confirm; perhaps someone here knows. ping! @jipperinbham ).

I have a table, with about 3.8 million documents, each document roughly 0.5kb to 1kb in size.

When I run the query `r.table('custom_field_values').group(index: 'contact_id_custom_field_id').count().run(conn)` one of the nodes drops off the cluster. I _don't_ think it's a crash, according to the logs I do have access to (it just reports a server disconnect, no other errors or stack traces).

Total data in the database is roughly 40GB in size; running 2.1.2

**Comment by coffeemug** [comment] 2015-10-07 23:55
@barkerja -- thanks for the github issue. Do you know if the node reconnects after a while, or does it become permanently unavailable?

**Comment by barkerja** [comment] 2015-10-07 23:57
It reconnects automatically in about 5 minutes.

**Comment by danielmewes** [comment] 2015-10-08 02:20
I suspect this might come from one server going into swap, which will usually make it slow enough to cause other servers to abort the connection to it.
That being said the `group.count()` query really shouldn't use that much memory.

We'll see if we can reproduce this.

**Comment by jipperinbham** [comment] 2015-10-08 14:50
@barkerja re: memory allocation, every member in the cluster has 9GB allocated and is constrained using cgroups. 

We've spoken with @danielmewes about this a few times and like he said, it's likely the heartbeat thread dying when the server process goes into swap.

**Comment by danielmewes** [comment] 2015-10-09 18:05
Talked to @barkerja directly.
There were a lot of groups in the data, all of which had to be loaded into memory.
The mid-term solution for this one and similar queries is going to be https://github.com/rethinkdb/rethinkdb/issues/2719

Short-term we found the following equivalent query which is actually lazily evaluated and avoids the memory overhead:
```
r.table('custom_field_values')
  .distinct({index: 'contact_id_custom_field_id'})
  .map({
    group: r.row,
    reduction: r.table('custom_field_values').getAll(r.row, {index: 'contact_id_custom_field_id'}).count()
  })
```

**Comment by danielmewes** [comment] 2015-10-09 18:06
Closing as duplicate of https://github.com/rethinkdb/rethinkdb/issues/2719

**Closed by danielmewes** 2015-10-09 18:06 UTC
Labels: tp:bug, tp:performance
