### ISSUE TITLE
[apt repo] Invalid 'Date' entry in Release file w/ apt-1.1

### ISSUE THREAD

**Issue by himdel** [rethinkdb/rethinkdb#5174] opened 2015-12-04 00:23 UTC
With the [new release](https://mvogt.wordpress.com/2015/11/30/apt-1-1-released/) of apt-1.1, the apt repositories at http://download.rethinkdb.com/apt/ are failing to update..

```
$ apt update
...
W: Failed to fetch http://download.rethinkdb.com/apt/dists/stretch/Release  Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/download.rethinkdb.com_apt_dists_stretch_Release
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

The invalid 'Date' entry specifically means no Date entry at all actually :).

This repo is probably not the right place for this issue, sorry, but there was no other; all other debian repo Release files do contain a Date entry, so assuming not an apt bug..

**Comment by danielmewes** [comment] 2015-12-04 00:54
Thanks for reporting this, this is definitely the right place for the issue.

@AtnNn could you look into this please?

**Comment by AtnNn** [comment] 2015-12-04 01:13
We use `freight` to manage the apt repo. It does not seem to know about the `Date` field: https://github.com/rcrowley/freight/blob/master/lib/freight/apt.sh#L155-L160

It shouldn't be too hard to add.

**Comment by AtnNn** [comment] 2015-12-04 02:35
This patch seems to fix the issue https://github.com/AtnNn/freight/commit/6da26b6575610cd667b4c2b53aeb9c31d3adc46e

**Comment by mmoll** [comment] 2015-12-07 22:12
@AtnNn could you open a PR to the the freight repo? I'm also running into this.

**Comment by AtnNn** [comment] 2015-12-07 22:21
@mmoll https://github.com/rcrowley/freight/pull/65

**Comment by mmoll** [comment] 2015-12-07 22:24
thanks :bow:

**Comment by DenJohX** [comment] 2015-12-12 19:12
So, until freight merges the patch and you install the updated version, there is no way to install rethink from the repos. 

Could you apply the patch to your freight so we can install it?

**Comment by danielmewes** [comment] 2015-12-14 19:22
@DenJohX We will build the repo with the fix for the next update (RethinkDB 2.2.2), independently of whether the patch gets merged upstream or not.

My understanding is that this only applies if you're running an unstable distribution or manually install the new apt version. Is that correct? Or does this affect any supported distributions?
We could rebuild the repositories before the next release if necessary.

In the meantime you can of course work around this by downloading the package directly from https://download.rethinkdb.com/apt/pool/ .

**Comment by DenJohX** [comment] 2015-12-14 19:34
I'm on Debian testing, which is not a uncommon situation if you use your computer for developing. 

But, yes, testing qualifies as an unstable distribution.

I will try to install the packages manually, though.

**Comment by himdel** [comment] 2015-12-15 14:47
Agreed, when I reported it, apt-1.1 was in experimental so needed to be manually installed. Is has since moved to sid (unstable) and stretch (testing). While stretch is not a release, I actually don't know anyone using Debian for daily work (as opposed to servers) and not using testing..

So.. 2.2.2 is probably fine, assuming it goes out after new years and not after easter.

**Comment by danielmewes** [comment] 2015-12-15 21:57
Yeah, 2.2.2 should be out shortly (this week probably).

**Comment by DenJohX** [comment] 2015-12-15 22:49
As a side note, currently the package doesn't work in Debian testing due to an unsatisfied dependency on  libprotobuf9 which got renamed to libprotobuf9v5.

IMHO there should be support for Debian testing as it is more suited for developing/daily-use.

**Comment by AtnNn** [comment] 2015-12-15 22:57
@DenJohX There are packages for stretch available on http://download.rehtinkdb.com/apt built against libprotobuf8v5.

**Comment by DenJohX** [comment] 2015-12-15 23:07
@AtnNn yo are right!, sorry I didnt notice the stretch pool.

**Comment by danielmewes** [comment] 2015-12-21 21:11
@DenJohX @himdel Would you mind retrying? This should be fixed now.

**Comment by himdel** [comment] 2015-12-22 13:08
@danielmewes Looks good, thanks!

**Comment by karmux** [comment] 2016-08-06 08:47
This started to happen again.

```
# apt-get update
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://download.rethinkdb.com/apt stretch InRelease
Hit:3 http://download.rethinkdb.com/apt stretch Release 
Get:4 http://download.rethinkdb.com/apt stretch Release.gpg [490 B]
Hit:5 http://ftp.acc.umu.se/debian stretch InRelease
Hit:6 http://ftp.vectranet.pl/debian stretch-updates InRelease
Fetched 490 B in 1s (265 B/s)                      
Reading package lists... Done
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/download.rethinkdb.com_apt_dists_stretch_Release
W: The repository 'http://download.rethinkdb.com/apt stretch Release' provides only weak security information.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by danielmewes** [comment] 2016-08-08 18:27
Thanks for the report @karmux .

This might be a different problem from the original. Originally the `Date` entry was missing, but it's definitely there now: http://download.rethinkdb.com/apt/dists/stretch/Release

I also wonder why it's complaining about the weak security...

Will see if I can reproduce.

**Comment by danielmewes** [comment] 2016-08-08 18:33
I can reproduce this after updating the version of `apt` in Debian Stretch. It works fine with the version that originally came with Stretch. We'll look into it.

**Comment by danielmewes** [comment] 2016-08-08 18:36
Looks like the data is supposed to be in UTC ( https://wiki.debian.org/RepositoryFormat#Date.2CValid-Until ), while our repositories specify it in PDT local time. Will need to try if that's actually the issue...

**Comment by danielmewes** [comment] 2016-08-08 20:04
Ok should be fixed now. @karmux Can you check again please?

**Closed by danielmewes** 2016-08-08 20:04 UTC
Labels: cp:packaging

**Comment by karmux** [comment] 2016-08-08 21:47
@danielmewes these warnings are gone now. Thanks!
