### ISSUE TITLE
Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

### ISSUE THREAD

**Issue by nitte93** [rethinkdb/rethinkdb#5802] opened 2016-05-28 17:01 UTC
Hi

I'm getting the following error when I try to call the connect function in rethinkDB
`
net.js?233a:840 XMLHttpRequest cannot load http://localhost:28051undefinedajax/reql/open-new-connection?cacheBuster=0.1805495970778639. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`

config.js
```
module.exports = {
    host: 'localhost',
    port: '28051',
    db: 'test'
};
```

connect.js
```
    import rethink from 'rethinkdb'
    import dbConfig from '../settings/config'
    var connection = rethink.connect(dbConfig)
    .then(function (connection) {

        module.exports.find = function (tableName, id) {
            return rethink.table(tableName).get(id).run(connection)
            .then(function (result) {
                return result;
            });
        };

    });

```

Moreover, How do I make my connection persistent throughout the app.

**Comment by larkost** [comment] 2016-05-30 01:09
Unless I am really misreading something, this is because you are trying to use the JavaScript driver directly in your browser. This is a common mistake (I opened rethinkdb/docs#1132 to put it in our FAQ), rather the JavaScript driver is made to work from [Node.js](http://nodejs.org). There are a number of reasons for this, but the primary one is that client-side is the wrong place to put code that enforces things like security. So there needs to be a server component.

I also will mention that we have recently unveiled [Horizon](http://horizon.io), which tries to take most of the work of setting up that back-end over from you until you need something more complicated, at which point you can transition to your own server-side code a piece at time.

I am going to close this as not-a-bug, but feel free to ask more questions in this issue.

**Closed by larkost** 2016-05-30 01:09 UTC

**Comment by nitte93** [comment] 2016-05-30 10:24
Hi @larkost ,
Thanks for your response, I think you're right. I am making some mistake with the rethink drivers.
I am using webpack as the bundler. And the entry folder contains the rethink driver files also. Do you think this is causing the issue. May be it is trying to bundle the driver's code too. What do you suggest?

**Comment by danielmewes** [comment] 2016-05-30 21:27
@nitte93 I don't think the issue is webpack, but the fact that you're running the code in your browser and not in node.js. Please correct me if I'm wrong though.

As @larkost said: The RethinkDB JavaScript driver must be run in node.js on the backend. You can't use it directly in your frontend / browser code. http://horizon.io might be what you're looking for.

**Comment by kayoderock** [comment] 2018-02-17 23:41
The problem I feel has to the with your URL "http://localhost:28051undefinedajax/reql/open-new-connection?cacheBuster=0.1805495970778639. " it is unsafe that's why chrome does not allow the connection. not sure, I stand to be corrected

**Comment by 0xcaff** [comment] 2019-12-26 21:35
Shouldn't this be theoretically possible? I think it also makes sense for some cases. Chrome extensions are privileged client-side applications, what if people just want to use RethinkDB to dump and query data from their chrome extensions? I don't think the security concern is valid in this case, as the chrome extension is trusted, adding a backend is just more boilerplate which doesn't affect the security guarantees.

**Comment by srh** [comment] 2019-12-27 10:42
@0xcaff I'm not familiar with Chrome extensions, but if there is an API to open TCP connections, they can use that.  That's what Electron users should use.  If there is not such an API... well, the RethinkDB admin UI tunnels TCP over HTTP, and if you enable the admin UI on the server, and aren't worried about RethinkDB's users and privileges (because the admin UI requires admin privileges), you could go that route.  There is an undocumented way to enable that in the JS driver.

But generally speaking, RethinkDB does not "officially" offer an HTTP protocol interface, but, it's open source, and if a more secure interface with passwords is necessary, that is possible.
