### ISSUE TITLE
Help building rethink-next_windows

### ISSUE THREAD

**Issue by chdev77** [rethinkdb/rethinkdb#5910] opened 2016-07-02 17:45 UTC
I downloaded the windows installer from http://rethinkdb.com/docs/install/windows/

I'm trying to set it up with ssl but this version does not support the command options
--http-tls-key key_filename
--http-tls-cert cert_filename

--driver-tls-key key_filename
--driver-tls-cert cert_filename
--driver-tls-ca ca_filename

So this lead me to venture off and get the latest source for windows.  I attempted to follow the instructions here https://github.com/rethinkdb/rethinkdb/blob/next_windows/WINDOWS.md

no luck.  I'm a total noob at compiling this type of source and have no idea what I'm doing.  My goal is to have a rethinkdb hosted on an Azure Windows VM.  I want to point my client to the Azure VM RethinkDb instance. https://rethinkdb.mydomain.com:5568  I have dns and ssl all setup but cannot seem to get RethinkDB configured.

I can access it locally but stopped when configuring TLS.

Here is the output from Cygwin.  Its not able to resolve the .cache path of the wget packages or something?!?!?

```
corey_000@Daddy-Desktop ~
$ cd "c:\rethinkdb-next_windows"

corey_000@Daddy-Desktop /cygdrive/c/rethinkdb-next_windows
$ ./configure
* Detecting system configuration
Bash:                           4.3.42(4)-release
Operating System:
Microsoft Windows [Version 10.0.10240]
msbuild:                        msbuild 14.0.25123
vcvarsall:                      /cygdrive/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/vcvarsall.bat
cmake:                          /cygdrive/c/Program Files/CMake/bin/cmake.exe
Platform:                       x64
Protobuf library:               external/protobuf_2.5.0
curl:                           external/curl_7.40.0
v8 javascript engine:           external/v8_4.7.80.23
zlib:                           external/zlib_1.2.8
RE2:                            external/re2_2015-11-01
openssl:                        external/openssl_1.0.1t
Google Test:                    external/gtest_1.7.0
boost:                          external/boost_1.60.0
Node.js package manager:        /cygdrive/c/Program Files (x86)/nodejs/npm
coffee:                         external/coffee-script_1.10.0
bluebird:                       external/bluebird_2.9.32
Browserify:                     external/browserify_12.0.1
web UI dependencies:            external/admin-deps_2.0.4
Python:                         no
Installation prefix:            /usr/local
Configuration prefix:           /usr/local/etc
Runtime data prefix:            /usr/local/var
* Wrote configuration to config.mk

corey_000@Daddy-Desktop /cygdrive/c/rethinkdb-next_windows
$ make -j
/bin/sh: line 4: mk/gen/phony-list.mk: No such file or directory
/bin/sh: mk/gen/allowed-variables.mk: No such file or directory
make: [mk/check-env.mk:11: mk/gen/allowed-variables.mk] Error 1 (ignored)
./scripts/gen-version.sh: Warning: could not determine the version, using the default version '2.3.2-fallback'
/usr/bin/bash: mk/gen/allowed-variables.mk: No such file or directory
make: Possibly unknown variables defined in : MAKE_VARIABLE_CHECK
./scripts/gen-version.sh: Warning: could not determine the version, using the default version '2.3.2-fallback'
/usr/bin/bash: mk/gen/allowed-variables.mk: No such file or directory
    FETCH protobuf_2.5.0
    FETCH curl_7.40.0
    FETCH v8_4.7.80.23
    FETCH zlib_1.2.8
    FETCH re2_2015-11-01
    FETCH openssl_1.0.1t
    BUILD gtest_1.7.0
    FETCH boost_1.60.0
    BUILD coffee-script_1.10.0
    BUILD browserify_12.0.1
    BUILD admin-deps_2.0.4
    CONVERT_PROTOFILE build/drivers/javascript/proto-def.js
/usr/bin/env: ‘python’: No such file or directory
make[1]: *** [drivers/javascript/build.mk:18: build/drivers/javascript/proto-def.js] Error 127
make[1]: *** Waiting for unfinished jobs....
++ [[ Windows != Windows ]]
+ pkg_fetch
+ test -n http://curl.haxx.se/download/curl-7.40.0.tar.bz2
+ pkg_fetch_archive
+ pkg_make_tmp_fetch_dir
++ mktemp -d /cygdrive/c/rethinkdb-next_windows/external/curl_7.40.0.fetch-XXXXXXXX
+ tmp_dir=/cygdrive/c/rethinkdb-next_windows/external/curl_7.40.0.fetch-ARM7a9fT
+ local archive_name=curl-7.40.0.tar.bz2
+ local archive=/cygdrive/c/rethinkdb-next_windows/external/.cache/curl-7.40.0.tar.bz2
+ local actual_sha1
+ [[ -e /cygdrive/c/rethinkdb-next_windows/external/.cache/curl-7.40.0.tar.bz2 ]]
+ [[ ! -e /cygdrive/c/rethinkdb-next_windows/external/.cache/curl-7.40.0.tar.bz2 ]]
+ local url
+ mkdir -p /cygdrive/c/rethinkdb-next_windows/external/.cache
+ geturl http://curl.haxx.se/download/curl-7.40.0.tar.bz2 /cygdrive/c/rethinkdb-next_windows/external/.cache/curl-7.40.0.tar.bz2
+ [[ -n '' ]]
+ wget --quiet --output-document=/cygdrive/c/rethinkdb-next_windows/external/.cache/curl-7.40.0.tar.bz2 http://curl.haxx.se/download/curl-7.40.0.tar.bz2
mk/support/pkg/pkg.sh: line 376: wget: command not found
+ [[ -n '' ]]
+ exit 1

Full error log: ./build/external/curl_7.40.0_fetch.log
++ true
+ pkg_fetch
+ test -n https://github.com/google/re2/archive/2015-11-01.tar.gz
+ pkg_fetch_archive
+ pkg_make_tmp_fetch_dir
++ mktemp -d /cygdrive/c/rethinkdb-next_windows/external/re2_2015-11-01.fetch-XXXXXXXX
+ tmp_dir=/cygdrive/c/rethinkdb-next_windows/external/re2_2015-11-01.fetch-2CmrG0in
+ local archive_name=2015-11-01.tar.gz
+ local archive=/cygdrive/c/rethinkdb-next_windows/external/.cache/2015-11-01.tar.gz
+ local actual_sha1
+ [[ -e /cygdrive/c/rethinkdb-next_windows/external/.cache/2015-11-01.tar.gz ]]
+ [[ ! -e /cygdrive/c/rethinkdb-next_windows/external/.cache/2015-11-01.tar.gz ]]
+ local url
+ mkdir -p /cygdrive/c/rethinkdb-next_windows/external/.cache
+ geturl https://github.com/google/re2/archive/2015-11-01.tar.gz /cygdrive/c/rethinkdb-next_windows/external/.cache/2015-11-01.tar.gz
+ [[ -n '' ]]
+ wget --quiet --output-document=/cygdrive/c/rethinkdb-next_windows/external/.cache/2015-11-01.tar.gz https://github.com/google/re2/archive/2015-11-01.tar.gz
mk/support/pkg/pkg.sh: line 376: wget: command not found
+ [[ -n '' ]]
+ exit 1
++ true
+ pkg_fetch
+ test -n http://protobuf.googlecode.com/files/protobuf-2.5.0.tar.bz2
+ pkg_fetch_archive
+ pkg_make_tmp_fetch_dir
++ mktemp -d /cygdrive/c/rethinkdb-next_windows/external/protobuf_2.5.0.fetch-XXXXXXXX
+ tmp_dir=/cygdrive/c/rethinkdb-next_windows/external/protobuf_2.5.0.fetch-VKQNfs1n
+ local archive_name=protobuf-2.5.0.tar.bz2
+ local archive=/cygdrive/c/rethinkdb-next_windows/external/.cache/protobuf-2.5.0.tar.bz2
+ local actual_sha1
+ [[ -e /cygdrive/c/rethinkdb-next_windows/external/.cache/protobuf-2.5.0.tar.bz2 ]]
+ [[ ! -e /cygdrive/c/rethinkdb-next_windows/external/.cache/protobuf-2.5.0.tar.bz2 ]]
+ local url
+ mkdir -p /cygdrive/c/rethinkdb-next_windows/external/.cache
+ geturl http://protobuf.googlecode.com/files/protobuf-2.5.0.tar.bz2 /cygdrive/c/rethinkdb-next_windows/external/.cache/protobuf-2.5.0.tar.bz2
+ [[ -n '' ]]
+ wget --quiet --output-document=/cygdrive/c/rethinkdb-next_windows/external/.cache/protobuf-2.5.0.tar.bz2 http://protobuf.googlecode.com/files/protobuf-2.5.0.tar.bz2
mk/support/pkg/pkg.sh: line 376: wget: command not found
+ [[ -n '' ]]
+ exit 1

Full error log: ./build/external/re2_2015-11-01_fetch.log

Full error log: ./build/external/protobuf_2.5.0_fetch.log
make[1]: *** [mk/support/build.mk:68: external/curl_7.40.0] Error 1
make[1]: *** [mk/support/build.mk:68: external/re2_2015-11-01] Error 1
make[1]: *** [mk/support/build.mk:68: external/protobuf_2.5.0] Error 1
++ true
+ pkg_fetch
+ test -n http://zlib.net/zlib-1.2.8.tar.gz
+ pkg_fetch_archive
+ pkg_make_tmp_fetch_dir
++ mktemp -d /cygdrive/c/rethinkdb-next_windows/external/zlib_1.2.8.fetch-XXXXXXXX
+ tmp_dir=/cygdrive/c/rethinkdb-next_windows/external/zlib_1.2.8.fetch-ZD2pXrPR
+ local archive_name=zlib-1.2.8.tar.gz
+ local archive=/cygdrive/c/rethinkdb-next_windows/external/.cache/zlib-1.2.8.tar.gz
+ local actual_sha1
+ [[ -e /cygdrive/c/rethinkdb-next_windows/external/.cache/zlib-1.2.8.tar.gz ]]
+ [[ ! -e /cygdrive/c/rethinkdb-next_windows/external/.cache/zlib-1.2.8.tar.gz ]]
+ local url
+ mkdir -p /cygdrive/c/rethinkdb-next_windows/external/.cache
+ geturl http://zlib.net/zlib-1.2.8.tar.gz /cygdrive/c/rethinkdb-next_windows/external/.cache/zlib-1.2.8.tar.gz
+ [[ -n '' ]]
+ wget --quiet --output-document=/cygdrive/c/rethinkdb-next_windows/external/.cache/zlib-1.2.8.tar.gz http://zlib.net/zlib-1.2.8.tar.gz
mk/support/pkg/pkg.sh: line 376: wget: command not found
+ [[ -n '' ]]
+ exit 1

Full error log: ./build/external/zlib_1.2.8_fetch.log
make[1]: *** [mk/support/build.mk:68: external/zlib_1.2.8] Error 1
+ pkg_fetch_archive
+ pkg_make_tmp_fetch_dir
++ mktemp -d /cygdrive/c/rethinkdb-next_windows/external/openssl_1.0.1t.fetch-XXXXXXXX
+ tmp_dir=/cygdrive/c/rethinkdb-next_windows/external/openssl_1.0.1t.fetch-ciX8Eybr
+ local archive_name=openssl-1.0.1t.tar.gz
+ local archive=/cygdrive/c/rethinkdb-next_windows/external/.cache/openssl-1.0.1t.tar.gz
+ local actual_sha1
+ [[ -e /cygdrive/c/rethinkdb-next_windows/external/.cache/openssl-1.0.1t.tar.gz ]]
+ [[ ! -e /cygdrive/c/rethinkdb-next_windows/external/.cache/openssl-1.0.1t.tar.gz ]]
+ local url
+ mkdir -p /cygdrive/c/rethinkdb-next_windows/external/.cache
+ geturl https://www.openssl.org/source/openssl-1.0.1t.tar.gz /cygdrive/c/rethinkdb-next_windows/external/.cache/openssl-1.0.1t.tar.gz
+ [[ -n '' ]]
+ wget --quiet --output-document=/cygdrive/c/rethinkdb-next_windows/external/.cache/openssl-1.0.1t.tar.gz https://www.openssl.org/source/openssl-1.0.1t.tar.gz
mk/support/pkg/pkg.sh: line 376: wget: command not found
+ [[ -n ftp://ftp.openssl.org/source/openssl-1.0.1t.tar.gz ]]
+ geturl ftp://ftp.openssl.org/source/openssl-1.0.1t.tar.gz /cygdrive/c/rethinkdb-next_windows/external/.cache/openssl-1.0.1t.tar.gz
+ [[ -n '' ]]
+ wget --quiet --output-document=/cygdrive/c/rethinkdb-next_windows/external/.cache/openssl-1.0.1t.tar.gz ftp://ftp.openssl.org/source/openssl-1.0.1t.tar.gz
mk/support/pkg/pkg.sh: line 376: wget: command not found

Full error log: ./build/external/openssl_1.0.1t_fetch.log
make[1]: *** [mk/support/build.mk:68: external/openssl_1.0.1t] Error 1
++ true
+ pkg_fetch
+ test -n http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.bz2
+ pkg_fetch_archive
+ pkg_make_tmp_fetch_dir
++ mktemp -d /cygdrive/c/rethinkdb-next_windows/external/boost_1.60.0.fetch-XXXXXXXX
+ tmp_dir=/cygdrive/c/rethinkdb-next_windows/external/boost_1.60.0.fetch-emQiAxq5
+ local archive_name=boost_1_60_0.tar.bz2
+ local archive=/cygdrive/c/rethinkdb-next_windows/external/.cache/boost_1_60_0.tar.bz2
+ local actual_sha1
+ [[ -e /cygdrive/c/rethinkdb-next_windows/external/.cache/boost_1_60_0.tar.bz2 ]]
+ [[ ! -e /cygdrive/c/rethinkdb-next_windows/external/.cache/boost_1_60_0.tar.bz2 ]]
+ local url
+ mkdir -p /cygdrive/c/rethinkdb-next_windows/external/.cache
+ geturl http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.bz2 /cygdrive/c/rethinkdb-next_windows/external/.cache/boost_1_60_0.tar.bz2
+ [[ -n '' ]]
+ wget --quiet --output-document=/cygdrive/c/rethinkdb-next_windows/external/.cache/boost_1_60_0.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.bz2
mk/support/pkg/pkg.sh: line 376: wget: command not found
+ [[ -n '' ]]
+ exit 1

Full error log: ./build/external/boost_1.60.0_fetch.log
make[1]: *** [mk/support/build.mk:68: external/boost_1.60.0] Error 1
CMake Error: : System Error: No such file or directory
CMake Error at C:/Program Files/CMake/share/cmake-3.6/Modules/CMakeDetermineCCompiler.cmake:184 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:42 (project)


CMake Error: Could not find cmake module file: C:/rethinkdb-next_windows/build/external/gtest_1.7.0/build/CMakeFiles/3.6.0-rc4/CMakeCCompiler.cmake
CMake Error at CMakeLists.txt:42 (project):
  No CMAKE_CXX_COMPILER could be found.



CMake Error at CMakeLists.txt:42 (project):
  No CMAKE_C_COMPILER could be found.



-- Configuring incomplete, errors occurred!
CMake Error: Unable to open check cache file for write. C:/rethinkdb-next_windows/build/external/gtest_1.7.0/build/CMakeFiles/cmake.check_cache

Full error log: ./build/external/gtest_1.7.0_install.log
make[1]: *** [mk/support/build.mk:146: build/external/gtest_1.7.0/install.witness.x64-Release] Error 1
+ pkg_depends_env
++ pkg_depends
++ true
+ pkg_fetch
+ pkg_make_tmp_fetch_dir
++ mktemp -d /cygdrive/c/rethinkdb-next_windows/external/v8_4.7.80.23.fetch-XXXXXXXX
+ tmp_dir=/cygdrive/c/rethinkdb-next_windows/external/v8_4.7.80.23.fetch-jz4LhkbA
+ git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git /cygdrive/c/rethinkdb-next_windows/external/v8_4.7.80.23.fetch-jz4LhkbA/depot_tools
Cloning into '/cygdrive/c/rethinkdb-next_windows/external/v8_4.7.80.23.fetch-jz4LhkbA/depot_tools'...
Checking out files: 100% (951/951), done.
+ PATH='/cygdrive/c/rethinkdb-next_windows/external/v8_4.7.80.23.fetch-jz4LhkbA/depot_tools:/usr/local/bin:/usr/bin:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/cygdrive/c/Program Files/Microsoft SQL Server/120/Tools/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/110/Tools/Binn/ManagementStudio:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/110/Tools/Binn:/cygdrive/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn:/cygdrive/c/WINDOWS/system32/config/systemprofile/.dnx/bin:/cygdrive/c/Program Files/Microsoft DNX/Dnvm:/cygdrive/c/Program Files (x86)/nodejs:/cygdrive/c/Program Files/Microsoft/Web Platform Installer:/cygdrive/c/Program Files (x86)/AMD/ATI.ACE/Core-Static:/cygdrive/d/Android/sdk/platform-tools:/cygdrive/c/Program Files/Microsoft SQL Server/110/DTS/Binn:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/IDE/PrivateAssemblies:/cygdrive/c/Program Files (x86)/Skype/Phone:/cygdrive/c/Program Files (x86)/Windows Live/Shared:/cygdrive/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/cygdrive/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/cygdrive/c/Program Files (x86)/Microsoft Emulator Manager/1.0:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Users/corey_000/AppData/Roaming/npm'
+ in_dir /cygdrive/c/rethinkdb-next_windows/external/v8_4.7.80.23.fetch-jz4LhkbA gclient config --unmanaged https://chromium.googlesource.com/v8/v8.git
+ local dir=/cygdrive/c/rethinkdb-next_windows/external/v8_4.7.80.23.fetch-jz4LhkbA
+ shift
+ cd /cygdrive/c/rethinkdb-next_windows/external/v8_4.7.80.23.fetch-jz4LhkbA
+ gclient config --unmanaged https://chromium.googlesource.com/v8/v8.git
mk/support/pkg/pkg.sh: line 320: gclient: command not found

Full error log: ./build/external/v8_4.7.80.23_fetch.log
make[1]: *** [mk/support/build.mk:68: external/v8_4.7.80.23] Error 1
make: *** [Makefile:53: make] Error 2

corey_000@Daddy-Desktop /cygdrive/c/rethinkdb-next_windows
```

**Comment by danielmewes** [comment] 2016-07-06 18:43
Hi @chdev77, the latest version of the Windows port has been merged into the `next` branch in the meantime. https://github.com/rethinkdb/rethinkdb/blob/next/WINDOWS.md has slightly updated build instructions.

You might also need to manually create the folder `mk/gen`:
```
$ mkdir mk/gen
```

Note however that TLS support is not implemented for Windows yet. So even if you compile from source, you can't just enable it. The Linux implementation doesn't work on Windows because the network APIs are different.
If you're familiar with C++ programming on Windows and would like to work on a patch to add TLS support for Windows, please let me know and I can give you some more details.
Also see https://github.com/rethinkdb/rethinkdb/issues/5592

**Comment by gabor-boros** [comment] 2022-05-07 22:45
Closing this issue, because

- The next branch is no longer maintained -- the default branch has been changed
- WSL2 runs RethinkDB properly -- as far as we know
- The issue is outdated

**Closed by gabor-boros** 2022-05-07 22:45 UTC
Labels: cp:build, windows
