### ISSUE TITLE
rethinkdb.errors.ReqlOpFailedError with CentOS 6.7/7.0 and Python 'rethinkdb' driver

### ISSUE THREAD

**Issue by zopyx** [rethinkdb/rethinkdb#5263] opened 2016-01-07 19:14 UTC
I am receiving the attached error below with a simple Python script.

Environment: Python 2.7 + RethinkDB 2.2.2

The error is reproducible with two hosts running CentOS 6.7 and 7.0.

```
import rethinkdb as r

db = r.connect( "localhost", 28015).repl()
rows = list()
for i in range(10000):
    rows.extend([
        { "name": "William Adama", "tv_show": "Battlestar Galactica",
          "posts": [
            {"title": "Decommissioning speech", "content": "The Cylon War is long over..."},
            {"title": "We are at war", "content": "Moments ago, this ship received..."},
            {"title": "The new Earth", "content": "The discoveries of the past few days..."}
          ]
        },
        { "name": "Laura Roslin", "tv_show": "Battlestar Galactica",
          "posts": [
            {"title": "The oath of office", "content": "I, Laura Roslin, ..."},
            {"title": "They look like us", "content": "The Cylons have the ability..."}
          ]
        },
        { "name": "Jean-Luc Picard", "tv_show": "Star Trek TNG",
          "posts": [
            {"title": "Civil rights", "content": "There are some words I've known since..."}
          ]
        }
    ])
    
print 'insert'    
print len(rows)
import time
ts = time.time()
r.table("authors").insert(rows).run()
print time.time() - ts
```

```
Traceback (most recent call last):
  File "o.py", line 31, in <module>
    r.table("authors").insert(rows).run()
  File "/home/ajung/src/remodel/lib/python2.7/site-packages/rethinkdb/ast.py", line 118, in run
    return c._start(self, **global_optargs)
  File "/home/ajung/src/remodel/lib/python2.7/site-packages/rethinkdb/net.py", line 589, in _start
    return self._instance.run_query(q, global_optargs.get('noreply', False))
  File "/home/ajung/src/remodel/lib/python2.7/site-packages/rethinkdb/net.py", line 451, in run_query
    raise res.make_error(query)
rethinkdb.errors.ReqlOpFailedError
````

**Comment by larkost** [comment] 2016-01-07 23:21
@zopyx thanks for the report, especially for putting it in the form of a script I can run to investigate with. However, I am not able to reproduce the error thus far... I am running v2.2.2, but using a `scroot` CentoOS 7.0 image rather than a full version of the OS. I don't think that that should make a difference, but I could be wrong about that.

However could you check a couple of things for me, just so that I can make sure we have the exact same environment? If you could provide the output from these commands that might help me nail what is going on here:
```
uname -a
rethinkdb --version
python2.7 -c 'import rethinkdb; print(rethinkdb.version)'
```

**Comment by danielmewes** [comment] 2016-01-07 23:51
This sounds like the table `authors` is unavailable. @zopyx can you check either the web UI or the output of `r.table('authors').status()` to make sure that the table is actually ready?

**Comment by larkost** [comment] 2016-01-08 01:32
@danielmewes Unless we have a bad case would that not give an error about table availability? Specifically something like: `rethinkdb.errors.ReqlOpFailedError: Cannot perform write: primary replica for shard ["", +inf) not available in:`. If we are not emitting the detail in the error then that is probably a bug.

**Comment by danielmewes** [comment] 2016-01-08 01:47
@larkost Yes that's true. There appears to be an issue with the error printing.

In a quick test on Python 2.7.3 and the latest Python driver this is working fine for me with `ReqlOpFailedError`s.

I wonder if printing the exception message is just taking a really long time, since the query is so large.
It looks something like this:
```py
rethinkdb.errors.ReqlOpFailedError: Cannot perform read: The primary replica isn't connected to a quorum of replicas. The read was not performed, you can do an outdated read using `read_mode="outdated"` in:
r.table('t1')
^^^^^^^^^^^^^
```
Note that it includes a printout of the query itself, which in this case will contain all of `rows`.

**Comment by zopyx** [comment] 2016-01-08 11:34
I can reproduce the same error on a third Linux system running OpenSuse
LEAP 42

ajung@blackmoon2:~/src/rethinkdb-2.2.2> /opt/rethinkdb/bin/rethinkdb
--version
rethinkdb 2.2.2 (GCC 4.8.5)

ajung@blackmoon2:~/src/rethinkdb-2.2.2> uname -a
Linux blackmoon2 4.1.13-5-default #1 SMP PREEMPT Thu Nov 26 16:35:17 UTC
2015 (49475c3) x86_64 x86_64 x86_64 GNU/Linux

ajung@blackmoon2:/data/home/ajung/src/rethinkdb> bin/python2.7 -c 'import
rethinkdb; print(rethinkdb.version)'
2.2.0-2


2016-01-08 2:47 GMT+01:00 Daniel Mewes <notifications@github.com>:

**Comment by danielmewes** [comment] 2016-01-08 16:54
Ok I think know what happens here:

1. The table (probably) doesn't exist, hence the `ReqlOpFailedError` is raised with the message "Table `test.authors` does not exist in: [...]"
2. Because the `insert` query is so big, printing the error message takes a while.I can see a delay of about 10 seconds on my machine, before it starts printing out the error message and the query itself (which in the end just prints loads of spaces, because of the `   ^^^^     ` highlighting at the end). Within those 10 seconds, the error output looks exactly like @zopyx posted above.

@zopyx The solution is simple: You need to create the table `authors` before you can use it. You can do this either through the web console (on port 8080 by default), or by running `r.table_create("authors").run()` in Python.
Please let us know if that works.

I'll open a separate issue to discuss if we should truncate long queries when printing exceptions.

**Comment by zopyx** [comment] 2016-01-08 18:06
You are right..the table did not exist and the deferred rendering of the huge exception did it job for adding extra confusion. Perhaps the exception render could limit the lenght of e exception in some way in order to provide a clearer feedback to the user.

**Comment by danielmewes** [comment] 2016-01-08 20:04
Ok, closing in favor of #5272.

**Closed by danielmewes** 2016-01-08 20:04 UTC
