### ISSUE TITLE
Mediafly Urgent Request- Remove Logo and Company Mention from Your Website

### ISSUE THREAD

**Issue by msstyu** [rethinkdb/rethinkdb#6930] opened 2020-12-02 15:51 UTC
Hello, please remove all mentions of Mediafly and the logo from your website. The logo is on your homepage and Mediafly is also mentioned on your FAQ page inaccurately. Please contact me regarding this issue, I have not been able to find any other contact information for this company. Thanks!

**Comment by v3ss0n** [comment] 2020-12-02 16:59
requested @srh

**Comment by msstyu** [comment] 2020-12-02 17:03
Hi,

Please remove all mentions of Mediafly from your website. We found our logo
on your homepage and also our name mentioned on your FAQ page inaccurately
portraying how we use your service.


<https://www.mediafly.com/>
*Sarah Senne*
*Digital Marketing Coordinator*

*t:* 734-660-2281
*w:* www.mediafly.com
*e:* ssenne@mediafly.com
*The Evolved Selling™ Solution*

**Comment by clovergaze** [comment] 2020-12-02 17:16
@msstyu The RethinkDB project is not exactly a company. May I kindly ask why you would like the mention to be removed? Are you no longer using RethinkDB?

**Comment by msstyu** [comment] 2020-12-02 17:25
Whoever runs the website should please remove our company mention then.
We'd like it removed firstly because we are listed in a way that is
completely inaccurate. The FAQ page mentions how we apparently use
RethinkDB and it is totally incorrect and the logo on the homepage is
outdated (we've since rebranded). Second, what brought our attention to
this in the first place, is the founder making inappropriate posts on
Twitter. The posts went viral and our company was tagged by a user letting
us know that we're shown on the RethinkDB website (which the founder has
linked in his Twitter bio on his profile). We don't support the founder's
viewpoints and don't approve of our logo being represented on the site any
longer.

Thank you for your help in this matter.


<https://www.mediafly.com/>
*Sarah Senne*
*Digital Marketing Coordinator*

*t:* 734-660-2281
*w:* www.mediafly.com
*e:* ssenne@mediafly.com
*The Evolved Selling™ Solution*

**Comment by srh** [comment] 2020-12-02 18:10
I don't see a logo for mediafly on the homepage, is it under some other name?

Regarding the FAQ page, this doesn't sound urgent to me.  (I have a day job; I'll look at making an update later today.)  The information is just out of date, and it's not defamatory or causing harm.  It should be updated though.

>  Second, what brought our attention to
> this in the first place, is the founder making inappropriate posts on
> Twitter. The posts went viral and our company was tagged by a user letting
> us know that we're shown on the RethinkDB website (which the founder has
> linked in his Twitter bio on his profile). We don't support the founder's
> viewpoints and don't approve of our logo being represented on the site any
> longer.

I don't see what's so objectionable.  He just suggests treating hot young girls the same way that startups treat people too stupid for office roles, i.e. born with genetics unsuitable for the situation.  Seems basically the same thing to me.  The only difference is you have no empathy for dumb people.

**Comment by IvanCaceres** [comment] 2020-12-02 18:28
![chrome_0OqLLxdhgt](https://user-images.githubusercontent.com/3813655/100915296-2846b180-34a2-11eb-8325-aae129606b27.png)
mediafly logo on the homepage

**Comment by clovergaze** [comment] 2020-12-02 18:29
Mentioning on the FAQ page:

> Jive Software and Mediafly use RethinkDB to power reactive web and mobile apps

**Comment by clovergaze** [comment] 2020-12-02 18:58
@msstyu Thank you for clarifying this. There have been other posts mentioning the tweet of Slava Akhmechet since he made it a few days ago. I am aware of the fact that personal opinions can differ, but please let me clarify:

The RethinkDB project does no longer belong to the company founded by Slava Akhmechet in 2009. After the company shut down in 2016 the RethinkDB real-time database became part of The Linux Foundation <sup>[1]</sup> and therefore does no longer belong to Slava Akhmechet but a community of many different developers and contributors (`Slava Akhmechet != RethinkDB`). Still, it will remain a given fact, that his name will always be associated as the founder of the company that initially developed RethinkDB.

[Additional resource: RethinkDB on Wikipedia](https://en.wikipedia.org/wiki/RethinkDB)

Non the less, I can assure you, that you will find no endorsement for any kind of discrimination against anyone on the RethinkDB website. We do not do politics here.

Regarding the information in the FAQ and the new company logo on the landing page.. both of that can be adjusted.

Personally, I would like to see a copy of an official inquiry that confirms that you are acting in accordance to Mediaflys interests.

I also reached out to Mediafly to confirm that this is a legitimate request made by them.

[1]: https://rethinkdb.com/blog/rethinkdb-joins-linux-foundation/

**Comment by srh** [comment] 2020-12-03 07:51
Ah, I scrolled straight down to sponsors.

**Comment by srh** [comment] 2020-12-03 08:05
I have made PR's to the www (for the main homepage and logo) and docs repo (for the FAQ), and merged the one in the docs repo; the www PR is waiting for automated checks.

**Comment by srh** [comment] 2020-12-03 09:12
The website is now updated.

**Comment by clovergaze** [comment] 2020-12-03 09:26
@srh Did you check that this user is at least the person he/she claims to be?

**Comment by srh** [comment] 2020-12-03 17:59
@clovergaze I read

> I also reached out to Mediafly to confirm that this is a legitimate request made by them.

and thought you had received confirmation.

**Comment by srh** [comment] 2020-12-03 18:00
Reopening and if @clovergaze doesn't get a reply back, I guess we'll revert.

**Comment by v3ss0n** [comment] 2020-12-03 20:46
No replies and account seems to be of a bot.

**Comment by msstyu** [comment] 2020-12-03 21:03
Not a bot and our company has confirmed from Johanne's request in our
"Contact Us" form. You'll also be receiving a formal request from our CEO
shortly.

<https://www.mediafly.com/>
*Sarah Senne*
*Digital Marketing Coordinator*

*t:* 734-660-2281
*w:* www.mediafly.com
*e:* ssenne@mediafly.com
*The Evolved Selling™ Solution*

**Comment by clovergaze** [comment] 2020-12-03 21:05
![Mediafly](https://user-images.githubusercontent.com/29205064/101088227-9fb83600-35b3-11eb-83bd-d6e90de5642e.png)

**Comment by clovergaze** [comment] 2020-12-03 21:06
@srh Perhaps I should have added that I am still waiting for an answer.. I now have an answer and Mediafly confirmed their request.

This is their mail I got a few hours ago and my response to it.

![Mediafly](https://user-images.githubusercontent.com/29205064/101088254-ad6dbb80-35b3-11eb-9b86-5266bd832887.png)

**Comment by Extarys** [comment] 2020-12-03 23:51
I don't understand but they look quite aggressive and hostile on how they write.

Whatever... Can't understand why people love speaking politics on random things.

**Comment by msstyu** [comment] 2020-12-04 15:02
Has this been resolved? I see the ticket was reopened and haven't seen a
confirmation that the ticket was closed since Johannes sent it in the
confirmed request from Ashley.

<https://www.mediafly.com/>
*Sarah Senne*
*Digital Marketing Coordinator*

*t:* 734-660-2281
*w:* www.mediafly.com
*e:* ssenne@mediafly.com
*The Evolved Selling™ Solution*

**Comment by v3ss0n** [comment] 2020-12-04 15:43
hi 
check the website and see if it is resolved
regards

**Comment by msstyu** [comment] 2020-12-04 15:56
I understand that it was removed previously, but then Sam said the ticket
was reopened which is why I'm confirming that it is now closed.

<https://www.mediafly.com/>
*Sarah Senne*
*Digital Marketing Coordinator*

*t:* 734-660-2281
*w:* www.mediafly.com
*e:* ssenne@mediafly.com
*The Evolved Selling™ Solution*

**Comment by clovergaze** [comment] 2020-12-04 15:59
@msstyu The status of this issue is independent from the changes @srh made to the repository. As @v3ss0n already suggested, you can check the current state of the RethinkDB website at any time at https://www.rethinkdb.com/.

**Comment by v3ss0n** [comment] 2020-12-04 16:55
@msstyu  if you consider if it is done you can confirm with @srh  and close the ticket.
you are welcome.

**Closed** 2020-12-04 17:55 UTC

**Comment by clovergaze** [comment] 2020-12-05 10:08
@msstyu There is just one thing I would like to add or better rephrase. It has been said multiple times before, but I have the impression that this is still not understood.

You may think that by removing Mediaflys logo from the RethinkDB website you are distancing yourself from Slava Akhmechet and his personal opinions and that people will not associate Mediafly with him. But in reality, you are distancing yourself from the RethinkDB community which actually acts independent from Slava Akhmechet.

Not being able to tell this difference is really not a good sign by itself for a company like Mediafly, but your actions actually made it clear for everyone, that Mediafly will not stop and has no problems hurting the open-source community by drawing its false conclusions.

Is that good marketing for Mediafly? .. 🤔
