### ISSUE TITLE
ReQL: two simple question

### ISSUE THREAD

**Issue by AnotherGoogleFans** [rethinkdb/rethinkdb#6089] opened 2016-09-01 10:53 UTC
The one is how to use index in filter.
for example, a query like this:
r.db("db").table("table").filter({"keyword":"facebook"})
but I have index in field "keyword". I tried like this but not work:
r.db("db").table("table").filter({"keyword", {index:"facebook"})

The other question is how to query the erliest date.
for example, in my table, there is a field named "createdAt" and another field named "name".
how can I find the a data, for example, name is "smith" and createdAt is the ealiest or latest?

**Comment by chrisvariety** [comment] 2016-09-01 11:35
You would want to use `getAll` instead of `filter`. For example:

the index: `r.db("db").table("table").indexCreate("keyword")`
the getAll: `r.db("db").table("table").getAll("facebook", {index: "keyword"})`

To query the earliest date, you can do something like this:

`r.db("db").table("table").filter({"name":"smith"}).orderBy(r.asc("createdAt")).nth(0).default(null)`

To do so in a more efficient manner (using an index), if you aren't expecting many rows matching "smith", you can do a `getAll` with an index on `name` alone, followed by an un-indexed orderBy, e.g. `r.db("db").table("table").getAll("smith", {index: "name"}).orderBy(r.asc("createdAt")).nth(0).default(null)` (you'll have to create the "name" index)

It's also possible to create an index on both fields, though you'll probably want to test the performance of this as compared to the above on your actual data.

```js
r.db("db").table("table").indexCreate("nameAndCreatedAt", function(item) {
  return [item("name"), item("createdAt")];
});
```

Then you can use the index like so:

`r.db("db").table("table").between(["smith", r.minval], ["smith", r.maxval], {index: "nameAndCreatedAt"}).orderBy({index: r.asc("nameAndCreatedAt")}).nth(0).default(null)`

**Comment by danielmewes** [comment] 2016-09-01 18:59
Closing since it's not a bug or feature request. @AnotherGoogleFans you might want to check out our Slack channel at https://rethinkdb.slack.com . Go to http://slack.rethinkdb.com to get an automated invitation.

@chrisvariety has given an excellent answer to your questions.

**Closed by danielmewes** 2016-09-01 18:59 UTC

**Comment by AnotherGoogleFans** [comment] 2016-09-07 10:00
@chrisvariety Thank you very much.  Your answer helps me a lot.
