### ISSUE TITLE
JS driver - Emit a "end" event at the end of a cursor

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#2577] opened 2014-06-19 21:56 UTC
I'll do it when I get a few minutes.

Putting in 1.13.x,

**Comment by danielmewes** [comment] 2015-02-23 21:24
Assigned @deontologician

**Comment by deontologician** [comment] 2015-02-23 23:23
Is this a bug / listener leak, or is this a cleaner way of doing something we already do? @neumino 
If it's a cleanliness thing, I think we should wait until #3771 is decided.

**Comment by danielmewes** [comment] 2015-02-23 23:45
I think it's just to make some use cases easier. I thought it might be really easy to do, but I don't know if that's true.
If it's a bit more difficult it definitely makes sense to wait for #3771.

**Comment by deontologician** [comment] 2015-02-23 23:46
I have a guess about how to do it, but I'd want to understand the repercussions well and write tests, and that would be wasted effort if we throw it all out next release

**Comment by deontologician** [comment] 2015-02-23 23:48
moving to 2.1 for now, unless there's a compelling reason not to. I confirmed with @neumino on irc it's not a memory leak issue currently

**Comment by Amberlamps** [comment] 2015-07-27 20:30
I find cursors emitting an `end` event when they are done extremely useful. I mean `cursor.each(function(err, row) {}, function() {});` gets the job done, but I think people as myself are more familiar with the `data`, `error`, `end` pattern.

**Comment by danielmewes** [comment] 2015-11-02 20:18
Since we aren't adopting rethinkdbdash in the next few versions, we should add this to our own driver.

**Comment by deontologician** [comment] 2015-11-02 20:20
That sounds good to me, I think when I commented before it seemed like it might happen soon.

**Comment by ember-max** [comment] 2015-11-04 17:06
(posted on #3702 as well, apologies if this is redundant but they seem related)

I would like to be able to close/cancel a cursor "externally," i.e., by some means other than the callback which is supplied directly, ideally without even relying on my callback having been called at all. There is obviously `cursor.close()`, but that doesn't seem to invoke the cursor's `onFinishedCallback`, and I'm worried that something isn't getting properly cleaned up. Ensuring that `cursor.close()` invoked any kind of `done` event, as well as calling any supplied `onFinishedCallback` would work for me, assuming I'm going about this the right way.

**Comment by marshall007** [comment] 2015-11-05 02:32
@ember-max I just tested this myself and I see what you're saying. It appears that there is no way to get out of a `cursor.each()` iteration once you close the cursor since the `callback` is not called with an error *and* the optional `onFinishedCallback` is never called. It does work if you close the underlying connection, though.

Even if the `cursor` fired an `end` event it wouldn't help because you can't use the `EventEmitter` and iterator APIs simultaneously.

**Comment by danielmewes** [comment] 2015-11-09 19:40
@ember-max I opened https://github.com/rethinkdb/rethinkdb/issues/5056 to discuss the `aborted` event.

**Comment by nighelles** [comment] 2016-02-24 23:40
@danielmewes I think this is closed by #5056?

**Comment by danielmewes** [comment] 2016-02-25 00:47
@nighelles Yep.

**Closed by danielmewes** 2016-02-25 00:47 UTC
Labels: JavaScript / Coffee
