### ISSUE TITLE
Inconsistent behavior when setting shards between the UI and the python driver

### ISSUE THREAD

**Issue by r-marques** [rethinkdb/rethinkdb#5867] opened 2016-06-17 13:06 UTC
__Setup__
- RethinkDB 2.3.4
- Python driver 2.3.0.post4
- Single rethinkdb node

If I try to set the number of shards to a value greater then the number of servers on the cluster the UI doesn't let me and gives a message saying: "A table may not have more shards than there are servers. Currently you have 1 servers available for this table."

But it is still possible to change the number of shards using the rethinkdb python driver:
```python
r.db('test').table('test').reconfigure(shards=10, replicas=1).run()
```

**Comment by larkost** [comment] 2016-06-17 17:35
This is a case of our WebUI not-too-subtly guiding you to do the right thing. It is legal to have multiple shards on the same server (we call it oversharding), it is just not very useful since they get stored in the same file anyways. So there is no benefit to doing so, and we want to generally do the right thing in the WebUI.

Since the `reconfigure` command is a little lower-level, we allow it to do more things, including ones that don't make as much sense (at least for the system as running). One place where this might make sense is in setting up a table, and then adding the servers to handle that configuration.

I am going to close this as `not a bug`, but you can ask more questions, or give feedback here if you would like.

**Closed by larkost** 2016-06-17 17:35 UTC
