### ISSUE TITLE
Silent data loss on metablock corruptions

### ISSUE THREAD

**Issue by ramanala** [rethinkdb/rethinkdb#6034] opened 2016-08-05 16:14 UTC
Looking at the code in metablock_manager.hpp and metablock_manager.cc, I believe that rethinkdb does have checksums for metablocks. If a metablock is corrupted due to problems in lower layers such as bugs in FS, disk errors etc, there is a **silent user data loss**. I added some logs around check_crc and compute_own_crc functions in metablock_manager.hpp and noticed that even if the checksums do not match, there is no error given to the user (or in the logs), and I believe there is no recovery for such checksum mismatches. 

I do not have much knowledge about the on disk format of RethinkDB. But, my (wrong?) guess is that the metablocks hold pointers to the actual data blocks.  When a metablock is read, a CRC check is performed. If the checksums do not match, the data pointed by that corrupted metablock becomes **silently inaccessible**. My understanding is that, in its current state, RethinkDB can reliably **detect** corruption in metablocks but **cannot recover** from them. Is that right? Given that metablocks do have checksums and so corruptions can be detected, and that the user data is still intact, can RethinkDB do something to recover the metablock (especially in a replicated setting?). The same problem occurs even in a replicated setting when the leader's metablock is corrupted.

**Comment by danielmewes** [comment] 2016-08-05 17:35
Hi @ramanala. Interesting question.

The checksum in the metablock is actually *not* to protect against corruption caused by disk or file-system errors. Its intended function is much simpler: Recovery after a crash.

If you unplug power on your server while RethinkDB is in the middle of writing the metablock, RethinkDB needs to be able to detect this situation the next time you start it. It uses the checksum to verify that the latest metablock has been fully written. If it finds that it has not been fully written, it simply uses the metablock before that and verifies its checksum, and so on until it finds a valid metablock. Normally only one new metablock can be written at a time, so the second most recent one will be guaranteed to be valid.

This does not cause silent data loss, because RethinkDB only acknowledges a write *after* the corresponding metablock has been written to disk. So it's always valid to skip to the next-older block, if the latest one turns out to be incomplete.

On many real systems, hard drives guarantee atomic writes of individual blocks. However we decided to not rely on that, as it depends on a bunch of assumptions about alignment etc.

RethinkDB overall relies on the storage to not exhibit silent data corruption, and on the operating system, file system and hard drives to guarantee persistence after an `fsync`.

The checksums in the metablocks are therefore not a corruption detection feature, and would be highly useless at that as well (since corruption is much more likely to happen in one of the other data blocks).

Hope this helps. I'm going to close this issue since it's more of a question than a bug or feature request. You're welcome to ask more questions in this thread though.

**Closed by danielmewes** 2016-08-05 17:35 UTC

**Comment by ramanala** [comment] 2016-08-05 18:01
@danielmewes : Thank you for your reply!

I have previously tested RethinkDB using our tool-set with respect to crashes (and did **not** discover any bugs wrt crashes). I think I somewhat understand the crash-consistency protocol of RethinkDB. If I am not wrong,  an acknowledgement to user is given only after writing the data block(s), fsync-ing it, then updating the metablock to point to the new changes, fsync-ing it. Something like below:

write(data_part) -- usually an append 
fsync(data_part) // or fdatasync
write(metablock) -- usually an inplace write
fsync(metablock) // or fdatasync
// ok to give ack here.

I see your point that you can detect partially written metablocks using checksum mismatches. I called the issue as "silent data loss" because, the user had been acknowledged after the above sequence of events completed and at a later point, the latest metablock is **corrupted** (not due to a crash) and so she cannot access the data -- i.e, the data seems to have silently disappeared.

I see your point that RethinkDB does expect that the storage layers beneath it won't return corrupt data silently (which may not be necessarily true). I have filed an older issue (5925) with respect to this and that was marked as "will be fixed in a future milestone". I understand that this fix is not-so-simple as it involves supporting older older on-disk formats and so on. Until then, **Would it be possible to explicitly document the expectations of RethinkDB from lower layers with respect to data reliability?**

**Comment by danielmewes** [comment] 2016-08-05 18:07
@ramanala Your understanding is correct.

Note that unless it's caused by software bugs or RAM corruption before being written to disk (which checksums don't fully protect against either), corruption of data on disk is rarely silent because disk drives (and I assume SSDs too) use their own checksums and a read will fail if the drive can't get a consistent read.

Documenting this assumption is a good idea. I'll open an issue in our documentation repository ( https://github.com/rethinkdb/docs/issues ). I think we can add it to our architecture FAQ at https://www.rethinkdb.com/docs/architecture/#data-storage .

**Comment by ramanala** [comment] 2016-08-05 18:10
@danielmewes : Thank you. Opening a doc issue and adding it in arch FAQ sounds great! Thanks again.

**Comment by danielmewes** [comment] 2016-08-05 18:13
Also you're raising a great point with respect to the handling of metadata checksums for https://github.com/rethinkdb/rethinkdb/issues/5925 .

Because checksum failures on the latest metablock are to a degree expected after a crash, it would be hard to tell whether this is due to a data corruption (which after #5925 we generally would be able to catch), or due to being interrupted in the middle of a write.
In the former case we would want to tell the user that the data was corrupted (and probably terminate RethinkDB, since the data loss might cause us to violate Raft invariants among others and could cause havoc and further data loss on other - so far unaffected - replicas in the cluster).
In the latter case we would want to silently read the next metablock and continue.

I'm not sure if we can fully solve this ambiguity. It might be that the best we can do is print a warning if the latest metablock is not valid (again, this only really makes sense after #5925).
