### ISSUE TITLE
crash: error: Error in src/rdb_protocol/datum.cc at line 1475

### ISSUE THREAD

**Issue by jodagm** [rethinkdb/rethinkdb#5455] opened 2016-02-28 10:30 UTC
Hi,

We started getting these crashes after upgrading to 2.2.5. This happens when we are running our automated tests against local rethinkdb:

```
Running rethinkdb 2.2.5~0wily (GCC 5.2.1)...
Running on Linux 4.2.0-30-generic x86_64
Loading data from directory /home/jonathan/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, 127.0.1.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "jonathan_wa3" 231ce904-2cc7-4591-bfc9-e954a2ad2174
Version: rethinkdb 2.2.5~0wily (GCC 5.2.1)
error: Error in src/rdb_protocol/datum.cc at line 1475:
error: Unreachable code: 
error: Backtrace:
addr2line: 'rethinkdb': No such file
addr2line: 'rethinkdb': No such file
error: Sun Feb 28 10:15:48 2016
       
       1 [0xad99da]: backtrace_t::backtrace_t() at 0xad99da (rethinkdb)
       2 [0xad9eba]: format_backtrace[abi:cxx11](bool) at 0xad9eba (rethinkdb)
       3 [0xd66626]: report_fatal_error(char const*, int, char const*, ...) at 0xd66626 (rethinkdb)
       4 [0x92706e]: void ql::datum_t::write_json_unchecked_stack<rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::RAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::RAllocator> >(rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::RAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::RAllocator>*) const at 0x92706e (rethinkdb)
       5 [0x927276]: void ql::datum_t::write_json<rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::RAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::RAllocator> >(rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::RAllocator>, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::RAllocator>*) const at 0x927276 (rethinkdb)
       6 [0xacd0e0]: write_response_internal(ql::response_t*, rapidjson::GenericStringBuffer<rapidjson::UTF8<char>, rapidjson::RAllocator>*, bool) at 0xacd0e0 (rethinkdb)
       7 [0xacefee]: json_protocol_t::send_response(ql::response_t*, long, linux_tcp_conn_t*, signal_t*) at 0xacefee (rethinkdb)
       8 [0xad5351]: void save_exception<void query_server_t::connection_loop<json_protocol_t>(linux_tcp_conn_t*, unsigned long, ql::query_cache_t*, signal_t*)::{lambda()#1}::operator()() const::{lambda()#1}>(std::__exception_ptr::exception_ptr*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, cond_t*, void query_server_t::connection_loop<json_protocol_t>(linux_tcp_conn_t*, unsigned long, ql::query_cache_t*, signal_t*)::{lambda()#1}::operator()() const::{lambda()#1}&&) at 0xad5351 (rethinkdb)
       9 [0xad5d2d]: void query_server_t::connection_loop<json_protocol_t>(linux_tcp_conn_t*, unsigned long, ql::query_cache_t*, signal_t*)::{lambda()#1}::operator()() const at 0xad5d2d (rethinkdb)
       10 [0x9e7102]: coro_t::run() at 0x9e7102 (rethinkdb)
error: Exiting.
Trace/breakpoint trap (core dumped)

```

this is what our app shows:
```
Message:
    Connection is closed in:
r.table("offers").getAll("Organization1", {"index": "channel_publisher"}).filter(r.row("status").eq("active").and(r.row("payout").ge(0), r.row("currency").eq("USD"), r.row("product")("productType").eq("Mobile App"), r.row("redirectUrlStatus").eq("valid"),  r.row("segment")("os").contains("IOS").or(r.row("segment")("os").contains("ANDROID")), r.row("product")("productId").eq("N/A").not(),r.row("subscription")("status").eq("inactive").or(r.row("subscription")("status").eq("deleted")).not(), r.branch(r.row.hasFields({"expirationTimestamp": true}), r.now().sub(r.row("expirationTimestamp")).le(0), true), r.branch(r.row.hasFields({"endDate": true}), r.now().sub(r.row("endDate")).le(0), true)).or().and()).changes({"includeInitial": true})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Details:
    msg: Connection is closed.
    frames: 
    domain: [object Object]
    domainThrown: true

```

This has not happened on our production server and it could be something related to our tests. we do start and stop changefeeds and delete tables as part of each test, but we did not experience this crash before.

Thanks,
Jonathan

**Comment by tatsujin1** [comment] 2016-02-29 07:29
Seems to be the same as my problem, however a newer version: #5438.
"Glad" I'm not the only one, because we have so far _no idea_ why this is happening.

**Comment by tatsujin1** [comment] 2016-02-29 14:13
It seems that this is very easy to reproduce with version 2.2.5.
I've made a small test that guarantees a crash.
However, in my case (#5438, version 2.2.3) I've yet to reproduce :-(

**Comment by tatsujin1** [comment] 2016-02-29 16:14
Success! I've now reproduced the crash with v2.2.3 as well.
Hopefully it's the same bug that crashes both versions (the stack trace is almost identical), but anyway here are the variants that crashes v2.2.3:
**test-modify-5438.py:**
```
#! /usr/bin/env python3

import rethinkdb as r
import random
import time

r.connect().repl()

db_name = 'test_db'
table_name = 'test_table'

if db_name not in r.db_list().run():
	r.db_create(db_name).run()

if table_name not in r.db(db_name).table_list().run():
	r.db(db_name).table_create(table_name).run()

table = r.db(db_name).table(table_name)
table.config().update({ 'durability': 'soft' }).run()

print('cleaning table...')
table.delete().run(noreply=True)

indexes = [	'index' ]
existing_indexes = table.index_list().run()
for index in [index for index in indexes if index not in existing_indexes]:
	table.index_create(idx).run()

max_id = 5000
print('inserting...', max_id)
for doc_id in range(1, max_id + 1):
	table.insert({
		'id': doc_id,
		'index': random.randint(1, 10),
		'value1': random.randint(1, 10),
		'value2': random.randint(1, 10),
		'value3': random.randint(1, 10),
	}).run(noreply=True)


while True:
	time.sleep(0.05)

	doc_id = random.randint(1, max_id)

	existing = table.get(doc_id).run()
	if existing:
		if random.random() > 0.2:
			table.get(doc_id).update({
				'index': random.randint(1, 10),
				'value1': random.randint(1, 10),
				'value2': random.randint(1, 10),
				'value3': random.randint(1, 10),
			}).run(noreply=True)
			print('   up   :', doc_id)

		else:
			table.get(doc_id).delete().run(noreply=True)
			print('     del:', doc_id)

	else:
		table.insert({
			'id': doc_id,
			'index': random.randint(1, 10),
			'value1': random.randint(1, 10),
			'value2': random.randint(1, 10),
			'value3': random.randint(1, 10),
		}).run(noreply=True)
		print('ins     :', doc_id)
```
It seems that it has to do with the `update()` part. Commenting out the value1/2/3 fields from the update averts the crash.

And the nodejs script:
**test-5438.js:**
```
'use strict';

var r = require('rethinkdb');

var query = r.db('test_db').table('test_table')
	.getAll(1, 2, 3, 4, 5, { index: 'index' })
	.filter(r.row('value1').gt(2))
	.filter(r.row('value2').lt(8))
	.filter(r.row('value3').gt(2))

r.connect(function(err, conn) {
	var first = true;
	console.time('first message');
	query.changes().run(conn, function(err, cursor) {
		cursor.on('data', function(item) {
			if(first)
			{
				console.timeEnd('first message');
				first = false;
			}
			else
				process.stdout.write('.');
		});
		cursor.on('error', function(err) {
			console.log('ERROR: ' + err.message);
		});
	});
});
```

**Comment by danielmewes** [comment] 2016-02-29 20:25
Thanks for the bug report @jodagm . That information is very helpful. I'm closing this as a duplicate of #5438, since they appear to be the same. Please follow the other issue for updates.

**Closed by danielmewes** 2016-02-29 20:25 UTC
