### ISSUE TITLE
Feature Request: row expiration

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#3772] opened 2015-02-12 22:28 UTC
Something like r.table("foo").get(1).expires(seconds) would be super cool

**Comment by danielmewes** [comment] 2015-02-12 22:37
This is a duplicate of https://github.com/rethinkdb/rethinkdb/issues/746 . To be honest I don't think we're going to get to this very soon, but it's on the list of course.

**Closed by danielmewes** 2015-02-12 22:37 UTC
