### ISSUE TITLE
Logs table can't parse backtraces

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3632] opened 2015-01-21 23:20 UTC
On a brand new cluster, I'm getting the following error:

```
Problem with reading log file on server `eos_3144`: cannot parse log message (8) in:
r.db("rethinkdb").table("logs", {identifierFormat: "uuid"}).orderBy({index: r.desc("id")}).limit(5).map(function(var_23) { return var_23.merge({server: r.db("rethinkdb").table("server_config").get(var_23("server"))("name"), server_id: var_23("server")}); })
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                        
```

The only oddity in my logs is a bunch of backtraces currently.

**Comment by danielmewes** [comment] 2015-01-21 23:35
My suspicion is that we're missing some escaping.

@deontologician Do you still have the log file from the server? Could you post it here?

**Comment by deontologician** [comment] 2015-01-21 23:38
blargh, I truncated it so I could get it running again. It's easy to replicate though. try creating 400 tables in a loop and you'll get a backtrace. I'll try it a bit later

**Comment by danielmewes** [comment] 2015-01-22 00:49
Just tested with a different backtrace and it worked fine. Must be something about specific backtraces.
I will try to get one the same way you did next.

**Comment by danielmewes** [comment] 2015-01-22 03:56
Actually I bet the problem was that this specific `rassert` has a newline at the end of its message...

**Comment by danielmewes** [comment] 2015-01-22 04:10
Forget that, the log writer should strip those newlines...

**Comment by danielmewes** [comment] 2015-01-22 05:42
Can't reproduce even when making it trigger the assert the way you described. Not sure what happened. Moving to 1.16-polish unless we can get it again.
I think the log parsing code actually hasn't changed for ReQL admin (@timmaxw ?), so if there is a problem now it's likely that there already had been a problem before and it didn't seem to happen very often.

**Comment by deontologician** [comment] 2015-01-22 20:14
It's possible I corrupted the file. If you can't reproduce it, we should
just close it

**Comment by timmaxw** [comment] 2015-01-23 05:59
There were some changes to the logs logic for ReQL admin, but I can't think of any that would be related to this bug.

**Closed** 2015-01-23 18:59 UTC
Labels: tp:bug
