### ISSUE TITLE
point changefeed return is inconsistent with table changefeeds

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3564] opened 2015-01-14 00:32 UTC
The return of a point changefeed (`r.table('a').get(1).changes()`) is just the new row, whereas the return of `table.changes()` is `{'old_val':, 'new_val':}`. I am not sure it is wrong, but it feels inconsistent, and I wanted to start a conversation about it.

**Comment by danielmewes** [comment] 2015-01-14 01:13
This was by design, see https://github.com/rethinkdb/rethinkdb/issues/1118#issuecomment-47066176 and following. Doesn't mean we can't change it of course.

Pinging @mlucy and @coffeemug

**Comment by mlucy** [comment] 2015-01-15 03:48
I'm open to re-considering this.  What do you think @coffeemug?

**Comment by timmaxw** [comment] 2015-01-15 04:01
One minor advantage of the `{old_val: _, new_val: _}` format is that it gives us more flexibility to add additional fields or event types later. For example, we've discussed adding `{error: _}` events, and in #3471 we discussed adding a `timestamp` field. Neither of those is necessary for point changefeeds, but it makes me think that we might later want to add a field or event type that does make sense for point changefeeds.

**Comment by coffeemug** [comment] 2015-01-15 19:31
I wouldn't change it this late in the release cycle. We've thought it through quite extensively. That's not to say that the decision was correct, just that I'd wait to release 1.16, get user feedback, and then reconsider if necessary. I think we're going to get *a lot* of new knowledge about the feeds API after release, so I wouldn't design new things (or redesign old things) until we hear what users have to say.

**Comment by mlucy** [comment] 2015-01-15 19:50
I think I agree.  If people find it confusing that there are 2 different return types, I think we should change it.

**Comment by mlucy** [comment] 2015-01-15 19:51
@danielmewes: can we move this to subsequent with the scope being "reconsider this when we have more information after release"?

**Comment by danielmewes** [comment] 2015-01-15 20:13
Done.

**Comment by mlucy** [comment] 2015-01-15 23:05
Actually, I'd like to go back to this because of https://github.com/rethinkdb/rethinkdb/issues/3570 .  We don't have a good way to report errors on non-squashing point changefeeds unless we change the format to be consistent with range changefeeds.  Between that and the possible desire to add timestamps, I think maybe we should just do this before 1.16.

@coffeemug -- how strongly are you opposed to talking about this so close to the deadling?

**Comment by mlucy** [comment] 2015-01-15 23:07
Moving back to 1.16 just so I don't forget about it.

**Comment by danielmewes** [comment] 2015-01-15 23:35
I personally think we should make all changefeeds consistent in their return format.

Code-wise it should be a reasonably easy change I imagine?

**Comment by mlucy** [comment] 2015-01-15 23:37
Yeah, it's completely trivial code-wise.

**Comment by danielmewes** [comment] 2015-01-16 00:45
We're changing this to the `{old_val: ..., new_val: ...}` format.

**Comment by AtnNn** [comment] 2015-01-16 00:48
Having an `old_val` field seems redundant for point changefeeds. Perhaps it could be omitted.

**Comment by mlucy** [comment] 2015-01-16 01:06
In CR 2486

**Comment by mlucy** [comment] 2015-01-20 23:10
This is in `mlucy_cfeed_tests` and will be merged into both 1.16 and 1.16.x when that branch is.

**Closed by mlucy** 2015-01-20 23:10 UTC
Labels: tp:review
