### ISSUE TITLE
Investigate .default() performance

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#1232] opened 2013-08-02 22:41 UTC
There are about 90k records in the table `test`.

This script runs in about 4 seconds

``` py
for i in xrange(10):
    r.db('test').table('test').grouped_map_reduce(
        lambda doc: doc["field"], # doc["field"] exists and always maps to the same value
        lambda doc: doc['rand'],
        lambda left, right:
            left + right
    ).run()
end = time.time()
```

While this one needs about 30 seconds

``` py
for i in xrange(10):
    r.db('test').table('test').grouped_map_reduce(
        lambda doc: doc["non_existing_field"].default(None),
        lambda doc: doc['rand'],
        lambda left, right:
            left + right
    ).run()
end = time.time()
```

**Comment by thelinuxlich** [comment] 2018-03-12 21:47
@srh just mentioning there was effort to optimize this: #6454

**Comment by srh** [comment] 2018-03-26 01:42
Whoops.

**Comment by srh** [comment] 2018-03-30 04:08
Closing as dupe of #4271.

**Closed by srh** 2018-03-30 04:08 UTC
Labels: tp:performance
