### ISSUE TITLE
JS driver - args is not defined

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#4239] opened 2015-05-17 18:39 UTC
There is a reference to `args` that is not defined in `cursor.js` for the EventEmitter's methods like `emit`, `once` etc.

**Comment by danielmewes** [comment] 2015-05-17 22:29
Hi @neumino , this one looks like a duplicate of https://github.com/rethinkdb/rethinkdb/issues/4192 . We'll put out 2.0.2 with the fix soon.

**Closed** 2015-05-17 22:29 UTC
